### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: statusFind is not a function

### ISSUE THREAD

**Issue by brainwares** [orkestral/venom#1]
Hi,
Trying to create instance with parameter getting error:
UnhandledPromiseRejectionWarning: TypeError: statusFind is not a function
at Object.<anonymous> (/../node_modules/venom-bot/dist/controllers/initializer.js:168:25)

**Comment by s2click** [comment]
he gets in scope now 2 callback

``` javascript
 venom.create("session-develop").then((client) => {
			  start(client)
			}).catch(erro => console.log(erro)) OR
```

 ``` javascript
venom.create("session-develop", ("statusFind") =>{
console.log(statusFind)
}).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```
 OR

 ```javascript
venom.create("session-name", (base64Qr, asciiQR) => {
		
			console.log(asciiQR);
			
		   exportQR(base64Qr, "documentos/qrcode.png");

		  }, (statusFind) =>{

			  console.log(statusFind)

		  }).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

**Comment by brainwares** [comment]
Tried using this sample
-----------------------------
create('sessionName', qrCallback, {
  headless: true, // Headless chrome
  devtools: false, // Open devtools by default
  useChrome: true, // If false will use Chromium instance
  debug: false, // Opens a debug session
  logQR: true // Logs QR automatically in terminal
  browserArgs: [''] // Parameters to be added into the chrome browser instance
  refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
});

**Comment by orkestral** [comment]
Hello! 5 options:

``` javascript
   venom.create("session-name", {
			headless: true, // Headless chrome
			devtools: false, // Open devtools by default
			useChrome: true, // If false will use Chromium instance
			debug: false, // Opens a debug session
			logQR: true, // Logs QR automatically in terminal
			browserArgs: [''], // Parameters to be added into the chrome browser instance
			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
		  }).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

 ``` javascript
venom.create("session-develop", (base64Qr, asciiQR) => {
			// To log the QR in the terminal
			console.log(asciiQR);
			// To write it somewhere else in a file
		   exportQR(base64Qr, "documentos/file.png");
		  }, (statusFind) =>{
			  console.log(statusFind+'\n\n')
		  },{
			headless: true, // Headless chrome
			devtools: false, // Open devtools by default
			useChrome: true, // If false will use Chromium instance
			debug: false, // Opens a debug session
			logQR: true, // Logs QR automatically in terminal
			browserArgs: [''], // Parameters to be added into the chrome browser instance
			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
		  }).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

``` javascript
 venom.create("session-develop", (base64Qr, asciiQR) => {
			// To log the QR in the terminal
			console.log(asciiQR);
			// To write it somewhere else in a file
		   exportQR(base64Qr, "documentos/file.png");
		  }).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

``` javascript
 venom.create("session-develop",() =>{}, (statusFind) =>{
			  console.log(statusFind+'\n\n')
		  }).then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

``` javascript
 venom.create("session-develop").then((client) => {
			  start(client)
			}).catch(erro => console.log(erro))
```

**Comment by orkestral** [comment]
Updated documentation, Thank You!

**Comment by brainwares** [comment]
> Hello! 5 options:
> 
> ```js
>    venom.create("session-name", {
> 			headless: true, // Headless chrome
> 			devtools: false, // Open devtools by default
> 			useChrome: true, // If false will use Chromium instance
> 			debug: false, // Opens a debug session
> 			logQR: true, // Logs QR automatically in terminal
> 			browserArgs: [''], // Parameters to be added into the chrome browser instance
> 			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> 		  }).then((client) => {
> 			  start(client)
> 			}).catch(erro => console.log(erro))
> ```
> 
This is not working. Error result:
TypeError: catchQR is not a function
    at SafeSubscriber._next (/.../node_modules/venom-bot/dist/controllers/initializer.js:219:13)

> ```js
> venom.create("session-develop", (base64Qr, asciiQR) => {
>    		// To log the QR in the terminal
>    		console.log(asciiQR);
>    		// To write it somewhere else in a file
>    	   exportQR(base64Qr, "documentos/file.png");
>    	  }, (statusFind) =>{
>    		  console.log(statusFind+'\n\n')
>    	  },{
>    		headless: true, // Headless chrome
>    		devtools: false, // Open devtools by default
>    		useChrome: true, // If false will use Chromium instance
>    		debug: false, // Opens a debug session
>    		logQR: true, // Logs QR automatically in terminal
>    		browserArgs: [''], // Parameters to be added into the chrome browser instance
>    		refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
>    	  }).then((client) => {
>    		  start(client)
>    		}).catch(erro => console.log(erro))
> ```
> 
Not working also
ReferenceError: exportQR is not defined
> ```js
>  venom.create("session-develop", (base64Qr, asciiQR) => {
> 			// To log the QR in the terminal
> 			console.log(asciiQR);
> 			// To write it somewhere else in a file
> 		   exportQR(base64Qr, "documentos/file.png");
> 		  }).then((client) => {
> 			  start(client)
> 			}).catch(erro => console.log(erro))
> ```
> 
Same Error...
Not working also
ReferenceError: exportQR is not defined

> ```js
>  venom.create("session-develop",() =>{}, (statusFind) =>{
> 			  console.log(statusFind+'\n\n')
> 		  }).then((client) => {
> 			  start(client)
> 			}).catch(erro => console.log(erro))
> ```
> 
This Sample is working, but I need to set the debug parameters to be true.
> ```js
>  venom.create("session-develop").then((client) => {
> 			  start(client)
> 			}).catch(erro => console.log(erro))
> ```
This is working, but need debug parameters to be true

**Comment by orkestral** [comment]
> > Hello! 5 options:
> > ```js
> >    venom.create("session-name", {
> > 			headless: true, // Headless chrome
> > 			devtools: false, // Open devtools by default
> > 			useChrome: true, // If false will use Chromium instance
> > 			debug: false, // Opens a debug session
> > 			logQR: true, // Logs QR automatically in terminal
> > 			browserArgs: [''], // Parameters to be added into the chrome browser instance
> > 			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> > 		  }).then((client) => {
> > 			  start(client)
> > 			}).catch(erro => console.log(erro))
> > ```
> 
> This is not working. Error result:
> TypeError: catchQR is not a function
> at SafeSubscriber._next (/.../node_modules/venom-bot/dist/controllers/initializer.js:219:13)
> 
> > ```js
> > venom.create("session-develop", (base64Qr, asciiQR) => {
> >    		// To log the QR in the terminal
> >    		console.log(asciiQR);
> >    		// To write it somewhere else in a file
> >    	   exportQR(base64Qr, "documentos/file.png");
> >    	  }, (statusFind) =>{
> >    		  console.log(statusFind+'\n\n')
> >    	  },{
> >    		headless: true, // Headless chrome
> >    		devtools: false, // Open devtools by default
> >    		useChrome: true, // If false will use Chromium instance
> >    		debug: false, // Opens a debug session
> >    		logQR: true, // Logs QR automatically in terminal
> >    		browserArgs: [''], // Parameters to be added into the chrome browser instance
> >    		refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> >    	  }).then((client) => {
> >    		  start(client)
> >    		}).catch(erro => console.log(erro))
> > ```
> 
> Not working also
> ReferenceError: exportQR is not defined
> 
> > ```js
> >  venom.create("session-develop", (base64Qr, asciiQR) => {
> > 			// To log the QR in the terminal
> > 			console.log(asciiQR);
> > 			// To write it somewhere else in a file
> > 		   exportQR(base64Qr, "documentos/file.png");
> > 		  }).then((client) => {
> > 			  start(client)
> > 			}).catch(erro => console.log(erro))
> > ```
> 
> Same Error...
> Not working also
> ReferenceError: exportQR is not defined
> 
> > ```js
> >  venom.create("session-develop",() =>{}, (statusFind) =>{
> > 			  console.log(statusFind+'\n\n')
> > 		  }).then((client) => {
> > 			  start(client)
> > 			}).catch(erro => console.log(erro))
> > ```
> 
> This Sample is working, but I need to set the debug parameters to be true.
> 
> > ```js
> >  venom.create("session-develop").then((client) => {
> > 			  start(client)
> > 			}).catch(erro => console.log(erro))
> > ```
> 
> This is working, but need debug parameters to be true

It is not normal to work this example which is just an example, but it is not a qr function, now and with you, here is only taught how to mess with the repo, more follows a part of the code:

function exportQR(qrCode, path) {
			  qrCode = qrCode.replace("data:image/png;base64,", "");
			  const imageBuffer = Buffer.from(qrCode, "base64");
			
			  // Creates "marketing-qr.png" file
			  fs.writeFileSync(path, imageBuffer);
			}
look the documentation

**Comment by brainwares** [comment]
> > > Hello! 5 options:
> > > ```js
> > >    venom.create("session-name", {
> > > 			headless: true, // Headless chrome
> > > 			devtools: false, // Open devtools by default
> > > 			useChrome: true, // If false will use Chromium instance
> > > 			debug: false, // Opens a debug session
> > > 			logQR: true, // Logs QR automatically in terminal
> > > 			browserArgs: [''], // Parameters to be added into the chrome browser instance
> > > 			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> > > 		  }).then((client) => {
> > > 			  start(client)
> > > 			}).catch(erro => console.log(erro))
> > > ```
> > 
> > 
> > This is not working. Error result:
> > TypeError: catchQR is not a function
> > at SafeSubscriber._next (/.../node_modules/venom-bot/dist/controllers/initializer.js:219:13)
> > > ```js
> > > venom.create("session-develop", (base64Qr, asciiQR) => {
> > >    		// To log the QR in the terminal
> > >    		console.log(asciiQR);
> > >    		// To write it somewhere else in a file
> > >    	   exportQR(base64Qr, "documentos/file.png");
> > >    	  }, (statusFind) =>{
> > >    		  console.log(statusFind+'\n\n')
> > >    	  },{
> > >    		headless: true, // Headless chrome
> > >    		devtools: false, // Open devtools by default
> > >    		useChrome: true, // If false will use Chromium instance
> > >    		debug: false, // Opens a debug session
> > >    		logQR: true, // Logs QR automatically in terminal
> > >    		browserArgs: [''], // Parameters to be added into the chrome browser instance
> > >    		refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> > >    	  }).then((client) => {
> > >    		  start(client)
> > >    		}).catch(erro => console.log(erro))
> > > ```
> > 
> > 
> > Not working also
> > ReferenceError: exportQR is not defined
> > > ```js
> > >  venom.create("session-develop", (base64Qr, asciiQR) => {
> > > 			// To log the QR in the terminal
> > > 			console.log(asciiQR);
> > > 			// To write it somewhere else in a file
> > > 		   exportQR(base64Qr, "documentos/file.png");
> > > 		  }).then((client) => {
> > > 			  start(client)
> > > 			}).catch(erro => console.log(erro))
> > > ```
> > 
> > 
> > Same Error...
> > Not working also
> > ReferenceError: exportQR is not defined
> > > ```js
> > >  venom.create("session-develop",() =>{}, (statusFind) =>{
> > > 			  console.log(statusFind+'\n\n')
> > > 		  }).then((client) => {
> > > 			  start(client)
> > > 			}).catch(erro => console.log(erro))
> > > ```
> > 
> > 
> > This Sample is working, but I need to set the debug parameters to be true.
> > > ```js
> > >  venom.create("session-develop").then((client) => {
> > > 			  start(client)
> > > 			}).catch(erro => console.log(erro))
> > > ```
> > 
> > 
> > This is working, but need debug parameters to be true
> 
> It is not normal to work this example which is just an example, but it is not a qr function, now and with you, here is only taught how to mess with the repo, more follows a part of the code:
> 
> ```js
> function exportQR(qrCode, path) {
> 			  qrCode = qrCode.replace("data:image/png;base64,", "");
> 			  const imageBuffer = Buffer.from(qrCode, "base64");
> 			
> 			  // Creates "marketing-qr.png" file
> 			  fs.writeFileSync(path, imageBuffer);
> 			}
> ```
> 
> look the documentation

It's working now, thanks!
In the
`console.log(statusFind+'\n\n')`
doesn't seem to return any value, is that right?

**Comment by orkestral** [comment]
> > > > Hello! 5 options:
> > > > ```js
> > > >    venom.create("session-name", {
> > > > 			headless: true, // Headless chrome
> > > > 			devtools: false, // Open devtools by default
> > > > 			useChrome: true, // If false will use Chromium instance
> > > > 			debug: false, // Opens a debug session
> > > > 			logQR: true, // Logs QR automatically in terminal
> > > > 			browserArgs: [''], // Parameters to be added into the chrome browser instance
> > > > 			refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> > > > 		  }).then((client) => {
> > > > 			  start(client)
> > > > 			}).catch(erro => console.log(erro))
> > > > ```
> > > 
> > > 
> > > This is not working. Error result:
> > > TypeError: catchQR is not a function
> > > at SafeSubscriber._next (/.../node_modules/venom-bot/dist/controllers/initializer.js:219:13)
> > > > ```js
> > > > venom.create("session-develop", (base64Qr, asciiQR) => {
> > > >    		// To log the QR in the terminal
> > > >    		console.log(asciiQR);
> > > >    		// To write it somewhere else in a file
> > > >    	   exportQR(base64Qr, "documentos/file.png");
> > > >    	  }, (statusFind) =>{
> > > >    		  console.log(statusFind+'\n\n')
> > > >    	  },{
> > > >    		headless: true, // Headless chrome
> > > >    		devtools: false, // Open devtools by default
> > > >    		useChrome: true, // If false will use Chromium instance
> > > >    		debug: false, // Opens a debug session
> > > >    		logQR: true, // Logs QR automatically in terminal
> > > >    		browserArgs: [''], // Parameters to be added into the chrome browser instance
> > > >    		refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> > > >    	  }).then((client) => {
> > > >    		  start(client)
> > > >    		}).catch(erro => console.log(erro))
> > > > ```
> > > 
> > > 
> > > Not working also
> > > ReferenceError: exportQR is not defined
> > > > ```js
> > > >  venom.create("session-develop", (base64Qr, asciiQR) => {
> > > > 			// To log the QR in the terminal
> > > > 			console.log(asciiQR);
> > > > 			// To write it somewhere else in a file
> > > > 		   exportQR(base64Qr, "documentos/file.png");
> > > > 		  }).then((client) => {
> > > > 			  start(client)
> > > > 			}).catch(erro => console.log(erro))
> > > > ```
> > > 
> > > 
> > > Same Error...
> > > Not working also
> > > ReferenceError: exportQR is not defined
> > > > ```js
> > > >  venom.create("session-develop",() =>{}, (statusFind) =>{
> > > > 			  console.log(statusFind+'\n\n')
> > > > 		  }).then((client) => {
> > > > 			  start(client)
> > > > 			}).catch(erro => console.log(erro))
> > > > ```
> > > 
> > > 
> > > This Sample is working, but I need to set the debug parameters to be true.
> > > > ```js
> > > >  venom.create("session-develop").then((client) => {
> > > > 			  start(client)
> > > > 			}).catch(erro => console.log(erro))
> > > > ```
> > > 
> > > 
> > > This is working, but need debug parameters to be true
> > 
> > 
> > It is not normal to work this example which is just an example, but it is not a qr function, now and with you, here is only taught how to mess with the repo, more follows a part of the code:
> > ```js
> > function exportQR(qrCode, path) {
> > 			  qrCode = qrCode.replace("data:image/png;base64,", "");
> > 			  const imageBuffer = Buffer.from(qrCode, "base64");
> > 			
> > 			  // Creates "marketing-qr.png" file
> > 			  fs.writeFileSync(path, imageBuffer);
> > 			}
> > ```
> > 
> > 
> > look the documentation
> 
> It's working now, thanks!
> In the
> `console.log(statusFind+'\n\n')`
> doesn't seem to return any value, is that right?

Callback Status Session
Gets the return if the session is isLogged or if it is notLogged

``` javascript
create('sessionName', qrCallback, (statusFind) => {
  console.log(statusFind);
})
  .then((client) => {
    start(client);
  })
  .catch((erro) => console.log(erro));
```

**Comment by brainwares** [comment]
> 
> Callback Status Session
> Gets the return if the session is isLogged or if it is notLogged
> 
> ```js
> create('sessionName', qrCallback, (statusFind) => {
>   console.log(statusFind);
> })
>   .then((client) => {
>     start(client);
>   })
>   .catch((erro) => console.log(erro));
> ```
<img width="330" alt="Screen Shot 2020-06-09 at 02 27 50" src="https://user-images.githubusercontent.com/25642097/84072285-24f1d200-a9f9-11ea-8a46-da2cbf3df2ce.png">
I don't see the Status Session logged in the console.

**Comment by orkestral** [comment]
here working, update npm venom-bot

![image](https://user-images.githubusercontent.com/66584466/84073139-a2d8bd80-a9a6-11ea-9d94-911f4fa0bd73.png)

**Comment by brainwares** [comment]
> here working, update npm venom-bot
> 
> ![image](https://user-images.githubusercontent.com/66584466/84073139-a2d8bd80-a9a6-11ea-9d94-911f4fa0bd73.png)

Very nice!
It is working now. Thanks!
