### ISSUE TITLE
Venom does not leave the "waiting"

### ISSUE THREAD

**Issue by XNexusPrimeX** [orkestral/venom#10]
I already used sulla for a few months, and I decided to migrate to venom, because of an authentication problem .. and here the same problem happens! my code is the simplest because i just went to test it

`// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom.create().then((client) => start(client));

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi') {
      client.sendText(message.from, 'Welcome Venom 🕷');
    }
  });
}`

(I don't know how to use git very well)

**Comment by orkestral** [comment]
use for npm install venom-bot, if it doesn't work let us know what happens when you run the code

**Comment by XNexusPrimeX** [comment]
I've done it, like I said, you wait all the time
