### ISSUE TITLE
base64Qr is not defined.

### ISSUE THREAD

**Issue by muhammadaliakbarr** [orkestral/venom#100]
Getting this error while trying to export QR Code.

base64Qr is not defined.

Code:
`venom.create('fastech', (base64Qr, asciiQR), (statusFind) => {
  console.log(statusFind);

   // To log the QR in the terminal
   //console.log(asciiQR);

   // To write it somewhere else in a file
   exportQR(base64Qr, 'marketing-qr.png');

})
  .then((client) => {
    start(client);
  })
  .catch((erro) => console.log(erro));
`

**Comment by joaosouz4** [comment]
In the documentation that we describe how to export or qr code
like this:
```
const fs = require('fs');

// Second create() parameter is the QR callback
venom.create('sessionMarketing', (base64Qr, asciiQR) => {
  // To log the QR in the terminal
  console.log(asciiQR);

  // To write it somewhere else in a file
  exportQR(base64Qr, 'marketing-qr.png');
});

// Writes QR in specified path
function exportQR(qrCode, path) {
  qrCode = qrCode.replace('data:image/png;base64,', '');
  const imageBuffer = Buffer.from(qrCode, 'base64');

  // Creates 'marketing-qr.png' file
  fs.writeFileSync(path, imageBuffer);
}
```

**Comment by bhavya32** [comment]
@joaosouz4 he has left the conversation. I think better close the issue?
