### ISSUE TITLE
Base64

### ISSUE THREAD

**Issue by nompaixg06** [orkestral/venom#1004]
#### Hello, I don't have an idea in wich form should be the base 64 data, in my cas i have the problem :

`Error when sending:  { erro: true, to: undefined, text: 'Invalid base64!' }`

I tried to convert it into png and it works. 
And I don't know what to do, thank you in advance.

[b64.txt](https://github.com/orkestral/venom/files/6702464/b64.txt)

**Comment by jonalan7** [comment]
At the beginning of the base64 format it must contain the following parameters:

```
//Example of an image with png format

date:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARw...

```

**Comment by nompaixg06** [comment]
Thank you a lot
