### ISSUE TITLE
Cannot create group

### ISSUE THREAD

**Issue by fabriciocotag** [orkestral/venom#1005]
I trying create a group from the wapi.js, but is not working..
when WAPI.createGroup("teste",number); this returns "window.Store.WapQuery.CreateGroup is not a function",
the Store.WapQuery not have the function.. but the window.Store.Wap have this function.. but when i try:
window.Store.Wap.createGroup("group007",[number]) or window.Store.Wap.createGroup("group007",number) this returns: "USER_JID: invalid jid type: Not an instance of WID", someone can help me?

**Comment by jonalan7** [comment]
Which version are you using?

**Comment by jonalan7** [comment]
Download the newest version! If you want to send via WAPI, do the following:

`WAPI.createGroup("test", ["000000000000@c.us"]);`
