### ISSUE TITLE
Get user online stauts

### ISSUE THREAD

**Issue by oscardimanno** [orkestral/venom#101]
Hello, can it possible to get the current online/offline status and manage this on events?

**Comment by joaosouz4** [comment]
Sim é possivel.

**Comment by joaosouz4** [comment]
Yes, is possible!

**Comment by oscardimanno** [comment]
How can i do this thing? I don't know what is the name of the event

**Comment by joaosouz4** [comment]
@oscardimanno 
can u use 
```
let res = client.getChatById(CHATID)
let online = res.isOnline
if(online) ...
```

**Comment by joaosouz4** [comment]
but I think this method is not so accurate
