### ISSUE TITLE
Bot enviando mensagem repetidas

### ISSUE THREAD

**Issue by merciomedina** [orkestral/venom#102]
Olá.
Criei um socket para ouvir um evento de recebimento de mensagem a partir de um chat. Ocorre que qdo recebo a mensagem e envio usando o metodo sendMessaToId, o bot envia para todas as sessoes ativas. Como poderia tratar este problema?
Grato.

**Comment by joaosouz4** [comment]
Você deve ta iniciando mais de uma sessão, entao vc deve tratar esse sockets e enviar apenas para o que vc deseja. Tem formas de criar roms pelo socket, talves seja o que vc está precisando
