### ISSUE TITLE
Page Closed after a while

### ISSUE THREAD

**Issue by grouprcs** [orkestral/venom#1027]
## Description

After some time, I get **Page Closed** error.
I only notice when some message that should have arrived does not arrive.
Sometimes it takes about 24 hours, other times it takes days.
But it always does.

What can it be?

## Environment

- **Venom version(s):** 3.0.20
- **Browser:** Chrome 91
- **OS:** Windows Server 2019
- **Node version:** 14

**Comment by 2482103133** [comment]
Hi I got same issue, page closed.  
- [instance: GeTSWhatsappBotService]: Page Closed
