### ISSUE TITLE
Issue running Venon /service on Debian 10

### ISSUE THREAD

**Issue by AlexanderPineda** [orkestral/venom#103]
(node:3654) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0804/224325.046739:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/chat-bot-test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.helper_js_1.helper.addEventListener (/chat-bot-test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RubberArchind** [comment]
did you ran it with sudo?

The error says Running as root without --no-sandbox is not supported.

use --no-sandbox args if you not use sudo 
venom.create('session name', '', '', {
    browserArgs: ['--no-sandbox']
}).then((client) => start(client));

if you use sudo try run without it

**Comment by AlexanderPineda** [comment]
> 
> 
> did you ran it with sudo?
> 
> The error says Running as root without --no-sandbox is not supported.
> 
> use --no-sandbox args if you not use sudo
> venom.create('session name', '', '', {
> browserArgs: ['--no-sandbox']
> }).then((client) => start(client));
> 
> if you use sudo try run without it

I ran my node app my root credentials and with Sudo prefix but the error persist, i dont Know how can I solve that issue

**Comment by RubberArchind** [comment]
Just try running it without using sudo

**Comment by RubberArchind** [comment]
Or if you really want to use "Sudo" use this to create a session:
`venom.create('session name', '', '', {
    browserArgs: ['--no-sandbox']
}).then((client) => start(client));`
Instead of `venom.create('session name').then((client) => start(client));`

**Comment by AlexanderPineda** [comment]
> 
> 
> Or if you really want to use "Sudo" use this to create a session:
> `venom.create('session name', '', '', { browserArgs: ['--no-sandbox'] }).then((client) => start(client));`
> Instead of `venom.create('session name').then((client) => start(client));`

Thanks, for your help, That code that you bring me, Where must I put, In the Cli or in any specific file of the library?, Thanks for your response.

**Comment by RubberArchind** [comment]
Take a look at [https://github.com/orkestral/venom#getting-started](url) and replace `venom.create().....` with the code above
