### ISSUE TITLE
session.data.json not being created

### ISSUE THREAD

**Issue by Ramstin13** [orkestral/venom#1030]
## Description

I start venom with basic code, just the one from the "Get started".
the problem i see is that the session file sometimes gets created inside tokens folder correctly, sometimes it takes like 2-5 minutes, or it doesnt gets created at all.
if i kill the process and delete de tokens folder manually, and run venom again, sometimes it doesnt create anything, or sometimes just the folder and not the file.
i don't think its related to user or folder permissions because if it where... the file will never be created.

## Environment

Debian GNU/Linux 9.13 (stretch)

node v14.17.0

package.json:
"express": "^4.17.1",
"express-basic-auth": "^1.2.0",
"log-to-file": "^2.0.2",
"mongoose": "^5.12.14",
"puppeteer": "^10.0.0",
"venom": "^0.1.0",
"venom-bot": "^3.0.18"

## Steps to Reproduce

delete tokens folder or alertas.data.json file inside
close venom
restart venom
scan qr
check for file or folder

## Log Output

venom.defaultLogger.level = 'silly'; ??? this is not working, should i enable an aditional logger for that?

```
If relevant, paste all of your Log Output
```

## Your Code

const express = require('express');
const basicAuth = require('express-basic-auth');
const path = require('path');
const mongoose = require("mongoose");
const venom = require("venom-bot");

venom
  .create('alertas')
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

## Additional context / Screenshot

![imagen](https://user-images.githubusercontent.com/65677938/125143886-7edc3400-e0f2-11eb-82c6-395642d15256.png)

no "tokens" folder...

![imagen](https://user-images.githubusercontent.com/65677938/124962103-992fe800-dff4-11eb-98db-a1375e3e1fe7.png)

**Comment by iamrenaud** [comment]
Any solution?
