### ISSUE TITLE
downloadMedia

### ISSUE THREAD

**Issue by AzamatIshmuratov** [orkestral/venom#1049]
After the last update, **downloadMedia** does not work for all files. Before the update, it was normal. Thanks!

**Comment by AzamatIshmuratov** [comment]
More precisely, sometimes it works, sometimes not

**Comment by AzamatIshmuratov** [comment]
I think they forgot or changed something in the latest version :)

**Comment by AzamatIshmuratov** [comment]
Does not work with pdf for example

**Comment by AzamatIshmuratov** [comment]
I can't download some files that were sent a few days ago, but I download today's files without problems

**Comment by vbutaev** [comment]
I see this behavior when an quite old image download is needed. I guess this happens when in native web.whatsapp.com you have to click blurred image to download. In newly received message image is shown without blur. This type of message downloadMedia serves correct.
