### ISSUE TITLE
Return id message on sendImage

### ISSUE THREAD

**Issue by mrangelba** [orkestral/venom#105]
How can I capture the message id, using sendImageFromBase64, sendFile or sendImage methods?

Could you return the id in the methods, as in sendText.

**Comment by jonalan7** [comment]
you mean, return an object with a confirmation and contact number, for example?

**Comment by jonalan7** [comment]
you mean, return an object with a confirmation and contact number, for example?

**Comment by mrangelba** [comment]
Yes

**Comment by jonalan7** [comment]
**In the next updates, we will implement this behavior**

**Comment by jonalan7** [comment]
**Problem fixed**
