### ISSUE TITLE
Verify phone is registered

### ISSUE THREAD

**Issue by jiangzongqi** [orkestral/venom#1059]
Hello, may I ask how to verify whether the mobile phone number has registered a WhatsApp account? Thank you!

**Comment by Felipe-53** [comment]
Hello there, @jiangzongqi

If I understood your question correctly, you want to know if there is a way to determine if a certain phone number is associated with a whatsapp account, right?

Well, I think the only way to know within the library is when you _receive_ a message from the number (in this case, of course you know the number is registered, I know).

Then, in the message object passed in the event 'onMessage', you can inspect the "sender" field, which contains information of whether that contact is in you contact list, etc, as seen the image below:

![image](https://user-images.githubusercontent.com/60227644/126542224-b8735de1-95ad-44d6-a702-8cbe17ee5fa2.png)

**Comment by jiangzongqi** [comment]
Hi,@Felipe-53
 CheckNumberStatus solved my problem perfectly. Since I'm Phper, not a front-end programmer, I want to make this project an open API project. In this process, I encountered the following difficulties:
1. I need to use the client connection pool to manage the client of the corresponding user, but in WA, I can't seem to monitor whether the client disconnects or even if the user logs out.
2. Waiting time for login is too long.
Could you do me a favor? Here's my first try:
![1626915927(1)](https://user-images.githubusercontent.com/29655482/126577829-d2712398-d866-4e1c-ba5d-3e88e42cfdcb.png)
