### ISSUE TITLE
Error sending video from sendFile method

### ISSUE THREAD

**Issue by henrickJona** [orkestral/venom#1060]
## Description
In the last version i was able to send videos from this method sendFile, the version i was using 3.0.18, now 3.0.21, but this new version is not working, when i try to downgrade my version, an error happens when trying to log in a session, token is not created and seems like i'm not logged, but terminal says i'm connected
[Description of the bug, When Issue Happens]
Error: Evaluation failed: Error: InvalidMediaFileType and the error is not being get from trycatch.
## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## await this.client
        .sendFile(formattedNumber, path, filename, subtitle)
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });

```
If relevant, paste all of your challenge code in here
```

**Comment by keyuritaliyaCodezee** [comment]
same problem here, are you got any solution?
