### ISSUE TITLE
How to do a send button link? 

### ISSUE THREAD

**Issue by AdllerSimas** [orkestral/venom#1067]
How to send the user a button that works as a link?

**Comment by jonalan7** [comment]
Atualmente não é possível!  Somente na API oficial

**Comment by famarojr** [comment]
> Not currently possible! Only on the official api

I saw some no official account using buttons. Not yet for venom?

**Comment by ProbBC** [comment]
Looks like this feature is available in the new version, but I'm having trouble understanding how to use it. There are no helpful guides in the documentation for the method. Not sure on what to put on the parameters.

**Comment by robinhodemorais** [comment]
> Looks like this feature is available in the new version, but I'm having trouble understanding how to use it. There are no helpful guides in the documentation for the method. Not sure on what to put on the parameters.

const buttons = [
            {buttonId: 'id1', buttonText: {displayText: 'Venom 1'}, type: 1},
            {buttonId: 'id2', buttonText: {displayText: 'Venom 2'}, type: 1}
          ]

        let options = await client.sendButtons('55123456789@c.us', 'Title', buttons, 'Description')

**Comment by liawifelix** [comment]
May I know is there any way to change the button size?
