### ISSUE TITLE
Close whatsapp session by mobile throws exception and kill server

### ISSUE THREAD

**Issue by reinaldocoelho** [orkestral/venom#1071]
## Description

When create Node Express server and close/logout browser session from the mobile phone, the Puppeteer throws exception and kill the server (if we has other accounts logged, all down)

## Environment

- **Venom version(s):** 3.0.21
- **Browser:** Chrome 91.0.4472.164 / Chromium 91.0.4472.114 
- **OS:** Ubuntu 21.04 / Container Ubuntu Core
- **Node version:** Node 14.17.2

## Steps to Reproduce

Steps
1. Create an Express API server using Venom
2. Run basic steps to create session and connect account (with QrCode Ok)
3. If you whant validate connection send message/receiving events
4. On the mobile, open Connections and logout from session

Expected
1. Receive event changing State warning of disconnection

Ocurred
1. Exception attached occurs and its stop the Express Server (we can not avoid that)

## Log Output

![log-exception-logout-whatsapp-mobile](https://user-images.githubusercontent.com/889634/126513669-843da678-6cf7-48dc-82ab-acd9fbe06afc.png)

**Comment by MatheusIbarra** [comment]
same issue here.
