### ISSUE TITLE
TimeoutError on docker container restart

### ISSUE THREAD

**Issue by jonit-dev** [orkestral/venom#108]
Hey guys, thanks for this awesome library!

So, whenever I'm trying to push any updates to my production bot, it crashes with a navigation timeout after the container restarts, and asks again for my QR code, to authenticate. Somehow, it's losing the session.

![image](https://user-images.githubusercontent.com/30300459/89686011-57616380-d8b2-11ea-85ee-4705f0cd8759.png)

Here's how I'm trying to handle it, without any success, on my WhatsAppBot class:
`
 public init = async () => {

    // Create one bot instance for each of our pre-defined bots

    for (const bot of bots) {
      await create(bot.name, undefined, undefined, {
        browserArgs: ['--no-sandbox'],
        disableSpins: true // disable spins for better container logs
      }).then((client) => {
        bot.instance = client;

        // In case of being logged out of whatsapp web
        // Force it to keep the current session
        // State change
        bot.instance.onStateChange((state) => {

          const conflicts = [
            SocketState.CONFLICT,
            SocketState.UNPAIRED,
            SocketState.UNLAUNCHED,
          ];
          if (conflicts.includes(state)) {
            client.useHere();
          }
        });

        process.on('SIGINT', function () {
          bot.instance?.close();
        });
        process.on('unhandledRejection', function () {
          bot.instance?.close();
        });

      });
    }
  }
`

Any help would be appreciated!

Thank you and keep up with the good work!

**Comment by jonalan7** [comment]
**Fixed error**
