### ISSUE TITLE
How to stop so many chrome child processes

### ISSUE THREAD

**Issue by JoseLourenc0** [orkestral/venom#1087]
I'm using a Linux VM just to run venom, and I'm getting out of memory sometimes. When I tried to investigate about it, I realized there're a lot of chrome process running at the same time. Then to know what was specifically happening, I used the log of the PID when starting a new instance.
For example, I got the PID 688676 and used 'pgrep -P 688676' to get all child process running and got 6:
688681
688682
688684
688685
688701
688848

When I used 'ps' to list those process and how much memory they're using I got those values (in percentage of my 16 gb RAM):
688681 0
688682 0
688684 0,3 = 48mb
688685 0,3 = 48mb
688701 0,5 = 80mb
688848 0,4 = 64mb

I tried to kill every child process and test if it's still running and to my surprise it went like usual. My question is:
Is there someway to don't create so many child processes when I'm starting a new instance, aiming memory saving?

**Comment by vinipjs** [comment]
Same problem!

**Comment by Pedrocanoas** [comment]
Anyone solved this? I've been the same problem

**Comment by diazzaid** [comment]
> Saya menggunakan VM Linux hanya untuk menjalankan venom, dan terkadang saya kehabisan memori. Ketika saya mencoba menyelidikinya, saya menyadari ada banyak proses chrome yang berjalan pada saat yang bersamaan. Kemudian untuk mengetahui apa yang secara khusus terjadi, saya menggunakan log PID saat memulai instance baru.
> Misalnya, saya mendapatkan PID 688676 dan menggunakan 'pgrep -P 688676' untuk menjalankan semua proses anak dan mendapatkan 6:
> 688681
> 688682
> 688684
> 688685
> 688701
> 688848
> 
> Ketika saya menggunakan 'ps' untuk membuat daftar proses tersebut dan berapa banyak memori yang mereka gunakan, saya mendapatkan nilai-nilai itu (dalam persentase dari 16 gb RAM saya):
> 688681 0
> 688682 0
> 688684 0,3 = 48mb
> 688685 0,3 = 48mb
> 688701 0 ,5 = 80mb
> 688848 0,4 = 64mb
> 
> Saya mencoba untuk membunuh setiap proses anak dan menguji apakah itu masih berjalan dan saya terkejut itu berjalan seperti biasa. Pertanyaan saya adalah:
> Apakah ada cara untuk tidak membuat begitu banyak proses anak ketika saya memulai instance baru, yang bertujuan menghemat memori?

Try adding 
browserArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process', // <- this one doesn't works in Windows
        '--disable-gpu'
	],

**Comment by JoseLourenc0** [comment]
> > Saya menggunakan VM Linux hanya untuk menjalankan venom, dan terkadang saya kehabisan memori. Ketika saya mencoba menyelidikinya, saya menyadari ada banyak proses chrome yang berjalan pada saat yang bersamaan. Kemudian untuk mengetahui apa yang secara khusus terjadi, saya menggunakan log PID saat memulai instance baru.
> > Misalnya, saya mendapatkan PID 688676 dan menggunakan 'pgrep -P 688676' untuk menjalankan semua proses anak dan mendapatkan 6:
> > 688681
> > 688682
> > 688684
> > 688685
> > 688701
> > 688848
> > Ketika saya menggunakan 'ps' untuk membuat daftar proses tersebut dan berapa banyak memori yang mereka gunakan, saya mendapatkan nilai-nilai itu (dalam persentase dari 16 gb RAM saya):
> > 688681 0
> > 688682 0
> > 688684 0,3 = 48mb
> > 688685 0,3 = 48mb
> > 688701 0 ,5 = 80mb
> > 688848 0,4 = 64mb
> > Saya mencoba untuk membunuh setiap proses anak dan menguji apakah itu masih berjalan dan saya terkejut itu berjalan seperti biasa. Pertanyaan saya adalah:
> > Apakah ada cara untuk tidak membuat begitu banyak proses anak ketika saya memulai instance baru, yang bertujuan menghemat memori?
> 
> Try adding
> browserArgs: [
> '--no-sandbox',
> '--disable-setuid-sandbox',
> '--disable-dev-shm-usage',
> '--disable-accelerated-2d-canvas',
> '--no-first-run',
> '--no-zygote',
> '--single-process', // <- this one doesn't works in Windows
> '--disable-gpu'
> ],

Thanks, it helped me decreasing the number of multiple chrome child processes being generated!! But the memory they're taking to run is the same as I haven't use those browserArgs :/
