### ISSUE TITLE
storage sesion with another query

### ISSUE THREAD

**Issue by MgArreaza13** [orkestral/venom#11]
hello brother I ask you, how can I export or respond to a front the client instance and pass it to another request so that it does not ask me to authenticate in each request, example I am implementing your library but in a node server to use angular in the frontend then for example

I have a path / login where I scan the qr code and log out

but i have another route / get-messages

and there when I access it asks me to rewrite the session because I am running the create method again to have the client instance, I need help how to optimize that process with an example and thanks

**Comment by MgArreaza13** [comment]
`// create new user and profile
  public test(req: Request, res: Response) {
    venom.create('test').then(async (client: any) => {
      client.onMessage(async (message: any) => {
        console.log(message.body, message.from, message.id.toString());
        if (message.body === 'hola' && message.from === '584148974225@c.us') {
          console.log('entre aqui')
          await client.reply(message.from, 'Hola como estas? yo Muy bien y tu?!', message.id.toString());
        } else if (message.body !== 'hola como estas' && message.from === '584148974225@c.us') {
          client.sendText(message.from, 'Welcome Venom 🕷');
        }
      });
      // keep session 
      client.onStateChange((state: any) => {
        console.log(state);
        const conflits = [
          venom.SocketState.CONFLICT,
          venom.SocketState.UNPAIRED,
          venom.SocketState.UNLAUNCHED,
        ];
        if (conflits.includes(state)) {
          client.useHere();
        }
      });
    });
  }`

 public contacts(req: Request, res: Response) {
    venom.create('test').then(async (client: any) => {
      const contacts = await client.getAllContacts();
      res.status(200).send(contacts);
    });
  }

**Comment by orkestral** [comment]
This weekend we are implementing the section by token which will help you in this process, thanks, stay tuned to update 1.0.1

**Comment by MgArreaza13** [comment]
It's ready this? Please? Section by token? For implementation?
