### ISSUE TITLE
how to download audio or documents?

### ISSUE THREAD

**Issue by gamadoleo** [orkestral/venom#110]
downloading images and videos files was possible with the decrypt function, however I am not able to obtain audio files (voice message) and also cannot get documents (pdf, docs, etc.) what is the procedure?

**Comment by gamadoleo** [comment]
Is possible?

**Comment by jonalan7** [comment]
const fs = require('fs');
    const mime = require('mime-types');
    client.onMessage(async(message) => {
        if(message.isMedia == true **|| message.isMMS == true**) {
             const buffer = await client.decryptFile(message); 
             
             const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
             await fs.writeFile(fileName, buffer, (err) => {
                 ....
             });
        }
    });

**Comment by gamadoleo** [comment]
valeu...
