### ISSUE TITLE
any new update for Whatsapp Multi-Device Beta?

### ISSUE THREAD

**Issue by hafidzaini** [orkestral/venom#1101]
Whatsapp Multi-Device Beta has roll out, any new implementation?

**Comment by mrizkypk** [comment]
I tried with multi device beta account, the result is successful scan but no token is stored.
It looks like there are 2 QRs that appear, 1 is small and the next has a larger size.

**Comment by rsoorajs** [comment]
same issue here.please whatsapp multi device beta support

**Comment by JimmyBastos** [comment]
+1
