### ISSUE TITLE
puppeteerOptions doesn't seems to work with browserWS

### ISSUE THREAD

**Issue by bielgvs** [orkestral/venom#1113]
## Description

When using browserWS parameter none of the puppeteerOptions are send to puppeteer, that happens because puppeteer.connect() doesn't receive the object puppeteerOptions.

## Environment

- **Venom version(s):** 3.1.2
- **Browser:** Chrome 92.0.4515.159
- **OS:** Windows 10
- **Node version:** Node 14.16.1

## Steps to Reproduce

1. When I try to set the Puppeteer Option defaultViewport: null using the browserWS the option is ignored
2. The documentation from venom says that the parameter puppeteerOptions pass these options to puppeteer.launch(), but when using the parameter browserWS venom uses the function puppeteer.connect(), and it seems that this call doesn't use the puppeteer.connect
3. I was able to find what seems to be the call to connect() on dist\controllers\browser.js:225
4. probably we just need to concat the puppeteerOptions on this call

## Log Output

Irrelevant I think

## Your Code

```
venom
            .create({
                statusFind: (statusSession, session) => {
                  console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken || chatsAvailable || deviceNotConnected || serverWssNotConnected || noOpenBrowser
                  //Create session wss return "serverClose" case server for close
                  console.log('Session name: ', session);
                },
                headless: false,
                browserWS: webSocketDebuggerUrl /* ws://127.0.0.1:9222/devtools/browser/...... */,
                puppeteerOptions: {
                  defaultViewport: null
                },
            })
            .then(async (client) => {
              start(client)
            })
            .catch((erro) => {
                console.log(erro);
            });
```

## Additional context / Screenshot

I did the following tests with the following results

1 - Not using the parameter browserWS making venom call launch(), all the puppeteerOptions Works
2 - Using browserWS I am able to open venom on any browser, but it always sets the viewport for 800x600
3 - Changing the browser.js:225 and forcing viewport = null works perfectly

`.connect({
                            browserWSEndpoint: options.browserWS
                        })`

to

`.connect({
                            browserWSEndpoint: options.browserWS,
							defaultViewport: null
                        })
`

but this is just a test and just solve my own issue, we should make it accept any puppeteerOption, right?

**Comment by orkestral** [comment]
We are discontinuing the use of browser, will soon migrate to socket
