### ISSUE TITLE
Error sending or receiving audios

### ISSUE THREAD

**Issue by AlexsandroZanella2** [orkestral/venom#1115]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [latest release]
- **OS:** [Windows 10, Server 2012, Server 2019]
- **Node version:** [ Node 12, Node 14]

## Log Output
<------------------->
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 948)
Error when sending:  {
  me: {
    id: '1',
    ref: '1@/A1Y8cAhiMdjsmPwdqClhDyrD/7BFO04XJijNGmCH5EW0YdxYaV6kRSgCoqDlklSjacX
aQ96o9oTIg==',
    refTTL: 20000,
    wid: {
      server: 'c.us',
      user: '558391162007',
      _serialized: '558391162007@c.us'
    },
    connected: true,
    protoVersion: [ 0, 17 ],
    clientToken: '9Aq20b4QjaV94IBZkoh2scGIcvEoRGrcx58AYQyuP+g=',
    serverToken: '1@R3++99LE7YXHvWoZ9o0yQ7IXKDtqgWHK1YJ0rlkNolxnC35CNs2G2sUadMNN
JiX+onf4E4CyuuPOgA==',
    isResponse: 'true',
    battery: 58,
    plugged: false,
    lc: 'BR',
    lg: 'pt',
    locales: 'pt-BR',
    platform: 'smba',
    phone: {
      wa_version: '2.21.17.24',
      mcc: '000',
      mnc: '000',
      os_version: '10',
      device_manufacturer: 'LGE',
      device_model: 'meh15lm',
      os_build_number: 'QKQ1.200614.002'
    },
    tos: 0,
    smbTos: 0,
    pushname: 'Farmácia do Arnaldo',
    stale: false,
    blockStoreAdds: false,
    isVoipInitialized: false
  },
  to: {
    fromMe: false,
    remote: {
      server: 'c.us',
      user: '555496838997',
      _serialized: '555496838997@c.us'
    },
    id: '3EB08293F2A91A86918A',
    _serialized: 'false_555496838997@c.us_3EB08293F2A91A86918A',
    formattedName: '+55 54 9683-8997',
    isBusiness: false,
    isMyContact: false,
    pushname: 'Cristiano Andrioli',
    isOnline: true
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  type: 'sendPtt'
}
<------------------->
and:
<------------------->
(node:6644) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeErro
r: this._find is not a function
    at j._serverQuery (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a
3.js:55:334921)
    at j._query (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:5
5:334450)
    at j.find (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:
332582)
    at Object.window.WAPI.window.WAPI.sendPtt (C:\mercfarma\WPPAPI\node_modules\
venom-bot\dist\lib\wapi\wapi.js:1:42432)
    at ExecutionContext._evaluateInternal (C:\mercfarma\WPPAPI\node_modules\pupp
eteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async ExecutionContext.evaluate (C:\mercfarma\WPPAPI\node_modules\puppete
er\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
<------------------->

**Comment by orkestral** [comment]
We ran some tests and noticed that everything is fine.

**Comment by AlexsandroZanella2** [comment]
Sorry, I wasn't very precise. Now I've found that this happens when I try to send a message to a number I've never spoken to before.
