### ISSUE TITLE
Create endpoint for send message

### ISSUE THREAD

**Issue by aditya37** [orkestral/venom#112]
help, how to create some end point for send message?

**Comment by joaosouz4** [comment]
I think u need to use lib node Express

**Comment by aditya37** [comment]
@joaosouz4  i don't know to integrate venom with express. do you want to help me?

**Comment by leobevi** [comment]
hello.....
const express = require('express');
const app = express();
const venom = require('venom-bot');

const porta = '3002';
var server = app.listen(porta);
console.log('listen on port', server.address().port);

venom.create().then((client) => start(client));

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi') {
      client.sendText(message.from, 'Welcome Venom 🕷');
    }
  });

  app.get('/sendmessage', async function (req, res) {
        console.log("Solicitou envio de mensagem");
        let retorno =  await client.sendMessageToId('5599999999@c.us', 'teste message'); 
        console.log(retorno);
        res.send(retorno); 
  });  

}



In your browser call this url:  http://127.0.0.1:3001/sendmessage

**Comment by joaosouz4** [comment]
@aditya37 have any questions about the above code ?

**Comment by snewen** [comment]
> let retorno = await client.sendMessageToId('[5599999999@c.us](mailto:5599999999@c.us)', 'teste message');

**client**.sendMessageToId would not be expossed

**Comment by bhavya32** [comment]
@joaosouz4 @aditya37 please close the issue.
