### ISSUE TITLE
await client.sendText('00000000@c.us', 'message here is')

### ISSUE THREAD

**Issue by yash6758** [orkestral/venom#1121]
No, i have not send any messages or saved that users numbers so I don't have the chatid,
How do I send message without chat id

From this [issue](https://github.com/orkestral/venom/issues/1119)

**Comment by pixplix** [comment]
chatid = phone number

**Comment by pixplix** [comment]
> chatid = phone number

example:

+1 = country code
9183089444 = phone number
@c.us = always

then you send as:

19183089444@c.us

**Comment by yash6758** [comment]
> > chatid = phone number
> 
> example:
> 
> +1 = country code
> 9183089444 = phone number
> @c.us = always
> 
> then you send as:
> 
> [19183089444@c.us](mailto:19183089444@c.us)

Will it worked for unsaved numbers as well ???

**Comment by pixplix** [comment]
> > > chatid = phone number
> > 
> > 
> > example:
> > +1 = country code
> > 9183089444 = phone number
> > @c.us = always
> > then you send as:
> > [19183089444@c.us](mailto:19183089444@c.us)
> 
> Will it worked for unsaved numbers as well ???

yes

**Comment by yash6758** [comment]
How to add url to the buttons ???

**Comment by orkestral** [comment]
we don't have this function, please don't open another issue if it's not relevant
