### ISSUE TITLE
VenomClient Chromium process

### ISSUE THREAD

**Issue by Tomcat-42** [orkestral/venom#1122]
First of all, y’all are doing a great work :ok_hand: .

## Previous Context

I have been using the Venom bot for my product, which have _n_ possible clients, and for each client that I have I gotta instantiate a new Venom session.

## Is your feature request related to a problem? Please describe.

I'm using Venom in a serverless architecture, thus, for every batch of messages from a specific client the system needs to create another instance of the VenomClient, hence a Chromium process is spawned too. This new Chromium process for every instance is really a bottleneck in my use case. Not mentioning the time it takes to start and authenticate which kinda make the serverless approach useless, but I couldn’t figure out any other way to not use 100% of the VM memory.

## Describe the solution you’d like

Therefore, it would be great if Venom can share a Chromium process across a set of instances, or if possible, use a global Chromium process for use by all instances.

## Describe alternatives you've considered
The first alternative I've considered is to spawn a Chromium process for every  _N_(and here _N_ is a predetermined value, maybe customizable?) venom client instances.

Another alternative I’ve considered is to make the Chromium process ID a parameter of the VenomClient constructor, this way it would be possible to spawn a single chromium process to handle the VenomClients.

## Addtional context

It may be related to #1117 .

**Comment by orkestral** [comment]
We'll be reviewing your idea and we'll be able to come in as a future feature soon, thank you
