### ISSUE TITLE
using open-wa instead

### ISSUE THREAD

**Issue by MarsVard** [orkestral/venom#113]
Open-wa seems to be more actively developed and maintained. This repo seems to just copy code from there and claim it their own without giving credit to the open-wa dev 🤷‍♂️

**Comment by joaosouz4** [comment]
open wa and venom came out of the same project, called [Sulla](https://github.com/danielcardeenas/sulla), so the similarity, wa went to the side of charging people for some features, we are open and we are helping each other.
