### ISSUE TITLE
forwardMessages erro

### ISSUE THREAD

**Issue by Madureiradaniel** [orkestral/venom#1138]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):*3.1.4* 
- **Browser:*Google Chrome 80.*
- **OS:*ubuntu 20.004*
- **Node version:*14.17*

forwardMessages error,  Error: Protocol error (Runtime.callFunctionOn): Promise was collected

![image](https://user-images.githubusercontent.com/35147768/133009953-5aa98715-011e-45f4-9c1b-6edba22a3a7f.png)

**Comment by mateuscdor** [comment]
Informações insuficiente.

**Comment by paulocorcino** [comment]
Hi, 
For me, too forwardMessages not working, I stay waiting for a return.

**Comment by orkestral** [comment]
fixed in version 4.0.1
