### ISSUE TITLE
Function sendText to new contact is not working with WhatsApp with massive number of opened chats

### ISSUE THREAD

**Issue by biscoitoman** [orkestral/venom#1147]
## Description

When I tried to use venom-bot to send a message for a new contact the function hangs and does nothing

## Environment

- **Venom version(s):** 3.1.4
- **Browser:** Chromium 90.0
- **OS:** Debian 10
- **Node version:** Node 16.5
## Steps to Reproduce

1. Have a massive number of opened chats ( > 2000)
2. Try to use sendText or any kind of send

## Additional context / Screenshot

The connection is on and the sendText function works on contacts that already had previous chats, and 
also works with new chats on a WhatsApp with less opened chats (~20)

**Comment by orkestral** [comment]
after some tests we verified that venom have no obvious errors, recheck your code
