### ISSUE TITLE
this repo copied Open-wa code

### ISSUE THREAD

**Issue by algoz098** [orkestral/venom#115]
I see we have several methods copied from https://github.com/open-wa/wa-automate-nodejs
Why do not give them credit?

That's a real problem in the dev community.

Credit is due

**Comment by leobevi** [comment]
https://github.com/orkestral/venom/issues/113

**Comment by algoz098** [comment]
Not related,
Theres code copied from open_wa e not the fork being told in here.

**Comment by orkestral** [comment]
> Not related,
> Theres code copied from open_wa e not the fork being told in here.

If anyone to give credit to venom is the people from WA, because before he thought about copying sulla I had already contributed in several methods, we are not clones, so much so that I pulled a sulla for Daniel to move the people to Venom, the officer, now don't talk shit, i'll block you sucker.
