### ISSUE TITLE
Bug - Send text invalid

### ISSUE THREAD

**Issue by mateuscdor** [orkestral/venom#1160]
**## Environment**

- **Venom version:** [3.1.6] Bug
-  **Venom Estavél :** [3.1.4] Bug não ocorre nesta versão
- **Browser:** [ Chrome 87, Chromium 85]
- **OS:** [ Windows 10]
- **Node version:** [14]

## Passos para reproduzir o erro

1. Usuário envia a mensagem para o BotVenom
2. BotVenom não consegue ler o caractere enviado. 
3. Caractere enviado: $ (Cifrão)
4. ![image](https://user-images.githubusercontent.com/90919904/133807841-87c09f7c-a218-4441-a805-526cd364bb31.png)

## Erro retornado pelo bot (console cmd)

Erro when sending:{}
Text: ' enter the chatId variable as an string'

## Observação final

A versão atual do bot não aceita o usuário enviar a mensagem de $ cirão

Imagem a baixo.
![erro](https://user-images.githubusercontent.com/90919904/133807317-6b2dfe3b-6994-4875-a81b-d4176806d6f9.jpg)

**Comment by orkestral** [comment]
We didn't find any error in send Text, check your code
