### ISSUE TITLE
SendListMenu not woring on Whatsapp Business

### ISSUE THREAD

**Issue by Goomer2** [orkestral/venom#1166]
## Description

The message list is not sent when using Whatsapp Business

## Environment

- **Venom version(s):**latests version on git
- **Browser:** Chrome Versão 93.0.4577.63 
- **OS:** Windows 10
- **Node version:** Node 12

## Steps to Reproduce

1. Connect to an Whatsapp Business
2. Send a List menu message
3. Verify that the message is not sent (red error icon on the right)

## Your Code

```
const list = [
    {
      title: "Pasta",
      rows: [
        {
          title: "Ravioli Lasagna",
          description: "Made with layers of frozen cheese",
        }
      ]
    },
    {
      title: "Dessert",
      rows: [
        {
          title: "Baked Ricotta Cake",
          description: "Sweets pecan baklava rolls",
        },
        {
          title: "Lemon Meringue Pie",
          description: "Pastry filled with lemonand meringue.",
        }
      ]
    }
  ];

  await client.sendListMenu('556282301217@c.us', 'Title', 'subTitle', 'Description', 'menu', list)
    .then((result) => {
      console.log('Result: ', result); //return object success
    })
    .catch((erro) => {
      console.error('Error when sending: ', erro); //return object error
    });
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/90841347/133898222-633d16cd-d7ec-48b3-b406-bbddf1ac1db5.png)

If you click on the Resend the message isn't sent.

**Comment by leonardoamaro-dev** [comment]
![image](https://user-images.githubusercontent.com/58569618/134048410-c83ca1d8-7057-4b34-99a7-0eb9aa315e8c.png)
