### ISSUE TITLE
getAllMessagesInChat return same from: even recived message

### ISSUE THREAD

**Issue by FernandoGambaro** [orkestral/venom#1167]
Hi, I think I found a bug....

## Description
const Messages = await client.getAllMessagesInChat(id, true, false)
for all message its return the same from even if the message was recived.

## Environment

- **Browser:** Chrome 91
- **OS:** Linux Fedora
- **Node version:** Node 15.14.0

    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "express-es6-template-engine": "^2.2.3",
    "express-session": "^1.17.2",
    "sessions": "^0.0.2-7",
    "venom-bot": "https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz"

## Steps to Reproduce

1. call const Messages = await client.getAllMessagesInChat(id, true, false);
2. console.log(Messages);
3. 
Message recieved
 {
    id: 'ID1',
    body: 'que tal?',
    type: 'chat',
    t: 1631937265,
    notifyName: '',
    from: 'local-whatsapp@c.us',
    to: 'SENDER@c.us',
-----
Message sent
{
    id: 'ID2',
    body: '
      'Es importante mantener el video encendido  y el nombre al pie del recuadro',
    type: 'chat',
    t: 1632004879,
    notifyName: '',
    from: 'local-whatsapp@c.us',
    to: 'SENDER@c.us',

## Your Code
        const Messages = await client.getAllMessagesInChat(chatId, true, false);
        console.log(Messages);

Thanks very much

**Comment by orkestral** [comment]
fixed in version 4.0.1
