### ISSUE TITLE
'The number does not exist' when trying to send message to a group

### ISSUE THREAD

**Issue by RafaelBini** [orkestral/venom#1168]
## Description

It can't send any message to a group, but it is able to send message to a normal contact. I'm using the version 3.1.6.

When I try to use the method sendText it returns the following error message:

```
{
  me: {
    id: '1',
    ref: '**--REMOVED--**',
    refTTL: 20000,
    wid: {
      server: 'c.us',
      user: '--REMOVED--',
      _serialized: '**--REMOVED--**@c.us'
    },
    connected: true,
    protoVersion: [ 0, 17 ],
    clientToken: '**--REMOVED--**',
    serverToken: '**--REMOVED--**',
    isResponse: 'true',
    battery: 41,
    plugged: false,
    lc: 'BR',
    lg: 'pt',
    locales: 'pt-BR',
    is24h: true,
    platform: 'android',
    phone: {
      wa_version: '2.21.18.17',
      mcc: '724',
      mnc: '005',
      os_version: '8.0.0',
      device_manufacturer: 'samsung',
      device_model: 'a5y17lte',
      os_build_number: 'R16NW.A520FXXSGCTK4'
    },
    tos: 0,
    smbTos: 0,
    pushname: 'Rafael Bini',
    stale: false,
    blockStoreAdds: false,
    isVoipInitialized: false
  },
  to: '_***********-*******_@g.us',
  erro: true,
  text: 'The number does not exist',
  status: 404
}
```

It was able to send message to groups before. This issue began today (19/09) in the morning.

## Environment

- **Venom version(s):**3.1.6
- **Browser:**Chromium
- **OS:**Windows 10
- **Node version:**Node 14.3.0

**Comment by marciodiasdeveloper** [comment]
+1

**Comment by andRodFor** [comment]
The problem is that the function to send messages to a group, internally first calls the function "checkNumberStatus" the problem is that it sends with the domain g.us and not c.us. and g.us not is a number is a group Id. This is a BUG.

**Comment by andRodFor** [comment]
Internally, before sending a message, verify that the number exists using the checkNumberStatus function.
The issue is that version 3.1.6 added a new condition that will always render the number invalid because when you send a message to a group it is with @ g.us and it is not a number like @c.us
The solution is that you look for the following line and comment it (**wapi.js)**

**`//if (404 === i.status) return WAPI.scope(e, !0, i.status, "The number does not exist");`**

**Comment by marciodiasdeveloper** [comment]
has been fixed wapi.js but not the best option

**Comment by andRodFor** [comment]
> has been fixed wapi.js but not the best option

I totally agree with you.
It is only a solution to get out of trouble.

**Comment by hendy79** [comment]
im heading to same trouble, how to fix this issue?

**Comment by andRodFor** [comment]
> im heading to same trouble, how to fix this issue?

Hello, the ideal solution is to wait for the bug to be updated. But if you need a fast temporary solution, you can locate the **wapi.js** file and comment the following line inside the function **window.WAPI.sendExist**

`//if (404 === i.status) return WAPI.scope(e, !0, i.status, "The number does not exist");`

Personally in my case I have modified the function a little more leaving it like this:

**window.WAPI.sendExist = async function (e, t = !0, n = !0) {
            if ("string" == typeof e) {
                const t = "@c.us",
                    n = "@broadcast",
                    i = "@g.us";
                if (t !== e.substr(-t.length, t.length) && n !== e.substr(-n.length, n.length) && i !== e.substr(-i.length, i.length)) return WAPI.scope(e, !0, 404, "The chat number must contain the parameters @c.us, @broadcast or @g.us. At the end of the number!");
                if (t === e.substr(-t.length, t.length) && (e.match(/(@c.us)/g) && e.match(/(@c.us)/g).length > 1 || !e.match(/^(\d+(\d)*@c.us)$/g))) return WAPI.scope(e, !0, 404, "incorrect parameters! Use as an example: 000000000000@c.us");
                if (n === e.substr(-n.length, n.length) && (e.match(/(@broadcast)/g) && e.match(/(@broadcast)/g).length > 1 || !e.match(/^(\d+(\d)*@broadcast)$/g))) return WAPI.scope(e, !0, 404, "incorrect parameters! Use as an example: 0000000000@broadcast");
                if (i === e.substr(-i.length, i.length) && (e.match(/(@g.us)/g) && e.match(/(@g.us)/g).length > 1 || !e.match(/^\d+(-)+(\d)*@g.us$/g))) return WAPI.scope(e, !0, 404, "incorrect parameters! Use as an example: 00000000-000000@g.us")
            }
            **var chatID;
            var numberExist;

            if (e.toString().toLowerCase().endsWith("@c.us")) {
                let i = await window.WAPI.checkNumberStatus(e);
                if (404 === i.status) return WAPI.scope(e, !0, i.status, "The number does not exist");
                chatID = i.id._serialized;
                numberExist = i.numberExists;
            } else {
                chatID = e;
                numberExist = true;
            }


            let a = await window.WAPI.getChat(chatID);
            if (numberExist && void 0 === a) {**
                var o = new window.Store.UserConstructor(e, {
                    intentionallyUsePrivateConstructor: !0
                });
                a = await Store.Chat.find(o)
            }
            if (!a) {
                const t = await window.Store.Chat.find(e);
                t && (a = await window.WAPI.getChat(t.id._serialized))
            }
            return i.numberExists || a.t || !a.isUser ? i.numberExists || a.t || !a.isGroup ? i.numberExists || a.t || !a.isBroadcast ? a ? (n && await window.Store.SendSeen(a, !1), t ? a : WAPI.scope(i.id._serialized, !1, 200)) : WAPI.scope(i.id._serialized, !0, 404) : WAPI.scope(e, !0, i.status, "The transmission list number does not exist on your chat list, or it does not exist at all!") : WAPI.scope(e, !0, i.status, "The group number does not exist on your chat list, or it does not exist at all!") : WAPI.scope(e, !0, i.status, "The number does not exist")
        }**

**Comment by jhonnattan123** [comment]
downgrade to 3.1.3 version

**Comment by RafaelBini** [comment]
> downgrade to 3.1.3 version

Thanks man! It fixed the issue for now.

**Comment by jonalan7** [comment]
No need to downgrade download the beta version of repor!

`npm i github:orkestral/venom`
