### ISSUE TITLE
i have seen this code before

### ISSUE THREAD

**Issue by rathmerdominik** [orkestral/venom#117]
The folks at wa automate are muggles even copy your code, just because they are free

**Comment by kingaspx** [comment]
Which codes were copied?

**Comment by dantenol** [comment]
Dude that's not okay at all. First off directly copying  someone else's code with not even giving credits. Then editing what other other people say about it...

**Comment by VincentWo** [comment]
It seems to me, that the code originated at the sulla repository, since that was no longer mantained the code was forke to this and wa automate. Or am I wrong?
