### ISSUE TITLE
Problems with sending files in BASE64

### ISSUE THREAD

**Issue by leobevi** [orkestral/venom#118]
Hello, is there any bug for sending files in base64?

When I send small files there is no problem.

I tried to send a 3mb video it doesn't send and it doesn't return any error.

Are there any limitations on file size?

**Comment by leobevi** [comment]
If I try to send an mp4 file via  client.sendFileFromBase64(numeroenvio+'@c.us', mensagemenvio, filename, caption);

It doesn't send the file, I tested several other file types and it was sent.

I tried the following code by saving the file locally
                                var  arquivo = mensagemenvio.replace('data:video/mp4;base64,', '');     
                               
                                const geraarq = await fs.writeFileSync('./'+filename, arquivo, 'base64');

                                retornoenvio = await client.sendFile(numeroenvio+'@c.us', './'+filename, filename, caption);


If you do not replace the file it is generated with failures and it is sent
// var  arquivo = mensagemenvio.replace('data:video/mp4;base64,', '');     

 if you do the replace the file is generated correctly but it is not sent
 var  arquivo = mensagemenvio.replace('data:video/mp4;base64,', '');     

Someone sending MP4 files normally?

Thanks for listening

**Comment by roysG** [comment]
same for me, any solution?
