### ISSUE TITLE
Regarding the Multi-device BETA

### ISSUE THREAD

**Issue by Mohadin** [orkestral/venom#1181]
I opened this issue to discuss the multi-device beta that just got announced and available to everyone at the latest version of the WhatsApp and WhatsApp Business beta.

We are in the final stages of supporting this beta update, and we need your help.

**Comment by orkestral** [comment]
we don't support the beta, because the version is beta, it doesn't fully work yet.

**Comment by Mohadin** [comment]
Thanks a lot.
