### ISSUE TITLE
UNPAIRED event is not received in onStateChange

### ISSUE THREAD

**Issue by MiniFris** [orkestral/venom#1182]
## Description

When exiting the session, the UNPAIRED event in onStateChange ceased to arrive.
5 days ago everything worked fine

## Steps to Reproduce

1. Scan QR code
2. Is Connected
3. Close session

Venom-bot version 3.1.7

**Comment by jhonnattan123** [comment]
downgrade to version 3.1.3

**Comment by MiniFris** [comment]
Will this be fixed in future versions?

**Comment by MiniFris** [comment]
@jonalan7 Can you answer?

**Comment by jonalan7** [comment]
@MiniFris  is returning normally! Try to uninstall and install the project again!

**Comment by jonalan7** [comment]
Or download the repor version!
`npm i github:orkestral/venom`

**Comment by MiniFris** [comment]
Thanks!
After a while, it began to work
