### ISSUE TITLE
Do you plan in support the new multi-device feature?

### ISSUE THREAD

**Issue by wellsousaaa** [orkestral/venom#1189]
**Is your feature request related to a problem? Please describe.**
I wanted to use venom-bot with the new whatsapp feature of multi-device, that allows to use whatsapp web independent of the phone connectivity, but I noticed that the tokens are not generated well and some functionalities as sending text messages have some problems when using this beta feature, so do you have plans in supporting the multi-device?

**Additional context**
https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta/?lang=en

**Comment by cardimajs** [comment]
+1

**Comment by VictorHSL** [comment]
+1

**Comment by jonalan7** [comment]
Why do you insist on using a beta version of Whatsapp? it still has bugs and issues that will need to be fixed by the developers before the definitive release. it's a waste of time trying to develop a compatibility!

**Comment by jonalan7** [comment]
**When the time is right, let's make a compatibility!**
