### ISSUE TITLE
Detect chat open on phone

### ISSUE THREAD

**Issue by CyberSinister** [orkestral/venom#1190]
Hi, I'm using venom bot as a server to send notifications to my team. I want venom to only send a message if the chat is not open on my phone i.e. I wanna detect if the chat is open on phone but I can't see any function for that. Is that possible? Is there already a function there that I missed?

**Comment by mateuscdor** [comment]
Get the PRO version
and make the request in the group.
here is just to report bugs, failures, errors.

**Comment by jonalan7** [comment]
//Check if there is chat
await client
  .checkChat(chatId)
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

**Comment by jonalan7** [comment]
**exists only if there is a conversation!**
