### ISSUE TITLE
How am I supposed to use getGroupMembers(), if there's no getAllGroups() method?

### ISSUE THREAD

**Issue by riservato-thiagomelo** [orkestral/venom#1197]
I have checked:

- discord;
- readme;
- documentation;

What I can't find: how to get all groups the account has joined.
The documentations says you have getAllContacts, but I can't find something for groups.

This is a feature open-wa bot has and I was wondering if that's the same for you.

**Comment by riservato-thiagomelo** [comment]
For what it seems, I can use **getAllChats** then filter the list by (**isGroup** === true).

Although, is it really how I am suppose to achive my goal?
Is is there any better way to achive this?

**Comment by orkestral** [comment]
fixed in version 4.0.1

**Comment by riservato-thiagomelo** [comment]
thank you so much
