### ISSUE TITLE
build venom-bot

### ISSUE THREAD

**Issue by thyagojcosta** [orkestral/venom#12]
Oi! Eu fiz uma aplicação com Electron e o venom-bot. O app funiona bem no VS Code, mas quando faço o build do electron o venom para de funiconar. Como faço o build do venom nesse caso?

-------------------------------------------------------------------------

Hi! I made an application with Electron and the venom-bot. The app works well on VS Code, but when I build the electron the venom stops working. How do I build venom in this case?

Sorry for my english "Google translator"

**Comment by orkestral** [comment]
instala apenas por nom install venom-bot e chama no arquivo do Electron

**Comment by thyagojcosta** [comment]
Eu já coloquei ele dentro do arquivo Electron, já importei de outro arquivo, mas não roda. Rodando pelo terminal ele funciona tranquilo, mas no build do Electron ele n executa.

**Comment by orkestral** [comment]
tenta com a versão 1.0.2

**Comment by thyagojcosta** [comment]
blza

**Comment by thyagojcosta** [comment]
Não consegui. Tive outra ideia aqui e vou seguir por ela.
Mas depois vou voltar pro Electron pra ver se consigo e aviso aqui!

valeu

**Comment by thyagojcosta** [comment]
Oi! Consegui resolver colocando o código do venom direto no html que usei como base no Electron. 

Funcionou perfeitamente, obrigado.

**Comment by orkestral** [comment]
De nada, qualquer coisa só chamar
