### ISSUE TITLE
sendContact is not a function

### ISSUE THREAD

**Issue by JhefersonBR** [orkestral/venom#120]
(node:9296) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: window.WAPI.getChat(...).sendContact is not a function
    at Object.window.WAPI.sendContact (<anonymous>:10:31353)

**Comment by tinyCoder32** [comment]
Same here.

**Comment by jonalan7** [comment]
**WhatsApp has been updated, the function has already been fixed by us. We will do an update soon**

**Comment by mikelustosa** [comment]
> **WhatsApp has been updated, the function has already been fixed by us. We will do an update soon**

Hello. What's the solution?

**Comment by joaosouz4** [comment]
the new function is sendContactVcard

**Comment by mikelustosa** [comment]
> the new function is sendContactVcard

Hello! How do I fix this in wapi.js?
