### ISSUE TITLE
Whatsapp in Android doesn't show all buttons if i send more than 3 options

### ISSUE THREAD

**Issue by NatsumeKaito** [orkestral/venom#1200]
## Description

When i send more than 3 buttons to android whatsapp number, i can only see the first 3 buttons, this only happends to android devices i have tested with ios and whatsapp web and theres no problem.

## Environment

- **Venom version(s):** 3.1.7
- **Browser:** 94.0.4606.71
- **OS:** Linux ubuntu 18.04
- **Node version:** 16.10

## Steps to Reproduce

1. Send message with 5 buttons
2. Check the message in my android phone
3. I can see only 3 buttons

## Your Code
`export const sendButtons  = (to: any,title:any,description:any,buttons: any[]) =>{
    return new Promise((resolve, reject) => {      
    cliente.sendButtons(`${to}@c.us`, title, buttons, description)
    .then(() => {
        resolve(true)
    })
    .catch((error: any) => {
        console.error('Error when sending: ', error); //return object error}
        reject(error)
    });
    })

}`

`const options= JSON.parse(currentQuestion[0].selection);
                for (let o of options) {
                    buttons.push({
                        "buttonText": {
                            "displayText": `${o.digit.toUpperCase()}- ${o.answer}`
                        },
                        "buttonId": `pool_${poolId}_u_${contactId}_q_${currentQuestion[0].id}_${ Math.floor(Math.random() * 10000) + 1}`
                    });
                }`

` sendButtons(WaId, currentQuestion[0].title, ` `, buttons);`

## Additional context / Screenshot
whatsapp web
![image](https://user-images.githubusercontent.com/86920136/136439492-57224349-ffc3-45de-a4b7-2a35e89c6f7f.png)

android:
![image](https://user-images.githubusercontent.com/86920136/136440196-f97a1cdb-b1b7-494a-8807-f2298657064d.png)

**Comment by mateuscdor** [comment]
The problem is in your code

**Comment by jonalan7** [comment]
**whatzapp only sends three buttons only**
