### ISSUE TITLE
How to set the user-agent

### ISSUE THREAD

**Issue by downdawn** [orkestral/venom#1201]
hello, It doesn't work when I use：
browserArgs: ['--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36']

It's still Windows, not MAC, on a connected device

thanks

**Comment by downdawn** [comment]
If I want to log in to multiple accounts, do I need to set puppeteerOptions args --proxy-server?

**Comment by orkestral** [comment]
fixed in version 4.0.1
