### ISSUE TITLE
I need code reference

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#121]
I am new to JS. (I am a python and .net guy) In the starting, the program displays QR code in CMD. Is it done by node.js or by program itself? I mean is the QR code an image? Can anyone refer me to the specific lines of code that does that job?

**Comment by leobevi** [comment]
https://github.com/orkestral/venom#exporting-qr-code

**Comment by bhavya32** [comment]
@leobevi I do not need to export from this program. I was asking for my other projects.

**Comment by joaosouz4** [comment]
the qr code comes as an ascii string and using a library called qrcode-terminal to display this format in the terminal, we were able to export this library in various formats to the same qrcode, it was a pleasure to help you use and help us better Venom
