### ISSUE TITLE
Error no open browser

### ISSUE THREAD

**Issue by Eider3a** [orkestral/venom#1214]
## Description

Hi guys, I'm trying to upload an app that uses the venom-bot library but I'm getting some errors when I try to run the app.
I'm using an AWS instance to upload the app and I'm getting the next errors. 

`Chrome not found using chromium`, I had already installed Chromium and Google Chrome. I had looked up similar issues but nothing had worked out. 

I appreciate your help, thanks a lot.

![image](https://user-images.githubusercontent.com/16583735/137761217-c107e8fc-b007-4e81-9d82-f438018111e5.png)

**Comment by chacalgbi** [comment]
I'm also having the same problem. Managed to solve?

**Comment by orkestral** [comment]
fixed in version 4.0.1
