### ISSUE TITLE
Limit Get Messages in loadAndGetAllMessagesInChat(chatId)

### ISSUE THREAD

**Issue by omar1989omb** [orkestral/venom#122]
Hi there,

Firstly, I would like to thank you for all of this! What a great tool you have created here! And all the documentation provided is amazing!
I’ve successfully implemented Venom, however I’ve found myself with a little problem when it tries to load too many messages of a single chat/group in WhatsApp. When the conversation is too big, it takes minutes for it to finish loading… Would be possible to limit the number of messages that we want to load from a single chat?
**Would be possible to add the max. number of messages loaded to the existing function: "loadAndGetAllMessagesInChat(chatId);" ?**

Many thanks.

**Comment by joaosouz4** [comment]
yes, it is possible, you just need to use another function with the name = "getAllMessagesInChat"

**Comment by joaosouz4** [comment]
like that 
client.getAllMessagesInChat(chatId, true);

**Comment by omar1989omb** [comment]
Thanks, I hadn't seen this feature.

It works perfect like this.

**Comment by 3V3RY** [comment]
Sorry guys, i didn't get how to put the max numbers of messages to get, can you help me ? Thank you very much
