### ISSUE TITLE
Method setGroupSettings() return 404 error: "The number does not exist" on execute sendExist()

### ISSUE THREAD

**Issue by felipebadr** [orkestral/venom#1232]
### Description

When trying to set group settings, returns 404 error: The number does not exist

`await client.setGroupSettings('00000000-000000@g.us', 'restrict', true);`

https://github.com/orkestral/venom/blob/a945c7c811e169757aab968b4f721ae961a1e565/src/lib/wapi/functions/set-group-settings.js#L71

**Comment by orkestral** [comment]
fixed in version 4.0.1
