### ISSUE TITLE
getAllUnreadMessages() Return an empty Array even new messages are available

### ISSUE THREAD

**Issue by Lololala09** [orkestral/venom#1234]
I did some testing in previous versions and I found that this method no longer works, Am i doing something wrong?

My code is simple as your examples:

     const messages = await client.getAllUnreadMessages();  
      console.log(messages);

My output:

 /\\\      /\\\ /\\\\\\\\\\  /\\\\\     /\\\    /\\\\\\\\    /\\\      \\\\      
 \/\\\     /\\\ \/\\\_____/  \/\\\ \\\  \/\\\  /\\\_____/\\\ \/\\\ \\ \\ \\\     
   \/\\\   /\\\  \/\\\        \/\\\ /\\\ \/\\\ \/\\\    \/\\\ \/\\\  \\\  \\\    
    \/\\\  /\\\   \/\\\\\\\\\\ \/\\\  /\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\   
      \/\\\ \\\    \/\\\_____/  \/\\\ \/\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\  
       \/\\\\\\     \/\\\        \/\\\ \ /\\\ \\\ \/\\\    \/\\\ \/\\\  \\\  \\\ 
        \/_/\\\      \/\\\\\\\\\\ \/\\\  \/_\\\\\\ \/_/\\\\\\\\\  \/\\\  \\\  \\\
          \/__/       \/________/  \/_/    \/____/    \/_______/   \/_/ \/_/ \/_/

[32minfo[39m:     [session] Initializing browser wss...
[32minfo[39m:     [session] Browser successfully opened
[32minfo[39m:     [session] checking headless...
[32minfo[39m:     [session] headless option is active, browser hidden
[32minfo[39m:     [session] Checking page...
[32minfo[39m:     [session] Page successfully accessed
- [instance: session]: Waiting page load
- [instance: session]: Checking is logged...
- [instance: session]: Authenticated
- [instance: session]: Checking phone is connected...
- [instance: session]: Connected
[]

**Comment by orkestral** [comment]
fixed in version 4.0.1
