### ISSUE TITLE
Stuck on "Connected"

### ISSUE THREAD

**Issue by ujjawalchauhan13** [orkestral/venom#1235]
## Description

Screen frozen on Connected. Doesn't proceed further than that.

## Environment

- **Venom version(s):** 3.1.11
- **Browser:** Chrome 95
- **OS:** mac OS Mojave (10.14.6)
- **Node version:** Node 12.13.0

## Steps to Reproduce

1. Running normal code as before 

## Log Output

<img width="405" alt="Screenshot 2021-10-28 at 11 17 59 AM" src="https://user-images.githubusercontent.com/23418119/139195285-9b69fbdd-5e0d-4a50-9163-62cf46c42c2e.png">

**Comment by scmntc** [comment]
replace that file works for me, thanks!!
