### ISSUE TITLE
Not save token and not change status

### ISSUE THREAD

**Issue by leandrogmuller** [orkestral/venom#1237]
When I try to create a new session, the status not change STARTING and not create the file token.

 

- **Venom version(s):** 3.1.12-alpha.0
- **Browser:** 95.0.4638.54
- **OS:** Windows 10
- **Node version:** 14.15.4

## Steps to Reproduce

1. Create session

## Log Output

session.status: qrReadSuccess

**Comment by jonalan7** [comment]
Atualizem para a versão nova! Caso continue o problema, tirem um pint.
Especifiquem melhor o problema, porque eu não entendi! Fiz testes aqui e pra min funciona normalmente!

**Comment by fernandonetom** [comment]
@jonalan7 o erro que citei acima apenas ocorre quando aciono o modo debug nas opções. O meu problema atual é que o token não está sendo salvo na pasta após scanear o qrcode.

**Comment by JoseLourenc0** [comment]
Mesmo problema de salvar o token para mim aqui

**Comment by jonalan7** [comment]
Possa ser que esse problema esteja acontecendo por falta de permissão de pasta!

**Comment by orkestral** [comment]
fixed in version 4.0.1
