### ISSUE TITLE
venon crashing due to unhandled error

### ISSUE THREAD

**Issue by doctorsanches** [orkestral/venom#1238]
When you unpair the session by cell phone, the venom starts to crash while checking the session's status because an unhandled error.

Venom version(s): 3.1.12-alpha.0
Browser: 95.0.4638.54
OS: Ubuntu 20
Node version: 14.15.4

Steps to reprocude:

Start a new cession
Scan QRCODE
Conect New Session.
Disconect by Whatsapp mobile acoount
Venon crash and restart

**Comment by orkestral** [comment]
fixed in version 4.0.1
