### ISSUE TITLE
Latitude and longitude not found in message

### ISSUE THREAD

**Issue by liawifelix** [orkestral/venom#1239]
## Description

Cannot find longitude and latitude in message type "location" in the new version. I remember it was exist in the previous version.

## Environment

- **Venom version(s):**  3.1.12
- **Browser:** Chrome 94
- **OS:** Ubuntu 20.04
- **Node version:** Node 14

## Steps to Reproduce

Send location

**Comment by can1871** [comment]
I have that same problem

**Comment by orkestral** [comment]
fixed in version 4.0.1

**Comment by can1871** [comment]
> fixed in version 4.0.1

the problem still continues
