### ISSUE TITLE
Problemas na leitura do QRCode.

### ISSUE THREAD

**Issue by Alexanddrres** [orkestral/venom#124]
Eu consigo exportar o QrCode, mas a leitura através da imagem png não está autenticando.

esse é meu código:

const fs = require('fs');

// Second create() parameter is the QR callback
bot.create('sessionMarketing', (base64Qr, asciiQR) => {
  // To log the QR in the terminal
  console.log(asciiQR);

  // To write it somewhere else in a file
  exportQR(base64Qr, 'marketing-qr.png');
});

// Writes QR in specified path
function exportQR(qrCode, path) {
  qrCode = qrCode.replace('data:image/png;base64,', '');
  const imageBuffer = Buffer.from(qrCode, 'base64');

  // Creates 'marketing-qr.png' file
  fs.writeFileSync(path, imageBuffer);
}

**Comment by jonalan7** [comment]
const fs = require('fs');
const venom = require('venom-bot');

venom.create('sessionName', (base64Qr, asciiQR) => { 
        console.log(asciiQR) // Opcional to log the QR in the terminal
        var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
            response = {};
    
        if (matches.length !== 3) {
            return new Error('Invalid input string');
        }
        response.type = matches[1];
        response.data = new Buffer.from(matches[2], 'base64');
    
        var imageBuffer = response;
    require("fs").writeFile("out.png", imageBuffer["data"], "binary", function(err) {
        if(err != null){
            console.log(err);
        }
     });
    
}, undefined, {logQR: false}).then((client) => { 
    start(client);
}).catch((erro) => { 
    console.log(erro);
});

**Comment by gutitrombotto** [comment]
Hi!
I have the same issue.
Did you find out the solution?

**Comment by joaosouz4** [comment]
@gutitrombotto  do u try to use the code above?

**Comment by Alexanddrres** [comment]
> Oi!
> Eu tenho o mesmo problema.
> Você descobriu a solução?

SIM! O CÓDIGO ACIMA DO @jonalan7 FOI A SOLUÇÃO.

**Comment by Alexanddrres** [comment]
> ```
> const fs = require('fs');
> const venom = require('venom-bot');
> 
> venom.create('sessionName', (base64Qr, asciiQR) => { 
>         console.log(asciiQR) // Opcional to log the QR in the terminal
>         var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
>             response = {};
>     
>         if (matches.length !== 3) {
>             return new Error('Invalid input string');
>         }
>         response.type = matches[1];
>         response.data = new Buffer.from(matches[2], 'base64');
>     
>         var imageBuffer = response;
>     require("fs").writeFile("out.png", imageBuffer["data"], "binary", function(err) {
>         if(err != null){
>             console.log(err);
>         }
>      });
>     
> }, undefined, {logQR: false}).then((client) => { 
>     start(client);
> }).catch((erro) => { 
>     console.log(erro);
> });
> ```

OBRIGADO!

**Comment by gutitrombotto** [comment]
Ok, thank you for the answers!

I have tried the code of  @jonalan7 but it does not work for me.
I 'm using and old cellphone (Samsung Galaxy J3). Maybe this could be the problem.

I will keep trying.

**Comment by Alexanddrres** [comment]
> Ok, obrigado pelas respostas!
> 
> Eu tentei o código de @ jonalan7 mas não funciona para mim.
> Estou usando um celular antigo (Samsung Galaxy J3). Talvez esse seja o problema.
> 
> Eu irei continuar a tentar.

Não acho que o problema seja a versão do seu celular.
Você pode me mandar o seu código pra mim analisar e quem sabe poder te ajudar?

**Comment by Alexanddrres** [comment]
> > Ok, obrigado pelas respostas!
> > Eu tentei o código de @ jonalan7 mas não funciona para mim. 
> > Estou usando um celular antigo (Samsung Galaxy J3). Talvez seja o problema.
> > Eu irei continuar a tentar.
> 
> Não acho que o problema seja a versão do seu celular.
> Você pode me mandar o seu código para mim analisar e quem sabe poder te ajudar?

Eu não sou muito experiente em node e nem nessa API, mas posso usar o pouco do que sei para ajudar você.
