### ISSUE TITLE
Beta after scan successfully but session in tokens folder session not generate. How to use whatsup Beta

### ISSUE THREAD

**Issue by Akash-Rathore** [orkestral/venom#1240]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://orkestral.github.io/venom/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
- Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by bhavya32** [comment]
Beta is currently not support. @jonalan7 I wanted to inform you that I have seen some screenshots where we can not opt out of the beta. It is getting mainstream maybe.

**Comment by orkestral** [comment]
fixed in version 4.0.1
