### ISSUE TITLE
Stuck on Checking page status

### ISSUE THREAD

**Issue by LuizTokuhara** [orkestral/venom#1243]
## Description
Stuck on Checking page... when connecting.

## Environment

- **Venom version(s):** 3.1.12
- **Browser:** Chromium
- **OS:** CentOS
- **Node version:** 14

## Steps to Reproduce

1. Try to connect and the status will stop in Checking page, will not continue.

**Comment by juniorppp** [comment]
estou com o mesmo problema ele conecta da que esta conectado, mas não gera a session em tokens e não roda o resto do codigo.

**Comment by fly2012** [comment]
The same to me.

**Comment by rn2web** [comment]
mesma coisa aqui.

**Comment by orkestral** [comment]
fixed in version 4.0.1
