### ISSUE TITLE
store tokens outside of CWD

### ISSUE THREAD

**Issue by acognigni-evotecnia** [orkestral/venom#1247]
**Is your feature request related to a problem? Please describe.**
i want to have two projects: one recieves messages and the ther one sends messages. If i created both then tey would keep stealing each other sessions. i'd like to have the tokens outside of both so they can share them

**Describe the solution you'd like**
i'd like for the `mkdirFolderToken` parameter for the `create` function to accept relative and absolute paths.
right now it does the cwd+pathparameter which means that i can't do `../tokens`

**Describe alternatives you've considered**
- if it runs on linux i can use sfot and hard links
- - runing both tasks i nt he same project

**Comment by orkestral** [comment]
fixed in version 4.0.1
