### ISSUE TITLE
Multidevices feature out of beta

### ISSUE THREAD

**Issue by MiniFris** [orkestral/venom#1249]
Ios now has an update to Whatsapp that includes Multidevices as the primary way to connect. But Venom is not yet able to receive a session with this feature. When will the Multidevices feature be supported?

**Comment by jeferssonlemes** [comment]
In IOS is now coming by default the mult-device

**Comment by lukasportal** [comment]
having issues too
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1
    at Generator.next (<anonymous>)
    at c (serviceworker.js:1)
    at o (serviceworker.js:1)

as soon as the wapi gets injected

**Comment by jeferssonlemes** [comment]
@lukasportal the same here

**Comment by douglasduarte** [comment]
@lukasportal the same here :\

**Comment by lukasportal** [comment]
more update on this
It seems that this issue with partial response isn't really what blocks it
i've inspected the messages sent in the websocket, and when you scan the QR Code, the following message comes up and nothing else:

s1,["Cmd", {type: "upgrade_md_prod", version: "2.2126.11"}]

the current version (using window.Debug.VERSION) is 2.2142.12

not sure what that message means
it can't be asking to downgrade to 2.2126.11 lol

**Comment by lukasportal** [comment]
it turns out this isn't a problem at all
my only problem right now with multi device is that any communication with the server never returns anything
for example 
Store.WapQuery.queryExist("1111111111@c.us")

just hangs

**Comment by jeferssonlemes** [comment]
still investigating the problem seems to be due to the fact that Store.Me.wid in MD version is always null.

right on some calls I'm getting the following error:
Uncaught (in promise) Error: CHAT_JID: invalid jid type: Not an instance of WID

**Comment by lukasportal** [comment]
a bunch of problems i'm seeing
if you inject WAPI from a logged in instance, Store.Conn will be undefined
you only get that if you inject it at the qr code page and then move to logged in


i'm thinking there will be a lot more problems like that and I'm freaking out lol
any luck with multi device?

**Comment by jeferssonlemes** [comment]
@lukasportal 
I always did the wapi injection after being connected inside whatsapp, after reading the QrCode, in the case in your tests you are injecting this at the time of pairing?

**Comment by jonalan7** [comment]
I'm already solving this question

**Comment by oltanalkan** [comment]
@jonalan7 Will there be an update in which all functions will work soon?

**Comment by jonalan7** [comment]
> @jonalan7 In the beta (MD) version, will there be an update to work with all functions soon?

yes!

**Comment by orkestral** [comment]
fixed in version 4.0.1

**Comment by lukasportal** [comment]
> > @jonalan7 In the beta (MD) version, will there be an update to work with all functions soon?
> 
> yes!

Can you please elaborate on how this was fixed? From what I can see in the commits, you just made sure it was a clean session, but even when I had a fresh clean session before, the calls to ```Store.WapQuery.queryExist()``` would still hang and never return

there’s nothing to be done to wapi.js?

**Comment by DrDeee** [comment]
@orkestral Bei mir hängt venom nun bei `Checking phone is connected...`.

**Comment by DrDeee** [comment]
After a while comes `Phone not connected`.

**Comment by DrDeee** [comment]
The full log is
```
[[ Phone says: connected ]]
× [instance: session]: Page Closed
× [instance: session]: Checking QRCode status...
(node:7588) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at ExecutionContext._evaluateInternal (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluateHandle (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:151:21)
    at WaitTask.rerun (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7588) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at ExecutionContext._evaluateInternal (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluateHandle (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:151:21)
    at WaitTask.rerun (C:\My\App\Path\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:7588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
× [instance: session]: Failed to authenticate
× [instance: session]: Unknow error
```

As soon as you restart the app, it shpws `Phone not connected`.
