### ISSUE TITLE
Error after read QR Code

### ISSUE THREAD

**Issue by vicfelipe** [orkestral/venom#1251]
## Description

Error after read QR Code.
Device is connected, but doesn't have response from client.

PS: It was working yesterday

## Environment

- **Venom version(s):** 3.1.12
- **Browser:** Chrome 95
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

Install and run a command "npm run dev"

## Log Output

![image](https://user-images.githubusercontent.com/12769395/140572002-b91bf3ac-3bf2-49e1-b71f-81c39664e895.png)

**Comment by helixcloud1337** [comment]
Same here.. maybe because whatsapp is update? 

I always like this
![image](https://user-images.githubusercontent.com/64077954/140647023-978f5a67-2b1e-4ea2-95b3-9e14dc6e849e.png)

**Comment by romulloleal** [comment]
Venom will update soon for version 4.

**Comment by jccalbuquerque** [comment]
I have the same problem.
I updated to version 3.2.0 and the error persists.
The qrcode is generated and read on the smartphone.
But the token is not generated and the status becomes QRCODE...

**Comment by jccalbuquerque** [comment]
I updated to version 4.0.0 and it worked 100% thanks.

**Comment by AlexsandroZanella2** [comment]
I have the same problem.
The token file is not created and the create function returns nothing, although it prints the Connected warning.
Node: 12,14,16.
W7, W10,W11,server 2012,2016,2019.
venom: 3.1.12, 3.2.0.

Is it any change in whatsapp web in the last few days

**Comment by AlexsandroZanella2** [comment]
Version 4.0.0 worked perfectly.

**Comment by orkestral** [comment]
fixed in version 4.0.1
