### ISSUE TITLE
checkNumberStatus throw Error on non-exist contact

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#1252]
## Description

Before sendMessage I call
`````
const chatStatus = await client.checkNumberStatus(chatId);
`````
if chatId exist - all ok
else I receive error in catch block and err contain chatStatus data with 404
`````
{
  id: {
    server: 'c.us',
    user: 'NUMBER',
    _serialized: 'NUMBER@c.us'
  },
  status: 404,
  isBusiness: false,
  canReceiveMessage: false
}
`````

## Environment

- **Venom version(s):** [3.1.12]
- **Browser:** [Chrome]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by orkestral** [comment]
fixed in version 4.0.1
