### ISSUE TITLE
getStore encrypted?

### ISSUE THREAD

**Issue by IanosJunior** [orkestral/venom#1255]
Hi, I use part of this project only to send messages through whatsapp. I saw that getStore was encrypted.
Are there any changes in the way to protect this project?

**Comment by IanosJunior** [comment]
I think it's obfuscated.

**Comment by orkestral** [comment]
no

**Comment by IanosJunior** [comment]
@orkestral  Desculpe pela insistência mas realmente o código do getStore não está legível. Está diferente de todos os outros JS.
Se puder me ajudar, ficarei muito grato.
