### ISSUE TITLE
Bug on SendText

### ISSUE THREAD

**Issue by matheusm821** [orkestral/venom#1257]
SendText

![image](https://user-images.githubusercontent.com/60859810/140782473-fff3a11c-335d-4f67-a35d-3cd254b7c93a.png)

**Comment by fernandopraise** [comment]
amigo tive um erro parecido.. dai usei 

venom
  .create('name')
  .then((client) => start(client))
  **.catch((erro) => {
    console.log(erro);
  });**

para tratar o erro... porem apareceu  outro de nao conseguiur acessar o web.whastapp

Error when trying to access the page: "https://web.whatsapp.com"

**Comment by mateuscdor** [comment]
Sua postagem está totalmente limitada.
Não possui a origem do código.
versão do venom 
sistema operacional..

O Venom está funcionando normalmente.

**Comment by matheusm821** [comment]
É a ultima versão do Venom 4.0.0, Windows 10

**Comment by fernandopraise** [comment]
Também não estou conseguindo logar, apos a atualização do venom para  4.0... nomeu caso Error accessing the page: "https://web.whatsapp.com"
Error when trying to access the page: "https://web.whatsapp.com"

**Comment by orkestral** [comment]
fixed in version 4.0.1
