### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by mateuscdor** [orkestral/venom#1259]
- **Venom version(s):**4.0.1
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
----------------------------------------------------------------------------------------

**A versão atual do 4.0.1 (Não está funcionando!)**

### e não é possivel encontrar. 

![image](https://user-images.githubusercontent.com/90919904/140843721-46913712-a631-4927-a68b-fa6c3da9be02.png)

### segue abaixo o retorno do debugger:

![image](https://user-images.githubusercontent.com/90919904/140845187-c6f48a00-18bd-4339-978f-cedb331bd27a.png)

C:\Program Files\nodejs\node.exe .\index.js
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (c:\Users\MR\Desktop\Telecom\lib\fs.js:723:3)
    at tryReadSync (c:\Users\MR\Desktop\Telecom\lib\fs.js:433:20)
    at readFileSync (c:\Users\MR\Desktop\Telecom\lib\fs.js:479:19)
    at Object.<anonymous> (c:\Users\MR\Desktop\Telecom\node_modules\venom-bot\dist\controllers\initializer.js:322:80)
    at step (c:\Users\MR\Desktop\Telecom\node_modules\venom-bot\dist\controllers\initializer.js:98:23)
    at Object.next (c:\Users\MR\Desktop\Telecom\node_modules\venom-bot\dist\controllers\initializer.js:79:53)
    at fulfilled (c:\Users\MR\Desktop\Telecom\node_modules\venom-bot\dist\controllers\initializer.js:70:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {errno: -4068, syscall: 'read', code: 'EISDIR', stack: 'Error: EISDIR: illegal operation on a directo…ions (node:internal/process/task_queues:96:5)', message: 'EISDIR: illegal operation on a directory, read'}
code: 'EISDIR'
errno: -4068
syscall: 'read'
message: 'EISDIR: illegal operation on a directory, read'
stack: 'Error: EISDIR: illegal operation on a directory, read\n    at Object.readSync (node:fs:723:3)\n    at tryReadSync (node:fs:433:20)\n    at readFileSync (node:fs:479:19)\n    at Object.<anonymous> (c:\\Users\\MR\\Desktop\\Telecom\\node_modules\\venom-bot\\dist\\controllers\\initializer.js:322:80)\n    at step (c:\\Users\\MR\\Desktop\\Telecom\\node_modules\\venom-bot\\dist\\controllers\\initializer.js:98:23)\n    at Object.next (c:\\Users\\MR\\Desktop\\Telecom\\node_modules\\venom-bot\\dist\\controllers\\initializer.js:79:53)\n    at fulfilled (c:\\Users\\MR\\Desktop\\Telecom\\node_modules\\venom-bot\\dist\\controllers\\initializer.js:70:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
[[Prototype]]: Object
Process exited with code 1

```

### alterei também o nome de administrator, apesar de todas as alterações sem sucesso.

**_Será necessário debuggar profundamente para ver a origem do problema._**

Segue abaixo o scripr utilizado.
Obs: é o mesmo script da pagina inicial a diferença que este o multdevice é true.

--------------------------------------------------------------------
`const venom = require('venom-bot');

venom
  .create({
    session: 'sessionname', //name of session
    multidevice: true, // for version not multidevice use false.(default: true)
    
    folderNameToken: 'tokens', //folder name when saving tokens
    mkdirFolderToken: 'tokens', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
    headless: false, // Headless chrome
    devtools: false, // Open devtools by default
    useChrome: true, // If false will use Chromium instance
    debug: true, // Opens a debug session
    logQR: true, // Logs QR automatically in terminal
    browserWS: '', // If u want to use browserWSEndpoint
    browserArgs: [''], //Original parameters  ---Parameters to be added into the chrome browser instance
    puppeteerOptions: {}, // Will be passed to puppeteer.launch
    disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
    disableWelcome: true, // Will disable the welcoming message which appears in the beginning
    updatesLog: true, // Logs info updates automatically in terminal
    autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
    createPathFileToken: true //
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}`

**Comment by orkestral** [comment]
there is no bug, review your project and only open the issue if you are sure of the bug, otherwise you will be blocked

**Comment by mateuscdor** [comment]
Jhon, o código não é do meu projeto 
e do seu proprio script que está pagina inicial como eu descrevi.

Não é possivel utilizar o venom multidevice.
