### ISSUE TITLE
checkNumberStatus don't work

### ISSUE THREAD

**Issue by IanosJunior** [orkestral/venom#1263]
## Description

Sempre retornando 404.

## Environment

- **Venom version(s):** [4.0.1]
- **Browser:** [Chrome 95]
- **OS:** [Windows 10]
- **Node version:** [16.13.0]

## Steps to Reproduce

const result = await Store.WidFactory.createWid(id);
    if (result.status === 404) {
      throw err;
    }
    if (result.jid === undefined) {
      throw err; //sempre entra aqui
    }

**Comment by lukasportal** [comment]
same here
WidFactory.createWid() will never return the status property

also, using WapQuery.queryExist() never returns anything

**Comment by fernandopraise** [comment]
Olá eu estou usando assim

const profile =  await client.getNumberProfile(telefone);

**Comment by lukasportal** [comment]
getNumberProfile uses WapQuery.queryExist() behind the scenes

https://github.com/orkestral/venom/blob/81568ed57ea2b35cd28ae9de2225a51b245a6ca1/src/lib/wapi/functions/get-number-profile.js

and that function isn't working for me
it just hangs without returning anything

**Comment by lukasportal** [comment]
Any idea @orkestral ?

**Comment by orkestral** [comment]
fixed in version 4.0.2
