### ISSUE TITLE
How to check if number exists on MD?

### ISSUE THREAD

**Issue by lukasportal** [orkestral/venom#1264]
Is there a way to check if a number exists on MD? 
```WapQuery.queryExist()``` isn't working anymore (never returns anything)

**Comment by MiniFris** [comment]
Also getHostDevice does not return the session phone number.

**Comment by AlexsandroZanella2** [comment]
Which version are you using? node 14, 12...? Pass an example to repeat too

**Comment by lukasportal** [comment]
node v16
i believe there's nothing to do with the node js version
it has to do with the WAPI script that gets injected into whatsapp
maybe Store.WapQuery has an old reference, maybe WhatsApp MD uses a different function to query a number, idk
getting this queryExist working would be the last thing i needed for having MD support


the example is simply:
```window.Store.WapQuery.queryExist('anyvalidnumberhere@c.us')```

**Comment by lukasportal** [comment]
anyone?

**Comment by fernandopraise** [comment]
Eu estou usando dessa forma...

const profile =  await  client.getNumberProfile(telefone);

**Comment by orkestral** [comment]
fixed in version 4.0.2
