### ISSUE TITLE
The tokens\session folder is created

### ISSUE THREAD

**Issue by MiniFris** [orkestral/venom#1265]
If multidevice = true, the tokens folder is created regardless of the createPathFileToken parameter. Is it possible to fix this?

Venom version: 4.0.1

My settings:
disableWelcome: true,
autoClose: 180000,
logQR: false,
createPathFileToken: false,
multidevice : true

**Comment by AlexsandroZanella2** [comment]
Pelo qFrom what I've seen, this option should be called: createFileToken.
It only serves to decide whether or not to create the file. For now, if you don't want the folder to be created, set folderNameToken : ''

**Comment by MiniFris** [comment]
Thanks!
