### ISSUE TITLE
[BUG] Many business accounts are unable to connect when reading qrcode.

### ISSUE THREAD

**Issue by rafosolima** [orkestral/venom#1266]
## Description

Na versão 3.1.12, eu consigo normalmente connectar varios whatsapp business ao venom, depois da atualização para o 4.0.1 o mesmo não acontece.

## Environment

- **Venom version(s):** [4.0.1]
- **Browser:** [e.g. Chrome 95]
- **OS:** [Windows 10 - WSL2.0]
- **Node version:** [Node v14.18.1]

## Steps to Reproduce

1. Conectar whatsapp normal
2. Conectar whatsapp business
3. Ele não consegue conectar e cancela a ação não exibindo erro.
OBS.: Todo o processo de ler o qrcode funciona, mas na exata hora que conectar ao whatsapp ele entra em espera e não conectar.

**Comment by neocomun** [comment]
Mesmo problema

**Comment by bhavya32** [comment]
@jonalan7 @orkestral Will the beta version be supported in this repo? Latest WhatsApp Business Beta version does not allow you to leave multi device beta.

**Comment by rafosolima** [comment]
Com base na relase 4.0.2 o problema do whatsapp beta e multiplos devices foi corrigido.
