### ISSUE TITLE
VENOM IS NOT SAVING THE TOKENS

### ISSUE THREAD

**Issue by Yash094** [orkestral/venom#1273]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://orkestral.github.io/venom/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
- Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by downdawn** [comment]
Same question. and
checkNumberStatus is not work

**Comment by lucianodltec** [comment]
It seems version 4.01 have a lot of issues/bugs or Whatsapp changed its api?

**Comment by downdawn** [comment]
version 3.1.12 is ok

**Comment by lucianodltec** [comment]
Version 3.1.12 is better, but have some issues also, like quotedMsg.

Version 4 have support for new connection type from WA, so I really need it.

I'm very interesting to help, but dont know how to run and debug venom-bot lib. Is any doc about it?

**Comment by downdawn** [comment]
4.0.2-alpha.0 (2021-11-16)

**Comment by dev-ispa** [comment]
Same problem here - v4 is not saving token and earlier version doesn't work with new connection type WA.

**Comment by orkestral** [comment]
fixed in version 4.0.2
