### ISSUE TITLE
quotedMsg is missing in received message object

### ISSUE THREAD

**Issue by sarvan27** [orkestral/venom#1276]
## Description

In onMessage event, the reply message doesn't have quotedMsg, only it has quotedParticipant. So can't able to find which message I'm getting a reply.

## Environment

- **Venom version(s):** 3.1.12 & 4.0.1 (tested in both)
- **OS:** Windows 11
- **Node version:** Node 14

## Steps to Reproduce

```
venom
    .create(
      sessionName,
      (base64Qrimg) => {
        console.log(base64Qrimg);
      },
      undefined,
      {
        logQR: true,
        autoClose: 0,
      }
    )
    .then((cli) => {
      cli.onMessage((message) => {
        console.log("message", message);
      });
    })
    .catch((erro) => {
      console.log(erro);
    });
```

**Comment by orkestral** [comment]
fixed in version 4.0.2

**Comment by sarvan27** [comment]
version 4.0.2 also the same 

![image](https://user-images.githubusercontent.com/48104744/142370902-6dc2ac2d-e334-40cc-b038-ec6b114b71fa.png)

I'm asking for this kind of reply message, not able to find for which i'm getting reply

**Comment by fernandonetom** [comment]
I'm with the same problem
