### ISSUE TITLE
Function getMe() don't work

### ISSUE THREAD

**Issue by IanosJunior** [orkestral/venom#1277]
## Description

Function getMe() don't work

## Environment

- **Venom version(s):** [4.0.1]
- **Browser:** [Chrome 95]
- **OS:** [Windows 10]
- **Node version:** [16.13.0]

## Log Output

Cannot read properties of undefined (reading 'all')

**Comment by mateuscdor** [comment]
Informação insuficiente
poste o script que foi utilizado.

**Comment by orkestral** [comment]
fixed in version 4.0.2
