### ISSUE TITLE
Function SendButtons don't work

### ISSUE THREAD

**Issue by IanosJunior** [orkestral/venom#1278]
## Description

Function SendButtons don't work

## Environment

- **Venom version(s):** [4.0.1]
- **Browser:** [Chrome 95]
- **OS:** [Windows 10]
- **Node version:** [16.13.0]

## Log Output
![Buttons_Error](https://user-images.githubusercontent.com/34457222/141994978-3c9968da-4dbd-4d9a-acff-b83bab516b84.png)

The buttons don't show

**Comment by mateuscdor** [comment]
Informação insuficiente para analise.
poste o script que foi utilizado.

**Comment by IanosJunior** [comment]
**Code:**
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: true // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
        client.sendButtons('553732621959@c.us','Vc tem uma consulta com o dr fulano',
           [{ buttonText: { displayText: 'Confirmar' } },{ buttonText: { displayText: 'Cancelar' } },], 'Escolha uma opcao')
           .then((result) => {
            console.log('Result: ', result); //return object success
          })
          .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
          });
    }
  });
}

**Log:**

Error when sending:  {
  me: {
    id: '1',
    ref: '2@OJGYKnnf6T2MArtKM29X+S1j/zo4H6iqcmuERu61qabAeolAiReSfS8xGyknv6LW8UZ0TWBTxUVPOQ==',
    refTTL: 60000,
    platform: 'android',
    pushname: 'Ianos Junior',
    blockStoreAdds: false,
    isVoipInitialized: false
  },
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '553732621959',
      _serialized: '553732621959@c.us'
    },
    id: 'RE2Z5OLRD2OPO3AMO8TI',
    _serialized: 'true_553732621959@c.us_RE2Z5OLRD2OPO3AMO8TI'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}

**Comment by mateuscdor** [comment]
Problema existe confirmado.

**Comment by orkestral** [comment]
fixed in version 4.0.2

**Comment by mateuscdor** [comment]
Não foi resolvido
not resolved.

**Comment by IanosJunior** [comment]
@orkestral @mateuscdor
Funciona para um dispositivo.
Para multiplos dispositivos continua com erro.

**Comment by liperg** [comment]
Same issue for me..

Works only with `multidevices = false`.

**Comment by SLotman** [comment]
Same for me, only works with multidevices = false. Why was this closed?

**Comment by jeferssonlemes** [comment]
same problem

**Comment by guimaraesdiego** [comment]
same problem

**Comment by felipecarioca** [comment]
same problem

**Comment by sandro-salles** [comment]
+1 ... not working even on nightly ....

`{
  err: {
    me: {},
    to: {
      fromMe: true,
      remote: [Object],
      id: 'K1FVJBIL0HAUSHLOTDD5',
      _serialized: 'true_554888691429@c.us_K1FVJBIL0HAUSHLOTDD5'
    },
    erro: true,
    text: null,
    status: 'ERROR_UNKNOWN',
    result: null
  }
}
`

**Comment by Dima564** [comment]
+ getting this while sending messages

**Comment by ZEZAP** [comment]
facing the same problem here... it doesnt work even with multidevice: false

Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '258844075216',
      _serialized: '258844075216@c.us'
    },
    id: '67LQRQMJFLI7MVIEFAWW',
    _serialized: 'true_258844075216@c.us_67LQRQMJFLI7MVIEFAWW'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}

**Comment by Andley302** [comment]
Same problem:

Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '5512996562935',
      _serialized: '5512996562935@c.us'
    },
    id: 'NNEVRYSZ7AYJC2P3LXN2',
    _serialized: 'true_5512996562935@c.us_NNEVRYSZ7AYJC2P3LXN2'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}

**Comment by renenucci** [comment]
Same here.

ERROR_UNKNOWN

**Comment by MarcoLimaSistemas** [comment]
Same here.

**Comment by Raggzinn** [comment]
Same here.

**Comment by SLotman** [comment]
Yup. Broken no matter if multidevice set to true or false now.
SendImage is failing for me too, even on nightly.

**Comment by renenucci** [comment]
> Yup. Broken no matter if multidevice set to true or false now. SendImage is failing for me too, even on nightly.

Yep, stoped work 3 days ago (send image)

**Comment by w7br** [comment]
I'm also having the same error in version 4.2.0

version 4.2.0 has some vulnerabilities, which when fixed with NPM AUDIT FIX returns the VENOM version to 4.0.3

**Comment by w7br** [comment]
**Version 4.2.0**

Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '5518991527279',
      _serialized: '5518991527279@c.us'
    },
    id: 'NFJAP56BXDHSDZFKH2NQ',
    _serialized: 'true_5518991527279@c.us_NFJAP56BXDHSDZFKH2NQ'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}

**Comment by w7br** [comment]
Version 4.2.0

Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '5518991527001',
      _serialized: '5518991527002@c.us'
    },
    id: 'NFJAP56BXDHSDZFKH2NQ',
    _serialized: 'true_5518991527002@c.us_NFJAP56BXDHSDZFKH2NQ'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}

**Comment by w7br** [comment]
> Same problem:
> 
> Error when sending: { me: {}, to: { fromMe: true, remote: { server: 'c.us', user: '5512996562935', _serialized: '[5512996562935@c.us](mailto:5512996562935@c.us)' }, id: 'NNEVRYSZ7AYJC2P3LXN2', _serialized: 'true_5512996562935@c.us_NNEVRYSZ7AYJC2P3LXN2' }, erro: true, text: null, status: 'ERROR_UNKNOWN', result: null }

Conseguiu resolver?

**Comment by w7br** [comment]
C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: Error: wid error: invalid wid: 0000000000@broadcast
    at new d (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:71:24915)
    at new s (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:71:29431)
    at window.WAPI.window.WAPI.sendExist (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33181)
    at async window.WAPI.window.WAPI.sendButtons (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:62549)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\api\layers\sender.layer.js:312:28

**Comment by w7br** [comment]
C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286
throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
^

Error: Evaluation failed: Error: wid error: invalid wid: 0000000000@broadcast
at new d (https://web.whatsapp.com/bootstrap_qr.14fc553e56546513bea58c.js:71:24915)
at new s (https://web.whatsapp.com/bootstrap_qr.14fc553e56546513bea58c.js:71:29431)
at window.WAPI.window.WAPI.sendExist (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33181)
at async window.WAPI.window.WAPI.sendButtons (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:62549)
at ExecutionContext._ExecutionContext_evaluate (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ExecutionContext.evaluate (C:\Users\HP\Desktop\bot-venom-allexus\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
at async C:\Users\HP\Desktop\bot-venom-allexus\node_modules\venom-bot\dist\api\layers\sender.layer.js:312:28

**Comment by itclubonline** [comment]
Not able to send button and list from business whatsapp. Any fix.....

**Comment by gsmatheus** [comment]
The same here:

```
{
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '5571****9549',
      _serialized: '5571****9549@c.us'
    },
    id: 'R4C8F7UD9XG2ERPXENWM',
    _serialized: 'true_5571****9549@c.us_R4C8F7UD9XG2ERPXENWM'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}
```

**Comment by WictorFlashvolve** [comment]
olá pessoal.
alguém conseguiu resolver o erro ao tentar enviar botões?
estou usando a função conforme a documentação, ela não me retorna erro,
mas não me traz nenhuma mensagem no whatsapp.
Por favor, alguém poderia compartilhar uma solução para este caso?

`if (message.body === 'Hi2' && message.isGroupMsg === false){
        let buttons = [
          {
            "buttonText1": {
              "displayText": "Button 1"
              }
            },
          {
            "buttonText2": {
              "displayText": "Button 2"
              }
            },
          ]
          const data = JSON.stringify(buttons)
        client.sendButtons('xxxxxxxxxxxx@c.us', 'Title', buttons, 'Description')
          .then((result) => {
            console.log('Result: ', result); //return object success
          })
          .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
          });
      }`

**Comment by Ah98lg** [comment]
@WictorFlashvolve no local do 'xxxxxxxxxxxx@c.us', você deve por message.from, ou se preferir o numero que quer enviar a mensagem

**Comment by WictorFlashvolve** [comment]
o xxxxxxxxxxx é apenas para não postar dados confidenciais. deve ser alguma configuração da lib que está com problemas.

**Comment by Divino67** [comment]
Estou usando a versão 4.3 e com o mesmo problema ainda, tanto com multidevice true ou false.
I'm using version 4.3 and still having the same problem, both with multidevice true or false.

**Comment by SahilAggarwal2004** [comment]
Any solution to this?

**Comment by junimheller** [comment]
onde vcs trocam o multidevice pra true e false?
estou recebendo o mesmo problema, onde o proprio exemplo não retorna os botoes, de acordo com a documentação.

**Comment by SLotman** [comment]
> onde os senhores trocam o multidevice = true or false?

Isso era em uma versão antiga. Provavelmente não existe mais a possibilidade de setar essa opção, sendo sempre multidevice.

E até onde sei o whatsapp web está bloqueando o envio de botões, não há muito o que fazer quanto à isso. Só libs que se comunicam direto com o servidor, sem uso de navegador/versão web são capazes de fazer isso - mas também mais arriscadas de serem banidas.

**Comment by allanalcantara** [comment]
Facil de resolver senhores, é só para devices obviamente vocês conseguem visualisar o texto, encima do queo colega falou lá, segue abaixo um exemplo que exibe os botões:
`await client.sendButtons(sender.id, 'Você deseja Sair do Processo?',
                            [{ buttonText: { displayText: 'Confirmar' } },{ buttonText: { displayText: 'Cancelar' } },], 
'Você tem certeza disso?'
                        );`
                        conforme imagem abaixo é o que exibe para você:
                        [
![Imagem do WhatsApp de 2023-10-09 à(s) 00 22 38_4eed4f0b](https://github.com/orkestral/venom/assets/33518897/2dc43782-a10a-4475-a88a-8909ce9971b6)
](url)

**Comment by WebertMaciel-Antares** [comment]
Bom Dia Pessoal, alguem ai ja tem uma solução para esta enviando os botoes ? Estou tendo problema. Estou utilizando o node.js
