### ISSUE TITLE
O token não esta sendo salvado

### ISSUE THREAD

**Issue by LennonSantos** [orkestral/venom#1279]
## Description

O token não esta sendo salvo quando realizado a leitura do qrcode, assim solicitando sempre um novo qrcode em caso de reiniciar o serviço.

## Environment

- **Venom version(s):** 4.0.2.alpha
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:**Linux e Mac
- **Node version:**Node 12 e 14

## Steps to Reproduce

1. Ler QRCODE

## Log Output

```
Error: ENOENT: no such file or directory, open './session-name/DevToolsActivePort'
```

**Comment by orkestral** [comment]
fixed in version 4.0.2
