### ISSUE TITLE
erro no linux 

### ISSUE THREAD

**Issue by dcorteztec** [orkestral/venom#128]
Alguém já rodou no linux ? estou tomando esse erro, ta rodando de boas no windows

0|back     | [0902/002722.334702:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
0|back     |
0|back     |
0|back     | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|back     |
0|back     |     at onClose (/opt/cronmsgzap/backend-chatbox-zap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
0|back     |     at Interface.helper_js_1.helper.addEventListener (/opt/cronmsgzap/backend-chatbox-zap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)

**Comment by hotsteed** [comment]
A good way to solve this is create another user to run your service.(CentOS)

**Comment by dcorteztec** [comment]
I searched on google about the error, they indicated this adjustment

const browser = await puppeteer.launch({args: ['--no-sandbox']});

**Comment by dcorteztec** [comment]
I stopped using root to start the component
