### ISSUE TITLE
Issue regarding getChatIsOnline() returning always false after 2 minutes

### ISSUE THREAD

**Issue by aaryanchauhann** [orkestral/venom#1280]
## Description

When we try to fetch the user online/offline status using `getChatIsOnline()`, **with multi device as `true`**, it returns perfectly fine for the first two minutes after connecting to the client, but after that it always returns false whether the user is online or offline.

It works perfectly fine with multi-device as `false`, this is only a bug while using multi-device

## Environment

- **Venom version(s):** 4.0.1
- **Browser:** Chrome 87
- **OS:** Ubuntu 18
- **Node version:** 16.13.0

**Comment by mateuscdor** [comment]
Informação insuficiente para o desenvolvedor analisar.
Poste o script utilizado.

**Comment by aaryanchauhann** [comment]
@mateuscdor 
`
  function checkOnline(number, name){
      setInterval(function(){
        client_obj.getChatIsOnline(number + '@c.us').then((response) => {
                var data = online_data[number];
              if(response === true){
                  if(data[0] == false){
                      // came online
                      console.log('[' + datetime() + '] ' + name + ' came online');
                      online_data[number][0] = true;
                      online_data[number][1] = timestamp();
                  }
              }else{
                  if(data[0] == true){
                      online_data[number][0] = false;
                      var online_time = (timestamp() - online_data[number][1]) / 1000;
                      online_data[number][2] = online_data[number][2] + online_time;
                      console.log('[' + datetime() + '] ' + name + ' went offline, was online since ' + online_time + ' seconds, total : ' + data[2] + ', debug : ' + online_data[number]);
                  }
                  
              }
          }).catch((error) => {
              console.log(error);
          });
    }, 1000);
  }`

**Comment by aaryanchauhann** [comment]
@mateuscdor 
`
  function checkOnline(number, name){
      setInterval(function(){
        client_obj.getChatIsOnline(number + '@c.us').then((response) => {
                var data = online_data[number];
              if(response === true){
                  if(data[0] == false){
                      // came online
                      console.log('[' + datetime() + '] ' + name + ' came online');
                      online_data[number][0] = true;
                      online_data[number][1] = timestamp();
                  }
              }else{
                  if(data[0] == true){
                      online_data[number][0] = false;
                      var online_time = (timestamp() - online_data[number][1]) / 1000;
                      online_data[number][2] = online_data[number][2] + online_time;
                      console.log('[' + datetime() + '] ' + name + ' went offline, was online since ' + online_time + ' seconds, total : ' + data[2] + ', debug : ' + online_data[number]);
                  }
                  
              }
          }).catch((error) => {
              console.log(error);
          });
    }, 1000);
  }`

**Comment by aaryanchauhann** [comment]
@mateuscdor 

function checkOnline(number, name){

      setInterval(function(){
        client_obj.getChatIsOnline(number + '@c.us').then((response) => {
                var data = online_data[number];
              if(response === true){
                  if(data[0] == false){
                      // came online
                      console.log('[' + datetime() + '] ' + name + ' came online');
                      online_data[number][0] = true;
                      online_data[number][1] = timestamp();
                  }
              }else{
                  if(data[0] == true){
                      online_data[number][0] = false;
                      var online_time = (timestamp() - online_data[number][1]) / 1000;
                      online_data[number][2] = online_data[number][2] + online_time;
                      console.log('[' + datetime() + '] ' + name + ' went offline, was online since ' + online_time + ' seconds, total : ' + data[2] + ', debug : ' + online_data[number]);
                  }
                  
              }
          }).catch((error) => {
              console.log(error);
          });
    }, 1000);
  }`

**Comment by aaryanchauhann** [comment]
Check it just now,
still not working in 4.0.2,
it stops working after 2 minutes of connection.

getChatIsOnline() keeps returning false after 2 minutes.
