### ISSUE TITLE
Re: Issue regarding getChatIsOnline() returning always false after 2 minutes

### ISSUE THREAD

**Issue by aaryanchauhann** [orkestral/venom#1283]
**My previous issue was closed with 'fixed in version 4.0.2', but I checked and it's still not fixed @orkestral **
When we try to fetch the user online/offline status using getChatIsOnline(), with multi device as true, it returns perfectly fine for the first two minutes after connecting to the client, but after that it always returns false whether the user is online or offline.

It works perfectly fine with multi-device as false, this is only a bug while using multi-device.

`
setInterval(function(){

    client_obj.getChatIsOnline(number + '@c.us').then((response) => {
            var data = online_data[number];
          if(response === true){
              if(data[0] == false){
                  // came online
                  console.log('[' + datetime() + '] ' + name + ' came online');
                  online_data[number][0] = true;
                  online_data[number][1] = timestamp();
              }
          }else{
              if(data[0] == true){
                  online_data[number][0] = false;
                  var online_time = (timestamp() - online_data[number][1]) / 1000;
                  online_data[number][2] = online_data[number][2] + online_time;
                  console.log('[' + datetime() + '] ' + name + ' went offline, was online since ' + online_time + ' seconds, total : ' + data[2] + ', debug : ' + online_data[number]);
              }
              
          }
      }).catch((error) => {
          console.log(error);
      });
}, 1000);`

Environment
Venom version(s): 4.0.2
Browser: Chrome 87
OS: Ubuntu 18
Node version: 16.13.0

**Comment by mateuscdor** [comment]
Refactor your code.

**Comment by aaryanchauhann** [comment]
> Refactor your code.

How will that solve the issue?
