### ISSUE TITLE
Cant connect using multidevice = true and Whatsapp running in new beta mode

### ISSUE THREAD

**Issue by lucianodltec** [orkestral/venom#1284]
## Description

Just try to connect Venom and Whatsapp on latest beta mode is not working as expected.

## Environment

- **Venom version(s):** 4.0.2
- **Browser:** lastest Chrome
- **OS:** Windows 10
- **Node version:** 12.22.1

## Steps to Reproduce

1. Set multidevice = true on venom connection options
2. Scan QR code
3. Nodejs freezes with no response

## 

Running Whatsapp in new beta mode and Venom with multidevice = false it is connecting, but it is not what was expected (or not).

**Comment by mateuscdor** [comment]
Luciano o problema está aí.
O node está funcionando normalmente.

Você está utilizando a versão 12 do node? 
recomendo atualizar para v16

**Comment by lucianodltec** [comment]
Mateus obrigado pelo retorno.

Vc tem certeza que se atualizar para versao 16 vai funcionar? porque eu uso a versao 3.1.12 com o node 12 sem problema.

Achei meio estranho.

Att

**Comment by mateuscdor** [comment]
Faz um debugger para descobrir qual é o erro.

**Comment by lucianodltec** [comment]
Ola, tudo joia!? Não entendi porque fechou essa questao... ainda estou com problema nela.
