### ISSUE TITLE
SendButtons don't work on MD

### ISSUE THREAD

**Issue by IanosJunior** [orkestral/venom#1286]
## Description

SendButtons don't work on MD

## Environment

Venom version(s): [4.0.2]
Browser: [Chrome 95]
OS: [Windows 10]
Node version: [16.13.0]

## Log Output

Error when sending: {
me: {
id: '1',
ref: '2@OJGYKnnf6T2MArtKM29X+S1j/zo4H6iqcmuERu61qabAeolAiReSfS8xGyknv6LW8UZ0TWBTxUVPOQ==',
refTTL: 60000,
platform: 'android',
pushname: 'Ianos Junior',
blockStoreAdds: false,
isVoipInitialized: false
},
to: {
fromMe: true,
remote: {
server: 'c.us',
user: '553732621959',
_serialized: '553732621959@c.us'
},
id: 'RE2Z5OLRD2OPO3AMO8TI',
_serialized: 'true_553732621959@c.us_RE2Z5OLRD2OPO3AMO8TI'
},
erro: true,
text: null,
status: 'ERROR_UNKNOWN',
result: null
}

## Your Code

const venom = require('venom-bot');

venom
.create({
session: 'session-name', //name of session
multidevice: true // for version not multidevice use false.(default: true)
})
.then((client) => start(client))
.catch((erro) => {
console.log(erro);
});

function start(client) {
client.onMessage((message) => {
if (message.body === 'Hi' && message.isGroupMsg === false) {
client.sendButtons('553732621959@c.us','Vc tem uma consulta com o dr fulano',
[{ buttonText: { displayText: 'Confirmar' } },{ buttonText: { displayText: 'Cancelar' } },], 'Escolha uma opcao')
.then((result) => {
console.log('Result: ', result); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});
}
});
}

**Comment by liperg** [comment]
Same issue here...

**Comment by jeferssonlemes** [comment]
here too
