### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by mitjarogl** [orkestral/venom#1288]
## Cannot read properties of undefined (reading 'id')

When I execute this `await client.sendMessageOptions(
        message.from,
        'Welcome'
      );` I get error `Cannot read properties of undefined (reading 'id')`

## Environment

- **Venom version(s):  4.0.2
- **Browser: Chrome/95.0
- **OS: Mac OS 12.0.1
- **Node version: Node v12.20.2

## Steps to Reproduce

1. Page successfully accessed
2. Bot connected
3. Try to send message to client

## Log Output

```
(node:12704) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
    at Object.window.WAPI.window.WAPI.sendMessageOptions (/node_modules/venom-bot/dist/lib/wapi/wapi.js:2251:55)
    at __puppeteer_evaluation_script__:3:57
    at ExecutionContext._evaluateInternal (/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --

```

**Comment by mitjarogl** [comment]
@orkestral how was issue resolved?

**Comment by alexandrejferreira** [comment]
maybe missing { quotedMessageId: reply,} ?

// Send message with options
await client.
        .sendMessageOptions(
          '000000000000@c.us',
          'This is a reply!',
           {
              quotedMessageId: reply,
            }
        )
        .then((retorno) => {
          resp = retorno;
        })
        .catch((e) => {
          console.log(e);
        });

**Comment by mitjarogl** [comment]
@alexandrejferreira @orkestral Which value should be defined under property `quotedMessageId `?
