### ISSUE TITLE
Tokens are not saved when using browserWSS

### ISSUE THREAD

**Issue by Nemo1710** [orkestral/venom#1292]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [4.0.2,3.1.12]
- **Browser:** [WSS]
- **OS:** [Linux Ubuntu]
- **Node version:** [v16.13.0]

## Steps to Reproduce

When the browserWSS is used, tokens are not being saved

```
If relevant, paste all of your Log Output
```

## Your Code
onst venom = require('venom-bot');
import {Workbook, Row, Cell,Worksheet} from 'exceljs';
const fs = require('fs');

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
function delay(ms: number) {
  return new Promise( resolve => setTimeout(resolve, ms) );
}
venom.create(
   {
    session: 'session-name', //name of session
    multidevice: false, // for version not multidevice use false.(default: true)
    browserWS: 'ws://localhost:3000/'
  }
).then((client) => start(client));

async function start(client) {
        console.log('starting');
        let wb:Workbook = new Workbook();
        //Poner nombre de archiv

        client.onMessage((message) => {
    if (message.body === 'Hi') {
      client.sendText(message.from, 'Welcome Venom 馃暦');
    }
  });
}

**Comment by mateuscdor** [comment]
O problema está no seu código.

**Comment by c0nf1ck** [comment]
Having the the same problem here. Using **browserWS**, the tokens are not saved
