### ISSUE TITLE
getBatteryLevel returns undefined

### ISSUE THREAD

**Issue by lucianodltec** [orkestral/venom#1293]
## Description

getBaterryLevel is returning 'undefined'

## Environment

- **Venom version(s):** 4.0.2
- **Browser:** Lastest Chrome
- **OS:** Win10
- **Node version:** Node 16.13.0

## Steps to Reproduce

Simply run demo code calling getBatteryLevel()

`// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: true // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

async function start(client) {
  const device = await client.getHostDevice();
  const battery = await client.getBatteryLevel();
  console.log(device)
  console.log(battery)
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}`

![image](https://user-images.githubusercontent.com/10486864/142640425-d308d0e0-fabe-4ab6-90ef-10e558fbbc22.png)

**Comment by lucianodltec** [comment]
Also, "device" object has different properties than before (running WA beta mode on/off). Is this a change on WA Api? How can I get host WA number?

**Comment by lucianodltec** [comment]
Please, dont close this issue. I can help to fix it...

**Comment by jonalan7** [comment]
if you are using beta, these functions have been removed by whatzapp!

**Comment by mateuscdor** [comment]
@lucianodltec  me chama no whats 73 9 9177-6616
