### ISSUE TITLE
Closing issues without any response?

### ISSUE THREAD

**Issue by aaryanchauhann** [orkestral/venom#1294]
Hello @orkestral , thanks for the amazing application but why are you closing the issues even when they are not solved.

Don't close them, someone else may help?

My issues #1283 & #1280 were closed without being solved properly.

**Comment by mateuscdor** [comment]
Verifique as propriedades
Venom create ()
Se não há algum argumento 
Que esteja interrompendo

Browser Args
Puppter args


Teste essa função de outro maneira

**Comment by orkestral** [comment]
only library issues will remain open, sorry and thank you for using
