### ISSUE TITLE
Does not store the token if using beta (multi-device).

### ISSUE THREAD

**Issue by generalov-viktar** [orkestral/venom#1295]
## Description
Does not store the token if using beta (multi-device).

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 4.0.1, 4.0.2]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [Looked at closed questions]

## Log Output
✓ [instance: ############]: Connected
{ WABrowserId: '"6i8zK6r/A/zferAItMveDA=="' }
"6i8zK6r/A/zferAItMveDA=="
undefined
undefined
undefined

```
If relevant, paste all of your Log Output
```

## Your Code
    .then(async (client) => {
        const browserSessionToken = await client.getSessionTokenBrowser(true);
        console.log(browserSessionToken)
        console.log(browserSessionToken.WABrowserId)
        console.log(browserSessionToken.WASecretBundle)
        console.log(browserSessionToken.WAToken1)
        console.log(browserSessionToken.WAToken2)
        await start(client)
    })
    .catch((err) => {
        console.log(err);
    });

**Comment by generalov-viktar** [comment]
{
            multidevice: true,
            createPathFileToken: true,
            
Multidevice, and createPathFileToken set TRUE

**Comment by generalov-viktar** [comment]
@orkestral I have an idea?

**Comment by lucianodltec** [comment]
Hey @generalov-viktar I have same issue here... but I have another question for you.

Did you get to connect WA with multidevice = true and beta mode ON ?

I tried here but it does not work... I see qrCode change from one to another very quickly running multidevice = false and that way it is connecting. Running multidevice = true, qrCode does not change and it is not connecting...

Did you have that same problem?

**Comment by generalov-viktar** [comment]
Hi @lucianodltec , I have the same problem. I haven't been able to solve it yet

**Comment by lucianodltec** [comment]
@generalov-viktar are you running Whatsapp Business? 

see https://github.com/orkestral/venom/issues/1309

**Comment by renandecarlo** [comment]
Same here

**Comment by rafaeldalbosco** [comment]
I have the same bug

**Comment by generalov-viktar** [comment]
Why closed?
