### ISSUE TITLE
Closing issues without proper response/help.

### ISSUE THREAD

**Issue by aaryanchauhann** [orkestral/venom#1296]
#1294 

@orkestral & @mateuscdor that is a library issue, you can check for yourself the function returns false (after two minutes of creating the venom session), even if the user is online.
The function getChatIsOnline is a library function I guess?
And the response from the function is incorrect, so this should be considered as library issue?

**Comment by orkestral** [comment]
if you are using beta, this function does not work

**Comment by aaryanchauhann** [comment]
It works but just for some initial time,
is there any workaround or alternative for this while using beta?

**Comment by zly0321** [comment]
Erro ao carregar grupos usando a função getAllChatsGroups，Como resolver?

> 如果您使用的是测试版，则此功能不起作用

Como resolver?Erro ao carregar grupos usando a função getAllChatsGroups，Como resolver?
