### ISSUE TITLE
Erro ao carregar grupos usando a função getAllChatsGroups？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by zly0321** [orkestral/venom#1298]
![1](https://user-images.githubusercontent.com/89902432/142727759-f20086b9-6001-48e1-bdb6-809ae621e005.png)

**Comment by zly0321** [comment]
Não resolvi este problema

**Comment by zly0321** [comment]
Não resolvi este problema

**Comment by zly0321** [comment]
4.0.2 também não é reparado

**Comment by zly0321** [comment]
Não é possível ler todos os grupos

**Comment by mateuscdor** [comment]
qual o script utilzado?

**Comment by zly0321** [comment]
> qual o script utilzado?

const chats = await client.getAllChatsGroups();
console.log(chats);
