### ISSUE TITLE
Cannot read property 'attributes' of undefined on 2.2146.9

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#1306]
## Description
`````
 Error: Evaluation failed: TypeError: Cannot read property 'attributes' of undefined
     at Object.window.WAPI.window.WAPI.getHost (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:68535)
     at __puppeteer_evaluation_script__:1:28
     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
`````
## Environment

- **Venom version(s):** [4.0.2]
- **Browser:** [Chrome]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by henrickJona** [comment]
i'm getting this error as well, can't connect, token is not being generated

**Comment by nourel** [comment]
if this helps at all... Store at this point of the code is undefined....
https://github.com/orkestral/venom/blob/14e2fea6fe6b066ce6a793b7894c1d8955b15792/src/lib/wapi/functions/check-send-exist.js#L57

**Comment by w3nder** [comment]
I also had the same problem when sending an image.

**Comment by Maker4You** [comment]
I also had the same problem,
What to change in :
{ id: "Conn", conditions: (module) => (module.default && module.default.ref && module.default.refTTL) ? module.default : null },{ id: "Me", conditions: (module) => (module.PLATFORMS && module.Conn) ? module.default : null }
to solve it?

**Comment by iamedusm** [comment]
i'm getting this error

**Comment by mohinderq** [comment]
I'm getting this error as wel, unfortunately.

**Comment by jonalan7** [comment]
@antirek fix error!

**Comment by jonalan7** [comment]
Take a test!
Download the repor version! I will update later!

`npm i github: orkestral / venom`

**Comment by lukasportal** [comment]
using Store.State.Socket works! thank you @jonalan7

**Comment by iamedusm** [comment]
> Faça um teste! Baixe a versão repor! Vou atualizar mais tarde!
> 
> `npm i github: orkestral / venom`

thanks, it worked perfect here

**Comment by lucianodltec** [comment]
@lukasportal how can I access Store.State.Socket?
Please leave a sample code.

**Comment by lukasportal** [comment]
> @lukasportal how can I access Store.State.Socket? Please leave a sample code.

Just look at the fix @jonalan7  did
https://github.com/orkestral/venom/commit/c1fac1b000f7277a680bcebfc04aed457e718305

the new update from WhatsApp removed `window.Store.State.default`, and instead we have to use `window.Store.State.Socket`

**Comment by lucianodltec** [comment]
@lukasportal Thanks man!

**Comment by mateus-n** [comment]
Just update for new latest version 4.0.2 or 4.0.3 (alpha) that solve this problem

**Comment by AlmirFill** [comment]
> > Faça um teste! Baixe a versão repor! Vou atualizar mais tarde!
> > `npm i github: orkestral / venom`
> 
> thanks, it worked perfect here



> 
não funciona yarn

**Comment by AlmirFill** [comment]
ainda tenho o problema alguém pode me ajudar

**Comment by AlmirFill** [comment]
uso yarn não consegui baixar a versão repo yarn add github: orkestral / venom

**Comment by mateus-n** [comment]
> uso yarn não consegui baixar a versão repo yarn add github: orkestral / venom

Baixa a versão nightly.
`npm i --save https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz`

**Comment by growupmarketingdigital** [comment]
it worked for me:
`{ id: "Conn", conditions: (module) => (module.default && module.default.ref && module.default.refTTL) ? module.default : (module.Conn && module.Conn.ref && module.Conn.refTTL?module.Conn:null)}`

**Comment by w3nder** [comment]
> @antirek fix error!

Thanks, here solved

**Comment by antirek** [comment]
@jonalan7 

getHost returns 
 {
   id: {
     server: 'c.us',
     user: '7908XXXXXXX',
     _serialized: '7908XXXXXXX@c.us'
   },
   statusConnection: 'CONNECTED',
   businessHours: { timezone: null },
   pushname: null,
   formattedTitle: '+7 908 XX',
   displayName: 'eng1',
   imgUrl: null,
   imgFull: null,
   previewEurl: null
 }

no battery data

**Comment by antirek** [comment]
@jonalan7 

https://github.com/orkestral/venom/commit/0e055aeda0c55279ca9278a8b618be44b672282a#diff-c1d3f36d40b4a09580ddd1b84aca24102adf45cc7b2158f44ac035ad8770a94bL18

batery was removed because no data or for decrease obj?

**Comment by antirek** [comment]
create issue #1312
