### ISSUE TITLE
Status qrReadFail on Whatsapp Business

### ISSUE THREAD

**Issue by pedroayres** [orkestral/venom#1309]
## Description

Error to read QrCode on Whatsapp Business

[Description of the bug, When Issue Happens]

## Environment

Venom Version: 4.0.3
Iphone 11 
Whatsapp Business Version 2.21.221

## Steps to Reproduce

1. Open WhatsApp business 
2. Read QRcode
3. The error shows up

Obs: Everything works well on canonical WhatsApp

**Comment by lucianodltec** [comment]
Hi @pedroayres , try to set multidevice = false (even with beta mode on).
That works for me, but tokens are not being saved... so you'll have to scan QR code each time server restarts.

**Comment by renandecarlo** [comment]
Same here

**Comment by generalov-viktar** [comment]
Why closed?
