### ISSUE TITLE
Session JSON file not being created!

### ISSUE THREAD

**Issue by Helkyd** [orkestral/venom#1310]
## Description

When is the Session JSON file is created?
Nothing declared on the options (mkdirFolderToken) for sure will assume my base Dir and create the Directory tokens..
Directory was created but is empty. I can send file to user and still no Session file is created.

## Environment

- **Venom version(s):** 4.0.2
- **Browser:** Chromium 95
- **OS:** Ubuntu 16
- **Node version:** Node 14

## Steps to Reproduce

1. Start your script for multiple sessions
2. Scan QR
3. Send your files
4. When trying to send another one will show QRScan again

**Comment by OtavioCostaLima** [comment]
I have the same problem!

**Comment by OtavioCostaLima** [comment]
I have the same problem!

**Comment by maitret** [comment]
I have the same problem! :(

**Comment by Helkyd** [comment]
The same problem is replicated on version 4.0.3
