### ISSUE TITLE
Not saving JSON Token when session.close() is called, sometimes does it, but sometimes doesnt

### ISSUE THREAD

**Issue by henrickJona** [orkestral/venom#1316]
## Description

When calling method session.close(), it simply removes JSON token and demands to read QRcode again, but i havent disconnected from device

## Environment

- **Venom version(s):** [4.0.3]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. Read QRcode 
2. Call session.close()
3. When starting again, it demands to read QRcode, but i havent disconnected, it should save JSON token

**Comment by OtavioCostaLima** [comment]
I have the same problem! :(

https://github.com/orkestral/venom/issues/1310

**Comment by RafaelBini** [comment]
Same problem here!
