### ISSUE TITLE
The Reply method not work more for me: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'attributes')

### ISSUE THREAD

**Issue by marciusbezerra** [orkestral/venom#1322]
## Description

The Reply method not work more for me: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'attributes')

ps: before it worked normally!

```
listeningMessages = venomClient.onMessage(async (message) => {
    //...
    await venomClient.reply(message.from, cleanText, message.id.toString());
    //...
}
```

Erro:
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'attributes')
at Object.window.WAPI.window.WAPI.scope (C:\...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:34545)
at Object.window.WAPI.window.WAPI.checkIdMessage (...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:31665)
at async Object.window.WAPI.window.WAPI.reply (...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:55620)
at ExecutionContext._evaluateInternal (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async ExecutionContext.evaluate (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

```
## Environment

- **Venom version(s):** 4.0.3
- **OS:** Windows Server 2019
- **Node version:** 14.17.0

## Steps to Reproduce

```
listeningMessages = venomClient.onMessage(async (message) => {
    //...
    await venomClient.reply(message.from, cleanText, message.id.toString());
    //...
}
```

**Comment by marciusbezerra** [comment]
so far I went downgrade to version 4.0.2 and it worked!

**Comment by riservato-thiagomelo** [comment]
O mesmo está acontecendo comigo.

    não estou invocando start() mais de 1x;
    fazer downgrade não adianta;
    o stack trace não mostra qual função causa o erro;
    as vezes o erro some, as vezes aparece.

Possível solução:

    deletar pasta de tokens;
    executar npm i venom-bot@latest;
    reconectar dispositivos;

https://github.com/orkestral/venom/issues/569

**Comment by antirek** [comment]
try use 
> npm i --save https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz 
it's not published by number current nightly version.

**Comment by joseallef** [comment]
> O mesmo está acontecendo comigo.
> 
> * não estou invocando `start()`mais de 1x;
> * fazer downgrade não adianta;
> * o stack trace não mostra qual função causa o erro;
> * as vezes o erro alguns, as vezes aparece.
> 
> Solução Possível:
> 
> * deletar pasta de tokens;
> * executar `npm i venom-bot@latest`;
> * reconectar dispositivos;
> 
> [# 569](https://github.com/orkestral/venom/issues/569)

Mine was at version 4.0.2, then I upgraded to version 4.0.3, that stopped the error!
