### ISSUE TITLE
startTyping doesn't seem to be working

### ISSUE THREAD

**Issue by riservato-thiagomelo** [orkestral/venom#1323]
## Description

Typing methods doesn't seem to work, at all.

``` javascript
await client.startTyping(chatID);
await sleep(3 * 1000);
await client.sendText(chatID, line);
await sleep(0.5 * 1000);
await client.stopTyping(chatID);
```

this code won't set chat state to "typing...". text is sent successfully

## Environment

- **Venom version(s):** 4.0.3
- **Browser:** Google Chrome
- **OS:** Windows 10
- **Node version:** 14.18.1

**Comment by antirek** [comment]
run venom with open browser and see to console output
if errors then append console output to this issue

**Comment by IanosJunior** [comment]
Solution in #1319

**Comment by ProbBC** [comment]
> Solution in #1319

I tried that, but still doesnt work for me
