### ISSUE TITLE
How to send messages to new contacts?

### ISSUE THREAD

**Issue by Muhammad-Taif-Khan** [orkestral/venom#1324]
Hi There, i am creating a Whatsapp bot where i need to fetch contact numbers and messages from excel sheet and send these messages to their respective contacts. So what is the best way to do it using venom-bot.
I read the docs but it's not helping me.

Thanks for your Time!

**Comment by Muhammad-Taif-Khan** [comment]
Don't close it please. I need help !

**Comment by KelseyJr** [comment]
@Muhammad-Taif-Khan If you want to send messages to your contacts that never talked to you, you will have to use the WhatsApp Business

Check out the Whatsapp Business Policy: https://www.whatsapp.com/legal/business-policy/?lang=en
Search for "Acceptable Message Types"

**Comment by diogolimas** [comment]
some news? taking the same problem 
@Muhammad-Taif-Khan
