### ISSUE TITLE
How can we stop a session after venom.create?

### ISSUE THREAD

**Issue by ayushsb** [orkestral/venom#133]
Hello
Can i stop/terminate a session some how before autoclose. I mean if I have an app that the user clicked on a button that started the session but he didn't scanned the qr code and clicked on the back button of my app so in that case in there a possibility we can stop that session before going on the previous page?

Can someone please help me with this?

**Comment by joaosouz4** [comment]
client.close()

**Comment by ayushsb** [comment]
@joaosouz4 Thanks for the help but I think that can be done once the qrcode has been scanned and a token has been generated right?

**Comment by joaosouz4** [comment]
yes, you can save the creation in a var and clear it when you return

**Comment by joaosouz4** [comment]
```
async () => {
  var marketingClient = await venom.create('marketing');
  ....
  var marketingClient = ''
```
