### ISSUE TITLE
Stop closing Issues without  a solution, reason or response => Unhandled rejection on sendContactVcard

### ISSUE THREAD

**Issue by voxsoftware** [orkestral/venom#1332]
## Please stop closing issues without any solution, reason or response.

This is a real bug. The library should reject the promise, in that way user code can control it, instead of generating an unhandled rejection when receiving invalid parameters.
Here the original issue closed without response: #1302 

## Description

Unhandled rejection, and promise never rejected or resolved on sendContactVcard when invalid parameters. 

## Environment

- **Venom version(s):** 4.0.2
- **Browser:** Not relevant in this bug, but using Chrome 96
- **OS:** Linux, Ubuntu 21.04
- **Node version:** Node 14

## Steps to Reproduce

1. Send invalid parameters to method sendContactVcard. For example send any text instead of a contactId

## Your Code

```typescript
await client.sendContactVcard("xxxxx@c.us", ["Not a correct contactId"])
```

## Additional context / Screenshot

```bash
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:874:47)
    at step (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:48:23)
    at Object.next (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:29:53)
    at fulfilled (/root/.kawi/packages/2afa2f5f633a45ca784c30c32efeead6/node_modules/venom-bot/dist/api/layers/sender.layer.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

I think can be solved checking ```result``` is an object, if not reject the promise with InvalidParameter exception or similar.

**Comment by foomoto** [comment]
+1

**Comment by foomoto** [comment]
This are the early signs that an open source project is failing

**Comment by jamesxt94** [comment]
+1 Why close? @orkestral please clarify you closed. No always is possible control user input parameters, so this method should reject the promise but no cause an unhandled rejection.

**Comment by jrCleber** [comment]
The await function `sendContactVcard` takes three parameters, but here `await client.sendContactVcard("xxxxx@c.us", ["Not a correct contactId"]) `<- only takes two parameters.
Make sure you pass the parameters correctly.
ex: `await client.sendContactVcard("550000000000@c.us", "550000000000@c.us", "name");`

**Comment by jamesxt94** [comment]
@jrCleber ```sendContactVcard``` can receive 2 or 3 parameters. Calling with only 2 parameters doesn't make difference. The error is present still if called with 3 parameters. My point is: 

* if parameter ````contactId``` is ok works like expected (no problem here)
* if parameter ```contactId``` is invalid, throws an UNHANDLED EXCEPTION that cannot be controlled by user code and can kill the entire app. The correct way is REJECT the promise so user can control with a try/catch flow.

**Comment by jrCleber** [comment]
@jamesxt94 
Yes, this is a serious problem!
You can deal with `then` too:
```
client.sendContactVcard(message.from, '550000000000@c.us', 'Contact name')
                 .then(result => console.log(result))
                 .catch(err => console.log('Error sending contact ', err));
```
That's why I recommend not using `await` with venom.

**Comment by jamesxt94** [comment]
@jrCleber I don't understand you completely.
In this bug you cannot deal with ```then``` because generates an unhandled exception. ```try{ await xxx(); yyy(); } catch(e){ ... } ``` has same effect than ```xxx().then(yyy()).catch(...)``` so using ```await``` doesn't make difference. The problem is that this bug can kill the entire app.

**Comment by jrCleber** [comment]
@jamesxt94 
IT'S! In fact you are right! It really doesn't matter.
An invalid parameter kills the entire application.

**Comment by jamesxt94** [comment]
@jrCleber Thanks for test. So my question for @orkestral  is why close issues like this without any response/comment?

**Comment by jamesxt94** [comment]
The only mistake in this bug is the title: Unhandled rejection is not the correct term, should be: **Unhandled exception** and can kill the entire app.
