### ISSUE TITLE
Keep the client online in Multi-Device mode

### ISSUE THREAD

**Issue by aaryanchauhann** [orkestral/venom#1334]
I've been using this library since quite a long, 
The only issue I'm facing currently is in `mult-device` version, the whatsapp client automatically goes to offline mode, ( in venom and in normal whatsapp web aswell), though in normal whatsapp web, it's fixed by moving the cursor every 2 minutes, 
Can you guide a solution about the same for venom? How to a program the cursor to move every 2 minutes or put some ping-pong to whatsapp which let's it stay online.

I need this functionality because I need the online/offline status of a user and it won't get that until the client is itself online.

Thanks

**Comment by orkestral** [comment]
it's not supported at the moment, as I said the version is still beta, if you want to check out, get superchats, it uses socket, and it doesn't go offline
