### ISSUE TITLE
Unhandled exception on sendContactVcard and kill the entire app => #1332 #1302

### ISSUE THREAD

**Issue by jamesxt94** [orkestral/venom#1337]
@orkestral Please clarify why this bugs was closed without any response: #1302 #1332

## And stop closing unanswered bugs. I understand, some reports are "stupid" but others not.  If you close a bug make it clear why you closed it. Why do you have this opensource project if you act in  this way?

Please i wait your response. Regards.

**Comment by jamesxt94** [comment]
Bug confirmed for 3 users #1302 (see comments)
@voxsoftware @jrCleber  @jamesxt94

**Comment by cucabr** [comment]
instead of closing the issues, we could discuss how to solve the problem @orkestral !

**Comment by cucabr** [comment]
same here

**Comment by jonalan7** [comment]
function fixed!
