### ISSUE TITLE
joinGroup() function error 406

### ISSUE THREAD

**Issue by AliMilani** [orkestral/venom#1338]
## Description

joinGroup() not work
I have status: 406 error

await client.joinGroup('HRc1oV18PAuEwLhvvGVdOv');

{ status: 406 }

**Comment by exallhost** [comment]
Estou também com o mesmo problema. Alguma novidades ou sugestão para tentar solucionar?

**Comment by AliMilani** [comment]
> Estou também com o mesmo problema. Alguma novidades ou sugestão para tentar solucionar?

Ainda não resolvido

**Comment by jgabriellima** [comment]
Alguma novidade sobre essa issue?

**Comment by AliMilani** [comment]
> Alguma novidade sobre essa issue?

This project is dead
you have better choices...

**Comment by jgabriellima** [comment]
Really, @AliMilani ? This is so interesting, could you please tell us the better choice?

**Comment by jgabriellima** [comment]
btw, I created this workaround if someone takes a look here in the future. It's working so far. ;) 
```
const join_group = async (client, code) => {
    const sleep = (ms) => {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    try {
        const fullUrl = `https://web.whatsapp.com/accept?code=${code}`
        const page = client.waPage
        await page.goto(fullUrl, {waitUntil: 'networkidle0'})
        await sleep(5000);
        const [button] = await page.$x("//*[@id=\"app\"]/div[1]/span[2]/div[1]/div/div/div/div/div/div[2]/div[2]");
        if (button) {
            await button.click();
        }

    } catch (e) {
        console.log(e)
    }
```

**Comment by AliMilani** [comment]
> btw

whatsapp-web.js :))

**Comment by AliMilani** [comment]
> Really, @AliMilani ? This is so interesting, could you please tell us the better choice?

whatsapp-web.js

**Comment by ikhsanul27** [comment]
> btw, I created this workaround if someone takes a look here in the future. It's working so far. ;)
> 
> ```
> const join_group = async (client, code) => {
>     const sleep = (ms) => {
>         return new Promise(resolve => setTimeout(resolve, ms));
>     }
>     try {
>         const fullUrl = `https://web.whatsapp.com/accept?code=${code}`
>         const page = client.waPage
>         await page.goto(fullUrl, {waitUntil: 'networkidle0'})
>         await sleep(5000);
>         const [button] = await page.$x("//*[@id=\"app\"]/div[1]/span[2]/div[1]/div/div/div/div/div/div[2]/div[2]");
>         if (button) {
>             await button.click();
>         }
> 
>     } catch (e) {
>         console.log(e)
>     }
> ```

@jgabriellima Thank you, it really helps my life  💯 👍🏼 👍🏼 🥇

**Comment by mikelustosa** [comment]
> btw, I created this workaround if someone takes a look here in the future. It's working so far. ;)
> 
> ```
> const join_group = async (client, code) => {
>     const sleep = (ms) => {
>         return new Promise(resolve => setTimeout(resolve, ms));
>     }
>     try {
>         const fullUrl = `https://web.whatsapp.com/accept?code=${code}`
>         const page = client.waPage
>         await page.goto(fullUrl, {waitUntil: 'networkidle0'})
>         await sleep(5000);
>         const [button] = await page.$x("//*[@id=\"app\"]/div[1]/span[2]/div[1]/div/div/div/div/div/div[2]/div[2]");
>         if (button) {
>             await button.click();
>         }
> 
>     } catch (e) {
>         console.log(e)
>     }
> ```

How do I create a new group?
