### ISSUE TITLE
onAck not work

### ISSUE THREAD

**Issue by MiniFris** [orkestral/venom#1347]
The issue was closed with no response. Still relevant

All details here #1326

**Comment by jonalan7** [comment]
The onAck function is only monitored in the browser where Venom is used!

**Comment by MiniFris** [comment]
When multidevice = false, the onAck event is triggered for any message. But with multidevice = true, the onAck event fires only on messages sent from Venom. This was shown in the video.

**Comment by jonalan7** [comment]
using multidevice = false, and synchronizing the messages with the cell phone. But with multidevice = true, it's just browser and server!

**Comment by MiniFris** [comment]
But does the web.whatsapp client update the message statuses somehow? How to track these statuses when multidevice = true?
