### ISSUE TITLE
Issues when trying to get latitude and longitude

### ISSUE THREAD

**Issue by Eider3a** [orkestral/venom#1353]
Hi guys.

I am using the latest version of the library and I'm trying to get the user latitude and longitude when it send it through WhatsApp but I'm not getting the values for the coordinates.

**Comment by gonmartinez** [comment]
It looks like the location it's now encrypted. Do you see an encrypted body/content?

**Comment by jesusvalverde** [comment]
When I do get location of message I do get. 

type: 'location',

content: '/9j/4AAQSkZJRgABAQAASABIAAD/4QBYRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAZKADAAQAAAABAAAAZAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgAZABkAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMABgYGBgYGCgYGCg4KCgoOEg4ODg4SFxISEhISFxwXFxcXFxccHBwcHBwcHCIiIiIiIicnJycnLCwsLCwsLCwsLP/bAEMBBwcHCwoLEwoKEy4fGh8uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLv/dAAQAB//aAAwDAQACEQMRAD8A+mWGenBHIPvQxBHnDjs49D606m52Nv6g8MPas0+hTFqrdfMY4T9125P05x+NWcbG2dQeVPtUc0XmxlM4PBB9COlOOktSKivFpE1FVUuVGVuCI3XqCeD7j2pDcNL8tqN3+2eFH+NHs5C9rHuW6Kq7LsdJFb6r/gafDN5gKsNrrwy/57Ghw0uncanrZqxPRRRUFhRRRQAUUUUAf//Q+mA6HuKdSl5cfNtb6ikO0MpQYDrnHvWduxQ0kBDG2cDlCOcH0pwzjmlopN3AYURiCygkdMiuZ8Ua2+kW8ENuyxzXUgjWR+VjXjc5Htmuprk/F2gPrtgiW5AuIWzGDwGzwVz2zWVbm5Hybndlqo/WYfWPhvr+l/mea3HiXXNG1eSOPUft8cbDJ6xuMZOB29ODXsNvdR3sVnqMQws69O+GGcfgRXh9r4R1u4u2tZIfJEbASO5GFzz2PPHpXsCTWunw2dlEfkhwgz/sqawy/wBpzS59j2eKPqns6SoNOatdq22m9tDpaKqw3KTfdqfjcd+7HbbXYkfMD6Kb+69ZPypP3X96T8v/AK1PlC4+imfuv77/APfP/wBaj91/ff8A75/+tRyhc//R+m6Z/wAs4/8AZYrSk4GTSGPad0jKh9uTWcRsd05NIHUnAIoHljlULH1f/Cnhi7COUAhumB0NFkFxKa3Vf94fzoXOMHqOD+FI3b6j+dJbjOdvPM+1Xmz++v8A6CK5uS1uZbiInP3j/I11pw1/er/tp/6AKW7UW1t54iaTyyHOzbkBeSTuI4xWkdZ2M6nw3HafavCvzVsVn2F+t6GxGYyFVwCQ2VcZU5UkdjWjUSi4uzLTTV0FFFFSMKKKKAP/0vprGXQHoWH+NJ1d2PUsf04oPDKfRhS9Hcf7X86z6FdRaTo6H/aFFMZl45Gcj+dJbgO6O4/2jSSfd/Efzpz5WVxgnJB4HtSFJH4CHqOvFVbURj29tejUruS5WMRuwKFWJY4GOQQAOPc81pXECTwNC6LIDztb7pI5GfbNWH/1z/h/Kik3Z3QWurHOabJHFcNbhokYuQwihZUZgDkbzwSP6GujrHubayspRqLYXaxJDMdoLdSq5wGOfT1qzbalZ3kpitnLkIHztYAqTgEEgA5raquf34rQypvl9yRfooornNgooooA/9P6Y/d8bpc4OcKPT86c5hZi4DnPpwP6UVHNNHbwvPM21I1LMT2AGSaz5h2HfJ2iH/Ajn/Gnh5B90Iv0FeWXHxK02W5t/snnrEsh8xRGpaQdFAJbgZ6966LUPEVzY+JLLT2QCzuIlMhYYZHkYqmTngZwD9ad2FjsS0p6ufwAFMKk/wATZ+tclrniC5sNa0/SrNVbzpE+0EjO1HO1QPQnB/KtEeJtHN2LQSNkyeSJNjeUZOmzzMbc5460rsZvfMWLN1PpS1zc3izQ4HkSSV/3MhjlYRuVjYHHzkDAGe9TXviTSbCUwzSOxRQ7mNGkWNW6M5UEAEc/SkBvVxou2064ktrBctuLMhQtJI+45HykBFxjBPGD9a1bvxHpNk/lyO74jErGJGkCRt0ZioIANarJBewDndHKAQVYjcp5HIwcGtaVRRupLRmdSDls9SZTuUNjGex6j2OKdXM6Nd263L2MEHlKxZl+bP3eCSv8Oe/PXrXTVNWm4Ssx058yuFFFFZln/9T6bqteWyXtpNZycLNG0ZPoGGKs0ViUfOn/AAgHiuCfMMCny5AFcOozg8MATnHevV77QrzUr+QXeGWTThCZhgDzw+4EDqMHmu0op3A88h0bWZoba/1CMG+lv4ZpwCMJFCCo7/jx61Rn0rxFdokV1DO80d2kjt5yi3MYkyPLjB7D1Gfxr1Gii4HmFq+qSWmt2FjY/aBd3lzGsgdVVS3ynzAcHAHIxmn3Wj6+sVxppSeeP7MkVu0MqxRfLHtbzRwzEn65HHFejxwww7vJRU3sWbaAMsepOOpPrUtFwPNp9K1SCKE21pOlyLOKJZraZVy6LjbMjnaVU9CM8V39ktylnCl4VM4jUSFBhd2Oce2atUUAYepQ35mEltIIosZZgcEEA9RjLAkqT9K2x0qC6IFtIT/dP8qljBCKD2ArSUrxRnFWm0PooorI0P/V+m6KKKxKCiiigAooooAKKKKACiiigCpd8oidmdQfpmrdVLrpF/10WrdW/hRnH438goooqDQ//9k=',
body: '/9j/4AAQSkZJRgABAQAASABIAAD/4QBYRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAZKADAAQAAAABAAAAZAAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/8AAEQgAZABkAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMABgYGBgYGCgYGCg4KCgoOEg4ODg4SFxISEhISFxwXFxcXFxccHBwcHBwcHCIiIiIiIicnJycnLCwsLCwsLCwsLP/bAEMBBwcHCwoLEwoKEy4fGh8uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLv/dAAQAB//aAAwDAQACEQMRAD8A+mWGenBHIPvQxBHnDjs49D606m52Nv6g8MPas0+hTFqrdfMY4T9125P05x+NWcbG2dQeVPtUc0XmxlM4PBB9COlOOktSKivFpE1FVUuVGVuCI3XqCeD7j2pDcNL8tqN3+2eFH+NHs5C9rHuW6Kq7LsdJFb6r/gafDN5gKsNrrwy/57Ghw0uncanrZqxPRRRUFhRRRQAUUUUAf//Q+mA6HuKdSl5cfNtb6ikO0MpQYDrnHvWduxQ0kBDG2cDlCOcH0pwzjmlopN3AYURiCygkdMiuZ8Ua2+kW8ENuyxzXUgjWR+VjXjc5Htmuprk/F2gPrtgiW5AuIWzGDwGzwVz2zWVbm5Hybndlqo/WYfWPhvr+l/mea3HiXXNG1eSOPUft8cbDJ6xuMZOB29ODXsNvdR3sVnqMQws69O+GGcfgRXh9r4R1u4u2tZIfJEbASO5GFzz2PPHpXsCTWunw2dlEfkhwgz/sqawy/wBpzS59j2eKPqns6SoNOatdq22m9tDpaKqw3KTfdqfjcd+7HbbXYkfMD6Kb+69ZPypP3X96T8v/AK1PlC4+imfuv77/APfP/wBaj91/ff8A75/+tRyhc//R+m6Z/wAs4/8AZYrSk4GTSGPad0jKh9uTWcRsd05NIHUnAIoHljlULH1f/Cnhi7COUAhumB0NFkFxKa3Vf94fzoXOMHqOD+FI3b6j+dJbjOdvPM+1Xmz++v8A6CK5uS1uZbiInP3j/I11pw1/er/tp/6AKW7UW1t54iaTyyHOzbkBeSTuI4xWkdZ2M6nw3HafavCvzVsVn2F+t6GxGYyFVwCQ2VcZU5UkdjWjUSi4uzLTTV0FFFFSMKKKKAP/0vprGXQHoWH+NJ1d2PUsf04oPDKfRhS9Hcf7X86z6FdRaTo6H/aFFMZl45Gcj+dJbgO6O4/2jSSfd/Efzpz5WVxgnJB4HtSFJH4CHqOvFVbURj29tejUruS5WMRuwKFWJY4GOQQAOPc81pXECTwNC6LIDztb7pI5GfbNWH/1z/h/Kik3Z3QWurHOabJHFcNbhokYuQwihZUZgDkbzwSP6GujrHubayspRqLYXaxJDMdoLdSq5wGOfT1qzbalZ3kpitnLkIHztYAqTgEEgA5raquf34rQypvl9yRfooornNgooooA/9P6Y/d8bpc4OcKPT86c5hZi4DnPpwP6UVHNNHbwvPM21I1LMT2AGSaz5h2HfJ2iH/Ajn/Gnh5B90Iv0FeWXHxK02W5t/snnrEsh8xRGpaQdFAJbgZ6966LUPEVzY+JLLT2QCzuIlMhYYZHkYqmTngZwD9ad2FjsS0p6ufwAFMKk/wATZ+tclrniC5sNa0/SrNVbzpE+0EjO1HO1QPQnB/KtEeJtHN2LQSNkyeSJNjeUZOmzzMbc5460rsZvfMWLN1PpS1zc3izQ4HkSSV/3MhjlYRuVjYHHzkDAGe9TXviTSbCUwzSOxRQ7mNGkWNW6M5UEAEc/SkBvVxou2064ktrBctuLMhQtJI+45HykBFxjBPGD9a1bvxHpNk/lyO74jErGJGkCRt0ZioIANarJBewDndHKAQVYjcp5HIwcGtaVRRupLRmdSDls9SZTuUNjGex6j2OKdXM6Nd263L2MEHlKxZl+bP3eCSv8Oe/PXrXTVNWm4Ssx058yuFFFFZln/9T6bqteWyXtpNZycLNG0ZPoGGKs0ViUfOn/AAgHiuCfMMCny5AFcOozg8MATnHevV77QrzUr+QXeGWTThCZhgDzw+4EDqMHmu0op3A88h0bWZoba/1CMG+lv4ZpwCMJFCCo7/jx61Rn0rxFdokV1DO80d2kjt5yi3MYkyPLjB7D1Gfxr1Gii4HmFq+qSWmt2FjY/aBd3lzGsgdVVS3ynzAcHAHIxmn3Wj6+sVxppSeeP7MkVu0MqxRfLHtbzRwzEn65HHFejxwww7vJRU3sWbaAMsepOOpPrUtFwPNp9K1SCKE21pOlyLOKJZraZVy6LjbMjnaVU9CM8V39ktylnCl4VM4jUSFBhd2Oce2atUUAYepQ35mEltIIosZZgcEEA9RjLAkqT9K2x0qC6IFtIT/dP8qljBCKD2ArSUrxRnFWm0PooorI0P/V+m6KKKxKCiiigAooooAKKKKACiiigCpd8oidmdQfpmrdVLrpF/10WrdW/hRnH438goooqDQ//9k=',


Not able un decrypt the text

**Comment by joselmoran** [comment]
Hi everyone,  the location it's now encrypted. see this message:

'/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCABkAGQDASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAAECAwQFBgcI/8QAOxAAAgEDAwIEAwYDBgcAAAAAAQIDAAQRBRIhMUEGE1FhIjJxBxRCgbHBI1KRFRYzQ6HhJCZygtHw8f/EABoBAAIDAQEAAAAAAAAAAAAAAAABAgMEBQb/xAAzEQACAQIDBAcGBwAAAAAAAAAAAQIDEQQx8BIhQVEFMmFxgbHBBhMkkaHRMzRSgsLi8f/aAAwDAQACEQMRAD8A+mLqdIYiiELGvU+tYlzM8kgAB3nhVH4f9/0pLi6aWQbAc5+Bf3+v6VPDGLSN5H3POELkIhchQMnCjkn2HJPFYKFK/wAXif2rX0++U5z3+5p+LJba2a3iyke+VuOOg/Os432jX93caHeSLcy3AaKSOWFxFMy/NGjkbSy+gOR+RxS8RxzXep6HaaZdraak4muYL+UEjKbA0GzI3bs8qegQnqOMm30efXnkU21vYxQy+Tco7OZLScTGaV7ZsYbzCVw2QVwOOMVXVc8TPafy1x1zL6cI04561rI1LXwisGpXCatHLqEYjVrTUmu2juogMAQsykNgdQy8HnPPJ7KSUiyU2+7aPhYsSzKAPfr9fzqqcZ4ycADLHJOPUmmtcpZK08rokQHxl2Crj3JroU6caasiiU5Te8UAAcUtU4NW0m7m26bqdldA/ghnV2X2IBzVyrE08iLi4uzVh8LqqmKX/Bbv/KaSRGikKP17H1FNqWJldBBKcD/Lf+U+lAiI8jmk64Vjgj5W/Y0rKyOUcYYf6+9SRRGTr8p4+vtQBFnHDcEdqK1A0cKqjOq4HQtRQBgwQi2VQFEl0549v9qzNe1F7BrK2trxbWS7ufJn1ExrKlu2DtRhn4WZsKMjHXvjM2q6nBp0Nxi4gkuoyn31UlHm20LjHmBeuFyG57Amuc8OeG7y1nNvqmkW53xrZTzqsYtZbRR+FQ295HbBJccZOOg3cuc54qpty8Fy19DVTpxpRsv919TQsNEnur+5i1eziiCSiS7jCMIJ3IOy6tmBzHIcYZc5557Fuls7WCytY7a0iWKBMkKCTyTkkk8kknJJ5NPgjWC2hgi3CKJFjQM5Y4AwMkkk/U0+uhTpqHeUTm5DJ5UggkmlYLHGpdmPYAZJr588WeI7vXdQee5do4EYmKEniIf+fU/tgD3jXbR7/Q9Rs4jiS4t5IlPoWUgfrXzTfQtJHLFyjHswwQfQ1h6QnJKMVkz0/sxQpzlOpJXksggvFkb+FLllO7Hv617V9l/iWbVrOWyv3MlzbgFJWOS6eh9SOOe4I6nJrwWws5YrjzJMKBnvnNetfYpak6zfXkqn7stuYGPbLspB/LYfpkVmwcnGqoxe5nV6cpQqYKVSqrSWR61SEAjB6U+WNon2scg8q3qKIk8yZFI3LnLD2rtngCxBGbmBTKDlT8L92FUdQ12y0+1eVWWaRJ/upXcECPt3EFmwFAAzmtDUUeeA21re/c7phujdQrMMH+Vuo7H9RXJnSr+XWbiLW7K1nsLyH/iZoJCql0/w5NpO5GxkcE9F54oEyl5d3qdxcXjaAdSEzh182+ET24KKREyZ4x83uGB70V1NhbrY2/lWmIkJLnzGLu7HqzMxySfeigVjk9NiuvFNstxqcOmapofmGO3ubiFra6ZMYZ025xzuAxtzg9BXWW0EdtbQW8ClYYI1ijDMWIVRgDJ5P1NMtLS3tBOLSIxRzTPcFNxIVmxuwO2TyQO5PrU9VUqWwt+ZdUntPdkFFFFWlYV4/wDav4c+5Xw1W1TFvct/FAHySdc/RuT9QfUV6+WUHBIqjrunR6to93Yy4xMhCk/hbqrfkQD+VU16SqwcWbujsbLBV41Vlx7j5zsraW8u4re3QyTSsEVR3JOB/wDa+hfDGjQ6Do0NlFhmHxSuB87nqf2HsAK83+x3TUuNYur6VCDaxr5Ybsz5GfqArD/ur2CGMzMB+D9f9qzYCjsx23mzre0ePdasqEerHzZLaL50TRPkx9UbuPpRfzHSdMluI4jcSgqNo43EsFGTzhRnJPYZNPvr+x0mBGv7qK2RztDSNtyf/f6VhNDq2ktJY2CJqGn3CkW7TyZNpns+eXjxkjqeNvoa3nmjCgFzrmp3N1aSy2WouqNKC4VY0wAkkb7NzoQN2wleT8QrsZCr3GT8pOfqe1V7CyttNtRb2cSRx8FtoI3NgDPJJ7DAzwABU5GRg9KASGNt3Hzdu/POf29qKeGYDBRXx0JPNFABRRRQMKRzgenIGfSloPI5oAASshRQFRfmJ7j1zTU6cdMnH07UvLKIyf8ApJ7+xoALZyCqj5vX6CgRR0fRbHTmnGn24hWeTdJhid7egyeB14HA5rXuLyDT2jinyryghG+VWbtGCfxHsO+DRNPBplm11eEoowoVVLHkgBQBkkkkcCuKubi41+6uEMjSLMWNpbyoy2txEvDI2RujmUgnPUEDHFJJLchym5O8ndlXTzcanDYWpngu3mjZ4GfdKYIw6GS3uBkErkINx5yMHrXWaXax6bpltZRzNKsS43ueSfYdh6DsKmsbZdPRRC3mzgYkndV3y46b2AG7A4z+dW5huj863AVf8wBeQaYkiA9NzDOflU9/c06JOAOw70iLuPUknuTmrCgKMCgCEowPTNFT0UAVqKKKBhRRRQAhAIwaJNQsdPSCTVbuC3DsViaZwoY/nxUsERmk2/hHLH2p+u6Ymp6cYAwimjIkglAz5TjocenYjuCR3oA5bXZLrVtQtree2u/7MuHMIuLGUSIpzujmVl5RgQAcjGG6nFbGlWK6ZbNCk0kzttDOyqoAUbVVVUAAAD9aq+HNJh0uxikNnHb6jLGfvLqQSzFstyOMZ6ccDArUoEgJx1p1uzLOhj5LHBA7inWwzdRexJ/0NLb7o7RnwVld9pJHKigY/aqSyqmNobjHb2pTx1pFUKoA6ChhlSPUYoENWVGHDf14oqBlQ43yeWwGCDj+tFAC0VS/tfSzqx0xdStG1AEj7uJBuz6fX260lvrGl3Opvp1vqVnLfJkNAsoLZHUe5HcVLZfIh72H6ly8S9QASQFGSeAKoWGs6XqNzLbafqNpczxDLxxSBiAOp9x9Kp3fiqHTPGumaHNZsRewhxdGTARmLhV247lMZz3oUJN2sKVenFKTe5u3idfbxCGML1PUn1NV7+UjbEMjcMk+o9K5v++8B8X6joptwkFjbvNJetJ8IKqpYbcdg3PPbpWnHqunzBIZtQgJlt/vsTlsfwv58njbQ4SWaFGvTnezydiWjIrOsNa03ULeeey1GymitxmaRZRiMerZ6D3pbfWNJu9PmvbbUrOSzgIM1x5owh7A+n70bL5ElVg8pI0O4IJBHQg4NTx3DN/Cn+NH+Hd0IzWfpt/Z6pbfeNNu4buHdtLxNkA+h9DWDe+LZLe51CTT9En1DT9KkKXl0s6ptZRlgiHltvfkUKDbsRnXpwipN7ny3+R14DKzIxyVOM+tLXNp4y0GfXYrFb5w1xbLdB+NvxAEJ0zu2kN9KuL4m8ONaSXQ1y38iMqrP5gwCwJA6dcA8e1GxJcBLEUnlJfM2CAeooplg9vqFpHdWN6Li2kGUkTDA/mKKiXJ3V0eSzvLfXVhqM0zKw8XpbiCNVSIAE/FgDJY45JJzV/Uoh4b17RjYkS293JdTfdrlFlSF9rHMZI3Lk9fioore1w7Gebi31uO0vMh8IRvJ4i8E3c88kj3dndO0ZVVjTjoiqAAOelWPtMH/N2pSKSslt4fS6iYdVkjugVI/wBf60UUn+KtcSUW3g5N8/4owLEmSCa4clprzw7qN3Mx/FI7tk/0AH5Vs2VtFeajoFtcpvhm8KKjrkjIO0dqKKc/uRoq9r9noZHi4SWMPiTSPPa4hgtrTZPMiGfb5yDYXCgsvsc9K6Hxp4Yt9Igtrxby8upbvUbOGVZ/L2MqscDaiKKKKllrsRUndu/L1kbfh9FT7QvGCxqEQCyO1RgElGJP1rD0qQ2nhz7RkiAxBd3joW5OWTB/Siis/wDX0Om9yXfU82JoqCK+0tFyR/dAnn3ZTVfSV26F4BsbbZai/ZzLPDEnm5VSQVYg4OT160UVZx12mXKN1y9YnU/ZEnl+Fp4wSwS+uFBPU4eiiistbrs6+C/Lw7kf/9k='
body: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCABkAGQDASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAAECAwQFBgcI/8QAOxAAAgEDAwIEAwYDBgcAAAAAAQIDAAQRBRIhMUEGE1FhIjJxBxRCgbHBI1KRFRYzQ6HhJCZygtHw8f/EABoBAAIDAQEAAAAAAAAAAAAAAAABAgMEBQb/xAAzEQACAQIDBAcGBwAAAAAAAAAAAQIDEQQx8BIhQVEFMmFxgbHBBhMkkaHRMzRSgsLi8f/aAAwDAQACEQMRAD8A+mLqdIYiiELGvU+tYlzM8kgAB3nhVH4f9/0pLi6aWQbAc5+Bf3+v6VPDGLSN5H3POELkIhchQMnCjkn2HJPFYKFK/wAXif2rX0++U5z3+5p+LJba2a3iyke+VuOOg/Os432jX93caHeSLcy3AaKSOWFxFMy/NGjkbSy+gOR+RxS8RxzXep6HaaZdraak4muYL+UEjKbA0GzI3bs8qegQnqOMm30efXnkU21vYxQy+Tco7OZLScTGaV7ZsYbzCVw2QVwOOMVXVc8TPafy1x1zL6cI04561rI1LXwisGpXCatHLqEYjVrTUmu2juogMAQsykNgdQy8HnPPJ7KSUiyU2+7aPhYsSzKAPfr9fzqqcZ4ycADLHJOPUmmtcpZK08rokQHxl2Crj3JroU6caasiiU5Te8UAAcUtU4NW0m7m26bqdldA/ghnV2X2IBzVyrE08iLi4uzVh8LqqmKX/Bbv/KaSRGikKP17H1FNqWJldBBKcD/Lf+U+lAiI8jmk64Vjgj5W/Y0rKyOUcYYf6+9SRRGTr8p4+vtQBFnHDcEdqK1A0cKqjOq4HQtRQBgwQi2VQFEl0549v9qzNe1F7BrK2trxbWS7ufJn1ExrKlu2DtRhn4WZsKMjHXvjM2q6nBp0Nxi4gkuoyn31UlHm20LjHmBeuFyG57Amuc8OeG7y1nNvqmkW53xrZTzqsYtZbRR+FQ295HbBJccZOOg3cuc54qpty8Fy19DVTpxpRsv919TQsNEnur+5i1eziiCSiS7jCMIJ3IOy6tmBzHIcYZc5557Fuls7WCytY7a0iWKBMkKCTyTkkk8kknJJ5NPgjWC2hgi3CKJFjQM5Y4AwMkkk/U0+uhTpqHeUTm5DJ5UggkmlYLHGpdmPYAZJr588WeI7vXdQee5do4EYmKEniIf+fU/tgD3jXbR7/Q9Rs4jiS4t5IlPoWUgfrXzTfQtJHLFyjHswwQfQ1h6QnJKMVkz0/sxQpzlOpJXksggvFkb+FLllO7Hv617V9l/iWbVrOWyv3MlzbgFJWOS6eh9SOOe4I6nJrwWws5YrjzJMKBnvnNetfYpak6zfXkqn7stuYGPbLspB/LYfpkVmwcnGqoxe5nV6cpQqYKVSqrSWR61SEAjB6U+WNon2scg8q3qKIk8yZFI3LnLD2rtngCxBGbmBTKDlT8L92FUdQ12y0+1eVWWaRJ/upXcECPt3EFmwFAAzmtDUUeeA21re/c7phujdQrMMH+Vuo7H9RXJnSr+XWbiLW7K1nsLyH/iZoJCql0/w5NpO5GxkcE9F54oEyl5d3qdxcXjaAdSEzh182+ET24KKREyZ4x83uGB70V1NhbrY2/lWmIkJLnzGLu7HqzMxySfeigVjk9NiuvFNstxqcOmapofmGO3ubiFra6ZMYZ025xzuAxtzg9BXWW0EdtbQW8ClYYI1ijDMWIVRgDJ5P1NMtLS3tBOLSIxRzTPcFNxIVmxuwO2TyQO5PrU9VUqWwt+ZdUntPdkFFFFWlYV4/wDav4c+5Xw1W1TFvct/FAHySdc/RuT9QfUV6+WUHBIqjrunR6to93Yy4xMhCk/hbqrfkQD+VU16SqwcWbujsbLBV41Vlx7j5zsraW8u4re3QyTSsEVR3JOB/wDa+hfDGjQ6Do0NlFhmHxSuB87nqf2HsAK83+x3TUuNYur6VCDaxr5Ybsz5GfqArD/ur2CGMzMB+D9f9qzYCjsx23mzre0ePdasqEerHzZLaL50TRPkx9UbuPpRfzHSdMluI4jcSgqNo43EsFGTzhRnJPYZNPvr+x0mBGv7qK2RztDSNtyf/f6VhNDq2ktJY2CJqGn3CkW7TyZNpns+eXjxkjqeNvoa3nmjCgFzrmp3N1aSy2WouqNKC4VY0wAkkb7NzoQN2wleT8QrsZCr3GT8pOfqe1V7CyttNtRb2cSRx8FtoI3NgDPJJ7DAzwABU5GRg9KASGNt3Hzdu/POf29qKeGYDBRXx0JPNFABRRRQMKRzgenIGfSloPI5oAASshRQFRfmJ7j1zTU6cdMnH07UvLKIyf8ApJ7+xoALZyCqj5vX6CgRR0fRbHTmnGn24hWeTdJhid7egyeB14HA5rXuLyDT2jinyryghG+VWbtGCfxHsO+DRNPBplm11eEoowoVVLHkgBQBkkkkcCuKubi41+6uEMjSLMWNpbyoy2txEvDI2RujmUgnPUEDHFJJLchym5O8ndlXTzcanDYWpngu3mjZ4GfdKYIw6GS3uBkErkINx5yMHrXWaXax6bpltZRzNKsS43ueSfYdh6DsKmsbZdPRRC3mzgYkndV3y46b2AG7A4z+dW5huj863AVf8wBeQaYkiA9NzDOflU9/c06JOAOw70iLuPUknuTmrCgKMCgCEowPTNFT0UAVqKKKBhRRRQAhAIwaJNQsdPSCTVbuC3DsViaZwoY/nxUsERmk2/hHLH2p+u6Ymp6cYAwimjIkglAz5TjocenYjuCR3oA5bXZLrVtQtree2u/7MuHMIuLGUSIpzujmVl5RgQAcjGG6nFbGlWK6ZbNCk0kzttDOyqoAUbVVVUAAAD9aq+HNJh0uxikNnHb6jLGfvLqQSzFstyOMZ6ccDArUoEgJx1p1uzLOhj5LHBA7inWwzdRexJ/0NLb7o7RnwVld9pJHKigY/aqSyqmNobjHb2pTx1pFUKoA6ChhlSPUYoENWVGHDf14oqBlQ43yeWwGCDj+tFAC0VS/tfSzqx0xdStG1AEj7uJBuz6fX260lvrGl3Opvp1vqVnLfJkNAsoLZHUe5HcVLZfIh72H6ly8S9QASQFGSeAKoWGs6XqNzLbafqNpczxDLxxSBiAOp9x9Kp3fiqHTPGumaHNZsRewhxdGTARmLhV247lMZz3oUJN2sKVenFKTe5u3idfbxCGML1PUn1NV7+UjbEMjcMk+o9K5v++8B8X6joptwkFjbvNJetJ8IKqpYbcdg3PPbpWnHqunzBIZtQgJlt/vsTlsfwv58njbQ4SWaFGvTnezydiWjIrOsNa03ULeeey1GymitxmaRZRiMerZ6D3pbfWNJu9PmvbbUrOSzgIM1x5owh7A+n70bL5ElVg8pI0O4IJBHQg4NTx3DN/Cn+NH+Hd0IzWfpt/Z6pbfeNNu4buHdtLxNkA+h9DWDe+LZLe51CTT9En1DT9KkKXl0s6ptZRlgiHltvfkUKDbsRnXpwipN7ny3+R14DKzIxyVOM+tLXNp4y0GfXYrFb5w1xbLdB+NvxAEJ0zu2kN9KuL4m8ONaSXQ1y38iMqrP5gwCwJA6dcA8e1GxJcBLEUnlJfM2CAeooplg9vqFpHdWN6Li2kGUkTDA/mKKiXJ3V0eSzvLfXVhqM0zKw8XpbiCNVSIAE/FgDJY45JJzV/Uoh4b17RjYkS293JdTfdrlFlSF9rHMZI3Lk9fioore1w7Gebi31uO0vMh8IRvJ4i8E3c88kj3dndO0ZVVjTjoiqAAOelWPtMH/N2pSKSslt4fS6iYdVkjugVI/wBf60UUn+KtcSUW3g5N8/4owLEmSCa4clprzw7qN3Mx/FI7tk/0AH5Vs2VtFeajoFtcpvhm8KKjrkjIO0dqKKc/uRoq9r9noZHi4SWMPiTSPPa4hgtrTZPMiGfb5yDYXCgsvsc9K6Hxp4Yt9Igtrxby8upbvUbOGVZ/L2MqscDaiKKKKllrsRUndu/L1kbfh9FT7QvGCxqEQCyO1RgElGJP1rD0qQ2nhz7RkiAxBd3joW5OWTB/Siis/wDX0Om9yXfU82JoqCK+0tFyR/dAnn3ZTVfSV26F4BsbbZai/ZzLPDEnm5VSQVYg4OT160UVZx12mXKN1y9YnU/ZEnl+Fp4wSwS+uFBPU4eiiistbrs6+C/Lw7kf/9k='

**Comment by Eider3a** [comment]
That's what I get when I try to get the coordinates, I think the coordinates are there but I do not know how to decrypt them.
I have had this issue for a long time. I think they removed this part from the documentation because I can not find anything related to this feature.

**Comment by SalehAlresaini** [comment]
I believe they are images base64 encoded, you can check in [this website](https://codebeautify.org/base64-to-image-converter)  to decode it online.

As for the latitude and longitude, I am not sure if this pull request fixed it: [https://github.com/orkestral/venom/pull/1281](https://github.com/orkestral/venom/pull/1281)

**Comment by jonalan7** [comment]
Has the issue been fixed! #1339
