### ISSUE TITLE
UnhandledPromiseRejection. Recebo esse ERRO e não sei sua origem

### ISSUE THREAD

**Issue by AlmirFill** [orkestral/venom#1363]
Esse erro tem certa recorrência em meu projeto, e estou enfrentando dificuldades em  resolve lo:

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
[ERROR] 07:43:29 UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".

meu package.json: 
{
  "dependencies": {
    "@types/node": "^15.0.1",
    "axios": "^0.21.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "mongoose": "^5.12.8",
    "venom-bot": "^4.0.3"
  },
  "scripts": {
    "dev": "ts-node-dev --respawn --transpile-only .\\src\\app.ts"
  },
  "devDependencies": {
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.2.4"
  }
}

**Comment by AlexsandroZanella2** [comment]
Write in English please.

**Comment by AlexsandroZanella2** [comment]
Also post your code, I believe you forgot to use try catch.
