### ISSUE TITLE
sendLinkPreview don't show thumbnail

### ISSUE THREAD

**Issue by LeoGarcez** [orkestral/venom#1370]
## Description

I updated for 4.0.3, and link preview stops work

## Your Code

 client
   .sendLinkPreview(
     message.from,
     "https://www.youtube.com/watch?v=xQ04WbgI9rg",
     ""
   )
   .then((result) => {
     console.log("Result: ", result); //return object success
   })
   .catch((erro) => {
     console.error("Error when sending: ", erro); //return object error
   });

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/19170860/146449934-2dd78c25-6c66-4e5d-a500-1e6973e63637.png)

**Comment by LeoGarcez** [comment]
Comparing two minified files, the preview is missing when send message and the query is not used, I change locally and works
![image](https://user-images.githubusercontent.com/19170860/146453793-c2232a7e-5116-40d3-9a6c-6f6f1d9084fd.png)

**Comment by jadsonlourenco** [comment]
Same issue until today...

**Comment by dpakakpo4** [comment]
![Image](https://github.com/user-attachments/assets/c97f1026-38fc-4e0c-8dd4-601042ec5620)

Hi I was abl to make the preview link work by using this code :

`sendLinkPreview("your_chat_id", link, 'Title Of the link', "Message of the link")`
