### ISSUE TITLE
useHere() function Return Error  : TypeError: Cannot read properties of undefined (reading 'takeover')

### ISSUE THREAD

**Issue by anaselfadili** [orkestral/venom#1373]
## Description

useHere() function Return Error  : TypeError: Cannot read properties of undefined (reading 'takeover')

" UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'takeover') "

## Environment

- Venom version(s): 4.0.3
- Browser: Version 92.0.4515.131
- OS: Windows 10
- Node version: v14.17.4

**Comment by jknvlvxs** [comment]
I am having the same error. I detect the conflict and try to use useHere on my client. However, I get this error and it tries to redo the QRCode process. Ideally, it would automatically reconnect.

Do you now how to solve this?
