### ISSUE TITLE
Whatsapp Web Beta does not work correctly

### ISSUE THREAD

**Issue by mufer19** [orkestral/venom#1385]
## Description

Requests to Whatsapp are not processed when using Whatsapp Web Beta. It used to work, but it stopped. Incoming events are processed, outgoing ones are not.

## Environment

- **Venom version(s):** 4.0.4
- **Browser:** Chrome
- **OS:** CentOS 7
- **Node version:** 17

## Steps to Reproduce

Client 1 = WA Web Beta
Client 2 = WA Web

[Log](https://prnt.sc/246wm1c)
[Code](https://prnt.sc/246wvy2)

**Comment by mufer19** [comment]
4.0.3 Correct
4.0.4 There is a problem

**Comment by gifuzzz** [comment]
so to use the beta version properly we should downgrade to 4.0.3?

**Comment by gifuzzz** [comment]
> 4.0.3 Correct 4.0.4 There is a problem

so to use the beta version properly we should downgrade to 4.0.3?
