### ISSUE TITLE
Browser session token is incomplete

### ISSUE THREAD

**Issue by siddharthjaidka** [orkestral/venom#1389]
Only WaBrowserId comes in from token

**Comment by acognigni-evotecnia** [comment]
could i get some more details of what you found? i might try to fix this myself and would like a starting point

**Comment by siddharthjaidka** [comment]
So basically older versions as in non-beta ones extract 4 keys namely WABrowserID, token 1 & 2, secret bundle. In multi devices support only BrowserID is returned in browser session token. So I am unable to reinject previous session.

**Comment by acognigni-evotecnia** [comment]
as a workaroud i obtained the session token with venom version 4.0.3

**Comment by siddharthjaidka** [comment]
Okay so i am currently on 4.0.3 only and using ios multi beta, not able to obtain, can you share the piece of code?

**Comment by acognigni-evotecnia** [comment]
i don't know why this got closed. i don't see a commit, PR or new release. 

disable the beta it has given me a lot of issues
