### ISSUE TITLE
Venom em Express/Total com Token

### ISSUE THREAD

**Issue by DeLuca92** [orkestral/venom#140]
Olá, tudo bem?
Gostaria de saber se existe algum projeto sendo feito com base no venom em express ou total?
Se tiver por favor me manda o repo que eu posso ajudar a implementar :).
Hoje uso a Wa-Automate/W2api e ela é muito boa, mas o unico problema que eu enfrento hoje e não enviar msg para não contatos :/

Outra duvida é possível enviar img da url?

**Comment by joaosouz4** [comment]
Você pode criar esse projeto convertendo o w2api para o venom, vou ficar feliz em ajudar com esse projeto.

**Comment by igormenin** [comment]
Existe este projeto abaixo, pelo que vi ele usa express.

https://github.com/billbarsch/myzap

**Comment by DeLuca92** [comment]
> Existe este projeto abaixo, pelo que vi ele usa express.
> 
> https://github.com/billbarsch/myzap

Eu vi esse, mas é bem basicão, talvez use como base, mas o total.js me parece melhor ehhe

**Comment by DeLuca92** [comment]
> Você pode criar esse projeto convertendo o w2api para o venom, vou ficar feliz em ajudar com esse projeto.

Opa, eu pilho sim.
VOu começar a ver sobre isso esse final de semana e te convido para repo

**Comment by winkcler** [comment]
> > Você pode criar esse projeto convertendo o w2api para o venom, vou ficar feliz em ajudar com esse projeto.
> 
> Opa, eu pilho sim.
> VOu começar a ver sobre isso esse final de semana e te convido para repo

Deluca pode falar comigo no instagram. @sulltanmusic
