### ISSUE TITLE
Sending a message to status@broadcast

### ISSUE THREAD

**Issue by dxkyy** [orkestral/venom#1408]
## Description

When I try to send a message to `status@broadcast` using 
```js
await client
      .sendText("status@broadcast", "test")
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });
```

I get this: 
```js
{
  me: {},
  to: 'status@broadcast',
  erro: true,
  text: 'incorrect parameters! Use as an example: 0000000000@broadcast',
  status: 404,
  result: null
}
```

## Environment

- **Venom version(s):** latest
- **Browser:** Chrome
- **OS:** Windows 10
- **Node version:** Node 17.3.1

**Comment by AlexsandroZanella2** [comment]
The problem is already written there. status is not a number. use something like 555499898874@broadcast.

**Comment by RogerioFernandes** [comment]
How do I send a message to "My status" in the Whatsapp updates tab???
