### ISSUE TITLE
ninth digit does not deliver

### ISSUE THREAD

**Issue by gamadoleo** [orkestral/venom#141]
ninth digit problem in brazil,
has anyone faced a problem of not sending messages to phones that have the ninth digit? on the device does it have only a single line and the message does not reach the recipient?

refer to places that you are not required to use the ninth digit on whatsapp ... for example my number is just 8 digits and if I send a message with the venom adding the ninth digit the message is not delivered.

**Comment by mrangelba** [comment]
Use o método getNumberProfile para consultar, pode usar o número com os 9 dígitos e utilize o Id do retorno para enviar a mensagem. No Id já retorna com 8 ou 9 dígitos, da forma que está cadastrado no WhatsApp.

**Comment by gamadoleo** [comment]
> Use the getNumberProfile method to query, you can use the 9-digit number and use the return Id to send the message. No Id already returns with 8 or 9 digits, as registered in WhatsApp.


Good morning, I actually made a query via getNumberProfile either passing 8 digits or 9 digits always comes with 8 digits in the return, now a question: I currently send using the format

example:
wait client.sendText ("000000000000@c.us",'mensage')

you're telling me that if I get the return from getNumberProfile this way it will work:
var profile = getNumberProfile ("000000000000@c.us")
and call it that?

client.sendText (profile.id, "message")

**Comment by mrangelba** [comment]
client.sendText (profile.id._serialized, "message")

It is good to check the status that returns in getNumberProfile, check if it returned 200.
