### ISSUE TITLE
onStateChanged not working 

### ISSUE THREAD

**Issue by Mohadin** [orkestral/venom#1418]
## Description

onStateChanged not working .

## Environment

    Venom version(s): e.g. 4.0.4
    Browser: Chromium 938248
    OS: Windows 10 Pro (WSL: Ubuntu)
    Node version: Node 14.8.2 (I also tested with node 17+ and node 8.x)

## Your Code

```
this.whatsapp.onStateChange((state) => {
			 console.log('State changed: ', state);
			// force whatsapp take over
			if ('CONFLICT'.includes(state)) {
				//this.whatsapp.useHere();
				process.exit(1)
			}
			// detect disconnect on whatsapp
			if ('UNPAIRED'.includes(state)) {
				console.log('logout');
				process.exit(1)
			}
		});
```

**Comment by yuriburk** [comment]
Same

**Comment by henrickJona** [comment]
same

**Comment by AlexsandroZanella2** [comment]
same.
Node 8, 12, 14.18 and 16.13.
W 8, 10, server 2008, 2012, 2016, 2019

**Comment by jonatascalebe** [comment]
same

**Comment by ArtemAlekhin** [comment]
Same

**Comment by marciodiasdeveloper** [comment]
same

**Comment by lukasportal** [comment]
the WAPI code is listening to state change `window.Store.State.default.on...` but instead it should use `window.Store.State.Socket.on...`

**Comment by rafaelOsio** [comment]
same

**Comment by sandro-salles** [comment]
onStateChanged still not working on version 4.0.9. ... anyone else with the same problem?

**Comment by warklp** [comment]
Same problem here
