### ISSUE TITLE
Chrome closing after logging in

### ISSUE THREAD

**Issue by mateusbarros92** [orkestral/venom#1429]
## Description
Browser closing after logging in.
I created the token in my local machine and I'm trying to use it on github actions, is there a problem on doing it?

## Environment

- **Venom version(s):** 4.0.5
- **Browser:** Chromium 99.0.4839.0 
- **OS:**  Ubuntu 20.04.3
- **Node version:** 14.18.1

## Log Output
![Screenshot from 2022-01-18 17-52-09](https://user-images.githubusercontent.com/28282371/150016753-f0842462-7de7-4ac6-953e-c4cfdd69f69b.png)

## Your Code

```
  create(
    'livres-bot',
    undefined,
    (statusSession, session) => {
      console.log('Status Session: ', statusSession)
      console.log('Session name: ', session)
    },
    {
      headless: true,
      browserArgs: ['--no-sandbox', '--disable-setuid-sandbox']
    }
  )
```

**Comment by antirek** [comment]
I used Chromium, after some troubles I began to use Chrome.

**Comment by arthuras96** [comment]
As a workaround i currently using version 4.0.3 and disable the beta.

**Comment by mateusbarros92** [comment]
I tried the same thing @arthuras96 with no success.

**Comment by mateusbarros92** [comment]
It worked @arthuras96
