### ISSUE TITLE
Multi device not send text message

### ISSUE THREAD

**Issue by nonna2010** [orkestral/venom#1433]
## Description

Multi device not send text message

## Environment

- **Venom version(s):** 4.0.5
- **Browser:** chrome88
- **OS:** ubuntu 18.04
- **Node version:** node12

**Comment by marksamfd** [comment]
same here

**Comment by bruyby** [comment]
Estou tendo o mesmo.

**Comment by Mohadin** [comment]
same here

**Comment by donaldjansen** [comment]
same here

**Comment by donaldjansen** [comment]
I noticed that sendMessage2 works but doesn't give a message Id, but sendMessage is the one that is not working

**Comment by jonalan7** [comment]
**The beta is a stage version still in development! They disabled the function to check the numbers.**
![WhatsApp Image 2022-01-28 at 14 33 43](https://user-images.githubusercontent.com/67329824/151598643-ab3f399b-466d-4f9a-956a-896f68e1f64b.jpeg)
**2.2202.9 is the latest, it is working fine!**
