### ISSUE TITLE
Tokens are not been created

### ISSUE THREAD

**Issue by gonmartinez** [orkestral/venom#1434]
## Description

When I create a new venom client no tokens are created and the session throws an unkown error after a few minutes.

```
2|whatsapp | - [instance: 5aadccfb-845c-5e1f-65d7-b5fb62f098bf]: Connected
2|whatsapp | - [instance: 5aadccfb-845c-5e1f-65d7-b5fb62f098bf]: Page Closed
2|whatsapp | - [instance: 5aadccfb-845c-5e1f-65d7-b5fb62f098bf]: Checking QRCode status...
2|whatsapp | - [instance: 5aadccfb-845c-5e1f-65d7-b5fb62f098bf]: Failed to authenticate
2|whatsapp | - [instance: 5aadccfb-845c-5e1f-65d7-b5fb62f098bf]: Unknow error
```

## Environment

- **Venom version(s):** 4.0.5
- **Browser:** Chrome 97.0.4692.71
- **OS:** Ubuntu 20.10
- **Node version:** v14.17.6

## Steps to Reproduce

1. Create a channel
2. Wait a few minutes
3. The session will finish

## Your Code

```
const venom = require('venom-bot');
venom
  .create({
    session: 'session-name', 
    multidevice: false 
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
     client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); 
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); 
        });
  });
}
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/8240607/150393529-114e23dc-1e2e-49db-bce5-88dfddc6edf3.png)

**Comment by marciodiasdeveloper** [comment]
consegui sucesso na criação do token utilizando o multidevice: true.

**Comment by gonmartinez** [comment]
that's right the multidevice on true is the only way to get a token at the moment

**Comment by acognigni-evotecnia** [comment]
can confirm.
Keep in mind that multidevice true seems to work for accounts  with and without the beta
I don't really know any reason to NOT have it on true which is what worries me. am I missing something? 
multidevice should be made the default and the parameter ignored
