### ISSUE TITLE
Error: ENOENT: no such file or directory, open DevToolsActivePort

### ISSUE THREAD

**Issue by marciodiasdeveloper** [orkestral/venom#1435]
server > Error: ENOENT: no such file or directory, open './55120-5fca-42d0-a4d5-4cdb1814d7ad/DevToolsActivePort'

the token exists inside the tokens folder, when venom tries to read it it doesn't seem to find the file

## Environment

- **Venom version(s):** [4.0.5]
- **Browser:** [Chrome]
- **OS:** [Debian]
- **Node version:** [Node 16]

**Comment by ynfantes** [comment]
Me too

errno: -4058,
syscall: 'open',
code: 'ENOENT',
path: './support/DevToolsActivePort'

- Venom version: 4.0.5
- Browser: Chrome
- OS: Windows 10
- Node version: 15.2.1

**Comment by alihalabyah** [comment]
For now to resolve this issue, disable the debugging.
