### ISSUE TITLE
TypeError: Cannot read property 'product' of null Erro ao criar o venombot

### ISSUE THREAD

**Issue by rafosolima** [orkestral/venom#1436]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [4.0.5]
- **Browser:** [e.g. Chrome 96]
- **OS:** [ Windows 10]
- **Node version:** [Node 14]

Desde a versão 4.0.4 não consigo criar a sessao do venombot com o chorme sempre dando essa mensagem ao criar a sessão. Não posso usar o chromium.

TypeError: Cannot read property 'product' of null
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at new BrowserFetcher (/home/raphael/Code/apache/venom-bot-adonis/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:158:34)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at PuppeteerNode.createBrowserFetcher (/home/raphael/Code/apache/venom-bot-adonis/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:185:16)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at PuppeteerExtra.createBrowserFetcher (/home/raphael/Code/apache/venom-bot-adonis/node_modules/puppeteer-extra/dist/index.cjs.js:175:26)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at /home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:242:64
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at step (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:44:23)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at Object.next (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:25:53)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at /home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:19:71
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at new Promise (<anonymous>)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at __awaiter (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:15:12)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at initBrowser (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/browser.js:231:12)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at Object.<anonymous> (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/initializer.js:148:68)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at step (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/initializer.js:98:23)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at Object.next (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/initializer.js:79:53)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at /home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/initializer.js:73:71
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at new Promise (<anonymous>)
0|app_whatsapp_5_1  | 2022-01-20T23:27:19:     at __awaiter (/home/raphael/Code/apache/venom-bot-adonis/node_modules/venom-bot/dist/controllers/initializer.js:69:12)

**Comment by Silventino** [comment]
Same error here

**Comment by Silventino** [comment]
As a workaround, remove "chrome: false"

**Comment by rafosolima** [comment]
I changed useChrome and even now it is giving this error: 
Error: Error no open browser....

I am using WSL2

**Comment by Silventino** [comment]
Can you share the params you are passing to venom.create?

**Comment by rafosolima** [comment]
```
await venom.create(
        `integracao_${this.idEmpresa}_${this.idIntegracao}`,
        async (base64Qr, asciiQR, attempts, urlCode) => {
          this.whatsappWs = Ws.getChannel("whatsapp").topic("whatsapp")
          if (this.whatsappWs) {
            this.whatsappWs.broadcast("qrCode", {
              base64Qr,
              idIntegracaoDisconnect: this.reconnect ? this.idIntegracao : null,
              idEmpresaDisconnect: this.reconnect ? this.idEmpresa : null
            });
          } else {
            throw ErrorException(
              `WebSocket não conectado, por favor reinicie a central`,
              "",
              "error"
            )
          }
        },
        async (statusSession, session) => {
          console.log("======================================= Status Session =======================================", statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken || chatsAvailable || deviceNotConnected || serverWssNotConnected || noOpenBrowser
          //Create session wss return "serverClose" case server for close
          this.whatsappWs = Ws.getChannel("whatsapp").topic("whatsapp")

          switch (statusSession) {
            case 'isLogged':
              this.whatsappWs.broadcast("alertMessage", {
                message: `Central está sendo inicializada para ${this.contactInfo.descricao} (${this.contactInfo.phonenumber}), por favor aguarde, até a exibição da mensagem de sucesso`,
                type: "info",
              })
              break;
            case 'chatsAvailable':
              break;
            case 'notLogged':
              this.reconnect = true
              break;
            case 'qrReadSuccess':
              this.whatsappWs.broadcast("alertMessage", {
                message: `QR Code lido com sucesso para ${this.contactInfo.descricao} (${this.contactInfo.phonenumber})`,
                type: "sucess",
              });
              this.whatsappWs.broadcast("loadingChatInDb");
              break;
            case 'qrReadFail':
              this.whatsappWs.broadcast("alertMessage", {
                message: `Por favor, leia o qrCode para ${this.contactInfo.descricao} (${this.contactInfo.phonenumber})`,
                type: "warning",
              });
              cmsModel.updateStatusLine(
                "N",
                this.idEmpresa,
                this.idIntegracao
              );
              break;
            case 'desconnectedMobile':
            case 'serverClose':
            case 'browserClose':
              this.whatsappWs.broadcast("deviceNotConnected", {
                  id_empresa: this.idEmpresa,
                  id_integracao: this.idIntegracao,
                  tipo_mensageiro: "whatsapp",
              });
              cmsModel.updateStatusLine(
                "N",
                this.idEmpresa,
                this.idIntegracao
              );
              break;
          }
        },
        {
          multidevice: true,
          disableWelcome: true,
          useChrome: true,
          logQR: true,
          autoClose: 120000,
          browserArgs: ["--no-sandbox"],
        },
        null,
        (browser, waPage) => {
          this.browser = browser;
          this.waPage = waPage;
        }
      );
```

**Comment by Silventino** [comment]
I don't know if it's the same error, but when I had the "No open browser" thing, I solved it by installing puppeteer dependencies:
```
sudo apt update && sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```

**Comment by rafosolima** [comment]
I installed it and it still didn't work, I don't know what to do anymore

**Comment by rafosolima** [comment]
Well, I kind of managed to solve it by putting the console.log in the build to see the path that is returned to me from the venombot. With this I realized that:

when I use useChrome true, it returns the relative path inside windows
```
/mnt/c/Program Files/Google/Chrome/Application/chrome.exe
```

Problem 1: I didn't have chrome installed on my local windows.
Problem 2: The path is wrong for linux by WSL2 system, the correct path is 
```
/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe
```

My Solution: I already have google-chorme-stable and chromium-browser installed on my wsl2 (ubuntu) so I just needed to force the path to:
```
/usr/bin/google-chrome-stable 
```
in node_modules
```
<project>/node_modules/venom-bot/dist/controllers/browser.js
``` 
after line 237:
```
chromePath = '/usr/bin/google-chrome-stable';
extras = __assign(__assign({}, extras), { executablePath: chromePath });
```

**Comment by joel-vasiliev** [comment]
I'd have the same issue, I've just downloaded node and npm for windows and run from powershell
