### ISSUE TITLE
Today i have error: The number does not exist, But yesterday everything was working

### ISSUE THREAD

**Issue by rumantic** [orkestral/venom#1437]
## Description

I try connect to whatsapp from different numbers and different IP, but result the same.

## Environment

- **Venom version(s):** 4.0.3
- **Browser:** Chromium 85
- **OS:** Windows 10
- **Node version:** Node 12

## Steps to Reproduce

1. Create session by scanning QR-code - OK
2. Get messages from chat - OK
3. Send message to chat - NOT FOUND

whatsapp.sendText(chat.chatId, message)

{
  "me": {},
  "to": "XXXXX...@c.us",
  "erro": true,
  "text": "The number does not exist",
  "status": 404,
  "result": null
}

But yesterday everything was working

**Comment by ojixzzz** [comment]
i have the same problem, run the latest venom update and it will run again

**Comment by rumantic** [comment]
> i have the same problem, run the latest venom update and it will run again

You mean switch to venom-bot 4.0.5 and message will send well?

**Comment by rumantic** [comment]
> i have the same problem, run the latest venom update and it will run again

thanks, update to 4.0.5 and its work! )
