### ISSUE TITLE
Return The number does not exist

### ISSUE THREAD

**Issue by Havaiano78** [orkestral/venom#1439]
Is it true that my venom was working perfectly and out of nowhere there is a bug that no longer works sending messages, only works if I update the venom? 

![image](https://user-images.githubusercontent.com/88166804/150541012-d7025131-7146-4080-ac76-98dcd6db82a6.png)

"node_modules/venom-bot": {
      "version": "4.0.6-alpha.0",

**Comment by Havaiano78** [comment]
I copied the C:UsersNsantosDesktopCopia-20220117T135912Z-001Copiachatbotnormalnode_modulesvenom-botdistlibwapiwapi.js and played for the venom bot penultimate versao, so it works.

**Comment by ricardofanetto** [comment]
I'm having the same problem too, I use version 4.0.0

**Comment by JoaoAngelo** [comment]
I have the same problem, I'm using the version 4.0.5

**Comment by Havaiano78** [comment]
That's that... many bugs emerging
My solution of copying wapi.js works

**Comment by lukasportal** [comment]
WhatsApp updates its web version without notice, and this may break our code because they changed naming, classes, methods, whatever
its not venom's owner trying to make your code stop working lol

**Comment by JoaoAngelo** [comment]
I installed this module and was able to send messages

npm install destroy

**Comment by altamirosantos** [comment]
run npm update.

**Comment by lukasportal** [comment]
this is still not working for me. Even if you open a whatsapp link like "wa.me/<number>" won't work on web.whatsapp.com on my own chrome browser (nothign even related to venom)

how did you have it fixed?

**Comment by altamirosantos** [comment]
Verify your package.json. Change for ^4.0.5, If you still haven't changed.

**Comment by Havaiano78** [comment]
Forgive me for my ignorance

**Comment by mburgos012576** [comment]
Buenas tardes, desde ayer tambien me sale este problema con el Venon 
Error when sending:  {
  me: {},
  to: '51993034280@c.us',
  erro: true,
  text: 'The number does not exist',
  status: 404,
  result: null
}

espero me puedan apoyar, gracias
