### ISSUE TITLE
Closing (saving) sessions

### ISSUE THREAD

**Issue by younglotushuncho** [orkestral/venom#1440]
how do I insert the closing saving sessions code in the project

**Comment by r3r** [comment]
Using https://github.com/orkestral/venom/issues/1404 as reference

I was able to write the following and it works:

`const TOKEN_DIR = "./tokens";
const TOKEN_PATH = TOKEN_DIR + "/session-wa.json";
var browserSessionToken = null;

if (fs.existsSync(TOKEN_PATH)) {
  browserSessionToken = JSON.parse(fs.readFileSync(TOKEN_PATH));
}

venom
  .create({
    session: 'session-wa', //name of session
    multidevice: false, // for version not multidevice use false.(default: true)
    folderNameToken: 'tokens', //folder name when saving tokens
    createPathFileToken: true,
    headless: true,
    browserSessionToken: browserSessionToken,
  })
  .then((client) => {
    client.getSessionTokenBrowser().then((result) => {
      fs.promises.mkdir(TOKEN_DIR, { recursive: true })
        .then(s => {
          fs.writeFile(
            TOKEN_PATH, 
            JSON.stringify(result), 
            function(err) {
              if(err) return 
              console.error(err);
            });
          }).catch((error) => { console.error(error)});
      }).catch((error) => { console.error(error)});
      
      // Start client in parallel
      start(client);
  })
  .catch((erro) => {
    console.log(erro);
  });`
