### ISSUE TITLE
The number does not exist 

### ISSUE THREAD

**Issue by AlePro12** [orkestral/venom#1446]
Venom was working perfectly until yesterday and it gives me this problem

the number is registered in whatsapp and exists

<img width="325" alt="Sin título" src="https://user-images.githubusercontent.com/46333161/151077486-9e387c11-cf84-48fa-a1f0-ea6cbb1de013.png">

Venom 4.0.5
Node v16.13.0
Ubuntu 20.04 LTS

**Comment by lukasportal** [comment]
same here

**Comment by altamirosantos** [comment]
This also happened to me. However, when connecting another number, there was no error. Seems like it's only happening for a few numbers.

**Comment by lukasportal** [comment]
From my tests, it seems like the problem is only with Beta
even on WhatsApp web without anything injected on chrome, opening a link like wa.me/chatId won't work, it will say its invalid
but if you do the same procedure without using whatsapp beta, it works

**Comment by jeferssonlemes** [comment]
same here

**Comment by AlePro12** [comment]
I deactivated the beta and it worked perfectly

**Comment by sergey-chechaev** [comment]
same here

**Comment by erickmourasilva** [comment]
Any solution to MD version?

**Comment by douglasduarte** [comment]
same here

**Comment by Mohadin** [comment]
same here

**Comment by jonalan7** [comment]
**The beta is a stage version still in development! They disabled the function to check the numbers.**
![WhatsApp Image 2022-01-28 at 14 33 43](https://user-images.githubusercontent.com/67329824/151598643-ab3f399b-466d-4f9a-956a-896f68e1f64b.jpeg)
**2.2202.9 is the latest, it is working fine!**

**Comment by mhjd30** [comment]
I'm running with this version 2.2202.9 of wa web and the problem continues.
Can you reopen this question, please?
I don't know how to solve

**Comment by vhmvictor** [comment]
Any solution? I don't know how to solve...
