### ISSUE TITLE
After updating whatsapp everything isn't working

### ISSUE THREAD

**Issue by KarimMohamed20** [orkestral/venom#1447]
## Description

When I try to scan the QR Code it doesn't scan it quickly as before and I need to scan it too many times and after connecting successfully nothing is working as before

## Environment

- **Venom version(s):** 4.0.5
- **Browser:** Chrome
- **OS:** MacOS and Windows
- **Node version:** 12.xx

**Comment by GuilhermeHumberto** [comment]
same here

**Comment by HuskyCodez** [comment]
> ## Description
> When I try to scan the QR Code it doesn't scan it quickly as before and I need to scan it too many times and after connecting successfully nothing is working as before
> 
> ## Environment
> * **Venom version(s):** 4.0.5
> * **Browser:** Chrome
> * **OS:** MacOS and Windows
> * **Node version:** 12.xx

having same issue here, session was signed out and could not get QR code
