### ISSUE TITLE
WHASAPP BAN

### ISSUE THREAD

**Issue by nielson266** [orkestral/venom#1451]
Olá como evitar ser ban do whatsapp?
Tem um tempo que posso enviar mensagens? O número tem que estar salvo nos meus contatos? Como posso proceder?
Obrigado pela ajuda!

**Comment by antirek** [comment]
this isn't issue
read docs, communicate with others in whatsapp and telegram chats ))

**Comment by AlexsandroZanella2** [comment]
please, write in english.
you will be banned if you receive reports, so don't spam
