### ISSUE TITLE
sendText is not working on Multi Device

### ISSUE THREAD

**Issue by donaldjansen** [orkestral/venom#1452]
## Description

sendText is not working when you send to a contact, it is working when you send to a group. It does not give an error 

## Environment

**Venom version(s):** 4.0.5
**Browser:** Chromium 97
**OS:** [Windows 10]
**Node version:** v14.17.3

## Steps to Reproduce

1. Install the latest venom-bot library 4.0.5
2. run the sample from github where you reply with Welcome Venom 🕷
3. open whatsapp send 'Hi' and you will get no response and no error

## Workaround
in check-number-status.js there is a line that checks if the instance is on BETA or not, whatsapp web no longer have this tag available.
This line:   
const checkBeta = document.querySelector('._3hcUV');
    if (checkBeta && checkBeta.innerText === 'BETA') {

The workaround is to change the two lines to
const checkBeta = true; // this is temporary as all my numbers are on Multi Device which is no longer BETA in our country
 if (checkBeta) {
  //
 }

**Comment by Mohadin** [comment]
same here

> This doesnt fix it for me my issue is that await Store.checkNumberBeta('[9999999@c.us](mailto:9999999@c.us)') always returns null, even if the number is valid this is also a problem if you click on a whatsapp link within whatsapp web, even if in chrome without any of the venom code wa.me/99999999 it will say its not a valid number seems like a bug with whatsapp web itself
same here

**Comment by jonalan7** [comment]
**The beta is a stage version still in development! They disabled the function to check the numbers. but now this duct is ok!**
![WhatsApp Image 2022-01-28 at 14 33 43](https://user-images.githubusercontent.com/67329824/151598643-ab3f399b-466d-4f9a-956a-896f68e1f64b.jpeg)
**2.2202.9 is the latest, it is working fine!**
