### ISSUE TITLE
It is not possible to send buttons with the option multiple devices (beta) enabled. 

### ISSUE THREAD

**Issue by LincolnJota** [orkestral/venom#1460]
## Description

This bug happens when I activate the new whatsapp option, I can't send buttons, and honestly, I need it a lot (multiple devices). Is there any way to resolve this bug? 

## Environment

- **Venom version(s):** latest version 
- **Browser:** Default config
- **OS:**  Windows 10
- **Node version:** version 16.13.2

## Steps to Reproduce

1. Enable multi devices in android device
2. Connect in bot
3. bot does not send buttons and throws an error in the console. 

## Log Output

```json
{
   "me":{
   },
   "to":{
      "fromMe":true,
      "remote":{
         "server":"c.us",
         "user":"myNumberHere",
         "_serialized":"myNumberHere@c.us"
      },
      "id":"BT7UTHMURMJKMOJSCX1H",
      "_serialized":"true_myNumberHere@c.us_BT7UTHMURMJKMOJSCX1H"
   },
   "erro":true,
   "text":null,
   "status":"ERROR_UNKNOWN",
   "result":null
}
```

**Comment by VictorHSL** [comment]
Same here

**Comment by alexandreclayton** [comment]
I have the same problem, my environment is

- Venom version(s): 4.0.5
- Browser: Default config
- OS: Ubuntu 18.04 (Docker)
- Node version: version 16.13.0

I'm getting the same error response (500).

*sendListMenu is working fine

**Comment by carlosbpf** [comment]
Same here. "status":"ERROR_UNKNOWN",

**Comment by tcferreira** [comment]
Same here.

**Comment by cduarte** [comment]
same here
ERROR_UNKNOWN

**Comment by sandro-salles** [comment]
+1

**Comment by GugaAraujo** [comment]
This is still a relevant problem.
Only works for WhatsApp web
