### ISSUE TITLE
Problem to retrieve session with token.

### ISSUE THREAD

**Issue by clovisdanielss** [orkestral/venom#1463]
## Description

When using **multidevice:true** and **headless:true**, I can't retrieve the session. When I restart the application, event with the generated token, the QR shows up as if no there is no connection. 

When set **headless:false** this does not happen. It works fine. But the venom must work with **headless:true**

Quando eu uso multidevice:true e headless:true eu não consigo recuperar minha sessão. Quando eu reinicio a aplicação, mesmo tento o token gerado, o QR aparece como se não houvesse token para conexão ou como se fosse inválido. 

Se eu defino headless como false, funciona tudo normalmente. Ou seja, ao reiniciar a aplicação, o token consegue resgatar a sessão. O problema é que headless false aumenta o consumo de memória, então o ideal é o venom funcionar com headless true, mesmo para multidevice

## Environment

- **Venom version(s):** 4.0.5
-

**Comment by mrksvol** [comment]
the same

**Comment by flavionc** [comment]
@clovisdanielss você conseguiu resolver isso? Estou com o mesmo problema aqui.

**Comment by dhonata** [comment]
the same

**Comment by sreza78** [comment]
same here

**Comment by sreza78** [comment]
I solved my problem with [this](https://github.com/orkestral/venom/issues/1555#issuecomment-1086007109)

**Comment by mmhospedagem** [comment]
https://github.com/orkestral/venom/issues/1626
