### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by AlexsandroZanella2** [orkestral/venom#1465]
## Description

If I try to start a session when there is a session.data.json file that points to an already logged out session, venom cannot verify that it needs to be logged in again.

## Environment

- **Venom version(s):** 4.0.4, 4.0.5
- **Browser:** Chrome latest
- **OS:** Windows 11, W 10, W 8, W 7, W server 2019, W Server 2016, W server 2008
- **Node version:** node 12, node 14, node 16

## Steps to Reproduce

1. Start a session as per the documentation by saving the session in the ./tokens/session.data.json folder
2. Stop node execution
3. disconnect from session by WhatsApp
4. restart execution via venom

## Log Output
You will get the message until timeout:
 

```
info:     [94498706000179.b] Initializing browser wss...
info:     [94498706000179.b] Browser successfully opened
info:     [94498706000179.b] checking headless...
info:     [94498706000179.b] headless option is active, browser hidden
info:     [94498706000179.b] Checking page...
info:     [94498706000179.b] Page successfully accessed
Status Session:  notLogged9.b]: Checking is logged...
Session name:  94498706000179.b
Status Session:  autocloseCalledWaiting for QRCode Scan: Attempt 1
```

**Comment by mrksvol** [comment]
the same

**Comment by mmhospedagem** [comment]
https://github.com/orkestral/venom/issues/1626

**Comment by renenucci** [comment]
> https://github.com/orkestral/venom/issues/1626

deleted...
