### ISSUE TITLE
The number does not exist [v4.0.5]

### ISSUE THREAD

**Issue by vhmvictor** [orkestral/venom#1469]
## Description

I'm having problems making a text send request. For most attempts it is returning a 404 error message. "The number does not exist". But the numbers are valid. Below is an image illustrating the error.

## Environment

- **Venom version(s):** [4.0.5]
- **Node version:** [v16.6.1]

## Steps to Reproduce

1. Send a text

## Log Output

![WhatsApp Image 2022-02-02 at 13 44 21](https://user-images.githubusercontent.com/51443108/152595536-63e06e4d-ab87-4f65-9d88-9bc43e487921.jpeg)

**Comment by fastsyrup** [comment]
same here

**Comment by AlexsandroZanella2** [comment]
It's not wrong, that number doesn't even exist!
You can use a try catch and ignore this error or check if it's a valid id before sending.
