### ISSUE TITLE
Session saving problem

### ISSUE THREAD

**Issue by kupuii209** [orkestral/venom#1476]
## Description

The session is created, but when the script is restarted, the session does not rise and asks to rescanQr

## Environment

- **Venom version(s):** [4.0.5]
- **Browser:** [default venom]
- **OS:** [linux ubuntu 20.04]
- **Node version:** [Node 12.22.5]

## Steps to Reproduce

1. [Session creation]
2. [Reboot script]

## Log Output

Session creation
```
info:     [79297401290] Initializing browser wss...
info:     [79297401290] Browser successfully opened
info:     [79297401290] checking headless...
info:     [79297401290] headless option is active, browser hidden
info:     [79297401290] Checking page...
info:     [79297401290] Page successfully accessed
- [instance: 79297401290]: Waiting page load
- [instance: 79297401290]: Checking is logged...
- [instance: 79297401290]: Waiting for QRCode Scan...
- [instance: 79297401290]: Waiting for QRCode Scan: Attempt 1
- [instance: 79297401290]: Waiting for QRCode Scan: Attempt 2
- [instance: 79297401290]: Checking QRCode status...
- [instance: 79297401290]: QRCode Success
- [instance: 79297401290]: Checking phone is connected...
- [instance: 79297401290]: Connected
```

Reboot script
```
info:     [79297401290] Initializing browser wss...
info:     [79297401290] Browser successfully opened
info:     [79297401290] checking headless...
info:     [79297401290] headless option is active, browser hidden
info:     [79297401290] Checking page...
info:     [79297401290] Page successfully accessed
- [instance: 79297401290]: Waiting page load
- [instance: 79297401290]: Checking is logged...
- [instance: 79297401290]: Waiting for QRCode Scan...
- [instance: 79297401290]: Waiting for QRCode Scan: Attempt 1
- [instance: 79297401290]: Page Closed
- [instance: 79297401290]: Checking QRCode status...
- [instance: 79297401290]: Failed to authenticate
- [instance: 79297401290]: Unknow error
```
```
If relevant, paste all of your Log Output
```

## Your Code

```javascript
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: false // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by mrksvol** [comment]
the same!

**Comment by sharadregoti** [comment]
I am also having the same problem

**Comment by jrCleber** [comment]
you can save the session token manually.  See here in this script!  The comments are in Portuguese, but you can translate the page.  OK!?

https://github.com/jrCleber/bot-venom-firebase/blob/main/app/bot.ts

**Comment by mrksvol** [comment]
> 

Wow, thanks!

**Comment by mrksvol** [comment]
> you can save the session token manually. See here in this script! The comments are in Portuguese, but you can translate the page. OK!?
> 
> https://github.com/jrCleber/bot-venom-firebase/blob/main/app/bot.ts
> 
> Project developers rarely help us.

I tried this, but it works only for non-beta sessions?

**Comment by mrksvol** [comment]
@jrCleber 
I'm understand it, but when I set true on multidevice in your code it doesn't work. Session don't save anyway

**Comment by jrCleber** [comment]
@mrksvol 
The create function creates a folder called tokens, or searches for it.
If this post is not being created by the function, create it manually.
Maybe this will work.

**Comment by mrksvol** [comment]
@jrCleber 

The problem is that everything is created. But after restarting the script, venom sees the session as logged out.
But I noticed something, if you create a session, hold it online for 3 minutes, then it will be saved.

**Comment by manuelfidalgo** [comment]
> you can save the session token manually. See here in this script! The comments are in Portuguese, but you can translate the page. OK!?
> 
> https://github.com/jrCleber/bot-venom-firebase/blob/main/app/bot.ts
> 
> Project developers rarely help us.

That fixed the issue for me!
Thanks a lot!

**Comment by r3r** [comment]
For multi device beta, the following config created the tokens for me automatically:

```
const client = await create({
        session: 'wa-session', //name of session
        multidevice: true, // for version not multidevice use false.(default: true)
        folderNameToken: 'tokens', //folder name when saving tokens
        mkdirFolderToken: './data/app', //folder name when saving tokens
        createPathFileToken: true})
```

Setting `folderNameToken`, `mkdirFolderToken` and `createPathFileToken` were the magic config that created a large session specific token folder that was reused when restarting the server.

For non multi device, you have to save it manually using `client.getSessionTokenBrowser()` and then read it back and pass it as an option to `create` as `browserSessionToken`.

The following works for both multi device and non:

```
import { create, Whatsapp } from 'venom-bot';
import fs from 'fs';

const TOKEN_DIR = "./data/app/tokens";
const TOKEN_PATH: string = TOKEN_DIR + "/wa-session.data.json";

export default async function createWhatsappClient(): Promise<Whatsapp> {
    var browserSessionToken: any = null;
    if (fs.existsSync(TOKEN_PATH)) {
        const savedTokenString: string = fs.readFileSync(TOKEN_PATH).toString();
        browserSessionToken = JSON.parse(savedTokenString);
    }
    const client = await create({
        session: 'wa-session', //name of session
        multidevice: true, // for version not multidevice use false.(default: true)
        folderNameToken: 'tokens', //folder name when saving tokens
        mkdirFolderToken: './data/app', //folder name when saving tokens
        createPathFileToken: true,
        disableWelcome: true,
        disableSpins: true,
        headless: true,
        browserSessionToken: browserSessionToken,
    });
    const token: any = await client.getSessionTokenBrowser();
    await fs.promises.mkdir(TOKEN_DIR, { recursive: true });
    await fs.promises.writeFile(TOKEN_PATH, JSON.stringify(token));
    return client;
}

```

**Comment by hiral2cool** [comment]
> For multi device beta, the following config created the tokens for me automatically:
> 
> ```
> const client = await create({
>         session: 'wa-session', //name of session
>         multidevice: true, // for version not multidevice use false.(default: true)
>         folderNameToken: 'tokens', //folder name when saving tokens
>         mkdirFolderToken: './data/app', //folder name when saving tokens
>         createPathFileToken: true})
> ```
> 
> Setting `folderNameToken`, `mkdirFolderToken` and `createPathFileToken` were the magic config that created a large session specific token folder that was reused when restarting the server.
> 
> For non multi device, you have to save it manually using `client.getSessionTokenBrowser()` and then read it back and pass it as an option to `create` as `browserSessionToken`.
> 
> The following works for both multi device and non:
> 
> ```
> import { create, Whatsapp } from 'venom-bot';
> import fs from 'fs';
> 
> const TOKEN_DIR = "./data/app/tokens";
> const TOKEN_PATH: string = TOKEN_DIR + "/wa-session.data.json";
> 
> export default async function createWhatsappClient(): Promise<Whatsapp> {
>     var browserSessionToken: any = null;
>     if (fs.existsSync(TOKEN_PATH)) {
>         const savedTokenString: string = fs.readFileSync(TOKEN_PATH).toString();
>         browserSessionToken = JSON.parse(savedTokenString);
>     }
>     const client = await create({
>         session: 'wa-session', //name of session
>         multidevice: true, // for version not multidevice use false.(default: true)
>         folderNameToken: 'tokens', //folder name when saving tokens
>         mkdirFolderToken: './data/app', //folder name when saving tokens
>         createPathFileToken: true,
>         disableWelcome: true,
>         disableSpins: true,
>         headless: true,
>         browserSessionToken: browserSessionToken,
>     });
>     const token: any = await client.getSessionTokenBrowser();
>     await fs.promises.mkdir(TOKEN_DIR, { recursive: true });
>     await fs.promises.writeFile(TOKEN_PATH, JSON.stringify(token));
>     return client;
> }
> ```


multidevice: true, // for version not multidevice use false.(default: true)
folderNameToken: 'tokens', //folder name when saving tokens
mkdirFolderToken: './data/app', //folder name when saving tokens
createPathFileToken: true

this is perfectly working fine. 
Thanks a lot @r3r

**Comment by HENRDS** [comment]
Adding the lines below didn't work for me
```
{
    ...,
    multidevice: true, // for version not multidevice use false.(default: true)
    folderNameToken: 'tokens', //folder name when saving tokens
    mkdirFolderToken: './data/app', //folder name when saving tokens
    createPathFileToken: true
}
```
I'm running with multidevice. Saving the token manually didn't work as well.

**Comment by mikelustosa** [comment]
Não funciona mais dessa forma?

{
      WABrowserId: '"UnXjH....."',
      WASecretBundle:
        '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
      WAToken1: '"0i8...."',
      WAToken2: '"1@lPpzwC...."'
    },

**Comment by vishwajit76** [comment]
> For multi device beta, the following config created the tokens for me automatically:
> 
> ```
> const client = await create({
>         session: 'wa-session', //name of session
>         multidevice: true, // for version not multidevice use false.(default: true)
>         folderNameToken: 'tokens', //folder name when saving tokens
>         mkdirFolderToken: './data/app', //folder name when saving tokens
>         createPathFileToken: true})
> ```
> 
> Setting `folderNameToken`, `mkdirFolderToken` and `createPathFileToken` were the magic config that created a large session specific token folder that was reused when restarting the server.
> 
> For non multi device, you have to save it manually using `client.getSessionTokenBrowser()` and then read it back and pass it as an option to `create` as `browserSessionToken`.
> 
> The following works for both multi device and non:
> 
> ```
> import { create, Whatsapp } from 'venom-bot';
> import fs from 'fs';
> 
> const TOKEN_DIR = "./data/app/tokens";
> const TOKEN_PATH: string = TOKEN_DIR + "/wa-session.data.json";
> 
> export default async function createWhatsappClient(): Promise<Whatsapp> {
>     var browserSessionToken: any = null;
>     if (fs.existsSync(TOKEN_PATH)) {
>         const savedTokenString: string = fs.readFileSync(TOKEN_PATH).toString();
>         browserSessionToken = JSON.parse(savedTokenString);
>     }
>     const client = await create({
>         session: 'wa-session', //name of session
>         multidevice: true, // for version not multidevice use false.(default: true)
>         folderNameToken: 'tokens', //folder name when saving tokens
>         mkdirFolderToken: './data/app', //folder name when saving tokens
>         createPathFileToken: true,
>         disableWelcome: true,
>         disableSpins: true,
>         headless: true,
>         browserSessionToken: browserSessionToken,
>     });
>     const token: any = await client.getSessionTokenBrowser();
>     await fs.promises.mkdir(TOKEN_DIR, { recursive: true });
>     await fs.promises.writeFile(TOKEN_PATH, JSON.stringify(token));
>     return client;
> }
> ```

Its working, but
Session status showed isLogged
Stuck at Checking phone is connected

- [instance: 623841d6bc2a1e1f70688ebb]: Page Closed
- [instance: 623841d6bc2a1e1f70688ebb]: Phone not connected

**Comment by jonalan7** [comment]
**This feature will be removed soon! Because it doesn't work multi-device**

**Comment by Dima564** [comment]
@jonalan7 I am trying to package my session in a docker image, and my account is forced to be multi-device. 
What can I do to accomplish this?

**Comment by luiscuriel** [comment]
So... does multi device support session restoring???

**Comment by luiscuriel** [comment]
So... does multi device support session restoring???

**Comment by Ionasjospo** [comment]
After tried many forms to persist the session, it works with 
multiDevice: true,
headless: 'new'

You should no longer use boolean false or true, now use false, true or 'new' learn more https://developer.chrome.com/articles/new-headless/
