### ISSUE TITLE
Client functions aren't working anymore

### ISSUE THREAD

**Issue by OmarMYousef** [orkestral/venom#1478]
## Description

On the multi-device update for whatsapp, the client functions aren't working for some reason
It just don't work, without errors or freezing, much like a promise that never be resolved

## Environment

- **Venom version(s):** [4.0.5]
- **Browser:** [Chromium 85]
- **OS:** [Windows 10]
- **Node version:** [v14.16.1]

## Log Output

nothing suspicious, just normal log output

**Comment by h4775346** [comment]
Yeah Same here, its just **freezing** and make no action

**Comment by yalzeee** [comment]
Same here.. listeners like "onMessage" working but the functions like "sendText" aren't

**Comment by mrizkypk** [comment]
Same here

**Comment by jonalan7** [comment]
what functions are not working?

**Comment by mrizkypk** [comment]
I think this is related to #1476

**Comment by OmarMYousef** [comment]
> what functions are not working?

I've tried client.send, client.getHostDevice and client.checkNumberStatus, and none of them worked

I believe more functions probably aren't working too

**Comment by jonalan7** [comment]
> > quais funções não estão funcionando?
> 
> Eu tentei client.send, client.getHostDevice e client.checkNumberStatus, e nenhum deles funcionou
> 
> Eu que provavelmente mais não estão funcionando também

if it's not working it must be a module loading problem!

**Comment by yalzeee** [comment]
So any suggestions on how to fix it @jonalan7

**Comment by iamfelipy** [comment]
So any suggestions on how to fix it @jonalan7
