### ISSUE TITLE
Venom bot stopped sending session statuses when I disconnect my device

### ISSUE THREAD

**Issue by rafosolima** [orkestral/venom#1483]
## Description

Venom bot stopped sending session statuses when I disconnect my device.

Venom bot parou de enviar os status de session, quando desconecto meu aparelho

## Environment

- **Venom version(s):** [4.0.5]
- **Browser:** [96.0.4664.45]
- **OS:** [Windows 11 + WSL2] 
- **Node version:** [v14.18.0]

## Steps to Reproduce
1. start venom, it issues the login / qrcode statuses
2. When I disconnect my device it does not fire the event

1.  Inicializo o venom, ele emit os status de login / qrcode
2. Quando desconecto meu device ele não dispara o evento

**Comment by felipelyp** [comment]
### Eu fiz essa solução temporária, que também seja o problema real

**Antes:**
![image](https://user-images.githubusercontent.com/28626603/154167717-cb104b93-2def-4dd3-a1a9-9e10c6c3d4a3.png)

Eu apenas alterei para **./tokens/** e resolveu

**Como ficou:** 
![image](https://user-images.githubusercontent.com/28626603/154167541-6a92423e-9493-464c-8228-2d7e3fbc08a0.png)

**Comment by rafosolima** [comment]
@felipelyp isso no build do projeto?
