### ISSUE TITLE
Problem not finding session folder

### ISSUE THREAD

**Issue by felipelyp** [orkestral/venom#1486]
### Bot can't access session folder because of that line which doesn't have ./tokens/ concatenated to project folder

https://github.com/orkestral/venom/blob/e5263e217b055137f1b4e115865c9ae3f33a47f8/src/controllers/initializer.ts#L355

![image](https://user-images.githubusercontent.com/28626603/154168220-4c3dd6c6-0466-4680-9059-fcb782b45fc8.png)

**Comment by marciodiasdeveloper** [comment]
+1

**Comment by Porkts** [comment]
I'm too
