### ISSUE TITLE
Not sending messages while no errors

### ISSUE THREAD

**Issue by elasti-co** [orkestral/venom#1487]
## Description

client.sendText(phone, message) not responding neither with then() nor with catch()

## Environment

- **Venom version(s):** 4.0.5
- **Browser:** default Chrome
- **OS:** MacOS (latest) and Ubuntu
- **Node version:** 17.5

## Steps to Reproduce

1. Create Client with multi-device option
2. Authorization works fine
3. Try to sendText
4. Get no response (success or error)

## Log Output

```
No log output after sending this command.
```

## Your Code

```
client.sendText(phone, message)
  .then((result) => {
      console.log(session, result)
      sendWebhook(sessionName, 'message', true)
  })
  .catch((error) => {
      console.log(error)
  })
```

**Comment by AntVentura** [comment]
Presenting the same issue

**Comment by AntVentura** [comment]
I'm having the same issue. client.onMessage recieve the message, but the client.sendText doesn't respond

**Comment by elasti-co** [comment]
I've spent the whole day mixing parameters from Venom and WppCconnect. The thing was that Venom authenticates well but not sending messages, and Wpp vice versa.

I am using multi-device beta. At last found a temporary workaround:
Wpp with `whatsappVersion: '2.2204.13'` @ `wpp.create()`.

Hope it will help you. Waiting for new release of Venom.

**Comment by yalzeee** [comment]
Could you explain a bit better… Where am I calling wpp.create(), where am I adding the new WhatsApp version?

**Comment by elasti-co** [comment]
@yalzeee I am talking about wppconnect (it’s almost the same as Venom). I just temporarily replaced venom with wppconnect.
To create the instance of wppconnect I followed the docs:
`
wpp.create({
    session: ‘my-session’,
    puppeteerOptions: { userDataDir: './tokens/' + session.name, },
    whatsappVersion: '2.2204.13',
    // and all other options that you may already use in venom
})`

**Comment by yalzeee** [comment]
@elasti-co Thank you so much. It is working with your fix.

**Comment by r3r** [comment]
I'm also seeing this problem. I'm not able to include whatsappVersion: '2.2204.13' on venom, but have to use wppclient which for some reason is much slower than venom.

@orkestral would it be possible to fix the issue in venom itself?

**Comment by renandecarlo** [comment]
Any fix?

**Comment by r3r** [comment]
@jonalan7 is this issue fixed?
Sorry, unsure why this is closed. 
Thank you for your help!
