### ISSUE TITLE
Ciphertext

### ISSUE THREAD

**Issue by OrhanArslan** [orkestral/venom#149]
'ciphertext' messages do not include the body even it's simple text message. Can you fix this please?

**Comment by joaosouz4** [comment]
i dont know whats u want and whats is ciphertext?

**Comment by OrhanArslan** [comment]
Some messages do not have any text content. But actually message is 'Hi' etc. When I check these messages' object, their type is ciphertext.

**Comment by ferbsferbs** [comment]
i have the same problem. 
ciphertext is the "type" of message obj recived
