### ISSUE TITLE
how to send a message in another module separate?

### ISSUE THREAD

**Issue by matheusm821** [orkestral/venom#150]
How do I create a function that sends a message? and export?

**Comment by matheusm821** [comment]
with the bot already created

**Comment by bourdog** [comment]
você passa por parametro o client dentro da função = function start(client) { ... } através de qualquer outra função.
ai é usar o client.sendText(message.from, 'teste') na função que você passou o client por parametro
abraço

**Comment by matheusm821** [comment]
so i would like to make a function and export it example:

function send(client,number,msg){
        client.sendText(number, msg).then(()=>console.log('Sucess'))
    
}

exports.send= send
-------------------------------------------------------
use em index.js

const send= require('./sendM')

send.send(number,msg)

Do you know how ?

**Comment by apriady** [comment]
your objective is to send the message from another module, right?

maybe you can try with event emitter or pubsub.
