### ISSUE TITLE
SendButtons

### ISSUE THREAD

**Issue by gabrielfelipecsk** [orkestral/venom#1514]
## Description

SendButtons não funciona sem multiservices false

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Log Output

Executing (default): INSERT INTO `wp_numbers` (`id`,`number`) VALUES (NULL, '***************')
Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '*************',
      _serialized: '*************'
    },
    id: '**************',
    _serialized: '*************'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}
```
Pode ser facilmente replicado, só seguindo a descrição do problema
```

**Comment by SrManinka** [comment]
Pelo que vi em outros, a causa pode ser o do multi devices ainda fato de ainda ser um beta

**Comment by alitons** [comment]
Fiz alguns testes em uma api oficial. Percebi que alguns parametros foram adicionados. Mas até agora não consegui fazer voltar a funcionar.

Acredito que seja algo referente a esse parametro:

"replyButtons": [
      {
        "id": "btn01",
        "displayText": "Button 01"
      },
      {
        "id": "btn02",
        "displayText": "Button 02"
      }
    ],

Mas não tenho certeza onde ele deve ser adicionado. Já fiz alguns testes adicionando ele no wapi.js, mas não obtive sucesso.

**Comment by ferbsferbs** [comment]
> > Estou estudando tambem a api e o codigo pra ver se faço funcionar, vc teme novidades?
> 
> Se tiverem alguma novidade quanto a utilização dos botões, me marca aqui, pf

Eu gastei várias horas e não cheguei a nada concreto.
Eu tinha a pressa de ter a solução rápidamente porque o sistema estava em stage e tinha gente testando, então saí da versão Beta e funcionou... O issue é com a versão Beta de multiplos dispositivos offline. só atualizei o whatsapp e desativei essa função.

Se quiser eu te passo meu zap pra gente manter contato ou tentar resolver junto . Abraço

**Comment by jonalan7** [comment]
> Fiz alguns testes em uma api oficial. Percebi que alguns parametros foram adicionados. Mas até agora não consegui fazer voltar a funcionar.
> 
> Acredito que seja algo referente a esse parametro:
> 
> "replyButtons": [ { "id": "btn01", "displayText": "Button 01" }, { "id": "btn02", "displayText": "Button 02" } ],
> 
> Mas não tenho certeza onde ele deve ser adicionado. Já fiz alguns testes adicionando ele no wapi.js, mas não obtive sucesso.

what were the parameters?

**Comment by alitons** [comment]
> > Fiz alguns testes em uma api oficial. Percebi que alguns parametros foram adicionados. Mas até agora não consegui fazer voltar a funcionar.
> > Acredito que seja algo referente a esse parametro:
> > "replyButtons": [ { "id": "btn01", "displayText": "Button 01" }, { "id": "btn02", "displayText": "Button 02" } ],
> > Mas não tenho certeza onde ele deve ser adicionado. Já fiz alguns testes adicionando ele no wapi.js, mas não obtive sucesso.
> 
> what were the parameters?

These parameters are returned when sending an official api

"id": "false_556899999999@c.us_C29E454C82861EEDB9",
    "body": "Do you like this t shirt?",
    "type": "chat",
    "t": 1646075467,
    "notifyName": "556899999999",
    "from": "556899999999@c.us",
    "to": "556899999990@c.us",
    "self": "in",
    "ack": 1,
    "isNewMsg": true,
    "star": false,
    "recvFresh": true,
    "caption": "Do you like this t shirt?",
    "isFromTemplate": false,
    "broadcast": false,
    "mentionedJidList": [],
    "footer": "We have this one in other colors.",
    "isVcardOverMmsDocument": false,
    "isForwarded": false,
    "labels": [],
    "hasReaction": false,
    "ephemeralOutOfSync": false,
    "privacyModeWhenSent": {
      "actualActors": 2,
      "hostStorage": 1,
      "privacyModeTs": 1646071636
    },
    "productHeaderImageRejected": false,
    "lastPlaybackProgress": 0,
    "isDynamicReplyButtonsMsg": true,
    "dynamicReplyButtons": [
      {
        "buttonId": "yes-unique-id",
        "buttonText": {
          "displayText": "Sim"
        },
        "type": 1
      },
      {
        "buttonId": "no-unique-id",
        "buttonText": {
          "displayText": "Não"
        },
        "type": 1
      }
    ],
    "replyButtons": [
      {
        "id": "yes-unique-id",
        "displayText": "Sim"
      },
      {
        "id": "no-unique-id",
        "displayText": "Não"
      }
    ],
    "headerType": 1,
    "isMdHistoryMsg": false,
    "requiresDirectConnection": false,
    "pttForwardedFeaturesEnabled": false,
    "chatId": "556899999999@c.us",
    "fromMe": false,
    "sender": {
      "id": "556899999999@c.us",
      "name": "Mr Delivery",
      "shortName": "Mr Delivery",
      "pushname": "556899999999",
      "type": "in",
      "verifiedName": "Imaginart",
      "isBusiness": true,
      "isEnterprise": true,
      "verifiedLevel": 0,
      "privacyMode": {
        "actualActors": 2,
        "hostStorage": 1,
        "privacyModeTs": 1646071636
      },
      "labels": [],
      "isContactSyncCompleted": 1,
      "formattedName": "Mr Delivery",
      "displayName": "Mr Delivery",
      "formattedShortName": "Mr Delivery",
      "formattedShortNameWithNonBreakingSpaces": "Mr Delivery",
      "isMe": false,
      "mentionName": "Mr Delivery",
      "notifyName": "Imaginart",
      "isMyContact": true,
      "isPSA": false,
      "isUser": true,
      "isWAContact": true,
      "profilePicThumbObj": {
        "eurl": null,
        "id": "556899999999@c.us",
        "raw": null,
        "tag": null
      },
      "msgs": null
    },
    "timestamp": 1646075467,
    "content": "Do you like this t shirt?",
    "isGroupMsg": false,
    "isMedia": false,
    "isNotification": false,
    "isPSA": false,
    "chat": {
      "id": "556899999999@c.us",
      "labels": [],
      "lastReceivedKey": {
        "fromMe": false,
        "remote": "556899999999@c.us",
        "id": "C29E454C82861EEDB9",
        "_serialized": "false_556899999999@c.us_C29E454C82861EEDB9"
      },
      "t": 1646075467,
      "unreadCount": 1,
      "muteExpiration": 0,
      "notSpam": true,
      "unreadMentionsOfMe": [],
      "unreadMentionCount": 0,
      "hasUnreadMention": false,
      "archiveAtMentionViewedInDrawer": false,
      "hasChatBeenOpened": false,
      "pendingInitialLoading": false,
      "msgs": null,
      "kind": "chat",
      "isGroup": false,
      "contact": {
        "id": "556899999999@c.us",
        "name": "Mr Delivery",
        "shortName": "Mr Delivery",
        "pushname": "556899999999",
        "type": "in",
        "verifiedName": "Imaginart",
        "isBusiness": true,
        "isEnterprise": true,
        "verifiedLevel": 0,
        "privacyMode": {
          "actualActors": 2,
          "hostStorage": 1,
          "privacyModeTs": 1646071636
        },
        "labels": [],
        "isContactSyncCompleted": 1,
        "formattedName": "Mr Delivery",
        "displayName": "Mr Delivery",
        "formattedShortName": "Mr Delivery",
        "formattedShortNameWithNonBreakingSpaces": "Mr Delivery",
        "isMe": false,
        "mentionName": "Mr Delivery",
        "notifyName": "Imaginart",
        "isMyContact": true,
        "isPSA": false,
        "isUser": true,
        "isWAContact": true,
        "profilePicThumbObj": {
          "eurl": null,
          "id": "556899999999@c.us",
          "raw": null,
          "tag": null
        },
        "msgs": null
      },
      "groupMetadata": null,
      "presence": {
        "id": "556899999999@c.us",
        "chatstates": []
      },
      "isOnline": null,
      "lastSeen": null
    },
    "isOnline": null,
    "lastSeen": null,
    "mediaData": {},
    "linkPreview": false,
    "text": "Do you like this t shirt?",
    "initialPageSize": 768

**Comment by ferbsferbs** [comment]
that is valuable info. Thanks

I'll try to put that together with source files from this library and
multiple devices.
As soon as i get some progress i'll share it here

**Comment by guimaraesdiego** [comment]
> Fiz alguns testes em uma api oficial. Percebi que alguns parametros foram adicionados. Mas até agora não consegui fazer voltar a funcionar.
> 
> Acredito que seja algo referente a esse parametro:
> 
> "replyButtons": [ { "id": "btn01", "displayText": "Button 01" }, { "id": "btn02", "displayText": "Button 02" } ],
> 
> Mas não tenho certeza onde ele deve ser adicionado. Já fiz alguns testes adicionando ele no wapi.js, mas não obtive sucesso.

cara meu ate com o multidevice desabilitado nao funciona.. qual versao vc ta?

**Comment by alitons** [comment]
> > Fiz alguns testes em uma api oficial. Percebi que alguns parametros foram adicionados. Mas até agora não consegui fazer voltar a funcionar.
> > Acredito que seja algo referente a esse parametro:
> > "replyButtons": [ { "id": "btn01", "displayText": "Button 01" }, { "id": "btn02", "displayText": "Button 02" } ],
> > Mas não tenho certeza onde ele deve ser adicionado. Já fiz alguns testes adicionando ele no wapi.js, mas não obtive sucesso.
> 
> cara meu ate com o multidevice desabilitado nao funciona.. qual versao vc ta?

Acho que não tem nada a ver com a versão do venom, e sim com a versão do whtasapp... Eu usava uma versão do whatsapp desatualizado, e estava funcionando normalmente, mesmo varias pessoas já falando que não estava funcionando. Sem querer cliquei em atualizar e parou de funcionar.

**Comment by lothusinfo** [comment]
Alguém conseguiu achar uma solução para o envio dos botões?

**Comment by jonalan7** [comment]
Ainda não foi encontrado a solução! [lothusinfo](https://github.com/lothusinfo)

**Comment by irhammusthofa** [comment]
![image](https://user-images.githubusercontent.com/22863461/159383687-7d111766-f9ed-43d3-997f-a5f0b1925ec6.png)
how to make a button action like this? tanks

**Comment by gabrielfelipecsk** [comment]
> tor

Sem novidades ainda também.

**Comment by cduarte** [comment]
buttons dont work here

  status: 'ERROR_UNKNOWN',


envio de botões retorna erro aqui ainda...
sem solução.
Alguem conseguiu?

**Comment by fernandopraise** [comment]
pra mim também dá erros... alguém teve sucesso?

**Comment by mmhospedagem** [comment]
https://github.com/orkestral/venom/issues/1626

**Comment by MazanLabeeb** [comment]
giving me the same error, any solution yet? 😥😥

**Comment by jailtonsdn** [comment]
Cara deu super certo muito obrigado! 
![image](https://user-images.githubusercontent.com/108580162/219129515-fb08674c-bf1b-467c-9039-e9beeb93e5a0.png)

**Comment by scatrus** [comment]
o meu funcionou uns dias, mas agora só funciona no whatsapp web...pelo celular não aparece o elemento dos botões..

**Comment by junimheller** [comment]
aparentemente os botões para o wpp de android estão atrasados

**Comment by GugaAraujo** [comment]
This is still a relevant problem.
Only works for WhatsApp web
