### ISSUE TITLE
Lost reference to Store.STATE

### ISSUE THREAD

**Issue by lukasportal** [orkestral/venom#1518]
## Description
WhatsApp just released an update and now we no longer have a reference to Store.STATE
using the latest version of venom

**Comment by henrickJona** [comment]
same, why did u guys release a version like this

**Comment by lukasportal** [comment]
from what I can see, it was WhatsApp that changed, not Venom

**Comment by henrickJona** [comment]
the last but one version has the same problem, when disconnecting a phone from whatsapp, qr-code is not being sent after that

**Comment by jeferssonlemes** [comment]
same here in version 2.2206.5 WhatsappWeb

**Comment by MarcosDLR** [comment]
Solution:

Change

if (typeof webpackJsonp === 'function') webpackJsonp([], {[parasite]: (x, y, z) => getStore(z)}, [parasite]);
// else webpackChunkbuild.push([[parasite], {}, function (o, e, t) {let modules = []; for (let idx in o.m) {modules.push(o(idx));} getStore(modules);}]);
else webpackChunkwhatsapp_web_client.push([[parasite], {}, function (o, e, t) {let modules = []; for (let idx in o.m) {modules.push(o(idx));} getStore(modules);}]);

And change to this version of ws 

2.2204.13

**Comment by lukasportal** [comment]
didnt work, Store.State is still undefined

**Comment by jonalan7** [comment]
> same, why did u guys release a version like this

Bro instead of criticizing, why not help? The library is free!

**Comment by jeferssonlemes** [comment]
Vi que mudou algumas coisas na ultima, pra mim dessa forma funcionou bem...

{
        id: 'State2',
        conditions: (module) => (module.Stream && module.Obscurity ? module.Stream : null)
}

// uso
Store.State2.info

**Comment by jonalan7** [comment]
@jeferssonlemes I'm not getting this error! I still haven't received this update!

**Comment by lukasportal** [comment]
> @jonalan7 não sei se essa é a melhor forma de fazer... Vi que mudou algumas coisas na ultima, pra mim dessa forma funcionou bem...
> 
> { id: 'State2', conditions: (module) => (module.Stream && module.Obscurity ? module.Stream : null) }
> 
> // uso Store.State2.info

this works! state names have changed, do you know the possible values for State2.info?

**Comment by jrrcdev** [comment]
Update:

`{
		id: "State",
		conditions: module =>
			module.Socket && module.Socket.takeover ? module : null
	}`

**Comment by lukasportal** [comment]
all working, tahanks guys!
