### ISSUE TITLE
Venom doesn't send messages (gadd called without an id attr (id))

### ISSUE THREAD

**Issue by NowDev** [orkestral/venom#1519]
## Description

When i try to send a text message (to unkown or a contact) it fails.

## Environment

- **Venom version(s):** 4.0.6
- **Browser:** Chrome Version 98.0.4758.102
- **OS:** Windows 10 x64
- **Node version:** Node v16.13.2

## Steps to Reproduce

1. Enable multi-device
2. Send a message to a number (like 55999123456@c.us)
3. It will crash.

## Log Output

```
Error: Evaluation failed: Error: gadd called without an id attr (id)
    at W.gadd (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:65:420665)
    at https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:65:249166
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:64054
    at Y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:243670)
    at new y (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:5:236237)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.947b18aebaee33ade8af.js:2:63935
    at W._findAndParse (https://web.whatsapp.com/bootstrap_qr.faeb72dc2a3a441a20d1.js:65:249899)
    at ExecutionContext._evaluateInternal
```

**Comment by icaro-tavares** [comment]
I have the same problem

**Comment by doctorsanches** [comment]
same

**Comment by edgaru** [comment]
same

**Comment by marcelo-maciel** [comment]
same

**Comment by canerd7u** [comment]
same

**Comment by jamesxt94** [comment]
Same problem, without multidevice.

**Comment by taigfs** [comment]
same here

**Comment by luizlago** [comment]
same, with/without multidevice

**Comment by razinj** [comment]
Facing same problem here!

**Comment by gbrvalerio** [comment]
+1

**Comment by bielgvs** [comment]
For me, it seems that updating whatsapp-web to version 2.2206.5 with venom running broke it, after that update "sendtext" started to send only one message and then crash. I had to completely remove my application and install it again, then Chromium was already running the new version of whatsapp-web, and everything start it to work normally.

In further tests I was able to make "sendtext" stop crash, cleaning my app's APPDATA folder.

I have no idea if this has something to do with your problems, but maybe it will help someone or even help to address the issue.

**Comment by jesusvalverde** [comment]
same here

**Comment by renandecarlo** [comment]
Same here

**Comment by leandrobrunoo** [comment]
Same here

**Comment by michaelloliveira** [comment]
same here

**Comment by michaelloliveira** [comment]
Gentlemen, I took a test and it seems that messages can only be sent to contacts who are in your conversation list.

In other words, it is necessary for the recipient to contact you first by sending a message.

try:


 let  chats = await client.getAllChats();
 if(chats.findIndex(c => c.id._serialized === message.from) > -1) {
//send message
}

**Comment by razinj** [comment]
I can confirm what @michaelloliveira has said, I no longer see the error when I started the conversation.

**Comment by hafidzaini** [comment]
any sollution?
may be something change on whatsapp web Version 2.2206.5

**Comment by r3r** [comment]
Facing the same problem: If it helps, there's a similar solution called wppconnect that has the same interfaces/API as venom and could perhaps work for you: https://www.npmjs.com/package/@wppconnect-team/wppconnect

**Comment by matheusb-comp** [comment]
Maybe this should be reopened.
Using WAPI directly, on WhatsApp legacy (without multi-device), the function `sendExist` fails with this error.
![Screenshot from 2022-03-08 20-29-52](https://user-images.githubusercontent.com/1227961/157343360-c7763f79-4f60-4576-9dc1-e16a4778332c.png)

Checking the calls, `sendExist` [calls `checkNumberStatus`](https://github.com/orkestral/venom/blob/0a204796998d547da7a3395dcf1985a05edf0935/src/lib/wapi/functions/check-send-exist.js#L155) that in turn is [calling `WAPI.isBeta` without `await`](https://github.com/orkestral/venom/blob/f5ce8e6be69827453a94187b2e58212d387ce9ca/src/lib/wapi/functions/check-number-status.js#L31).

**Comment by jamesxt94** [comment]
Same error again with multidevice, in ```checkNumberStatus```
Generates an unhandled exception and kill the app.

```bash 
/node_modules/.pnpm/puppeteer@13.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: Error: gadd called without an id attr (id)
    at W.gadd (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:455434)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:277773
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at j (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:259320)
    at new y (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:251887)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63094
    at W._findAndParse (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:278506)
    at ExecutionContext._evaluateInternal (/root/.kawi/pnpm-packages/74d2e9396fc759ebd8f80ddd82f2bb83/node_modules/.pnpm/puppeteer@13.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/.kawi/pnpm-packages/74d2e9396fc759ebd8f80ddd82f2bb83/node_modules/.pnpm/puppeteer@13.4.0/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

**Comment by AlexsandroZanella2** [comment]
same

**Comment by renandecarlo** [comment]
I'm having this issue also in the lastest version, 4.0.7

**Comment by luccafabro** [comment]
I still getting the same error, any solution using venom ?

**Comment by paraisotech** [comment]
Same issue here. Using CentOS 8 Stream... 
**SOLUTION**: Reinstall/Update Venom libs with **npm i --save venom-bot** command with elevated privileges(root user ou sudo)
Worked here for me.
I'm using multidevice, btw.
