### ISSUE TITLE
SendImageAsSticker problem

### ISSUE THREAD

**Issue by brainwares** [orkestral/venom#152]
I'm having error message when sending jpg sticker.
`
(node:6660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
....
`
Any help?

**Comment by jonalan7** [comment]
**Problem resolved in the current update.**
