### ISSUE TITLE
checkNumberStatus not working, is return reject to all request.

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#1524]
`  eNumeroWhatsapp(client: venom.Whatsapp, numero: string): Promise<boolean> {
    return new Promise(async (resolve, reject) => {
      try {
        let statusAt = await client.checkNumberStatus(`${numero}@c.us`)
        if (statusAt.status == 200) {
          return resolve(statusAt.numberExists)
        } else resolve(false)
      } catch (error: any) {
        if (error.status == 404) return resolve(false)
        if (typeof error == 'object')
          reject(JSON.stringify(error))
        else reject(error)
      }
    })
  }
  pr`

**Comment by thelordapofis** [comment]
This method returns <{}> as rejection for all executions.

**Comment by hafidzaini** [comment]
using last version still having {} return 🤔

**Comment by beetechbr** [comment]
same here

**Comment by AlexsandroZanella2** [comment]
try with this version: [nightly release 4.0.7.Alpha.0](https://github.com/orkestral/venom/tree/nightly)
