### ISSUE TITLE
client.downloadMedia() return undefined

### ISSUE THREAD

**Issue by zinct** [orkestral/venom#1525]
## Description

What's wrong with my script? can someone help?

## Environment

- **Venom version(s):** ^4.0.6
- **Browser: Chrome/95
- **OS: Mint 20.2 Cinamon
- **Node version: Node v14.18.2

## Steps to Reproduce

1. Sending the image to the bot
2. try to run client.downloadMedia(message.id)

## Log Output
    This catch block gets executed. but no error message showed {}
    media undefined

## Your Code

```
   client.onMessage(async (message) => {
       const media = await client.downloadMedia(message.id).catch((err) => console.log("This catch block get execute. but no error message 
       showed ", err));
      console.log("media", media);
   });
   
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by AlexsandroZanella2** [comment]
Try using the decryptFile function

**Comment by zinct** [comment]
> Try using the decryptFile function

thanks! it worked.
