### ISSUE TITLE
Pacote incompatível [sharp 0.30.1]

### ISSUE THREAD

**Issue by zaidnei** [orkestral/venom#1536]
## Description

Olá, possuo um projeto utilizando electron + venom bot...

Quando atualizei a biblioteca venom, o sharp atualizou para a versão 0.30.1, desde então não consigo mais executar, pois o seguinte erro é disparado:

(Something went wrong installing the "sharp" module)

## Environment

- **Venom version(s):** [4.0.6]
- **Browser:** [Chrome 98, Chromium 97]
- **OS:** [Windows 10]
- **Node version:** [Node 14]

Para reproduzir este erro, basta fazer o get started do electron + venom

Abaixo está o meu código, obrigado desde já....

![indexhtml](https://user-images.githubusercontent.com/29881843/156372543-683fcb2b-fa23-4634-b538-b76e39e1e53d.png)
![indexjs](https://user-images.githubusercontent.com/29881843/156372554-4f9a2d18-500b-4c6d-a59f-e93759a1b526.png)
![package](https://user-images.githubusercontent.com/29881843/156372555-19ac28b9-6059-4e22-a252-9ae096e52b62.png)

**Comment by bielgvs** [comment]
Hello, I can confirm that some of our clients were having this same problem. It works fine with most of the versions of W10 and W7, not sure exactly what triggers this problem, it seems to be something related with x86 versions.

`npm install sharp@0.30.2`

Will likely solve the problem, VENOM should add this to the project too.

This is a problem with the SHARP version, not exactly with VENOM.

**Comment by zaidnei** [comment]
Ok, thank you for your answer, I tested with the sharp@0.30.2 and it worked fine.
