### ISSUE TITLE
getHostDevice() interface out of date

### ISSUE THREAD

**Issue by henrickJona** [orkestral/venom#1537]
## Description

it's about 4 or 5 update since this interface is out of date, please update it

## Environment

- **Venom version(s):** [4.0.7]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Log Output

```
{
  id: {
    server: 'c.us',
    user: '',
    _serialized: '@c.us'
  },
  email: null,
  description: null,
  statusConnection: 'CONNECTED',
  businessHours: { timezone: null },
  pushname: '',
  website: null,
  formattedTitle: '',
  categories: null,
  displayName: '',
  isBusiness: null,
  imgUrl: '',
  imgFull: '',
  previewEurl: ''
}
```

## Additional context / Screenshot

this is the new interface please update it

**Comment by jonalan7** [comment]
sometimes whatsapp modules are not downloaded! then it generates this problem!
