### ISSUE TITLE
Store.checkNumberBeta empty on new bootstrap_qr.js file

### ISSUE THREAD

**Issue by matheusb-comp** [orkestral/venom#1548]
## Description

After running the function `injectParasite`, the key [`Store.checkNumberBeta`](https://github.com/orkestral/venom/blob/0a204796998d547da7a3395dcf1985a05edf0935/src/lib/wapi/store/store-objects.js#L458) is `undefined`.
However, this happens only when the WhatsApp Web page loads the js file [bootstrap_qr.79aba964bea38dbcc501.js](https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js)

From what I tested, sometimes the page loads the file [bootstrap_qr.4ec5f0d2877d5f3b7590.js](https://web.whatsapp.com/bootstrap_qr.4ec5f0d2877d5f3b7590.js), and in this case the current conditions of `checkNumberBeta` in `storeObjects` works fine.

This happens because in the new js file (hash `79aba9...`) the `queryExists` function was moved from being the single default export of a module, to being one of two functions of a new module containing:
```
t.queryExists = function (e) ...
t.queryPhoneExists = function (e) ...
```
<details>
<summary>Module code in <code>bootstrap_qr.79aba964bea38dbcc501.js</code></summary>
<br>
<img src="https://user-images.githubusercontent.com/1227961/157503460-81aa7f8c-5e7b-443e-97b4-aade0278b54e.png" width="500" alt="Beautified code of the new module in the js file with hash 79aba9...">
</details>

Because of this situation, any place that calls `WAPI.checkNumberStatus` can have problems, [like this one on #1519](https://github.com/orkestral/venom/issues/1519#issuecomment-1062382804)

## Environment

- **Venom version(s):** 4.0.7 (using `WAPI` directly)
- **Browser:** Chrome 99
- **OS:** Ubuntu 21.10
- **Node version:** Node 17

## Your Code

To fix this, I changed the `checkNumberBeta` object in the `storeObjects` to:
```
{
  id: 'checkNumberBeta',
  conditions: (module) => {
    // function 'queryExists' is on bootstrap_qr.79aba964bea38dbcc501.js
    // function 'default' is on bootstrap_qr.4ec5f0d2877d5f3b7590.js
    const f = module.queryExists || module.default || {};
    return typeof f.toString === 'function' &&
      f.toString().includes('Should not reach queryExists MD')
      ? { queryExists: f }
      : null
  },
},
```
And changed the call on `checkNumberStatus`.

**Comment by jamesxt94** [comment]
Hi, thanks for your info. There is any workaround mean while?

**Comment by matheusb-comp** [comment]
I only changed the `storeObjects` file, and [these lines](https://github.com/orkestral/venom/blob/f5ce8e6be69827453a94187b2e58212d387ce9ca/src/lib/wapi/functions/check-number-status.js#L31-L32) to:
```
if (await WAPI.isBeta()) {
  return await Store.checkNumberBeta.queryExists(id)
```

**Comment by sergiooak** [comment]
This workaround works with me, I've just updated it directly on node_modules

**Comment by jeferssonlemes** [comment]
Just change the module.

```
{
    id: 'checkNumberBeta',
    conditions: (module) =>
        module.queryPhoneExists && module.queryExists
            ? module.queryExists
            : null,
}
```

**Comment by jamesxt94** [comment]
Not working. I run ```build:wapi``` and replace the file direcly on ```venom-bot``` folder, but still error ```gadd called without an id attr```

**Comment by jamesxt94** [comment]
Sorry I made a mistake, I just put working with this code in store-objects.js: 

```javascript
{
    id: 'checkNumberBeta',
    conditions: (module) => {
      let func = module.queryExists || module.default
      return (func && 
      typeof func.toString === 'function' &&
      func.toString().includes('Should not reach queryExists MD'))
        ? func
        : null
        
    }
  },
```

**Comment by jesusvalverde** [comment]
can someone please upload a wapi build with the modification ?

**Comment by jamesxt94** [comment]
[https://gist.github.com/jamesxt94/fae5bf879d875c46ebb82a6c9e9cae1d](https://gist.github.com/jamesxt94/fae5bf879d875c46ebb82a6c9e9cae1d)

**Comment by dockydicky** [comment]
thank you @jamesxt94
