### ISSUE TITLE
getProfilePicFromServer return undefined

### ISSUE THREAD

**Issue by Lacqua-Developer** [orkestral/venom#155]
the function "getProfilePicFromServer" not return url.

    static async GetPicture(sessionName,chatId,id){
       var session = Sessions.getSession(sessionName);
       var resultSendText = await session.client.then(async client => {
            const url = await client.getProfilePicFromServer(chatId);
           console.log(url);
            return url;
       });
       console.log(resultSendText);
       return resultSendText;
  }

**Comment by joaosouz4** [comment]
Or it is because this contact does not have a photo or it is blocked or it is your code with some problem, because it is working here.

**Comment by Lacqua-Developer** [comment]
Sorry, the problem was in my whatsapp account, function is working perfectly.

**Comment by bhavya32** [comment]
@Lacqua-Developer  @joaosouz4 Please close this issue.
