### ISSUE TITLE
disable welcome message and logo

### ISSUE THREAD

**Issue by Pezhvak** [orkestral/venom#156]
how can i disable welcoming message in terminal when i run the bot?

**Comment by igormenin** [comment]
in the file "src/controllers/initializer.ts" on line 95 there is a console.log

**Comment by Pezhvak** [comment]
i found it yesterday, had you comment it out, isn't it better to add an option to disable that?

**Comment by Pezhvak** [comment]
i found it yesterday, had to comment it out, isn't it better to add an option to disable that?

**Comment by Pezhvak** [comment]
i found it yesterday, had to comment it out, isn't it better to add an option to disable that? i can push a PR if it isn't a issue for repo owner.

**Comment by Pezhvak** [comment]
i found it yesterday, had to comment it out, isn't it better to add an option to disable that? i can push a PR if it isn't an issue for repo owner.

**Comment by Pezhvak** [comment]
i found it yesterday, had to comment it out, isn't it better to add an option to disable that? i can push a PR if it isn't an issue for @orkestral
