### ISSUE TITLE
onParticipantsChanged doesn't catch event

### ISSUE THREAD

**Issue by ClaraProgramadora** [orkestral/venom#1568]
## Description

The function onParticipantsChanged doesn't catch event, so I can't know about participants changes in my group.  Before, this code works. 

## Environment

- **Venom version(s):** 4.0.9
- **Browser:** Chrome 99.0.4844.51
- **OS:** macOS Monterey V12.2.1
- **Node version:** v14.17.4

## Steps to Reproduce

1. I create a new session
2. I execute start(client)
3. Finally, I execute client.onParticipantsChanged

## Your Code
function start(client: any) {

    idGroup = '000000000000-0000000000@g.us'
    client.onParticipantsChanged( idGroup,  (event: any) => {
        console.log(event)
    })

**Comment by mmhospedagem** [comment]
https://github.com/orkestral/venom/issues/1626

**Comment by ClaraProgramadora** [comment]
@mmhospedagem  Sorry, but issue https://github.com/orkestral/venom/issues/1626 has been deleted, so I don`t know how I catch onParticipantsChanged event. 
Thanks you for your answer.

**Comment by shailidalmia** [comment]
Is this issue resolved?

**Comment by aadishj02** [comment]
I am facing the same issue. Could anyone help me with this?
