### ISSUE TITLE
How venom listens for message even when sending message??

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#157]
I had 2 different programs in c#. 1st - for sending message and 2nd for autoreply.

The problem was how to mix both.

If I was sending message and had to stop autoreply function but then how to start it back(in my program).

How venom solved this problem?

**Comment by leobevi** [comment]
I believe that there is no way to have two instances of the same number for WhatsApp. If you open WebWhatsApp twice to the same number, WhatsApp itself blocks one of the instances.
The same is true with Venom or any other API

**Comment by bhavya32** [comment]
@leobevi Then do you know the part of code in venom where the switching takes place? I mean where autoreply hands over the command to sendtext function?
