### ISSUE TITLE
getHostDevice() return Error: gadd called without an id attr (id)

### ISSUE THREAD

**Issue by zinct** [orkestral/venom#1571]
## Description

when I want to fetch current client phone data via client.getHostDevice(). but it returns an error.

## Environment

- **Venom version(s):** ^4.0.6
- **Browser:** Chrome default version
- **OS:** Linux Mint 20.4 Cinnamon
- **Node version:** v16.14.0

## Steps to Reproduce

1. Scan QRcode
2. execute the getHostDevice()
3. then return an error.

## Log Output

Error: Evaluation failed: Error: gadd called without an id attr (id)
    at W.gadd (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:455434)
    at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:277773
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at j (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:259320)
    at new y (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:251887)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63094
    at W._findAndParse (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:278506)
    at ExecutionContext._evaluateInternal (/var/www/html/wa_bri/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/var/www/html/wa_bri/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

## Your Code

venom
  .create({
  "bot_name": "BurgerBot",
  "disableWelcome": true,
  "multidevice": false,
  "headless": true,
  "createPathFileToken": false,
  "logQR": false,
  "autoClose": 0
})
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

async function start(client) {
 const hostDevice = await client.getHostDevice();
 console.log(hostDevice);
}

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by downdawn** [comment]
`
client.getHostDevice().then((data) => {
    console.log("getHostDevice data", data)
}).catch((error) => {
    console.log("getHostDevice error", error)
})
`

**Comment by h4775346** [comment]
My Code 

```
const venom = require('venom-bot');

async function start(client) {
    client.onStateChange(state => {
        console.log(state);
    })
    client.getHostDevice().then((data) => {
        console.log("getHostDevice data", data)
    }).catch((error) => {
        console.log("getHostDevice error", error)
    })
}

venom.create(
    //session
    'session_1', //Pass the name of the client you want to start the bot
    //catchQR
    (base64Qrimg, asciiQR, attempts, urlCode) => {
        console.log('Number of attempts to read the qrcode: ', attempts);
        console.log('Terminal qrcode: ', asciiQR);
        console.log('base64 image string qrcode: ', base64Qrimg);
        console.log('urlCode (data-ref): ', urlCode);
    },
    // statusFind
    (statusSession, session) => {
        console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
        //Create session wss return "serverClose" case server for close
        console.log('Session name: ', session);
    },
    // options
    {
        folderNameToken: 'tokens', //folder name when saving tokens
        mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
        headless: true, // Headless chrome
        devtools: false, // Open devtools by default
        useChrome: true, // If false will use Chromium instance
        debug: false, // Opens a debug session
        logQR: true, // Logs QR automatically in terminal
        browserWS: '', // If u want to use browserWSEndpoint
        browserArgs: [''], // Parameters to be added into the chrome browser instance
        puppeteerOptions: {}, // Will be passed to puppeteer.launch
        disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
        disableWelcome: true, // Will disable the welcoming message which appears in the beginning
        updatesLog: true, // Logs info updates automatically in terminal
        autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
        createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
    },
)
    .then((client) => start(client))
    .catch((error) => console.log(error));
```

The Output

```
Status Session:  isLoggedChecking is logged...
Session name:  session_1
Status Session:  chatsAvailable
Session name:  session_1
√ [instance: session_1]: Connected
getHostDevice error Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (D:\test-whats\venom\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.getHost (D:\test-whats\venom\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:72570)
    at ExecutionContext._evaluateInternal (D:\test-whats\venom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\test-whats\venom\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)


```

**Comment by h4775346** [comment]
> ## Description
> when I want to fetch current client phone data via client.getHostDevice(). but it returns an error.
> 
> ## Environment
> * **Venom version(s):** ^4.0.6
> * **Browser:** Chrome default version
> * **OS:** Linux Mint 20.4 Cinnamon
> * **Node version:** v16.14.0
> 
> ## Steps to Reproduce
> 1. Scan QRcode
> 2. execute the getHostDevice()
> 3. then return an error.
> 
> ## Log Output
> Error: Evaluation failed: Error: gadd called without an id attr (id) at W.gadd (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:455434) at https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:277773 at Generator.next () at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943) at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154) at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213 at j (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:259320) at new y (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:5:251887) at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63094 at W._findAndParse (https://web.whatsapp.com/bootstrap_qr.79aba964bea38dbcc501.js:65:278506) at ExecutionContext._evaluateInternal (/var/www/html/wa_bri/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ExecutionContext.evaluate (/var/www/html/wa_bri/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
> 
> ## Your Code
> venom .create({ "bot_name": "BurgerBot", "disableWelcome": true, "multidevice": false, "headless": true, "createPathFileToken": false, "logQR": false, "autoClose": 0 }) .then((client) => start(client)) .catch((erro) => { console.log(erro); });
> 
> async function start(client) { const hostDevice = await client.getHostDevice(); console.log(hostDevice); }
> 
> ## Additional context / Screenshot
> Add any other context about the problem here. If applicable, add screenshots to help explain.

Check this [](https://github.com/orkestral/venom/issues/1584#issue-1175786840)
