### ISSUE TITLE
Receive Error When Trying to Send Message 

### ISSUE THREAD

**Issue by KayAlbertus** [orkestral/venom#1572]
Hello Team 

Receive the following error when trying to send message 

 **Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization**

  await client
         .sendText(message.from, 'Welcome To The BOT');

anyone else having this issue ?

**Comment by Helkyd** [comment]
I have the same error.

**Comment by sandro-salles** [comment]
+1
