### ISSUE TITLE
Whatsapp has changed the format of your group id.

### ISSUE THREAD

**Issue by matthewsbrandan** [orkestral/venom#1576]
## Description

Whatsapp has changed the format of your group id.

Recently created groups have the id in a different format, and I believe that because of this some requests are returning an error, such as addParticipant, promoteParticipant, demoteParticipant.

The default was < phoneNumber >-< groupId >@g.us, and now it's just < groupId >@g.us (groupId is 18 characters long).

## Environment

- **Venom version(s):** ^4.0.9
- **OS:** [Windows 10]
- **Node version:** 14.17.1

## Steps to Reproduce

1- Create the group using the *client.createGroup* function
2- The return will have the group id inside the response object, in the response.gid._serialized path

Here we can already see that the id is in a different pattern: xxxxxxxxxxxxxxxxxx@g.us

3- Run any function that uses group_id, like *client.addParticipant*

The return will be something like:

Error submitting: Error: Evaluation failed: TypeError: window.Store.sendAddParticipants is not a function
    in Object.window.WAPI.window.WAPI.addParticipant (C:\xampp\htdocs\codewriters\chatinger\venom-http\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:41306)
    in ExecutionContext._evaluateInternal (C:\xampp\htdocs\codewriters\chatinger\venom-http\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    in runMicrotasks(<anonymous>)
    in processTicksAndRejections(internal/process/task_queues.js:95:5)
    in async ExecutionContext.evaluate (C:\xampp\htdocs\codewriters\chatinger\venom-http\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by aseem2625** [comment]
Same error for both, any fixes yet?

```
TypeError: window.Store.sendAddParticipants is not a function

TypeError: window.Store.sendRemoveParticipants is not a function
```


<img width="946" alt="image" src="https://user-images.githubusercontent.com/6055628/160511459-f1093887-e179-406f-8ffd-d1fe1f9c1549.png">


<img width="945" alt="image" src="https://user-images.githubusercontent.com/6055628/160511481-16c0309d-8cc0-4ad5-a1d5-7e68bde2b731.png">

**Comment by aseem2625** [comment]
Hi @orkestral please suggest something

format of group id: XXXX6302XX696XXXXX@g.us
format of number: <CountryCode><Number>@c.us

**Comment by mikelustosa** [comment]
createGroup No works in Multi device version

**Comment by can1871** [comment]
i have the same problem

TypeError: window.Store.sendAddParticipants is not a function

**Comment by vielhuber** [comment]
Any update on this? This also does not work in the current nighty.
