### ISSUE TITLE
I want to become an active Contributor

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#158]
Can I have an overview about WAPI, middleware ? How venom works? Does it act like whatsapp web or it interacts with whatsapp web? **If this repo is left uncontributed, what are the chances it would break and why would it break??**

**Comment by joaosouz4** [comment]
he works with whatsapp web, using Puppeteer to enter WAPI, WAPI uses functions from whatsapp itself and sometimes we create modified functions.

**Comment by bhavya32** [comment]
@joaosouz4  So is there a chance whatsapp bringing update and breaking complete repo as WAPI will no longer work? I will be analysing WAPI this weekend.
