### ISSUE TITLE
Can't connect on IOS

### ISSUE THREAD

**Issue by ricocrivelli** [orkestral/venom#1592]
Hello everyone! I'm trying to connect using IOS but I'm getting this message error:

```
**Invalid QR code**
Make sure you are scanning a QR code displayed on WhatsApp Web, WhatsApp Desktop, Portal or any other official WhatsApp app.
If the scan still doesn't work, please refresh the app or page, and try again
```

I have already refreshed QR code, updated the app, but the error still showing. Anyone can help me?

![image](https://user-images.githubusercontent.com/2865753/160006507-5903727d-456c-4529-8537-da105e7f164d.png)

**Comment by alexandrefmota** [comment]
Tentei também com o Android e tive o mesmo problema
