### ISSUE TITLE
Error: Evaluation failed: Error: Unexpected null or undefined: bundle.encKey

### ISSUE THREAD

**Issue by knezenk** [orkestral/venom#1595]
## Description
i'm read qrcorde, show connected. But, when my application have this error:
Error: Evaluation failed: Error: Unexpected null or undefined: bundle.encKey

If i read qrcode by another number, works normally.

My number is not blocked, i use normally in my mobile and with whatsapp web.
[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output
(node:34086) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Unexpected null or undefined: bundle.encKey
    at t.default (https://web.whatsapp.com/:2:398)
    at Function.encrypt (https://web.whatsapp.com/bootstrap_main.0760a934d34cf2b1458a.js:5:7483)
    at t.default.<anonymous> (https://web.whatsapp.com/bootstrap_main.0760a934d34cf2b1458a.js:2:114672)
    at t.default.write (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:5:249992)
    at Object.<anonymous> (https://web.whatsapp.com/bootstrap_main.0760a934d34cf2b1458a.js:2:98703)
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:62943)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63154)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.da24f3cea9fbcca5ad69.js:2:63213
    at j (https://web.whatsapp.com/bootstrap_qr.7472073f4355d08a7723.js:5:259320)
    at ExecutionContext._evaluateInternal (/home/jarvis/PROJETOS/iclipping-wpp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/jarvis/PROJETOS/iclipping-wpp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(node:34086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

```
If relevant, paste all of your Log Output
```

## Your Code

```
const venom          = require('venom-bot');
const express        = require('express');
const app            = express();
 
global.createGroup   = '' ;



/*
| ------------------------------------------------------------------------------------------
| Start venom session application
| ------------------------------------------------------------------------------------------
|
*/ 

//venom.create( 'create group', '', '', { folderNameToken: 'tokens', headless: false, browserArgs: ['--no-sandbox'] } ).then( ( client ) => { 
venom.create( 'create group', '', '', { folderNameToken: 'tokens', headless: false } ).then( ( client ) => { 

  createGroup = require('./managerWhatsapp')( client ); 
  
  alertsSend();
  
});
 

 

/*
| ------------------------------------------------------------------------------------------
| Start send alerts whatsapp
| ------------------------------------------------------------------------------------------
|
*/ 

var alertsSend = () =>{

  createGroup.sendAlerts() 
  
}
 
 


/*
| ------------------------------------------------------------------------------------------
| Route for create group whatsapp
| ------------------------------------------------------------------------------------------
|
*/ 

app.get('/create', function (req, res) {

  createGroup.registerGroup() 
 
});


/*
| ------------------------------------------------------------------------------------------
| Route for send indivudual msg
| ------------------------------------------------------------------------------------------
|
*/ 

app.get('/sendMessage/:phone/:message', function (req, res) {

  createGroup.sendMessage(req.params.phone,req.params.message) 
 
});



/*
| ------------------------------------------------------------------------------------------
| Route for send message group iclipping
| ------------------------------------------------------------------------------------------
|
*/ 

app.get('/sendMessageGroup/:message', function (req, res) {
  
  createGroup.sendMessageGroup( req.params.message ) 

  res.end()
});

 


/*
| ------------------------------------------------------------------------------------------
| Start port server
| ------------------------------------------------------------------------------------------
|
*/ 

app.listen(3000);

```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by 239626** [comment]
I'm having the same error
