### ISSUE TITLE
Label e primeira mensagem

### ISSUE THREAD

**Issue by Juuhz** [orkestral/venom#16]
Oi, tudo bem?

Gostaria de saber se existe suporte para:

- Arquivar a mensagem.
- Colocar Label na mensagem.
- Saber se a mensagem recebida é a primeira (Para exibir uma lista de opções, por exemplo).

Abraços.

**Comment by orkestral** [comment]
Sim nas próximas versões adicionaremos essas mudanças obrigado.

**Comment by emersonbroga** [comment]
boa noite @orkestral, alguma informação sobre label nas mensagens?
