### ISSUE TITLE
How to save the tokens in redis or database?

### ISSUE THREAD

**Issue by fly2012** [orkestral/venom#161]
I need run the application on multiple servers and get tokens from redis or database.
So,how to save the tokens in redis or database after user sign in?

**Comment by edgardmessias** [comment]
@jonalan7 @joaosouz4 , maybe we can create an interface to handle this, with two methods: saveToken and loadToken. By default we can use methods for saving and loading for file.

**Comment by joaosouz4** [comment]
yes, it would be interesting to have this new feature

Em ter., 22 de set. de 2020 às 15:07, Edgard Lorraine Messias <
notifications@github.com> escreveu:

**Comment by jonalan7** [comment]
@fly2012  @joaosouz4  @edgardmessias  
**Enhancement done!**
