### ISSUE TITLE
onStateChange still not working on version 4.0.9

### ISSUE THREAD

**Issue by sandro-salles** [orkestral/venom#1612]
## Description

When i logout from the device, the event is never sent to the **onStateChange** callback.
I'm currently on version 4.0.9. ... anyone else with the same problem?

[Description of the bug, When Issue Happens]

When i logout from the device, nothing happens on Venom client tha is running.

## Environment

- **Venom version(s):** 4.0.9
- **Browser:** Version 99.0.4844.84 (Official Build) (64-bit)
- **OS:** Ubuntu 20.04
- **Node version:** v14.17.1

## Your Code

`import { create } from "venom-bot";

create(
  //session
  "sessionName", //Pass the name of the client you want to start the bot
  //catchQR
  (base64Qrimg, asciiQR, attempts, urlCode) => {
    console.log("Number of attempts to read the qrcode: ", attempts);
    console.log("Terminal qrcode: ", asciiQR);
    console.log("base64 image string qrcode: ", base64Qrimg);
    console.log("urlCode (data-ref): ", urlCode);
  },
  // statusFind
  (statusSession, session) => {
    console.log("Status Session: ", statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken || chatsAvailable || deviceNotConnected || serverWssNotConnected || noOpenBrowser
    //Create session wss return "serverClose" case server for close
    console.log("Session name: ", session);
  },
  // options
  {
    multidevice: true, // for version not multidevice use false.(default: true)
    headless: true, // Headless chrome
    devtools: false, // Open devtools by default
    logQR: true, // Logs QR automatically in terminal
    disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
    disableWelcome: true, // Will disable the welcoming message which appears in the beginning
    updatesLog: true, // Logs info updates automatically in terminal
  }
)
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

async function start(client) {
  client.onStateChange((state) => console.log("onStateChange", state));
}`

**Comment by jonalan7** [comment]
WhatsApp is making status changes, due to multiple devices
