### ISSUE TITLE
client.setProfileName not working on 4.0.9

### ISSUE THREAD

**Issue by sandro-salles** [orkestral/venom#1614]
## Description

[Description of the bug, When Issue Happens]

When we call client.setProfileName on 4.0.9, it does nothing.

Setting headless to false, we can inspect that there is an error when the call is made. 
It looks like **window.Store.Perfil** does not exists when the function below is called:

https://github.com/orkestral/venom/blob/87ffc7ddaa2a61a0ab77b490f36f42bb1a0c0165/src/lib/wapi/functions/set-my-name.js#L56

## Environment

- **Venom version(s):** 4.0.9
- **Browser:** Version 99.0.4844.84 (Official Build) (64-bit)
- **OS:** Ubuntu 20.04
- **Node version:** v14.17.1

**Comment by jonalan7** [comment]
I tested it and it works normally!

**Comment by sandro-salles** [comment]
@jonalan7 still not working here.. 

The thing I noticed is that when I start the client from a previous valid session in the tokens folder, then the name is set successfully... but if i try to set the profile name right after the first connection (after a successful QR scan), then it does nothing as i said in the description.
