### ISSUE TITLE
A database error occurred on your browser.

### ISSUE THREAD

**Issue by mikelustosa** [orkestral/venom#1619]
This message started to appear and I have to authenticate the qrcode again. In WhatsApp Multi device:
A database error occurred on your browser. Please restart your computer and relink your device.

**Comment by sergey-chechaev** [comment]
> This message started to appear and I have to authenticate the qrcode again. In WhatsApp Multi device: A database error occurred on your browser. Prease restart your computer and relink your device.

Send bug report to WhatsApp email: support@whatsapp.com or in mobile Application "Settings" -> "Help" -> "Contact Us"

**Comment by idealti-git** [comment]
https://github.com/orkestral/venom/issues/1626
