### ISSUE TITLE
Error when scanning QR code

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#1621]
I get this error when scanning the qr code

node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by joel-vasiliev** [comment]
I'm having the same issue, how'd you fixed it?
