### ISSUE TITLE
joinGroup not working

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#1622]
const joinCommand = (client, message) => {
    //let link = message.content.split('/');
    let url = message.content.split(' ')[1];
    console.log(`URL: ${url}`);
    client.joinGroup(url.split('/')[3]);
    console.log(`Invite: ${url.split('/')[3]}`)
}

exports.joinCommand = joinCommand;

Doesn't work when I send the link to the bot, the console.logs are working perfectly and the invite code is correct

**Comment by idealti-git** [comment]
https://github.com/orkestral/venom/issues/1626
