### ISSUE TITLE
Send Buttons

### ISSUE THREAD

**Issue by Fernandosousa1998** [orkestral/venom#1624]
A função de enviar botões, parou de funcionar. Alguém poderia me ajudar?

**Comment by idealti-git** [comment]
https://github.com/orkestral/venom/issues/1626

**Comment by felipebadr** [comment]
Parece ser alguma atualização no whatsapp web pois testei outra api e também está dando erro pra enviar botão.

**Comment by Termulux** [comment]
sendListMenu parou tbm? comecei a utilizar API hoje e nenhum dos dois estão funcionando pra mim, usei os exemplos do readme, depois que uso as funções elas não retornam o Result.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/78597559/165168042-af9524ea-5e85-47e5-8411-936e6ef56546.png">

**Comment by pedruhb** [comment]
> sendListMenu parou tbm? comecei a utilizar API hoje e nenhum dos dois estão funcionando pra mim, usei os exemplos do readme, depois que uso as funções elas não retornam o Result. <img alt="image" width="658" src="https://user-images.githubusercontent.com/78597559/165168042-af9524ea-5e85-47e5-8411-936e6ef56546.png">

sendListMenu tá funcionando mas só no whatsapp normal, no business não funciona, o botão parou mesmo, vou ter que usar listmenu.

**Comment by FernandoTBarros** [comment]
Mesmo problema aqui com o sendButton. O sendListMenu tá funcionando. 
Eu já tinha usado o sendButton outra vez e funcionou, agora fui tentar usar hoje e sem sucesso... tem relação com o WhatsApp mesmo ou alguma coisa com a atualização do Venom?

**Comment by orkestral** [comment]
Hello thanks for the report, we are creating a new version with all the bugs fixed, this issue will be closed for the open time.

**Comment by FernandoTBarros** [comment]
Hello!
Sorry to return on this but I don't find the commits fixing these errors?
Do you have any open PR or something I could work on apart from the official new released version?
