### ISSUE TITLE
Pessoal, alguém mais aqui foi roubado pelo pessoal da Superchats / Venom? 

### ISSUE THREAD

**Issue by idealti-git** [orkestral/venom#1626]
Em dezembro o Joe Dutra me prometeu um painel por 3mil reais. Assinei o contrato e paguei e não recebi nada. Ao cobrar o Joe de forma mais assídua ele disse que não tinha como devolver o dinheiro por não tinha a grana e que era pra eu fazer o que quisesse.. Acredito que tenha sido vítima de um estelionatário e vou procurar a Justiça.

**Comment by mmhospedagem** [comment]
Ele nos roubou literalmente também! Recomendo a todos terem cuidado com esse cara.

**Comment by alexandreluchini** [comment]
Nós tambem.
Ano passado final de 2021 compramos e pagamos 3.000 com promessas e mais promessas.
Nao nos devolveu o dinheiro, nos bloqueou dos grupos.

Ele tem UM PUXA SACO que tem um sistema de atendimento que defende ele, mas o cara é um pilantra esse JOE DUTRA.

FUJAM desse VENOM.

**Comment by jrCleber** [comment]
+1
