### ISSUE TITLE
I cant't start a project: Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by JulioMiguell** [orkestral/venom#163]
![image](https://user-images.githubusercontent.com/37316841/93652693-51e85480-f9ec-11ea-9eca-bd78c999bbaf.png)
Using ES6 import some problemas appear, too: 
![image](https://user-images.githubusercontent.com/37316841/93652791-adb2dd80-f9ec-11ea-8cdb-79dbf4489232.png)
My node version is: v12.16.3

**Comment by WilliamTeixeira** [comment]
> ![image](https://user-images.githubusercontent.com/37316841/93652693-51e85480-f9ec-11ea-9eca-bd78c999bbaf.png)
> Using ES6 import some problemas appear, too:
> ![image](https://user-images.githubusercontent.com/37316841/93652791-adb2dd80-f9ec-11ea-8cdb-79dbf4489232.png)
> My node version is: v12.16.3

I went through this same problem. In the "venom-bot" version: "1.1.4" does not occur.

**Comment by JulioMiguell** [comment]
> > ![image](https://user-images.githubusercontent.com/37316841/93652693-51e85480-f9ec-11ea-9eca-bd78c999bbaf.png)
> > Using ES6 import some problemas appear, too:
> > ![image](https://user-images.githubusercontent.com/37316841/93652791-adb2dd80-f9ec-11ea-8cdb-79dbf4489232.png)
> > My node version is: v12.16.3
> 
> I went through this same problem. In the "venom-bot" version: "1.1.4" does not occur.

What version are you using?!

**Comment by OmarMYousef** [comment]
Hello guys, i've experienced this error before
try running `npm i --save rxjs`
if `cannot find module 'venom-bot'` error appeared reinstall `venom-bot` again using `npm i --save venom-bot`

Hope it works for you guys ^^

**Comment by bhavya32** [comment]
@joaosouz4 I think issue is resolved?

**Comment by WilliamTeixeira** [comment]
> > > ![image](https://user-images.githubusercontent.com/37316841/93652693-51e85480-f9ec-11ea-9eca-bd78c999bbaf.png)
> > > Using ES6 import some problemas appear, too:
> > > ![image](https://user-images.githubusercontent.com/37316841/93652791-adb2dd80-f9ec-11ea-8cdb-79dbf4489232.png)
> > > My node version is: v12.16.3
> > 
> > 
> > I went through this same problem. In the "venom-bot" version: "1.1.4" does not occur.
> 
> What version are you using?!

I use version 1.1.4, but I will try the @OmarMYousef procedure.

**Comment by JulioMiguell** [comment]
> > > > ![image](https://user-images.githubusercontent.com/37316841/93652693-51e85480-f9ec-11ea-9eca-bd78c999bbaf.png)
> > > > Using ES6 import some problemas appear, too:
> > > > ![image](https://user-images.githubusercontent.com/37316841/93652791-adb2dd80-f9ec-11ea-8cdb-79dbf4489232.png)
> > > > My node version is: v12.16.3
> > > 
> > > 
> > > I went through this same problem. In the "venom-bot" version: "1.1.4" does not occur.
> > 
> > 
> > What version are you using?!
> 
> I use version 1.1.4, but I will try the @OmarMYousef procedure.

I'll do it, too!

**Comment by joaosouz4** [comment]
i fix this #168
