### ISSUE TITLE
Group functions do not work

### ISSUE THREAD

**Issue by can1871** [orkestral/venom#1635]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** 4.0.10
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** Node 14

Group functions do not work.

```
sendAddParticipants is not a function
```
when run says. When I try to fix the removeParticipant, either nothing happens or I get the error 

```
participantsAction with action = remove: incoming change missing version id.
```

**Comment by vielhuber** [comment]
Any update on this? This does also not work in the current nightly.
