### ISSUE TITLE
Error on sendListMenu

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#1637]
## Description
This error is occurring when sending the method send List Menu, in linux environment, version 4.0.10.

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 4.0.10]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. Linux Ubuntu]
- **Node version:** [Node 12.22,7]

## Your Code

```
        const messageAt = await client.sendListMenu(`${destinatario}@c.us`, this.titulo, ' ', this.mensagem, 'Opções', <any>menus)
```
![image](https://user-images.githubusercontent.com/59453913/165324955-d21d7cd6-1f7c-4c16-9d03-ea8516ccae64.png)

**Comment by FernandoTBarros** [comment]
Looking for the line this error ocours it appears that the sent method returns an undefined result.
What do you have on 'menus' variable?
