### ISSUE TITLE
get all messages in chat, even the ones sent by the bot

### ISSUE THREAD

**Issue by OmarMYousef** [orkestral/venom#164]
Hello there, i want to load all messages in chat, includes the contact messages and the bot messages
is there's a way to do that ?

**Comment by bhavya32** [comment]
@OmarMYousef ```const Messages = await client.getAllMessagesInChat('000000000000@c.us');```

**Comment by OmarMYousef** [comment]
> @OmarMYousef `const Messages = await client.getAllMessagesInChat('000000000000@c.us');`

@bhavya32  Yeah, i've tried that in 1.1.4, and it returns the contact messages only, i want to get all messages in the chat including the ones sent by the bot and messages sent by the contact

is that function changed in 2.0.1 or it does the same ?

**Comment by jonalan7** [comment]
@OmarMYousef **Just do the following**

const Messages = await client.getAllMessagesInChat('000000000000@c.us', **true**);
