### ISSUE TITLE
Problems - QRCODE

### ISSUE THREAD

**Issue by leobevi** [orkestral/venom#165]
Hello .... it was in version 1.1.4, when I started the system and already made a request for QRCODE, it was working normal. I upgraded to version 2.0 and started to have problems with this routine, when I start the system - node server.js - and make a QRCODE request it does the reading but after a while the system is closed. error picture follows

![qrcode](https://user-images.githubusercontent.com/17435878/93657841-4147d680-fa0c-11ea-9fe9-bef0934237f2.jpg)

` 
function startVenom(session,enviaqrcod){ 
    let enviadoqrcode = 1;
    const OPTIONS = {
        headless: true,
        devtools: false,
        useChrome: true,
        debug: false,
        logQR: true,
        browserArgs: [],
        refreshQR: 15000,
        autoClose: 15000,
        disableSpins: true
    };
    venom.create(session+'', (base64Qr, asciiQR) => {
 
        if(enviadoqrcode == 1 && enviaqrcod !== '' ){
            //fazendo a validação se foi solicitado umqrcod para envio da requisição
            //o objeto está sendo passado como parametro para envio
            //let send_qrcode= '<img src='+base64Qr+' >'
            let retorno = {
                qrCode : base64Qr
            }
            enviaqrcod.send(retorno); // passando como base64
        }
       
        enviadoqrcode ++;
    }, (statusSession) =>{
         console.log(statusSession);
    }, OPTIONS).then((client) => {
        start(client);
    }).catch((erro) => console.log(erro));
}
`

`  
app.get('/getqrcode', async function (req, res) {
    console.log('solicitou QRCODE');
    try {
    
         const executa = async()=>{
                 if (typeof(srv) === "object"){ // não está inciado o venom
                    status = await srv.close();
                    srv='';
                }                
                await deletasessao();
                startVenom(token,res);        
             
           };
         executa();

    }
    catch (e) {
        console.log(e);
    }
  });
`

Será algum parâmetro incorreto na inicialização para a nova versão?

**Comment by bhavya32** [comment]
Have you tried with a phone with faster network? In my case, I got the same problem but if I was on faster network, this was resolved. Try overriding the autoclose time.

**Comment by bhavya32** [comment]
You can also set headless to false and post images that what is happening in chrome when script ends.

**Comment by leobevi** [comment]
I'm using wiffi the connection is very good.

What I realized here is that: if I start server.js, I start venom create and do not scan the QRCODE it has this problem. in version 1.1.4 I did not have this problem regardless if I read it or not at any time that I create it the reading was done.

Even if I change the values of the options for initialization, it seems that they are not applied.

         headless: false,
         devtools: false,
         useChrome: true,
         debug: false,
         logQR: true,
         browserArgs: [],
         refreshQR: 15000,
         autoClose: NautoClose,
         disableSpins: true

![qrcode](https://user-images.githubusercontent.com/17435878/93659637-c8517a80-fa1d-11ea-8f00-c024bfe7a775.jpg)

**Comment by bhavya32** [comment]
@leobevi   What is **NautoClose**? You should set autoclose to 0 or false. And try without headless.

**Comment by leobevi** [comment]
@bhavya32 - NautoClose is a variable, I put the value 0 or 15000 or false

**Comment by jonalan7** [comment]
> @ bhavya32 - NautoClose é uma variável, coloco o valor 0 ou 15000 ou falso
**Aparentemente, seu erro foi gerado na linha 107 em seu código-fonte, não vejo nenhum erro em nenhuma linha do wapi venom-bot.**

**Comment by jonalan7** [comment]
@leobevi  
**Apparently, your error was generated on line 107 in your source code, I don't see any errors on any line in the wapi venom-bot.**

**Comment by bhavya32** [comment]
@jonalan7 spinnies is not his code, it is a node module. And it is not the error he is trying to resolve. He claims that even he specified headless to false, chrome still runs headless and specifying autoclose to false, autoclose still remains on.

**Comment by jonalan7** [comment]
@Leobevi **Review your codes, because it works perfectly for me!**

```
const venom = require("venom-bot");
venom.create("Testing", undefined, undefined,
  { 
    headless: true,
    autoClose: 0 | false,
  }
).then((client) => { 
    ////
}).catch((erro) => { 
    console.error("ERROR: ", erro);
});
```
![image](https://user-images.githubusercontent.com/67329824/93688990-b369fb00-faa0-11ea-84df-f1d42eb970b6.png)

```
const venom = require("venom-bot");
venom.create("Testing", undefined, undefined,
  { 
    headless: true,
    autoClose: 60000,
  }
).then((client) => { 
    ////
}).catch((erro) => { 
    console.error("ERROR: ", erro);
});

```

![image](https://user-images.githubusercontent.com/67329824/93689017-f4faa600-faa0-11ea-9e4a-8beba7595c19.png)

**Comment by leobevi** [comment]
@jonalan7 ......Thank you very much for your attention! ..... I removed the undefined in create here and there was no problem closing the application. But the problem still persists, when I ask for a QRCODE reading and I don't do the reading and right after I ask for a new reading the venom does not recognize it, I enabled it to view in the browser, when the reading is done, via the browser it recognizes but not in the venom.

I will try to record a video in both versions to try to reproduce the problem.

**Comment by leobevi** [comment]
@ jonalan7 ..... I tried to reproduce the two versions in videos, the code is the same for both

Version 2.0
![venom](https://user-images.githubusercontent.com/17435878/93692173-1b7f0800-fac6-11ea-9253-c8e5a80c466f.gif)


Version 1.1.4

![venom114](https://user-images.githubusercontent.com/17435878/93692177-276aca00-fac6-11ea-900f-71a470a3af66.gif)

**Comment by leobevi** [comment]
@ jonalan7 .....

If I do the reading for the first time it works fine ...... but it is that the user requests the QRCODE and does not do the reading the first time and the second one ends up not working ...... I have to restart the server at hand ..... which in version 1.1.4 did not need. maybe I have to do a process to restart it via a user command, where when he asks for a QRCODE I stop the node and start the process again

**Comment by winkcler** [comment]
Hello friend, did you manage to solve your problem?

**Comment by winkcler** [comment]
@leobevi  fale comigo no instagram por gentileza, @sulltanmusic

**Comment by leobevi** [comment]
@winkcler, Salve!! Não consegui resolver ainda, como está sendo gerenciado pelo pm2 acho que vou criar um botão para dar restart no nodejs a cada requisição de QRCODE, talvez seja uma solução......... infelizmente não tenho instagram amigo.

**Comment by winkcler** [comment]
@leobevi  Fala comigo no whatsapp ai mano , to desenvolvendo a mesma coisa. Vamos se ajudar

meu whats 68 99229-8012

**Comment by joaosouz4** [comment]
@leobevi Seu problema está no gerenciamento da sessão, logo vamos fazer um gerenciamento um pouco melhor pelo venom, mas por enquanto vc deve gerenciar pelo seu node mesmo, removendo adicionar dentro de um array client do venom, se o qr nao for lido e der autoclose, vc deleta o mesmo do array

**Comment by leobevi** [comment]
@joaosouz4  - Vaelu pelo retorno! 
Legal vou estudar como fazer esta implementação, parabéns pelo trabalho de vocês!! Obrigado!
