### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'session')

### ISSUE THREAD

**Issue by Arcane6** [orkestral/venom#1659]
Olá, estou com um problema na leitura da sessão.
Não está gerando o QR CODE...
Alguém consegue me ajudar?

```
import { start } from "repl"
import {create, Whatsapp, Message, SocketState } from "venom-bot"

class Sender {
    private client: Whatsapp
    
    constructor()
    {   
        //NAO FOI FEITO NO CONSTRUTOR PRA FICAR MAIS LIMPO E EXPLICITO.
        // METODOS DE INICIALIZAÇÃO
        this.initialize()
    }

    async sendText(to: string, body:string)
    {
        //55dddnumero@c.us
        this.client.sendText(to,body)
    }

    // METODO DE FORA
    private initialize()
        {
            const qr = (base64Qrimg: string) => {}

            const status = (statusSession: string) =>
            {
                // isLogged || notLogged || browserClosed || qrReadSuccess || noOpenBrowser || deleteToken
            }

            const start = (client: Whatsapp) =>
            {
                this.client = client

                this.sendText("5521982314899@c.us", "Ola, tudo bem? esse é um teste")
            }

            create('arcane-sender', qr, status)
            .then((client)=> start(client))
            .catch((error) => console.error(error))
        }
}
export default Sender

```

O ERRO:

``
TypeError: Cannot read properties of undefined (reading 'session')
    at C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\src\controllers\initializer.ts:177:48
    at step (C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\dist\controllers\initializer.js:98:23)
    at Object.next (C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\dist\controllers\initializer.js:79:53)
    at C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\dist\controllers\initializer.js:73:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\dist\controllers\initializer.js:69:12)
    at create (C:\Users\Antonio Oliveira\Desktop\JavaScript\node_modules\venom-bot\dist\controllers\initializer.js:117:12)
    at Sender.initialize (C:\Users\Antonio Oliveira\Desktop\JavaScript\src\sender.ts:37:19) 
    at new Sender (C:\Users\Antonio Oliveira\Desktop\JavaScript\src\sender.ts:11:14)        
    at Object.<anonymous> (C:\Users\Antonio Oliveira\Desktop\JavaScript\src\app.ts:4:16)
``

**Comment by joaocib** [comment]
Tenta isso... const status = (statusSession: string, **session: string**) => ...

**Comment by pedrolucasD** [comment]
I'm with the same problem.
I've noticed that this happens when I put the status parameter on creation.
If I don't put the status parameter it works, but I wouldn't be able to use the status either.

**Comment by caio1985** [comment]
> 

That is right @pedrolucasD.
If I use:
```

    const status = (statusSession: string, session: string) => {

    };

    const start = (client: Whatsapp) => {
      this.client = client;
    }

    create('ws-sender-dev', qr)
      .then((client) => start(client))
      .catch((error) => console.error(error));
```
It works. However if I call create like this:
```
    create('ws-sender-dev', qr, status)
      .then((client) => start(client))
      .catch((error) => console.error(error));
```
It fails with:
`TypeError: Cannot read property 'session' of undefined`

I'm using 4.0.11.

**Comment by lorangel37** [comment]
Realmente se trata de algo da versão 4.0.11, pra resolver é só colocar a versão 4.0.10 conforme o @pedrolucasD disse.
npm i --save venom-bot@4.0.10

**Comment by emersonart** [comment]
Olá, estou tendo o mesmo problema na versão 4.1.0, resolvendo apenas também sem passar o callback status.

**Comment by emourinho** [comment]
I have the same problem in version ^4.2.0.

**Comment by NicolasFelippe** [comment]
I have the same problem in version ^4.2.0.

**Comment by iwfet** [comment]
I have the same problem in version ^4.0.10

**Comment by dralucindaodonto** [comment]
same here!

**Comment by luizfelipedev-agillity** [comment]
> Realmente se trata de algo da versão 4.0.11, pra resolver é só colocar a versão 4.0.10 conforme o @pedrolucasD disse. npm i --save venom-bot@4.0.10

deve realizar esse processo para funcionar perfeitamente

**Comment by taigfs** [comment]
I am having the same problem on versions 4.0.11 and 4.2.0.

**Comment by prdanielmota** [comment]
O problema é a versão, teste outras versões do venom.

**Comment by rodrigoadachi** [comment]
I am having the same problem on version 4.3.0

**Comment by matheusmastrangelo** [comment]
Alguém conseguiu resolver?

**Comment by aislanspeedio** [comment]
I'm getting the same problem into 4.3.0

**Comment by aislanspeedio** [comment]
Why this issue is closed ?

**Comment by Feeh03114** [comment]
Foi corrigido?

**Comment by Feeh03114** [comment]
I found a solution, but I don't recommend it because you have to do it every time you do an npm install or yarn.

Access: node_modules/venom-bot/controllers/initializer.js
remove this.session -> session
save ready
tested in version **4.3.0**

**Comment by Feeh03114** [comment]
> estou usando a versão venom-bot@4.0.10

I solved this problem from version 4.3 by doing the following step:
Step 1: Access node_modules/venom-bot/controllers/initializer.js
Step 2: remove this.session -> session
Step 3: save ready

**Comment by regis-amaral** [comment]
@Feeh03114 muito obrigado por sua solução!

> > estou usando a versão venom-bot@4.0.10
> 
> I solved this problem from version 4.3 by doing the following step: Step 1: Access node_modules/venom-bot/controllers/initializer.js Step 2: remove this.session to session Step 3: save ready

@Feeh03114, Obrigado por sua correção!

**Comment by TrereZero** [comment]
> > estou usando a versão venom-bot@4.0.10
> 
> I solved this problem from version 4.3 by doing the following step: Step 1: Access node_modules/venom-bot/controllers/initializer.js Step 2: remove this.session to session Step 3: save ready

Thank you. I've find/replace all the "this.session" to "session", and it worked. God bless.

:brazil: Funcionou galera, só dar replace em todos os "this.session" e trocar por "session" no initializer.js

**Comment by kodiyak** [comment]
This works for me 🚀
`import * as venom from "venom-bot";`

**Comment by cristianoof** [comment]
> > estou usando a versão venom-bot@4.0.10
> 
> Resolvi esse problema a partir da versão 4.3 fazendo o seguinte passo: Passo 1: Acesse node_modules/venom-bot/controllers/initializer.js Passo 2: remova this.session para a sessão Passo 3: salve pronto

funcionou pra mim também, valeu!
