### ISSUE TITLE
 Message to a group

### ISSUE THREAD

**Issue by WilliamTeixeira** [orkestral/venom#166]
Is there a method to send a message to a group?

I made a bow to send to contacts, but it was inelegant and I'm afraid to use it. 😧

**Comment by OmarMYousef** [comment]
Hello there, as the documentary says, you can send messages by setting chatID to `<phoneNumber>-<groupId>@c.us`

please notice that message listener returns an object, it contains data about the message including the chatID where the message was sent and if the chat was either a group or a contact 😄

**Comment by WilliamTeixeira** [comment]
> Hello there, as the documentary says, you can send messages by setting chatID to `<phoneNumber>-<groupId>@c.us`
> 
> please notice that message listener returns an object, it contains data about the message including the chatID where the message was sent and if the chat was either a group or a contact 😄


Got it, I didn't get it that way. 
Thank you!

**Comment by developerdevice** [comment]
![image](https://user-images.githubusercontent.com/24875140/93767846-df939200-fbee-11ea-9fb8-832f65f9ce04.png)

I'm trying to send a message to the group but it returns error 400.

`	
await client.sendText("558796354993-1600688152@c.us", '👋 Hello from venom!').then((result)=>{
		  console.log("Result: ", result); //return object success
	  }).catch((erro)=>{
		  console.error("Error when sending: ", erro); //return object error
	});
`
