### ISSUE TITLE
Got onmessage chat with type ciphertext without body

### ISSUE THREAD

**Issue by rahman77889** [orkestral/venom#1660]
Recently i have chat but no body value as well

which kind parameter to get body from this message type

this is response message : 
message :  {
  id: 'false_886954103624@c.us_FDBA47336EE3833F1D47EB7B57A1E3CE',
  type: 'ciphertext',
  subtype: 'fanout',
  t: 1651960621,
  notifyName: 'Mamaindi',
  from: '886954103624@c.us',
  to: '886985039039@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  recvFresh: true,
  isFromTemplate: false,
  broadcast: false,
  mentionedJidList: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  hasReaction: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  requiresDirectConnection: null,
  pttForwardedFeaturesEnabled: true,
  chatId: '886954103624@c.us',
  fromMe: false,
  sender: {
    id: '886954103624@c.us',
    type: 'in',
    formattedName: '+886 954 103 624',
    displayName: '+886 954 103 624',
    formattedShortName: '+886 954 103 624',
    formattedShortNameWithNonBreakingSpaces: '+886 954 103 624',
    isMe: false,
    isMyContact: false,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {},
    msgs: null
  },
  timestamp: 1651960621,
  isGroupMsg: false,
  isMedia: false,
  isNotification: false,
isPSA: false,
  chat: {
    id: '886954103624@c.us',
    t: 1651960621,
    unreadCount: 1,
    muteExpiration: 0,
    unreadMentionsOfMe: [],
    hasUnreadMention: false,
    archiveAtMentionViewedInDrawer: false,
    hasChatBeenOpened: false,
    pendingInitialLoading: false,
    msgs: null,
    kind: 'chat',
    isGroup: false,
    contact: {
      id: '886954103624@c.us',
      type: 'in',
      formattedName: '+886 954 103 624',
      displayName: '+886 954 103 624',
      formattedShortName: '+886 954 103 624',
      formattedShortNameWithNonBreakingSpaces: '+886 954 103 624',
      isMe: false,
      isMyContact: false,
isPSA: false,
      isUser: true,
      isWAContact: true,
      profilePicThumbObj: {},
      msgs: null
    },
    groupMetadata: null,
    presence: { id: '886954103624@c.us', chatstates: [] },
    isOnline: null,
    lastSeen: null
  },
  isOnline: null,
  lastSeen: null,
  mediaData: {},
  linkPreview: false,
  initialPageSize: 768
}

Thank you

**Comment by murilobesse** [comment]
Same here, I wrote this function to process ciphertext msg:

`async function processCipherText(client, msgId, from){
	setTimeout( async () => {
		const Messages = await client.getAllMessagesInChat(from);
		Messages.forEach(message => {
			if(message.id == msgId)
			{
				if(message.type == 'ciphertext'){
					console.log('process again');
					processCipherText(number, msgId, from);
				}else{
					console.log('message processed');
                                        console.log(message.body);
				}
			}
		})
	}, 500);
}`

**Comment by valentinolopezbruno** [comment]
if (message.type === 'ciphertext') { 
        log('Intentando procesar/descifrar un mensaje: ', { message }, INFO);
        const processedMessage = await processCipherText(client, message.id, message.from);
        if (!processedMessage) {
          return;
        }
        
        if (processedMessage && processedMessage.content) {
          message = { ...message, content: processedMessage.content };
      } else {
        log('processedMessage no contiene el atributo content: ', { processedMessage }, ERROR);
      }     
     }



async function processCipherText(client, msgId, from) {
  const MAX_ATTEMPTS = 5;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {      
      const Messages = await client.getAllMessagesInChat(from);
      const message = Messages.find(msg => msg.id === msgId);

      if (!message) { // no encuentra el msj en el chat
        log('No se encontro el mensaje para procesar (processCipherText) ',  INFO);
        return null;
      }

      if (message.type != 'ciphertext') {
        return message;

    } catch (error) {
      log('Error al procesar el mensaje (processCipherText): ', { ERROR }, ERROR);
      return null; 
    }
  }
  return null; 
}
