### ISSUE TITLE
Como fechar o aba da sessão do browser

### ISSUE THREAD

**Issue by lopesclayton** [orkestral/venom#1663]
Tenho um servidor que tem varias sessões,  para cada sessão conectada tem um processo do chromium rodando...
quando eu dou o client.close()

esse processo ainda fica ativo...
como faco para  matar esse processo para nao ficar ocupando memoria ?

**Comment by jonalan7** [comment]
`process.exit()`

**Comment by jonalan7** [comment]
Quando for abrir um issue tente cria-lo em inglês!

**Comment by joaocib** [comment]
Opa, avisa ai se conseguiu se não eu mando um email... descobri como matar esse processo.
Quando tu dá create ele te retorna o tipo Client : Whatsapp
Essa classe tem uma propriedade: Page
Essa propriedade tem o método: Page.browser(); -- te retorna o navegador, que tem o pid do chromiun/chrome.exe

A solução foi... declarei uma variável e dei chamei esse método assim:

`let browser;
browser = Whatsapp.page.browser();
browser.close();`

**Comment by MatheusIbarra** [comment]
Infelizmente quando eu fecho, o backend crasha...

**Comment by diogolimas** [comment]
alguma novidade sobre isso? como resolveu? o bot sempre cria processos novos do chrome, sem, no entanto, fechar o antigo.
