### ISSUE TITLE
Venom not working on server

### ISSUE THREAD

**Issue by Pezhvak** [orkestral/venom#167]
i tried on ubuntu 18, centos 7 and centos 8, no matter what this is what I'm getting:

```
Chrome not found, using chromium
TypeError: Cannot read property 'onMessage' of undefined
    at start (/root/test2/test.js:13:10)
    at /root/test2/test.js:7:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
✓ Checking for updates
⠼ Waiting...
```

**Comment by Pezhvak** [comment]
found the problem!
it should be run with a non-root user, also you might need to install rxjs
`npm i --save rxjs`

**Comment by luizfeer** [comment]
same problem here

**Comment by Pezhvak** [comment]
@luizfeer try running your index.js from where package.json is, and also remember to not run it by a user which sudo privileges

**Comment by Pezhvak** [comment]
@luizfeer try running your index.js from where package.json is, and also remember to not run it by a user with sudo privileges

**Comment by krarrobo1** [comment]
Same problem here :(

**Comment by luizfeer** [comment]
> Same problem here :(

I solved! :100: 
https://github.com/orkestral/venom/issues/187#issuecomment-700012737

**Comment by yuniordaga** [comment]
> same problem here
> ![image](https://user-images.githubusercontent.com/3594167/94296641-894d8880-ff39-11ea-8ef4-b8cbcd122755.png)
> non-root user, and install rxjs :/

install the Chrome and Chromium , and verify than there are in /usr/bin else install them

**Comment by yuniordaga** [comment]
> found the problem!
> it should be run with a non-root user, also you might need to install rxjs
> `npm i --save rxjs`

what is the rxjs? , what does this?

**Comment by yuniordaga** [comment]
Hello friend , I don't understand ,why is this?
![image](https://user-images.githubusercontent.com/71469982/107654765-f5166080-6c50-11eb-8c5b-8f9fa09ce8b1.png)
it isn't create folder tokens , and when I give it "ctrl+c" , fineshed but when I start it again , I have than scanner again 
how can I fix this? :/

**Comment by yuniordaga** [comment]
> Hello friend , I don't understand ,why is this?
> ![image](https://user-images.githubusercontent.com/71469982/107654765-f5166080-6c50-11eb-8c5b-8f9fa09ce8b1.png)
> it isn't create folder tokens , and when I give it "ctrl+c" , fineshed but when I start it again , I have than scanner again
> how can I fix this? :/
I solved it  : 
1 - I must be root : sudo su
2.-edit the script then execute in line command : node index.js --> edit index.js : 
     const venom = require('venom-bot');
        venom
              .create (
                   browserArgs: ['--no-sandbox'] //only add this in the script
                 )

ref: https://github.com/puppeteer/puppeteer/issues/3698#issuecomment-504648941
obs:make sure you have google-chrome installed : ls -l /usr/bin/google-chrome else you install it
good day! :D
