### ISSUE TITLE
venom for Deno pls :((

### ISSUE THREAD

**Issue by Heryson1616** [orkestral/venom#1671]
**This is not a problem!**

I looked through the issues list and didn't find anything related to Deno.

> For those who don't know, Deno is a JavaScript runtime created by the creator of Node, and in my honest opinion, it's much better than Node, but it's very recent and that's why it has few modules.

I would like to ask you to try to create a version for Deno, because it does not have any module for interacting with whatsapp-web, venom would be a pioneer in this sector. I can't stand the slowness of Node anymore, this is affecting my work =[

Advantages of using Deno:
- [x] Faster than Node;
- [x] More optimized than Node;
- [x] Runs TypeScript natively;
- [x] It is much more secure than Node;
- [x] Supports ES6;
- [x] It's a cute dinosaur;

Thank you very much for your attention :)

**Comment by orkestral** [comment]
Thanks for the suggestion, let's do it.

**Comment by Sunf3r** [comment]
Hello, I would like to know if there is a Venom for Deno branch or repository, so I can help with the development =]
