### ISSUE TITLE
Puxar dados

### ISSUE THREAD

**Issue by Fernandosousa1998** [orkestral/venom#1674]
Alguém poderia me ajudar? 

Estou puxando os dados do número de telefone a partir de um arquivo json. Isto estou conseguindo fazer...

Agora estou tentando na mensagem, puxar o nome da pessoa, para poder enviar mensagem personalizada, porém não estou conseguindo.

**Comment by LucasMdosAnjos** [comment]
Acho que essa lib não te atende nesse caso sugiro procurar outra

**Comment by Fernandosousa1998** [comment]
Consegui fazer. Muito Obrigado. Só concatenar a messagembody com o nome.

**Comment by Fernandosousa1998** [comment]
Problema solucionada.
Só concatenar a messagembody com o nome.
