### ISSUE TITLE
Hanged in "Checking is logged..." while launching [ARM64 | Chromium]

### ISSUE THREAD

**Issue by truekasun** [orkestral/venom#1675]
## Description

Everything works fine until the point "Checking is logged..." and does not proceed beyond that. (No further errors displayed)

**NOTE:**

1. The CPU architecture is **ARM64**
2. This issue is **not** available in venom-bot@[3.1.12](https://github.com/orkestral/venom/releases/tag/v3.1.12)
3. I have manually installed Chromium using ```sudo apt install chromium-browser``` while ```yarn install```
4. There is an error stating "executablePath" is undefined. I have been able to fix that by hardcoding the chromium path in ```node_modules/venom-bot/dist/controllers/browser.js | Line: 233 and  276```

## Environment

- **Venom version(s):** [4.0.0 - 4.0.11]
- **Browser:** Chromium 101.0.4951.64 snap
- **OS:** Ubuntu 20.04.4 LTS (ARM64)
- **Node version:** v16.15.0

## Steps to Reproduce

1. Install venom-bot
5. Start the bot

## Log Output

```
info:     [Techie] Waiting... checking the browser...
info:     [Techie:browser] Check chromium....
info:     [Techie:browser-total] Checking the total bytes to download!
info:     [Techie:browser] Chromium Finished result
info:     [Techie:browser-total] Chromium completed result
info:     [Techie] Error chromium: TypeError: Cannot read properties of undefined (reading 'executablePath')
info:     [Techie] Browser successfully opened
info:     [Techie] checking headless...
info:     [Techie] headless option is active, browser hidden
info:     [Techie] Checking page...
info:     [Techie] Page successfully accessed
[instance: Techie]: Checking is logged...
```

## Your Code

```
await venom.create({session:'Techie', useChrome: false}).then((client) => {
    _client = client;
})
.catch((error) => {
    console.log(error);
});
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/278469/169696336-7b93f5bf-1308-4510-a504-7c68c6c8fe45.png)

**Comment by orkestral** [comment]
Thank you for joining our community, happy. We are currently fixing this bug, our new version will be released soon.

**Comment by orkestral** [comment]
**Fix in version 4.1.0**

**Comment by truekasun** [comment]
@orkestral Thank you for the update.
I have updated the package and tested the functionality but unfortunately, the issue is still there.

![image](https://user-images.githubusercontent.com/278469/171562903-221ceea6-e012-42a0-9096-7fa3d953c483.png)

If you require additional information on the issue, feel free to ask me.

**Comment by truekasun** [comment]
@orkestral The bot is working fine on AMD64 architecture, both Windows and Ubuntu. This issue is only occurring on ARM64 architecture.

**Comment by truekasun** [comment]
@orkestral New observation: When I turned off multidevice (multidevice: false) it works fine. The issue must be connected to the Multi-Device option.
