### ISSUE TITLE
Erro ao enviar mensagens!!!

### ISSUE THREAD

**Issue by Fernandosousa1998** [orkestral/venom#1676]
Venom 4.0.11

Error:
/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));

Alguém passando por esse problema, se resolveu, poderia compartilhar a solução?

**Comment by Guilherme-j10** [comment]
O mesmo erro esta acontecendo comigo. e também certas vezes quando vou me conectar este erro aparece, muito provavelmente é algo relacionado ao puppeteer, em casos como esse é de se desconfiar de que o próprio whatsapp fez alguma modificação em sua estrutura HTML.

````
Error: Evaluation failed: i 
````

**Comment by orkestral** [comment]
**Fix in version 4.1.0**
