### ISSUE TITLE
Is there any reason for using puppeteer ?

### ISSUE THREAD

**Issue by Allu9221** [orkestral/venom#1677]
Hi, I wanted to implement this feature in prod, but your library is internally using puppeteer which is a heavy one and also utilizes 1GB RAM in prod. could you please answer the below questions :

1) why are you using puppeteer, instead you can directly connect through WebSocket with WhatsApp servers?
2) will venom handle when there are huge hits in prod?

**Comment by orkestral** [comment]
Thank you for joining our community, happy. We are currently fixing this bug, our new version will be released soon.

**Comment by orkestral** [comment]
We have superchats that use socket, if you want to hire just get in touch.
