### ISSUE TITLE
How to handle client Object instance outside the then() block/ How to deploy this to DigitalOcean Cloud

### ISSUE THREAD

**Issue by siddmegadeth** [orkestral/venom#1688]
## How to handle client Object instance outside the then() block/ How to deploy this to DigitalOcean Cloud

This is not a bug but a generic question. not all of our code uses async functions. since the code utilized Promises while initializing Venom then why not return it Instance and use it across the App built

**Comment by dev-guidolin** [comment]
> ## How to handle client Object instance outside the then() block/ How to deploy this to DigitalOcean Cloud
> This is not a bug but a generic question. not all of our code uses async functions. since the code utilized Promises while initializing Venom then why not return it Instance and use it across the App built

Any resolution?
