### ISSUE TITLE
Client.restartService(); with problem

### ISSUE THREAD

**Issue by Guilherme-j10** [orkestral/venom#1696]
The restartService and killServiceWorker methods have problems, I don't even need to go into much detail here because you just have to try to use them for some error to pop. many other methods are buggy a lot of people report issues here in the repo but no one ever responds. I follow other libs and none of them are as abandoned as this one. The feeling is that this project was abandoned, at least for the free version that I've tested so far.

error output for the two methods mentioned above.

```
- Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
- node_modules\venom-bot\dist\lib\wapi\wapi.js:1:73178)
```

**Comment by Pawan-Dev-Pizone** [comment]
is it still not fixed ? ... as I am still facing this problem .
