### ISSUE TITLE
Como rodar no droplet?

### ISSUE THREAD

**Issue by Juuhz** [orkestral/venom#17]
Criei um chatbot e estou querendo subir a aplicação para um servidor ubuntu, porém não consigo startar o projeto:

![image](https://user-images.githubusercontent.com/7996030/84579844-d69d5400-ada7-11ea-8f0c-d50b456a4433.png)

Consegue me dar uma luz?

Já fiz a instalação das dependências do `puppeteer`.

**Comment by orkestral** [comment]
precisa rodar como usuário, não como root

**Comment by Juuhz** [comment]
Funcionou \o/ 

Coloquei o `PM2` para deixar o processo ligado 24hs.

Para ficar 100% só falta tirar a dependência do uso do Celular.

Quer que eu documente esse processo de deixar o bot em um servidor rodando 24hs? Posso mandar um Pull Request pro `readme`.
