### ISSUE TITLE
client.getSessionTokenBrowser() return empty object

### ISSUE THREAD

**Issue by jhaineymilevis** [orkestral/venom#1710]
## Description
Hello, i am getting empty object on client.getSessionTokenBrowser() method. Token folder is created but i can not get session object to save it.
[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jhaineymilevis** [comment]
hi! this was closed but this not have 30 days

**Comment by NicolasFelippe** [comment]
I'm having the same problem, windows 10, node 14.x, use chromium

**Comment by jhaineymilevis** [comment]
@NicolasFelippe have you found any solution?

**Comment by NicolasFelippe** [comment]
No, I'm using whatsapp-web.js and I leave the token saved in the default project folder. I found it simpler to implement multi-session with this library.

**Comment by jhaineymilevis** [comment]
@NicolasFelippe thanks, i will try that library

**Comment by Deblancd** [comment]
This issue is not fixed yet

**Comment by jhaineymilevis** [comment]
not fixed
