### ISSUE TITLE
Sessions with error

### ISSUE THREAD

**Issue by Guilherme-j10** [orkestral/venom#1712]
## Description

When i start the application with the session enabled the browser open normaly, but sometimes the qrcode dont show, so i exposed the browser instance and whatsapp page version is showed and the application can't send the qrcode to my frontend.

## Environment

- **Venom version: 4.1.0

## Log Output

without log

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/55926786/172161481-20e9e2d4-baf0-40be-b159-eaaf3cdff3b7.png)

**Comment by alexnobrega18** [comment]
Quando sair a nova versão, como faz para atualizar? Tenho versão SONIC-PRO
