### ISSUE TITLE
SendImage / SendFile not working

### ISSUE THREAD

**Issue by ono77** [orkestral/venom#1718]
## Description

WAPI.SendImage is not sending images

## Environment

Tested in Chrome console, calling the function:

WAPI.sendImage('imgBase64','333333333333@c.us', 'filename', 'caption')

## Log Output

[[PromiseState]]: "rejected"
[[PromiseResult]]: TypeError: Cannot read properties of undefined (reading '0') at u (<anonymous>:1:25584)
message: "Cannot read properties of undefined (reading '0')"
stack: "TypeError: Cannot read properties of undefined (reading '0')\n    at u (<anonymous>:1:25584)"
[[Prototype]]: Error

**Comment by abdullah-zaydi** [comment]
I encountered the same issue. But it's working fine after this update.
Thank you for helping.

**Comment by acognigni-evotecnia** [comment]
Same issue with sendFile

**Comment by gabrielaz318** [comment]
I'm also having problems with sendFile.

**Comment by acognigni-evotecnia** [comment]
#1719 should (in theory) resolve this. however I've been unable to replicate the issue on my test environment so i can't test if it works

**Comment by arbisyarifudin** [comment]
> Hi guys the fix proposed by limshengli works, I have retested the SendImage and everything works regularly. 👍

how to fix bro.. are we just only update the venom or edit it manually in node_modules?

**Comment by sergioxdev** [comment]
Hi @arbisyarifudin

i manually edited the wapi.js file in node_modules
node_modules/venom-bot/dist/lib/wapi/wapi.js
row 1 column 25578
for the SendImage and it works

**Comment by acognigni-evotecnia** [comment]
can confirm that this fixed it

**Comment by arbisyarifudin** [comment]
> Yep @sergioxdev you're right. You can either unminify `wapi.js` and change `.models[0]` to `._models[0]` on line:1007 or you simply goto row 1 column 25578 and change `.models[0]` to `._models[0]`.
> 
> file path: node_modules/venom-bot/dist/lib/wapi/wapi.js

Woaah.. It's work! Thanks a lot, @sergioxdev & @abdullah-zaydi ! That's really helpful!

**Comment by gabrielaz318** [comment]
> Yep @sergioxdev you're right. You can either unminify `wapi.js` and change `.models[0]` to `._models[0]` on line:1007 or you simply goto row 1 column 25578 and change `.models[0]` to `._models[0]`.
> 
> file path: node_modules/venom-bot/dist/lib/wapi/wapi.js

Thanks!

**Comment by marlos7** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot
