### ISSUE TITLE
statusFind Callback not working

### ISSUE THREAD

**Issue by abdullah-zaydi** [orkestral/venom#1720]
## Description

The statusFind callback on venom.create is not working fine. I found a workaround of that by simply adding null coalescing to this.session everywhere in initializer.js file.
I don't know if this is the right way to do that.

## Environment

- **Venom version(s):** [latest]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. Windows 10]
- **Node version:** [e.g. Node 17.2.0]

## Steps to Reproduce

Simply create an instance with ```venom.create``` and add the QR Callback and statusFind callback and it will start throwing this exception.

## Log Output

TypeError: Cannot read properties of undefined (reading 'session')
    at create (node_modules\venom-bot\dist\controllers\initializer.js:91:50)
    at Socket.<anonymous> (MyProject/index.js:95:37)
    at Socket.emit (node:events:390:28)       
    at Socket.emitUntyped (node_modules\socket.io\dist\typed-events.js:69:22)
    at node_modules\socket.io\dist\socket.js:465:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

## Code

```
socket.waClient = await create(
                "sessionName",
                // QR Callback
                (base64Qr, asciiQR, attempts, urlCode) => {
                    var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
                        response = {};

                    if (matches.length !== 3) {
                        return new Error('Invalid input string');
                    }

                    response.type = matches[1];
                    response.data = new Buffer.from(matches[2], 'base64');
                },
                (statusGet, sessionName) => {
                     // exception here
                      console.log(sessionName);
                },
                {
                    logQR: false,
                    useChrome: false
                },
                undefined,
                (browser, waPage) => {
                    console.log('Browser PID:', browser.process().pid);
                }
            );
```

**Comment by henrybastos** [comment]
Apparently I fixed it just replacing every `this.session` to just `session`, referring to the variable `session` defined at line 70 (`let session  = 'session';`).

I don't know about the trouble it may cause in general as I don't know where this `session` variable is used throughout the library, but as I tested, it worked just fine.
