### ISSUE TITLE
Venom works with Docker Container?

### ISSUE THREAD

**Issue by Adllers** [orkestral/venom#1724]
When i use venom in my local machine, it works perfectly, but when i try to use with Docker container, the Venom is not stable and not work! 
Somebody use Docker with Venom?

**Comment by acognigni-evotecnia** [comment]
i have not. but when submitting an issue please be more specific. what doesnt work? do you have logs?

when you first create an issue it come preloaded with a bunch of suggested data useful for poeple helping you. please fill that instead of deleting it

**Comment by pedroinbezerra** [comment]
At the company I work for, we use Venom with docker perfectly. Works well.
