### ISSUE TITLE
loadAndGetAllMessagesInChat not working gives n.loadEarlierMsgs is not a function

### ISSUE THREAD

**Issue by qazgal1** [orkestral/venom#1730]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. Windows 10]
- **Node version:** [Node 16.15.1]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Your Code
// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: true // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });
  
async function start(client) {
    console.log("papa")
    const allMessages = await client.loadAndGetAllMessagesInChat(
      '972507157096@c.us'
    );    console.log(allMessages)
    console.log("mama")
  };

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.
![Screenshot from 2022-06-10 17-12-34](https://user-images.githubusercontent.com/103256078/173084790-711b2c45-c12c-40ca-adb6-f15d26e28011.png)

**Comment by macleysousa** [comment]
try
`
                        client.loadAndGetAllMessagesInChat('972507157096@c.us').then((data)=>{
                            console.log(data);                            
                        }).catch(() => { })
`

**Comment by qazgal1** [comment]
returns empty but not gives error

**Comment by macleysousa** [comment]
but is there any conversation in the chat?

**Comment by qazgal1** [comment]
yes

**Comment by qazgal1** [comment]
I checked with multiple chats and all returned empty

**Comment by macleysousa** [comment]
this function only loads new messages

**Comment by qazgal1** [comment]
ohhhh thanks!!
so what function loads all messages?

**Comment by macleysousa** [comment]
`
 client.getAllMessagesInChat('00000000000@c.us', true, false).then((data) => {
                console.log(data);
            });
`

**Comment by qazgal1** [comment]
i checked with new messages and its steal returned nothing

**Comment by qazgal1** [comment]
and 

> `client.getAllMessagesInChat('00000000000@c.us', true, false).then((data) => { console.log(data); });`

that's only gave me the last seven messeges

**Comment by qazgal1** [comment]
> `client.getAllMessagesInChat('00000000000@c.us', true, false).then((data) => { console.log(data); });`

and when I ran it the second time gave me only the last messages

**Comment by group2tts** [comment]
loadEarlierMsgs is not a function
there are solutions ?

**Comment by group2tts** [comment]
#1758

**Comment by marlos7** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot
