### ISSUE TITLE
getMe() function doesnt work

### ISSUE THREAD

**Issue by B6sh** [orkestral/venom#1732]
## Description

I cant use the fucntion (getMe()), it reutrns an error 

## Environment

- **Venom version(s):** [4.2.0]
- **Browser:** [Chromium 102]
- **OS:** [Windows 11]
- **Node version:** [Node 16]

## Steps to Reproduce

1. create a new session
2. add `client.getMe()` to the start function

## Log Output

```
$ node venom.js
Unable to load the sleep module (no animations available)



 /\\\      /\\\ /\\\\\\\\\\  /\\\\\     /\\\    /\\\\\\\\    /\\\      \\\\
 \/\\\     /\\\ \/\\\_____/  \/\\\ \\\  \/\\\  /\\\_____/\\\ \/\\\ \\ \\ \\\
   \/\\\   /\\\  \/\\\        \/\\\ /\\\ \/\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
    \/\\\  /\\\   \/\\\\\\\\\\ \/\\\  /\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
      \/\\\ \\\    \/\\\_____/  \/\\\ \/\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
       \/\\\\\\     \/\\\        \/\\\ \ /\\\ \\\ \/\\\    \/\\\ \/\\\  \\\  \\\
        \/_/\\\      \/\\\\\\\\\\ \/\\\  \/_\\\\\\ \/_/\\\\\\\\\  \/\\\  \\\  \\\
          \/__/       \/________/  \/_/    \/____/    \/_______/   \/_/ \/_/ \/_/



info:     https://orkestral.io - official site!

info:     [session-name] Waiting... checking the browser...
info:     [session-name] Browser successfully opened
info:     [session-name] checking headless...
info:     [session-name] headless option is disabled, browser visible
info:     [session-name] Checking page...
info:     [session-name] Page successfully accessed
✓ [instance: session-name]: Connected
TypeError: client.getMe is not a function
    at start (C:\Users\ALyas\Desktop\Projects\TESTING STUFF\Node.js.env\venom.js:19:12)
    at C:\Users\ALyas\Desktop\Projects\TESTING STUFF\Node.js.env\venom.js:13:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Code
`// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: true // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
    client.getMe()
    .then(res => console.log(res))
    .catch(err => console.error("ERROR", err))
}`

**Comment by igiul667** [comment]
I also couldn't access the GetMe function, could have been useful to fix another issue.
