### ISSUE TITLE
DeleteMessageMe(); don't working

### ISSUE THREAD

**Issue by Guilherme-j10** [orkestral/venom#1742]
## Description

Ao utulizar o método que deleta um conjunto de mensagem ou uma mensagem especifica o venom retorna um erro.

## Environment

- **Venom version(s):** 4.2.0

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55926786/173677082-1d03f574-3730-4b33-a82e-8a4145169064.png)

## Log Output

![image](https://user-images.githubusercontent.com/55926786/173677173-c5400f9b-04c4-4c34-a929-dc1d673e1256.png)

**Comment by acognigni-evotecnia** [comment]
i have a very similar issue with deleteMessageAll(). in my case the issue is on wapi.js line 1 char 49063, while OP's is on line 49448

**Comment by igiul667** [comment]
Same issue with deleteMessageAll() and deleteMessageMe()
