### ISSUE TITLE
sendButton retornando erro

### ISSUE THREAD

**Issue by kennyroger2010** [orkestral/venom#1744]
Description
Utilizando o recurso sendButtons conforme exemplo da documentação é retornando um erro.

Environment
Venom version(s): [4.1.0]
Browser: [Chrome Version 102.0.5005.63 (64-bit)]
OS: [Windows Server 2016 Datacenter]
Node version: [Node v16.13.2]
Steps to Reproduce
Utilizado mesmo exemplo da documentação
// Send Messages with Buttons Reply
const buttons = [
{
"buttonText": {
"displayText": "Text of Button 1"
}
},
{
"buttonText": {
"displayText": "Text of Button 2"
}
}
]
await client.sendButtons(req.body.phone + '@c.us', '👋 ' + req.body.message, buttons, 'Description')
.then((result) => {
console.log('Result: ', result); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});

Log Output
Error when sending: {
me: {},
to: {
fromMe: true,
remote: {
server: 'c.us',
user: '5527900000000',
_serialized: '[5527900000000@c.us](mailto:5527900000000@c.us)'
},
id: 'M4WYKULJQCRNM4ECH5T8',
_serialized: 'true_5527900000000@c.us_M4WYKULJQCRNM4ECH5T8'
},
erro: true,
text: null,
status: 'ERROR_UNKNOWN',
result: null
}

**Comment by kennyroger2010** [comment]
> the SendButton still with error?

yes

**Comment by ElismarPrado** [comment]
I try others bots like: **whatsapp-web.js** and **wa-automate-nodejs**, all have error sending buttons.

**Comment by danieldavilaids** [comment]
> I try others bots like: **whatsapp-web.js** and **wa-automate-nodejs**, all have error sending buttons.

try with **wppconnect**.

**Comment by ElismarPrado** [comment]
Thanks @danieldavilaids, i tested **wppconnect** and all functions are work fine, I finally managed to send buttons.
until now i think wppconnect is better than venom-bot.

**Comment by tmandinyenya** [comment]
Anyone who managed to send buttons with venom please assist

**Comment by igiul667** [comment]
Same issue here. Checking similar issues I noticed that this problem occured when using multi-device beta but now that is not beta anymore and from my understanding it can't be disabled. Idk if this helps
