### ISSUE TITLE
Issue with autoClose

### ISSUE THREAD

**Issue by effer89** [orkestral/venom#175]
When we let autoClose enable, or we kill using the process that has not been authenticated with whats and try create another session of venom, ```client``` keeps returning ```undefined``` even if we authenticate properly

```venom.create('sales').then(client => {...})```

"venom-bot": "^2.0.4"

btw: Amazing bot guys!

**Comment by joaosouz4** [comment]
try like this
```
clients['marketing'] = await venom.create('marketing', 
    (base64Qr) => {
        exportQR(base64Qr, "marketing-qrcode.png");
    }, 
    undefined,
    OPTIONS
).catch((erro) => console.log(erro));
```

**Comment by effer89** [comment]
> try like this
> 
> ```
> clients['marketing'] = await venom.create('marketing', 
>     (base64Qr) => {
>         exportQR(base64Qr, "marketing-qrcode.png");
>     }, 
>     undefined,
>     OPTIONS
> ).catch((erro) => console.log(erro));
> ```

Thanks for the answer, I am saving each session in separate variables like you shown, but no still lucky :(

**Comment by wellcoj** [comment]
You could try to delete or unset the variable after autoclose, in the status callback you can get this event.

`
.create(
    'sessionName',
    (base64Qrimg, asciiQR) => {
      console.log('Terminal qrcode: ', asciiQR);
      console.log('base64 image string qrcode: ', base64Qrimg);
    },
    //Here you can get the status, if autocloseCalled then, unset your var
    (statusSession) => {
      console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled
    },
    {
      //Your options
    }
  )
`

**Comment by joaosouz4** [comment]
a correction was made that I believe will solve this problem, try to update and simulate the error again, if it happens open a new issue, please.
