### ISSUE TITLE
Como obter uma mensagem enviada para o BOT via GET method?

### ISSUE THREAD

**Issue by fredzolio** [orkestral/venom#1771]
Estou com muita dificuldade em obter essa requisição!!

**Comment by ArmandoTL** [comment]
> Estou com muita dificuldade em obter essa requisição!!

pode mostrar o codigo e o que está tentando fazer?

**Comment by ArmandoTL** [comment]
Cara não entendi o codigo onde você ta usando get? E outra coisa a função const chatsAllNew = getAllChatsNewMsg(); parece está com problema no codigo deles.

**Comment by fredzolio** [comment]
> Cara não entendi o codigo onde você ta usando get? E outra coisa a função const chatsAllNew = getAllChatsNewMsg(); parece está com problema no codigo deles. getAllChatsNewMsg grupos e outras tambem.

Obrigado por tentar me ajudar.
Eu consegui resolver meu problema, escrevi um código que integra o bot com o DialogFlow, daí ele lê as mensagens e dentro do Dialog eu programei para ele enviar via POST tudo que é recebido no bot. Portando consigui resolver meu problema.
