### ISSUE TITLE
The documentation is no longer avaliable

### ISSUE THREAD

**Issue by RenatoCesarF** [orkestral/venom#1779]
## Description

I tried to enter in the documentation website but it gives me an 404 error.
the website is: https://orkestral.github.io/venom/index.html
## Environment

- **Browser:** [Safari]

## Additional context / Screenshot
<img width="1280" alt="Screen Shot 2022-06-28 at 07 44 04" src="https://user-images.githubusercontent.com/62253156/176170419-7c83e393-825f-40c1-9eee-b0f160fd30bb.png">

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lucasbastianik** [comment]
+1
