### ISSUE TITLE
How to delete a message locally and the other end.?

### ISSUE THREAD

**Issue by fquero47** [orkestral/venom#178]
Im trying to use the function `client.deleteMessage('000000000000@c.us', message.id.toString(), false);` but with the boolean option in true or false, the function does exactly the same. just delete the message for me, it does not revoke the message. Could you help me out with this issue please ?

**Comment by edgardmessias** [comment]
@fquero47 , Couldyou post the code that you create the  `message` variable?

**Comment by fquero47** [comment]
> @fquero47 , Couldyou post the code that you create the `message` variable?

`await client.sendText(groupIds.conductores['conductores fundadores'], MensajePres).then( async (messageId)=>{

      setTimeout(async ()=>{

        await client.deleteMessage(message.from, messageId.toString(), false);

    }, 15000);
 });`

**Comment by edgardmessias** [comment]
Could you try this, please?

```ts
await client.deleteMessage(message.from, (messageId as any).to._serialized, false);
```

**Comment by fquero47** [comment]
Thanks to @edgardmessias it worked like this:
`await client.deleteMessage(message.from, messageId.to._serialized, false);`
