### ISSUE TITLE
Send Image sends like a file

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#1784]
## Description

Images is send like a attachment.... 
i am using de sendImageFromBase64 method

![image](https://user-images.githubusercontent.com/25329333/176902638-0c068384-d593-4e4d-af22-79bd102da76f.png)

## Environment

- **Venom version(s):** 4.2.0

**Comment by jesusvalverde** [comment]
Base64 Header must wrong.. Have you try sendFile ? await client.sendFile(url.to,file , 'filename', send.txt);

**Comment by MrR1pp3r** [comment]
> Base64 Header must wrong.. Have you try sendFile ? await client.sendFile(url.to,file , 'filename', send.txt);

Yes.. I share some screenshot
I use sendFile & sendFIleFromBase4, both not working
![sameerror](https://user-images.githubusercontent.com/48425460/182049869-fdb7b8f1-89be-4780-85e1-e3fa32a115c7.png)
![errorcode](https://user-images.githubusercontent.com/48425460/182049875-b1fd818f-0872-4c82-a92d-5ca1da6a753c.png)
