### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by matheusm821** [orkestral/venom#179]
![image](https://user-images.githubusercontent.com/60859810/94085868-a79f7100-fddf-11ea-9955-26785d3fb6bd.png)

**Comment by matheusm821** [comment]
I'm having this error when trying to start venom

**Comment by ahmadarif** [comment]
yeah, I have the same problem. using v1.6.0 and v2.0.4

**Comment by IsaacDSC** [comment]
I'm having problem starting the application, whats problem?? help peoples

**Comment by igortrust** [comment]
The same here! help us!!

**Comment by bhavya32** [comment]
this is the same error received if the wapi is not compiled from ts to js. Try the following 

npm run build:wapi

**Comment by igortrust** [comment]
> this is the same error received if the wapi is not compiled from ts to js. Try the following
> 
> npm run build:wapi

I tried that too, it didn't work :/

**Comment by leobevi** [comment]
Same here!

**Comment by thiagovasconcellos** [comment]
@jonalan7 just submitted a new version to solve this problem. I was looking into the "injectApi" function trying to figure it out, but no luck.  Update to version 2.0.5 and you will be good to go!

**Comment by m0w4hhed** [comment]
thanks for update

**Comment by leobevi** [comment]
Thanks..!!

**Comment by igortrust** [comment]
> @ jonalan7 acaba de enviar uma nova versão para resolver este problema. Eu estava olhando para a função "injectApi" tentando descobrir, mas sem sorte. Atualize para a versão 2.0.5 e você estará pronto para ir!

Tks so much!!

**Comment by jonalan7** [comment]
**bug fixed**
