### ISSUE TITLE
WAPI.checkNumberStatus function return undefined status

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#1790]
`WAPI.checkNumberStatus` method returns undefined status due to `Store.checkNumberBeta.queryExists(id)` function throw exception `Uncaught TypeError: e.isLid is not a function`.

**Comment by rafahlobo** [comment]
I got the same error.

**Comment by ono77** [comment]
I’ve same error too

**Comment by rafahlobo** [comment]
People, I fix it change the method name:

replace it:

Store.checkNumberBeta.queryExists

for it:

Store.checkNumberBeta.queryPhoneExists

**Comment by luccafabro** [comment]
Same error too

**Comment by felipeescher** [comment]
> People, I fix it changing the method name:
> 
> replace it:
> 
> Store.checkNumberBeta.queryExists
> 
> for it:
> 
> Store.checkNumberBeta.queryPhoneExists

this erros was locking venom when sending messages too. I created a pull request with your correction that also works for me

**Comment by limshengli** [comment]
Hi @rafahlobo, the `Store.checkNumberBeta.queryPhoneExists` function does return result, but the function doesn't accept the WhatsApp ID with country code. For example, 601XXXXXXXX@c.us (60 is the country code) should be a valid WhatsApp user ID, but `Store.checkNumberBeta.queryPhoneExists` function returned null, whereas 01XXXXXXXX@c.us returned result, but 01XXXXXXXX@c.us is not a valid WhatsApp user ID.

Previous `Store.checkNumberBeta.queryExists` function accept 601XXXXXXXX@c.us, not 01XXXXXXXX@c.us.

**Comment by nicoroms** [comment]
> > People, I fix it changing the method name:
> > replace it:
> > Store.checkNumberBeta.queryExists
> > for it:
> > Store.checkNumberBeta.queryPhoneExists
> 
> this erros was locking venom when sending messages too. I created a pull request with your correction that also works for me

I tried, but is not working for me. It says that my number doesn't exists. 
![image](https://user-images.githubusercontent.com/57744706/178009251-3ac4a55a-79f0-4616-a2ba-7052a7610fbe.png)

**Comment by jrrcdev** [comment]
Fix: https://github.com/orkestral/venom/pull/1794

**Comment by Jonalan** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot
