### ISSUE TITLE
Stop after 1 or 2  text  send  stops...

### ISSUE THREAD

**Issue by jesusvalverde** [orkestral/venom#1792]
## Description

You send one Hi and recive the answer...but stops there...

## Environment

- **Venom version(s):** 4.2.0
- **OS:**  Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1080-aws x86_64)
- **Node version:** v14.20.0
- 
have several server.. and all where working

## Steps to Reproduce

const venom = require('venom-bot');

venom
  .create({
    session: 'session-name', //name of session
    multidevice: true // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

**Comment by nicoroms** [comment]
I have the same error, it seems to be something related to puppeteer or some update from whatsapp.

**Comment by anjardev** [comment]
same error

**Comment by DevDefault** [comment]
Same error

**Comment by luccafabro** [comment]
See the last pull request from [felipeescher], is a palliative solution, it work for me.

**Comment by anexa-digital** [comment]
Same error.

**Comment by acognigni-evotecnia** [comment]
> See the last pull request from [felipeescher], is a palliative solution, it work for me.

Pull Request id #1791

**Comment by nicoroms** [comment]
> > See the last pull request from [felipeescher], is a palliative solution, it work for me.
> 
> Pull Request id #1791

I tried, but is not working for me. It says that my number doesn't exists. 
![image](https://user-images.githubusercontent.com/57744706/178009251-3ac4a55a-79f0-4616-a2ba-7052a7610fbe.png)

**Comment by luiz-limber** [comment]
See the last pull request from [felipeescher], is a palliative solution, it work for me.

**Comment by jrrcdev** [comment]
Fix: https://github.com/orkestral/venom/pull/1794

**Comment by nicoroms** [comment]
> Fix: #1795

Thanks! Is working for me now!

**Comment by marlos7** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot
