### ISSUE TITLE
Error when trying to access the page: "https://web.whatsapp.com"

### ISSUE THREAD

**Issue by manish-snappe** [orkestral/venom#1797]
I have version v4.0.12-alpha.0 of venom-bot installed. It was working well earlier. But now its giving error

Error when trying to access the page: "https://web.whatsapp.com"

I looked at previous issues and as per comments there, the issue was resolved. I also tried to look for and delete tokens folder. but that too didnt help. Any ideas ?

Cheers
Manish

**Comment by iamkunal9** [comment]
Try deleting tokens folder :)

**Comment by iamkunal9** [comment]
> I have version v4.0.12-alpha.0 of venom-bot installed. It was working well earlier. But now its giving error
> 
> Error when trying to access the page: "https://web.whatsapp.com"
> 
> I looked at previous issues and as per comments there, the issue was resolved. I also tried to look for and delete tokens folder. but that too didnt help. Any ideas ?
> 
> Cheers Manish

Deleting the tokens folder and re scanning the qr solves this issue :)

**Comment by iamkunal9** [comment]
> I have version v4.0.12-alpha.0 of venom-bot installed. It was working well earlier. But now its giving error
> 
> Error when trying to access the page: "https://web.whatsapp.com"
> 
> I looked at previous issues and as per comments there, the issue was resolved. I also tried to look for and delete tokens folder. but that too didnt help. Any ideas ?
> 
> Cheers Manish

Try a complete reinstall, this issue was also occur in mine but reinstalling the venom-bot using the specific installation method solves the problem and i also deleted the tokens because after reinstalling the web.whatsapp.com not reachable error was showing
