### ISSUE TITLE
client crash without error after sending 2nd text message

### ISSUE THREAD

**Issue by AlirezaDadrass** [orkestral/venom#1798]
Hi
I'm struggling with client.sendText for a week and I couldn't find any solution.
My problem is when I send first message everything is fine but when I send second message process goes lost without any exception or terminating program! and this does not happen just for send message. all client methods die after calling them (I tried all of them). 
finally, I reached Line 120 in file sender.layer.js:
`      const result = await this.page.evaluate(({ to, content }) => {
                return WAPI.sendMessage(to, content);
            }, { to, content });`
All my breakpoint hit before this line but after calling this function nothing happens! and my server can't return response to client. 
please help me
Thanks

**Comment by AlirezaDadrass** [comment]
So, what I have to do right now?

**Comment by JEAN-HELSING** [comment]
> Hi I'm struggling with client.sendText for a week and I couldn't find any solution. My problem is when I send first message everything is fine but when I send second message process goes lost without any exception or terminating program! and this does not happen just for send message. all client methods die after calling them (I tried all of them). finally, I reached Line 120 in file sender.layer.js: ` const result = await this.page.evaluate(({ to, content }) => { return WAPI.sendMessage(to, content); }, { to, content });` All my breakpoint hit before this line but after calling this function nothing happens! and my server can't return response to client. please help me Thanks

Hi, use the @wppconnect-team/wppconnect dependency

**Comment by luiz-limber** [comment]
See this pull request from [felipeescher] #1792, is a palliative solution, it work for me.

**Comment by renandecarlo** [comment]
@renenucci @ViniciusFH it seems latest-version became an ESM module, which was updated in a recent venom commit.
You can use my repo for installation for now, I've downgraded it: https://github.com/renandecarlo/venom

**Comment by adisoe** [comment]
i try to use patch from https://github.com/jrrcdev/venom/tree/patch-4 and downgrade the dependencies
npm i github:icemanbsi/venom
