### ISSUE TITLE
"Create" function returning "false | Whatsapp"

### ISSUE THREAD

**Issue by thiagovasconcellos** [orkestral/venom#180]
Create function has a validation if the browser fails.

```js
if (!browserFail) {
            // Wait til inside chat
            var IsLog = await isInsideChat(waPage).toPromise();
            if (IsLog == false) {
              return false;
            }
            if (statusFind) {
              statusFind('qrReadSuccess');
            }
            spinnies.succeed(`${session}-auth`, {
              text: 'Compilation Mutation',
            });
          }
```

Problem is, since "create" has no default return signature, TypeScript exports the method with 2 possible returns: "False | Whatsapp"

Is there a problem if you guys change this "return false" for a simple "throw new Error" or even a spinner error?
It's so annoying to manually change this every time I upgrade the package.

**Comment by joaosouz4** [comment]
You can send a pull request to fix this
