### ISSUE TITLE
SEND BUTTONS "status": "ERROR_UNKNOWN",

### ISSUE THREAD

**Issue by LuizVeloso10** [orkestral/venom#1800]
## Description

SEND BUTTONS NOTWORKING

## Environment

- **Venom version 4.2
- **Browser:** Versão 87.0.4280.66
- **OS:** [ Windows 10]
- **Node version: v14.15.1

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

"response": {
        "me": {},
        "to": {
            "fromMe": true,
            "remote": {
                "server": "c.us",
                "user": "557388218366",
                "_serialized": "557388218366@c.us"
            },
            "id": "R5IUF7RVI90AHLPLI75S",
            "_serialized": "true_557388218366@c.us_R5IUF7RVI90AHLPLI75S"
        },
        "erro": true,
        "text": null,
        "status": "ERROR_UNKNOWN",
        "result": null
    }
}
```
If relevant, paste all of your Log Output
```

app.post('/send-button', async (req, res) => {
    const buttons = [
      {buttonId: 'id1', buttonText: {displayText: 'SIM'}, type: 1},
      {buttonId: 'id2', buttonText: {displayText: 'NÃO'}, type: 1}
    ]
    await client
        .sendButtons( '557388218366@c.us', 'VOCE ME AMA?', buttons, 'Description optional')
        .then((result) => {
          res.status(200).json({
            status: true,
            response: result
    
          })
        })
        .catch((erro) => {
          res.status(200).json({
            status: false,
            response: erro
    
          })
        });
     
   })

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Abuzar1047** [comment]
I am getting this same error from months. is this fixed now ?

**Comment by godraxsz** [comment]
> 
You can use wppconnect-team/wppconnect

https://github.com/wppconnect-team/wppconnect
