### ISSUE TITLE
client.getHostDevice() return all params with null value

### ISSUE THREAD

**Issue by bruno1pb13** [orkestral/venom#1802]
## Description

let info = await client.getHostDevice()

info => 

```json
{
    id: null,
    email: null,
    description: null,
    statusConnection: 'CONNECTED',
    ....
}
```

## Environment

- **Venom version(s): 4.0.11
- **OS: Ubuntu 20.04
- **Node version: 16.13

## Your Code

```
details = await client.getHostDevice()

obj = {
    name: name,
    state: "connected",
    details: details,
    client: client,
    socket: socket
}
sessionManager().changeState(obj)
```

No warning is printed on console

**Comment by arbisyarifudin** [comment]
I'm facing same issue here.

**Comment by Jonalan** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot

**Comment by gvargas1404** [comment]
I have the same problem with the latest version of venom (4.2.0), the "getHostDevice" method returns an object with null properties. 
{
  id: null,
  email: null,
  description: null,
  statusConnection: 'CONNECTED',
  businessHours: { timezone: null },
  pushname: null,
  website: null,
  formattedTitle: null,
  categories: null,
  displayName: null,
  isBusiness: null,
  imgUrl: null,
  imgFull: null,
  previewEurl: null
}

help pls

**Comment by CollapsedMetal** [comment]
Any news on this?
