### ISSUE TITLE
Failed to send text

### ISSUE THREAD

**Issue by cristian-eng** [orkestral/venom#1803]
## Description

Whatsapp returns number does not exist, and crashes

## Environment

- **Venom version(s):** 4.2.0
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** LINUX
- **Node version:** 16.14.0

## Steps to Reproduce

clientWhats.sendText("5500000000@c.us", "Test").then((result) => {
      resolve({ IsSuccess: true, dados: result }); //return object success
 })

## Log Output

{
        "me": {},
        "to": "5575xxxxxxxx@c.us",
        "erro": true,
        "text": "The number does not exist",
        "result": null
    }

The number does not exist >>> but the number exists and working

**Comment by vitorsbgs** [comment]
I have the same problem when I try to send a text message to unregistered contacts in my list.

**Comment by adisoe** [comment]
i try to use patch from https://github.com/jrrcdev/venom/tree/patch-4 and downgrade the dependencies
npm i github:icemanbsi/venom

**Comment by Jonalan** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot

**Comment by eldevanjr** [comment]
see this > https://github.com/orkestral/venom/pull/1795#issuecomment-1182645064

**Comment by anexa-digital** [comment]
This fork seems to work https://github.com/jonalan7/Hydra-bot
