### ISSUE TITLE
After running sendText, no functions work

### ISSUE THREAD

**Issue by can1871** [orkestral/venom#1805]
After running sendText, no functions work, not even onmessage.

venom version v4.2.0
node version v16.15.0

**Comment by adisoe** [comment]
i try to use patch from https://github.com/jrrcdev/venom/tree/patch-4 and downgrade the dependencies
npm i github:icemanbsi/venom

**Comment by can1871** [comment]
@adisoe thanks. I will try it.

**Comment by Jonalan** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot

**Comment by eldevanjr** [comment]
see this > https://github.com/orkestral/venom/pull/1795#issuecomment-1182645064

**Comment by cristian-eng** [comment]
> @adisoe thanks. I will try it.

not work for me ...

execute npm i github:icemanbsi/venom

and what next step ?

**Comment by OtavioCostaLima** [comment]
Is there an earlier version that works?

**Comment by cristian-eng** [comment]
I was using 4.0.9 , but this one crashed too

**Comment by renandecarlo** [comment]
> > @adisoe thanks. I will try it.
> 
> not work for me ...
> 
> execute npm i github:icemanbsi/venom
> 
> and what next step ?



> > > @adisoe thanks. I will try it.
> > 
> > 
> > not work for me ...
> > execute npm i github:icemanbsi/venom
> > and what next step ?
> 
> doesn't work for me either.

Try `npm i github:renandecarlo/venom`

**Comment by can1871** [comment]
I applied @renandecarlo 's changes manually, it worked for me. Thanks @renandecarlo

**Comment by mailonruan** [comment]
when I use npm i github:renandecarlo/venom, Cannot find module 'venom-bot' or its corresponding type declarations. @renandecarlo  help.

**Comment by DevCodeLabsBr** [comment]
I'm having the same problem, I've tried everything but I can't run, it sends the first message and crashes.

**Comment by can1871** [comment]
@mailonruan  @DevCodeLabsBr  
If you apply the changes made by @renandecarlo  to the wapi file in your own project, it works.

**Comment by alvacirjunior01** [comment]
I tried **`npm i github:renandecarlo/venom`** but it didn't work either. My problem is that after the first reply venom no longer sends messages

**Comment by w7br** [comment]
npm i github:renandecarlo/venom solved my problem

**Comment by anexa-digital** [comment]
This fork seems to work https://github.com/jonalan7/Hydra-bot
