### ISSUE TITLE
API Official ? 

### ISSUE THREAD

**Issue by cristian-eng** [orkestral/venom#1808]
This API is Oficial ? 

Is there any risk of the blocked number?

sending 3000 messages per month

**Comment by marcelovieirahonorio** [comment]
> This API is Oficial ?
> 
> Is there any risk of the blocked number?
> 
> sending 3000 messages per month


No, it's not. This API works like a "human" typing in the web client (browser).
I think this volume (3000) is not enough to be blocked, however, I suggest waiting at least 1 or 2 seconds between each send.
