### ISSUE TITLE
Error when sending: ( The number does not exist)

### ISSUE THREAD

**Issue by raynunes** [orkestral/venom#1810]
Olá.
Meu script vinha enviando mensagens normalmente após um período apresentou a seguinte mensagem:
Alguém tem uma dica?
me: {},
  to: '5585999495807@c.us',
  erro: true,
  text: 'The number does not exist',
  result: null

Versões:
express@4.18.1
venom-bot@4.0.10

**Comment by raynunes** [comment]
Senhores,

No meu caso o erro se dava que o cadastro do telefone estava sem o 9 no WhatsApp.

Obrigado.

**Comment by felipedamacenoteodoro** [comment]
I have the same problem, and the numbers exist.

**Comment by felipedamacenoteodoro** [comment]
Resolution.

I was using an old version of whatsapp on my mobile, I updated the mobile version and now it works again.

**Comment by geovanny1781** [comment]
I have same problem, some phone numbers send, but it is aleatory and other when I use 'sendText' method is loop infinity  , help please.

**Comment by anexa-digital** [comment]
This fork seems to work https://github.com/jonalan7/Hydra-bot
