### ISSUE TITLE
checkNumberStatus not working

### ISSUE THREAD

**Issue by santiagomarcos** [orkestral/venom#1817]
## Description

após mandar a consulta do numero o mesmo retorna error

## Environment

- **Venom version(s):**  4.2.0
- **Browser:**Chromium 85
- **OS:**centos 7.0
- **Node version:** node 16.13.2

## Log Output

```
If relevant, paste all of your Log Output
```

 const numero = 11953558283;
     //res.send(numero);
  // Check if the number exists
const chat = client.checkNumberStatus('55'+numero+'@c.us')
.then((result) => {
     res.send(result);
    console.log('Result: ', result); //return object success
}).catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
         res.send(erro);
});

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by anexa-digital** [comment]
This fork seems to work https://github.com/jonalan7/Hydra-bot
