### ISSUE TITLE
Error ReferenceError: WAPI is not defined

### ISSUE THREAD

**Issue by Lacqua-Developer** [orkestral/venom#182]
After update:

- Checking for updates
- Waiting...
GET /start?sessionName=LacquaZap 304 86.104 ms - -
┌───────────────────────────────────────────────────┐
│                                                                                                                                        │
│   There is a new version of Venom 1.6.0 ➜  2.0.5                                                          │
│   Update your package by running:                                                                               │
│                                                                                                                                       │
│   > npm update venom-bot                                                                                          │
│                                                                                                                                       │
└────────────────────────────────────────────────────┘
For more info visit: https://github.com/orkestral/venom/blob/master/UPDATES.md

- Checking for updates
- Waiting...
- Checking for updates
- Waiting...
- check headless
- Checking for updates
- Waiting...
- headless option is active, browser hidden
- Checking for updates
- Authenticating...
- headless option is active, browser hidden
session.status: isLogged
- Checking for updates
- Authenticated
- headless option is active, browser hidden
- Checking for updates
- Authenticated
- headless option is active, browser hidden
- Injecting Sibionte...
(node:27696) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:29)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:27)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (D:\projetos\LacquaBot\myzap\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WaitTask.rerun (D:\projetos\LacquaBot\myzap\node_modules\puppeteer\lib\DOMWorld.js:404:24)
  -- ASYNC --
    at ExecutionContext.<anonymous> (D:\projetos\LacquaBot\myzap\node_modules\puppeteer\lib\helper.js:94:19)
    at WaitTask.rerun (D:\projetos\LacquaBot\myzap\node_modules\puppeteer\lib\DOMWorld.js:404:72)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joaosouz4** [comment]
npm update venom-bot

**Comment by Lacqua-Developer** [comment]
I run "npm update venom-bot", but only run when uninstall Venom-Bot

npm uninstall venom-bot
after
npm install venom-bot

**Comment by Lacqua-Developer** [comment]
Now normal execution!
