### ISSUE TITLE
The number does not exist (sendText)

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#1822]
## Description

I have already updated whatsapp but this error still persists when executing the sendText command

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 4.2.0]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. Ubuntu/Windows]
- **Node version:** [Node 16 e Node 12.22.7]

## Steps to Reproduce

run command sendText

## Log Output

The number does not exist

## Print command

![image](https://user-images.githubusercontent.com/59453913/181773113-7f7d586e-2e55-4842-8e0f-1f55ba5267e1.png)

**Comment by lzzy12** [comment]
Hi, I am facing the same issue. any idea why is this happening? It works only if we send message to ourself. otherwise just gives number does not exist. I am on the latest version of whatsapp

**Comment by mohammadghs** [comment]
> ## Description
> 
> I have already updated whatsapp but this error still persists when executing the sendText command
> 
> [Description of the bug, When Issue Happens]
> ## Environment
> 
>     * **Venom version(s):** [e.g. 4.2.0]
> 
>     * **Browser:** [e.g. Chrome 87, Chromium 85]
> 
>     * **OS:** [e.g. Ubuntu/Windows]
> 
>     * **Node version:** [Node 16 e Node 12.22.7]
> 
> 
> ## Steps to Reproduce
> 
> run command sendText
> ## Log Output
> 
> The number does not exist
> ## Print command
> 
> ![image](https://user-images.githubusercontent.com/59453913/181773113-7f7d586e-2e55-4842-8e0f-1f55ba5267e1.png)


Phone number should start with the country code
