### ISSUE TITLE
Crashing the process after executing the sendText command.

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#1823]
## Description

Depending on the phone being used for the bot it is crashing when executing the sendText command, the first message goes but doesn't send any more later

## Environment

- **Venom version(s):** [4.2.0]
- **Browser:** [All]
- **OS:** [Windows 11/Ubuntu]
- **Node version:** [16, 12]

## Steps to Reproduce
Run the sendText command, after the first run it will no longer run

**Comment by Adllers** [comment]
In my case, the process chash when i use sendText, when i try to send a simple message
