### ISSUE TITLE
Como enviar butões usando Venom-Bot ou outras dependências 

### ISSUE THREAD

**Issue by renato425** [orkestral/venom#1826]
Bom, acho que a questão é auto-explicativa.

Como eu posso enviar botões usando Venom-Bot ou packages similares?

**Comment by DaniHRE** [comment]
Estou tendo a mesma dúvida, e está sendo difícil de resolver isso, tentei utilizando um método nativo da biblioteca porém não está funcionando corretamente. 😢

**Comment by nsggerson** [comment]
já foi corrigido o erro de envio de botão no venom?

**Comment by WeslleySantos-dev** [comment]
Também estou com esta dificuldade, vi que foi alterado a ordem porem a documentação não esta com a atualização. 
Segundo a documentação client.sendButtons(to, 'title', buttons,'subTitle')
atualmente client.sendButtons(phoneNumber, 'title', 'subTitle', buttons)
porem no console da o seguinte erro
 {to: '**************',
  erro: true,
  text: 'It is necessary to write a subtitle!',
  status: 404
  }

**Comment by edmagnini** [comment]
Com base em pesquisas na issue [#2418](https://github.com/orkestral/venom/issues/2418) se alterarmos o arquivo "node_modules\venom-bot\dist\lib\wapi\wapi.js" com a função  "(window.WAPI.sendButtons = async function (e, t, i, n)" para função "(window.WAPI.sendButtons = async function (e, t, n, i)" volta a funcionar
![image](https://github.com/orkestral/venom/assets/32701426/a230f3ad-72c8-47ea-b571-ddcce89a2a64)
Mas pelo que encontrei só funciona em whatsapp web e iOS.

**Comment by llDanielll5** [comment]
> Com base em pesquisas na issue [#2418](https://github.com/orkestral/venom/issues/2418) se alterarmos o arquivo "node_modules\venom-bot\dist\lib\wapi\wapi.js" com a função "(window.WAPI.sendButtons = async function (e, t, i, n)" para função "(window.WAPI.sendButtons = async function (e, t, n, i)" volta a funcionar ![image](https://private-user-images.githubusercontent.com/32701426/264765620-a230f3ad-72c8-47ea-b571-ddcce89a2a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzE1MzMsIm5iZiI6MTcxOTg3MTIzMywicGF0aCI6Ii8zMjcwMTQyNi8yNjQ3NjU2MjAtYTIzMGYzYWQtNzJjOC00N2VhLWI1NzEtZGRjY2U4OWEyYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIyMDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTEwN2ZkMWIxNzFjMDdjMWYyZWRmZWY4NzE1MzM3MTNiNTlhMjRkNzc5N2I1ZGNhYjI4ZjY0ZTU5MjIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7FjQV3iL963QjBUarxCzrZZcgkyn_GABfJ3ajTmz7A) Mas pelo que encontrei só funciona em whatsapp web e iOS.

pra o meu azar o meu já está na ordem (e,t,n,i). E agora só choro? kkkkk

**Comment by idelioofico** [comment]
> > Com base em pesquisas na issue [#2418](https://github.com/orkestral/venom/issues/2418) se alterarmos o arquivo "node_modules\venom-bot\dist\lib\wapi\wapi.js" com a função "(window.WAPI.sendButtons = async function (e, t, i, n)" para função "(window.WAPI.sendButtons = async function (e, t, n, i)" volta a funcionar ![image](https://private-user-images.githubusercontent.com/32701426/264765620-a230f3ad-72c8-47ea-b571-ddcce89a2a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzE1MzMsIm5iZiI6MTcxOTg3MTIzMywicGF0aCI6Ii8zMjcwMTQyNi8yNjQ3NjU2MjAtYTIzMGYzYWQtNzJjOC00N2VhLWI1NzEtZGRjY2U4OWEyYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIyMDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTEwN2ZkMWIxNzFjMDdjMWYyZWRmZWY4NzE1MzM3MTNiNTlhMjRkNzc5N2I1ZGNhYjI4ZjY0ZTU5MjIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7FjQV3iL963QjBUarxCzrZZcgkyn_GABfJ3ajTmz7A) Mas pelo que encontrei só funciona em whatsapp web e iOS.
> 
> pra o meu azar o meu já está na ordem (e,t,n,i). E agora só choro? kkkkk

Também rsrsrs...
