### ISSUE TITLE
SendButtons not work

### ISSUE THREAD

**Issue by iGuihP** [orkestral/venom#1830]
## Description

SendButtons is not working...

## Environment

- **Venom version(s):** [4.2.0
- **OS:** Ubuntu 22.04
- **Node version:** Node 16

## Log Output

```
Error when sending:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '*************',
      _serialized: '*************@c.us'
    },
    id: 'ZWPCZVXHGUECFAWNRUZN',
    _serialized: 'true_**************@c.us_ZWPCZVXHGUECFAWNRUZN'
  },
  erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',
  result: null
}
```

**Comment by orkestral** [comment]
#[dc417cb](https://github.com/orkestral/venom/commit/dc417cb2728561b2d6f8b8b640abd4de2b3cb2b6)

**Comment by orkestral** [comment]
#[f82b9b0](https://github.com/orkestral/venom/commit/f82b9b0e042d2f19c8338f0ddc0795aa04c1d529)
