### ISSUE TITLE
Removed index.d.ts from compiled package

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#1835]
## Description

index.d.ts was removed from the compiled package, my project uses typescript and the lack of these files affected its functioning,
In version 4.2.0 it was ok now in 4.2.2 this file is no longer present in the package

## Environment

- **Venom version(s):** [4.2.2]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [Windows 11, Ubutnu]
- **Node version:** [Node 16]

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/59453913/183411618-dcdc2a28-f09d-4889-8b39-eaa6a4b9eb67.png)

**Comment by orkestral** [comment]
#[272964a](https://github.com/orkestral/venom/commit/272964a200d83f832dd38fe1a2c43b01a7dad18e)
