### ISSUE TITLE
Client.sendText to groups has no body

### ISSUE THREAD

**Issue by kevinjoseph61** [orkestral/venom#1847]
## Description

Up until recently, when venom sends a message to a group chat no issues just like any other message but now it does not show the body/text of the message in the message object

## Environment

- **Venom version(s):** [4.2.3]
- **OS:** [Windows 10]
- **Node version:** [v16.15.0]

## Steps to Reproduce

1. Send a message to a group using venom client (client.sendText)
2. Read that message using a venom client listener (client.onMessage)
3. The message will not have a body/text

## Log Output
I have pasted relevant diffs for comparison in the same message sent via venom and when the user sends the same message to the group without venom. As seen there is no body/text attr
https://www.diffchecker.com/J71pEjjW  
Sending message to a contact directly is fine. Just sending to a group is the issue

**Comment by kevinjoseph61** [comment]
This works fine with latest updates closing this

**Comment by leanmarro** [comment]
i have the same problem too... someone know the solution?
