### ISSUE TITLE
Client still stop working after 2nd message, even with new changes.

### ISSUE THREAD

**Issue by joaocib** [orkestral/venom#1853]
## Description

Client stop working after 2nd message sent.

## Environment

- **Venom version(s):** v4.27
- **Browser:** Chromium
- **OS:** Windows 11
- **Node version:** v16

## Steps to Reproduce

1. Create client
2. Send message
3. Send another message.
4. All client functions stop working and message is not sent.

**Comment by daviladanielc** [comment]
@joaocib 
Forget this venom-bot is garbage.
The real and totally free with all functions: https://github.com/wppconnect-team/wppconnect

**Comment by joaocib** [comment]
> @joaocib Forget this venom-bot is garbage. The real and totally free with all functions: https://github.com/wppconnect-team/wppconnect

I am also using wppconnect and other libs... but I have some things in this lib, and my branch is working with venom 4.2.0. So, just in case they decide to fix it in recent versions I will be informed.

**Comment by orkestral** [comment]
after several tests we have not identified any problem related to the open issue
