### ISSUE TITLE
Evaluation failed: TypeError: r._find is not a function

### ISSUE THREAD

**Issue by jhaineymilevis** [orkestral/venom#1857]
## Description
i am getting this error on getHostDevice method
error Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
    at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
    at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
    at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Whatsapp.getHostDevice (/usr/src/app/node_modules/venom-bot/src/api/layers/host.layer.ts:347:12)

## Environment

- **Venom version(s):** 4.2.
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by orkestral** [comment]
use version node > 16

**Comment by antoniovalenzuela** [comment]
@orkestral 
node v16.16.0
venom-bot updated

error ocurrs to send wsp bussiness number

0|ventas  | Error: Evaluation failed: TypeError: r._find is not a function
0|ventas  |     at https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568548
0|ventas  |     at Generator.next (<anonymous>)
0|ventas  |     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66483)
0|ventas  |     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66694)
0|ventas  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66753
0|ventas  |     at Y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:117092)
0|ventas  |     at new y (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:37:109659)
0|ventas  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.01552bec6677c60ebdd8.js:2:66634
0|ventas  |     at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568914)
0|ventas  |     at H._query (https://web.whatsapp.com/bootstrap_qr.440594ca182cc155b985.js:75:568040)
0|ventas  |     at ExecutionContext._ExecutionContext_evaluate (/home/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
0|ventas  |     at runMicrotasks (<anonymous>)
0|ventas  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|ventas  |     at async ExecutionContext.evaluate (/home/bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
0|ventas  |     at async /home/bot/node_modules/venom-bot/dist/api/layers/sender.layer.js:120:28

**Comment by jhaineymilevis** [comment]
i have uypdate node v16.16 and same error

**Comment by jhaineymilevis** [comment]
![image](https://user-images.githubusercontent.com/8782191/184502341-f45b142d-54a9-4cc8-9534-b7eec45a6272.png)
![image](https://user-images.githubusercontent.com/8782191/184502352-634789dc-e23f-467a-ba2c-58dfdd0427a2.png)

**Comment by jhaineymilevis** [comment]
@orkestral this is not fixed yed
