### ISSUE TITLE
After Restart Script Does Not Get Anything

### ISSUE THREAD

**Issue by rapstar2004** [orkestral/venom#1889]
When you restart nodejs no features dont work. For example on message event doesn't work but send text works. I guess there are some changes in WhatsApp web .

**Comment by AlePro12** [comment]
Same here

**Comment by faradaytrs** [comment]
Same here

**Comment by devchn** [comment]
Same here

**Comment by luccafabro** [comment]
Same here

**Comment by joaovitor27** [comment]
Same here

**Comment by Divino67** [comment]
Same here. The function 'onMessage' apparently does not exist!

**Comment by joaovitor27** [comment]
#1895 pullrequest made in the newest version
