### ISSUE TITLE
Sending files to GROUP not working

### ISSUE THREAD

**Issue by dionesdf** [orkestral/venom#1896]
Hello guys, I`ve been trying to send files to a GROUP, but it`s not working.

I`m using this method:

await client
  .sendFile(
    '000000000000@c.us',
    'path/to/file.pdf',
    'file_name',
    'See my file in pdf'
  )
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

Can someone help me?

**Comment by pedropuppim** [comment]
+1

**Comment by John-Vinic** [comment]
Not work too last version
