### ISSUE TITLE
section by token for node api 

### ISSUE THREAD

**Issue by MgArreaza13** [orkestral/venom#19]
It's ready section by token!? For implementation?

Example

Path /login - > get Auth and response token 

Path /get-messages - > get messages by token in active session, 

Implementation in node server

**Comment by orkestral** [comment]
yes, install venom-bot, sessions for token, in folder token with file json

**Comment by MgArreaza13** [comment]
Any examples for implementation of this requirement?

**Comment by MgArreaza13** [comment]
Any examples for implementation of this requirement?

**Comment by MgArreaza13** [comment]
Like multiple router

Path :/login return token

Path: /send-message/:token - > send message to sesión token!?

**Comment by orkestral** [comment]
> Any examples for implementation of this requirement?

no example at the moment, if you find out how to do it, we will be very happy
