### ISSUE TITLE
Use Conventional Commits for commit message

### ISSUE THREAD

**Issue by edgardmessias** [orkestral/venom#190]
Use Conventional Commits for commit message. It is an easy way to generate changelog (I am working to do it with release-it)

English: https://www.conventionalcommits.org/en/v1.0.0/
Portuguese: https://www.conventionalcommits.org/pt-br/v1.0.0-beta.4/

For pull-request, I can create a workflow rule to check the commit message.

May we can use a tool like: https://github.com/commitizen/cz-cli

**Comment by joaosouz4** [comment]
I think this will be very good for the project.

**Comment by joaosouz4** [comment]
@jonalan7 @joedutra @orkestral
