### ISSUE TITLE
WAPI.loadAndGetAllMessagesInChat is not a function

### ISSUE THREAD

**Issue by lucaspaulino** [orkestral/venom#1908]
Hi! I would like to know why this error happens:
Error: Evaluation failed: TypeError: WAPI.loadAndGetAllMessagesInChat is not a function

 when I try to run this code below:
`await session.client.then(async (client) => {
          await client.loadAndGetAllMessagesInChat(number);
}`

The venom version is up to date, v4.3. The other functions run normally, only this one is causing the problem.

Any reason for this to occur?

**Comment by aislanspeedio** [comment]
I'm having the same problem!!!!

Bot, please open up the issue, wtf!!!
