### ISSUE TITLE
sendText for a group, it is returning error "The number does not exist". (the same number and the same code worked a month ago)

### ISSUE THREAD

**Issue by marciusbezerra** [orkestral/venom#1916]
## Description

sendText for a group, it is returning error "The number does not exist".

ps1: the same number and the same code worked a month ago!
ps2: works for some other numbers!
ps3: for security, the group number has been modified here

thanks!

## Environment

Venom: 4.3.0
Node: v16.14.0

## Steps to Reproduce

Just run the code below

## Log Output

```
{
  "me": {},
  "to": "550000000000-1500000000@g.us",
  "erro": true,
  "text": "The number does not exist",
  "status": 404,
  "result": null
}
```

## Code

```
await venomClient.sendText('550000000000-1500000000@g.us', 'TEST! PING..');
```

**Comment by canbal99** [comment]
Hi @marciusbezerra,
You can try to rollback to version 4.2.9
see https://github.com/orkestral/venom/issues/1878

**Comment by marciusbezerra** [comment]
> Hi @marciusbezerra,
> You can try to rollback to version 4.2.9
> see #1878

I had already done it and it continued the same

**Comment by canbal99** [comment]
That was a suggestion from https://github.com/orkestral/venom/issues/1878, and solved my exact same problem.
Sorry then :(

**Comment by marciodiasdeveloper** [comment]
+1

**Comment by pedropuppim** [comment]
+1

**Comment by sysupdate** [comment]
+1

**Comment by felippeantonachi** [comment]
+1

**Comment by marciusbezerra** [comment]
Dear, as there is no answer, I advise you to migrate to whatsapp-web.js, I have already tested it and it works well. and I'm already migrating.

**Comment by ecureuill** [comment]
Facing same problem on 4.3.6

**Comment by TangramBee** [comment]
> Facing same problem on 4.3.6

Facing same problem on 4.3.6
