### ISSUE TITLE
The number does not exist

### ISSUE THREAD

**Issue by coppo82** [orkestral/venom#1923]
on sendText i get "The number does not exist" just for some numbers ( italian prefix 328 ......  , 327 .... ) for other types of number prefix work fine.

All numbers i used for test work normally on whatsapp app and whatsapp web ( i mean the numbers exist and has whatsapp)

I use the 4.3.0 version .... tried also the 4.2.9 version ( same problem) 

## Environment

- **Venom version(s):** [4.3.0] 
- **OS:** [win 2016 Server]
- **Node version:** [ Node 16]

## Log Output

Error when sending:  {
  me: {},
  to: '327xxxxxxxxxx@c.us',
  erro: true,
  text: 'The number does not exist',
  status: 404,
  result: null
}

**Comment by leanmarro** [comment]
i have the same problem... someone know the solution?
