### ISSUE TITLE
When use multidevice = true and kill and start app, callbacks not working

### ISSUE THREAD

**Issue by rubensedanoc** [orkestral/venom#1924]
## Description

When ctrl-c app and run again and multidevices is set true, callbacks not working, for the first time working all fine, but por second and next times not working callbacks

## Environment

- **Venom version(s):** 4.3.0
- **Browser:** Chrome 105
- **OS:** macos 12.6
- **Node version:** 14.13.1

## Steps to Reproduce

1. run first time
2. scan qr
3. onmessage callback work fine
4. press ctrl-c
5. run again app
6. is connected because files sessions are found
7. onmessage callback is not working

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by acognigni-evotecnia** [comment]
+1
