### ISSUE TITLE
When sending buttons the title does not appear in whatsapp web. Displays Only the buttons in the message, but without the title.

### ISSUE THREAD

**Issue by suporteIQdeveloper** [orkestral/venom#1925]
## Description

     const buttons = [
        {
          "buttonText": {
            "displayText": "Option 1"
            }
          },
        {
          "buttonText": {
            "displayText": "Option 2"
            }
          }
        ]

      await client.sendButtons('000000000000@c.us', 'Any more questions?', buttons, "Choose an option!")
      .then((result) => {

      })
      .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
      });

## Environment

Venom version: 4.3.0
Browser: Chrome 105
OS: Windows 10
Node version: 16.16.0

**Comment by scatrus** [comment]
`[{
                buttonText: {displayText: 'texto'}, buttonId: 1, text: 'texto'
            }, {
                buttonText: {displayText: 'texto'}, buttonId: 2, text: 'texto'
            }]`
