### ISSUE TITLE
Image base64 from client message small

### ISSUE THREAD

**Issue by allanlisboaweb** [orkestral/venom#193]
When trying to capture the bse64 images of the return of the message sent it comes with very low quality[
<img width="746" alt="Captura de Tela 2020-09-28 às 14 26 22" src="https://user-images.githubusercontent.com/37181884/94465748-c5315980-0196-11eb-9b5a-93b858ac7631.png">
<img width="1054" alt="Captura de Tela 2020-09-28 às 14 26 35" src="https://user-images.githubusercontent.com/37181884/94465771-cbbfd100-0196-11eb-942c-45764c856b52.png">

](url)

**Comment by wellcoj** [comment]
Why don't you use the same base64 that you used to send the message?

**Comment by allanlisboaweb** [comment]
That was in the message received!!

**Comment by leobevi** [comment]
@allanlisboaweb, try this in client.onMessage

`   if (message.isMedia == true) {

        try {
            const buffer = await client.decryptFile(message); 
            let base64data = Buffer.from(buffer).toString('base64');
            let imagebase64 = 'data:'+message.mimetype+';base64,'+base64data;
			
        } catch (err) {
            console.error(err);
            console.log('Ocorreu um erro ao realizar decode64 do arquivo');
        }    
    } `
