### ISSUE TITLE
Client onMessage not working

### ISSUE THREAD

**Issue by paraisotech** [orkestral/venom#1939]
My bot doesn’t figure out any incoming messages, acts like nothing happened. I had another bot with an old session registered in venom working, but after logging out and started a new session, also stopped dealing with incoming messages. I’m using the onMessage method… does anyone having the same issue?

**Comment by paraisotech** [comment]
🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻
How can I know this has been solved? Venom has a active changelog here?

**Comment by paraisotech** [comment]
> Thank you for joining our community, happy. We are currently fixing this bug, our new version will be released soon.
> 
> Working with Love!

I answered a bot 🤦🏼‍♂️

**Comment by HenriquedCM** [comment]
I'm having the same issue.

**Comment by paraisotech** [comment]
Based on the last issues posted here, all of them had the same bot answer but not the developers team. I use another API: wppconnect, that is facing the sabe issue. Seems that whatsapp changed some json structure that the API is not recognizing.

**Comment by mjbcastro** [comment]
@HenriquedCM 

If you restart the server, you will have to log out of whatsapp web and read the QR Code again, every time you restart the server you will have to do this procedure. I was having the same problem

**Comment by paraisotech** [comment]
Worked for me @mjbcastro . Thank you!

**Comment by wandersonsousa** [comment]
@mjbcastro worked for me too

**Comment by gabriellemos197** [comment]
> @HenriquedCM
> 
> If you restart the server, you will have to log out of whatsapp web and read the QR Code again, every time you restart the server you will have to do this procedure. I was having the same problem

I tried this way, even scanning a new qr code, it keeps sending only one message and doesn't return anymore

**Comment by mjbcastro** [comment]
> > @HenriquedCM
> > If you restart the server, you will have to log out of whatsapp web and read the QR Code again, every time you restart the server you will have to do this procedure. I was having the same problem
> 
> I tried this way, even scanning a new qr code, it keeps sending only one message and doesn't return anymore

Sua versão está atualizada?

O meu continua funcionando da forma que mencionei acima, só envio para o grupo que não está funcionando ainda.

**Comment by gabriellemos197** [comment]
> > > @HenriquedCM
> > > If you restart the server, you will have to log out of whatsapp web and read the QR Code again, every time you restart the server you will have to do this procedure. I was having the same problem
> > 
> > 
> > I tried this way, even scanning a new qr code, it keeps sending only one message and doesn't return anymore
> 
> Sua versão está atualizada?
> 
> O meu continua funcionando da forma que mencionei acima, só envio para o grupo que não está funcionando ainda.

Não utilizo a última seção pois obtive outro problema ao passar a seção no .create, este é o erro que retorna:
TypeError: Cannot read properties of undefined (reading 'session')

Segue meu código abaixo:
![image](https://user-images.githubusercontent.com/45287054/195203134-556c9ce2-efaa-4ffa-89da-fadf4267cb54.png)

**Comment by anexa-digital** [comment]
Last npm package v4.3.0 keeps this issue.   
Try > npm i github:orkestral/venom
or     "dependencies": {
...
    "venom-bot": "github:orkestral/venom"
  }, 
  in package.json
  
  It worked  for me.

**Comment by gabriellemos197** [comment]
> Last npm package v4.3.0 keeps this issue. Try > npm i github:orkestral/venom or "dependencies": { ... "venom-bot": "github:orkestral/venom" }, in package.json
> 
> It worked for me.

worked the solution for OnMessage.

But this other error that I reported regarding the session in the creation of the client, still persists.

**Comment by HenriquedCM** [comment]
Worked for me. Thank you, @mjbcastro.

**Comment by mjbcastro** [comment]
Fiz algumas mudanças no meu código e agora está funcionando o onMessage mesmo depois de reiniciar o servidor node.

**Mudei o Venom Create para** 

venom
.create(
  'session-name',
  (base64Qr, asciiQR, attempts, urlCode) => {
    console.log(asciiQR); // Optional to log the QR in the terminal
    var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
      response = {};

    if (matches.length !== 3) {
      return new Error('Invalid input string');
    }
    response.type = matches[1];
    response.data = new Buffer.from(matches[2], 'base64');

    var imageBuffer = response;
    require('fs').writeFile(
      'qrcode.png',
      imageBuffer['data'],        
      'binary',      

      function (err) {
        if (err != null) {
          console.log(err);
        }
      }
    );
  },
  undefined,
  { logQR: false }
)
.then((client) => {
  start(client);
})
.catch((erro) => {
  console.log(erro);
}); 


**Adicionei na function start(client) o código avaixo:**


client.onStateChange((state) => {
      console.log('State changed: ', state);
      // force whatsapp take over
      if ('CONFLICT'.includes(state)) client.useHere();
      // detect disconnect on whatsapp
      if ('UNPAIRED'.includes(state)) console.log('logout');
    });


**E por fim exclui a instancia na pasta token.**

Até o momento não estou precisando mais desconectar e reconectar o Whatsapp.

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```

**Comment by syncdeck** [comment]
> > Thank you for joining our community, happy. We are currently fixing this bug, our new version will be released soon.
> > Working with Love!
> 
> I answered a bot 🤦🏼‍♂️

kkk happens to the best of us i still don't see changes have you ? with venom i mean

**Comment by paraisotech** [comment]
I moved to wppconnect.
The team is active and keeps the tool updated.

Em sáb., 7 de out. de 2023 às 16:02, Syncdeck Incorporated <
***@***.***> escreveu:
