### ISSUE TITLE
Filename duplicate extesion name

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#194]
Params
  fileData:  base64data
  fileName: 'P20070317471907.pdf',
  caption: '',
  sessionName: 'xxxx',
  number: 'xxxx'

Result
![image](https://user-images.githubusercontent.com/1323545/94512012-84484c00-024d-11eb-9ce8-405af2ae6de1.png)

Source code  sender.layer.ts  376
      var extension = path.split('.').pop();
      filename = filename + '.' + extension;

**Comment by wellcoj** [comment]
I guess it's the mimetype helper. What function are you using? 
Try to use sendFileFromBase64()

/**
   * Sends file
   * base64 parameter should have mime type already defined
   * @param to Chat id
   * @param base64 base64 data
   * @param filename
   * @param caption
   */
  public async sendFileFromBase64(
    to: string,
    base64: string,
    filename: string,
    caption?: string
  )

**Comment by joaosouz4** [comment]
in the **filename** you don't need to send the extension, just the file name, as the extension is captured automatically.
