### ISSUE TITLE
cannot find the functions folder 

### ISSUE THREAD

**Issue by Pawan-Kumar-J** [orkestral/venom#1948]
Cannot find the functions folder in path node_modules\venom-bot\dist\lib\wapi when downloaded from npm install but it exists in the lastest version of the repository in github.

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```
