### ISSUE TITLE
sendButton not send any response

### ISSUE THREAD

**Issue by luthfifadle** [orkestral/venom#1949]
## Description

I have an issue when select button option not reponse anything to bot

## Environment

- **Venom version(s):** 4.3.0
- **Browser:** Chrome
- **OS:** Windows 10
- **Node version:** Node 16

## Steps to Reproduce

1. Select an Option on sendButton

## Log Output

```
-
```

## Your Code

```
-
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/67321679/196911306-6a7483d0-24bf-48cf-9eb0-ce25d89ed362.png)

when i click the button, nothing happen to bot
have a solution for this issue?

**Comment by etc-tiago** [comment]
Same issue!

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```
