### ISSUE TITLE
CustomAgent & Browser Path

### ISSUE THREAD

**Issue by Gidraf** [orkestral/venom#195]
Hey everyone is there a way to add a custom agent and the browser path when creating the client

**Comment by antonioGabrielGomes** [comment]
Hi @Gidraf . Iam try to do it that way:  https://github.com/orkestral/venom/issues/196#issuecomment-701841332

**Comment by Gidraf** [comment]
@antonioGabrielGomes Thanks for the response but your comment doesn't solve my problem I would like to dynamically add custom browser user agent and browser path if possible.

**Comment by antonioGabrielGomes** [comment]
@Gidraf yes .. it's just an example.  I am improving it, at another time I add it here, maybe it will help.

**Comment by joaosouz4** [comment]
Browser Path yes, but CustomAgent no has this option yet. u can do a PR for this.
