### ISSUE TITLE
SendText working with problems

### ISSUE THREAD

**Issue by Adllers** [orkestral/venom#1954]
## Description

The function sendText work perfectly for some contacts but not work for others contacts. Some contacts can receive my messages and others can't do it.

## Environment

- **Venom version(s):** [4.3.0]
- **Node version:** [Node 12]

## Log Output

I attached the log

![sendTextNotWorkPerfectly](https://user-images.githubusercontent.com/26190577/198155475-dd1880a8-cd19-4e44-ac86-11de307500fa.jpg)

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```
