### ISSUE TITLE
Cannot read property 'isWidlike' of undefined is show again

### ISSUE THREAD

**Issue by luthfifadle** [orkestral/venom#1955]
## Description

in 29 Oct 2022. this error show again, before that date absolutly normal and no one solution in report issue #923 worked for me

## Environment

- **Venom version(s):** 4.30
- **Browser:** Chromium
- **OS:** Windows 10
- **Node version:** Node 16.16.0

## Steps to Reproduce

1. Running venom bot, then first time chat the bot show that error

## Log Output

err Error: Evaluation failed: TypeError: Cannot read property 'isWidlike' of undefined
    at Object.window.WAPI.window.WAPI.sendCheckType (C:\xampp\htdocs\wa_pasteur\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:31862)
    at Object.window.WAPI.window.WAPI.sendExist (C:\xampp\htdocs\wa_pasteur\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:33133)
    at Object.window.WAPI.window.WAPI.sendMessage (C:\xampp\htdocs\wa_pasteur\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:47248)
    at pptr://__puppeteer_evaluation_script__:2:29
    at ExecutionContext._ExecutionContext_evaluate (C:\xampp\htdocs\wa_pasteur\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\xampp\htdocs\wa_pasteur\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async C:\xampp\htdocs\wa_pasteur\node_modules\venom-bot\dist\api\layers\sender.layer.js:120:28

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/67321679/198958718-71749749-ad08-4630-8994-ed6765e78a46.png)

**Comment by etc-tiago** [comment]
Same issue!

**Comment by ZagrosDEV** [comment]
Same issue here. It was working till yesterday.

**Comment by chacalgbi** [comment]
Aqui tb....

**Comment by jackson-uti** [comment]
Aqui também mesmo problema.

**Comment by marcelovieirahonorio** [comment]
Same issue...

**Comment by luthfifadle** [comment]
maybe this can help, i change venom bot version to 4.0.0 and worked. but have some bug when send list menu

**Comment by jackson-uti** [comment]
Bom pessoal, ativei o debug do venom e no console peguei um erro do wppconnect/wa-js que estava causando uma falha na carga das funções na variavel window.Store. Atualizei o pacote com:
npm update @wppconnect/wa-js --save
E depois disso passou a funcionar.  Espero que possa ser de ajuda para mais alguém.

**Comment by joaovitor27** [comment]
> Bom pessoal ativo o debug do venom e no console peguei um erro do wpp/wa-js que estava conectado, uma falha na carga das funções na variavel window.Store. Atualizei o pacote com: npm update @wppconnect/wa-js --save E depois disso passou a funcionar. Espero que possa ser de ajuda para mais alguém.

Deu certo aqui também!

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```

**Comment by Bocapio** [comment]
> Bom pessoal, ativei o debug do venom e no console peguei um erro do wppconnect/wa-js que estava causando uma falha na carga das funções na variavel window.Store. Atualizei o pacote com: npm update @wppconnect/wa-js --save E depois disso passou a funcionar. Espero que possa ser de ajuda para mais alguém.

O mesmo problema voltou a acontecer ontem (versão 4.3.7) e essa solução funcionou novamente!
