### ISSUE TITLE
client.getHostDevice() not working / causes crash

### ISSUE THREAD

**Issue by omarmyousef** [orkestral/venom#1958]
## Description

using client.getHostDevice() is called, the client crashes

## Environment

- **Venom version(s):** [the latest github version ("venom-bot": "github:orkestral/venom" in package.json)]
- **Browser:** [included chromium version]
- **OS:** [Windows 10]
- **Node version:** [v18.0.0]

## Steps to Reproduce

1. create new project and implement client.getHostDevice();

## Log Output

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getMaybeMeUser')
    at window.WAPI.window.WAPI.getHost (...\project\node_modules\venom-bot\dist\lib\wapi\wapi.js:2362:47)
    at pptr://__puppeteer_evaluation_script__:1:13
```

## Your Code

```
just use "this.client.getHostDevice();" after creating the client
```

## Additional context / Screenshot

none

**Comment by orkestral** [comment]
solved #[54d5a7b](https://github.com/orkestral/venom/commit/54d5a7b2cf4aa9523dfe59efde8abed6418d9707)
new version 3.4.1 for update
```javascript
npm i venom-bot@latest
```
