### ISSUE TITLE
Not loading in ubuntu 20 raspberry pi 3

### ISSUE THREAD

**Issue by antonioGabrielGomes** [orkestral/venom#196]
Hi.  i can't load the token on the raspberry pi.  He waits and does not continue.  I leave Chrome disabled because it's just a terminal.

**Comment by antonioGabrielGomes** [comment]
`
const app = express()

app.set('view engine', 'ejs')

app.get('/', (req, res) => res.render('home'))

app.get('/launch',  (req, res) => {

   try {
        
        venom
            .create(
          'test',
          (base64Qr, asciiQR) => {
            console.log(asciiQR)

            base64Qr = base64Qr.replace('data:image/png;base64,', '');
            const imageBuffer = Buffer.from(base64Qr, 'base64');
            fs.writeFileSync('out.png', imageBuffer);


            const img = `${path.resolve(__dirname, '..')}/out.png`
                       
            res.setHeader('Content-disposition', `attachment; filename=${img}`)
            res.setHeader('Content-type', 'png')
            
            const filestream = fs.createReadStream(img);
            filestream.pipe(res)
            

          },
          undefined,
          { 
            useChrome: false,
            logQR: false,
            disableWelcome: true,
            autoClose: 120000
          }
        )


        /*
        const img = `${path.resolve(__dirname, '..')}/test-qr.png`
        const mimetype = mime.getType(img)
        
        res.setHeader('Content-disposition', `attachment; filename=${img}`)
        res.setHeader('Content-type', mimetype)
        
        const filestream = fs.createReadStream(img);
        filestream.pipe(res)
        */    

   } catch (error) {
       res.send(error)
   }

})



app.listen(3333)`

**Comment by bhavya32** [comment]
@antonioGabrielGomes useChrome:true.

**Comment by antonioGabrielGomes** [comment]
Thanks @bhavya32
