### ISSUE TITLE
getSessionTokenBrowser() returning empty object

### ISSUE THREAD

**Issue by AndersonVale** [orkestral/venom#1985]
After start a session, under the "then(async (client)" block, the getSessionTokenBrowser method returns "{}"

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):4.3.3
- **Browser:** Chrome / Chromiun
- **OS:** Ubuntu
- **Node version: various

**Comment by orkestral** [comment]
resolve with version 4.3.4 [afea4e4](https://github.com/orkestral/venom/commit/afea4e4fc3d9f065eb3e2e7ad93837a74ddc1924)
