### ISSUE TITLE
Tem como usar o bot para enviar uma lista de contatos?

### ISSUE THREAD

**Issue by DeLuca92** [orkestral/venom#199]
Eu tenho uma lista de contatos, mas estou com problemas para enviar, pois eu já "queimei" uns 6 chips :/.

Todos esses contatos querem receber as mensagens, mas o problema que o whats está pegando ele como bot/spammer e dai bane o numero.

E ficar comprando chip toda hora não é uma boa ideia :/

Valeu

**Comment by orkestral** [comment]
use a ferramenta https://smily.chat, ela e feita para não banir o número com várias métricas de uso

**Comment by DeLuca92** [comment]
Valeu, vou ver aqui.
Sera q eles tem um beta? Um teste?

**Comment by orkestral** [comment]
mano, acho que liberam 1 hora para testar, ao fazer o cadastro vai em suporte deles e pede 1 hora de teste fala que a orkestral indicou.

**Comment by DeLuca92** [comment]
Bale, vou falar lá valeu, brother
