### ISSUE TITLE
Stuck at waiting

### ISSUE THREAD

**Issue by chamel-arch** [orkestral/venom#2]
Hello, I try to make simple whatsapp bot, but I stuck at waiting, something wrong ? 

I'm using WSL 2 (Ubuntu 20.04).
![image](https://user-images.githubusercontent.com/65443284/84178792-34cbed80-aaaf-11ea-9e44-230dcc0be96d.png)

My app.js :
```
const venom = require('venom-bot');

venom.create("session-coba", {
                headless: true, // Headless chrome
                devtools: false, // Open devtools by default
                useChrome: true, // If false will use Chromium instance
                debug: false, // Opens a debug session
                logQR: true, // Logs QR automatically in terminal
                browserArgs: [''], // Parameters to be added into the chrome browser instance
                refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
          }).then((client) => {
                  start(client)
                }).catch(erro => console.log(erro))

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi') {
      client.sendText(message.from, 'Welcome Venom 🕷' );
    }
  });
}
```
Thanks

**Comment by orkestral** [comment]
new documentation, receive 2 params exemplo:

create('sessionName', qrCallback, statusFind, {
  headless: true, // Headless chrome
  devtools: false, // Open devtools by default
  useChrome: true, // If false will use Chromium instance
  debug: false, // Opens a debug session
  logQR: true, // Logs QR automatically in terminal
  browserArgs: [''], // Parameters to be added into the chrome browser instance
  refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
});

**Comment by chamel-arch** [comment]
Hi, Sorry. so yeah WSL not working somehow, but at windows machine it self is working.

**Comment by orkestral** [comment]
ok, Thank You!
