### ISSUE TITLE
 How to send to 'broadcast lists'?

### ISSUE THREAD

**Issue by WilliamTeixeira** [orkestral/venom#200]
I was able to send messages to a contact and a group perfectly, however, when sending to a 'broadcast lists', only the first contact receives the message. Is it possible to send to 'broadcast lists'?
I have a need to send to a list of 'broadcast lists'.
Thankful right now!😉

**Comment by daffigusti** [comment]
looking for the same function that can send message to broadcast list....

**Comment by joaosouz4dev** [comment]
it is not possible to do this by whatsapp web, and it is not possible to do any poison for now, but you can capture all your contacts and make a delay to send messages to all your contacts, but be careful with that
