### ISSUE TITLE
Evento onAddedToGroup não funciona

### ISSUE THREAD

**Issue by Moisa** [orkestral/venom#2005]
Quado anciono participande ao grupo, o evento não  esta sendo disparado.

[Description of the bug, When Issue Happens]

## Environment

Venom version(s): [e.g. 4.3.3]
Browser: [e.g. 107.0.5304.1075]
OS: [e.g. Windows 10]
Node version: [e.g. v16.15.1]

**Comment by orkestral** [comment]
test new version : 4.3.4 [afea4e4](https://github.com/orkestral/venom/commit/afea4e4fc3d9f065eb3e2e7ad93837a74ddc1924)

**Comment by Moisa** [comment]
Estou usando  esta versão:  4.3.4  eu havia informado a versao errada no post anterior
