### ISSUE TITLE
WAPI.checkNumberStatus returned Object with undefined value.

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#2022]
## Description

With the commit #8d89f6db, WAPI.checkNumberStatus returned undefined value:

## Environment

- **Venom version(s):** 4.3.6
- **Browser:** Microsoft Edge Chromium 107.0.1418.56
- **OS:** Windows 11
- **Node version:** Node 19.1.0

## Steps to Reproduce

1. call WAPI.checkNumberStatus(wid);

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/44156695/203706985-6e3e9d57-739c-42d8-9ba7-fc48ac3e148c.png)

**Comment by orkestral** [comment]
use new version 4.3.6, thank you!
