### ISSUE TITLE
Send Buttons and sendListMenu breaks the Chat

### ISSUE THREAD

**Issue by JoaoAlvarez** [orkestral/venom#2023]
## Description

When sending a message of type sendButtons or sendListMenu, the chat breaks and does not show any message.

## Environment

- **Venom version(s):**  4.3.3, 4.3.5,4.3.6
- **Browser:**  Chrome 87
- **OS:** OSX 12.5.1
- **Node version:** Node 16.18.0

## Steps to Reproduce

1. send any button message
2. payload: `{
	"phone": "xxxx",
	"title": "Bem vindo",
	"message": "xxxxxxx",
	"buttons": [
		{
			"buttonId": "1",
			"buttonText": {
				"displayText": "xxxx"
			}
		},
		{
			"buttonId": "2",
			"buttonText": {
				"displayText": "xxx"
			}
		},
		{
			"buttonId": "3",
			"buttonText": {
				"displayText": "xxxxx"
			}
		}
	]
}`

## Your Code

```
await client.sendButtons(messageAttr.phone, data.title, data.buttons, data.message);
```

## Additional context / Screenshot

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/10214657/203772947-9577ef2b-ccf9-4c6b-b9c0-bc40d3b5847d.png">

**Comment by etc-tiago** [comment]
Same error.
@JoaoAlvarez the buttons show on app or the buttons are showing with blank space?
I can't fix the button text and I think this might be related to it not displaying in the web.

![IMG_8299](https://user-images.githubusercontent.com/33164463/203789508-030f9f5d-31bd-4281-90e3-5154c2448784.jpg)

**Comment by JoaoAlvarez** [comment]
> Same error. @JoaoAlvarez the buttons show on app or the buttons are showing with blank space? I can't fix the button text and I think this might be related to it not displaying in the web.
> 
> ![IMG_8299](https://user-images.githubusercontent.com/33164463/203789508-030f9f5d-31bd-4281-90e3-5154c2448784.jpg)

With me, in the app it doesn't show the message sent and in the web it breaks the chat and doesn't show any more messages, as well as in the attached print

**Comment by orkestral** [comment]
verify documentation in : https://doc.orkestral.io/venom

**Comment by etc-tiago** [comment]
@orkestral the docs says to use:
```
let buttons = [
   {
     "buttonId": "1",
     "buttonText": {
       "displayText": "Button 1"
       }
     },
   {
     "buttonId": "2",
     "buttonText": {
       "displayText": "Button 2"
       }
     }
   ]
```

but only work with (starting today):
```
let buttons = [
   {
     "id": "1",
     "text": "Button 1"
   },
   {
     "id": "2",
     "text": "Button 2"
     }
   ]
```

**Comment by JoaoAlvarez** [comment]
> verify documentation in : https://doc.orkestral.io/venom

Page no found

**Comment by orkestral** [comment]
https://docs.orkestral.io/venom
