### ISSUE TITLE
sendText not returning "id"

### ISSUE THREAD

**Issue by Pedro-Coimbra** [orkestral/venom#2024]
## Description

sendText not returning "id" in the most recent version

## Environment

- **Venom version(s):** 4.3.6
- **Browser:**  Chrome 107
- **OS:** Ubuntu 20.04.3 LTS
- **Node version:** 14.17.3

## Steps to Reproduce

I have this code on my app and used to work fine, but now the sendText is not returning the "id", this is normal now or is a change in the recent versions? In 4.3.3 was working normally.
![image](https://user-images.githubusercontent.com/35116761/203788260-bd8d845a-57d2-4f21-b8be-815d01cc6276.png)

The return from sendText that I'm getting:
![image](https://user-images.githubusercontent.com/35116761/203787452-f47618d5-3b33-4258-847e-9a9cecf13d26.png)

## Additional context / Screenshot

I'm starting my client with this code:

```
const client = await venom.create(
	process.env.ACCOUNT,
	async (base64Qrimg) => {
		await Account.updateOne({
			_id: process.env.ACCOUNT
		}, {
			$set: {
				token: null,
				phone: null,
				pid: process.pid
			}
		});
		socket.emit('qrcode', base64Qrimg, account.name);
	},
	(statusGet) => {
		socket.emit('session_status', statusGet);
		if (statusGet == 'chatsAvailable' || statusGet == 'isLogged' || statusGet == 'qrReadSuccess') {
			setState('CONNECTED');
		}
	},
	{
		logQR: false,
		disableWelcome: true,
		disableSpins: true,
		multidevice: true,
		autoClose: false,
		//headless: process.env.NODE_ENV != 'development'
	},
	(!account.multiDevice && account.token) ? account.token : undefined
);

**Comment by orkestral** [comment]
after testing we did not find any problems, do not open this issue again
