### ISSUE TITLE
function create not working

### ISSUE THREAD

**Issue by mitydev** [orkestral/venom#203]
Função .create().then(result) result está retornando undefined, e a aplicação fica Waiting

**Comment by jonalan7** [comment]
**Would you like to show your code?**

**Comment by mitydev** [comment]
const venom = require('venom-bot');

venom
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

**Comment by mitydev** [comment]
![image](https://user-images.githubusercontent.com/62960678/95751461-059fd580-0c75-11eb-9275-1f67c9f6daab.png)

**Comment by mitydev** [comment]
client variable just return undefined

**Comment by jonalan7** [comment]
**I tested it here and it's working normally, try to await the functions.**
**Are you using a newer version?**

```
const venom = require('venom-bot');

venom.create().then((client) =>{ 
  start(client);
}).catch((erro) => {
  console.log(erro);
});

async function start(client) {
  await client.onMessage(async (message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      await client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```
**if it still doesn't work try desistalizing and installing venom again**

```
npm uninstall venom
npm i --save venom
```

**Comment by Oxicode** [comment]
> **I tested it here and it's working normally, try to await the functions.**

Me too.

@mitydev version nodeJS?

**Comment by mitydev** [comment]
yes

**Comment by mitydev** [comment]
![WhatsApp Image 2020-10-19 at 15 07 45](https://user-images.githubusercontent.com/62960678/96494616-f85a8c00-121c-11eb-9201-45e92fea49fe.jpeg)

**Comment by mitydev** [comment]
I have chrome, and chromium installed, any suggestions to resolve this?

**Comment by mitydev** [comment]
#187
