### ISSUE TITLE
New and reply messages not call .onMessage

### ISSUE THREAD

**Issue by etc-tiago** [orkestral/venom#2031]
## Description

I develop a large automation bot and after a few versions I notice that new messages do not call the .onMessage method.

Run a test with the code from README.md and I confirmed that it is something related to venom.

I started to investigate, but I've been reading the source code for 4 hours and I haven't found where the possible error could be.

## Environment

- **Venom version(s):** 4.3.5
- **Browser:** Firefox 107, Chrome 107
- **OS:**  OSX 12.14, Ubuntu 20
- **Node version:** Node 16, Node 18

## Your Code
As the README.MD
```ts
const venom = require("venom-bot");

venom
  .create({
    session: "dev", //name of session
    multidevice: true, // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    console.log({ message });
  });
}
```

**Comment by rajatdhoot123** [comment]
Same `onMessage` method not working on message reply

**Comment by guh0rzd** [comment]
The .sendButtons functions doesn't working too, the "displaytext" content don't show

**Comment by etc-tiago** [comment]
@guh0rzd try https://github.com/orkestral/venom/issues/2023#issuecomment-1326539461

**Comment by guh0rzd** [comment]
Funcionou mano!! valeu, o problema ta sendo que o listen do venom (.onMessage) não identifica a resposta do botão....

**Comment by brunomanoel** [comment]
I have this same issue. The `onMessage` event is not triggered when a message is a reply or on new chats.

**Comment by all4conn-mariano** [comment]
I have this same issue. Posted in the Telegram group too!
I did this test and it returns false if the message is a reply , if it is a response I don't receive it!
            client.onMessage(async (message) => {
		console.log("Return Reply: ", await client.returnReply(message))
                console.log("Mensagem: ", message)

**Comment by imznx** [comment]
Any version that these functions are working correctly?

**Comment by all4conn-mariano** [comment]
> Any version that these functions are working correctly?

Yes, in version 4.3.3 Ok

**Comment by regis-amaral** [comment]
> Funcionou mano!! valeu, o problema ta sendo que o listen do venom (.onMessage) não identifica a resposta do botão....

O que você fez pra funcionar?

**Comment by regis-amaral** [comment]
> Funcionou mano!! valeu, o problema ta sendo que o listen do venom (.onMessage) não identifica a resposta do botão....

@guh0rzd o que fez para funcionar?

**Comment by etc-tiago** [comment]
> > Funcionou mano!! valeu, o problema ta sendo que o listen do venom (.onMessage) não identifica a resposta do botão....
> 
> @guh0rzd o que fez para funcionar?

https://github.com/orkestral/venom/issues/2031#issuecomment-1327621914

**Comment by leanmarro** [comment]
> Same `onMessage` method not working on message reply

same here

**Comment by guh0rzd** [comment]
> > Funcionou mano!! valeu, o problema ta sendo que o listen do venom (.onMessage) não identifica a resposta do botão....
> 
> @guh0rzd o que fez para funcionar?

Vc tem que trocar a sintaxe do componente botão que vc estiver criando, tenta criar o botão assim:
let botoes = [
    {
      "id": "1",
      "text": "opção 1",
      },
    
    {
      "id": "2",
      "text": "opção 2",
      },
  ];

**Comment by guh0rzd** [comment]
> > Any version that these functions are working correctly?
> 
> Yes, in version 4.3.3 Ok

Tem como voltar versão do Venom?

**Comment by regis-amaral** [comment]
> 
@guh0rzd, sim! 

[OPÇÃO 1] 
Dentro do arquivo package.json você precisa especificar a versão exata que quer usar, sem o ^
```
{
   //(...)
   "dependencies": {
     //(...)
      "venom-bot": "4.3.3" // sem ^
   }
}
```
Depois de especificar, delete a pasta node_modules e o arquivo package-lock.json
e execute o comando: `npm i`
Ele vai reinstalar todos os pacotes novamente.

[OPÇÃO 2] 
Acredito que também possa apenas desinstalar o venom e suas dependências:
```
npm uninstall -D venom-bot
```
e reinstalar novamente pela versão 4.3.3

```
npm i --save venom-bot@4.3.3
```

**Comment by leanmarro** [comment]
> Same `onMessage` method not working on message reply

try this file... replace wapi.js e run again
[new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)

**Comment by guh0rzd** [comment]
> > Same `onMessage` method not working on message reply
> 
> try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)

How to use that?

**Comment by leanmarro** [comment]
> > > Same `onMessage` method not working on message reply
> > 
> > 
> > try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> 
> How to use that?

(version 4.3.6), replace the content in wapi.js file. The txt file is a wapi.js with the changes wich work fine for me... just CTRL+A then CTRL+C in txt file and CTRL+A then CTRL+V in wapi.js file. try and run again.

**Comment by guh0rzd** [comment]
> > > > Same `onMessage` method not working on message reply
> > > 
> > > 
> > > try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> > 
> > 
> > How to use that?
> 
> (version 4.3.6), replace the content in wapi.js file. The txt file is a wapi.js with the changes wich work fine for me... just CTRL+A then CTRL+C in txt file and CTRL+A then CTRL+V in wapi.js file. try and run again.

Where´s "wapi.js"?

**Comment by guh0rzd** [comment]
> > > > > > Same `onMessage` method not working on message reply
> > > > > 
> > > > > 
> > > > > try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> > > > 
> > > > 
> > > > How to use that?
> > > 
> > > 
> > > (version 4.3.6), replace the content in wapi.js file. The txt file is a wapi.js with the changes wich work fine for me... just CTRL+A then CTRL+C in txt file and CTRL+A then CTRL+V in wapi.js file. try and run again.
> > 
> > 
> > Where´s "wapi.js"?
> 
> in your project, go to: node_modules/venom-bot/dist/lib/wapi/wapi.js

worked!! thanks

**Comment by leanmarro** [comment]
> 

de nada man

**Comment by leanmarro** [comment]
> > > > > > > Same `onMessage` method not working on message reply
> > > > > > 
> > > > > > 
> > > > > > try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> > > > > 
> > > > > 
> > > > > How to use that?
> > > > 
> > > > 
> > > > (version 4.3.6), replace the content in wapi.js file. The txt file is a wapi.js with the changes wich work fine for me... just CTRL+A then CTRL+C in txt file and CTRL+A then CTRL+V in wapi.js file. try and run again.
> > > 
> > > 
> > > Where´s "wapi.js"?
> > 
> > 
> > in your project, go to: node_modules/venom-bot/dist/lib/wapi/wapi.js
> 
> worked!! thanks

de nada man

**Comment by guh0rzd** [comment]
> > > > > > > > Same `onMessage` method not working on message reply
> > > > > > > 
> > > > > > > 
> > > > > > > try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> > > > > > 
> > > > > > 
> > > > > > How to use that?
> > > > > 
> > > > > 
> > > > > (version 4.3.6), replace the content in wapi.js file. The txt file is a wapi.js with the changes wich work fine for me... just CTRL+A then CTRL+C in txt file and CTRL+A then CTRL+V in wapi.js file. try and run again.
> > > > 
> > > > 
> > > > Where´s "wapi.js"?
> > > 
> > > 
> > > in your project, go to: node_modules/venom-bot/dist/lib/wapi/wapi.js
> > 
> > 
> > worked!! thanks
> 
> de nada man

kkkkkkkkkkk é brasileiro tbm e eu escrevendo em ingles kkkkk

**Comment by guh0rzd** [comment]
funcionou no whatsApp Web, mas no mobile não está funcionando...

**Comment by leanmarro** [comment]
> funcionou no whatsApp Web, mas no mobile não está funcionando...

estranho... o meu funciona nos dois. Qual a versão que está utilizando? apagou a sessão e fez outra?

**Comment by guh0rzd** [comment]
> 
Verifiquei aqui e na verdade o sendListMenu() não funciona no mobile, simplesmente não aparece...

**Comment by leanmarro** [comment]
> > 
> 
> Verifiquei aqui e na verdade o sendListMenu() não funciona no mobile, simplesmente não aparece...

entendo... Eu não tive problema com isso, pois nem sei se uso essa function... olha os issues já fechados para ver se acha algo.

**Comment by orkestral** [comment]
solved [8ee0067](https://github.com/orkestral/venom/commit/8ee0067ddd74bc139e4bf65c3edabe44a5270980) 
the return now comes by onMessage with type: reply and subtype: text, image ...

**Comment by brunomanoel** [comment]
> > Same `onMessage` method not working on message reply
> 
> try this file... replace wapi.js e run again [new wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)

Thanks, it works.
Seems like a minified code, not user friendly.
I'm curious to know where does that came from? Why this isn't in the codebase?

BTW, the release 4.3.7 didn't solve the problem of not triggering the `onMessage` event when a message is a reply.
Anyone else?

**Comment by imznx** [comment]
> > > Mesmo `onMessage` método não está funcionando na resposta à mensagem
> > 
> > 
> > tente este arquivo ... substitua wapi.js e execute novamente [novo wapi.txt](https://github.com/orkestral/venom/files/10125660/new.wapi.txt)
> 
> Obrigado, funciona. Parece um código minificado, não fácil de usar. Estou curioso para saber de onde isso veio? Por que isso não está na base de código?
> 
> BTW, o lançamento 4.3.7 não resolveu o problema de não acionar o `onMessage` evento quando uma mensagem é uma resposta. Mais alguém?

Estou tambem na busca de uma solução para isso ;-;
