### ISSUE TITLE
Logout Not detected 

### ISSUE THREAD

**Issue by Akash-Rathore** [orkestral/venom#2032]
i am doing whatsapp logout my phone . but not detected logout session

**Comment by TangramBee** [comment]
> 我正在做 whatsapp 注销我的手机。但未检测到注销会话

client.onStreamChange((state) => {
        let time = 0;
        console.log('State Connection Stream: ' + state);
        clearTimeout(time);
        if (state === 'DISCONNECTED' || state === 'SYNCING') {
          time = setTimeout(() => {
            client.close();
          }, 8000);
        }
      });

**Comment by orkestral** [comment]
solved [8ee0067](https://github.com/orkestral/venom/commit/8ee0067ddd74bc139e4bf65c3edabe44a5270980) 
returns only LOGOUT, the other returns do not exist anymore
