### ISSUE TITLE
sendMessage and checkNumberStatus not working

### ISSUE THREAD

**Issue by ppiyushjv** [orkestral/venom#2033]
## Description

WAPI.sendMessage("919904700322@c.us","test") 
hang Google Chrome 

## Environment

- **Venom version(s): v4.3.6
- **Browser: Chrome 107.0.5304.121
- **OS:**  Windows 11
- **Node version:** 9.1.2

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/13052658/203975773-7a5b7521-4a8d-4bf4-be8b-48f447dcc5f6.png)

**Comment by xzvcit** [comment]
same problem

**Comment by fwalid08** [comment]
The page freez after sending message

**Comment by orkestral** [comment]
use client.sendText
