### ISSUE TITLE
WAPI.checkNumberStatus doesn't check for WhatsApp Group

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#2035]
## Description

When checking WhatsApp group ID with `WAPI.checkNumberStatus`, it'll failed as it only uses `WPP.contact.queryExists` to check for WhatsApp ID, which will not work with WhatsApp Group ID. 

## Environment

- **Venom version(s):** 4.3.6
- **Browser:** Microsoft Edge Chromium 107.0.1418.56
- **OS:** Windows 11
- **Node version:** Node 19.1.0

## Steps to Reproduce

1. Call `WAPI.checkNumberStatus()` with WhatsApp Group ID

**Comment by orkestral** [comment]
normal behavior, this function checks contact not group
