### ISSUE TITLE
Enviar botão

### ISSUE THREAD

**Issue by Rodrigomsdevs** [orkestral/venom#2036]
Estou tentando enviar botões, está retornando como se tivesse sido enviado, porém não chega à mensagem nem os botões

multidevice está false, deixei o handless false para ver como ficava pelo navegador.

![image](https://user-images.githubusercontent.com/85195682/204118986-de0e522c-cf98-41e2-aadb-dca106faa391.png)

![image](https://user-images.githubusercontent.com/85195682/204118962-f0a0c183-1455-4a50-8e52-e5bcd134c597.png)

**Comment by giovaninogueira** [comment]
@Rodrigomsdevs , amigo, eu segui essa thread e consegui resolver meu problema dos botões.

https://github.com/orkestral/venom/issues/2023

**Comment by Rodrigomsdevs** [comment]
Boa tarde, eu vi athread #2023 e segui como dizia la para mudar o array do button, mas aqui nao envia nada do botao, vou enviar print do console, do whatsapp web e do whatsapp app

![image](https://user-images.githubusercontent.com/85195682/204157870-9e9d0a37-bcf8-45a9-819d-862af26c7a44.png)

A print do whatsapp pelo app. nao chega nada da mensagem com botao somente quando é list ou texto normal
![image](https://user-images.githubusercontent.com/85195682/204157917-fb07a9b5-b816-46d1-88a2-cd033d0774d8.png)

**Comment by Rodrigomsdevs** [comment]
Boa tarde, eu segui igual da documentação e igual da thread #2023 

E não deu certo ainda :/

![image](https://user-images.githubusercontent.com/85195682/204158289-f96b8d62-389d-4f4c-8be3-eeede1e91729.png)
