### ISSUE TITLE
sendText for a group, it is returning error "The number does not exist".

### ISSUE THREAD

**Issue by TangramBee** [orkestral/venom#2038]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s): 4.3.6
- **OS: Windows11
- **Node version :Node 14

## Steps to Reproduce

1. await await client.sendText("120363045171610938@g.us", '123').then(response => {))

## Log Output

{me: {}, to: "120363045171610938@g.us", erro: true, text: "The number does not exist", status: 404,…}

**Comment by RickGroenewegen** [comment]
Same here. Sending messages to a group no longer works: The number does not exist

**Comment by felippeantonachi** [comment]
face the same problem. Again.

**Comment by all4conn-mariano** [comment]
> if (e && "object" == typeof e) return { status: 200, numberExists: !0, id: e.wid }; in wapi.js, in this part, remove "e &&" remove too "r.canreply" in the same file and run again

Solved with the changes! File with changes attached.
[wapi.txt](https://github.com/orkestral/venom/files/10117501/wapi.txt)

**Comment by TangramBee** [comment]
> r.canreply

thanks,Solved my problem!

**Comment by TangramBee** [comment]
> if (e && "object" == typeof e) return { status: 200, numberExists: !0, id: e.wid }; in wapi.js, in this part, remove "e &&" remove too "r.canreply" in the same file and run again

thanks,solved my problem!

**Comment by orkestral** [comment]
solved [8ee0067](https://github.com/orkestral/venom/commit/8ee0067ddd74bc139e4bf65c3edabe44a5270980)
