### ISSUE TITLE
Buttons dont work

### ISSUE THREAD

**Issue by wnexous** [orkestral/venom#2045]
when I try to send buttons to the user, he just doesn't send. In the response of the button it returns the text as null. I reviewed the venom-bot code and from what I noticed, the problem is when the data is returned from WAPI, but I can not mess with it because of the compression used.

## Environment

- **Venom version(s):** [e.g. 4.3.6 - last version]
- **OS:** [ubuntu 22.04 lts]
- **Node version:** [16.17.1]

## Your Code
        const buttons = [
            {
                "buttonText": {
                    "displayText": "Text of Button 1"
                }
            },
            {
                "buttonText": {
                    "displayText": "Text of Button 2"
                }
            }
        ]
        await client.sendButtons(msg.from, 'Title', buttons, 'Description')
            .then((result) => {
                console.log('Result: ', result); //return object success
            })
            .catch((erro) => {
                console.error('Error when sending: ', erro); //return object error
            });

**Comment by wnexous** [comment]
![image](https://user-images.githubusercontent.com/87741591/204792110-f01f9f4f-1aa6-4bcd-ba3d-196b3959eb48.png)

quando eu envio os botoes, recebo esse log da variavel resultado

**Comment by guh0rzd** [comment]
bom dia mano, pra usar o sendButtons, faz assim: 
let botoes = [
    {
      "id": "1",
      "text": "Opção 1",
      },
    
    {
      "id": "2",
      "text": "Opção 2",
      },
  ];
  
  
porém o reply não está funcionando...

**Comment by wnexous** [comment]
> bom dia mano, pra usar o sendButtons, faz assim: let botoes = [ { "id": "1", "text": "Opção 1", },
> 
> ```
> {
>   "id": "2",
>   "text": "Opção 2",
>   },
> ```
> 
> ];
> 
> porém o reply não está funcionando...

Poise, notei tambem que o reply nao esta funcionando. Teria algum método para contornar isso?

**Comment by guh0rzd** [comment]
> > bom dia mano, pra usar o sendButtons, faz assim: let botoes = [ { "id": "1", "text": "Opção 1", },
> > ```
> > {
> >   "id": "2",
> >   "text": "Opção 2",
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ];
> > porém o reply não está funcionando...
> 
> Poise, notei tambem que o reply nao esta funcionando. Teria algum método para contornar isso?

ainda não consegui... estou testando voltar a versão do venom, se não der certo, resta esperar uma atualização que corrija isso

**Comment by wnexous** [comment]
> > > bom dia mano, pra usar o sendButtons, faz assim: let botoes = [ { "id": "1", "text": "Opção 1", },
> > > ```
> > > {
> > >   "id": "2",
> > >   "text": "Opção 2",
> > >   },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ];
> > > porém o reply não está funcionando...
> > 
> > Poise, notei tambem que o reply nao esta funcionando. Teria algum método para contornar isso?
> 
> ainda não consegui... estou testando voltar a versão do venom, se não der certo, resta esperar uma atualização que corrija isso
> 

tá certo, vou esperar uma atualização nova então
aparentemente a versao 4.3.3 está conseguindo mandar os buttons e buttonsTemplate sem problema mas também não consegue ver mensagens reply

**Comment by guh0rzd** [comment]
> 

acabei de testar isso kkk, realmente, nem na versão 4.3.3 funciona...

**Comment by wnexous** [comment]
@guh0rzd achei um método pra ler mensagens reply

Adicione um await na função e espere o callback com o then e catch como mostrado na imagem.

![image](https://user-images.githubusercontent.com/87741591/205066186-ec99ce3f-622f-4e8d-92e6-2580b89f1cef.png)
