### ISSUE TITLE
.sendListMenu doesn´t work

### ISSUE THREAD

**Issue by guh0rzd** [orkestral/venom#2046]
## Description

.sendListMenu Sends the list but the reply don´t call .onMessage function

## Environment

- **Venom version(s): 4.3.7

- **Node version: v16.15.0

## SendList Function

var validabv = async (msg) => {
  if (msg.body == "Abrir Chamado") {
    storage.client
      .sendListMenu(
        msg.from,
        "Abertura de Chamados",
        "Tipos de Chamado Disponíveis",
        "Escolha o tipo de Chamado",
        await gettipo(msg.from)
      )
      .then((result) => {
        console.log("Result: ", result);
      })
      .catch((erro) => {
        console.error("Error when sending: ", erro);
      });

## List Function

return await axios(config)
    .then(function (response) {
      var rowid = 0;
      var nomes = [
        {
          title: "Serviços Disponíveis",
          rows: [],
        },
      ];
      response.data.forEach((tipo) => {
        nomes[0].rows.push({
          rowId: ++rowid + "",
          description: tipo.nome,
        });
      });
      return nomes;

##ScreenShot

![Screenshot_3](https://user-images.githubusercontent.com/89607635/205085788-e1255bf8-b336-4465-a466-fe084f742c5e.png)
![image](https://user-images.githubusercontent.com/89607635/205085991-e0c005bc-5b4a-43b5-b321-ca0fc90d7418.png)

**Comment by wnexous** [comment]
> Tente com isso: 

       const listr = [
            {
                title: "Pasta",
                rows: [
                    {
                        title: "Ravioli Lasagna",
                        description: "Made with layers of frozen cheese",
                    }
                ]
            },
            {
                title: "Dessert",
                rows: [
                    {
                        title: "Baked Ricotta Cake",
                        description: "Sweets pecan baklava rolls",
                    },
                    {
                        title: "Lemon Meringue Pie",
                        description: "Pastry filled with lemonand meringue.",
                    }
                ]
            }
        ];
        if (msg.body == "Abrir Chamado") {
            await client.sendListMenu(
                msg.from,
                "Abertura de Chamados",
                "Tipos de Chamado Disponíveis",
                "Escolha o tipo de Chamado",
                listr
            )
                .then((result) => {
                    console.log("Result: ", result);
                })
                .then((result) => {
                    console.log("Result: ", result);
                })
                .catch((erro) => {
                    console.error("Error when sending: ", erro);
                });
        }

**Comment by guh0rzd** [comment]
não sei se ficou entendível, mas eu monto a lista com o array que vem da requisição que eu estou fazendo, a lista é enviada, mas o reply não funciona...

**Comment by wnexous** [comment]
> não sei se ficou entendível, mas eu monto a lista com o array que vem da requisição que eu estou fazendo, a lista é enviada, mas o reply não funciona...

experimente adicionar um .then a mais. 
sinceramente ainda não fui na base do problema para descobrir o motivo do bug, mas deixando a função com 2 .then resolve o problrma

**Comment by guh0rzd** [comment]
vou testar, valeu!

**Comment by wnexous** [comment]
> vou testar, valeu!
> 

teste e me retorne aqui se resolveu o problema

**Comment by orkestral** [comment]
working
