### ISSUE TITLE
Where can I deploy for free? I tried in fly.io but dosent work (get a pupeeter error) and tried too in cyclic but get the build size error (is very big)

### ISSUE THREAD

**Issue by JoaoVitorJJV** [orkestral/venom#2078]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://orkestral.github.io/venom/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
- Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by muriloux** [comment]
It's not an issue with your deploy environment, i get puppeteer error even in development environment. It's probably an update in whatsapp web that needs to be accounted to in the crawler. By the way, i deployed in railway.app since fly.io CLI was giving me some headaches.
