### ISSUE TITLE
Erro na versão 2.0.11

### ISSUE THREAD

**Issue by thyagojcosta** [orkestral/venom#208]
Depois que atualizei para a versão 2.0.11 apareceu este erro: Cannot read property 'browserWS' of undefined

Comentando a parte do código no initializer.js que apresentou o erro, voltou a funcionar normalmente

                    // if (!options.browserWS || options.browserWS == '') {
                    //     browser['_process'].once('close', function () {
                    //         browser['isClose'] = true;
                    //     });
                    // }

**Comment by ricardojlrufino** [comment]
this works !!

**Comment by jonalan7** [comment]
**This problem has been fixed!**

**Comment by dp-152** [comment]
should probably use mergedOptions.browserWS instead of options.browserWS
