### ISSUE TITLE
Venom Bot as Windows Service

### ISSUE THREAD

**Issue by AndisKush** [orkestral/venom#2081]
Hello, which is the best way to run Venom Bot as a windows service?

I made an app that works fine, i used Nexe to generate a .exe file, that when executing manually works fine, so I tried using Nssm to run .exe as a windows service, if I start the service manually venom bot works, but if I let the service starts automatically i gotta an error in wapi undefined (reading 'isWidLike')
So I tried to create a task in task schedules but i don't wanna the console windows popping, so I make a .vbs file that run a hide console and again i gotta the wapi error.

I think that this error has something to do with service or task running as System Account

So anyone already used this lib with windows services or task that can help me?

**Comment by AndisKush** [comment]
To sum up I wanna a way to run the app when windows starts or user logged in and hide my code, thats why the Nexe part

**Comment by eliasnepo** [comment]
Hi Andis, I'm trying to use Nexe or Pkg to generate an executable for my venom application. Did you face any problem doing that? It's being tough to me
