### ISSUE TITLE
checkNumberStatus Method is Error but returning null object

### ISSUE THREAD

**Issue by robbytian** [orkestral/venom#2083]
## Description

i am using checkNumberStatus method before sending the message, usually, if the number is not exists, its returning the message that phone number is not exists. But now, its returning null object and the number that i checked is actually exists

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** Chrome 103
- **OS:** Ubuntu 20.04..5
- **Node version:** 18.10

this is my code
![image](https://user-images.githubusercontent.com/47393745/207512833-06548524-58d0-4791-906a-0e64dbb1b3cd.png)

the checkNumberStatus method is error but returning null object
![image](https://user-images.githubusercontent.com/47393745/207509132-8457c20c-64d2-4745-a509-a34e217df0a2.png)

**Comment by AndisKush** [comment]
Same issue, when the number doesnt exists returning this error

![image](https://user-images.githubusercontent.com/66446864/207726903-68229282-5ecb-4d26-bf6b-f0662f47712e.png)

My code

`console.log(phoneNumber1)
    await client.checkNumberStatus(phoneNumber1)
    .then(async (result)  => {
    result.numberExists ? 
        number = phoneNumber1
        :
        null
    })
    .catch((erro) => {
        console.log('Numero Invalido 1')
        console.log(erro)
        }
    );`

Venom version(s): 4.3.7

**Comment by AndisKush** [comment]
in version 4.3.0

![image](https://user-images.githubusercontent.com/66446864/207728436-d19a6139-f627-46f9-a05e-854fb0da9089.png)
