### ISSUE TITLE
getAllChats  Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by TangramBee** [orkestral/venom#2089]
## Description

Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WAPI.window.WAPI.getAllChats (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:61537)
    at pptr://__puppeteer_evaluation_script__:2:30

## Environment

- **Venom version(s):** 4.3.7
- **OS:** Windows 11
- **Node version:** Node 14

## Log Output

Error: Evaluation failed: TypeError: Cannot read property 'map' of undefined
    at Object.window.WAPI.window.WAPI.getAllChats (/usr/src/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:61537)
    at pptr://__puppeteer_evaluation_script__:2:30

## Your Code

```
await client.getAllChats().then(async (chats) => {})
```

**Comment by TangramBee** [comment]
Downloading node_module again solves this problem

**Comment by renenucci** [comment]
> Downloading node_module again solves this problem

Not works for me, Tried everything, remove node_modules, reconnect account, and nothing. 

The same issue as you.
