### ISSUE TITLE
client.onAck(ack => {  --   Dont work :(

### ISSUE THREAD

**Issue by igortrust** [orkestral/venom#209]
Dear, it seems that the lock function has stopped working. 

We did several tests, but apparently it is not entering the method when typing the whatsapp message connected to the venom.

Does anyone know what happened? Until last Friday it worked perfectly.

  client.onAck(ack => {
     console.log(ack)
 });

**Comment by randhipp** [comment]
confirmed, on 2.0.8 or latest 2.0.11 `onAck` not working

**Comment by iagoln** [comment]
I have the same problem reported

**Comment by jonalan7** [comment]
**This function has already been corrected! Soon we will update npm.**

**Comment by iagoln** [comment]
Great that this is resolved, thank you very much for resolving so fast.

**Comment by igortrust** [comment]
> **This function has already been corrected! Soon we will update npm.**

Tks so much!!! 👍

**Comment by iagoln** [comment]
@jonalan7  Will it be the update on npm today?

**Comment by jonalan7** [comment]
**Yesterday I updated!**
