### ISSUE TITLE
Venom stuck at "Checking is logged"

### ISSUE THREAD

**Issue by ukoBodsquare** [orkestral/venom#2090]
## Description

I'm building a REST API that utilizes the different function of the venom client. I have an endpoint that instantiates a user and I pass along "session-{{userId}}" as the session name. After the user scans and is authenticated he can call the send message endpoint. But venom only exposes a create function which starts the entire authentication process again except this time it's stuck at 
"[instance: session-6399d8d3829632de8adb72cd]: Checking is logged...".

## Environment

- Venom version: 4.3.7
- OS: Windows 11
- Node version: Node 14

**Comment by AdrielSantoss** [comment]
same problem here

**Comment by dgabriel2334** [comment]
Same problem here

**Comment by matheusverri** [comment]
Did anybody get an answer?

**Comment by Helkyd** [comment]
Having same problem on Version 4.3.7

**Comment by leobaccili** [comment]
I enabled devtools, this is the message that is showing up
![image](https://user-images.githubusercontent.com/14761612/214365778-6680d824-7780-41f9-b426-6803e7730cfa.png)

**Comment by renandecarlo** [comment]
This might be related to #2133

**Comment by suknaic** [comment]
same problem here

**Comment by andrguilhem** [comment]
Anyone has any update on this bug? I can't find a solution to it
I'm using:
ubuntu server on AWS (not the amazon Linux)
node v18.13.0
venom-bot 4.3.7

**Comment by leobaccili** [comment]
> Anyone has any update on this bug? I can't find a solution to it I'm using: ubuntu server on AWS (not the amazon Linux) node v18.13.0 venom-bot 4.3.7

try this
#2133
