### ISSUE TITLE
checkNumberStatus return error {}

### ISSUE THREAD

**Issue by thelordapofis** [orkestral/venom#2092]
## Description

The checkNumberStatus endpoint for any phone is returning error {}

- **Venom version(s):** [e.g. 4.3.7]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. Linux Ubuntu, Windows 11]
- **Node version:** [e.g. Node 16.13.0]

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/59453913/208104373-11e05149-96a0-4a08-8c03-d83d305a056e.png)

**Comment by mufer19** [comment]
when is the new version expected?

**Comment by TangramBee** [comment]
checkNumberStatus doesn't check for WhatsApp Group

**Comment by TangramBee** [comment]
> 

checkNumberStatus doesn't check for WhatsApp Group

**Comment by edilsonlm217** [comment]
"venom-bot": "^4.3.6"

It's returning an empty object as well.
