### ISSUE TITLE
Authentication does not work (scanning QR code does nothing)

### ISSUE THREAD

**Issue by panzi** [orkestral/venom#21]
When I start a WhatsApp client using venom-bot I first get this log:
```
- Checking for updates...
- Checking for updates...
- Creating whatsapp instace...
Chrome not found, using chromium
- Checking for updates
- Creating whatsapp instace...
- Checking for updates
- Authenticating...
- Checking for updates
- Authenticate to continue
```
Then I get the QR code, which I scan. Then the phone acts as if the authentication was successful (short vibration and switch back to contact list), but the promise that creates the client object never returns. Just as if no authentication happened or as if venom-bot would not be able to detect the authentication. WhatsApp probably changed their web interface and broke venom-bot?

Versions:
venom-bot: 1.0.4
node: 10.16.3

**Comment by orkestral** [comment]
Friend I just tested, is running normal and in our group there are no reports of this problem, access our chat one of our employees can help you and soon you will help someone

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

**Comment by panzi** [comment]
I don't want to join some random WhatsApp chat and share my WhatsApp account/phone number that way. I'd rather chat here, on IRC (e.g. irc://irc.freenode.net/#venom-bot) or on Discord.

**Comment by panzi** [comment]
And I'm not saying it doesn't work for you, but it certainly doesn't work for me or many other people. I highly suspect WhatsApp is rolling out updates to the web interface and it's breaking things.
