### ISSUE TITLE
How to set an ID when sending a message

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#210]
How to set an ID when sending a message？

**Comment by AlanMartines** [comment]
The contact number and the id itself.

**Example Number:** +1 (905) 9999-9999
**Example ID:** 190599999999

```node
// Send basic text
await client.sendText('190599999999@c.us', 'Message here!')
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });
```

**Comment by Lucipher** [comment]
Not phone number, I mean the ID like after send the message and return id  in the result

**Comment by AlanMartines** [comment]
Would you post the return of your json?

**Comment by Lucipher** [comment]
It's ok, I can update the return id to db,but it will better to set a message ID before send for send message  with cronjob

**Comment by Lucipher** [comment]
@AlanMartines 

Thanks for your help
