### ISSUE TITLE
Template buttons are not working as expected

### ISSUE THREAD

**Issue by Javid507** [orkestral/venom#2103]
## Description

In [docs ](https://docs.orkestral.io/venom/#/?id=chatting) we have option to send template buttons. But this doesn't seem to work.

Here is code from docs:

```
// Send Messages with Buttons Template
let buttons: [
  {
    url: 'https://orkestral.io/',
    text: 'Orkestral Cloud'
  },
  {
    phoneNumber: '+55 11 91438-0641',
    text: 'Suporte Orkestral'
  },
  {
    id: '1',
    text: 'Button 1'
  },
  {
    id: '2',
    text: 'Button 2'
  }
]
await client.sendButtonsTemplate("5511914380641@c.us", "Title", buttons, "Description")
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });
````

## Environment

- **Venom version(s):** [4.3.7]
- **Browser:** [Chromium 103.0.5058.0]
- **OS:** [ Windows 10]
- **Node version:** [18]

## Expected

When we send a message with buttons e.g

```
let buttons = [
 {
    url: 'https://orkestral.io/',
    text: 'Orkestral Cloud'
  },
]
```

Then once the message is received, clicking the button in the message should open the url or prompt the user to open the url.

**Comment by Misterr-H** [comment]
@Javid507 Hi Facing same issue. It says no function found sendButtonsTemplate. Have you found any solution?

**Comment by Javid507** [comment]
No @Misterr-H ,
It isn't working for me. Did lot of googling on this. It seems this is a paid feature from WhatsApp itself.
However, I don't know why it is not clearly mentioned in the **Venom-bot** docs.
