### ISSUE TITLE
Message reactions support?

### ISSUE THREAD

**Issue by LeonardoZivieri** [orkestral/venom#2108]
**Is your feature request related to a problem? Please describe.**
Reading all the documentation and thinking about the improvements and nexts steps, I'm willing to help to improve the Venom project, and the WhatsApp's reactions support it's a nice feature. I'm studing the project, but for now, it's better and faster write this issue first.

**Describe the solution you'd like**
In `Whatsapp.onMessage`, when you recieve a reply message, maybe the reactions api can be equal. When a reaction happen, you recieve the message, and the reacted emoji.

- [ ]  Whatsapp.onMessageReaction(reaction: Reaction)
- [ ]  `message.reactions` list

**Describe alternatives you've considered**
No other alternatives found

**Additional context**
Below are the new reaction object and some additions in already existing Message interface

```typescript
// new interface to handle Reaction object
interface Reaction {
    message: Message; // The message reacted
    sender: Sender; // Who sent the reaction
    reaction: string; // '👍', '❤️', '😂', '😮', '😢', etc
}

// The changes of message interface when message has reaction support
interface ReactionMessage extends Message {
   type: "reaction";
   subtype: "chat";
   reactions: Array<Omit<Reaction, "message">>;
}
```

To start, i'm not finding where the message is processed to a object. Someone know where?

**Comment by santiramirezc** [comment]
I'd really like to have this feature implemented. Sadly I don't really know where the message is proccesed. I'm new at this module and ts but if you have any aproach on how to solve this I'd love to see a PR to play around and help if I can.
