### ISSUE TITLE
onAnyMessage  download file from send message 

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#211]
onAnyMessage  download file from send message not work, receive message works

sender isMe equal true  can't download the file with onAnyMessage event

client.onAnyMessage(async (message) => {

         const buffer = await client.decryptFile(message);
         or 
         const mediaBlob = await client.downloadFile(message);

......

**Comment by jonalan7** [comment]
**There is no way to do it at the moment! We will try to complement!**
