### ISSUE TITLE
sendButton not working

### ISSUE THREAD

**Issue by AndisKush** [orkestral/venom#2114]
## Description

Usando o código da documentação

const buttons = [
  {
    "buttonText": {
      "displayText": "Text of Button 1"
      }
    },
  {
    "buttonText": {
      "displayText": "Text of Button 2"
      }
    }
  ]
await client.sendButtons('000000000000@c.us', 'Title', buttons, 'Description')
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

O result:

Result:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '553488354011',
      _serialized: '553488354011@c.us'
    },
    id: '3EB0CCF2210FACEA1D69',
    _serialized: 'true_553488354011@c.us_3EB0CCF2210FACEA1D69'
  },
  erro: false,
  text: null,
  status: 'OK',
  result: null,
  type: 'Buttons',
  dynamicReplyButtons: [ { buttonText: [Object] }, { buttonText: [Object] } ]
}

Mas a mensagem não aparece no WhatsApp

![image](https://user-images.githubusercontent.com/66446864/212483250-cec425d3-90f5-4c29-b912-96f9600cf934.png)

## Environment

- **Venom version(s):** [4.3.7]

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by karein** [comment]
Hello,
i'm having the same problem

the function doesn't return an error, I receive the notification but I don't received the message.
After calling the button function, the chat messages disappear, and I can't see any new messages sent to that chat.

I tested multidevice: true/false with both, business and personal account.

**Environment**
 - venom-bot: ^4.3.7
 - nodejs: v16.17.0

**screenshots**
- chat before send the button:
![erroButtonBefore](https://user-images.githubusercontent.com/32269228/216348590-a6c9f458-b0fd-47aa-ae52-11aeb4de5aeb.png)


- notification received after sending the button:
![erroButtonNotification](https://user-images.githubusercontent.com/32269228/216348005-167799a1-eca0-4ba4-b31c-46f321c45d63.png)

- chat after sending button:
![errorButtonChat](https://user-images.githubusercontent.com/32269228/216348390-9c1a6214-e1a2-4a88-9cbc-7b47d7fa769a.png)



i'm using the documentation code:
`const buttons = [{ "buttonText": { "displayText": "Text of Button 1" }}, { "buttonText": { "displayText": "Text of Button 2"  }}]                                                        
await client.sendButtons('xxxxxxxxxxxx@c.us', 'title', buttons, 'description')        
.then((result) => {
  console.log('Result: ', result); //return object success
 })          
.catch((erro) => {
  console.error('Error when sending: ', erro); //return object error
});`

Result:  {
  me: {},
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: 'xxxxxxxxxxxx',
      _serialized: 'xxxxxxxxxxxx@c.us'
    },
    id: 'XXXXXXXXXXXXXXXXXXXX',
    _serialized: 'true_xxxxxxxxxxxx@c.us_XXXXXXXXXXXXXXXXXXXX'
  },
  erro: false,
  text: null,
  status: 'OK',
  result: null,
  type: 'Buttons',
  dynamicReplyButtons: [ { buttonText: [Object] }, { buttonText: [Object] } ]
}

**Comment by Divino67** [comment]
Same problem here!

**Comment by serobalino** [comment]
The solution is simple, the example is wrong. It should look like this:

````js
[
                    {
                        url: 'https://orkestral.io/',
                        text: 'Orkestral Cloud'
                    },
                    {
                        phoneNumber: '+55 11 91438-0641',
                        text: 'Suporte Orkestral'
                    },
                    {
                        id: '1',
                        text: 'Button 1'
                    }
                ]
````

**Comment by marlon33** [comment]
> The solution is simple, the example is wrong. It should look like this:
> 
> ```js
> [
>     {
>         url: 'https://orkestral.io/',
>         text: 'Orkestral Cloud'
>     }, {
>         phoneNumber: '+55 11 91438-0641',
>         text: 'Suporte Orkestral'
>     }, {
>         id: '1',
>         text: 'Button 1'
>     }
> ]
> ```
> 
> But it's still wrong because alone, the 'text' attribute works, the rest doesn't work

It doesn't work for me, can you show the code please??
Whatsapp business??

**Comment by serobalino** [comment]
````js
let buttons = [
    {
        url: 'https://orkestral.io/',
        text: 'Prueba de link'
    }, {
        phoneNumber: '+55 11 91438-0641',
        text: 'Suporte Orkestral'
    }, {
        id: '1',
        text: 'Button 1'
    }
];
client.sendButtons(message.from, "Title", buttons, "Description")
````

**Comment by guh0rzd** [comment]
You can try this: 
let buttons =
  [
    {
      "id": "1",
      "text": "Text 1",
      },
    
    {
      "id": "2",
      "text": "Text 2",
      },
  ];
  
  This format is working in 4.3.7 version

**Comment by marlon33** [comment]
Sorry

> ```js
> let buttons = [
>     {
>         url: 'https://orkestral.io/',
>         text: 'Prueba de link'
>     }, {
>         phoneNumber: '+55 11 91438-0641',
>         text: 'Suporte Orkestral'
>     }, {
>         id: '1',
>         text: 'Button 1'
>     }
> ];
> client.sendButtons("xxxxxxxxxxxx@c.us", "Title", buttons, "Description")
> ```

It doesn't work here 4.3.7,

```js
    let buttons = [
        {
            url: 'https://orkestral.io/',
            text: 'Prueba de link'
        }, {
            phoneNumber: '+55 11 91438-0641',
            text: 'Suporte Orkestral'
        }, {
            id: '1',
            text: 'Button 1'
        }
    ]
    client.sendButtons(numberMarlon, 'Title', buttons, 'Description')
        .then((result) => {
            console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
        });
```

Whtas that was sent
![image](https://user-images.githubusercontent.com/41172965/219950813-1fec08cb-3f75-442d-8848-6d8dc1d78fba.png)


Whats that was recived
![image](https://user-images.githubusercontent.com/41172965/219950840-e77f790c-61fc-4b2b-9de0-6e8e617d6aa0.png)

**Comment by tapan-thapa** [comment]
It is not working for me too and i am using 4.3.7

**Comment by yuryalencar** [comment]
### The same BUG in the Brazilian context

The sendButton method is working only for São Paulo (SP) DDD numbers for me.

```
// São Paulo DDD number
const spNumber = 5511XXXXXXXXX@c.us // sendButton working for sender and receiver
```

But when I change the phone number to another Brazilian DDD like GO/RS/PA/MA ... doesn't work. The messages are sent but the WhatsApp sends to the same number but not Whatsapp. When I try to call the number I receive the respective message: "This number doesn't have WhatsApp"

The sender's perspective (With number):
<img width="607" alt="image" src="https://user-images.githubusercontent.com/19940344/221210999-22ecdfd4-5db6-48b8-ab42-ec35b2bdb428.png">

But the real conversation is (With contact name):
<img width="608" alt="image" src="https://user-images.githubusercontent.com/19940344/221211551-08473a18-27f7-4e82-8e18-bff164081f3a.png">

**Comment by SahilAggarwal2004** [comment]
Any solutions to this issue?
