### ISSUE TITLE
ERR_UNHANDLED_REJECTION when using .reply() method

### ISSUE THREAD

**Issue by santiramirezc** [orkestral/venom#2117]
## Description

When I try to reply to a message in a group, the app crashes.

## Environment

- **Venom version(s):** ^4.3.7
- **OS:** Windows 10
- **Node version:** Node.js v18.12.1

## Steps to Reproduce

1. Send a message to a group
2. Reply to that message using ```.reply(message .from, "", message .id)```

## Log Output
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Node.js v18.12.1

## Your Code

```
client.reply(message.from, "Message sent", message.id)
```

**Comment by matheusfterra** [comment]
Hi! You resolved this question?
