### ISSUE TITLE
How to disable waiting for the login?

### ISSUE THREAD

**Issue by GodCode** [orkestral/venom#212]
Hello @orkestral, thanks for the fabulous library...
I just wanted to ask if there is a way to disable the waiting of the bot to login and execute the WAPI just after login
someting like this : 

```
venom.create({
    on_created : () => {
        console.log('Browser Started')
    }
})
```

Please help me solving this issue...

**Comment by orkestral** [comment]
yes, 
venom.create({
      headless: true, // Headless chrome
      devtools: false, // Open devtools by default
      useChrome: true, // If false will use Chromium instance
      debug: false, // Opens a debug session
      logQR: true, // Logs QR automatically in terminal
      disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
      disableWelcome: true, // Will disable the welcoming message which appears in the beginning
    })
