### ISSUE TITLE
Checking is logged eternally in the terminal

### ISSUE THREAD

**Issue by matheusfterra** [orkestral/venom#2121]
## Description

Hi, my venon-bot in ubuntu terminal does not connect, nor does it show the qr code. It stays "Checking is logged" and does not go to the next one. Any help please?

## Environment

- **Venom version(s):**4.3.7
- **Browser:** How get?
- **OS:** Ubuntu 22.04
- **Node version:** Node 19.4.0

**Comment by matheusfterra** [comment]
Thanks for reply. Can you back here when the bug was fixed, please?

**Comment by renandecarlo** [comment]
This might be related to #2133
