### ISSUE TITLE
Stuck at "update chrome" window in headless mode

### ISSUE THREAD

**Issue by renandecarlo** [orkestral/venom#2133]
## Description

WhatsApp Web keeps stuck at "update chrome" window if you sync the first time in headless mode.

## Environment

- **Venom version(s):** v4.3.7
- **Browser:** Chrome 109
- **OS:** Windows 10
- **Node version:** Node 16

## Steps to Reproduce

1. Close all open Chrome instances/windows
2. Delete "tokens" folder
3. Start venom in headless mode
4. Read QR CODE
5. Close venom
6. Open venom

In headless mode it gets stuck at "Checking is logged..." message. 
If you disable headless mode, you'll see WhatsApp Web is stuck at "update chrome" warning as in screenshot below.

## Additional context / Screenshot

![2023-01-24 23_50_52-Window](https://user-images.githubusercontent.com/6974980/214471132-f9386343-c192-4156-9571-57a3069a39a7.png)

**Comment by leobaccili** [comment]
A workaround to fix this issue is set venom to do not use chrome:
`useChrome: false,`
and use puppeteer env variable to set chromium to use latest revision
`process.env['PUPPETEER_CHROMIUM_REVISION'] = '1096680';`

**Comment by andrguilhem** [comment]
Anyone has any update on this bug? I can't find a solution to it
I'm using:
ubuntu server on AWS (not the amazon Linux)
node v18.13.0
venom-bot 4.3.7
