### ISSUE TITLE
Develop functions to catalog for whatsapp business

### ISSUE THREAD

**Issue by IgorDePaula** [orkestral/venom#2137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IgorDePaula** [comment]
Hi???????

**Comment by IgorDePaula** [comment]
WFT??????? Can you say anything? Will does, not?

**Comment by bhavyagosai** [comment]
LMAOOOO SIKE
