### ISSUE TITLE
Where do you guys deploy your bots?

### ISSUE THREAD

**Issue by paulotolentino** [orkestral/venom#2138]
Hey guys, I'm developing my WhatsApp bot using Venom package, but the size limit of most of the cloud providers.
AWS lambda limit is 250mb, including the node_modules, for example.

I'm currently using a VPS server, but I'd like to be aware of the options I can go.

What do you guys use to run your bots? 
Is there a way to reduce the size of the package? Or to create a production build of venom?

Thank you guys in advance.

**Comment by chr0nu5** [comment]
hey @paulotolentino, i use ECS (AWS) with a persistent volume for the tokens

**Comment by leobaccili** [comment]
VPS

**Comment by Im2rnado** [comment]
You can use something like https://railway.app 
It's like Heroku and has a free plan

**Comment by paulotolentino** [comment]
Closing. I decide to continue using the VPS. But instead of using a cron task (node-schedule) I decide to create a simple express API to store the bot and when the cron task runs it makes a request to the API to run the bot. Worked like a charm.
