### ISSUE TITLE
onParticipantsChanged doesn't catch event

### ISSUE THREAD

**Issue by shailidalmia** [orkestral/venom#2146]
## Description

The function onParticipantsChanged doesn't catch event, so I can't know about participants changes in my group.

## Environment

- **Venom version(s): v4.3.7** 
- **Browser:** Chrome
- **OS:** OSX 13.2 (22D49)
- **Node version:** v19.6.0

## Steps to Reproduce

1. create a new session
2. execute start(client)
3. execute client.onParticipantsChanged

## Your Code

```
function start(client) {
idGroup = '000000000000-0000000000@g.us'
client.onParticipantsChanged( idGroup,  (event: any) => {
    console.log(event)
})
```

**Comment by aadishj02** [comment]
I am facing the same issue. Any update on this issue would be helpful.
