### ISSUE TITLE
The number does not exist

### ISSUE THREAD

**Issue by AndisKush** [orkestral/venom#2147]
## Description

I am facing this error message "The number does not exist" but the number is correct, and it was working with this same number today.

## Environment

- **Venom version(s):** [4.3.7]

- **OS:** [Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

I am using this function to send text

async function sendText(number1, number2, body , callback) {
  let number = await validateNumber(client, number1,number2)  
  await client.sendText(number, body)
  .then(res => callback(res))
  .catch((error) => {console.log('nro > ' + number + ' error > ');console.log(error);callback(error)})
}

And i always use this number for test, and its woking, i've already tried to put the '9' before number because some regions here in Brazil has the 9 before number, but no success

## Log Output

{
  me: {},
  to: '553488354011@c.us',
  erro: true,
  text: 'The number does not exist',
  result: null
}

![image](https://user-images.githubusercontent.com/66446864/218207168-f2b743c5-68e8-41cd-ab2a-71b3d5ffcc4a.png)

**Comment by AndisKush** [comment]
without headless, we can see in chrome that venon open the chat but not send the message, so the number is correct

![image](https://user-images.githubusercontent.com/66446864/218207920-0baf308f-dbb2-4a3d-896c-708e2d94562c.png)

**Comment by AndisKush** [comment]
I dont know why this error happened, but i deleted the tokens folder and node_modules and its working again

**Comment by boinaweb** [comment]
Adicione no Modulo: { id: 'checkNumberBeta', conditions: (module) => module.queryExist || module.queryPhoneExists ? module : null,},
e mude a função de checar para "window.Store.checkNumberBeta.queryPhoneExists" resolvera seu problema

**Comment by boinaweb** [comment]
Add in Module: { id: 'checkNumberBeta', conditions: (module) => module.queryExist || module.queryPhoneExists ? module : null,},
and change the check function to "window.Store.checkNumberBeta.queryPhoneExists" solving your problem

**Comment by AndisKush** [comment]
> Add in Module: { id: 'checkNumberBeta', conditions: (module) => module.queryExist || module.queryPhoneExists ? module : null,}, and change the check function to "window.Store.checkNumberBeta.queryPhoneExists" solving your problem

Where exactly i had to add this?
{ id: 'checkNumberBeta', conditions: (module) => module.queryExist || module.queryPhoneExists ? module : null,}

**Comment by murilobesse** [comment]
Same here, have to downgrade version from 4.3.7 to 4.3.6, now it works.

**Comment by AndisKush** [comment]
i've downgraded to version 4.3.6 and still the same error
I'm not even using the checknumber function

**Comment by AndisKush** [comment]
I've noticed that after the first message sent, venom bot stop returning responses in sendText()

console.log('Sending')
  client.sendText(numero1, body)
  .then(res => {
    console.log(res)
  })
  .catch((error) => console.log(error))

![image](https://user-images.githubusercontent.com/66446864/218589674-32bf520a-c11b-438d-ace3-c0fdb48c7cc0.png)

**Comment by willy9772** [comment]
O mesmo aconteceu comigo, tentei mudar para a versão anterior, porém continuou a mesma coisa... 
Percebi também que funciona com alguns números, porém não com todos..
-----------
The same happened to me, I tried to change to the previous version, but the same thing continued...
I also realized that it works with some numbers, but not with all..

**Comment by matheusfterra** [comment]
I am also having the same problem. Before sending the msg, I check that the number is valid.

Using the checkNumberStatus, the error, he can not make the request.

  I use getNumberProfile, it can return, but for some numbers it returns a non-existent number, even the existing number. I don't know if it has something to do with the profile that will receive the message having to have my number registered....

**Comment by martinvcp** [comment]
Same error, it works with numbers that already have a chat started, but not with new chats.

**Comment by boinaweb** [comment]
For me it goes both unknown numbers and contacts, without using the constructor.

**Comment by karein** [comment]
> I've noticed that after the first message sent, venom bot stop returning responses in sendText()
> 
> console.log('Sending') client.sendText(numero1, body) .then(res => { console.log(res) }) .catch((error) => console.log(error))
> 
> ![image](https://user-images.githubusercontent.com/66446864/218589674-32bf520a-c11b-438d-ace3-c0fdb48c7cc0.png)

I also had this problem using onMessage function, but it worked again after remove ' package.lock', 'node_modules' and and re-installing it  again, as reported in these issues:
https://github.com/orkestral/venom/issues/2152#issuecomment-1434573030
https://github.com/orkestral/venom/issues/2155

**Comment by zeekhuge** [comment]
bump
