### ISSUE TITLE
sendText returns {}

### ISSUE THREAD

**Issue by can1871** [orkestral/venom#2152]
The first time I send it, there is no problem, but when I send a message again, {} is returned and the message is not send.
My code is below:

var result = client.sendText(phone_number + "@c.us", msg_content)
await console.log('Result: ', JSON.stringify(result));

**Comment by YoSoyZpock** [comment]
Same problem, the first message works fine, but when i send another message stop responding and dont catch the next messages.

**Comment by guh0rzd** [comment]
> Same problem, the first message works fine, but when i send another message stop responding and dont catch the next messages.

- Same problem here, the first message works, but after this, the bot dont listen to anyone message but dont show errors ou things like that

**Comment by rodrigopba** [comment]
Está acontecendo o mesmo aqui. A primeira mensagem é enviada normalmente, já na segunda trava o navegador. Sem retornar erros.

**Comment by guh0rzd** [comment]
> Está acontecendo o mesmo aqui. A primeira mensagem é enviada normalmente, já na segunda trava o navegador. Sem retornar erros.

> ta dificil... kkkk

**Comment by danielalves1** [comment]
> The first time I send it, there is no problem, but when I send a message again, {} is returned and the message is not send. My code is below:
> 
> var result = client.sendText(phone_number + "@c.us", msg_content) await console.log('Result: ', JSON.stringify(result));

Try changing the console.log await to the sendText call and add `catch` to catch any errors that occur. 

For example:
```javascript
var result = await client.sendText(phone_number + "@c.us", msg_content).catch(err => err);

console.log('Result: ', JSON.stringify(result));
```

**Comment by guh0rzd** [comment]
> > The first time I send it, there is no problem, but when I send a message again, {} is returned and the message is not send. My code is below:
> > var result = client.sendText(phone_number + "@c.us", msg_content) await console.log('Result: ', JSON.stringify(result));
> 
> Try changing the console.log await to the sendText call and add `catch` to catch any errors that occur.
> 
> For example:
> 
> ```js
> var result = await client.sendText(phone_number + "@c.us", msg_content).catch(err => err);
> 
> console.log('Result: ', JSON.stringify(result));
> ```

> my code :
  client.onMessage(async (msg) => {
      if (!msg.isGroupMsg && usernum != "status") {
      console.log(msg.body);
      
      the first one message appears on console, anyone after that, dont shows on my console

**Comment by leobaccili** [comment]
After the second message Chrome stuck, unable to send new messages, to read console, just stuck

**Comment by guh0rzd** [comment]
Eu apaguei os arquivos "package", "package-lock", "node-modules", desinstalei o venom-bot e instalei de novo, após isso, voltou a funcionar normalmente... sugiro tentarem

**Comment by rodrigopba** [comment]
> Eu apaguei os arquivos "package", "package-lock", "node-modules", desinstalei o venom-bot e instalei de novo, após isso, voltou a funcionar normalmente... sugiro tentarem

tentei aqui e continua do mesmo jeito... tem algum comando pra desinstalar  o venom ou é só apagar os arquivos?

**Comment by rodrigopba** [comment]
apaguei a pasta inteira e deu certo!!!

**Comment by guh0rzd** [comment]
> > Eu apaguei os arquivos "package", "package-lock", "node-modules", desinstalei o venom-bot e instalei de novo, após isso, voltou a funcionar normalmente... sugiro tentarem
> 
> tentei aqui e continua do mesmo jeito... tem algum comando pra desinstalar o venom ou é só apagar os arquivos?

>npm uninstall venom-bot

**Comment by yaustar** [comment]
Confirmed that uninstalling and re-installing venom bot also fixed this issue for me. Weird

**Comment by jwandekoken** [comment]
I was having the same issue, as reported [here](https://github.com/orkestral/venom/issues/2155). After deleting node_modules, package.lock and re-installing it is working again as well.

**Comment by can1871** [comment]
I installed the module again in a clean empty folder and created the json files again. It worked for me.
