### ISSUE TITLE
The client.onMessage event stop working after the first client.sendText method call

### ISSUE THREAD

**Issue by jwandekoken** [orkestral/venom#2155]
## Description

This is the first time I am testing the project, so, forgive me if I am doing something wrong. But I am having this weird behavior where the `client.onMessage` stop working after I call the `client.sendText` method. 

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** chrome
- **OS:** linux
- **Node version:** 16

## Steps to Reproduce

```typescript
import { create, Whatsapp } from "venom-bot";

import { matchInitialMessage, getNameFromInitialMessage } from "./utils/string";

create({
  session: "test-001",
})
  .then((client) => start(client))
  .catch((error) => {
    console.log(error);
  });

function start(client: Whatsapp) {
  client.onMessage((message) => {
    console.log("message.body: ", message.body);

    const matchResult = matchInitialMessage(message.body);
    if (matchResult && matchResult.length) {
      const name = getNameFromInitialMessage(matchResult[0]);

      client
        .sendText(
          message.from,
          `Olá, ${name}. Para iniciarmos o seu atendimento, digite uma das opções a seguir:`
        )
        .then((res) => {
          console.log("res: ", res);
        })
        .catch((error) => console.log("error: ", error));
    }
  });
}

```

After I call `client.sendText`, the messages that I send to the bot are not logged anymore, it seems that the `client.onMessage` event is not working anymore after that. Someone already had this issue?

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jwandekoken** [comment]
As reported [here](https://github.com/orkestral/venom/issues/2152), after deleting node_modules, package.lock and re-installing it is working again as well.

**Comment by wesley-blanco** [comment]
Here, when using a new whatsapp account, the same problem occurs, only the first message works (the other messages doesn't return, it is frozen). 

When I use an older account , the problem does not occur.

 I already deleted folders (tokens, node modules and etc...), reinstalled, updated dependencies and it didn't work.
