### ISSUE TITLE
export qrcode via web

### ISSUE THREAD

**Issue by Lohuama** [orkestral/venom#2162]
I'm exporting the qrcode via an html page, so far ok. The problem is when I refresh the page, then the socket stops sending the qrcode to the page. So I think I need to restart venom-bot, does anyone know how to restart venom with nodejs?

**Comment by Jlperich** [comment]
To correct a similar situation, I saved the qr_code (base64) whenever updated in venom. And from the frontend I called this endpoint to get the most updated one within a setInterval()

**Comment by Lohuama** [comment]
wow, does it work like that? That's all it takes for me to deliver the project. would you have an example?

**Comment by Jlperich** [comment]
`axios.get(cacheBuster('http://localhost:3005/api-whatsapp/start'));
qrCodeValidate = setInterval(async () => {
    const qrCodeApi = await axios.get(cacheBuster('http://localhost:3005/api-whatsapp/qrcode'))
    if (qrCodeApi.qr_code) {
        setQrCode(qrCodeApi.data.qr_code)
    }
}, 2000);
getStatusConnected = setInterval(async () => {
    statusValidation = axios.get(cacheBuster('http://localhost:3005/api-whatsapp/status')).then((statusValidation) => {
        if (statusValidation.connected) {
            setWhatsappConnected(true)
        }
    })
}, 10000);

setTimeout(() => {
    clearInterval(refreshIntervalId);
    clearInterval(getStatusConnected);
}, 150000);`

**Comment by Jlperich** [comment]
setQrCode and setWhatsappConnected is are my functions to set what to display on the screen, I used the React framework

**Comment by Jlperich** [comment]
('http://localhost:3005/venom-bot/status')
('http://localhost:3005/venom-bot/qrcode')

Create inside the venom bot project two functions for you to get the qrCode saved in a file and the status if it is connected or not
