### ISSUE TITLE
Reply not received in onAnyMessage()

### ISSUE THREAD

**Issue by matheusfterra** [orkestral/venom#2164]
Hii, how are you?

When someone send to whatsapp any message in reply, the venom not recognize the message. He simple not receive in onAnyMessage(). 

Exists some way to solve? 

I'm lost so much messages.

Venom version(s): 4.3.7
OS: Ubuntu 22.04
Node version: Node 18.13

Thank you so much.

**Comment by LucasSGomide** [comment]
Not sure if you already solved the issue, but I downgraded venon version to 4.3.6 and solved for me.
