### ISSUE TITLE
PROBLEMA AO ENVIAR LISTA DE CONTATO

### ISSUE THREAD

**Issue by ojauumdev** [orkestral/venom#2188]
Bom dia, estou com problemas ao disparar uma lista de contato, segue o erro:
![ERRO](https://user-images.githubusercontent.com/115158157/225642895-37383ad9-3db6-4387-b30a-d28d20fed078.png)

**Comment by ojauumdev** [comment]
Ainda náo foi resolvido.

**Comment by jonalan7** [comment]
this problem has now been fixed!
