### ISSUE TITLE
Error launch: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by LestterX** [orkestral/venom#2193]
It doesn't start on Debian server from Google Cloud Plataform

It has no interface. Does Venom-bot necessary need interface for it to work?
If it needs an interface, how can I deploy it? Some windwos server? Or another linux?

Thats the error bellow:

/home/lgsal/backend/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
0|backend- |
0|backend- |
0|backend- | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|backend- |
0|backend- | info:     [Loja] Error no open browser....

Could someone please help?

**Comment by 618457** [comment]
Same problem in CentOs 7.

**Comment by LestterX** [comment]
I solved this problem just installing Google Chrome on the server (No interface server linux based) and started venom-bot HEADLESS: TRUE and maybe USECHROME: TRUE.
I also deletede the node_modules and tokens directories

Installing chrome on linux: https://pt.wikihow.com/Instalar-o-Google-Chrome-Usando-o-Terminal-no-Linux

**Comment by Oladapodaniel** [comment]
> I solved this problem just installing Google Chrome on the server (No interface server linux based) and started venom-bot HEADLESS: TRUE and maybe USECHROME: TRUE. I also deletede the node_modules and tokens directories
> 
> Installing chrome on linux: https://pt.wikihow.com/Instalar-o-Google-Chrome-Usando-o-Terminal-no-Linux

This didn't help as i encountered errors while installing Google Chrome on the server, is there any other solution that works??

**Comment by LestterX** [comment]
> > I solved this problem just installing Google Chrome on the server (No interface server linux based) and started venom-bot HEADLESS: TRUE and maybe USECHROME: TRUE. I also deletede the node_modules and tokens directories
> > 
> > Installing chrome on linux: https://pt.wikihow.com/Instalar-o-Google-Chrome-Usando-o-Terminal-no-Linux
> 
> This didn't help as i encountered errors while installing Google Chrome on the server, is there any other solution that works??

That's how it worked for me. I think that if you solve that chrome issue it may work. I don't know if Mozilla Firefox works. Just a reminder, Google Chrome on Linux based servers needs to be without interface for it to work running on background or something. The way a installed is shown on the weblink I posted
