### ISSUE TITLE
Message Events not firing after successful QR code scan

### ISSUE THREAD

**Issue by ghayman** [orkestral/venom#2196]
## Description

Message Events not firing after successful QR code scan

## Environment

- **Venom version(s):** 4.3.7
- **Browser:** Headless and Full Chrome
- **OS:** Mac OSX & Linux (not tested on Windows)
- **Node version:** 18.14.0

## Steps to Reproduce

1. Register new session
2. Wait for QR code
3. Scan QR successfully
4. "Client Started" just fine
5. Try and send a message - nothing received

## Log Output

There is an uncaught exception in the browser that is stopping it from loading the message handlers

NOTE: fix to follow....

**Comment by ghayman** [comment]
The uncaught exception comes from the code snippet - I have wrapped it on a try/catch that seems to have fixed it.

It would appear that the o.m for loop is producing an idx that is non-existent in the o array

 
<img width="980" alt="Screenshot 2023-03-22 at 5 26 19 PM" src="https://user-images.githubusercontent.com/3300798/227068551-b1cc4f24-f4c1-4142-ac67-c835c0317990.png">

**Comment by ZerXus** [comment]
Same there!
