### ISSUE TITLE
Múltiplos acessos

### ISSUE THREAD

**Issue by Juuhz** [orkestral/venom#22]
Pessoal, boa tarde.

Tenho uma dúvida:

Há a possibilidade de utilizar o Venom-Bot + Whatsapp web no PC?

Estou tentando aqui mas um derruba o outro, os 2 não conseguem coexistir.

**Comment by orkestral** [comment]
Não tem como pois venom usa o token gerado pela Whatsapp web, e gera um token único, não tem como utilizar nos 2 apenas em 1 só
