### ISSUE TITLE
SendButtons not working on multi-device

### ISSUE THREAD

**Issue by betohg** [orkestral/venom#2200]
## Description

The whole conversation is erased and the buttons are not showing on android devices

## Environment

- **Venom version(s):** [4.3.7]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [18.12.1]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
client.onMessage(async(message) => {
    const buttons = [
        {
          "buttonText": {
            "displayText": "Text of Button 1"
            }
          },
        {
          "buttonText": {
            "displayText": "Text of Button 2"
            }
          }
        ]
    if (message.body === 'hi') {
        try{
            await client.sendButtons(message.from, 'Buttons',buttons,'description')
            
        }
        catch(err){
            console.log(err)
        }
      
    }
  });
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by FaelN1** [comment]
The function of sending buttons is under maintenance indefinitely.

**Comment by LuukPlay** [comment]
is the send button function really not working?
