### ISSUE TITLE
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isWidlike')

### ISSUE THREAD

**Issue by thiMoreira** [orkestral/venom#2204]
Version 4..3.7

when sending a message to the group, this error is popping and I could not identify where this problem would be, someone to help me please?

**Comment by FaelN1** [comment]
Hello friend, use the command "npm update @wppconnect/wa-js --save" and your problem will be solved.

**Comment by thiMoreira** [comment]
> Hello friend, use the command "npm update @wppconnect/wa-js --save" and your problem will be solved.

I used this command and it didn't work, still the same error
