### ISSUE TITLE
[Question] [Thank you] Send message later when currently offline

### ISSUE THREAD

**Issue by POTATOES-BoilEm-MashEm-StickEm-inAStew** [orkestral/venom#221]
Dear Sir/Madam,

first off I want to thank you so much for this tool. For all the hard work, for the great documentation. I know that WhatsApp does actively monitor "spam" and disallow bots but you have actually found a way to get an API - kind off. I hope your work will continue to live since such a tool is technically illegal in the marketer$ eyes of Facebook. BS.

You have helped me automate processes in my live, sending reminders to groups of friends in WhatsApp saving me time. It is actually funny and really interesting to create a nodeJS program using this library and sending reminders on when to put the garbage outside and when the washing machine is done. Once again thanks.

I have more of a question that a big issue. Feel free to close it if you deem it answered.
If my phone is currently offline and i send a message using venom it will not arrive. It (whatsapp-web in this case) requires a phone to be online and connected. I do not want a separate phone to online 24/7 as a kind of server. 

Is there a way or tool you know that can send a message even if it is failed currently by sending it when the phone is connected again later?

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
Nevermind figured it all out by myself.
Wasn't using `await` in an `async function`.

**Comment by Fredwuz** [comment]
https://github.com/orkestral/venom#callback-status-session 
In the readme is noted that it is possible to detect if the phone gets disconnected but I think it can only check when you start the Client maybe its also possible to check while the bot is running with the "onStateChange" function but I am not sure what it does exactly so you can try it :D
https://github.com/orkestral/venom#events

**Comment by leobevi** [comment]
@POTATOES-BoilEm-MashEm-StickEm-inAStew .....
I don't know if there is a possibility for the API to save the message to be sent later .... I don't know how your application is developing but I think you should analyze the status of your connection before sending the messages.
Analyzes the Status,
If you are not logged on, 
	save pending messages in a file or database,
	when the status changes to connected you analyze the pending messages to send in the file or database.

`

// Before sending the message
	var v_status = await srv.getConnectionState();
   
  if(v_status === 'CONNECTED'){
	  retornoenvio =  await srv.sendText(numeroenvio+'@c.us', messagetosent);                          

  }else{
	  
	save the message to a file or database file to send later
  }                   



//in the Status change event
 client.onStateChange( async (state) => {
	if(status === 'CONNECTED'){
		
		Find pending message to send and send
	
	}
 });

`

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
Oh that's interesting that can actually help me. Thank you!
