### ISSUE TITLE
onMessage Json changed

### ISSUE THREAD

**Issue by can1871** [orkestral/venom#2214]
Hi, has the json in the onMessage function changed? The isGroupMsg parameter that I use the most and many parameters are not coming.
Below is an example of the json:

{
  id: 'false_120XXXXXXXXX8@g.us_23B6XXXXXXXXXXXXXXXA_905XXXXXXXXX@c.us',
  body: 'test',
  type: 'chat',
  t: 1680266151,
  notifyName: 'TEST',
  from: 'XXXXXXXXXXXXX@g.us',
  to: '905XXXXXXXXX@c.us',
  author: '905XXXXXXXXX@c.us',
  self: 'in',
  ack: 1,
  isNewMsg: true,
  star: false,
  kicNotified: false,
  recvFresh: true,
  isFromTemplate: false,
  pollInvalidated: false,
  isSentCagPollCreation: false,
  latestEditMsgKey: null,
  latestEditSenderTimestampMs: null,
  broadcast: false,
  mentionedJidList: [],
  groupMentions: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  labels: [],
  hasReaction: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  stickerSentTs: 0,
  isAvatar: false,
  requiresDirectConnection: false,
  chatId: 'XXXXXXXXXXXX@g.us',
  fromMe: false,
  sender: {
    id: '905XXXXXXXXX@c.us',
    name: 'TEST Demo',
    shortName: 'TEST Demo',
    pushname: 'Test',
    type: 'in',
    verifiedName: 'Test',
    isBusiness: true,
    isEnterprise: false,
    isSmb: true,
    verifiedLevel: 0,
    privacyMode: null,
    labels: [],
    isContactSyncCompleted: 1,
    formattedName: 'TEST Demo',
    displayName: 'TEST Demo',
    formattedShortName: 'TEST Demo',
    formattedShortNameWithNonBreakingSpaces: 'TEST Demo',
    isMe: false,
    mentionName: 'TEST Demo',
    notifyName: 'Test',
    isMyContact: true,
    isPSA: false,
    isUser: true,
    isWAContact: true,
    profilePicThumbObj: {
      eurl: 'https://pps.whatsapp.net/v/t61.
      id: '905XXXXXXXXX@c.us',
      img: 'https://pps.whatsapp.net/v/t61.24694-24/3FE',
      imgFull: 'https://pps.whatsapp.net/v/t61-4&oh=01_AdTOZl8pmV9sZ3yC127DF9ds8VxltEFE',
      tag: '1668070743'
    },
    msgs: null
  },
  timestamp: 1680266151,
  content: 'test',
  chat: {},
  mediaData: {}
}

**Comment by can1871** [comment]
As far as I understand, the chat parameter is {}.

**Comment by Divino67** [comment]
Same problem here, multiple properties are not coming or coming empty. Including the chat property, which is the one I use the most.
