### ISSUE TITLE
is version 5.0.0 working on windows operating system?

### ISSUE THREAD

**Issue by markseng** [orkestral/venom#2234]
i updated to version 5.0.0 but it doesn't work anymore in windowns 
in the application it seems that you are logged in chrome from linux

**Comment by antonio-emilio** [comment]
Isn't working for me neither... it's stuck on "Waiting... checking the browser"...

**Comment by markseng** [comment]
It didn't work for me.
Does anyone know how I can specify the use of a specific chrome?
in the documentation reports that it is possible but it is not clear how to do it.

**Comment by bielgvs** [comment]
Hello

I was having the same problem, what solves it for me was downgrading the puppeteer version to 14.4.1

**Comment by jonalan7** [comment]
the useChrome function will be removed from the project, I will create another tag so you can add the browser path!
