### ISSUE TITLE
Token Expired Asking for scanning again

### ISSUE THREAD

**Issue by BhagavatiAntala** [orkestral/venom#2235]
When I have upgrade the package it again asked for QR code scanning. And when I switch to the older version again. It automatically detects the token.

**Comment by guh0rzd** [comment]
same error here

**Comment by Feeh03114** [comment]
same error here

**Comment by jonalan7** [comment]
the token is working normally! I tested it here, make sure the machine has permission to create a file or you must be launching the browser in incognito mode!
for example if you put the following parameter in the arguments settings:
```
{
browserArgs: ['--incognito']
}
```
the browser will enter incognito mode so it will not load the token nor save!

see how i am starting and loading the token normally!

```
(async () => {
  create({
    session: 'session-name',
    headless: false
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

async function start(client) {

}

})();

```

![image](https://user-images.githubusercontent.com/67329824/235194709-5298fa9a-a2d7-4594-8929-976a1e480dfc.png)

see the example it creates a token in the local path
token/session-name
in case you want to change the path
```
{
       folderNameToken: "tokens", // folder name when saving tokens
       mkdirFolderToken: ''", //tokens from folder directory, just inside venom folder, example: { mkdirFolderToken: '/node_modules', } //will save tokens folder to node_modules directory
}
```
