### ISSUE TITLE
SendButtons Doesn't working

### ISSUE THREAD

**Issue by guh0rzd** [orkestral/venom#2237]
sendbuttons function doesnt working on new 5.0.0 version

## Environment

- **Venom version(s): 5.0.0

**Comment by Ridtt** [comment]
#2219

**Comment by Ridtt** [comment]
And same as #2200
I think its about whatsapp web changes, many library struggling this atm. 
Hope for best devs can do to find new ways to export this functionality to library again.

**Comment by scatrus** [comment]
working only in whatsapp web.

**Comment by jonalan7** [comment]
Currently, you can only push the buttons to the iPhone and the web, not yet able to push to android devices!
