### ISSUE TITLE
OnAck can only listen for messages sent, but not received messages

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#225]
OnAck can only listen for messages sent, but not received messages

**Comment by joaosouz4** [comment]
ack captures only outgoing messages so you can stay on top of new message statuses.

**Comment by joaosouz4** [comment]
to receive messages use onMessage

**Comment by bhavya32** [comment]
@joaosouz4 I think the issue should be closed.

**Comment by Lucipher** [comment]
ok, I think so
