### ISSUE TITLE
Version 5.0.0 is not working

### ISSUE THREAD

**Issue by thiagomartins89** [orkestral/venom#2252]
## Description

I installed version 5.0.0 but it's not working anymore. The QR code appears and after scanning it, it shows as connected. It also shows as active on my phone. However, I noticed that the 'tokens' folder is not being created and messages are not arriving in the onMessage event. Does anyone know what the issue might be?

✓ Successfully connected!
✓ [instance: session-name]: Connected
✓ Successfully main page!

I also noticed that on the WhatsApp mobile app, it appears as Google Chrome (Linux), whereas on version 4.3.7, it appeared as Google Chrome (Windows).

## Environment

- **Venom version(s):** 5.0.0
- **Browser:** Google Chrome 112.0.5615.138
- **OS:** Windows 11 Home
- **Node version:** 18.14.0

## Code

const venomBot = require("venom-bot");

venomBot
  .create({
    session: "session-name",
  })
  .then((client) => start(client))
  .catch((err) => console.log(err));

function start(client) {
  client.onMessage(async (message) => {
    console.log(message.body);
  });
}

**Comment by TiagoGouvea** [comment]
Sometimes it just stucks on the initial message:

```
You're up to date 🎉🎉🎉
 /\\\      /\\\ /\\\\\\\\\\  /\\\\\     /\\\    /\\\\\\\\    /\\\      \\\\              /\\\\\\\\      /\\\\\\\\    /\\\\\\\\\\\\
 \/\\\     /\\\ \/\\\_____/  \/\\\ \\\  \/\\\  /\\\_____/\\\ \/\\\ \\ \\ \\\             \/\\\   \\\   /\\\_____/\\\ \/___/\\\___/
   \/\\\   /\\\  \/\\\        \/\\\ /\\\ \/\\\ \/\\\    \/\\\ \/\\\  \\\  \\\             \/\\\   \\\  \/\\\    \/\\\     \/\\\
    \/\\\  /\\\   \/\\\\\\\\\\ \/\\\  /\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\  /\\\\\\\\\ \/\\\\\\\    \/\\\    \/\\\     \/\\\
      \/\\\ \\\    \/\\\_____/  \/\\\ \/\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\ \/_______/  \/\\\   \\\\ \/\\\    \/\\\     \/\\\
       \/\\\\\\     \/\\\        \/\\\ \ /\\\ \\\ \/\\\    \/\\\ \/\\\  \\\  \\\             \/\\\    \\\ \/\\\    \/\\\     \/\\\
        \/_/\\\      \/\\\\\\\\\\ \/\\\  \/_\\\\\\ \/_/\\\\\\\\\  \/\\\  \\\  \\\             \/\\\\\\\\\  \/_/\\\\\\\\\      \/\\\
          \/__/       \/________/  \/_/    \/____/    \/_______/   \/_/ \/_/ \/_/              \/______/      \/_______/       \/_/



⠋ Waiting... checking the browser...
  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

✓ Browser successfully opened
✓ headless option is active, browser hidden
✓ Page successfully accessed
✓ Successfully connected!
✓ [instance: Chat-GPT]: Connected
✓ Successfully main page!
```

and the `create()` never finishes, never get to the `then` promisse.

**Comment by clarobcle** [comment]
> ## Description
> I installed version 5.0.0 but it's not working anymore. The QR code appears and after scanning it, it shows as connected. It also shows as active on my phone. However, I noticed that the 'tokens' folder is not being created and messages are not arriving in the onMessage event. Does anyone know what the issue might be?
> 
> ✓ Successfully connected! ✓ [instance: session-name]: Connected ✓ Successfully main page!
> 
> I also noticed that on the WhatsApp mobile app, it appears as Google Chrome (Linux), whereas on version 4.3.7, it appeared as Google Chrome (Windows).
> 
> ## Environment
> * **Venom version(s):** 5.0.0
> * **Browser:** Google Chrome 112.0.5615.138
> * **OS:** Windows 11 Home
> * **Node version:** 18.14.0
> 
> ## Code
> const venomBot = require("venom-bot");
> 
> venomBot .create({ session: "session-name", }) .then((client) => start(client)) .catch((err) => console.log(err));
> 
> function start(client) { client.onMessage(async (message) => { console.log(message.body); }); }

Thiago eu voltei pra versao 4.3.7 pois ela ainda funciona, vou esperar a nova versao ficar estavel.

**Comment by guh0rzd** [comment]
a versão 5.0.0 está funcionando, só que com muitos erros...
depois dessa msgns aparecerem no terminal: 
✓ Browser successfully opened
✓ headless option is active, browser hidden
✓ Page successfully accessed

ele demora para responder/reconhecer as msgns recebidas, mas depois de uns minutos ele funciona (com muitos erros)

**Comment by TiagoGouvea** [comment]
É.. melhor então voltar pra anterior mesmo.

**Comment by astafieff** [comment]
Hoje após deletar a pasta tokens a api subiu, mas está com o load bem lento, principalmente na etapa  waitChat.
