### ISSUE TITLE
Is onAnyMessage working now?

### ISSUE THREAD

**Issue by ZerXus** [orkestral/venom#2256]
Cant find any listener that work well to recieve incoming and outcoming messages

**Comment by jonalan7** [comment]
you must use the onAnyMessage is working normally! If it takes too long, it may be that you are running on a machine that is already using all the resources!

```
    client.onAnyMessage((msg) => {
      console.log('Msg: ', msg);
    });
```

**Comment by ZerXus** [comment]
Its dont working on my wa
![image](https://user-images.githubusercontent.com/50263574/236426039-74ef8673-a6a7-4bdc-b2c8-f68cd37b419a.png)
![image](https://user-images.githubusercontent.com/50263574/236431566-dd62b5e3-5ba1-4df8-b66e-8358394921ab.png)

**Comment by jonalan7** [comment]
put your code here for us to see?

**Comment by ZerXus** [comment]
import { create, Whatsapp as WhatsappVenom } from 'venom-bot';
import fs from "fs";

import paths from "../utilities/paths.js";
import Database from "../database/database.js";
import whatsappMessage from "../whatsappMessage/whatsappMessage.js";


export default class Whatsapp {
    constructor(manager) {
        this.manager = manager;
        this.options = {
            session: this.manager,
            headless: false,
            // mkdirFolderToken: './data',
            disableWelcome: true,
            updatesLog: false,
            devtools: false, // Open devtools by default
            debug: false, // Opens a debug session,
        };
        this.db = Database;
    }

    startClient() {
        create(this.options)
            .then(client => {
                this.tryCatchSIGINT(client, () => this.onMessageEvent(client));
            })
            .catch(error => {
                if (!error) return;
                console.log(error);
            });
    }

    tryCatchSIGINT(client, callback) {
        process.on('SIGINT', () => {
            console.log("Stopping WA-Bot");
            client.close();
        });
        try {
            this.client = client;
            callback();
        } catch (error) {
            console.log(error);
            this.client.close();
        }
    }

    onMessageEvent() {
        this.client.onAnyMessage(incomingMessage => {
            console.log(incomingMessage);
            // if (incomingMessage.chatId === 'status@broadcast') return;
            //
            // new whatsappMessage(incomingMessage, { client: this.client, manager: this.manager }).parse()
            //     .then(message => {
            //         this.db.storeMessage(message);
            //     });
        })
        // this.client.onMessageEvent(msg => console.log(msg));
    }
}

**Comment by jonalan7** [comment]
try to run like this!

import { create } from 'venom-bot';

(async () => {
  create({
    session: 'session-name', //name of session
    headless: false
  })
    .then((client) => start(client))
    .catch((erro) => {
      console.log(erro);
    });

  function start(client) {
    client.onAnyMessage((msg) => {
      console.log('Msg: ', msg);
    });
  }

})();

**Comment by jonalan7** [comment]
solved?

**Comment by ZerXus** [comment]
Haven't checked yet, I'll answer when I check

пт, 5 мая 2023 г., 19:35 Jónalan de Lima ***@***.***>:

**Comment by ZerXus** [comment]
Hello! This one dont work too 
![image](https://github.com/orkestral/venom/assets/50263574/b276313a-fa24-4e1d-bc7b-863fc1ee5667)

**Comment by ZerXus** [comment]
and sessions dont save, i cant ctrl+c and then re-login again with qr-code

**Comment by keinou** [comment]
solved?
