### ISSUE TITLE
How to update the chats to unread/ all/ unseen chats in whatsapp web

### ISSUE THREAD

**Issue by rahulbansal16** [orkestral/venom#2258]
Hi,
I trying to use the venom library to filter out chats on whatsapp web using chrome extension.

I am injecting the wapi library as a content script and Window.Store object is getting initialised.

This is the code I am using for filtering out the chats.
```
const showAllChats =  () => {
  let model = getChatModel();
  // console.log("showAllChats model before :", model);
  model.forEach((chat) => {
    updateObj(chat, true, "__x_shouldAppearInList");
  });  
  refreshChat(model);
};
```

```
const getChatModel = () => {
  return window.Store.Msg._models;
};

```

```
const refreshChat = (model) => {
  model[0].__x_t = model[0].__x_t + 1;
};
```
I am not able to update the chats using the above code. Any suggestion on achieveing the same?

**Comment by jonalan7** [comment]
I don't quite understand what you want to do!
do you want to list for example all group chats?
