### ISSUE TITLE
não tem como enviar botões !!

### ISSUE THREAD

**Issue by Kauaevangelista** [orkestral/venom#2260]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Documentation: https://orkestral.github.io/venom/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
- Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by jonalan7** [comment]
You can send buttons, but they have problems receiving on android devices!

```
const buttons = [
  {
    "buttonText": {
      "displayText": "Text of Button 1"
      }
    },
  {
    "buttonText": {
      "displayText": "Text of Button 2"
      }
    }
  ]
await client.sendButtons('000000000000@c.us', 'Title', buttons, 'Description')
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

```

**Comment by Kauaevangelista** [comment]
> Você pode enviar botões, mas eles têm problemas para receber em dispositivos Android!
> 
> ```
> const buttons = [
>   {
>     "buttonText": {
>       "displayText": "Text of Button 1"
>       }
>     },
>   {
>     "buttonText": {
>       "displayText": "Text of Button 2"
>       }
>     }
>   ]
> await client.sendButtons('000000000000@c.us', 'Title', buttons, 'Description')
>   .then((result) => {
>     console.log('Result: ', result); //return object success
>   })
>   .catch((erro) => {
>     console.error('Error when sending: ', erro); //return object error
>   });
> ```

eu testei em vários dispositivos android porém todos deram erro, eu não tive a oportunidade de enviar para um dispositivo ios, mas tem alguma ideia de que no futuro será possivel enviar os botões no android?
