### ISSUE TITLE
[BUG] Cannot acess the link

### ISSUE THREAD

**Issue by himanshu1221** [orkestral/venom#2265]
## Description

when we click on get started we are not able to go to docs page

## Environment

- **Venom version(s):** 4.3.3
- **Browser:** Chrome 113.0.5672.63

## Steps to Reproduce

1. Go to official website
2. Click on get started

## Additional context / Screenshot

![Screenshot from 2023-05-08 16-08-33](https://user-images.githubusercontent.com/32031706/236803520-7bc9c113-cf68-4ae1-b167-c95ff8974eff.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dpaes** [comment]
#2221 , #2254  ,  #2264 , have the same problem...
