### ISSUE TITLE
triggerCriticalSyncLogout is not function

### ISSUE THREAD

**Issue by AlejandroBlackburn** [orkestral/venom#2266]
I have a bot working, but recently it is giving me the following error: 

![Screenshot.](https://i.imgur.com/XNASXBx.png)

In my code I am not using the logout function at any time, because I need the bot working 24/7, so I find it very strange that this happens. I am thinking there is some kind of inactivity shutdown, can it be removed?

**Comment by jonalan7** [comment]
I'm going to fix this problem, but it happens that your server or machine is running out of internet! Remember that if you run out of internet the functions will not work!

**Comment by thalles7765** [comment]
I have same problem, my vps is hosted, don't believe it's problem internet, but i'll more tests find result.

**Comment by w7br** [comment]
Hello, I also have the same issue. It seems to be a version compatibility problem with Puppeteer, but it's just an assumption. I'm eagerly awaiting the resolution of this amazing bot. I'm integrating it with ChatGPT using synthesized audio and speech recognition to enable audio responses as well. However, this error has slightly disrupted my progress. I appreciate any correction or suggestion on how to resolve it. Thank you in any case.

**Comment by morenodelas** [comment]
I'm facing the same problem I'm waiting for the problem to be solved

**Comment by danilogeronimo** [comment]
Same problem here.

**Comment by sewmer** [comment]
Alguma solução para isso mesmo problema aqui

**Comment by xbral** [comment]
I'm having the same error. I tried to disconnect from my local internet in order to validate the hypothesis that the connection was lost on the server, but the error did not occur. Reading the code where the error is triggered, I saw that it uses spinnies in some functions where the error is popping, I was using disableSpins as "true", I will try to remove this configuration to see if it solves it, and I will tell you here tomorrow.

**Comment by sewmer** [comment]
I verified that when the internet connection loses connection and comes back quickly it generates this error, would there be any way to avoid this error so that the bot does not disconnect?

**Comment by xbral** [comment]
> I verified that when the internet connection loses connection and comes back quickly it generates this error, would there be any way to avoid this error so that the bot does not disconnect?

The phone disconnects or the server?

**Comment by sewmer** [comment]
> > Verifiquei que quando a conexão com a internet perde a conexão e volta rapidamente gera esse erro, teria como evitar esse erro para que o bot não desconecte?
> 
> O telefone desconecta ou o servidor?
I did the test on the local server, disconnecting the internet and quickly reconnecting, and it generated the same error

**Comment by tataredhaalfath** [comment]
I have same problem with this. but why this issues is already closed yet ? 
anyone can explain how to solved this problem ? i need my bot runnint 24/7, thankyou all

**Comment by AlejandroBlackburn** [comment]
> I have same problem with this. but why this issues is already closed yet ? anyone can explain how to solved this problem ? i need my bot runnint 24/7, thankyou all

My solution was to switch to wppconnect, they have a method called Watchdog that keeps the connection alive.
