### ISSUE TITLE
Buttons not working in android devices

### ISSUE THREAD

**Issue by sostenesapollo** [orkestral/venom#2267]

**Comment by julioreisdev** [comment]
I'm with the equal problem. The buttons sent in `sendButtons` function dont sent to **Android** devices, only IOS devices and WhatsApp Web.
![WhatsApp Image 2023-05-10 at 10 46 24](https://github.com/orkestral/venom/assets/89112561/e5285029-abe0-4297-80c4-2736536e1dac)
![WhatsApp Image 2023-05-10 at 10 47 37](https://github.com/orkestral/venom/assets/89112561/6473e3d1-dc62-4265-8c73-2713a1dc1dd4)
![WhatsApp Image 2023-05-10 at 10 47 54](https://github.com/orkestral/venom/assets/89112561/95054ed9-4d8d-48ae-856d-fa548b8aacf8)

**Comment by guh0rzd** [comment]
SendListMenu também parou de funcionar

**Comment by jonalan7** [comment]
Buttons are not working because Meta is preventing access to them. There's nothing to do, unfortunately!

**Comment by julioreisdev** [comment]
Thank!
