### ISSUE TITLE
Problem Puppeteer in version 5.0.0 and 5.0.1

### ISSUE THREAD

**Issue by matheusfterra** [orkestral/venom#2271]
Hi, after upgrade to 5.0.0 or 5.0.1 version, all times there I run, I receive this error:

![image](https://github.com/orkestral/venom/assets/25447579/13dfe4d2-61e8-4a40-9703-4af9e1d4361c)

I think this is a Puppeter error, because the warning message in start:

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

Someone know how fix this? Thank you!

**Comment by evandrosk** [comment]
```
[DEBUG] Whatsapp status: initBrowser PokerBot
- Waiting... checking the browser...

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
- Error no open browser....
[DEBUG] Whatsapp status: noOpenBrowser PokerBot
Error onCreate: Error no open browser....
```

**Comment by guh0rzd** [comment]
eu instalei a versão 14.4.1 do puppeteer e tá funcionando normal, tenta isso:

npm install puppeteer@14.4.1

**Comment by jonalan7** [comment]
```
  {
  headless: true, // you should no longer use boolean false or true, now use false, true or 'new' learn more https://developer.chrome.com/articles/new-headless/
  }
```

**Comment by klebinhopk** [comment]
![image](https://github.com/orkestral/venom/assets/16194393/22cc334d-0c8e-4d4b-88c0-2d19dedf4c4e)
I have this problem, do you know how to solve it?

**Comment by guh0rzd** [comment]
recomendo parar de usar o venom-bot e usar o wpp-connect, são bem parecidos, mas o wpp connect dá menos problemas
