### ISSUE TITLE
Docs page not working 

### ISSUE THREAD

**Issue by vspok** [orkestral/venom#2280]
## Docs page not working 
![image](https://github.com/orkestral/venom/assets/59256568/27f1a953-7e0a-4533-ac27-ad895e516ff6)
![image](https://github.com/orkestral/venom/assets/59256568/6afb2143-a8c2-46b7-ae99-1ed492d2aeaa)

**Comment by PwccaCode** [comment]
meses q ta assim

**Comment by PedroPaduelo** [comment]
ta mesmo

**Comment by dpaes** [comment]
#2221 , #2254 , #2264 , #2265 , have the same problem...
