### ISSUE TITLE
SendLinkPreview showing black preview image

### ISSUE THREAD

**Issue by brainwares** [orkestral/venom#2281]
## Description

Hi,
I tried using SendLinkPreview as the example, but the preview image is showing black image.
Is there any way to show the right preview image?

## Environment

- **Venom version(s):** 5.0.5
- **Browser:** 113.0.5672.127
- **OS:** Windows 11
- **Node version:** Node 16

**Comment by jonalan7** [comment]
for this function to work in this useful update I had to put any meta image, in the next updates I can fix this problem, soon!

**Comment by marciusbezerra** [comment]
sendLinkPreview is returning a black image (venom-bot 5.0.11)

![image](https://github.com/orkestral/venom/assets/1328224/ee2ffcf8-7984-4a27-a3e6-6ca676bea4c8)
