### ISSUE TITLE
client.getAllUnreadMessages() not work :/

### ISSUE THREAD

**Issue by lisboadas** [orkestral/venom#2282]
## Description

I'm trying to pull unread messages and it returns as if the function no longer exists.

## Environment

- **Venom version(s):** 5.0.1
- **Browser:** Google Chrome 113.0.5672.126
- **OS:** Ubuntu 20.04
- **Node version:** 18.13.0

## Log Output

const messages = await client.getAllUnreadMessages();
TypeError: client.getAllUnreadMessages is not a function

**Comment by jonalan7** [comment]
use the function: getUnreadMessages()
