### ISSUE TITLE
Illegal Instruction - Centos 7

### ISSUE THREAD

**Issue by serobalino** [orkestral/venom#2285]
## Description
When I run my application with venom-bot I get an error in the console that says Illegal Instruction, in Centos 7

## Environment

- **Venom version(s):** [4.3.7]
- **OS:** [Centos 7]
- **Node version:** [14.21.3]

## Steps to Reproduce

1. Create JS Project
Create black project of Express

2. Install
Install venom-bot@4.3.7

3. Import venom-bot in index.js file
const venom = require("venom-bot");

4. Test project
npm run start

## Log Output

```
sd@s bot-whats]$ sudo npm run start
[sudo] password for sd: 

> bot-whats@1.0.0 start /home/sd/bot-whats
> node index

Instrucción ilegal
```

## Additional context / Screenshot

It is only a blank project to create an application with venom and express but it does not work. When removing the import of venom-bot the application worked without problem. I need help please

**Comment by V3llens** [comment]
venom-bot@4.3.7 is no longer supported due to deprecated version of puppeteer, try installing the latest version of venom-bot

**Comment by serobalino** [comment]
I updated the version of venom and it gives the same message

**Comment by fricgabriel** [comment]
i have the same problem

**Comment by bazzooka** [comment]
I have the same issue on: 
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

No GUI

google-chrome-stable is placed in the /usr/bin/google-chrome-stable

Any update?
