### ISSUE TITLE
how to generate more qrCode without having to restart the server?

### ISSUE THREAD

**Issue by Lohuama** [orkestral/venom#2289]
I'm exporting the qrCode to a web page, the problem is that after generating 5 or 6 times it doesn't generate any more qr codes, only if you restart the server, and also if you disconnect the device, to connect it again you also need to restart the server. Please can you help me to generate qrCodes just by refreshing the page without having to restart the server?

**Comment by jonalan7** [comment]
the browser and closed for 60 seconds only in qrcode! If you want to disable it just put it in the options
{
autoClose: 0, // Automatically close venom-bot only when scanning QR code (default 60 seconds, if you want to shut down, set 0 or false)
}
know more: [Optional create parameters](https://github.com/orkestral/venom#optional-create-parameters)

**Comment by jonalan7** [comment]
the question of the device that I did not understand very well! Could you make it clearer so I can help you?

**Comment by V3llens** [comment]
As said by jonalan7 you need to pass 'autoClose: 0' to generate more than 5 QR codes
![image](https://github.com/orkestral/venom/assets/91237058/559a478d-d725-43d8-a68d-51d3515a196e)

About the last question. Could you be more clear on what 'refreshing the page without having to restart the server' would mean? And if possible, share an image of your code to verify its configuration

**Comment by Lohuama** [comment]
> a questão do aparelho que não entendi muito bem! Poderia deixar mais claro para que eu possa te ajudar?

when the token expires and it is necessary to connect it again to the device, so every time this happens I need to restart the server.. I am looking for something that solves this problem

**Comment by Lohuama** [comment]
> Como dito por jonalan7 você precisa passar 'autoClose: 0' para gerar mais de 5 códigos QR ![imagem](https://user-images.githubusercontent.com/91237058/240951548-559a478d-d725-43d8-a68d-51d3515a196e.png)
> 
> Sobre a última pergunta. Você poderia ser mais claro sobre o que significa 'atualizar a página sem ter que reiniciar o servidor'? E se possível, compartilhe uma imagem do seu código para verificar sua configuração


this is my code to generate the qrCode and send it to a web page:
const io = socketIO(server);

io.on("connection", (socket) => {
  console.log("New Connection");
  CONNECTED = false;
  venom
    .create(
      "planRoute",
      (base64Qr, asciiQR, attempts, urlCode) => {
        console.log(asciiQR);

        console.log("att" + attempts);
        if (attempts >= 6) {
          socket.emit("notLogged");
          console.log("notLogged");
          // restartService();
        }
        var matches = base64Qr.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/),
          response = {};

        if (matches.length !== 3) {
          return new Error("Invalid input string");
        }
        response.type = matches[1];
        response.data = new Buffer.from(matches[2], "base64");

        var imageBuffer = response;
        require("fs").writeFile(
          "./views/out.png",
          imageBuffer["data"],
          "binary",
          function (err) {
            if (err != null) {
              console.log(err);
            }
          }
        );
        socket.emit("qrCode", "./views/out.png");
      },
      undefined,
      { logQR: false }
    )
    .then((client) => {
      whatsapp = client;

      CONNECTED = true;

      console.log("conectoou");

      socket.emit("CONNECTED");

      start(whatsapp);

      socket.emit("message", async () => {
        await fs.unlink("./views/out.png", (err) => {
          if (err) console.log(err);
          console.log("out.png deletado");
        });
      });
    })
    .catch((erro) => {
      socket.emit("notLogged");
      console.log(erro);
    });
});

the connection works, my problem is when the token expires or the device is disconnected, because it is necessary to read the qrCode again, but I cannot generate qrCode's automatically when disconnecting, I always have to restart directly from the server that is hosted to be able to generate new ones qrCodes

**Comment by V3llens** [comment]
You can create the connection inside a function, and if the token expires, the function will rerun the venombot creation. Something like that:
![image](https://github.com/orkestral/venom/assets/91237058/4a27aeea-58b6-4d16-bf0f-6559f09785d9)

Creating the connection in a separate function, it is possible to call it using socket.io or other desired methods instead of restarting the server

**Comment by pedro0506** [comment]
> I'm exporting the qrCode to a web page, the problem is that after generating 5 or 6 times it doesn't generate any more qr codes, only if you restart the server, and also if you disconnect the device, to connect it again you also need to restart the server. Please can you help me to generate qrCodes just by refreshing the page without having to restart the server?

Can you share the code for 'exporting the QR code'?
