### ISSUE TITLE
Page Closed

### ISSUE THREAD

**Issue by FernandoGambaro** [orkestral/venom#2290]
## Description
Hello, when you are starting venom-bot this error appears

✖ Erro intro
✖ [instance: sessionName]: Page Closed

## Environment

- **Venom version(s):** 
venom-bot@5.0.1 
- **Browser:** 
Chrome 113
- **OS:** 
Fedora 37
- **Node version:** 
Node v16.18.1

## Steps to Reproduce

 Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

After showing the QR code the Error appears

Not Logged
✖ Erro intro
✖ [instance: sessionName]: Page Closed

Note:
The error started after sending a message with empty text

Used code
I change code to this 
clienteWhatsapp = await create(
        //session
        'sessionName', //Pass the name of the client you want to start the bot
        //catchQR
        (base64Qrimg, asciiQR, attempts, urlCode) => {
          //console.log('Terminal qrcode: ', asciiQR);
          if (attempts >= 1) {
            console.log("Number of attempts to read the qrcode: ", attempts);
            socket.emit("image", base64Qr);
          }
          //socket.emit('msg', 'Scanee el código QR: intento ' + attempts);
          exportQR(base64Qr, "./public/images/fundacion-qr.png");
        },
        (statusFind) => {
          console.log("Como esta .status: " + statusFind);
          if (statusFind == "successChat") {
            console.log("socket.js create -> emito Ya conectado");
            socket.emit("msg", "Ya conectado");
            socket.local.emit("msg", "Ya conectado");
          }
          if (statusFind == "erroPageWhatsapp") {
            socket.emit("error", "Error accessing the page: 'https://web.whatsapp.com'");
          }
          if (statusFind == "initWhatsapp") {
            socket.emit("msg", "iniciando");
            socket.local.emit("msg", "iniciando");
          }
        },
        // statusFind
        (statusSession, session) => {
          //console.log("Status -> Session: ", statusSession);
          //console.log("estado de la session ", statusSession);
          if (statusSession == "qrReadSuccess" || statusSession == "isLogged") {
            sessionIniciada = true;
            socket.emit("msg", "Ya conectado");
          }
          if (statusSession == "qrReadFail") {
            sessionIniciada = false;
            socket.emit("error", "Error al intentar leer código QR");
          }

          //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken || chatsAvailable || deviceNotConnected || serverWssNotConnected || noOpenBrowser
          //Create session wss return "serverClose" case server for close
          console.log("Session name: ", session);
        },
        // options
        {
          folderNameToken: 'tokens', //folder name when saving tokens
          mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
          headless: true, // you should no longer use boolean false or true, now use false, true or 'new' learn more https://developer.chrome.com/articles/new-headless/
          devtools: false, // Open devtools by default
          debug: false, // Opens a debug session
          logQR: true, // Logs QR automatically in terminal
          browserWS: '', // If u want to use browserWSEndpoint
          browserArgs: [''], // Original parameters  ---Parameters to be added into the chrome browser instance
          addBrowserArgs: [''], // Add broserArgs without overwriting the project's original
          puppeteerOptions: {}, // Will be passed to puppeteer.launch
          disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
          disableWelcome: true, // Will disable the welcoming message which appears in the beginning
          updatesLog: true, // Logs info updates automatically in terminal
          autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
          createPathFileToken: false, // creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
          addProxy: [''], // Add proxy server exemple : [e1.p.webshare.io:01, e1.p.webshare.io:01]
          userProxy: '', // Proxy login username
          userPass: '' // Proxy password
        },

        // BrowserInstance
        (browser, waPage) => {
          console.log('Browser PID:', browser.process().pid);
          waPage.screenshot({ path: 'screenshot.png' });
        }).then((client) => {
          start(client); loadcron();
          console.log("socket.js -> Session Whatsapp iniciada ")
          sessionIniciada = true; return client
        })
        .catch((erro) => {
          console.log(erro);
        });

/////////////////////
Then this error apear

node_modules/venom-bot/dist/controllers/initializer.js:160
browserInstance(browser, page, client);
                ^

TypeError: browserInstance is not a function
node_modules/venom-bot/dist/controllers/initializer.js:160:17

**Comment by FernandoGambaro** [comment]
Apparently there is some compatibility problem with the use of socket, so when sending a message by socket it generates errors.
In addition to suppressing the socket usage, delete the node_modules folder and the packages-lock.json file and reinstall everything again

I still haven't figured out how to use sockets

**Comment by eladcandroid** [comment]
I'm not using sockets
