### ISSUE TITLE
Only the first message is sent.

### ISSUE THREAD

**Issue by chacalgbi** [orkestral/venom#2295]
Everything starts correctly. Reads the qr-code and everything is ok.
The first message is sent successfully, after that nothing else happens, no message can be sent.

- **Venom version(s): Version: 5.0.1
- **OS: Ubuntu 22.04
- **Node version: 18.16.0

**Comment by vitorssoares7** [comment]
Had the same issue about a month ago using venom with docker, everything worked the it was supposed to be until the first message was send then it would stop responding. What solved the problem for me was uninstalling venom, reinstalling it and also running a docker prune to delete the image i was using in docker.

**Comment by chacalgbi** [comment]
I deleted the folders and installed everything again and it worked. Thanks!
