### ISSUE TITLE
Qrcode nao gera no vps apenas localhost

### ISSUE THREAD

**Issue by Igorhenri0407** [orkestral/venom#2299]
ola pessoal,o qrcode esta gerando na aplicaçao local porem quando subo pro vps nao gera o qrcode fica apenas verificando se esta logado

**Comment by marcelovieirahonorio** [comment]
Olá... eu fiz alguns testes com VPS, para aparecer o QRCode, foi necessário desativar a interface gráfica e ficar monitorando via linha de comando... ao iniciar via linha de comando, apareceu o QRCode em modo **texto** e deu certo. Para você, na janela do modo texto, aparece alguma coisa? Quais as mensagens geradas no log?
