### ISSUE TITLE
window.WAPI.onInterfaceChange not working

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#2304]
## Description

window.WAPI.onInterfaceChange does not provide any status.

## Environment

- **Venom version(s):** 5.0.1
- **Browser:** Microsoft Edge 114.0.1823.43
- **OS:** Windows 11
- **Node version:** Node 20

## Steps to Reproduce

1. Add listener by calling window.WAPI.onInterfaceChange(console.log) in browser console after injected WAPI.js

**Comment by sandro-salles** [comment]
Maybe related to #2308
