### ISSUE TITLE
Store.Chat is no longer available

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#2305]
## Description

Store.Chat no longer available and causes checkNumberStatus and sendMessage function to fail

## Environment

- **Venom version(s):** 5.0.1
- **Browser:** Microsoft Edge 114.0.1823.43
- **OS:** Windows 11
- **Node version:** Node 20

## Steps to Reproduce

1. Inject WAPI.js script through browser console 
2. Call `window.WAPI.checkNumberStatus('<whatsapp-id>')`

**Comment by sandro-salles** [comment]
Probably related to #2308
