### ISSUE TITLE
WAPI Injection throwing an error on recent update. Fix suggestion... 

### ISSUE THREAD

**Issue by sandro-salles** [orkestral/venom#2308]
The code below is raising an error in recent update, preventing the code to inject the parasite and leading all **Store** dependencies to failures.

https://github.com/orkestral/venom/blob/962d539ad2e348a4e56e6be8235fda5b05525ed1/src/lib/wapi/wapi.js#L182

Based on a recent code update in **waconnect-team/wajs**, instead of forcing the setting of chunk key on window object, we should first check if it exists and, if not, set as an empty array, as shown below:

https://github.com/wppconnect-team/wa-js/commit/53396183f624e5afc0388c2d4374d683dcc43fba

So the proposed fix would be to override that line with:

`if (typeof window[injectConfig.webpack] === 'undefined') {
    window[injectConfig.webpack] = [];
  }`

**Already tested locally and it works**.

**Comment by Carloslml** [comment]
I try this change, but no work, what is your version?

**Comment by sandro-salles** [comment]
For me its working on:

-  Venom-Bot: 5.0.1
-  Node: v16.14.0
-  OS: Ubuntu 22.04
-  Browser: Chrome 114.0.5735.106
-  Puppeteer: ^20.7.1
-  Puppeteer Core: ^20.7.1

**Comment by leanmarro** [comment]
> 
headless: true,
puppeteerOptions: {
  ignoreDefaultArgs: ['--disable-extensions']
},
About that... Where did you add this setting?

**Comment by Carloslml** [comment]
> > 
> 
> headless: true, puppeteerOptions: { ignoreDefaultArgs: ['--disable-extensions'] }, Acerca de eso... ¿Dónde agregaste esta configuración?

When create a session:
![image](https://github.com/orkestral/venom/assets/37524166/ed99388c-bfef-4cfd-8ec7-bdae2682a177)

**Comment by leanmarro** [comment]
> > > 
> > 
> > 
> > headless: true, puppeteerOptions: { ignoreDefaultArgs: ['--disable-extensions'] }, Acerca de eso... ¿Dónde agregaste esta configuración?
> 
> When create a session: ![image](https://user-images.githubusercontent.com/37524166/245919621-ed99388c-bfef-4cfd-8ec7-bdae2682a177.png)

Did that work for you?

**Comment by Carloslml** [comment]
> > > > 
> > > 
> > > 
> > > headless: true, puppeteerOptions: { ignoreDefaultArgs: ['--disable-extensions'] }, Acerca de eso... ¿Dónde agregaste esta configuración?
> > 
> > 
> > When create a session: ![image](https://user-images.githubusercontent.com/37524166/245919621-ed99388c-bfef-4cfd-8ec7-bdae2682a177.png)
> 
> Did that work for you?

No, i try with this settings, and show same error
![image](https://github.com/orkestral/venom/assets/37524166/16e43432-bc3a-4ccc-9717-5f972a488a3f)

**Comment by CarlosAurelioMRF** [comment]
> The code below is raising an error in recent update, preventing the code to inject the parasite and leading all **Store** dependencies to failures.
> 
> https://github.com/orkestral/venom/blob/962d539ad2e348a4e56e6be8235fda5b05525ed1/src/lib/wapi/wapi.js#L182
> 
> Based on a recent code update in **waconnect-team/wajs**, instead of forcing the setting of chunk key on window object, we should first check if it exists and, if not, set as an empty array, as shown below:
> 
> [wppconnect-team/wa-js@5339618](https://github.com/wppconnect-team/wa-js/commit/53396183f624e5afc0388c2d4374d683dcc43fba)
> 
> So the proposed fix would be to override that line with:
> 
> `if (typeof window[injectConfig.webpack] === 'undefined') { window[injectConfig.webpack] = []; }`
> 
> **Already tested locally and it works**.

I was getting the error: `Cannot read properties of undefined (reading 'createWid')`

So, I've changed manually on node_modules put the code that you left and it's working!

**Comment by jackson-uti** [comment]
Can I make this change directly in wapi.js.map?

> > The code below is raising an error in recent update, preventing the code to inject the parasite and leading all **Store** dependencies to failures.
> > https://github.com/orkestral/venom/blob/962d539ad2e348a4e56e6be8235fda5b05525ed1/src/lib/wapi/wapi.js#L182
> > 
> > Based on a recent code update in **waconnect-team/wajs**, instead of forcing the setting of chunk key on window object, we should first check if it exists and, if not, set as an empty array, as shown below:
> > [wppconnect-team/wa-js@5339618](https://github.com/wppconnect-team/wa-js/commit/53396183f624e5afc0388c2d4374d683dcc43fba)
> > So the proposed fix would be to override that line with:
> > `if (typeof window[injectConfig.webpack] === 'undefined') { window[injectConfig.webpack] = []; }`
> > **Already tested locally and it works**.
> 
> I was getting the error: `Cannot read properties of undefined (reading 'createWid')`
> 
> So, I've changed manually on node_modules put the code that you left and it's working!

I found the line mentioned in node_modules/venom-bot/dist/lib/wapi.js.map changed it but it didn't work

**Comment by CarlosAurelioMRF** [comment]
change`wapi.js` instead of `wapi.js.map`

**Comment by Divino67** [comment]
É a linha 9313 de wapi.js meu amigo

**Comment by sandro-salles** [comment]
> Can I make this change directly in wapi.js.map?
> 
> > > The code below is raising an error in recent update, preventing the code to inject the parasite and leading all **Store** dependencies to failures.
> > > https://github.com/orkestral/venom/blob/962d539ad2e348a4e56e6be8235fda5b05525ed1/src/lib/wapi/wapi.js#L182
> > > 
> > > Based on a recent code update in **waconnect-team/wajs**, instead of forcing the setting of chunk key on window object, we should first check if it exists and, if not, set as an empty array, as shown below:
> > > [wppconnect-team/wa-js@5339618](https://github.com/wppconnect-team/wa-js/commit/53396183f624e5afc0388c2d4374d683dcc43fba)
> > > So the proposed fix would be to override that line with:
> > > `if (typeof window[injectConfig.webpack] === 'undefined') { window[injectConfig.webpack] = []; }`
> > > **Already tested locally and it works**.
> > 
> > 
> > I was getting the error: `Cannot read properties of undefined (reading 'createWid')`
> > So, I've changed manually on node_modules put the code that you left and it's working!
> 
> I found the line mentioned in node_modules/venom-bot/dist/lib/wapi.js.map changed it but it didn't work

Check this module:
https://github.com/ds300/patch-package

You can patch external/third party modules in your own code with this (i use this when i have no time to submit pull requests or wait for them to be accepted)

**Comment by fernandopraise** [comment]
na linha 9313 tem esses codigo com while... esta correta essa linha para alteração do codigo?


![image](https://github.com/orkestral/venom/assets/56304118/5013b391-6ca0-448d-a679-43f92d89bb32)

**Comment by carlos-aurelio-libertas** [comment]
> na linha 9313 tem esses codigo com while... esta correta essa linha para alteração do codigo?
> 
> no caminho node_modules/venom-bot/dist/lib/wapi.js
> 
> ![image](https://user-images.githubusercontent.com/56304118/245934994-5013b391-6ca0-448d-a679-43f92d89bb32.png)

No seu caso é 9312

**Comment by fernandopraise** [comment]
continua a luta rs... aqui não sai disso...

![image](https://github.com/orkestral/venom/assets/56304118/cfbcaa08-74b0-4246-a487-3a51e49152dd)

**Comment by Carloslml** [comment]
> na linha 9313 tem esses codigo com while... esta correta essa linha para alteração do codigo?
> 
> ![image](https://user-images.githubusercontent.com/56304118/245934994-5013b391-6ca0-448d-a679-43f92d89bb32.png)

Only 9312, replace this line, but this code is generated by "npm install" and it generates the ./dist folder, change the code in src/lib/wapi and then run npm install, then look at this line and you should get the change

**Comment by Carloslml** [comment]
> continua a luta rs... aqui não sai disso...
> 
> ![image](https://user-images.githubusercontent.com/56304118/245936538-cfbcaa08-74b0-4246-a487-3a51e49152dd.png)

What version do you use?, see package.json i use "puppeteer": "^20.7.1",

**Comment by fernandopraise** [comment]
Também estou usando essa versão do puppeteer

**Comment by sandro-salles** [comment]
> continua a luta rs... aqui não sai disso...
> 
> ![image](https://user-images.githubusercontent.com/56304118/245936538-cfbcaa08-74b0-4246-a487-3a51e49152dd.png)

Aparentemente conectou... qual é o erro exatamente @fernandopraise ?

**Comment by fernandopraise** [comment]
fica rodando esse Waiting for introduction e ao tentar enviar mensagem ... da o erro abaixo...

![image](https://github.com/orkestral/venom/assets/56304118/f0322d61-5d74-4d8c-a339-3176e7f9e611)

**Comment by sandro-salles** [comment]
> fica rodando esse Waiting for introduction e ao tentar enviar mensagem ... da o erro abaixo...
> 
> ![image](https://user-images.githubusercontent.com/56304118/245937503-f0322d61-5d74-4d8c-a339-3176e7f9e611.png)

Consegue mandar um print de como ficou a sua alteração no arquivo do wapí, dentro do node_modules?

**Comment by CarlosAurelioMRF** [comment]
> mandar um print

você tem que alterar aquele arquivo e manter o mesmo padrão do arquivo compilado:

`if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }`

**Comment by CarlosAurelioMRF** [comment]
> > na linha 9313 tem esses codigo com while... esta correta essa linha para alteração do codigo?
> > ![image](https://user-images.githubusercontent.com/56304118/245934994-5013b391-6ca0-448d-a679-43f92d89bb32.png)
> 
> Only 9312, replace this line, but this code is generated by "npm install" and it generates the ./dist folder, change the code in src/lib/wapi and then run npm install, then look at this line and you should get the change


você tem que alterar aquele arquivo e manter o mesmo padrão do arquivo compilado:

`if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }`

**Comment by fernandopraise** [comment]
ficou assim. o arquivo wapi.js

![image](https://github.com/orkestral/venom/assets/56304118/9a289bab-ab41-4f60-ac06-41b6d9719ee3)

**Comment by sandro-salles** [comment]
> ficou assim. o arquivo wapi.js
> 
> ![image](https://user-images.githubusercontent.com/56304118/245938520-9a289bab-ab41-4f60-ac06-41b6d9719ee3.png)

Tá certinho então... como vc tá rodando seu projeto?

**Comment by fernandopraise** [comment]
![image](https://github.com/orkestral/venom/assets/56304118/0c168678-00fc-47fe-a96f-a80f9dac10ef)

**Comment by sandro-salles** [comment]
> ![image](https://user-images.githubusercontent.com/56304118/245939318-0c168678-00fc-47fe-a96f-a80f9dac10ef.png)

Tá usando chrome ou chromium?

**Comment by fernandopraise** [comment]
por padrão é o Chromium certo?... não setei o chrome... acredito..

**Comment by CarlosAurelioMRF** [comment]
> ficou assim. o arquivo wapi.js
> 
> ![image](https://user-images.githubusercontent.com/56304118/245938520-9a289bab-ab41-4f60-ac06-41b6d9719ee3.png)

A linha que você adicionou está errada, no arquivo compilado tem que colocar `_helper__WEBPACK_IMPORTED_MODULE_1__` igual fiz no comentário ali de cima.

**Comment by sandro-salles** [comment]
> > ficou assim. o arquivo wapi.js
> > ![image](https://user-images.githubusercontent.com/56304118/245938520-9a289bab-ab41-4f60-ac06-41b6d9719ee3.png)
> 
> A linha que você adicionou está errada, no arquivo compilado tem que colocar `_helper__WEBPACK_IMPORTED_MODULE_1__` igual fiz no comentário ali de cima.

@CarlosAurelioMRF matou a charada. Nem notei que ele não usou a estrutura do compilado.

**Comment by sandro-salles** [comment]
@fernandopraise ali na linha 9312 tem que ser como o @CarlosAurelioMRF passou no comentário dele:

`if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }`

**Comment by fernandopraise** [comment]
aeeeeeeeeeeeeeeeeeeeeeee vcs. são feeeeeeeeeeeeeeerasss... funcionou muitíssimo obrigado... manos

**Comment by FernandoAlmondes** [comment]
Value pessoal, obrigado! Aqui também funcionou certinho com:

if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }

**Comment by Carloslml** [comment]
Thans, with this change, QR code Work, and register functions getHostDevice, onMessages, etc...

**Comment by AndreyKrauthein** [comment]
![image](https://github.com/orkestral/venom/assets/54869693/38cfc2d2-a3ce-4e17-8073-fbbc7e7e5b14)

Está certo pessoal? Depois do código adicionado, o que devo fazer?

**Comment by AndreyKrauthein** [comment]
Resolvi o problema, meu vscode nao estava salvando automaticamente porque precisava do sudo e minha versao estava desatualizada. Valeu pessoal!

**Comment by fernandopraise** [comment]
Olá amigos... 

Isso conteceu com vocês também?.. apos um tempo de atividade ele apresentou esse erro...

![image](https://github.com/orkestral/venom/assets/56304118/3861b317-1ce9-4d1b-924f-fe7c73bb39c5)

**Comment by jackson-uti** [comment]
> Valeu pessoal, obrigado! Aqui também funcionou certinho com:
> 
> `if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }`

Aqui funcionou também, muito obrigado.

**Comment by w7br** [comment]
Olá prezados, alguém poderia por favor compartilhar com nós que ainda não obtivemos êxito onde fica o arquivo a ser alterado?

Este arquivo está dentro de qual lib?? venom-bot?

Ficarei muito muito grato por qualquer informação que me ajude a trazer o bot de volta

**Comment by jackson-uti** [comment]
> Olá prezados, alguém poderia por favor compartilhar com nós que ainda não obtivemos êxito onde fica o arquivo a ser alterado?
> 
> Este arquivo está dentro de qual lib?? venom-bot?
> 
> Ficarei muito muito grato por qualquer informação que me ajude a trazer o bot de volta

Então, o que resolveu para mim foi fazer um clone do git atual numa pasta a parte do meu projeto:

git clone https://github.com/orkestral/venom.git

entrar na pasta venom que foi criada e compilar:

npm install --save

depois de terminado o processo eu copiei os arquivos venom/dist//lib/wapi/* para o meu projeto em:
node_modules/venom-bot/dist/lib/wapi/ 

Rodei e funcionou.  Espero que ajude!

**Comment by w7br** [comment]
Muitíssimo obrigado à todos que fizeram parte desta solução. já estava ficando deprimido sem o bot funcionar hahaha

OBRIGADO, de coração I LOVE YOU!!! hahaha

**Comment by benoli** [comment]
Thanks a lot mates! It works like a charm

**Comment by TeuryBazzo** [comment]
Alguem tem uma correção dessa pra docker ?eu fiz o q falaram e funcionou, mas não queria alterar a node_modules

**Comment by fellipgomes** [comment]
Obrigado @CarlosAurelioMRF !!! Fiz o replace da linha com o código que você disponibilizou e funcionou !!!

**Comment by EdesNogueira** [comment]
galera, fiz o replace como todos fizeram, funcionou, mas depois de uns minutos tenho o erro: 


![erro](https://github.com/orkestral/venom/assets/132686747/a111ddd6-7659-4644-bbf6-1d5f0a7d1c66)

ele é aleatório, as vezes vem logo em segundos, as vezes demora minutos...Ajudem um iniciante desesperado :/

**Comment by GanaxXD** [comment]
https://github.com/orkestral/venom/issues/2308#issuecomment-1592025741
Caramba, funcionou real. Muito obrigado, pessoal.

**Comment by l3and49** [comment]
Boa tarde, infelizmente meu bot estava funcionando a um tempo atrás e agora não está mais, e está dando a mensagem de Timeout, porém não consigo ajeitar com as soluções dadas aqui pois não tenho o arquivo [/src/lib/wapi/wapi.js], apenas a [\src], alguém me ajuda por favor?

**Comment by leanmarro** [comment]
> Boa tarde, infelizmente meu bot estava funcionando a um tempo atrás e agora não está mais, e está dando a seguinte mensagem: TimeoutError: waiting for function failed: timeout 30000ms exceeded at new WaitTask (/home/bot/SorriBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680:34) at DOMWorld.waitForFunction (/home/bot/SorriBot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:611:26) at Frame.waitForFunction (/home/bot/SorriBot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1089:32) at Page.waitForFunction (/home/bot/SorriBot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2385:33) at injectApi (/home/bot/SorriBot/node_modules/venom-bot/dist/controllers/browser.js:139:16) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Object.create (/home/bot/SorriBot/node_modules/venom-bot/dist/controllers/initializer.js:297:9) Porém não consigo ajeitar com as soluções dadas aqui pois não tenho o arquivo [/src/lib/wapi/wapi.js], apenas a [\src], alguém me ajuda por favor?

como assim man? na biblioteca do venom não tem o wapi? já tentou baixar de novo usando  npm? qual a versão do teu venom?

**Comment by l3and49** [comment]
> 

Então, não consegui achar nenhum wapi, pra baixar de novo é npm install? Estou usando a versão 5.0.1

**Comment by leanmarro** [comment]
> > 
> 
> Então, não consegui achar nenhum wapi, pra baixar de novo é npm install? Estou usando a versão 5.0.1

isso, além disso... tenta a versão mais recente. Aplica as modificações sugeridas pelo pessoal no Wapi.js e no Browser.js e tenta novamente.

**Comment by l3and49** [comment]
> > > 
> > 
> > 
> > Então, não consegui achar nenhum wapi, pra baixar de novo é npm install? Estou usando a versão 5.0.1
> 
> isso, além disso... tenta a versão mais recente. Aplica as modificações sugeridas pelo pessoal no Wapi.js e no Browser.js e tenta novamente.

É que assim man, dando um contexto, é o bot do lugar onde trabalho e estava funcionando recentemente, até que parou e não estamos conseguindo arrumar por nada, e na pasta "src" não tem nada de lib ou wapi, saca?

**Comment by leanmarro** [comment]
> > > > 
> > > 
> > > 
> > > Então, não consegui achar nenhum wapi, pra baixar de novo é npm install? Estou usando a versão 5.0.1
> > 
> > 
> > isso, além disso... tenta a versão mais recente. Aplica as modificações sugeridas pelo pessoal no Wapi.js e no Browser.js e tenta novamente.
> 
> É que assim man, dando um contexto, é o bot do lugar onde trabalho e estava funcionando recentemente, até que parou e não estamos conseguindo arrumar por nada, eu achei o wapi.js pelo caminho node_modules/venom-bot/dist/lib/wapi/wapi.js porém tinha apenas uma linha de código enorme... copiei e colei o código que foi disponibilizado aqui com as mudanças necessárias, porém continua dando o mesmo erro

essa linha enorme tu pega e joga em um identador de código que vem "bonitinho"... em relação as modificações, essa de time out
vai no browser.js que fica no node_modules/venom-bot/dist/controllers/ e aplica essa alteração que um mano passou por ai
    const sessionName = options.session || '';
    const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
    // const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
lembra de atualizar para a última versão

**Comment by l3and49** [comment]
Vou tentar aqui, valeu mano

**Comment by l3and49** [comment]
Fui atualizar o venom-bot e deu erro de browser agora, não consegui achar onde deve ser colocada essa alteração, mas obrigado.

**Comment by leanmarro** [comment]
> node_modules/venom-bot/dist/controllers/

node_modules/venom-bot/dist/controllers/browser.js
seguiu esse caminho aqui?
da um ctrl+f (pesquisa) e cola essa parte 'const folderSession = path.join' para achar a const e substitui por essa:

const sessionName = options.session || '';
const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
// const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
faz isso ai, se não der certo, te mando o arquivo...

**Comment by otaviojulioneto** [comment]
> 

@leanmarro 
Fiz essas alterações que orientou, chegou a pedir para eu fazer a leitura do QR Code novamente, porém continuo com o mesmo erro de timeout.
![image](https://github.com/orkestral/venom/assets/37215011/2ae583a7-51eb-4a3f-98cd-36bfff6fe5c1)

Segue o print com as modificações, talvez senha substituído algo errado.
![image](https://github.com/orkestral/venom/assets/37215011/a0c138c1-f340-4165-9f3b-604226c8c783)

**Comment by leanmarro** [comment]
> > 
> 
> @leanmarro Fiz essas alterações que orientou, chegou a pedir para eu fazer a leitura do QR Code novamente, porém continuo com o mesmo erro de timeout. ![image](https://user-images.githubusercontent.com/37215011/249779636-2ae583a7-51eb-4a3f-98cd-36bfff6fe5c1.png)
> 
> Segue o print com as modificações, talvez senha substituído algo errado. ![image](https://user-images.githubusercontent.com/37215011/249779798-a0c138c1-f340-4165-9f3b-604226c8c783.png)

substituiu errado aparentemente...
olha onde eu fiz a substituição:
![image](https://github.com/orkestral/venom/assets/92586129/7c4872c6-36f8-4207-bca3-ecc954990fe1)

**Comment by l3and49** [comment]
> > node_modules/venom-bot/dist/controllers/
> 
> node_modules/venom-bot/dist/controllers/browser.js seguiu esse caminho aqui? da um ctrl+f (pesquisa) e cola essa parte 'const folderSession = path.join' para achar a const e substituir por essa:
> 
> const nomedasessão = opções.sessão || ''; const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName)); // const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session)); faz isso ai, se não der certo, te mando o arquivo...

Agora está dando o seguinte erro e mesmo depois de colocar o wapi.js no identor de código ainda não acho a linha que deve ser modificada...
![print](https://github.com/orkestral/venom/assets/126525698/d84110d5-fd53-485e-bb07-cc11ce279ba4)

**Comment by l3and49** [comment]
Estava usando a 5.0.6, atualizei para a 5.0.7 porém continua com o mesmo erro, e estou criando da seguinte forma:
![Print2](https://github.com/orkestral/venom/assets/126525698/3d4f43dc-3515-4ae0-a1d4-48d76e00e6f8)

**Comment by karein** [comment]
Bem estranho,
eu criei um index.js, versão ^5.0.7 com o seu código e funcionou

![Captura de tela 2023-06-29 152313](https://github.com/orkestral/venom/assets/32269228/f48813a5-96c9-43cd-9bfc-7ff195bbf3c4)

Seu browser está atualizado?
Ou tentou fechar e abrir sua IDE (isso é meio besta mas, as vezes acontece ¯\\(o_o)/¯ )

**Comment by l3and49** [comment]
> const sessionName = options.session || '';

Como faço para atualizar o browser? Não estou acostumado a programar assim

**Comment by l3and49** [comment]
> Bem estranho, eu criei um index.js, versão ^5.0.7 com o seu código e funcionou
> 
> ![Captura de tela 2023-06-29 152313](https://user-images.githubusercontent.com/32269228/249862906-f48813a5-96c9-43cd-9bfc-7ff195bbf3c4.png)
> 
> Seu browser está atualizado? Ou tentou fechar e abrir sua IDE (isso é meio besta mas, as vezes acontece ¯\(o_o)/¯ )

Como faço para atualizar o browser? Não estou acostumado a programar assim

**Comment by karein** [comment]
Pelo Chrome mesmo [chrome://settings/help](url)
se estiver desatualizado vai aparecer a opção de atualizar 

![Captura de tela 2023-06-29 154357](https://github.com/orkestral/venom/assets/32269228/fce7be21-9813-4e4a-85e2-8b7aee0b273c)

**Comment by l3and49** [comment]
Ah ta, sendo assim eles está sim. Já não sei mais o que tentar, mas muito obrigado pela ajuda.

**Comment by l3and49** [comment]
> > Bem estranho, eu criei um index.js, versão ^5.0.7 com o seu código e funcionou
> > ![Captura de tela 2023-06-29 152313](https://user-images.githubusercontent.com/32269228/249862906-f48813a5-96c9-43cd-9bfc-7ff195bbf3c4.png)
> > Seu browser está atualizado? Ou tentou fechar e abrir sua IDE (isso é meio besta mas, as vezes acontece ¯(o_o)/¯ )
> 
> Como faço para atualizar o browser? Não estou acostumado a programar assim

Teria só como me mandar o arquivo browser.js desse por favor?

**Comment by l3and49** [comment]
Fui atualizar o venom bot de novo e acabou dando um erro a mais, I will 
![print pn](https://github.com/orkestral/venom/assets/126525698/d68d270b-a159-4848-a055-e9e77aa3ce53)
cry

**Comment by karein** [comment]
> > > Bem estranho, eu criei um index.js, versão ^5.0.7 com o seu código e funcionou
> > > ![Captura de tela 2023-06-29 152313](https://user-images.githubusercontent.com/32269228/249862906-f48813a5-96c9-43cd-9bfc-7ff195bbf3c4.png)
> > > Seu browser está atualizado? Ou tentou fechar e abrir sua IDE (isso é meio besta mas, as vezes acontece ¯(o_o)/¯ )
> > 
> > 
> > Como faço para atualizar o browser? Não estou acostumado a programar assim
> 
> Teria só como me mandar o arquivo browser.js e o initializer.js desse por favor? Acredito que esses que estão dando o problema.

https://github.com/karein/teste-venom.git

**Comment by otaviojulioneto** [comment]
> > > 
> > 
> > 
> > @leanmarro Fiz essas alterações que orientou, chegou a pedir para eu fazer a leitura do QR Code novamente, porém continuo com o mesmo erro de timeout. ![image](https://user-images.githubusercontent.com/37215011/249779636-2ae583a7-51eb-4a3f-98cd-36bfff6fe5c1.png)
> > Segue o print com as modificações, talvez senha substituído algo errado. ![image](https://user-images.githubusercontent.com/37215011/249779798-a0c138c1-f340-4165-9f3b-604226c8c783.png)
> 
> substituiu errado aparentemente... olha onde eu fiz a substituição: ![image](https://user-images.githubusercontent.com/92586129/249831441-7c4872c6-36f8-4207-bca3-ecc954990fe1.png)
> 
> se bem que não sei se foi o lugar errado no teu caso, tem que olhar a versão também do venom...

Consegui resolver o problema com um zip enviado no grupo do Telegram no qual reenviaram todos os arquivos com as correções feitas.
Agora o server está rodando normalmente na porta 4000, porém ele nao está enviando a mensagem no WhatsApp (Grupos do Telegram funcionam normalmente).
Uma OBS. essa configuração no server do zabbix do beezap não foi feita por mim, foi feita por um outro colaborador que está de férias.
Conferi as configurações nas Trigger actions, Media types e Media do usuário (contatos)  do Zabbix e estão todos OK e criados.
Dentro dos arquivos default, tem algo que eu deva editar para conseguir ajustar isso? Talvez em algum ponto onde estou referenciando essas Triggers.
![image](https://github.com/orkestral/venom/assets/37215011/d2b65409-a81f-4479-80c9-bc132b2101d1)
![image](https://github.com/orkestral/venom/assets/37215011/b759e64c-855d-4f72-a56b-e17ca47b2a2d)
![image](https://github.com/orkestral/venom/assets/37215011/3a1bd95e-b4d9-4ac3-870e-37ab4dec4bfb)

**Comment by otaviojulioneto** [comment]
Continuando a análise acima, tentei realizar um envio de test por dentro do zabbix no Media types e identifiquei este erro agoran os logs do pm2.
![image](https://github.com/orkestral/venom/assets/37215011/9ec24258-fa43-484a-817f-932b246bf670)

![image](https://github.com/orkestral/venom/assets/37215011/58b65ff8-5b62-4c3f-aedf-aae2a5ddcf37)

**Comment by otaviojulioneto** [comment]
Consegui resolver meu problema.

Executei os passos abaixo e também desabilitei algumas regras no iptables.

Obrigado a todos!

pm2 stop 0

rm -rf tokens

npm install venom-bot@5.0.6

nano beezap.js
# Comentar isso
//venom.create().then((client) => start(client)).catch((error) => {
//  console.error('Erro ao iniciar o cliente Venom:', error);
//});

# E adicionar isso.
venom
  .create({
    session: 'API-ZAP-BEE' //name of session
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

# Leia o Qrcode novamente.
node beezap.js

ctrl + c

pm2 start 0 --name api-beezap
pm2 save
