### ISSUE TITLE
How to integrate with Electron?

### ISSUE THREAD

**Issue by GuilhermeCunha** [orkestral/venom#231]
I'm trying to use venom-bot inside a [nextron ](https://github.com/saltyshiomix/nextron)project, but I'm having an error when trying to run venom-bot project inside the rendered part of the project.

Would anyone know how to help me accomplish this integration or have a similar problem to share?

![image](https://user-images.githubusercontent.com/19752833/96255572-86b8de80-0f8d-11eb-8770-68cde6b5f2ad.png)

**Comment by joaosouz4** [comment]
the error is saying that the module sharp.node was not found. did you install lib before compiling?
can you share this project?

**Comment by GuilhermeCunha** [comment]
> the error is saying that the module sharp.node was not found. did you install lib before compiling?
> can you share this project?

I installed it separately, but it always gives error in a different dependency.

Unfortunately I cannot share the project.

But I would like to know, can I call this script inside Frontend (React)? Or only on NodeJs?

**Comment by joaosouz4** [comment]
I believe that only knotted.
for not being able to share I will not be able to help you more than that.
