### ISSUE TITLE
client.checkNumberStatus throws an error, but empty

### ISSUE THREAD

**Issue by swsolutions2022** [orkestral/venom#2311]
The method worked perfectly for weeks but today when I restarted the service it started throwing an error and I can't see what it is. 

 const output = await client.checkNumberStatus(`${phone}@c.us`);
in the catch I only get {}

- **Venom version(s): 5.0.1
- **Browser: 114.0.5735.134
- **OS: Windows 10
- **Node version: 16.15.0

My client obj:
Whatsapp {
  browser: CDPBrowser {
    eventsMap: Map(3) {
      'targetcreated' => [Array],
      'targetchanged' => [],
      'disconnected' => [Array]
    },
    emitter: {
      all: [Map],
      on: [Function: on],
      off: [Function: off],
      emit: [Function: emit]
    },
    _createPageInContext: [AsyncFunction (anonymous)]
  },
  page: CDPPage {
    eventsMap: Map(4) {
      'pageerror' => [Array],
      'close' => [Array],
      'load' => [Array],
      'dialog' => [Array]
    },
    emitter: {
      all: [Map],
      on: [Function: on],
      off: [Function: off],
      emit: [Function: emit]
    }
  },
  spinnies: Spinnies {
    options: {
      spinnerColor: 'greenBright',
      succeedColor: 'green',
      failColor: 'red',
      spinner: [Object],
      disableSpins: true,
      succeedPrefix: '✓',
      failPrefix: '✖'
    },
    spinners: {
      'browser-bot': [Object],
      'whatzapp-bot': [Object],
      'whatzapp-intro-bot': [Object],
      'session-bot': [Object]
    },
    isCursorHidden: false,
    currentInterval: null,
    stream: WriteStream {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      columns: 204,
      rows: 18,
      _type: 'tty',
      fd: 2,
      _isStdio: true,
      destroySoon: [Function: destroy],
      _destroy: [Function: dummyDestroy],
      [Symbol(async_id_symbol)]: 4,
      [Symbol(kHandle)]: [TTY],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    lineCount: 0,
    currentFrameIndex: 0,
    spin: false
  },
  spinStatus: {
    apiInject: '',
    autoCloseRemain: 0,
    previousText: 'Connected',
    previousStatus: 'succeed',
    state: ''
  },
  autoCloseInterval: null,
  statusFind: null,
  session: 'bot',
  options: {
    folderNameToken: 'tokens',
    mkdirFolderToken: '',
    headless: false,
    devtools: false,
    debug: true,
    logQR: true,
    browserWS: '',
    browserArgs: [ '' ],
    addBrowserArgs: [],
    puppeteerOptions: { userDataDir: 'C:\\wv\\tokens\\bot', ignoreHTTPSErrors: true },
    disableSpins: true,
    disableWelcome: false,
    updatesLog: true,
    autoClose: 60000000,
    createPathFileToken: true,
    waitForLogin: true,
    BrowserFetcher: true,
    forceConnect: false,
    attemptsForceConnectLoad: 5,
    forceConnectTime: 5000,
    addProxy: [],
    useChrome: false,
    refreshQR: 15000
  },
  listenerEmitter: EventEmitter {
    _events: [Object: null prototype] {
      onInterfaceChange: [AsyncFunction (anonymous)],
      onStreamChange: [Function (anonymous)],
      onStateChange: [Array],
      onMessage: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false
  }
}

**Comment by hiagodotme** [comment]
@swsolutions2022 Friend, do the following. Open the node_modules\venom-bot\dist\lib\wapi\wapi.js file at line 9312.

Remove the content from the line and place the content below

```javascript
  if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') {
    window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];
  }
```

Something similar to what you reported happened to me, when applying this change everything normalized. It is already in the master repository but there is still no NPM version for the fix.
