### ISSUE TITLE
Error [TypeError]: Cannot read properties of undefined (reading 'createWid')

### ISSUE THREAD

**Issue by abhilash-screl** [orkestral/venom#2314]
## Description
Unable to send an image file along with caption (That's my only requirement using the Bot)
when i sent the image with a caption

 Error [TypeError]: Cannot read properties of undefined (reading 'createWid')

is what i get

thanks in advance.

## Environment

- **Venom version(s):* v5.0.1*
- **Browser:*chromium*
- **OS: *Ubuntu server 22.04.2*
- **Node version: *v18.15.0*

## Steps to Reproduce

1. successfully login
2. send an image along with a caption
3. get the error message

## Log Output

Error[TypeError]: Cannot read properties of undefined(reading 'createWid')
Object.sendExist(<anonymous>:515:40)
    at ExecutionContext._ExecutionContext_evaluate (/home/location/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:262:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/location/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:145:16)
    at async /home/location/node_modules/venom-bot/dist/api/layers/sender.layer.js:423:28
    at sendExist (:514:39)
    ServiceUnavailableError: Response timeout
    at IncomingMessage.<anonymous> (/home/location/node_modules/connect-timeout/index.js:84:8)
        at IncomingMessage.emit (node:events:513:28)
        at IncomingMessage.emit (node:domain:489:12)
        at Timeout._onTimeout (/home/location/node_modules/connect-timeout/index.js:49:11)
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7)

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by abhilash-screl** [comment]
Anybody??

**Comment by Z3roS4n** [comment]
same error, but with sendText

**Comment by klebinhopk** [comment]
#https://github.com/orkestral/venom/commit/a65de595655b549efc4b142407ea793c593dd296
Apparently there was an update, consider updating your package and try running it again.

**Comment by weershft** [comment]
conseguiu arrumar este erro ?

**Comment by weershft** [comment]
para mim ainda esta ocorrendo, tentei autalizar a versão do venom-bot, porem ainda se encontra na mesma versão: "venom-bot": "^5.0.1"

**Comment by abhilash-screl** [comment]
> para mim ainda esta ocorrendo, tentei autalizar a versão do venom-bot, porem ainda se encontra na mesma versão: "venom-bot": "^5.0.1"

same here.

**Comment by abhilash-screl** [comment]
> conseguiu arrumar este erro ?

unfortunately, no.
could not find any fix.

**Comment by abhilash-screl** [comment]
> como vamos fazer para pegar esta alteração ? será que vão liberar uma nova versão ?

no idea
meanwhile i found another package/repo called wppconnect which is a clone of this repo
its almost the same
no codes need to be changed except front-end since keywords used for indicating statuses are different
eg:- 'inChat' instead of 'successChat' but it works
im looking for a way to incorporate this new package into my codes

or you may check this
https://github.com/orkestral/venom/issues/2308
i found this on venom-bot telegram group
i could not make it work following this link's discussion
but you may

**Comment by weershft** [comment]
Deu certo!

Basicamente, você terá que ir ate o caminho:
  node_modules/venom-bot/dist/lib/wapi/wapi.js

e fazer uma alteração antes da função "while() {}" com o seguinte codigo:
if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') {
    window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []
  }
e acredito que ira funcionar.

veja se voce consegue, qualquer coisa me relate por aqui

**Comment by fellipgomes** [comment]
Estou com o mesmo problema para enviar mensagens ou qualquer outra coisa. 
@weershft  mano, não encontrei esse while na linha 9312

**Comment by karein** [comment]
> Deu certo!
> 
> @abhilash-screl Basicamente, você terá que ir ate o caminho: node_modules/venom-bot/dist/lib/wapi/wapi.js
> 
> e fazer uma alteração antes da função "while() {}" na linha 9312, com o seguinte codigo: if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [] } e acredito que ira funcionar.
> 
> veja se voce consegue, qualquer coisa me relate por aqui


Estava com o mesmo problema, mas voltou a funcionar fazendo essa alteração, espero que o erro seja corrigido logo..
resaltando que a linha antes do `while()`:
```javascript
   window[[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
```
é substituida pelo `if` (foi como funcionou pra mim), 
continuava dando erro com essa linha de código, então comentei ela..
espero que ajude :)
