### ISSUE TITLE
Bug: connection problems from puppeteer

### ISSUE THREAD

**Issue by guilherme179** [orkestral/venom#2315]
## Description

every time I try to start my code, after it reads the qrcode it takes a while and then it gives this error with puppeteer. I can't instantiate my function and consequently my bot doesn't work, it reads the qrcode it says the instance was started, but the bot is not working.

## Environment

- **Venom version(s):** [4.3.7]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [Windows 10, Windows 11]
- **Node version:** [v16.17.1]

## Your Code

// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
import { create } from 'venom-bot';

create({
    session: 'session-name' //name of session
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  console.log(client);
  client.onMessage((message) => {
    console.log(client);
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

## Additional context / Screenshot

![image](https://github.com/orkestral/venom/assets/83122773/0dcca976-2d5e-41db-aa87-96e87fb896ab)

**Comment by klebinhopk** [comment]
I was having the same problem. See the possibility of updating to the latest version that might solve the problem.

**Comment by guilherme179** [comment]
ok, thank you so much
