### ISSUE TITLE
Doesnt work anything!

### ISSUE THREAD

**Issue by hasanablak** [orkestral/venom#2316]
I open terminal and write those code;

$ mkdir wp-bot
$ cd wp-bot
$ npm i --save venom-bot
$ touch index.jsx
$ nano index.js

I paste this code from documentation;

```
// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');
venom
  .create({
    session: 'session-name' //name of session
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```

Command + X, Yes (for save) and 
$ node index.js

You're up to date 🎉🎉🎉

VENOM-BOT

⠋ Waiting... checking the browser...
  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

✓ Browser successfully opened
✓ headless option is active, browser hidden
✓ Page successfully accessed
[QR CODE SHOWING]

(i read qr code from my whatsapp)

⠏ waiting for introduction
✓ [instance: session-name]: Connected

(I send an message from other whatsapp to my whatsapp)
(Doesnt still work, doesnt happent anything )

Node.js version: v18.15.0
Npm version: 9.5.0
OS: MacOs

**Comment by weershft** [comment]
O meu também esta desta forma, porem o erro supostamente esta acontecendo por causa deste "⠏ aguardando introdução", e a 10 horas atras, uma pessoa chamada refael nicolas adicionou a seguinte att na master do venom-bot> "fix: aguardando introdução.
