### ISSUE TITLE
venom-bot not starting

### ISSUE THREAD

**Issue by subburaja** [orkestral/venom#2319]
## Description
venom-bot not starting
Error: Cannot find module '......../node_modules/venom-bot/index.js'. Please verify that the package.json has a valid "main" entry

If I edit package.json of venom-bot "main" into "/dist/index.js", this issue goes away, but ends up with following error

```
You're up to date 🎉🎉🎉
- Waiting... checking the browser...
- Error no open browser....
```

## Environment

- **Venom version(s): 5.0.3** [e.g. 2.0.27, 2.2.1]
- **Browser:** chrome 114.0.5735.106  [e.g. Chrome 87, Chromium 85]
- **OS:** mac OS ventura 13.4 (22F66) [e.g. OSX 10.13.4, Windows 10]
- **Node version:** v18.16.0 [e.g. Node 8, Node 14]

## Steps to Reproduce

1. npm init and install a fresh venom-bot on mac PC
2. paste basic venom.create codes from npm at index.js file & start it by "node index"

## Log Output

node:internal/modules/cjs/loader:444
      throw err;
      ^

Error: Cannot find module '......../node_modules/venom-bot/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:436:19)
    at Module._findPath (node:internal/modules/cjs/loader:678:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/subburaja/Documents/dev/my-whats-api/index.js:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  path: '....../node_modules/venom-bot/package.json',
  requestPath: 'venom-bot'
}

Node.js v18.16.0

**Comment by alexandrejr-rajtecnologia** [comment]
Tive o mesmo problema, conseguir resolver voltando a verão do Puppeteer
estou usando esta antiga e esta ok!

npm i puppeteer@19.11.1

**Comment by DenisAlvesDias** [comment]
Tenho o mesmo problema. A atualização está quebrando a pasta parece. Eu tenho um backup aqui na versão 5.0.1 funcionando. Quando atualizo para a 5.0.3 ele da erro. Ae se eu volto pra 5.0.1 continua o erro. Tenho q restaurar o backup para voltar a funcionar. Espero que arrumem o problema. Ontem abri um topico relatando o bug e o mesmo foi fechado sem resposta poucos minutos depois de abrir.

**Comment by Divino67** [comment]
Mesmo problema aqui

**Comment by PedroPaduelo** [comment]
aqui tambem

**Comment by TeuryBazzo** [comment]
mesmo aqui

**Comment by alexandrejr-rajtecnologia** [comment]
Estou na Versão 5.0.1 com o puppeteer@19.11.1!

Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js

comentar esta linha 9312
//window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
 
colocar este bloco no lugar
  if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){
  window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}

E esta funcionando de boa!

**Comment by onitorrinco** [comment]
mesmo problema.

**Comment by PedroPaduelo** [comment]
Memso com essa alteração estou com erro

**Comment by karein** [comment]
Mesmo problema

dentro da pasta do venom quando mudo no `package.json`

```json
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
```
por
```json
    "main": "index.js",
    "types": "index.d.ts",
```
como estava na versão 5.0.1, ele roda, mas não consegue abrir o browser, retornando o erro 'noOpenBrowser'

**Comment by onitorrinco** [comment]
Versão 5.0.4 tbem não funciona....

**Comment by DenisAlvesDias** [comment]
Sim. Na atualização de versão para 5.0.4 continuo a mesma coisa.

**Comment by GustavoTG75** [comment]
> Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> 
> Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> 
> comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> 
> colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> 
> E esta funcionando de boa!

O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas.  Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.

O erro é este:
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid')
    at Object.sendExist (<anonymous>:515:40)
    at async Object.sendMessage (<anonymous>:4686:7)
    at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12)
    at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22

Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?

**Comment by alexandrejr-rajtecnologia** [comment]
> > Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> > Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> > comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> > colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> > E esta funcionando de boa!
> 
> O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas. Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.
> 
> O erro é este: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid') at Object.sendExist (:515:40) at async Object.sendMessage (:4686:7) at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12) at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22
> 
> Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?





Tenta atualizar o npm i puppeteer-core!

**Comment by sandro-salles** [comment]
> > Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> > Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> > comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> > colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> > E esta funcionando de boa!
> 
> O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas. Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.
> 
> O erro é este: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid') at Object.sendExist (:515:40) at async Object.sendMessage (:4686:7) at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12) at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22
> 
> Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?

Tenta atualização pra versão **5.0.4**, e atualizar o puppeteer pra:

Puppeteer: ^20.7.1
Puppeteer Core: ^20.7.1

Além disso, se ainda estiver problemas, sugiro vc limpar os tokens gerados anteriormente (caso haja algum) ... no meu caso, em algumas das conexões eu tive que fazer isso pra ele pedir o qr code normalmente e continuar daí.

**Comment by rennan0** [comment]
> 



> > Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> > Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> > comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> > colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> > E esta funcionando de boa!
> 
> O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas. Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.
> 
> O erro é este: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid') at Object.sendExist (:515:40) at async Object.sendMessage (:4686:7) at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12) at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22
> 
> Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?

Na linha 9313, troquei por esse if e deu certo:
`if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }`
Ele é um pouco diferente do que vc usou mas funcionou para mim. Eu segui os passos desse outro post #2308

**Comment by Carloslml** [comment]
With the version 5.0.4 work?

**Comment by blunkrs** [comment]
Na linha 9313, troquei por esse if e deu certo: `if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined') { window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = []; }` Ele é um pouco diferente do que vc usou mas funcionou para mim. Eu segui os passos desse outro post #2308



Perfeito.... funcionando novamente 5.0.1

**Comment by karein** [comment]
@leanmarro não sei se é o seu caso, mas as vezes ao atualizar o arquivo ele identa tudo quando salva.
O meu por exemplo, depois de salvar, o código saiu da linha 9312 pra 9613

**Comment by leanmarro** [comment]
> @leanmarro não sei se é o seu caso, mas as vezes ao atualizar o arquivo ele identa tudo quando salva. O meu por exemplo, depois de salvar, o código saiu da linha 9312 pra 9613

questão é que está vindo com apenas 3200 linhas, não chega se quer à linha 9000

**Comment by karein** [comment]
> > @leanmarro não sei se é o seu caso, mas as vezes ao atualizar o arquivo ele identa tudo quando salva. O meu por exemplo, depois de salvar, o código saiu da linha 9312 pra 9613
> 
> questão é que está vindo com apenas 3200 linhas, não chega se quer à linha 9000... não sei o motivo, fora que só vem o wapi na pasta, acho que são dois arquivos que tinham que vir, certo? Veio apenas um e ainda veio errado

ah, entendi..
sim, era pra ter dois arquivos wapi na pasta wapi, que são o wapi.js e o wapi.js.map 
a versão nova `.v5.0.5` veio só um pra mim e foi minificado mas na versão `5.0.1` veio os dois

Você já tentou apagar o node_modules e instalar de novo com essa versão `5.0.1`?
ou rodar `npm uninstall venom-bot` e `npm i  venom-bot@5.0.1`?

**Comment by leanmarro** [comment]
> > > @leanmarro não sei se é o seu caso, mas as vezes ao atualizar o arquivo ele identa tudo quando salva. O meu por exemplo, depois de salvar, o código saiu da linha 9312 pra 9613
> > 
> > 
> > questão é que está vindo com apenas 3200 linhas, não chega se quer à linha 9000... não sei o motivo, fora que só vem o wapi na pasta, acho que são dois arquivos que tinham que vir, certo? Veio apenas um e ainda veio errado
> 
> ah, entendi.. sim, era pra ter dois arquivos wapi na pasta wapi, que são o wapi.js e o wapi.js.map a versão nova `.v5.0.5` veio só um pra mim e foi minificado mas na versão `5.0.1` veio os dois
> 
> Você já tentou apagar o node_modules e instalar de novo com essa versão `5.0.1`? ou rodar `npm uninstall venom-bot` e `npm i venom-bot@5.0.1`?

eu apaguei e baixei novamente o projeto, mas deu na mesma, porém havia feito usando o yarn, consegui com o npm aqui, vlw. Agora vou testar o código.

**Comment by jonalan7** [comment]
Download the latest version!

`npm i venom-bot@5.0.6`

**Comment by jonalan7** [comment]
bro this is browser problem! O Puppeteer had an update in this latest version! You will have to update your browser!

**Comment by karein** [comment]
Mesmo erro `Error no open browser`

Acho que talvez possa ser um erro ao receber a sessão..

no arquivo `node_modules\venom-bot\dist\controllers\browser.js`, quando adiciono:

```javascript
  const sessionName = options.session || '';
  const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
 //const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
```

na função `folderSession`, o browser carrega..
a session estava vindo undefined e tudo depois do path.resolve não carregava

**Comment by onitorrinco** [comment]
> Mesmo erro `Error no open browser`
> 
> Acho que talvez possa ser um erro ao receber a sessão..
> 
> no arquivo `node_modules\venom-bot\dist\controllers\browser.js`, quando adiciono:
> 
> ```js
>   const sessionName = options.session || '';
>   const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
>  //const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
> ```
> 
> na função `folderSession`, o browser carrega e consegui ler o QR code e enviar uma mensagem simples... a session estava vindo undefined e tudo depois do path.resolve não carregava

Essa solução funciona

**Comment by warleypo** [comment]
> mesmo erro`Error no open browser`
> 
> Acho que talvez possa haver um erro ao receber uma sessão.
> 
> no arquivo `node_modules\venom-bot\dist\controllers\browser.js`, quando adicionar:
> 
> ```js
>   const sessionName = options.session || '';
>   const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
>  //const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
> ```
> 
> na função `folderSession`, o navegador carrega e consegui ler o QR code e enviar uma mensagem simples... a sessão estava vindo indefinida e tudo depois do path.resolve não carregava



> mesmo erro`Error no open browser`
> 
> Acho que talvez possa haver um erro ao receber uma sessão.
> 
> no arquivo `node_modules\venom-bot\dist\controllers\browser.js`, quando adicionar:
> 
> ```js
>   const sessionName = options.session || '';
>   const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, sessionName));
>  //const folderSession = path.join(path.resolve(process.cwd(), options.mkdirFolderToken, options.folderNameToken, options.session));
> ```
> 
> na função `folderSession`, o navegador carrega e consegui ler o QR code e enviar uma mensagem simples... a sessão estava vindo indefinida e tudo depois do path.resolve não carregava

Essa solução não funciona para multi sessões, porque ele não carrega a sessão, apenas vai para a default.

**Comment by karein** [comment]
Entendo, não utilizo Multiple Sessions ainda..

Acho que a versão ainda não foi atualizada, mas foram adicionados alguns commits de ajuste da nova versão que talvez resolvam o problema e podem ser instalados por comando como cita esse comentário: https://github.com/orkestral/venom/issues/2343#issuecomment-1601727830

Eu instalei e funcionou com uma sessão sem ter que fazer o ajuste `options.session || '';` dentro dos módulos.
espero que ajude

**Comment by GustavoTG75** [comment]
> > > Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> > > Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> > > comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> > > colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> > > E esta funcionando de boa!
> > 
> > 
> > O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas. Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.
> > O erro é este: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid') at Object.sendExist (:515:40) at async Object.sendMessage (:4686:7) at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12) at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22
> > Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?
> 
> Tenta atualizar o npm i puppeteer-core!

Tentei, mas não deu certo ainda infelizmente...

**Comment by GustavoTG75** [comment]
> > > Estou na Versão 5.0.1 com o puppeteer@19.11.1!
> > > Ajustei o arquivo venom-bot/dist/lib/wapi/wapi.js
> > > comentar esta linha 9312 //window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] || [];
> > > colocar este bloco no lugar if (typeof window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] === 'undefined'){ window[_helper__WEBPACK_IMPORTED_MODULE_1__.injectConfig.webpack] = [];}
> > > E esta funcionando de boa!
> > 
> > 
> > O meu estava funcionando normalmente até segunda-feira e depois parou de funcionar em torno das 18 horas. Agora quando estou rodando ele conecta, porém ele fica sempre carregando o "waiting for introduction". Além disso, quando envio uma mensagem com o insomnia ele dá um erro e não envia.
> > O erro é este: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid') at Object.sendExist (:515:40) at async Object.sendMessage (:4686:7) at ExecutionContext._ExecutionContext_evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:325:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (C:\testes\WSSENDERDEV\node_modules\puppeteer\node_modules\puppeteer-core\src\common\ExecutionContext.ts:187:12) at async C:\testes\WSSENDERDEV\node_modules\venom-bot\src\api\layers\sender.layer.ts:383:22
> > Estou com a versão 5.0.1 do venom-bot e mudei a versão do puppeteer para 19.11.1, também modifiquei o código , mas ainda não deu certo... Alguém sabe porque?
> 
> Tenta atualização pra versão **5.0.4**, e atualizar o puppeteer pra:
> 
> Puppeteer: ^20.7.1 Puppeteer Core: ^20.7.1
> 
> Além disso, se ainda tiver problemas, sugiro vc limpar os tokens gerados anteriormente (caso haja algum) ... no meu caso, em algumas das conexões eu tive que fazer isso pra ele pedir o qr code normalmente e continuar daí.

Tentei fazer isso também, tentei limpando também o package-lock.json e o node_modules e depois mandar o comando npm install, mas ainda não deu certo também...

**Comment by subburaja** [comment]
> Can you try a fresh install of latest version of venom-bot 5.0.6 in a new folder, for me this worked (Mac ventura + node 18, also with my linux vps), make sure you pass session name through options. 

like:
`venom
  .create({
    session: 'session-name' //name of session
  })`

If that still ends up with error post it here I can try solve.
