### ISSUE TITLE
Unable to run venom on AWS EC2 ubuntu server

### ISSUE THREAD

**Issue by Manjit2003** [orkestral/venom#232]
Hello @orkestral  currently I am trying to deploy the bot on  a EC2 instance but i am getting the following log in console:
```
- Checking for updates
- Checking for updates
- Waiting...
- Checking for updates
- Waiting...
- Checking for updates
- Error no open browser
Error no open browser
```

Please help me how can I solve this??

**Comment by joaosouz4** [comment]
u need disabled headless option

**Comment by orkestral** [comment]
use Browser WS for Amazon and Docker

**Comment by matheusm821** [comment]
which command?

**Comment by ryanwidjaja** [comment]
can anyone help this issue?

**Comment by mateusbadalotti** [comment]
Same error running on Linux / CentOS 8, chrome is installed on the machine and running, also the same error with chromium option. Any workaround for this issue? Windows is working fine.

**Comment by lucasscarduelli** [comment]
> use Browser WS for Amazon and Docker

@orkestral How can we use it correctly?

**Comment by tadeubarbosa** [comment]
I was with that same problem, someone share that code on the group that solve the problem to me:

```javascript
const chromiumArgs = [
  '--disable-web-security', '--no-sandbox', '--disable-web-security',
  '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
  '--disable-offline-load-stale-cache', '--disk-cache-size=0',
  '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
  '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
  '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
  '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'
];

// then put it in your venom create options:
venom.create({
	...
	browserArgs: chromiumArgs,
})
```

**Comment by lucasscarduelli** [comment]
Great, it's work to me!!

**Comment by mateusbadalotti** [comment]
Creating the app using the following args solved the issue.

`venom.create(
	'session',
	(base64Qrimg, asciiQR, attempts) => {},
	(statusSession, session) => {}, { useChrome: false, browserArgs: ['--no-sandbox'] }
).then((client) => start(client));`

**Comment by 2482103133** [comment]
if you have no browser installed,  install one.

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
sudo yum install ./google-chrome-stable_current_*.rpm

```

**Comment by huasipango** [comment]
> if you have no browser installed, install one.
> 
> ```
> wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
> sudo yum install ./google-chrome-stable_current_*.rpm
> ```
Using an Ubuntu 20.04 LTS DO Droplet.
Just to be sure.  There are the steps if you are not using a GUI server, just terminal:
```os
$ sudo apt update 
$ sudo apt upgrade   //If you don't get all the necessary packages in the OS, google-chrome installation will fail.
$ wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_89.0.4389.114-1_                     amd64.deb
$ sudo dpkg -i google-chrome-stable_89.0.4389.114-1_amd64.deb
```
