### ISSUE TITLE
TypeError when using Venom-bot - Cannot read properties of undefined

### ISSUE THREAD

**Issue by darley-raffael** [orkestral/venom#2327]
## Problem Description

I'm encountering the following error when using the Venom-bot package:

```
TypeError: Cannot read properties of undefined (reading 'erro')
    at /Users/darley.raffael/Lab/chat_bot_openai/node_modules/venom-bot/src/api/layers/sender.layer.ts:417:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Steps to Reproduce

1. I executed the following code:

```javascript
import { Message, Whatsapp, create } from "venom-bot";

create({
  session: "food-gpt",
  disableWelcome: true,
})
  .then(async (client: Whatsapp) => await start(client))
  .catch((err) => {
    console.log(err);
  });

async function start(client: Whatsapp) {
  client.onMessage(async (message: Message) => {
    if (!message.body || message.isGroupMsg) return;

    const response = "Hello!";

    await client.sendText(message.from, response);
  });
}
```

## Expected Behavior

I expected the above code to work correctly, responding to received messages with the response "Hello!".

## Current Behavior

However, I'm getting the aforementioned error, which indicates that the 'erro' property is undefined in the `sender.layer.ts` file of the Venom-bot package.

## Additional Information

- Venom-bot Version: 5.0.5
- Node.js Version: 18.16
- Operating System: Mac OS

**Comment by orkestral** [comment]
use latest version
