### ISSUE TITLE
Store.Chat is not object

### ISSUE THREAD

**Issue by ppiyushjv** [orkestral/venom#2329]
## Description

I used wap.js inject it and try to send message by WAPI.sendMessage2("919904700322@c.us","test",null).
I just on browser console Store.Chat is not object.

## Environment

Venom version(s): latest
Browser: Chrome
OS: Windows 11
Node version: Node 14

## Steps to Reproduce

WAPI.sendMessage2("919904700322@c.us","test",null)

## Additional context / Screenshot

![image](https://github.com/orkestral/venom/assets/13052658/e4a1925d-f64e-4d48-8a49-11173695fc95)

**Comment by orkestral** [comment]
fix: https://github.com/orkestral/venom/issues/2326
