### ISSUE TITLE
Client Token

### ISSUE THREAD

**Issue by leobevi** [orkestral/venom#233]
Olá.... Me desculpe o desconhecimento neste assunto, mas, não entendi ainda seria a finalidade desta funcionalidade na API. Ela se aplicaria para qual caso?

// To receive the client's token use the function await clinet.getSessionTokenBrowser()
    {
      WABrowserId: '"UnXjH....."',
      WASecretBundle:
        '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
      WAToken1: '"0i8...."',
      WAToken2: '"1@lPpzwC...."',
    }
  )

**Comment by jonalan7** [comment]
Você pode usar esse parâmetro para logar, ao invés de utilizar o arquivo que o bot cria, pois, quando logado o bot cria automaticamente um aquivo de token, no caminho: **tokens->session.data.json**.

Para receber o token do usuário quando logado, basta utilizar a função:

`const browserSessionToken = await client.getSessionTokenBrowser(); `

Ao utilizar essa função, você vai receber uma variável de tipo objeto, com os requintes parâmetros de exemplo:

```
{
WABrowserId: '"UnXjH....."',
WASecretBundle:
'{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
WAToken1: '"0i8...."',
WAToken2: '"1@lPpzwC...."',
}
```

Pode por exemplo guardar os parâmetros em algum banco de dados e depois adicional no Venom.create().

**Comment by leobevi** [comment]
Showww @jonalan7 !!! Obrigado pelo esclarecimento!!!
