### ISSUE TITLE
Venom with error in require

### ISSUE THREAD

**Issue by leanmarro** [orkestral/venom#2330]
## Description

i'm getting this error in version 5.0.5

## Environment

- **Venom version(s):** [5.0.5]
- **Browser:** [Chromium]
- **OS:** [Windows 10]
- **Node version:** [Node 16]

## Error:

C:\dev\avbot\node_modules\venom-bot\dist\controllers\check-up-to-date.js:7
const latest_version_1 = __importDefault(require("latest-version"));
                                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\dev\avbot\node_modules\latest-version\index.js from C:\dev\avbot\node_modules\venom-bot\dist\controllers\check-up-to-date.js not supported.
Instead change the require of index.js in C:\dev\avbot\node_modules\venom-bot\dist\controllers\check-up-to-date.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\dev\avbot\node_modules\venom-bot\dist\controllers\check-up-to-date.js:7:42)
    at Object.<anonymous> (C:\dev\avbot\node_modules\venom-bot\dist\controllers\init.js:4:28)
    at Object.<anonymous> (C:\dev\avbot\node_modules\venom-bot\dist\index.js:30:14)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by thalles7765** [comment]
follow issue #2326

**Comment by orkestral** [comment]
fix: https://github.com/orkestral/venom/issues/2326
