### ISSUE TITLE
Problemas na hora do disparo

### ISSUE THREAD

**Issue by Lavechia1** [orkestral/venom#2332]
Estou na versão 4.3.3 e lá na hora de disparar a mensagem, depois que já foi conectado no whatsapp, ele da essa mensagem de erro:

![image_2023_06_20T14_00_36_386Z](https://github.com/orkestral/venom/assets/36973845/bd1fd26a-b882-4442-ba6a-dfa7c21ba323)

conseguem me ajudar?

**Comment by orkestral** [comment]
use latest version, not support for previous versions
