### ISSUE TITLE
[TypeError]: Cannot read properties of undefined (reading 'createWid')

### ISSUE THREAD

**Issue by luisotavio756** [orkestral/venom#2337]
## Description

I'm trying to connect and I'm receiving this error when venom-bot starts.

## Environment

- **Venom version(s):** 5.0.6
- **Browser:** Chromium 113.0.5672.126 Fedora Project
- **OS:** Amazon Linux 2 AMI
- **Node version:** 16.19.0

## Steps to Reproduce

1. Connect to WhatsApp Venom by QR Code
2. Receives the success connection
3. The error is displayed

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

![image](https://github.com/orkestral/venom/assets/51246715/11f49469-bb13-4537-a0ea-72fa010e7795)

**Comment by luisotavio756** [comment]
I'm testing it locally and I'm facing the same problem:

![image](https://github.com/orkestral/venom/assets/51246715/da7e67d6-5d0a-44a7-8caa-b6f9caa0372c)

**Comment by EdesNogueira** [comment]
estou com quase o mesmo erro, já quebrei tanto a cabeça que nem sei mais o que fazer kkkk 

![erro](https://github.com/orkestral/venom/assets/132686747/a199a300-11cf-4d56-8427-4750cf786000)

**Comment by MatheusKonradXavier** [comment]
I'm facing the same issue

**Comment by yuryalencar** [comment]
One possible solution already mentioned is: https://github.com/orkestral/venom/issues/2314#issuecomment-1594537947

**Comment by MatheusKonradXavier** [comment]
[#2343](https://github.com/orkestral/venom/issues/2343#issuecomment-1601727830)  resolved my problem

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
