### ISSUE TITLE
How to run two instances of venom-bot (2 different Whatsapp) at the same time?

### ISSUE THREAD

**Issue by GuilhermeCunha** [orkestral/venom#234]
How to run two instances of venom-bot (2 different Whatsapp) at the same time? 

I believe this problem could be solved by opening Chrome as an anonymous tab, but I didn't see an option to do that

**Comment by jonalan7** [comment]
**Usando o mesmo número de Whatsapp, não é possível!**

**Comment by jonalan7** [comment]
**Using the same Whatsapp number, it is not possible!**

**Comment by GuilhermeCunha** [comment]
> **Using the same Whatsapp number, it is not possible!**

Can I use other browsers? Like Chrome, etc.

**Comment by GuilhermeCunha** [comment]
> **Using the same Whatsapp number, it is not possible!**

In fact what I want is to use several different whatsapp numbers at the same time.

**Comment by bhavya32** [comment]
@GuilhermeCunha Please read documentation and then open an issue. It is clearly given in docs.
