### ISSUE TITLE
I Have a Question About Being Banned from Whatsapp

### ISSUE THREAD

**Issue by leanmarro** [orkestral/venom#2345]
Pessoal, alguém ai está sendo banido temporariamente do Whatsapp também? se sim, conseguiram resolver? o motivo parece ser uso de versão não oficial do Whatsapp, porém nunca utilizei apps de terceiros, seria por conta do venom?

**Comment by victornassif** [comment]
Venom is a third-party app. Any external API with an owner different from Meta is considered as such

**Comment by VianaSamuel** [comment]
How often do these bans occur?
