### ISSUE TITLE
POll not working my code is

### ISSUE THREAD

**Issue by kumarnishu** [orkestral/venom#2347]
## Description

POll not working my code is

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

let client1 = "c1"
let client2 = "c2"

venom
    .create({
        session: client1 //name of session
    })
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });

function start(client) {
    client.onMessage((message) => {
        
        //send text
        // client.sendText(message.from, "hello nishu")

        //send poll
        const poll = {
            name: 'new poll',
            options: [
                {
                    name: 'option 1'
                },
                {
                    name: 'option 2'
                }
            ],
            selectableOptionsCount: 1
        }
        client.sendPollCreation(message.from, poll)

            .then((result) => {
                console.log('Result: ', result); //return object success
            })
            .catch((erro) => {
                console.error('Error when sending: ', erro); //return object error
            });
    });
}

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
