### ISSUE TITLE
Version 5 is not displaying the image preview (thumbnail)

### ISSUE THREAD

**Issue by Louise92rodriguez** [orkestral/venom#2348]
## Description

In Version 5 of Venom, the image preview (thumbnail) is not being displayed when images are sent to iOS or Android devices. Instead of the expected image preview, only a download button is shown, as illustrated in the attached image below. Interestingly, this issue does not occur on WhatsApp Web, where the image preview is displayed correctly.

![image](https://github.com/orkestral/venom/assets/86729771/ac943891-a091-4d09-bcd6-ae8f0908c12f)

## Environment

- **Venom version(s):**   5.0.0 and above (to 5.0.6)
- **Browser:**   Chrome and Chromium last stable versions
- **OS:** debian. 
- **Node version:**   Node 14 and above

## Steps to Reproduce
Just send and image in both: sendImage or sendImageFromBase64 for iOS or Android devices.

**Comment by hermanorigotto** [comment]
The same issue for me, any progress will be appreciated!

**Comment by luigiradano** [comment]
Maybe unrelated but when sending images as stickers from the bot the sticker cannot be downloaded, seems like it could be the same underlying issue

**Comment by ShubhamPipaliya** [comment]
@Louise92rodriguez  
any update on this ?,  we are facing same issue.

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

**Comment by Louise92rodriguez** [comment]
Hello, @orkestral, there is any additional parameter to pass on sendImage to create an image thumbnail? stills not working for me on 5.0.11

**Comment by Louise92rodriguez** [comment]
> @Louise92rodriguez any update on this ?, we are facing same issue.

I am trying on v5.0.11 with 

```
// Send image (you can also upload an image using a valid HTTP protocol)
await client
  .sendImage(
    '000000000000@c.us',
    'path/to/img.jpg',
    'image-name',
    'Caption text'
  )
```
  
 It's not creating the thumbnail.

**Comment by Louise92rodriguez** [comment]
> any update

in v5.0.11 supposed to be ok, but not for me!
