### ISSUE TITLE
Deploy Open Browser 

### ISSUE THREAD

**Issue by PedroPaduelo** [orkestral/venom#2349]
## Description

Erro ao utilizar 
![image](https://github.com/orkestral/venom/assets/37857002/ca82eab7-0bb8-4fc4-8098-9b36b6ef5205)

Não esta sendo reconhecido e no servidor esta dando erro de --no-sandbox

**Comment by xbral** [comment]
Aparentemente ele não está reconhecendo nenhuma configuração inserida na função create, e está setando tudo como default.

**Comment by PedroPaduelo** [comment]
Então mas nesse caso ela não esta rodando em servidor Docker por que o browser não abre. 

Como que faço para corrigir isso ?

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
