### ISSUE TITLE
[BUG] getConnectionState() is buggy + [Feature Request]

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#235]
BUG
The onStateChange event is not triggered when venom session is started successfully. So even though connection is established, getConnectionState() is stuck waiting on promise. 

It works fine after a timeout and connected.
Feature Request
Venom should trigger the onStateChange manually at first when connection is established successfully.

**Comment by joaosouz4** [comment]
you can receive what you want by the third parameter of create sessionstatus.

**Comment by joaosouz4** [comment]
onStateChange had a bug because of whatsapp itself, but this has already been fixed

**Comment by bhavya32** [comment]
@joaosouz4 I am well aware of that and was using the same. What function start(client) was called I put 'Connected' in an array. Then when onStatechange was called, I updated the value in my array. I just came here to tell the issue in a function. Can you refer me to the commit? For me, its still the same bug.

**Comment by joaosouz4dev** [comment]
I think this has already been fixed
