### ISSUE TITLE
Erro ao instalar a lib 

### ISSUE THREAD

**Issue by PedroPaduelo** [orkestral/venom#2353]
Toda vez que atualizão a lib querbra meu deus como usar assim.

**Comment by Nathan-Romano** [comment]
aqui quebrou também, tava tudo de boa, de repente. zoou tudo

**Comment by RickGroenewegen** [comment]
Also getting the 'No open browser' error

**Comment by PwccaCode** [comment]
mesmo problema aqui

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
