### ISSUE TITLE
getGroupMembers is not working

### ISSUE THREAD

**Issue by sudeepaviraj** [orkestral/venom#2354]
## getGroupMembers is not working

getGroupMembers function is not working when I tried to get group members

## Environment

- **Venom version(s):** 5.0.6
- **Browser:** Chrome 114
- **OS:** Windows 11
- **Node version:** Node 20

## Log Output

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [TypeError]: window.Store.Cmd.openChatBottom is not a function
    at ExecutionContext._ExecutionContext_evaluate (D:\Programming-Projects\whatsapp-grabber\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:262:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\Programming-Projects\whatsapp-grabber\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:145:16)
    at window.WAPI.window.WAPI.getGroupParticipant (D:\Programming-Projects\whatsapp-grabber\node_modules\venom-bot\dist\lib\wapi\wapi.js:0:86341)

Node.js v20.2.0
```

## My Code

```
client.getGroupMembers(group.id).then(async (number) => {
                        fs.appendFileSync(`output.txt`, `${group.name}\n`)
                        console.log(`\n${number.length - 1} Numbers Found In ${group.name}\n`);
                        let bar1 = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);
                        bar1.start(number.length - 1, 0)
                        let numberlist = []
                        number.forEach(async (user, index) => {
                            if (!user.isMe) {
                                fs.appendFileSync(`output.txt`, `${user.id.user}\n`)
                                numberlist = [...numberlist,{id:index,number:user.id.user,user_id:user.id._serialized,group:group.name}]
                                bar1.increment()
                            }
                        });
                        ExportToExcel(numberlist,group_index)
                        bar1.stop()
                        console.log(`\n${group.name} Numbers Saved!\n`);
                    });
```

## Additional context / Screenshot

[![Hi9ibwB.md.jpg](https://iili.io/Hi9ibwB.md.jpg)](https://freeimage.host/i/Hi9ibwB)

**Comment by ghayman** [comment]
+1

**Comment by ghayman** [comment]
@orkestral I know you guys probably hate my hacking but here is a possible solution. I'm not putting it through as a PR as I don't know the unexpected consequences.
I commented out the call to openChatBottom() - I could not seeing it add any value but I might be wrong.
I rebuilt the dist and the getGroupParticipant() returned the participants.

Other people - please comment. This may or may not be a solution. 

```typescript
export async function getGroupParticipant(groupId, time = 1000) {
  if (typeof groupId !== 'string') {
    return WAPI.scope(undefined, true, null, 'Use to groupId string');
  }

  const chat = await WAPI.sendExist(groupId);

  if (chat && chat.status != 404 && chat.id) {
    // await window.Store.Cmd.openChatBottom(chat);
    // await sleep(time);
    const moduleGroup = await window.Store.GroupMetadata._models.filter(
      (e) => e.id._serialized === groupId
    );

: 
: 
: 

```

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

**Comment by SMe12435** [comment]
> @orkestral I know you guys probably hate my hacking but here is a possible solution. I'm not putting it through as a PR (yet) as I don't know the unexpected consequences. I commented out the call to openChatBottom() - I could not seeing it adding any value but I might be wrong. I rebuilt the dist and the getGroupParticipant() returned the participants.
> 
> I should add that this is being called during onAnyMessage() so maybe other things are being loaded at the same time outside of this.
> 
> Other people - please comment. This may or may not be a solution.
> 
> ```ts
> export async function getGroupParticipant(groupId, time = 1000) {
>   if (typeof groupId !== 'string') {
>     return WAPI.scope(undefined, true, null, 'Use to groupId string');
>   }
> 
>   const chat = await WAPI.sendExist(groupId);
> 
>   if (chat && chat.status != 404 && chat.id) {
>     // await window.Store.Cmd.openChatBottom(chat);
>     // await sleep(time);
>     const moduleGroup = await window.Store.GroupMetadata._models.filter(
>       (e) => e.id._serialized === groupId
>     );
> 
> : 
> : 
> : 
> ```

This worked for me. Thanks <3

**Comment by pedroota** [comment]
This still an issue for me, I'm facing the same problem here 

Error:
![image](https://github.com/orkestral/venom/assets/48136045/9cbf987d-6930-4002-ada9-46ed0599f688)


My code:
![image](https://github.com/orkestral/venom/assets/48136045/602d6426-f37b-4360-b225-5ad3159f46cd)

**Comment by ddimoia-wt** [comment]
> This still an issue for me, I'm facing the same problem here
> 
Hi have you solved the issue?
