### ISSUE TITLE
Error no open browser

### ISSUE THREAD

**Issue by ssouza** [orkestral/venom#2357]
## Description

Apresentando o erro: _"Error no open browser"_ ao executar um código simples

## Environment

- **Venom version(s):** 5.0.7
- **Browser:** Chrome 114.0.5735.133 (Official Build) (arm64)
- **OS:** macOS 13.2.1 (22D68) - Apple M1
- **Node version:** v19.3.0

## Log Output

```
❯ node index.js
You're up to date 🎉🎉🎉
✖ Error no open browser....
Error no open browser....
```

## Your Code
```json
{
  "name": "bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "venom-bot": "^5.0.7"
  }
}

```

```js
const venom = require('venom-bot');

venom
  .create('bot')
  .then((client) => start(client))
  .catch((error) => console.log(error));
```

**Comment by josetetevi95** [comment]
Hi, 
same error; 
I use MacPro i7 

`
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680:34)
    at DOMWorld.waitForFunction (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:611:26)
    at Frame.waitForFunction (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1089:32)
    at Page.waitForFunction (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2385:33)
    at injectApi (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/venom-bot/dist/controllers/browser.js:140:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/Users/niffobscurus/nodeJs/whatsappbaseproject/node_modules/venom-bot/dist/controllers/initializer.js:297:9)

`

**Comment by PedroPaduelo** [comment]
Mesmo erro aqui e toda vez que a libe tem uma atualização quebra tudo

**Comment by karein** [comment]
> ## Description
> Apresentando o erro: _"Error no open browser"_ ao executar um código simples
> 
> ## Environment
> * **Venom version(s):** 5.0.7
> * **Browser:** Chrome 114.0.5735.133 (Official Build) (arm64)
> * **OS:** macOS 13.2.1 (22D68) - Apple M1
> * **Node version:** v19.3.0
> 
> ## Log Output
> ```
> ❯ node index.js
> You're up to date 🎉🎉🎉
> ✖ Error no open browser....
> Error no open browser....
> ```
> 
> ## Your Code
> ```json
> {
>   "name": "bot",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "venom-bot": "^5.0.7"
>   }
> }
> ```
> 
> ```js
> const venom = require('venom-bot');
> 
> venom
>   .create('bot')
>   .then((client) => start(client))
>   .catch((error) => console.log(error));
> ```

versão: ^5.0.7
Você pode tentar alterar o código passando o argumento `session` no seu código

```javascript
venom
  // .create('bot')
  .create({ session: 'bot' })
  .then((client) => start(client))
  .catch((error) => console.log(error));
```

Eu criei um arquivo .js simple e, dessa forma ele rodou e mostrou o QrCode.
Espero que ajude

**Comment by ssouza** [comment]
> > ## Description
> > Apresentando o erro: _"Error no open browser"_ ao executar um código simples
> > ## Environment
> > 
> > * **Venom version(s):** 5.0.7
> > * **Browser:** Chrome 114.0.5735.133 (Official Build) (arm64)
> > * **OS:** macOS 13.2.1 (22D68) - Apple M1
> > * **Node version:** v19.3.0
> > 
> > ## Log Output
> > ```
> > ❯ node index.js
> > You're up to date 🎉🎉🎉
> > ✖ Error no open browser....
> > Error no open browser....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Your Code
> > ```json
> > {
> >   "name": "bot",
> >   "version": "1.0.0",
> >   "description": "",
> >   "main": "index.js",
> >   "scripts": {
> >     "test": "echo \"Error: no test specified\" && exit 1"
> >   },
> >   "author": "",
> >   "license": "ISC",
> >   "dependencies": {
> >     "venom-bot": "^5.0.7"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > const venom = require('venom-bot');
> > 
> > venom
> >   .create('bot')
> >   .then((client) => start(client))
> >   .catch((error) => console.log(error));
> > ```
> 
> versão: ^5.0.7 Você pode tentar alterar o código passando o argumento `session` no cretate
> 
> ```js
> venom
>   // .create('bot')
>   .create({ session: 'bot' })
>   .then((client) => start(client))
>   .catch((error) => console.log(error));
> ```
> 
> Eu criei um arquivo .js simples e, dessa forma ele rodou e mostrou o QrCode. Espero que ajude

Parece ser um erro intermitente... fiz como sugeriu e funcionou... voltei usando o `.create('bot')` e funcionou tb. Bem estranho!

**Comment by josetetevi95** [comment]
I am update package and use 
```javascript
.create('bot)
``` 

tanks

**Comment by l3and49** [comment]
O meu continua dando erro. Meu código:
#!/usr/bin/env node
// Supports ES6
const bot = require("venom-bot");
const { db } = require("../src/models/banco");
const { step } = require("../src/models/stages");

bot.create({ 
    session: 'bot2',
    headless : true,
    puppeteerOptions: {ignoreDefaultArgs: ['--disable-extensions']},
}).then((client) => start(client))
.catch((error) => {
    console.error('Erro ao criar o cliente do bot:', error);
});

let m_varResp = null;

function start(client) {
    client.onMessage((message) => { //executa quando o cliente manda uma mensagem
         console.log(new Date() + " Interação do usuário.");
        if (message.isGroupMsg === false || message.isGroupMsg == undefined) { 
            m_varResp = step[getStage(message.from)].obj.execute(
                message.from,
                message.body,
            );
            if(m_varResp == "0") //resposta que retorna direto sem precisar de mensagem
            {
                m_varResp = step[getStage(message.from)].obj.execute(
                    message.from,
                    message.body,
                );
            }
            for (let m_varIndex = 0; m_varIndex < m_varResp.length; m_varIndex++) //imprime a mensagem do estado
            {
                const element = m_varResp[m_varIndex];
                console.log(" elemento: " + element)
                client.sendText(message.from, element);
            }
        }
    });
}

function getStage(user) {
    if (db[user]) {
        //Se existir esse numero no banco de dados
        return db[user].stage;
    } else {
        console.log("Acessando menu");
        //Se for a primeira vez que entra e contato
        db[user] = {
            stage: "menu_0",
        };
        return db[user].stage;
    }
}

**Comment by PedroPaduelo** [comment]
Continuo com erros

**Comment by l3and49** [comment]
Eu também infelizmente

**Comment by georgepes06** [comment]
Soluçao =>  bot.create({ session: 'bot' }).then((client) => start(client));

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

**Comment by lucasgabrielba** [comment]
aqui mostro como solicitei o problema: https://www.youtube.com/watch?v=Tg6_SsOY9mA

**Comment by subburaja** [comment]
Deleting session named folder under "tokens" folder helped me resolve issue version "5.0.19". Because of some kind of lock happening with session folders created using previous version or something like that. That lock prevents browser session from starting.

**Comment by matheus-ma1a** [comment]
Tive este erro ao fazer deploy na hostsquare

**Comment by vitorfail** [comment]
> Tive este erro ao fazer deploy na hostsquare



> Tive este erro ao fazer deploy na hostsquare

é possivel fazer deploy do venom em algum lugar?

**Comment by matheus-ma1a** [comment]
Sim, porem voce precisa colocar ele em uma vps, por conta do puppeteer

**Comment by fakedamage** [comment]
Fala Pessoal, bão? eu to bão...
Então, eu desconfiei que esse problema acontecia por conta da string utilizada ao criar a session... entao, utilizei essa função para remover qualquer caractere especial ou acentos e **funcionou**!

```
 removeSpecialCharacters(str: string): string {
    return str
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-zA-Z0-9 ]/g, "");
  }

```

create(
    this.removeSpecialCharacters(variable),

**Comment by marcelodive** [comment]
Here only worked like that (aqui funcionou só assim):

```
venom
  .create({
    session: 'bot',
    multidevice: true,
    headless: false,
    useChrome: true,
    debug: true,
    logQR: true,
    browserArgs: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--no-first-run',
      '--no-zygote',
      '--disable-gpu'
    ],
    puppeteerOptions: {
      headless: false,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--disable-gpu'
      ]
    },
    disableWelcome: true,
    updatesLog: true,
    autoClose: false,
    createPathFileToken: true,
  })
  .then((client) => {
   ...
  }
```
