### ISSUE TITLE
WAPI.getAllContacts function no longer works

### ISSUE THREAD

**Issue by eduardoff19** [orkestral/venom#2358]
## Description

the getAllContacts function - no longer returns any results, it no longer searches for whatsapp contacts, how can I solve it?

## Environment

- **Venom version(s):** [5.0.7]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [Windows 11]
- **Node version:** [v20.3.1.]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Your Code

            const getAllContacts = function () {
                const allContacts = window.Store.Contact.map((contact) =>
                  WAPI._serializeContactObj(contact)
                );
              
                return allContacts.filter((result) => {
                  return result.isUser === true;
                });
              };

```
If relevant, paste all of your challenge code in here
```

**Comment by rafahlobo** [comment]
The same problem.
I think whatsapp removed these attributes from the store.

**Comment by PwccaCode** [comment]
i was able to reproduce

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
