### ISSUE TITLE
Close unconnected sessions.

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#236]
Scan QR code with venom and close venom and turn off Internet on phone.
Then start venom. The session will be created. (do not turn on mobile data yet). 

Venom will stay in .create() function. So we do not get the client variable. As QR code is already scanned, autoClose does not work in this case. I want to close such session. 

Since client variable does not exists, we can not do client.close();

**Comment by jonalan7** [comment]
**Does autoclose not work?**

**Comment by bhavya32** [comment]
@jonalan7 the qrcode was already scanned the previous time. Autoclose only works in case when qr code is not scanned.

**Comment by bhavya32** [comment]
Sorry I closed accidentally.

**Comment by bhavya32** [comment]
@joaosouz4 @jonalan7 Did  you got my problem or should I clarify more? I believe venom would have to return browser info required to close browser earlier when creating session.

**Comment by helloeyesimple** [comment]
@bhavya32 have you tried using onStateChange that mentioned on documentation?

**Comment by jonalan7** [comment]
**I'll be fixing this problem!**

**Comment by Lucipher** [comment]
The same issue for a long time~
