### ISSUE TITLE
Old way of sending MP3s

### ISSUE THREAD

**Issue by luigiradano** [orkestral/venom#2360]
**Is your feature request related to a problem? Please describe.**
I have used venom in the past and I remember I could send MP3s as if I were sending an audio file from my phone, now however I cannot find a way to do that. Sendfile sends the file but it appears as a document which is ugly, sendvoice also sends the file but it is a ptt and that's not what I want.

**Describe the solution you'd like**
Introduce a function like sendAudio that sends the audio in the right form (not ptt or document)

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

**Comment by eduardozaniboni** [comment]
I can't send audios, what should I use?

**Comment by eduardozaniboni** [comment]
> [Versão 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

I can't send audios, what should I use?
