### ISSUE TITLE
sendSeen() not working

### ISSUE THREAD

**Issue by luigiradano** [orkestral/venom#2361]
## Description
Trying to send seen to a message chat when it arrives but it seems that the execution gets stuck at client.sendSeen() (what's after doesn't get executed and the .then() callback is never called). I tried rearranging the code to avoid issues when it blocks but it still doesn't mark messages as read.
I also send files to the chat, when I do that the messages are marked as read...
## Environment

- **Venom version(s):**5.0.6
- **Browser:**  Chromium
- **OS:** Windows 11
- **Node version:** 18.16.0

## Your Code

```javascript
function start(client) {
    client.onMessage((message) => { //Set up RX interrupt
        
        console.log(message)
        
        if(message.type == "chat")
            onChatHandler(client, message);
        client.send
    });
}
```

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
