### ISSUE TITLE
Error no open browser 

### ISSUE THREAD

**Issue by l3and49** [orkestral/venom#2362]
## Environment

- **Venom version(s):** [^5.0..7]
- **Browser:** [linux-114.0.5735.133]
- **Node version:** [16.19.1]

## Steps to Reproduce

1. Segui o caminho ao iniciar
2. Ele entra no browser.js
3. Cai na função abaixo
4.Vai para o catch

## Log Output

```
Unable to load the sleep module (no animations available)
You're up to date 🎉🎉🎉
✖ Error no open browser....
Erro ao criar o cliente do bot: Error no open browser....
```

## Your Code

```
async function initBrowser(options) {
    var _a, _b, _c;
    try {
        folderSession(options);
        // Set the executable path to the path of the Chrome binary or the executable path provided
        const executablePath = (_a = getChrome()) !== null && _a !== void 0 ? _a : puppeteer_extra_1.default.executablePath();
        console.log('Path Chrome: ', executablePath);
        const extras = { executablePath };
        // Use stealth plugin to avoid being detected as a bot
        puppeteer_extra_1.default.use((0, puppeteer_extra_plugin_stealth_1.default)());
        if (Array.isArray(options.addProxy) && options.addProxy.length) {
            const proxy = options.addProxy[Math.floor(Math.random() * options.addProxy.length)];
            const args = (_b = options.browserArgs) !== null && _b !== void 0 ? _b : puppeteer_config_1.puppeteerConfig.chromiumArgs;
            args.push(`--proxy-server=${proxy}`);
        }
        if (Array.isArray(options.addBrowserArgs) &&
            options.addBrowserArgs.length) {
            options.addBrowserArgs.forEach((arg) => {
                if (!puppeteer_config_1.puppeteerConfig.chromiumArgs.includes(arg)) {
                    puppeteer_config_1.puppeteerConfig.chromiumArgs.push(arg);
                }
            });
        }
        const launchOptions = {
            headless: options.headless,
            devtools: options.devtools,
            args: (_c = options.browserArgs) !== null && _c !== void 0 ? _c : puppeteer_config_1.puppeteerConfig.chromiumArgs,
            ...options.puppeteerOptions,
            ...extras
        };
        if (options.browserWS && options.browserWS !== '') {
            return await puppeteer_extra_1.default.connect({ browserWSEndpoint: options.browserWS });
        }
        else {
            return await puppeteer_extra_1.default.launch(launchOptions);
        }
    }
    catch (_d) {
        return false;
    }
}
```

## Additional context / Screenshot

Caso ajude
![print](https://github.com/orkestral/venom/assets/126525698/50b64f02-97bf-43bf-8bc1-3abcce4f0d88)

**Comment by PedroPaduelo** [comment]
Mesmo erro aqui

**Comment by PedroPaduelo** [comment]
Pessoal achei erro e corrigi para que não de este erro mais. 
O erro esta no arquivo browser.ts como esta no print abaixo 
![image](https://github.com/orkestral/venom/assets/37857002/c58b41e6-ee85-465f-bfd4-13735db95992)

**Comment by rafaelsnnoleto** [comment]
Same bug: https://github.com/orkestral/venom/issues/2357

replace `.create('bot')` with `.create({ session: 'bot' })`

it worked for me (v5.0.7).

**Comment by l3and49** [comment]
> Mesmo bug: #2357
> 
> substituir `.create('bot')`por`.create({ session: 'bot' })`
> 
> funcionou para mim (v5.0.7).
> 
> ```
> async reconnect(req: Request): Promise<Whatsapp | null> {
>     let currentBrowserPid = undefined;
> 
>     try {
>         return await venom.create({ session: req.query.sessionName as string }, undefined, undefined, {
>             logQR: false,
>             autoClose: 60000,
>             reconnect: false
>             // browserArgs: ['--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36']
>         }, (browser: Browser, waPage: any) => {
>             currentBrowserPid = browser?.process()?.pid;
>         });
>     } catch (erro) {
>         this.killProcess(currentBrowserPid);
>         Session.deleteSession(req);
>         console.trace(this.currentDateTimeToLog() + "WhatsappService.reconnect: Não foi possível reconectar.");
>         return null;
>     }
> }
> ```

Onde isso foi colocado?

**Comment by l3and49** [comment]
Após pedirem para atualziar o venom-bot para o '5.0.11', apareceu os seguintes erros
![Pritn](https://github.com/orkestral/venom/assets/126525698/82391057-7378-4ed0-941a-aa147ec05679)
Porém ao entrar no site que está ai, fala que o erro é bug porque o node está abaixo do 14.0.0, porém estou usando o 16.19.1

**Comment by karein** [comment]
Essa versão também me retornou erro, mas acho que o meu caiu em um tratamento de erro diferente, já que retornou um `console.log('aqui');`
![Captura de tela de 2023-07-03 15-59-24](https://github.com/orkestral/venom/assets/32269228/5d75ba70-26df-44f0-9065-a3c044c08ed2)
No seu caso, você sabe se o seu navegador está instalado nessa rota mesmo '/root/.cache/puppeterr[...]'?
Ou verificar se você tem essa `libnss3.so`? 
no seu erro parece não estar encontrando

**Comment by l3and49** [comment]
Ele retorna o console.log("aqui") pois cai onde o Pedro Paduelo colocou ele, no meu também cai ai, porém não coloquei esse "Aviso", sabe?

**Comment by PedroPaduelo** [comment]
Nessa versão tem um log de de validação para se execução mas que aparentemente ja foi corrigido, porém o log ficou. 

![image](https://github.com/orkestral/venom/assets/37857002/7b6f0a95-9ebf-437f-a06e-5c79c97ddf9f)

**Comment by rafaelsnnoleto** [comment]
> > Mesmo bug: #2357
> > substituir `.create('bot')`por`.create({ session: 'bot' })`
> > funcionou para mim (v5.0.7).
> > ```
> > async reconnect(req: Request): Promise<Whatsapp | null> {
> >     let currentBrowserPid = undefined;
> > 
> >     try {
> >         return await venom.create({ session: req.query.sessionName as string }, undefined, undefined, {
> >             logQR: false,
> >             autoClose: 60000,
> >             reconnect: false
> >             // browserArgs: ['--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36']
> >         }, (browser: Browser, waPage: any) => {
> >             currentBrowserPid = browser?.process()?.pid;
> >         });
> >     } catch (erro) {
> >         this.killProcess(currentBrowserPid);
> >         Session.deleteSession(req);
> >         console.trace(this.currentDateTimeToLog() + "WhatsappService.reconnect: Não foi possível reconectar.");
> >         return null;
> >     }
> > }
> > ```
> 
> Onde isso foi colocado?

@l3and49 
Guy, the example code is for using the framework, the problem was in the connection creation function.


The following code has been modified from
await venom.create("nomeDaSessao")...

to
await venom.create({ session: "nomeDaSessao"}

**Comment by supremurs33** [comment]
i just open my package.json and change the version, downgrade to version before update in my case was "venom-bot": "^5.0.1"

**Comment by karein** [comment]
O `puppeteer` mostra a mensagem de que o `headless` vai passar a ser `new`, (não sei como estava nas versões anteriores) mas o venom funcionou depois de trocar o headless pra `true/false` no `create` ou direto dentro do módulo. E não abre o browser quando uso o `new` 

![Captura de tela de 2023-07-04 09-11-28](https://github.com/orkestral/venom/assets/32269228/29da7a34-e5f1-4563-b434-395749dfe285)

**Comment by karein** [comment]
> Troquei o headless para true e false, mas mesmo assim ele continua dando erros. ![image](https://user-images.githubusercontent.com/126525698/250952120-56740343-5198-406f-95f8-969d433015f8.png)

Você viu se tem a lib que aparece no erro `libnss3.so`?
Eu não consegui o mesmo erro mas tentei simular um parecido com o seu, e movi essa lib do diretório dela pra outro.
Sem ela o venom retorna o erro 

> Error: Failed to launch the browser process! 
undefined /usr/bin/google-chrome-stable: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

mas quando movi ela de volta pro diretório que ela pertence, o venom conseguiu lançar o browser

**Comment by fedejuret** [comment]
Same error here with `"venom-bot": "^5.0.11"` and Nodejs v18.16.0

**Comment by l3and49** [comment]
> > Troquei o headless para true e false, mas mesmo assim ele continua dando erros. ![image](https://user-images.githubusercontent.com/126525698/250952120-56740343-5198-406f-95f8-969d433015f8.png)
> 
> Você viu se tem a lib que aparece no erro `libnss3.so`? Eu não consegui o mesmo erro mas tentei simular um parecido com o seu, e movi essa lib do diretório dela pra outro. Sem ela o venom retorna o erro
> 
> > Error: Failed to launch the browser process!
> > undefined /usr/bin/google-chrome-stable: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> 
> mas quando movi ela de volta pro diretório que ela pertence, o venom conseguiu lançar o browser

Quando cou ctrl + click nesses caminhos ele sempre acha, por isso que também não estou entendendo o motivo do erro, entende?

**Comment by karein** [comment]
> > > Troquei o headless para true e false, mas mesmo assim ele continua dando erros. ![image](https://user-images.githubusercontent.com/126525698/250952120-56740343-5198-406f-95f8-969d433015f8.png)
> > 
> > 
> > Você viu se tem a lib que aparece no erro `libnss3.so`? Eu não consegui o mesmo erro mas tentei simular um parecido com o seu, e movi essa lib do diretório dela pra outro. Sem ela o venom retorna o erro
> > > Error: Failed to launch the browser process!
> > > undefined /usr/bin/google-chrome-stable: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> > 
> > 
> > mas quando movi ela de volta pro diretório que ela pertence, o venom conseguiu lançar o browser
> 
> Quando cou ctrl + click nesses caminhos ele sempre acha, por isso que também não estou entendendo o motivo do erro, entende?

E a versão da lib, você consegue ver?
[Checking a Library Version in Linux
](https://www.baeldung.com/linux/check-library-version#:~:text=Using%20the%20dpkg%20Command&text=By%20using%20dpkg%2C%20we%20can,library%20installed%20on%20our%20system)

**Comment by karein** [comment]
> > > Troquei o headless para true e false, mas mesmo assim ele continua dando erros. ![image](https://user-images.githubusercontent.com/126525698/250952120-56740343-5198-406f-95f8-969d433015f8.png)
> > 
> > 
> > Você viu se tem a lib que aparece no erro `libnss3.so`? Eu não consegui o mesmo erro mas tentei simular um parecido com o seu, e movi essa lib do diretório dela pra outro. Sem ela o venom retorna o erro
> > > Error: Failed to launch the browser process!
> > > undefined /usr/bin/google-chrome-stable: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> > 
> > 
> > mas quando movi ela de volta pro diretório que ela pertence, o venom conseguiu lançar o browser
> 
> Quando cou ctrl + click nesses caminhos ele sempre acha, por isso que também não estou entendendo o motivo do erro, entende?

E a versão da lib, você consegue ver?
Pra atualizar talvez, caso seja menor que 3.30
[Checking a Library Version in Linux
](https://www.baeldung.com/linux/check-library-version#:~:text=Using%20the%20dpkg%20Command&text=By%20using%20dpkg%2C%20we%20can,library%20installed%20on%20our%20system)

**Comment by orkestral** [comment]
[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)

**Comment by l3and49** [comment]
> > > > Troquei o headless para true e false, mas mesmo assim ele continua dando erros.![imagem](https://user-images.githubusercontent.com/126525698/250952120-56740343-5198-406f-95f8-969d433015f8.png)
> > > 
> > > 
> > > Você viu se tem a lib que aparece sem erro `libnss3.so`? Eu não consegui o mesmo erro, mas tentei simular um parecido com o seu, e movi essa lib do diretório dela pra outro. Sem ela o veneno retorna o erro
> > > > Erro: Falha ao iniciar o processo do navegador! 
> > > > indefinido /usr/bin/google-chrome-stable: erro ao carregar bibliotecas compartilhadas: libnss3.so: não é possível abrir arquivo de objeto compartilhado: arquivo ou diretório inexistente
> > > 
> > > 
> > > mas quando movi ela de volta pro diretório que ela pertence, o venom conseguiu lançar o navegador
> > 
> > 
> > Quando cou ctrl + click nesses caminhos ele sempre acha, por isso que também não estou entendendo o motivo do erro, entende?
> 
> E a versão da lib, você consegue ver? Pra atualizar talvez, caso seja menor que 3.30 [Checking a Library Version in Linux ](https://www.baeldung.com/linux/check-library-version#:~:text=Using%20the%20dpkg%20Command&text=By%20using%20dpkg%2C%20we%20can,library%20installed%20on%20our%20system)

Está na versão 3.26.2, sabe como faço para atualiza-la?

**Comment by karein** [comment]
@l3and49 
Não sei muito não,
Talvez esses links ajudem, mas qualquer coisa você dá uma pesquisada melhor que alguém já deve ter feito posts a respeito.
Espero que ajude 👍

[How to Upgrade Packages on Ubuntu via Command Line](https://tecadmin.net/upgrading-ubuntu-packages-command-line/#:~:text=Update%20Ubuntu%20Packages,all%20repositories%20on%20your%20system.&text=Then%20run%20the%20upgrade%20command,versions%20from%20the%20configured%20sources)
[askubuntu](https://askubuntu.com/a/1209974)

**Comment by l3and49** [comment]
Atualizei aqui, porém fala que a 3.26 é a última versão, muito confuso, mas obrigado pela ajuda e atenção!

**Comment by l3and49** [comment]
Continuo com os seguintes erros agora
![image](https://github.com/orkestral/venom/assets/126525698/16da0513-dca1-45b7-9dc8-5e17159c0ee1)

**Comment by l3and49** [comment]
Alguém sabe como arrumar esse erro?
![image](https://github.com/orkestral/venom/assets/126525698/7035d676-a97b-4bde-b8c9-0c105e499539)
