### ISSUE TITLE
if (!this.spinners[name]) throw Error(`No spinner initialized with name ${name}`);

### ISSUE THREAD

**Issue by djmarcosban** [orkestral/venom#2363]
## Description

i got the same error every time after update the code. I already deleted node_modules and tokens folders.

## Environment

Venom version(s): [^5.0..7]
Browser: [linux-114.0.5735.133]
Node version: [16.19.1]

## Steps to Reproduce

i just npm run dev, after receive success message "headless option is active, browser hidden" then show following error:

if (!this.spinners[name]) throw Error(`No spinner initialized with name ${name}`);
                                    ^
Error: No spinner initialized with name browser-ws-sender-dev-dev
    at Spinnies.setSpinnerProperties (C:\apps\wppbot\node_modules\spinnies\index.js:107:37)
    at Spinnies.succeed (C:\apps\wppbot\node_modules\spinnies\index.js:62:10)
    at C:\apps\wppbot\node_modules\venom-bot\src\controllers\initializer.ts:206:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by orkestral** [comment]
#7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2

**Comment by orkestral** [comment]
#7cb6d93

**Comment by orkestral** [comment]
#[Release 5.0.11](https://github.com/orkestral/venom/commit/7cb6d93c8cb603cad052ee5ebd9cbdd87c318ca2)
