### ISSUE TITLE
Failed to launch the browser process! undefined

### ISSUE THREAD

**Issue by gabriellemos197** [orkestral/venom#2372]
## Description

Venom not starting on restart

## Environment

- **Venom version(s):** [5.0.11]

## My Code

```
venom.create(
    {session: 'name-session'}, 
    (base64Qrimg, asciiQR, attempts) => {
      console.log('Number of attempts to read the qrcode: ', attempts);
      //console.log('Terminal qrcode: ', asciiQR);
      //console.log('base64 image string qrcode: ', base64Qrimg);
      qr = base64Qrimg;
    },
    (statusSession, session) => {
      console.log('Status Session: ', statusSession); 
      console.log('Session name: ', session);
    },
    {
      headless: true,
      puppeteerOptions: {
        ignoreDefaultArgs: ['--disable-extensions']
      },
    }
    )
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });
```

## Error Code

```
You're up to date 🎉🎉🎉
Status Session:  initBrowser
Session name:  name-session
Path Google-Chrome:  /usr/bin/google-chrome-stable
aqui
Error: Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/root/whatsapp-api-venom-simple/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at ChildProcess.emit (node:events:525:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
✖ Error no open browser....
Status Session:  noOpenBrowser
```

**Comment by fedejuret** [comment]
Same error here!

**Comment by CarlosAurelioMRF** [comment]
I've got this same error but I found a temp solution:

If you're using version 5.0.11:

1. go to `.\node_modules\venom-bot\dist\controllers\browser.js`
2. search for `const browser = await puppeteer_extra_1.default.launch({` should be on line 251 
3. just add `args: ['--no-sandbox'],` to next line.

Like this:
![image](https://github.com/orkestral/venom/assets/28075600/43d08ff4-0f0d-4cf5-a0ac-d0d23a5c3a33)

**Comment by RickGroenewegen** [comment]
Same error. After deleting the token directory I can connect only once. 2nd try results in this error.

Also: The workaround described above does not seem to work for me

**Comment by fedejuret** [comment]
> Same error. After deleting the token directory I can connect only once. 2nd try results in this error.
> 
> Also: The workaround described above does not seem to work for me

Exactly, the same thing happens to me. If I delete the tokens folder it works the first time.

**Comment by RickGroenewegen** [comment]
Karein's workaround works for me

**Comment by gabriellemos197** [comment]
> Mesmo erro, mas para mim funciona depois de alterar o mesmo arquivo browser.js. Mas eu modifico `headless`para `true` Adicionar `args: ['--no-sandbox']`também funciona, mas apenas sem pasta de token
> 
> ![Captura de tela de 2023-07-04 13-23-17](https://user-images.githubusercontent.com/32269228/250954478-f3960b8c-9b8f-470c-a23b-6925a45043cd.png) #2362


This solution worked for me.
