### ISSUE TITLE
Error: Failed to launch the browser process! spawn

### ISSUE THREAD

**Issue by l3and49** [orkestral/venom#2374]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** ^5.0.11]
- **Node version:** [16.19.1]

![image](https://github.com/orkestral/venom/assets/126525698/adc029e3-c7f1-483d-b7e9-bbcba614d44b)

**Comment by EdesNogueira** [comment]
To com o mesmo problema aqui, conseguiu arrumar?

**Comment by l3and49** [comment]
Consegui nada, já nem sei mais o que tentar

**Comment by l3and49** [comment]
> To com o mesmo problema aqui, conseguiu arrumar?

Cara, consegui resolver de uma forma bruta. Eu copiei a pasta do projeto e coloquei no disco local, acessei o cmd como admin, acessei a pasta e iniciei, ai foi.
