### ISSUE TITLE
I can't use sendPttFromBase64 function

### ISSUE THREAD

**Issue by yurik44** [orkestral/venom#238]
The result came "undefined". Someone has any example of usage? I tried different ways while looking at the code.

https://github.com/orkestral/venom/blob/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/api/layers/sender.layer.ts#L317
https://github.com/orkestral/venom/blob/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/lib/wapi/functions/send-ptt.js#L66

**Comment by joaosouz4** [comment]
this function work fine, like this:
`await clien.sendPttFromBase64( '000000000000@c.us', BASE64, 'ptt');`

**Comment by bhavya32** [comment]
@yurik44 then try sendFile after coverting base64 to buffer.
