### ISSUE TITLE
Button message not displayed on Android

### ISSUE THREAD

**Issue by heptopcm** [orkestral/venom#2389]
Button message displayed only on a web view. then list messages not displayed on both web and Android.

**Comment by yuryalencar** [comment]
I have the same problem here.
In addition, this bug is only on Android devices. Buttons are shown on WhatsApp Web and iOS devices too.

**Comment by VictorVirgolino** [comment]
me too

**Comment by PwccaCode** [comment]
buttons were disabled a long time ago no? its not supported anymore due to meta restrictions

**Comment by heptopcm** [comment]
What's a solution? In feature possible or not. (Button, list messages displaying on android)

**Comment by isspublicidade** [comment]
Well, there are two possible solutions for now. First is to use the official whatsapp API. But it's expensive and you pay per message sent. Some companies, like Twillo and Manychat, offer this solution for small business.

Second is simply not to use buttons or lists. You can create a simple menu using numbers. And the message flow continues according to the user's answer. Like this:

''Type your answer:
1. Purchase
2. Support"

Hope it helps.

**Comment by SahilAggarwal2004** [comment]
> Buttons are outdated now. Only the official Whatsapp API can show buttons.

I am a Developer who is learning right now and don't have a verified business. Is there any way to access the official Whatsapp API without verified business?

**Comment by isspublicidade** [comment]
> > Buttons are outdated now. Only the official Whatsapp API can show buttons.
> 
> I am a Developer who is learning right now and don't have a verified business. Is there any way to access the official Whatsapp API without verified business?

You can search for Twillo and Manychat. Those are companies that allow you to use their API with automated whatsapp chat flows. But they are very expensive, I don't recomend for small business at all.

Just go for the solution that I suggested above. It will work for most small businesses.

**Comment by FaelN1** [comment]
Buttons and lists are deprecated.

**Comment by GugaAraujo** [comment]
So, what we can use

> Buttons and lists are deprecated.

The response was insufficient.
What is the alternative for sending buttons and lists?
