### ISSUE TITLE
Failed to launch the browser process! undefined

### ISSUE THREAD

**Issue by mathmartins2** [orkestral/venom#2398]
## Environment

- **Venom version(s):** [5.0.11]
- **Browser:** [chrome 115.0.5790.98]
- **OS:** [ubuntu 20.04]
- **Node version:** [node 18]

## Steps to Reproduce

1. try to create a new session

## Log Output

```
Path Google-Chrome:  /usr/bin/google-chrome-stable
Error: Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/math/dev/DeliveryHub/back/node_modules/.pnpm/@puppeteer+browsers@1.4.5_typescript@4.9.5/node_modules/@puppeteer/browsers/src/launch.ts:399:11)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

## Your Code

```
private async start() {
    this.client = await create({
      session: 'session',
      headless: 'new',
    });
  }
```

**Comment by vsantos1711** [comment]
Same problem here!

**Comment by BLRocha** [comment]
veja a issue [issue 2377](https://github.com/orkestral/venom/issues/2377)

@vsantos1711 @mathmartins2

**Comment by niron1** [comment]
erase the contents of 'tokens' directory before running

**Comment by Feeh03114** [comment]
Even deleting the tokens folder, it gives the same error

**Comment by niron1** [comment]
@Feeh03114 
there could be many reasons why puppeteer can't launch the browser.
for me it was the tokens.
I wish there was a better error code, but there isn't.
follow all checklist items in : https://pptr.dev/troubleshooting
