### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by dedenhendrap** [orkestral/venom#24]
i've tried to run on mac it 's works but when i tried run on windows, i found this

**Comment by wellcoj** [comment]
I guess that's cuz you're taking too long to scan the QRCode

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!
