### ISSUE TITLE
useChrome should not appear in docs

### ISSUE THREAD

**Issue by niron1** [orkestral/venom#2403]
the following file:  https://github.com/orkestral/venom/blob/master/docs/getting-started/creating-client.md

has "useChrome" as a configuration key example,
but this key was removed.

**Comment by jonalan7** [comment]
has been removed and replaced by the browserPathExecutable, now you will be able to direct the path of the browser you want to use!

**Comment by niron1** [comment]
I know that :)
the issue was meant to update the docs, so others won't spend the time I had to (no complaint intended)

**Comment by allanalcantara** [comment]
```
{
            headless: 'new', // Headless chrome
            useChrome: true, // If false will use Chromium instance
            browserWS: '',  // If u want to use browserWSEndpoint
            browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'], // Parameters to be added into the chrome browser instance
            addBrowserArgs: [''],  // Add broserArgs without overwriting the project's original
           
        }
```

**Comment by niron1** [comment]
why was it closed? the bug is still there...

**Comment by jonalan7** [comment]
> por que foi fechado? o bug ainda está lá...

I'm going to change the file, don't worry!
