### ISSUE TITLE
Venom-bot does not run in root on linux

### ISSUE THREAD

**Issue by Feeh03114** [orkestral/venom#2404]
## Description
It's not working when you run the script with venom-bot in root on linux, it shows an error.

- Venom version(s): 5.0.11
- Browser: Chromium 114.0.5735.198
- OS: Ubuntu 20.04.6 LTS
- Node version: 16

## Steps to Reproduce

1. try to create a new session

## Log Output

```
Error: Failed to launch the browser process! undefined
4|ChatBot  | [678527:678527:0721/103612.711285:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
4|ChatBot  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
4|ChatBot  |     at ChildProcess.onClose (/root/projetos/ChatBot/node_modules/@puppeteer/browsers/src/launch.ts:399:11)
4|ChatBot  |     at ChildProcess.emit (node:events:525:35)
4|ChatBot  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
4|ChatBot  | - Error no open browser....
4|ChatBot  | Erro Connect Error no open browser....
```

## Your Code

```
 const options = {
        headless: 'new',
        disableWelcome: true,
        browserArgs:[
                  '--user-agent',
                  '--no-sandbox', 
                  '--disable-setuid-sandbox'
        ]
 }
 create(`touch-wa-bot`, qr, status,options)
      .then((client) => start(client, companie))
      .catch(async (error) => {
        console.error('Erro Connect',error); 
      });
  }
```

**Comment by jonalan7** [comment]
Delete the token and try again!

**Comment by Feeh03114** [comment]
Even deleting the tokens folder, it gives the same error

**Comment by Feeh03114** [comment]
Follow what was passed in this issue, https://github.com/orkestral/venom/issues/2377

**Comment by BLRocha** [comment]
For me, this error already occurred with alpine chromium container, it only worked with the creation of a new user. another solution that worked for me was to install chrome.

**Comment by mrjoebudi** [comment]
just do it work well on ubuntu 22.04 CLI
**`venom.create({session: 'session-survey', puppeteerOptions: {args: ['--no-sandbox']}}).then((client) => start(client)).catch((erro) => {console.log(erro);});`**

**Comment by Feeh03114** [comment]
> apenas faça funcionar bem no ubuntu 22.04 CLI **`venom.create({session: 'session-survey', puppeteerOptions: {args: ['--no-sandbox']}}).then((client) => start(client)).catch((erro) => {console.log(erro);});`**

"args" does not exist in puppeteerOptions typing

**Comment by Feeh03114** [comment]
I managed to make it run by putting the na argument in the code, as shown in the image.

<img width="382" alt="image" src="https://github.com/orkestral/venom/assets/58147419/c9f39aca-4460-4a80-a9f1-3c2f317f9b14">

**Comment by rafaelcastan** [comment]
I fixed this by doing two steps:

1 - I have installed google-chrome-stable

I'm using fedora so I have run: dnf install google-chrome-stable

maybe you can get a Hint of how to install in your OS runing: google-chrome --version

2 - I have changed one line in node_modules/venom-bot/dist/controllers/browser.js

const singletonLockPath = path.join(process.cwd(), userDataDir, 'SingletonLock')

to

const singletonLockPath = path.join(userDataDir, 'SingletonLock')
