### ISSUE TITLE
Documentation url is broken

### ISSUE THREAD

**Issue by maico910** [orkestral/venom#2406]
## Description

Documentation from README is broken:

- https://orkestral.github.io/venom/index.html
- https://docs.orkestral.io/venom

## Steps to Reproduce

1. Open the url from README (https://orkestral.github.io/venom/index.html or https://docs.orkestral.io/venom)

**Comment by pedroota** [comment]
I'm having the same issue. Does someone have the updated documentaion link?

**Comment by TiagoAndreAlmeida** [comment]
link still broken, does anyone have the correct link ?

**Comment by Oladapodaniel** [comment]
this issue is giving me doubt as to if this project is still being maintained or it has been deprecated.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
