### ISSUE TITLE
5.0.12 -> google-chrome: command not found

### ISSUE THREAD

**Issue by RickGroenewegen** [orkestral/venom#2407]
## Description

5.0.11 is working (However it will only start once I clear out tokens directory). When I update to 5.0.12 I get the message:

```
You're up to date 🎉🎉🎉
Path Google-Chrome:  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Error: Command failed: google-chrome --version
/bin/sh: google-chrome: command not found

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'google-chrome --version'
}
✖ Error no open browser....
✓ Platform: darwin
```

## Environment

- **Venom version(s):** 5.0.12
- **Browser:** Chrome version 115.0.5790.102 (Official Build) (arm64)
- **OS:** Sonoma 14.0 beta
- **Node version:** Node 18

**Comment by jonalan7** [comment]
The way to check the version on mac is incorrect, I'll fix this problem!

**Comment by brainwares** [comment]
Version: 5.0.13 on Ubuntu 22.04, if token exists error: no open browser.
So everytime I run, need to delete the token folder then re-scan barcode
