### ISSUE TITLE
Version 5.0.12 -> 2 Errors: Error removing SingletonLock and google-chrome: not found

### ISSUE THREAD

**Issue by marciusbezerra** [orkestral/venom#2408]
## Description

After updating to 5.0.12 there were 2 errors that I have to fix temporarily here

1) it tries to see the version of google-chrome that does not exist on the machine and gives an error (on the machine I use /usr/bin/chromium-browser):

```bash
Error: Command failed: google-chrome --version
/bin/sh: 1: google-chrome: not found
```

**My fix - I created a symlink:**

```bash
sudo ln -s /usr/bin/chromium-browser /usr/local/bin/google-chrome
```

2) for some reason it tries to remove SingletonLock using a duplicate path (below an example path)

Error removing SingletonLock: [Error: ENOENT: no such file or directory, unlink '/home/myname/projects/venom-wp/home/myname/projects/venom-wp/tokens/my_session/SingletonLock']

**My fix - I put an try catch on venom-bot/dist/controllers/browser.js:**

```js
// ...
try {
    await removeStoredSingletonLock(options.puppeteerOptions);
} catch (error) {
    console.error(error);
}
return await puppeteer_extra_1.default.launch(launchOptions);
// ...
```

## Environment

- **Venom version(s):** 5.0.12
- **Browser:** Chromium-Browser 113
- **OS:** [Debian GNU/Linux 11 (bullseye), Windows 11]
- **Node version:** v19.9.0

**Comment by subburaja** [comment]
Delete these two files : SingletonLock and SingletonCookie under the folder named as your session name in tokens folder
