### ISSUE TITLE
New Function to check whether a Contact is Online

### ISSUE THREAD

**Issue by hi2vaisakh** [orkestral/venom#241]
I am using the `getChatIsOnline` api and working perfectly with recent chats. But if I check a number which is in my contact list but it's not in my recent chats as I didn't messaged the user or I archived the chat, then it's giving the response as `false` even though the user is online.
I am struggling to add that functionality. Can anybody please help me. Any help will be much appreciated.

**Comment by joaosouz4** [comment]
this is a bit complicated since on whatsapp web we don't see it.
but maybe it has some form since we communicate directly with the websocket

**Comment by hi2vaisakh** [comment]
Thank you @joaosouz4 for the quick response. Any chance, we can implement this functionality. We are using this framework in our support project as a bot service(we are a startup with 3 employees only ). I tried to understand the core logic behind this framework, but still missing at some places. It will great if we can implement this functionality and more helpful.

**Comment by joaosouz4** [comment]
I will try to implement this for we

**Comment by hi2vaisakh** [comment]
@joaosouz4 Can you please help to implement this functionality. Also if you can advice me on how we can do this, I will also try to add this functionality.Expecting your help. Thanks.

**Comment by joaosouz4** [comment]
I searched quickly, but I couldn't find a way to implement it for all contacts and not contacts. you need to understand about WAPI and how it works on whatsapp web.

**Comment by frankeu** [comment]
https://github.com/orkestral/venom/issues/205
