### ISSUE TITLE
Full documentation not found

### ISSUE THREAD

**Issue by JMcrafter26** [orkestral/venom#2410]
## Description

I get an 404 error when trying to open the full documentation 

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. Click on **full documentation** in the readme

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by PauloFavero** [comment]
I am also getting 404 while opening any venom documentation

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
