### ISSUE TITLE
Error getting Chromium browser version

### ISSUE THREAD

**Issue by Feeh03114** [orkestral/venom#2415]
## Description
Start an application on linux with the Chromium browser installed, but it was executing the command ``google-chrome --version`` and not chrome.

- Venom version: 5.0.13
- Browser: Chromium 115.0.5790.102
- OS: Ubuntu 22.04.1 LTS
- Node version: v18.12.1

## Steps to Reproduce
1.  try to create a new session

## Your Code

```
 const options = {
        headless: 'new',
        disableWelcome: true,
        browserArgs:[
                  '--user-agent',
                  '--no-sandbox', 
                  '--disable-setuid-sandbox'
        ]
 }
 create(`touch-wa-bot`, qr, status,options)
      .then((client) => start(client, companie))
      .catch(async (error) => {
        console.error('Erro Connect',error); 
      });
  }
```
### How to fix
 Em ``node_modules\venom-bot\dist\controllers\browser.js``
```
if ((platform === 'darwin' || platform === 'linux')) {
    chromeVersion = await getChromeVersionBash();
}
```
to
```
if ((platform === 'darwin' || platform === 'linux') && executablePath.includes('google-chrome')) {
    chromeVersion = await getChromeVersionBash();
}
```

**Comment by jonalan7** [comment]
At the moment, due to the Puppeteer update, I've only implemented checking the Google Chrome version! I'll be adding more checks for other browser versions soon

**Comment by Feeh03114** [comment]
I put it here in case it happens to anyone else has the solution already.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
