### ISSUE TITLE
Failed to launch the browser process! undefined

### ISSUE THREAD

**Issue by Feeh03114** [orkestral/venom#2416]
## Description
It's not working when you run the script with venom-bot in root on linux, it shows the following error: Failed to launch the browser process! undefined.

- Venom version: 5.0.13
- Browser: Chromium 115.0.5790.102
- OS: Ubuntu 22.04.1 LTS
- Node version: v18.12.1

## Steps to Reproduce

1. Try to create a new session

## Log Output
```
1|ChatBot  |  Error: Failed to launch the browser process! undefined
1|ChatBot  | mkdir: cannot create directory ‘/run/user/0’: Permission denied
1|ChatBot  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
1|ChatBot  |     at ChildProcess.onClose (/home/ubuntu/projetos/ChatBot/node_modules/@puppeteer/browsers/src/launch.ts:399:11)
1|ChatBot  |     at ChildProcess.emit (node:events:525:35)
1|ChatBot  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
1|ChatBot  | - Error no open browser....
1|ChatBot  | - Platform: linux
1|ChatBot  | - Chrome Version: Chrome/115.0.5790.102
1|ChatBot  | Erro Connect Error no open browser....
```

## Your Code

```
 const options = {
        headless: 'new',
        disableWelcome: true,
        browserArgs:[
                  '--user-agent',
                  '--no-sandbox', 
                  '--disable-setuid-sandbox'
        ]
 }
 create(`touch-wa-bot`, qr, status,options)
      .then((client) => start(client, companie))
      .catch(async (error) => {
        console.error('Erro Connect',error); 
      });
  }
```

**Comment by jonalan7** [comment]
it seems that you are not allowed to create or delete something inside the project, try giving permission in the main folder!

**Comment by Feeh03114** [comment]
still gave error, I gave permission for all project folders

**Comment by jonalan7** [comment]
try to make the following change:
`headless: 'new'`
for
`headless: true`

**Comment by Feeh03114** [comment]
it still gave an error, it's giving an error, but I don't know how to solve it await puppeteer_extra_1.default.launch(launchOptions);

**Comment by jonalan7** [comment]
send the print of the error!

**Comment by Feeh03114** [comment]
> mande o print do erro!

![image](https://github.com/orkestral/venom/assets/58147419/368e5ffe-75d2-4a03-91d5-fe158adc785a)

**Comment by Feeh03114** [comment]
I got a solution, I removed the ```options.browserArgs``` from ```launchOptions``` and only put the arguments ```['--no-sandbox', '--disable-setuid-sandbox']```, it was like this in the end:
```const launchOptions = {
             headless: options.headless,
             devtools: options.devtools,
             args: ['--no-sandbox', '--disable-setuid-sandbox'],
             ...options.puppeteerOptions,
             ...extras,
         };```
         
![image](https://github.com/orkestral/venom/assets/58147419/89d1367e-3006-4667-8de0-f2356557511a)

**Comment by jonalan7** [comment]
if you disabled the sandbox and it worked it might be related to the root user this problem!!
This error may be occurring because you are trying to run Puppeteer as root (user with administrative privileges).
Chrome does not support running as root without the --no-sandbox option as this could compromise system security.

Running as root without --no-sandbox is not supported. See [https://crbug.com/638180.](https://crbug.com/638180)

**Comment by jonalan7** [comment]
Overall, the problem was you replacing the main arguments of venom-bot. 
By default, they come linked to the arguments: `--no-sandbox` and `--disable-setuid-sandbox`, since users usually start the project as the root user (system administrator)!

see the main arguments included: [https://github.com/orkestral/venom/blob/master/src/config/puppeteer.config.ts](arguments)

**Comment by Feeh03114** [comment]
yes, there is some default argument that is preventing venom-bot from starting on linux in Chromium.

**Comment by jonalan7** [comment]
if you start the project that way does it work? or give some kind of error?

```
 const options = {
        headless: 'new',
        disableWelcome: true,
 }
 create(`touch-wa-bot`, qr, status,options)
      .then((client) => start(client, companie))
      .catch(async (error) => {
        console.error('Erro Connect',error); 
      });
  }
```
without the browserArgs!

**Comment by Feeh03114** [comment]
I did a test like this and it was. Thank you very much.

**Comment by Ygohel18** [comment]
could you please help a little bit more, 

async function startVenom() {
    let client = await venom
        .create({
            session: "default",
            catchQR: (base64Qr, asciiQR, attempts, urlCode) => {
                console.log(asciiQR); // Optional to log the QR in the terminal
                var r = {
                    qr: base64Qr,
                };
                sendWebhook(r, "qrcode");
            },
        })
        .then((client) => {
            start(client);
        })
        .catch((erro) => {
            console.log(erro);
        });

    return client;
}

what should I change here, I have same error in ubuntu

**Comment by Feeh03114** [comment]
I am not able to open multi sessions
