### ISSUE TITLE
Session folder is removed on close

### ISSUE THREAD

**Issue by evertonbatini** [orkestral/venom#2420]
It's only happening on a specific computer.

When closing the window, the session folder is deleted, as shown in the video.

I already did the test by doing the whole process of reading the QR code and login, but the same thing happens.

video link: https://youtu.be/AmKjBW-cgUg

**Comment by rodolfoguiari** [comment]
I have the same problem. Did you get any solution?

**Comment by evertonbatini** [comment]
> I have the same problem. Did you get any solution?

my solution was to use another library

**Comment by rodolfoguiari** [comment]
which library are you using?

**Comment by evertonbatini** [comment]
> which library are you using?

https://github.com/pedroslopez/whatsapp-web.js

**Comment by rodolfoguiari** [comment]
thanks
