### ISSUE TITLE
I got a scoped_ptrace_attach.cc error

### ISSUE THREAD

**Issue by hasanablak** [orkestral/venom#2424]
## Description

When i install and run venom bot script i got a this logs;

2023-07-29 00:55:37 You're up to date 🎉🎉🎉
2023-07-29 00:55:38 Path Google-Chrome:  /usr/bin/google-chrome-stable
2023-07-29 00:55:38 Error: Failed to launch the browser process!
2023-07-29 00:55:40 **[0728/215540.165944:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)**
2023-07-29 00:55:40 **Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)**
2023-07-29 00:55:40 
2023-07-29 00:55:40 
2023-07-29 00:55:40 TROUBLESHOOTING: https://pptr.dev/troubleshooting
2023-07-29 00:55:40 
2023-07-29 00:55:40     at ChildProcess.onClose (/var/www/html/node_whatsapp_bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
2023-07-29 00:55:40     at ChildProcess.emit (node:events:549:35)
2023-07-29 00:55:40     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2023-07-29 00:55:40 ✖ Error no open browser....
2023-07-29 00:55:40 ✓ Platform: linux
2023-07-29 00:55:40 ✓ Chrome Version: 115.0.5790.110
2023-07-29 00:55:40 Error no open browser....
2023-07-28T21:55:40.384327583Z 

## Environment

- **Venom version(s):** 5.0.13
- **Browser:** Google Chrome 115.0.5790.110 
- **OS:** Docker amd64/node:16.2 image | Debian GNU/Linux 11 | My Pc Is MacOs
- **Node version:** Node 16.2 (I tried Node 18 still doesnt work)

## Steps to Reproduce

1. Docker up from amd64/node:16.2
2. create an index.js file and paste demo script code;
`
// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
       session: 'session-name', //name of session
      headless: 'new',
      args: [ '--no-sandbox', '--disable-setuid-sandbox'],
     
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}`

**Comment by allanalcantara** [comment]
try

```
const venom = require("venom-bot");

venom
    .create(
        'sessionName',
        (base64Qrimg, asciiQR) => {
            console.log('Terminal qrcode: ', asciiQR);
            console.log('base64 image string qrcode: ', base64Qrimg);
        },
        (statusSession) => {
            console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled
        },
        {
            folderNameToken: 'tokens', //folder name when saving tokens
            headless: 'new', // Headless chrome
            useChrome: true, // If false will use Chromium instance
            logQR: true, // Logs QR automatically in terminal
            browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'], // Parameters to be added into the chrome browser instance
            updates: true, // Logs info updates automatically in terminal
        }
    )
    .then((client) => {
        start(client);
    })
    .catch((erro) => {
        console.log(erro);
    });

function start(client) {
client.onMessage((message) => {

        if (message.body === 'Hi' && message.isGroupMsg === false) {
            client.sendText(
                message.from,
                'Welcome to Venom🕷')
                .then((result) => {
                    console.log('result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('error when sending: ', erro); //return object error
                });
        }

    })
    
}
```

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
