### ISSUE TITLE
How can i send mesage with link

### ISSUE THREAD

**Issue by hasanablak** [orkestral/venom#2426]
Hello there, how can i send message has link something like in picture;

![image](https://github.com/orkestral/venom/assets/20007699/6a984133-72cd-4379-83db-f7ccdf681412)

When I use "sendLinkPreview" method, the method send message like in picture;
![image](https://github.com/orkestral/venom/assets/20007699/1e1c34a6-14b3-4e8d-a056-b5e9b30ba4d6)

You see that from the picture; 
First number mark properties is that 3. paramaters in the method
Second number mark properties is that 2. paramters in the method

Like this;
```

 .sendLinkPreview(
                `parameter one`, // send to
                `parameter two`, // link text
                `parameter three` // link 
            )
```

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
