### ISSUE TITLE
err_require_esm after last update.

### ISSUE THREAD

**Issue by junimheller** [orkestral/venom#2427]
hello fellas,
the same file was running before the new update.
after that  i got stuck in this error:

$$$$$$ node .\buttons.js
$$$$$$\node_modules\venom-bot\dist\controllers\welcome.js:9
const latest_version_1 = require("latest-version");
                                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module $$$$$$\node_modules\latest-version\index.js from $$$$$$\node_modules\venom-bot\dist\controllers\welcome.js not supported.
Instead change the require of index.js in $$$$$$ \node_modules\venom-bot\dist\controllers\welcome.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ($$$$$$ \venom-bot\dist\controllers\welcome.js:9:26)
    at Object.<anonymous> ($$$$$$ \venom-bot\dist\controllers\initializer.js:67:19)
    at Object.<anonymous> ($$$$$$ \venom-bot\dist\index.js:85:21)
    at Object.<anonymous> ($$$$$$ \venom-bot\buttons.js:3:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.5.0

I tried to change the require for import, but the index script is not being executed.
just run the welcome and nothing else.

the code was:

// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
    session: 'buttons' //name of session
  },
  //options
  {
    headless: 'false', // you should no longer use boolean false or true, now use false, true or 'new' learn more https://developer.chrome.com/articles/new-headless/
    multidevice: false,
  }
  
  )
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage( async (message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });

        const buttons = [
            {
              "buttonText": {
                "displayText": "Text of Button 1"
                }
              },
            {
              "buttonText": {
                "displayText": "Text of Button 2"
                }
              }
            ]
          await client.sendButtons(message.from, 'Title', buttons, 'Description')
            .then((result) => {
              console.log('Result: ', result); //return object success
            })
            .catch((erro) => {
              console.error('Error when sending: ', erro); //return object error
            });
    }
  });
}

**Comment by sergiozaninotti** [comment]
same error here... after update :(

**Comment by Gustavo-Diogo** [comment]
same error here after the update :(

**Comment by junimheller** [comment]
I have a Debian(bullseye) running the older version, 5.0.13, and my code is running without problems.
maybe if you reinstall with:
npm i --save venom-bot 5.0.13
should run okay.
I installed the new one to see the buttons were working :v:

**Comment by Jucinei** [comment]
Same error here

**Comment by sergiozaninotti** [comment]
i'm working with venom in docker container... i downgraded to 5.0.13 and used this configs and worked :smile: 

```
FROM node:18

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /usr/src/app

CMD ["node", "app.js" ]
```

**Comment by junimheller** [comment]
não consegui solucionar na versão nova, reinstalar com:
>npm i --save venom-bot@5.0.13
e as funções voltaram ao normal.

**Comment by flavionc** [comment]
Same here, using version 5.0.13 and 5.0.14. Has anyone discovered the solution?

**Comment by jonalan7** [comment]
npm i venom-bot@5.0.16
