### ISSUE TITLE
How to add a contact and how to create a tags

### ISSUE THREAD

**Issue by SyncLxZs** [orkestral/venom#2428]
How can I create tags for contacts as it exists in WA BUSSINESS and is there a way to add a contact?
How to create broadcast lists and send messages to them?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
