### ISSUE TITLE
QR Code não aparece para escanear e da erro de not logged

### ISSUE THREAD

**Issue by l3and49** [orkestral/venom#2429]
## Description

Quando coloco para rodar o bot ele fica carregando a introdução e o qrcode, porém nada aparece e acaba fechando a página

## Environment

- **Venom version(s):** [5.0.11]
- **Node version:** [16.19.1]

![image](https://github.com/orkestral/venom/assets/126525698/db0e915d-b4e6-4830-9127-57288a5ebdc4)

**Comment by chr0nu5** [comment]
@l3and49 tenta deletar a pasta "tokens" se ela existir e roda novamente :)

**Comment by ViniciusFH** [comment]
Mesmo problema aqui. Deletar a pasta "tokens" não adianta.

**Comment by jonalan7** [comment]
add option:
```
{ 
autoClose: false
}
```
[find out more](https://github.com/orkestral/venom#optional-create-parameters)

**Comment by ViniciusFH** [comment]
I've tried that (actually `autoClose: 0`), but it didn't help as well. And I don't think it's related to the auto close function, since its default value is 60 seconds, and the "QRCode Fail" error is throwing in about 30.

**Comment by l3and49** [comment]
> use a opção de pegar o qrcode. Eu tive o mesmo problema, o primeiro código qr que deveria ser mostrado não estava entrando no terminal.
> 
> ```
> //catchQR
> (asciiQR) => {
>   console.log('',asciiQR);
> },
> ```
> 
> apenas espere 30 segundos e a atualização do qrcode aparecerá.
> 
> esta foi a minha solução.

Onde você colocou esse código?

**Comment by junimheller** [comment]
mande seu código inteiro, pode ser alguma coisa no start client.

**Comment by l3and49** [comment]
const bot = require("venom-bot");
const { db } = require("../src/models/banco");
const { step } = require("../src/models/stages");

bot.create({ 
    session: 'sessionName',
    headless : 'new', 
}).then((client) => start(client))
.catch((error) => {
    console.error('Erro ao criar o cliente do bot:', error);
  });

**Comment by l3and49** [comment]
const bot = require("venom-bot");
const { db } = require("../src/models/banco");
const { step } = require("../src/models/stages");

bot.create({ 
    session: 'sessionName',
    headless : 'new', 
}).then((client) => start(client))
.catch((error) => {
    console.error('Erro ao criar o cliente do bot:', error);
  });

let m_varResp = null;

function start(client) {
    client.onMessage((message) => { //executa quando o cliente manda uma mensagem
         console.log(new Date() + " Interação do usuário.");
        if (message.isGroupMsg === false || message.isGroupMsg == undefined) { 
            m_varResp = step[getStage(message.from)].obj.execute(
                message.from,
                message.body,
            );
            if(m_varResp == "0") //resposta que retorna direto sem precisar de mensagem
            {
                m_varResp = step[getStage(message.from)].obj.execute(
                    message.from,
                    message.body,
                );
            }
            for (let m_varIndex = 0; m_varIndex < m_varResp.length; m_varIndex++) //imprime a mensagem do estado
            {
                const element = m_varResp[m_varIndex];
                console.log(" elemento: " + element)
                client.sendText(message.from, element);
            }
        }
    });
}

function getStage(user) {
    if (db[user]) {
        //Se existir esse numero no banco de dados
        return db[user].stage;
    } else {
        console.log("Acessando menu");
        //Se for a primeira vez que entra e contato
        db[user] = {
            stage: "menu_0",
        };
        return db[user].stage;
    }
}

**Comment by junimheller** [comment]
vc tentou colocar o "asciiQR" dentro do create e nao deu certo ?

**Comment by l3and49** [comment]
isso

**Comment by junimheller** [comment]
vc tem que mudar a forma de nomear, as opções adicionais mudam como vc define os atributos.
![Screenshot 2023-08-03 150414](https://github.com/orkestral/venom/assets/81993802/64a4308e-9798-4977-ac60-35196afd13bf)

**Comment by l3and49** [comment]
Bom, não consegui fazer desse jeito cara, mas eu dei npm update venom-bot 5.0.11 e ai ele rodou, mas obrigado pela atenção!
