### ISSUE TITLE
Detect new group participant

### ISSUE THREAD

**Issue by caugustoschiller** [orkestral/venom#243]
Hello, is there anyway to detect when a new participant is added or join to group by link? And leave too? And to detect a legend on an incomming media file? Ex: a picture or a video with something write above, on a group?

Thanks, nice work

**Comment by caugustoschiller** [comment]
Anybody?

**Comment by bhavya32** [comment]
@caugustoschiller Try these 2 events.
```
client.onParticipantsChanged("000000000000@c.us", (event) => {
  ...
});

// Listen when client has been added to a group
client.onAddedToGroup(chatEvent => {
  ...
});
```
I am not sure which one is correct

**Comment by caugustoschiller** [comment]
Ok, thanks i ll try!
