### ISSUE TITLE
Need help sending text to a group

### ISSUE THREAD

**Issue by douglasalves0** [orkestral/venom#2431]
At the venom readme on the **basic functions section** there is a text that says:

_"Here, chatId could be <phoneNumber>@c.us or <phoneNumber>-<groupId>@g.us"_

And what follows is a lot of examples on how to use some venom functions. I need to send a text message on a group but I'm not becoming very successfull at my first tries. I am trying to do something like this:

```js
venomClient.sendText(
    "558399683456-120363160675336687@g.us",
    "some-message-here"
);
```

But I receive and error message that says **wid error: invalid wid**.

What is my group id? Is it the number that I get when I call getAllChatsGroups() function?
```js
id: {
      server: 'g.us',
      user: '120363160675336687',
      _serialized: '120363160675336687@g.us'
}
```
And, what **phone number** should I put on the first the section of the chatId? My number? The bot number? Or what?

Thanks in advance.

**Comment by BLRocha** [comment]
try to put only the group and the example message

```js
venomClient.sendText(
    "120363160675336687@g.us",
    "some-message-here"
)
```

it is important that you are in the group
