### ISSUE TITLE
Link a device with phone number 

### ISSUE THREAD

**Issue by andresayac** [orkestral/venom#2432]
This library already has this functionality, I would like to know?

![image](https://github.com/orkestral/venom/assets/16548795/d58c6b0a-5a8d-48c1-9445-f4cad1260db7)

![image](https://github.com/orkestral/venom/assets/16548795/3367e00a-7632-421c-bb05-35b6651cf64b)

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
