### ISSUE TITLE
POll not working

### ISSUE THREAD

**Issue by andresayac** [orkestral/venom#2433]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [5.0.16]
- **Browser:** [Chrome/115.0.5790.171]
- **OS:** [Windows 11]
- **Node version:** [Node 18.16.0]

## Steps to Reproduce

1. Retry send Poll message

## Log Output

```
does not return error, empty console for this case
```

## Your Code

``` javascript
//send poll
    const poll = {
        name: 'Select an option',
        options: [
            {
                name: 'doc'
            },
            {
                name: 'gracias'
            },
            {
                name: 'discord'
            },
        ],
        selectableOptionsCount: 1
    }
    client.sendPollCreation(message.from, poll)

        .then((result) => {
            console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
        });
```

## Additional context / Screenshot

![image](https://github.com/orkestral/venom/assets/16548795/8e1f9701-de91-4df0-9248-3538ebd284f2)

**Comment by junimheller** [comment]
venom bot poll and buttons are deprecated for android. 
they only work at wpp web and iphone. :(

**Comment by junimheller** [comment]
not sure, i've been testing in my code, and lists, buttons and polls were not working in my android correctly.

as they're having the same problem, I suppose it is the same source.

**Comment by andresayac** [comment]
> not sure, i've been testing in my code, and lists, buttons and polls were not working in my android correctly.
> 
> as they're having the same problem, I suppose it is the same source.

I keep in mind that the buttons and lists are depreciated but the polls should not be since it is a function accessible from the web

**Comment by junimheller** [comment]
the polls are accessible through web as buttons are.

**Comment by andresayac** [comment]
maybe I'm not being clear, I'm talking about polls and not buttons, I understand that the buttons are depreciated and I understand it, it's more for sending polls

![image](https://github.com/orkestral/venom/assets/16548795/81e5b0e9-d86e-4266-93c5-536ae81d041c)


> the polls are accessible through web as buttons are.

**Comment by andresayac** [comment]
Example I have tried debug this is what happens
![image](https://github.com/orkestral/venom/assets/16548795/be257aeb-91b0-4c94-b3c3-29397cf85b50)

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
