### ISSUE TITLE
r.findImpl is not a function

### ISSUE THREAD

**Issue by yuryalencar** [orkestral/venom#2435]
## Description

I can't send any messages to anyone.

## Environment

- **Venom version(s):** 5.0.6, 5.0.13, 5.0.16 ...
- **Browser:** Chromium
- **OS:** MacOS
- **Node version:** v19.7.0

## Steps to Reproduce

1. Connect your bot
2. Send a simple text message

## Log Output

<img width="1417" alt="Screenshot 2023-08-09 at 18 58 55" src="https://github.com/orkestral/venom/assets/19940344/6d7180c0-f64e-4a30-a204-246e85e2d199">

**Comment by lukasportal** [comment]
same.. looks like `window.Store.Chat.find(...)` is broken

**Comment by willf5** [comment]
Same error

**Comment by ghayman** [comment]
I'm fairly sure that WhatsApp just did an update to their Web App which is why this might appear to be hard to reproduce

It failing in _ServerQuery but I have no idea where this code is located - maybe it will give someone else a clue...

```
            _serverQuery(e, t, n) {
                var r = this;
                return (0,
                i.default)((function*() {
                    let i;
                    i = e === I ? r._update(t, n) : e === A ? r.findImpl(t, n) : r.findQueryImpl(t);
                    const a = yield i;
                    if (r._staleCollection) {
                        const e = Array.isArray(a) ? a : [a];
                        (0,
                        o.default)(e).forEach((function(e) {
                            void 0 === e.stale && (e.stale = !1)
                        }
                        ))
                    }
                    let s;
                    if (s = (null == n ? void 0 : n.set) ? r.set(a) : r.add(a, {
                        merge: !0
                    }),
                    Array.isArray(a))
                        return s;
                    if (s[0])
                        return s[0];
                    throw new m.ModelCreateError("Unknown",a)
                }
                ))()
```

**Comment by lukasportal** [comment]
@ghayman yes thats exactly what happened from my findings. they released a new version around 6:30 PM UTC
Basically, this is under the `Store.Chat` module.
this class has some methods, mainly `find()` which is used to find a chat. If the chat is already in your chat list (you have a history with it), it will simply call `Chat.get()` and return just fine.
If it is a new conversation, it will try to query its server by first calling `Store.Chat._query()` which will then call `Store.Chat._queryServer()` which will then try to call `Store.Chat.findImpl()`, but the problem is that `findImpl()` does not exist! No idea how they can deploy a build that doesn't build lol



or maybe they are now using another method to start a new chat and send messages that does not use `Store.Chat.find()`, which is what we have to figure out: how to get a Chat instance and send a message if there's no conversation with that person yet

**Comment by matbks** [comment]
![image](https://github.com/orkestral/venom/assets/44726485/a8b08813-4054-4aa4-b150-dc497ebd4f55)
https://chat.openai.com/share/44d65e22-0403-40aa-a028-18bf2b8ffe98

**Comment by Srreven** [comment]
Same problemn here, any solutions ?

**Comment by onitorrinco** [comment]
Same problemn here, any solutions ?

**Comment by benoli** [comment]
Same issue

**Comment by anbuthane** [comment]
Whatsapp-web.js a similar wrapper has this issue solved.

https://github.com/pedroslopez/whatsapp-web.js/pull/2390/files

May be we should look there to fix this.

**Comment by onitorrinco** [comment]
> Whatsapp-web.js a similar wrapper has this issue solved.
> 
> https://github.com/pedroslopez/whatsapp-web.js/pull/2390/files
> 
> May be we should look there to fix this.

npm i github:alechkos/whatsapp-web.js#fix-findImpl
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred

I was not able to download the fix. can you help me please?

**Comment by yuryalencar** [comment]
@onitorrinco you can try to install stable version 1.22.1. The fix is already in that version

**Comment by onitorrinco** [comment]
> @onitorrinco you can try to install stable version 1.22.1. The fix is already in that version

I'm using the "venom-bot": "^5.0.16"

I don't know how to update that package you mentioned

**Comment by yuryalencar** [comment]
The fix mentioned in this issue is of another WhatsApp lib. If u want to use do you need to install the correct lib

**Comment by Srreven** [comment]
> The fix mentioned in this issue is of another WhatsApp lib. If u want to use do you need to install the correct lib

Yes.. the link is about another package.. in that lib they force the use of Whatsapp Web version after the update


Anyone knows if this is possible here with venom-bot ?


This is the new file with the r.findImpl bug
https://web.whatsapp.com/app.9bf7959578bdb7663582.js
And this is the version that works fine:
 https://web.whatsapp.com/app.5c64dea375f2072d23cc.js
 
 in this other lib.. they force a page with app.5c64dea375f2072d23cc.js

**Comment by mauricioabreeu** [comment]
Has anyone found a solution here yet with an error in the find() function?

My code:
Store.Chat.find(chatId);

My error:
Uncaught (in promise) TypeError: r.findImpl is not a function

**Comment by lukasportal** [comment]
here's my temporary solution until we find a better one
it's still under testing, but hoping to work
its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`

```
if (!window.Store.Chat.findTemp) {
    window.Store.Chat.findTemp = window.Store.Chat.find;
}
window.Store.Chat.find = async function (id) {
    try {
        return await window.Store.Chat.findTemp(id);
    }
    catch (err) {
        if (err && err.message && err.message.includes('findImpl')) {
            var tempChat = new window.Store.Chat.modelClass({ id });
            window.Store.Chat.add(tempChat);
            return await window.Store.Chat.findTemp(id);
        }
        throw err;
    }
};
```

**Comment by onitorrinco** [comment]
> here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> 
> ```
> if (!window.Store.Chat.findTemp) {
>     window.Store.Chat.findTemp = window.Store.Chat.find;
> }
> window.Store.Chat.find = async function (id) {
>     try {
>         return await window.Store.Chat.findTemp(id);
>     }
>     catch (err) {
>         if (err && err.message && err.message.includes('findImpl')) {
>             var tempChat = new window.Store.Chat.modelClass({ id });
>             window.Store.Chat.add(tempChat);
>             return await window.Store.Chat.findTemp(id);
>         }
>         throw err;
>     }
> };
> ```

in which file did you make this change?

**Comment by Srreven** [comment]
> 

I tried with headless false and manually add this code on Console... and It works..

Someone knows how inject this code automatically ?

**Comment by mauricioabreeu** [comment]
> here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> 
> ```
> if (!window.Store.Chat.findTemp) {
>     window.Store.Chat.findTemp = window.Store.Chat.find;
> }
> window.Store.Chat.find = async function (id) {
>     try {
>         return await window.Store.Chat.findTemp(id);
>     }
>     catch (err) {
>         if (err && err.message && err.message.includes('findImpl')) {
>             var tempChat = new window.Store.Chat.modelClass({ id });
>             window.Store.Chat.add(tempChat);
>             return await window.Store.Chat.findTemp(id);
>         }
>         throw err;
>     }
> };
> ```

Thank you very much, it worked perfectly

**Comment by Davson-Siva** [comment]
> > > here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> > > ```
> > > if (!window.Store.Chat.findTemp) {
> > >     window.Store.Chat.findTemp = window.Store.Chat.find;
> > > }
> > > window.Store.Chat.find = async function (id) {
> > >     try {
> > >         return await window.Store.Chat.findTemp(id);
> > >     }
> > >     catch (err) {
> > >         if (err && err.message && err.message.includes('findImpl')) {
> > >             var tempChat = new window.Store.Chat.modelClass({ id });
> > >             window.Store.Chat.add(tempChat);
> > >             return await window.Store.Chat.findTemp(id);
> > >         }
> > >         throw err;
> > >     }
> > > };
> > > ```
> > 
> > 
> > in which file did you make this change?
> 
> I use this code snippet to inject the code on Browser... in this case I have just one tab in browser... inside venom.create().then( async (client) => [...])
> 
> ```
> let pages = await client.browser.pages()
>       pages[0].addScriptTag({
>         content: `
>         if (!window.Store.Chat.findTemp) {
>         window.Store.Chat.findTemp = window.Store.Chat.find;
>         }
>         window.Store.Chat.find = async function (id) {
>             try {
>                 return await window.Store.Chat.findTemp(id);
>             }
>             catch (err) {
>                 if (err && err.message && err.message.includes('findImpl')) {
>                     var tempChat = new window.Store.Chat.modelClass({ id });
>                     window.Store.Chat.add(tempChat);
>                     return await window.Store.Chat.findTemp(id);
>                 }
>                 throw err;
>             }
>         };`})
> ```

I use the venom-bot lib, but I don't have much knowledge in the structure of the project. Could someone show me an example in which file should I put this code snippet, pls?

**Comment by onitorrinco** [comment]
> > > > here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> > > > ```
> > > > if (!window.Store.Chat.findTemp) {
> > > >     window.Store.Chat.findTemp = window.Store.Chat.find;
> > > > }
> > > > window.Store.Chat.find = async function (id) {
> > > >     try {
> > > >         return await window.Store.Chat.findTemp(id);
> > > >     }
> > > >     catch (err) {
> > > >         if (err && err.message && err.message.includes('findImpl')) {
> > > >             var tempChat = new window.Store.Chat.modelClass({ id });
> > > >             window.Store.Chat.add(tempChat);
> > > >             return await window.Store.Chat.findTemp(id);
> > > >         }
> > > >         throw err;
> > > >     }
> > > > };
> > > > ```
> > > 
> > > 
> > > in which file did you make this change?
> > 
> > 
> > I use this code snippet to inject the code on Browser... in this case I have just one tab in browser... inside venom.create().then( async (client) => [...])
> > ```
> > let pages = await client.browser.pages()
> >       pages[0].addScriptTag({
> >         content: `
> >         if (!window.Store.Chat.findTemp) {
> >         window.Store.Chat.findTemp = window.Store.Chat.find;
> >         }
> >         window.Store.Chat.find = async function (id) {
> >             try {
> >                 return await window.Store.Chat.findTemp(id);
> >             }
> >             catch (err) {
> >                 if (err && err.message && err.message.includes('findImpl')) {
> >                     var tempChat = new window.Store.Chat.modelClass({ id });
> >                     window.Store.Chat.add(tempChat);
> >                     return await window.Store.Chat.findTemp(id);
> >                 }
> >                 throw err;
> >             }
> >         };`})
> > ```
> 
> I use the venom-bot lib, but I don't have much knowledge in the structure of the project. Could someone show me an example in which file should I put this code snippet, pls?


mine worked like this

Venom
    .create('API',
        // ... (restante do seu código de inicialização)
    )
    .then(async (venomClient) => {
        console.log('WhatsAPP  API... iniciando.....');
        client = venomClient; // Atribui o venomClient para a variável client

        // Injetando o script no navegador
        let pages = await client.browser.pages();
        pages[0].addScriptTag({
            content: 
            if (!window.Store.Chat.findTemp) {
                window.Store.Chat.findTemp = window.Store.Chat.find;
            }
            window.Store.Chat.find = async function (id) {
                try {
                    return await window.Store.Chat.findTemp(id);
                }
                catch (err) {
                    if (err && err.message && err.message.includes('findImpl')) {
                        var tempChat = new window.Store.Chat.modelClass({ id });
                        window.Store.Chat.add(tempChat);
                        return await window.Store.Chat.findTemp(id);
                    }
                    throw err;
                }
            };
        });

        start(venomClient);
        console.log('WhatsAPP API iniciado com sucesso.');
    })
    .catch((error) => {
        console.log('Erro ao iniciar o WhatsAPP API:', error);
    });

**Comment by Srreven** [comment]
> > > > here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> > > > ```
> > > > if (!window.Store.Chat.findTemp) {
> > > >     window.Store.Chat.findTemp = window.Store.Chat.find;
> > > > }
> > > > window.Store.Chat.find = async function (id) {
> > > >     try {
> > > >         return await window.Store.Chat.findTemp(id);
> > > >     }
> > > >     catch (err) {
> > > >         if (err && err.message && err.message.includes('findImpl')) {
> > > >             var tempChat = new window.Store.Chat.modelClass({ id });
> > > >             window.Store.Chat.add(tempChat);
> > > >             return await window.Store.Chat.findTemp(id);
> > > >         }
> > > >         throw err;
> > > >     }
> > > > };
> > > > ```
> > > 
> > > 
> > > in which file did you make this change?
> > 
> > 
> > I use this code snippet to inject the code on Browser... in this case I have just one tab in browser... inside venom.create().then( async (client) => [...])
> > ```
> > let pages = await client.browser.pages()
> >       pages[0].addScriptTag({
> >         content: `
> >         if (!window.Store.Chat.findTemp) {
> >         window.Store.Chat.findTemp = window.Store.Chat.find;
> >         }
> >         window.Store.Chat.find = async function (id) {
> >             try {
> >                 return await window.Store.Chat.findTemp(id);
> >             }
> >             catch (err) {
> >                 if (err && err.message && err.message.includes('findImpl')) {
> >                     var tempChat = new window.Store.Chat.modelClass({ id });
> >                     window.Store.Chat.add(tempChat);
> >                     return await window.Store.Chat.findTemp(id);
> >                 }
> >                 throw err;
> >             }
> >         };`})
> > ```
> 
> I use the venom-bot lib, but I don't have much knowledge in the structure of the project. Could someone show me an example in which file should I put this code snippet, pls?


That's how I did it

```
 venom.create({
    session: 'YOUR_SESSION_NAME',
    headless: true,
    autoClose: 0,
  })
    .then(async (client) => {
    let pages = await client.browser.pages()
      pages[0].addScriptTag({
        content: `
        if (!window.Store.Chat.findTemp) {
        window.Store.Chat.findTemp = window.Store.Chat.find;
        }
        window.Store.Chat.find = async function (id) {
            try {
                return await window.Store.Chat.findTemp(id);
            }
            catch (err) {
                if (err && err.message && err.message.includes('findImpl')) {
                    var tempChat = new window.Store.Chat.modelClass({ id });
                    window.Store.Chat.add(tempChat);
                    return await window.Store.Chat.findTemp(id);
                }
                throw err;
            }
        };`})
        
        client.sendMessage()
        
        client.onMessage(() =>)
    })
```


If you can.. paste your venom.create snippet and I help you out

**Comment by yuryalencar** [comment]
The solution of @Srreven  is to run your venom bot, then select the first page of the venom client, and inject the script into the browser. U don't need to change the venom library only your code.

I'm trying it now

**Comment by Srreven** [comment]
> 

Yes, thanks you for the explanation

**Comment by yuryalencar** [comment]
It works here 🎉🎉🎉🎉🎉🎉🎉

**Comment by Srreven** [comment]
> here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call `findImpl`
> 
> ```
> if (!window.Store.Chat.findTemp) {
>     window.Store.Chat.findTemp = window.Store.Chat.find;
> }
> window.Store.Chat.find = async function (id) {
>     try {
>         return await window.Store.Chat.findTemp(id);
>     }
>     catch (err) {
>         if (err && err.message && err.message.includes('findImpl')) {
>             var tempChat = new window.Store.Chat.modelClass({ id });
>             window.Store.Chat.add(tempChat);
>             return await window.Store.Chat.findTemp(id);
>         }
>         throw err;
>     }
> };
> ```

Thanks for the workaround solution!!

**Comment by yuryalencar** [comment]
@Srreven I tried with 5.0.16 and works too

**Comment by yuryalencar** [comment]
Thank u @lukasportal 💪🏻🚀

**Comment by jonalan7** [comment]
I have a solution ready and will be uploading it shortly!

**Comment by fernandopraise** [comment]
recebi aqui o codigo completo...

venom.create({
    session: 'YOUR_SESSION_NAME',
    headless: true,
    autoClose: 0,
  })
    .then(async (client) => {
    let pages = await client.browser.pages()
      pages[0].addScriptTag({
        content: 
        if (!window.Store.Chat.findTemp) {
        window.Store.Chat.findTemp = window.Store.Chat.find;
        }
        window.Store.Chat.find = async function (id) {
            try {
                return await window.Store.Chat.findTemp(id);
            }
            catch (err) {
                if (err && err.message && err.message.includes('findImpl')) {
                    var tempChat = new window.Store.Chat.modelClass({ id });
                    window.Store.Chat.add(tempChat);
                    return await window.Store.Chat.findTemp(id);
                }
                throw err;
            }
        };})

        client.sendMessage()

        client.onMessage(() =>)
    })

**Comment by cotacompras** [comment]
Onde esta a solucao pf?

**Comment by alexandrejferreira** [comment]
venom.create({
    session: 'YOUR_SESSION_NAME',
    headless: true,
    autoClose: 0,
  })
    .then(async (client) => {
    let pages = await client.browser.pages()
      pages[0].addScriptTag({
        content: 
        if (!window.Store.Chat.findTemp) {
        window.Store.Chat.findTemp = window.Store.Chat.find;
        }
        window.Store.Chat.find = async function (id) {
            try {
                return await window.Store.Chat.findTemp(id);
            }
            catch (err) {
                if (err && err.message && err.message.includes('findImpl')) {
                    var tempChat = new window.Store.Chat.modelClass({ id });
                    window.Store.Chat.add(tempChat);
                    return await window.Store.Chat.findTemp(id);
                }
                throw err;
            }
        };})

        client.sendMessage()

        client.onMessage(() =>)
    })

**Comment by jonalan7** [comment]
This issue has been fixed!
