### ISSUE TITLE
Não retorna QrCode, erro retornado: qrReadFail

### ISSUE THREAD

**Issue by brnyza** [orkestral/venom#2436]
Já tentei apagar a pasta tokens, usar a versão 5.0.13 e a mais recente 5.0.16.
No Windows ele funciona, mas rodando no ubuntu, ele não está mais retornando o QrCode.
retornando o status: "qrReadFail"

Ele fica alguns segundos em "Waiting for QRCode Scan ..."
Depois ele manda os status:
"not Logged"
"qrReadFail"
"autocloseCalled"
"waitForLogin"
"Page Closed"

Mesmo modificando o parâmetro autoClose, com alguma dessas opções:
- autoClose: 0
- autoClose: false
- autoClose: 60 * 60 * 24 * 365

**Comment by jhonatanvago** [comment]
same error here!

![image](https://github.com/orkestral/venom/assets/48833856/5df4dc12-e47c-48f9-98ba-bc3fce9e59ab)

**Comment by jonalan7** [comment]
This issue has been fixed in the latest version. Please update!

**Comment by juniorerivaldo** [comment]
Ola fiz atualização para a versão 5.0.21 e estou utilizando autoClose:false porem depois do attempt 6 o venom esta encerrando e me retornando  QRCode Fail. podem me ajudar.
