### ISSUE TITLE
Not Loggedfor introduction

### ISSUE THREAD

**Issue by AGNconsultoria** [orkestral/venom#2438]
![erro venom-bot](https://github.com/orkestral/venom/assets/121176766/fecb661e-947e-4b11-904b-c3426a411702)

**Comment by felipebremgar** [comment]
Same issue here

**Comment by junimheller** [comment]
my old project works fine, but somehow I cant create new ones. it brings the typeError: cannot read properties of undefined (reading 'erro').

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
