### ISSUE TITLE
Error no open browser....

### ISSUE THREAD

**Issue by BhagavatiAntala** [orkestral/venom#2439]
![image](https://github.com/orkestral/venom/assets/98010597/96a7ac97-78ec-40c8-93de-5f7587610787)

**Comment by BhagavatiAntala** [comment]
After login device get logged out autometically

**Comment by sandrocampos** [comment]
I'm having the same error on linux and mac os:

![image](https://github.com/orkestral/venom/assets/2911866/802e88e3-8af9-42ac-9f03-e5f5540aef67)

**Comment by pedrogiroldo** [comment]
same

**Comment by karein** [comment]
Same error,
it works on Windows but on Linux does not work with a non-empty tokens
(also, on Linux only works if I modify a node_modules function)
(tried a lot of versions)

**Comment by CarlosAurelioMRF** [comment]
I've found a fix for this, the bug is because of the file `SingletonLock` in tokens folder. So you have to remove this before start your project.

In browser.ts exists a validation to remote this but SingletonLock is a link and it isn't removed.

Original code:
![image](https://github.com/orkestral/venom/assets/28075600/bb693d4d-b0b0-476a-81c9-f3c33087db40)

Remove the if of `fs.existsSync`:
![image](https://github.com/orkestral/venom/assets/28075600/589abbe0-4681-4d3c-9539-3e90c74c387f)

After this change it's working as expected for me. I just went to browser.js in `node_modules/venom-bot/dist/controllers/browser.js` and change the method.

**Comment by CarlosAurelioMRF** [comment]
@jonalan7 I've tried to create a branch for a new PR this but I dont have access.

**Comment by dardanbujupaj** [comment]
@CarlosAurelioMRF good catch with the SingletonLock!

However, this will fail if there is no SingletonLock file (e.g. when you delete the token folder).

I'd suggest checking the error code (`ENOENT` means there was no file, which can be ignored in this case).

Something like this (also removed the error log, as this isn't really an error):

```javascript
function removeStoredSingletonLock(
  puppeteerOptions: PuppeteerLaunchOptions
): Promise<boolean> {
  return new Promise((resolve, reject) => {
    try {
      const platform = os.platform();
      const { userDataDir } = puppeteerOptions;
      const singletonLockPath = path.join(userDataDir, 'SingletonLock');

      if (platform === 'win32') {
        // No need to remove the lock on Windows, so resolve with true directly.
        resolve(true);
      } else {
        fs.unlink(singletonLockPath, (error) => {
          if (error && error.code !== 'ENOENT') {
            console.error('Error removing SingletonLock:', error);
            reject(false);
          } else {
            resolve(true);
          }
        });
      }
    } catch {
      resolve(true);
    }
  });
}
```


As for the PR - you need to fork this repository, make the changes on a branch on your repo, then create a PR from there pointing to the upstream (original venom repository).

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by luchor23** [comment]
hello friends to solve the problem, delete the SingletoLock file manually in the tokens folder within the session name and also uninstall google chrome, just leave it running with Chromium the browser I figure SNAP.  And that's how it works for me in Ubuntu 22.04.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
