### ISSUE TITLE
Is there an example to send images with "HTTP protocol"?

### ISSUE THREAD

**Issue by brnyza** [orkestral/venom#244]
// Send image (you can also upload an image using a valid HTTP protocol)
"client.sendImage"

Could you help me please?

**Comment by GodCode** [comment]
Just add the link of image example : 

```
client
  .sendImage(
    '000000000000@c.us',
    'https://file-examples-com.github.io/uploads/2017/10/file_example_JPG_100kB.jpg',
    'image-name',
    'Caption text'
)
```

**Comment by brnyza** [comment]
> Just add the link of image example :
> 
> ```
> client
>   .sendImage(
>     '000000000000@c.us',
>     'https://file-examples-com.github.io/uploads/2017/10/file_example_JPG_100kB.jpg',
>     'image-name',
>     'Caption text'
> )
> ```
