### ISSUE TITLE
Error no open browser - Raspberry (arm64)

### ISSUE THREAD

**Issue by jackson-uti** [orkestral/venom#2441]
## Description

I have venom 5.0.1 working perfectly on my Raspberry (arm64) with Ubuntu 22.04.2 LTS but when I upgrade to a higher version I get the "Error in the open browser"

## Environment

- Venom version: 5.0.1 (ok) 5.0.6 (erro) 5.0.17 (erro)
- Browser: Chromium 115.0.5790.170 snap
- OS: Ubuntu 22.04.2 - Raspberry (arm64)
- Node version: 16.15.1

## Steps to Reproduce

With version 5.0.1 it is working perfectly. But if I try to upgrade to any higher version I get the error below

![image](https://github.com/orkestral/venom/assets/83785088/5767cf95-50a6-4b41-8cbd-fcb4d5272578)

When I enter the mentioned link I have the following.

![image](https://github.com/orkestral/venom/assets/83785088/34203e5e-b4b5-482e-a217-2380379937b8)

I understand that puppeteer no longer supports arm64. Is there a solution for this?

Thank you very much for your good work

**Comment by pedrogiroldo** [comment]
same here

**Comment by creakuno** [comment]
same here, work perfectly after updating Venom, ...control + c and try to run with pm2, then failed with the same error as above

**Comment by CarlosAurelioMRF** [comment]
Check this solution https://github.com/orkestral/venom/issues/2439#issuecomment-1683929856

**Comment by creakuno** [comment]
> Check this solution [#2439 (comment)](https://github.com/orkestral/venom/issues/2439#issuecomment-1683929856)

Thank you! it works!

**Comment by jackson-uti** [comment]
After debugging the code for a few hours I found the problem. 
The routine in node/node_modules/venom-bot/dist/controllers/initializer.js
It only happens if you put a name for the session, which is my case.

![image](https://github.com/orkestral/venom/assets/83785088/011c619f-e967-4732-ae7d-bd8052a9859c)

The options variable was being replaced by the session name that way the arguments passed in create were cleared. Changed to include session name and problem solved.

![image](https://github.com/orkestral/venom/assets/83785088/ab9e9b4b-4de4-41e5-99f4-59fbaabf418d)

Now with venom 5.0.17 working fine on raspberry.
Thanks again to venom development for the great job.

**Comment by luchor23** [comment]
hello friends to solve the problem, delete the SingletoLock file manually in the tokens folder within the session name and also uninstall google chrome, just leave it running with Chromium the browser I figure SNAP. And that's how it works for me in Ubuntu 22.04.

**Comment by pedrogiroldo** [comment]
@luchor23 the venom will save the whatsapp credentials?

**Comment by creakuno** [comment]
Running 'node Script.js' with 'headless' set to 'old' in the new release runs smoothly, but if I quit with Ctrl+C and then run it with 'pm2 start .....', it seems like Venom needs to rescan the QR code, is the session not saved ?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
