### ISSUE TITLE
 "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."

### ISSUE THREAD

**Issue by devandcom** [orkestral/venom#2443]
## Description

After a lot of messages sent ( for example 50 in two days of use )
I receive this error on sending message text
I need to restart Node, I lose authentication and I need to reconnect WhatsApp.

## Environment

- Venom version(s): latest
- Browser: Chrome 116
- OS:Linux
- Node version: 16

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
