### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Militao36** [orkestral/venom#2446]
I'm considering using the paid plan of Venom, but for multiple phone numbers. Is this possible? The website lacks a comprehensive description of the limitations.

**Comment by lorangel37** [comment]
![image](https://github.com/orkestral/venom/assets/56090130/904bea00-1658-4740-9f6a-56b8bb31cc94)

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
