### ISSUE TITLE
-> Error no open browser - Fix

### ISSUE THREAD

**Issue by Carloslml** [orkestral/venom#2447]
Try add in the route 
venom-bot/dist/config/puppeteer.config.js
add '--headless=old'
Doc: https://developer.chrome.com/articles/new-headless/
I tried in linux and it works

**Comment by jonalan7** [comment]
I'm going to establish a routine to incorporate this argument!

**Comment by jonalan7** [comment]
Download the latest version and try setting `headless: 'old'`
```
venom.create({
  session: 'sessionname',
  headless: 'old',
}).then((client)=> {
  start(client);
});
```

**Comment by pedrogiroldo** [comment]
but how can i save the credentials?

**Comment by thiagomarinheiro89** [comment]
Boa Noite,

Estou começando a utilizar essa biblioteca e estou enfrentando uma dificuldade, utilizei o código que informaram, porém estou com o seguinte erro:

![image](https://github.com/orkestral/venom/assets/48741949/40a48eed-0040-4d15-b7d9-e82c04f05cc8)

quando tento ler o qr code com o celular recebo a infomação de **Não foi possível conectar o aparelho** poderiam me auxiliar?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
