### ISSUE TITLE
How can I use it in Nextjs?

### ISSUE THREAD

**Issue by vitoropereira** [orkestral/venom#2452]
Can I use Venom with Nextjs? If yes, how to start?

**Comment by BLRocha** [comment]
There are several ways to manipulate instances, one way is to create a backend that handles venom and communicates with Rest API Websocket

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
