### ISSUE TITLE
See qr code when used in conjunction with pm2

### ISSUE THREAD

**Issue by pedrogiroldo** [orkestral/venom#2453]
I need help, I would like to know how to access the qr code when I start through pm2

**Comment by Gauravism2017** [comment]
You can save it in local/S3 whenever QR code is available.

**Comment by lorangel37** [comment]
you can pass the parameter on creation

private initialize(){
        const qr = (base64Qr: string) => {
            this.qr = base64Qr
        }
        const start = (client: Whatsapp) => {
            this.client = client
            client.onStateChange((state) => {
                this.connected = state
            })
        }

        create('mensagem',qr)
            .then((client) => start(client))
            .catch((error) => console.error(error))
    }
    
    then you have a base64 to show in some view html.

**Comment by riberman** [comment]
If your QR code is printed in console terminal:  
List pm2 services running:  
`pm2 list`  
If you need , add name to pm2 service running using:  
`pm2 restart idServiceVenonRunning --name newName`  
Acess the log of this service:  
`pm2 logs newName`

**Comment by pedrogiroldo** [comment]
thank you everyone
