### ISSUE TITLE
Error message returned when send file

### ISSUE THREAD

**Issue by lorangel37** [orkestral/venom#2454]
Even the message is sended this error message is returned :

error {
  me: {
    id: {
      server: 'c.us',
      user: '',
      _serialized: '@c.us'
    },
    displayName: null,
    verifiedName: 'a',
    searchName: null,
    pushname: null,
    notifyName: null,
    isBusiness: true,
    formattedUser: null,
    tag: '1728169099',
    stale: false,
    eurlStale: false,
    timestamp: 1692908519976,
    hostRetryCount: 0,
    description: null,
    categories: [ [Object] ],
    profileOptions: { commerceExperience: 'none', cartEnabled: true },
    email: null,
    website: [],
    businessHours: null,
    address: null,
    fbPage: {},
    igProfessional: {},
    isProfileLinked: false,
    coverPhoto: null
  },
  to: {
    fromMe: true,
    remote: {
      server: 'c.us',
      user: '',
      _serialized: '@c.us'
    },
    id: 'EGB7ASNLRHELKEFD',
    serialized: 'true@c.us_EGB7ASNLRHELKEFD'
  },
  erro: true,
  text: null,
  status: { messageSendResult: 'OK', t: 1692908533, count: null }
} 

**i've already tried to update version of venom btw**

**Comment by junimheller** [comment]
good afternoon, i'm having the same error plus, my async commands are getting out of order, not respecting the async.

**Comment by riberman** [comment]
Same error in my project. In my code this error resulted in the same file message being sent repeatedly in the WP chat.
To resolve I needed to add try catch when calling client.sendFile
in client.sendImage the same problem.

**Comment by junimheller** [comment]
> Same error in my project. In my code this error resulted in the same file message being sent repeatedly in the WP chat. To resolve I needed to add try catch when calling client.sendFile in client.sendImage the same problem.

it worked ?
can you show a snippet of this code?

**Comment by emartirios** [comment]
temporary solution...
go to file:
node_modules/venom-bot/dist/api/layers/sender.layer.js

find function, ex: SendFile, SendFileFromBase64

change line:

if (result['erro'] == true) {

if (result['erro'] == true && result['text'] != null) {

**Comment by junimheller** [comment]
It worked. Nice catch. tyvm.

**Comment by bernardogazola** [comment]
@junimheller troque em todas as functions do sender.layer.js que você está usando. Por ex.: quero enviar uma imagem, tenho que ir no sender.layer.js, procurar a função do sendImage e alterar a linha da solução temporária ( if (result['erro'] == true) para
if (result['erro'] == true && result['text'] != null) ).

**Comment by junimheller** [comment]
> @junimheller troque em todas as functions do sender.layer.js que você está usando. Por ex.: quero enviar uma imagem, tenho que ir no sender.layer.js, procurar a função do sendImage e alterar a linha da solução temporária ( if (result['erro'] == true) para if (result['erro'] == true && result['text'] != null) ).

ja troquei e ainda nao funciona.

**Comment by bernardogazola** [comment]
> > @junimheller troque em todas as functions do sender.layer.js que você está usando. Por ex.: quero enviar uma imagem, tenho que ir no sender.layer.js, procurar a função do sendImage e alterar a linha da solução temporária ( if (result['erro'] == true) para if (result['erro'] == true && result['text'] != null) ).
> 
> 
> 
> ja troquei e ainda nao funciona. 

Então não sei como ajudar, fiz isso no meu e funcionou

**Comment by devadonis** [comment]
Hello, everybody. Thanks for your help.
I have got same problem, but I want to solve it permanently not temporary.
Is there any way to resolve it?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
