### ISSUE TITLE
option headless=false not working

### ISSUE THREAD

**Issue by robbytian** [orkestral/venom#2457]
## Description

before using version 5.0.19, I'm using version 5.0.1, and the option headless=false still works to make the browser visible. But after upgrading to version 5.0.19, the headless=false option doesn't work and the browser is still in headless mode. Is there any other configuration that needs to be added?

## Environment

- **Venom version(s):** 5.0.19

## Your Code
![image](https://github.com/orkestral/venom/assets/47393745/794bacc2-a211-493f-a581-87ab7440f2ee)

## Log Output
![image](https://github.com/orkestral/venom/assets/47393745/1b9673e8-7a31-4bf4-9191-7d64c8cc7772)

**Comment by 9cb14c1ec0** [comment]
I am having this problem as well.

**Comment by devadonis** [comment]
Try like this:
headless: 'old'

And then try again.

**Comment by 9cb14c1ec0** [comment]
That still leaves it in headless mode, which is not the desired outcome here.

**Comment by devadonis** [comment]
If still the browser doesn't open, try this option:
browserPathExecutable: 'YOUR BROWSER EXECUTABLE PATH'

**Comment by leandrosantoss** [comment]
Hi guys

![image](https://github.com/orkestral/venom/assets/59751373/f1c9745c-fc0d-4bd5-87fb-5328fd8a16f9)

No matter what you enter in "options" it will be overwritten.
To work around the problem use the "sessionOrOptions"

My exemple here:
![image](https://github.com/orkestral/venom/assets/59751373/18790afd-d446-408a-8052-fc3af5b11e0f)
Enter null to options and Object instance in sessionOrOpitions

[]

**Comment by 9cb14c1ec0** [comment]
#2459, which has been merged, stops overwriting whatever is in options.
