### ISSUE TITLE
erro no método sendMentioned

### ISSUE THREAD

**Issue by rafaelsupport** [orkestral/venom#2461]
## Description

Utilizei no meu código o mesmo modelo informado aqui, apenas substituindo os valores:
```
await client.sendMentioned(
  '000000000000@c.us',
  'Hello @5218113130740 and @5218243160777!',
  ['5218113130740', '5218243160777']
);
```
A função aparentemente não gera erro, porém, também não envia a mensagem com menção e o retorno que chega é apenas **undefined**
Mais alguém passa por esse problema na versão 5.0.19?
**Observação:** No meu Linux ocorre a mesma situação também
## Environment (Linux)
- **Venom version(s):** 5.0.19
- **Browser Version:** 116.0.5845.96
- **OS:** Debian 10
- **Node** v16.15.0

## Environment (Windows)

- **Venom version(s):** 5.0.19
- **Browser:** Chrome/116.0.5845.141
- **OS:** Windows 11
- **Node version:** v18.17.1

## Screenshots
![Captura de tela 2023-09-04 103350](https://github.com/orkestral/venom/assets/43580307/d7a82f35-05be-4b2f-984c-501b23b2694c)

**Comment by sanisamoj** [comment]
Estou com o mesmo erro. Ele gera undefinied quando é colocado um .then()

**Comment by rafaelsupport** [comment]
Up

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
