### ISSUE TITLE
I lost catching-up messages :(

### ISSUE THREAD

**Issue by niron1** [orkestral/venom#2465]
I used to have venom running on a linux docker (inside a ARM Mac) and worked fine (with Chromium)
however I needed to change the setup and now running venom directly under the MacOS (with Chrome)
now, I notice that when the Mac goes to sleep, as I wake it up in the morning, venom never catches-up the messages that accumulated during the night, whereas under the docker it was able to do that.
any idea?

**Comment by allanalcantara** [comment]
> I used to have venom running on a linux docker (inside a ARM Mac) and worked fine (with Chromium) however I needed to change the setup and now running venom directly under the MacOS (with Chrome) now, I notice that when the Mac goes to sleep, as I wake it up in the morning, venom never catches-up the messages that accumulated during the night, whereas under the docker it was able to do that. any idea?

Possibly the MacOS is doing all the work, and when it goes into standby, it may be stopping this job.
use a half check so when it doesn't respond, to half check restart it automatic.
did you understand? orr you can use cron, in case the service stops in the middle of the night.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
