### ISSUE TITLE
Donation Info

### ISSUE THREAD

**Issue by anexa-digital** [orkestral/venom#2468]
**I need info about how to donate to this project from other countries (outside of Brazil), I've tried Paypal, but it doesn't work**

I´m in Colombia.

Best regards, great work.

**Comment by jonalan7** [comment]
If you want to make the link here: [Donate](https://www.paypal.com/donate/?business=ZNZ9EAZN4XCDY&no_recurring=0&item_name=We+deeply+appreciate+your+generous+donation+%E2%80%93+your+support+makes+our+project+a+success%21&currency_code=USD)

**Comment by anexa-digital** [comment]
Done!!!

**Comment by jonalan7** [comment]
> Done!!!

thanks!!!
