### ISSUE TITLE
Multiplas sessoes nao funcionam

### ISSUE THREAD

**Issue by Rafael-720** [orkestral/venom#2473]
As sessão não estão sendo salvas, tem a pasta tokens e gera o qr code, mas ai quando reinicio o cmd pede pra escanear novamente o qrcode, isso pra multiplas sessões, pois 1 sessão funciona, podem me ajudar? Tem alguma forma de salvar a sessão, ou teria que salvar a pasta tokens toda?, a sessão só é salva quando da client.close??

meu codigo:

import fs from 'fs';
import { create } from 'venom-bot';

const sessions = ['sessao1', 'sessao2'];

sessions.forEach((session) => {
  create({
    session: session,
    multidevice: true
  })
    .then((client) => 
      start(client))
    .catch((error) => {
      console.log(error);
    })
});

async function start(client) {
    const botText = "🤖 world 🌎"
    
    client.onAnyMessage((message) => {
        if (message.body.toLowerCase() === "hello") {
            
            client.sendText(message.from, botText)
        }
    })

    // Catch ctrl+C
  process.on('SIGINT', function() {
    client.close();
  });
}

**Comment by augustosnk12** [comment]
@Rafael-720 , conseguiu algum progresso?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
