### ISSUE TITLE
Next Error...

### ISSUE THREAD

**Issue by NyboTV** [orkestral/venom#2475]
Same System Stuff like Error 10 minutes ago...
https://github.com/orkestral/venom/issues/2474

![Bild_2023-09-18_211646888](https://github.com/orkestral/venom/assets/46395862/5380802a-ffea-4c29-ab59-9863cfd9b44b)

**Comment by NyboTV** [comment]
and yes i tried to insert the groupid directly in the function. Nothing changed

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
