### ISSUE TITLE
The file "SingletonLock" was not found

### ISSUE THREAD

**Issue by cesarhcq** [orkestral/venom#2477]
## Description

In the 5.0.21 version for multiple sessions, the venon returns **The file "SingletonLock" was not found**. Anyone can help us to solve this issue?

## Environment

- **Venom version(s):*5.0.21* 
- **Browser:*Chrome* 
- **OS:*Linux*

**Comment by BLRocha** [comment]
Replace: removeStoredSingletonLock

In Linux linkfiles is not considered a file so it will not be ignored by `fs.existsSync(singletonLockPath)` even if it exists.

github project folder: src/controllers/browser.ts
npm: dist/controllers/browser.js



```js
function removeStoredSingletonLock(
  puppeteerOptions: PuppeteerLaunchOptions,
  spinnies: any,
  options: options | CreateConfig
): Promise<boolean> {
  return new Promise((resolve, reject) => {
    try {
      const platform = os.platform();
      const { userDataDir } = puppeteerOptions;
      const singletonLockPath = path.join(
        path.resolve(userDataDir, 'SingletonLock')
      );

      if (platform === 'win32') {
        // No need to remove the lock on Windows, so resolve with true directly.
        resolve(true);
      } else {
        fs.unlink(singletonLockPath, (error) => {
          spinnies.add(`path-stored-singleton-lock-${options.session}`, {
            text: `...`
          });
          if (error && error.code !== 'ENOENT') {
            spinnies.fail(`path-stored-singleton-lock-${options.session}`, {
              text: `Error removing "SingletonLock": ${error}`
            });

            reject(false);
          } else {
            spinnies.succeed(`path-stored-singleton-lock-${options.session}`, {
              text: `Removing SingletonLock path: ${singletonLockPath}`
            });
            resolve(true);
          }
        });
      }
    } catch {
      resolve(true);
    }
  });
}
```

**Comment by chris-kck** [comment]
Thank you @BLRocha . I also experienced this when I was starting the venomBot server in the background using supervisor. Your code worked for me. Would be great if it could be merged in via a PR if it passes tests and does not break anything 🙏

**Comment by Janfrancisco** [comment]
Apologize me @BLRocha , but, can you explain better how to procedure step-by-step? Thanks in advance

**Comment by BLRocha** [comment]
@Janfrancisco  find the function removeStoredSingletonLock in controllers/browser.js and replace it with the code mentioned above, in full.

**Comment by Janfrancisco** [comment]
Sorry again for my ignorance, but in the node_modules folder I can't
find this file. By the way, are you Brazilian?


Em seg., 23 de out. de 2023 às 23:34, Leandro Rocha <
***@***.***> escreveu:

**Comment by BLRocha** [comment]
Yes I'm brazilian. 
In the node_modules folder it is located in `node_modules/venom-bot/dist/controllers/browser.js`.

**Comment by Janfrancisco** [comment]
Em Portugues mesmo amigo, mas, gostaria de sua ajuda pois não sou especialista em nodeJs e nem em JS. Após a colagem , o meu vsCode está dando o seguinte erro: 'Type annotation can only be used in Typescript files'. Ele deve estar reclamando que eu deveria usar typescript, mas não quero me aprofundar muito nisto.  Tem outra forma de contornar?

**Comment by BLRocha** [comment]
Seu problema é de configuração do vscode, nada tem haver com o venom-bot.

Procure por `javascript.validate.enable` veja também as configurações do eslint e prettier.

**Comment by Janfrancisco** [comment]
Leandro, ainda com problemas aqui que não consigo resolver dando 'google'.
Vc tem algum chat que poderia me ajudar a resolver este problema, pra não
poluir aqui?


Em ter., 24 de out. de 2023 às 09:38, Leandro Rocha <
***@***.***> escreveu:

**Comment by BLRocha** [comment]
não tenho!

**Comment by MarcoLimaSistemas** [comment]
> Replace: removeStoredSingletonLock
> 
> In Linux linkfiles is not considered a file so it will not be ignored by `fs.existsSync(singletonLockPath)` even if it exists.
> 
> github project folder: src/controllers/browser.ts npm: dist/controllers/browser.js
> 
> ```js
> function removeStoredSingletonLock(
>   puppeteerOptions: PuppeteerLaunchOptions,
>   spinnies: any,
>   options: options | CreateConfig
> ): Promise<boolean> {
>   return new Promise((resolve, reject) => {
>     try {
>       const platform = os.platform();
>       const { userDataDir } = puppeteerOptions;
>       const singletonLockPath = path.join(
>         path.resolve(userDataDir, 'SingletonLock')
>       );
> 
>       if (platform === 'win32') {
>         // No need to remove the lock on Windows, so resolve with true directly.
>         resolve(true);
>       } else {
>         fs.unlink(singletonLockPath, (error) => {
>           spinnies.add(`path-stored-singleton-lock-${options.session}`, {
>             text: `...`
>           });
>           if (error && error.code !== 'ENOENT') {
>             spinnies.fail(`path-stored-singleton-lock-${options.session}`, {
>               text: `Error removing "SingletonLock": ${error}`
>             });
> 
>             reject(false);
>           } else {
>             spinnies.succeed(`path-stored-singleton-lock-${options.session}`, {
>               text: `Removing SingletonLock path: ${singletonLockPath}`
>             });
>             resolve(true);
>           }
>         });
>       }
>     } catch {
>       resolve(true);
>     }
>   });
> }
> ```

funciona mas em node_modules é preciso estar em js. Obrigado pela ajuda! 

```js
function removeStoredSingletonLock(puppeteerOptions, spinnies, options) {
  return new Promise((resolve, reject) => {
    try {
      const platform = os.platform()
      const { userDataDir } = puppeteerOptions
      const singletonLockPath = path.join(
        path.resolve(userDataDir, "SingletonLock")
      )

      if (platform === "win32") {
        // No need to remove the lock on Windows, so resolve with true directly.
        resolve(true)
      } else {
        fs.unlink(singletonLockPath, error => {
          spinnies.add(`path-stored-singleton-lock-${options.session}`, {
            text: `...`
          })
          if (error && error.code !== "ENOENT") {
            spinnies.fail(`path-stored-singleton-lock-${options.session}`, {
              text: `Error removing "SingletonLock": ${error}`
            })

            reject(false)
          } else {
            spinnies.succeed(`path-stored-singleton-lock-${options.session}`, {
              text: `Removing SingletonLock path: ${singletonLockPath}`
            })
            resolve(true)
          }
        })
      }
    } catch {
      resolve(true)
    }
  })
}
```

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
