### ISSUE TITLE
sendFile and sendImage not working properly

### ISSUE THREAD

**Issue by wluisvilhegas** [orkestral/venom#2482]
## Description

Im using the most recent version, simply trying to send a PDF and a PNG file but can't.

Error when sending:  {
  me: {
    id: {
      server: 'c.us',
      user: '55XXXXXXXXXXX',
      _serialized: '55XXXXXXXXXXX@c.us'
    },
    displayName: null,
    verifiedName: null,
    searchName: null,
    pushname: null,
    notifyName: null,
    isBusiness: null,
    formattedUser: null,
    tag: '1695338692',
    eurl: 'https://pps.whatsapp.net/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?ccb=11-4&oh=01_AdRxE89sQZIwBXhuyihyIzMQUJGYMRWTmF8NVFR8xG3rdw&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
    previewEurl: 'https://pps.whatsapp.net/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdSRVgL78g82By2vk_Y-6F4V6QqFlJHd2gnUMSBVm_eJrA&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
    fullDirectPath: '/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?ccb=11-4&oh=01_AdRxE89sQZIwBXhuyihyIzMQUJGYMRWTmF8NVFR8xG3rdw&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
    previewDirectPath: '/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdSRVgL78g82By2vk_Y-6F4V6QqFlJHd2gnUMSBVm_eJrA&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
    filehash: 'rJj3z/t3AECqnoiHKVU6pofHVLyA52ldSF+Gg//1UlA=',
    stale: false,
    eurlStale: false,
    timestamp: 1695339379959,
    hostRetryCount: 0
  },
  to: {
    server: 'c.us',
    user: '55XXXXXXXXXXX',
    _serialized: '55XXXXXXXXXXX@c.us'
  },
  erro: true,
  text: 'Error to processFiles',
  status: 404
}

## Your Code

I tried with local file:

await client.sendImage(message.from, "21577.jpg", "21577.jpg", "TesteCaption")
.then((result) => {
     console.log("Result: ", result); //return object success
}).catch((erro) => {
     console.error("Error when sending: ", erro); //return object error
});

and with URL 

await client.sendImage(message.from, "https://img.ibxk.com.br/materias/5866/21577.jpg", "image.jpg", "TesteCaption")
.then((result) => {
     console.log("Result: ", result); //return object success
}).catch((erro) => {
     console.error("Error when sending: ", erro); //return object error
});

both ways return me the same error.

  erro: true,
  text: 'Error to processFiles',
  status: 404

I can send messages normally, the error is when sending files or images, how can i solve it?

**Comment by admina1** [comment]
Same error here, last night the image worked, today it doesn't

**Comment by admina1** [comment]
If I fix it I'll come back and tell yo, Maybe it's an anti-virus update or firewall, is the only think changes in my computer today, check it

**Comment by ono77** [comment]
same problem here..

**Comment by robbytian** [comment]
same problem heree.I have checked and found that this error occurs in the latest version of WhatsApp web

**Comment by veracity-ind** [comment]
I am also having this issue. Started coming with whatsapp web version 2.2340.9

**Comment by mauricioabreeu** [comment]
I have the same problem here

**Comment by rzlnhd** [comment]
I've tried to change from this
```js
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob
          };
        }),
    chat,
    1
  );
```
to this
```js
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob
          };
        }),
    chat,
    chat
  );
```

on [src/lib/wapi/functions/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/functions/process-files.js#L9) and [src/lib/wapi/help/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/help/process-files.js#L10) file. Works good for me.

I'm still waiting the correct ways to solve this issue though.

**Comment by mauricioabreeu** [comment]
Funciona pra mim, obrigado

**Comment by rajeshshettysrs** [comment]
We are also facing same issue,while sending pdf
![image](https://github.com/orkestral/venom/assets/20316958/ae48fb7b-e046-407b-9d4d-ef1fc0ca6e3b)

**Comment by satishgunasekaran** [comment]
How to resolve this

**Comment by AwesomeAbhaySingh** [comment]
I am facing the same problem file and image not send. 
Error when sending: {
me: {
id: {
server: 'c.us',
user: '55XXXXXXXXXXX',
_serialized: '[55XXXXXXXXXXX@c.us](mailto:55XXXXXXXXXXX@c.us)'
},
displayName: null,
verifiedName: null,
searchName: null,
pushname: null,
notifyName: null,
isBusiness: null,
formattedUser: null,
tag: '1695338692',
eurl: 'https://pps.whatsapp.net/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?ccb=11-4&oh=01_AdRxE89sQZIwBXhuyihyIzMQUJGYMRWTmF8NVFR8xG3rdw&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
previewEurl: 'https://pps.whatsapp.net/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdSRVgL78g82By2vk_Y-6F4V6QqFlJHd2gnUMSBVm_eJrA&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
fullDirectPath: '/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?ccb=11-4&oh=01_AdRxE89sQZIwBXhuyihyIzMQUJGYMRWTmF8NVFR8xG3rdw&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
previewDirectPath: '/v/t61.24694-24/378017733_688551789817191_5553061098892593864_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdSRVgL78g82By2vk_Y-6F4V6QqFlJHd2gnUMSBVm_eJrA&oe=6519FD11&_nc_sid=000000&_nc_cat=105',
filehash: 'rJj3z/t3AECqnoiHKVU6pofHVLyA52ldSF+Gg//1UlA=',
stale: false,
eurlStale: false,
timestamp: 1695339379959,
hostRetryCount: 0
},
to: {
server: 'c.us',
user: '55XXXXXXXXXXX',
_serialized: '[55XXXXXXXXXXX@c.us](mailto:55XXXXXXXXXXX@c.us)'
},
erro: true,
text: 'Error to processFiles',
status: 404
}

How to resolve it?

**Comment by robbytian** [comment]
on your project go to node_modules/venom-bot/dist/lib/wapi/wapi.js

find this code
![image](https://github.com/orkestral/venom/assets/47393745/03a4a01f-79af-4e8a-9aa0-3b668474c64b)

change 1 to e, like this
![image](https://github.com/orkestral/venom/assets/47393745/214b781d-b218-4c50-813a-2f149d870028)

this work for me

**Comment by AwesomeAbhaySingh** [comment]
Solution not work

**Comment by rajeshshettysrs** [comment]
> I've tried to change from this
> 
> ```js
> await mediaCollection.processAttachments(
>     Debug.VERSION === '0.4.613'
>       ? blobs
>       : blobs.map((blob) => {
>           return {
>             file: blob
>           };
>         }),
>     chat,
>     1
>   );
> ```
> 
> to this
> 
> ```js
> await mediaCollection.processAttachments(
>     Debug.VERSION === '0.4.613'
>       ? blobs
>       : blobs.map((blob) => {
>           return {
>             file: blob
>           };
>         }),
>     chat,
>     chat
>   );
> ```
> 
> on [src/lib/wapi/functions/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/functions/process-files.js#L9) and [src/lib/wapi/help/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/help/process-files.js#L10) file. Works good for me.
> 
> I'm still waiting the correct ways to solve this issue though.

worked,thank you so much
