### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by EdesNogueira** [orkestral/venom#2490]
Hi, the bot was working perfectly, it was sending pdf files, then suddenly it stopped, does anyone know how to solve this error?

Fala pessoal, o bot estava funcionando perfeitamente, enviava os arquivos pdf, do nada parou, alguem ai sabe solucionar esse erro?

![errorr](https://github.com/orkestral/venom/assets/132686747/5a71376f-22d1-463f-a036-09394899192b)

**Comment by rafael3007** [comment]
Também percebi e estou com o mesmo problema

**Comment by EdesNogueira** [comment]
> Também percebi e estou com o mesmo problema

cara se achar uma solução avisa aqui por favor..

**Comment by rafael3007** [comment]
Ainda não lançaram a versão oficial, ainda está na 5.0.21, porém vc pode baixar o repositório e fazer as seguintes alterações:
Mude de 

```javascript
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob
          };
        }),
    chat,
    1
  );
 ```
para

```javascript
await mediaCollection.processAttachments(
    Debug.VERSION === '0.4.613'
      ? blobs
      : blobs.map((blob) => {
          return {
            file: blob
          };
        }),
    chat,
    chat
  );
```
em [src/lib/wapi/functions/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/functions/process-files.js#L9) e [src/lib/wapi/help/process-files.js](https://github.com/orkestral/venom/blob/17b437be9d322f9bb38ee6988f4e9feef677de71/src/lib/wapi/help/process-files.js#L10).

Caso faça isso ( de clonar o repositório ) terá que alterar a importação do venom que ao invés de puxar do node_modules, vai puxar de dist/index.js

Ainda estou esperando as maneiras oficial/correta de resolver esse problema
