### ISSUE TITLE
404 Page Not Found: docs.orkestral.io/venom

### ISSUE THREAD

**Issue by code4you2021** [orkestral/venom#2491]
![CleanShot 2023-09-27 at 08 22 00@2x](https://github.com/orkestral/venom/assets/83153991/9a267661-1eab-48e7-a859-081dfd4d71e8)

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
