### ISSUE TITLE
How to use it with Python?

### ISSUE THREAD

**Issue by CyberSinister** [orkestral/venom#25]
Hey Orkestral!
Amazing piece of work. When all else failed, this worked.

Now, I have no experience with node what-so-ever but I was hoping anyone could help and guide me on how to use it with Python. I was to send messages using a Python script but I just don't know where to start. Can you help?

**Comment by netojose** [comment]
You can't @CyberSinister . Maybe you can write some javascript functions and call them from python using this: http://sweetme.at/2014/02/17/a-simple-approach-to-execute-a-node.js-script-from-python/

But I don't know how the phyton will handle the async code.

**Comment by smashah** [comment]
@CyberSinister https://github.com/open-wa/wa-automate-python

**Comment by CyberSinister** [comment]
Thank you for your time guys. I just made an API and called it from Python.

**Comment by smashah** [comment]
@CyberSinister if you want a simple and completely **_working_** API (along with webhooks) you can use this: https://github.com/open-wa/wa-automate-nodejs/blob/master/demo/server.ts
