### ISSUE TITLE
window.WAPI.onInterfaceChange does not return any status

### ISSUE THREAD

**Issue by limshengli** [orkestral/venom#2502]
## Description

WAPI.onInterfaceChange() callback function doesn't provide any changed state

## Environment

- **Venom version(s):** 5.0.22
- **Browser:** Microsoft Edge 117.0.2045.60
- **OS:** Windows 11
- **Node version:** 20.5.1

## Steps to Reproduce

1. Inject WAPI.js script into Microsoft Edge browser through console after navigated to WhatsApp web
2. Execute window.WAPI.onInterfaceChange(console.log) in console window to print out callback value

## Additional context / Screenshot

WAPI.onInterfaceChange(console.log) does not show anything on the console, unlike the old version of venom

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
