### ISSUE TITLE
npm does not detect the new v5.0.22

### ISSUE THREAD

**Issue by jack1230** [orkestral/venom#2503]
Hello, I want to update the version of Venom but npm stays at v5.0.21 and if I force v5.0.22 it shows me that the version is not available.
Any solution?

**Comment by henriquedcm** [comment]
Hello. You can add a reference to the Github release to your package.json as the following:

```json
"dependencies": {
    "venom-bot": "github:orkestral/venom#v5.0.22"
},
```

This is a temporary solution I used in my project while the 5.0.22 version hasn't been published to NPM.

**Comment by jack1230** [comment]
thank you
