### ISSUE TITLE
Error when sending animated Sticker "Error: Evaluation failed: t"

### ISSUE THREAD

**Issue by Fredwuz** [orkestral/venom#251]
I am trying to send a animated Sticker using this code
```javascript    
await gclient
      .sendImageAsStickerGif(message.from, 'test.gif')
      .then((result) => {
        console.log('Result: ', result) //return object success
      })
      .catch((erro) => {
        console.error('Error when sending:', erro.stack) //return object error
      })
```
and I get this error
```
(node:1745) UnhandledPromiseRejectionWarning: Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/helper.js:94:19)    at DOMWorld.evaluate (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/DOMWorld.js:89:24)
  -- ASYNC --
    at Frame.<anonymous> (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/helper.js:95:27)
    at Whatsapp.<anonymous> (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:510:84)
    at step (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at /home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:17:12)
    at /home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:506:99
    at new Promise (<anonymous>)
    at Whatsapp.<anonymous> (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:506:51)
    at step (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:46:23)
    at Object.next (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:27:53)
    at fulfilled (/home/pi/venom-bot-WhatsappWebBot/node_modules/venom-bot/dist/api/layers/sender.layer.js:18:58)
(node:1745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
this is the gif I am trying to send
![test](https://user-images.githubusercontent.com/36505101/96793496-d0298380-13fc-11eb-86ae-86ff9c47bd55.gif)
I think the problem is that the gif is too large to send
the problem is because the error isn't caught by the try and catch the whole process get stopped in my setup and the queue I made for the bot gets filled up with Sticker that cant be sent and the message won't show up on the onAck function
Thanks for the Help in Advance :D

**Comment by caugustoschiller** [comment]
I made a code to convert gif to animated sticker using [](https://github.com/NabiKAZ/video2gif)

 if (message.isGroupMsg === false && message.isMedia === true && message.isMMS === true) {
            const buffer = await client.decryptFile(message);
            const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
            await fs.writeFile(fileName, buffer, (err) => {
                exec('start video2gif.bat some-file-name.mp4 -o clip.gif -y -w 96:96 -f 10 -q 6', (error, stdout, stderr) => {
                    if (error) {
                        console.log(`error: ${error.message}`);
                        return;
                    }
                    if (stderr) {
                        console.log(`stderr: ${stderr}`);
                        return;
                    }
                    client
                        .sendImageAsStickerGif(message.from, 'clip.gif')
                        .then((result) => {
                           console.log('Result: ', result); //return object success
                        })
                        .catch((erro) => {
                            console.error('Error when sending: ', erro); //return object error
                        });
                });
            });
        }

**Comment by Fredwuz** [comment]
ok thanks for the answer but does this code work with the given gif above? and can you send the code inside a code block thanks (to send I  a code block just press the <> icon above the text field and insert the code :D)

**Comment by caugustoschiller** [comment]
When you download the gif via whatsappweb it saves with the .mp4 format so I convert it to gif already reducing the size to 96x96 which is the size of the sticker so that I have no problem when converting to the animated sticker

**Comment by Fredwuz** [comment]
hmm okk thanks will try this to convert the image to 96x96

**Comment by Fredwuz** [comment]
Thank you it worked but I made 256x256 because the quality was pretty bad with just 96x96

**Comment by Fredwuz** [comment]
But in the end, this wouldn't solve the problem it will help to prevent it from occurring but there is still an error that won't get 
caught when sending a Sticker that's to large

**Comment by caugustoschiller** [comment]
I downloaded the gif you posted up there and it has black borders on the top and bottom and the font is very small, I sent the gif using my code and it turned into a figure without problems even the gif with a large size

**Comment by Fredwuz** [comment]
Okay thanks for the comment could you post your code again in code blocks because when I copy the code above it gives errors just use the <> button above the text box and I think you are using a batch file to convert the video or what is video2gif.bat? 
Thanks in advance :D

**Comment by caugustoschiller** [comment]
Sorry, newbie here and I'm from Brazil, lol, [video2gif](https://github.com/NabiKAZ/video2gif)

`if (message.isGroupMsg === false && message.isMedia === true && message.isMMS === true) {
const buffer = await client.decryptFile(message);
const fileName = some-file-name.${mime.extension(message.mimetype)};
await fs.writeFile(fileName, buffer, (err) => {
exec('start video2gif.bat some-file-name.mp4 -o clip.gif -y -w 96:96 -f 10 -q 6', (error, stdout, stderr) => {
if (error) {
console.log(error: ${error.message});
return;
}
if (stderr) {
console.log(stderr: ${stderr});
return;
}
client
.sendImageAsStickerGif(message.from, 'clip.gif')
.then((result) => {
console.log('Result: ', result); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});
});
});
}`

**Comment by Fredwuz** [comment]
sooo I tested the new version but it isn't working as far as I tested. The code only checks for the height and width of the image and not for the size so I checked it in making the Image smaller (512x512) and the same error and I would say it didn't made the situation worse but it won't help because every image inserted will automatically get converted to 512x512 by the "select-sticker" code https://github.com/orkestral/venom/blob/f24416af0613ce2cf2bf29a6835f1a7793ef2ece/src/api/helpers/select-sticker.ts#L70
and now even Images larger than 512x512 won't get accepted even if they would work.
I think a fix would be to check if the image size is larger then 1MB before sending

the image I used
![testimage](https://user-images.githubusercontent.com/36505101/99889859-6b5e8480-2c59-11eb-9c52-6cc42e1c98ae.gif)

Error:
```
(node:25762) UnhandledPromiseRejectionWarning: Error: Evaluation failed: a
    at ExecutionContext._evaluateInternal (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/pi/venom-bot-WhatsappWebBot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:25762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)


```

**Comment by edgardmessias** [comment]
@Fredwuz , there are not resize from a gif image, but I agree about file size.

By default the sharp don't resize gif.

https://faq.whatsapp.com/general/how-to-create-stickers-for-whatsapp

Could you make tests with differents files sizes?

**Comment by Fredwuz** [comment]
Ohh ok and yeah sure I could test some stuff

**Comment by Fredwuz** [comment]
Soo I already made some tests regarding the Sticker size because venom edits the file a bit that it has a different size (smaller) before sending and WhatsApp also is only using 75% quality of the images  
I think the reduced file size by venom is because of the conversion to webp format and here is the table with my test results I haven't got the OG images anymore sadly because the testing is a bit in the past
| Picture | Gif Original File Size | File Size after Converting by Venom | File Size after Sending | Gif/Sent ratio | Converted/Sent ratio | Gif/Converted ratio |
|---------|------------------------|-------------------------------------|-------------------------|----------------|----------------------|---------------------|
| 1       | 346687                 | 258708                              | 194030                  | 0.55966909633  | 0.74999613463        | 0.7462293077        |
| 2       | 83204                  | 49096                               | 36820                   | 0.44252680159  | 0.74995926348        | 0.5900677852        |
| 3       | 414018                 | 313160                              | 234870                  | 0.56729417561  | 0.75                 | 0.75639223415       |
| 4       | 262505                 | 141048                              | 105784                  | 0.40297899087  | 0.74998582043        | 0.5373154797        |
| 5       | 1404020                | 1326688                             | 995016                  | 0.70869075939  | 0.75                 | 0.94492101252       |

**Comment by kaiserdj** [comment]
Is there any way to detect that the error it gives is that the image is too heavy?
I mean to distinguish that error from any other

**Comment by Fredwuz** [comment]
I am not sure the if it gives a response or just crashes but I would be possible to check if the image is to large just before sending it so like if its larger than 1mb don't send it if its smaller its okay but the problem is if you convert a Gif to webp the file size decreases so the check has to be done with the webp file
