### ISSUE TITLE
Body Text in sendLinkPreview or Pending in sendText

### ISSUE THREAD

**Issue by muhfajarm** [orkestral/venom#2511]
I'm still learning how to use this repository, and I'm having problems with sending link with preview, is there a way to send the text in the body instead of just the URL, or can you not send the text with a pending duration of maybe 10 seconds so that the preview link can work.
The linkWithPreview function only contains the URL in the body text like the following image
![Screenshot_2023-10-21_15-53-01](https://github.com/orkestral/venom/assets/62341193/24b0d8c2-c64a-4a0f-9329-267fe726614e)
But can it be made like this, not only the url but there is other text in the body
![Screenshot_2023-10-21_15-56-10](https://github.com/orkestral/venom/assets/62341193/39d32868-253e-4c67-ba90-8cbbf3dd4781)
Thank You

**Comment by pO1GKEpI** [comment]
http://api.textmebot.com/send.php?recipient=[phone number]&apikey=[your premium apikey]&text=[text to send]`

**Comment by muhfajarm** [comment]
> [http://api.textmebot.com/send.php?recipient=[phone](http://api.textmebot.com/send.php?recipient=%5Bphone) number]&apikey=[your premium apikey]&text=[text to send]`

What is this for? I want to use this repository. Thank

**Comment by wernerpj1** [comment]
Puxa estou com um problema semelhante injetei o script na extensao do chrome e quando escrevo um link no wp fica só loading não envia

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
