### ISSUE TITLE
Add onMessageDeleted/onMessageEdited event/method

### ISSUE THREAD

**Issue by myishay** [orkestral/venom#2515]
**Is your feature request related to a problem? Please describe.**
When a message is being deleted/edited by the sender, venom client is not able to identify that.

**Describe the solution you'd like**
add `onMessageDeleted` method
add `onMessageEdited` method

**Describe alternatives you've considered**
Maybe adding a raw event handler and make it possible to generate a custom event

**Additional context**
whatsapp-web.js handles it as follows:
https://github.com/pedroslopez/whatsapp-web.js/blob/7737a0d701c2bde180c4cdcb2926895b0b649b4f/example.js#L386C25-L386C25

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
