### ISSUE TITLE
Can't Send Audios: Error to chat not find 404

### ISSUE THREAD

**Issue by llzmbbtz** [orkestral/venom#2516]
## Description

I can't send audio, I tried using the two methods available by the library, but they both give a similar error

## Environment

Venom 5.0.21
Chrome/118.0.5993.70
Windows 11
node v20.8.1

## Steps to Reproduce

if (message.body.toLowerCase() === '/audio') {
                try {
                    // Caminho para o arquivo de áudio
                    const audioFilePath = 'C:\\Users\\bruno\\Desktop\\bruno bot\\audio.mp3';
                    await client.sendVoice(message.from, audioFilePath)
                    .then((result: any) => {
                        console.log('Áudio enviado com sucesso:', result);
                      });
                } catch (error) {
                    console.error('Erro ao enviar áudio:', error);
                    await client.reply(message.from, '🤖 *Chat Bot:* Desculpe, houve um problema ao enviar o áudio. Por favor, tente novamente mais tarde.', message.id);
                }
                return;
            }

## Log Output

Erro ao enviar áudio: {
  me: {
    id: {
      server: 'c.us',
      user: '50378589068',
      _serialized: '50378589068@c.us'
    },
    displayName: null,
    verifiedName: 'Chat Bot',
    searchName: null,
    pushname: 'Chat Bot',
    notifyName: null,
    isBusiness: true,
    formattedUser: null,
    tag: '1542350478',
    eurl: 'https://pps.whatsapp.net/v/t61.24694-24/390184699_348409127845950_3902716254527738964_n.jpg?ccb=11-4&oh=01_AdSGjQWMsvzNG9O4acIhi13FuSS4ZNdu9MqyXCP5EWFysA&oe=654E417E&_nc_sid=000000&_nc_cat=103',
    previewEurl: 'https://pps.whatsapp.net/v/t61.24694-24/390184699_348409127845950_3902716254527738964_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdQ-kJlAMdKv0mIo_7_yz4G2l6tnKuzZk_1CSb37jTFGug&oe=654E417E&_nc_sid=000000&_nc_cat=103',
    fullDirectPath: '/v/t61.24694-24/390184699_348409127845950_3902716254527738964_n.jpg?ccb=11-4&oh=01_AdSGjQWMsvzNG9O4acIhi13FuSS4ZNdu9MqyXCP5EWFysA&oe=654E417E&_nc_sid=000000&_nc_cat=103',
    previewDirectPath: '/v/t61.24694-24/390184699_348409127845950_3902716254527738964_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdQ-kJlAMdKv0mIo_7_yz4G2l6tnKuzZk_1CSb37jTFGug&oe=654E417E&_nc_sid=000000&_nc_cat=103',       
    filehash: 'X+/m4y5NMsCVpytP+JTqG2ksDAeeBtSdFdhziM4VlmU=',
    stale: false,
    eurlStale: false,
    timestamp: 1698771964166,
    hostRetryCount: 0,
    dataSource: 'server',
    description: 'Your virtual assistant!',
    categories: [ [Object], [Object] ],
    profileOptions: { commerceExperience: 'none', cartEnabled: true },
    email: null,
    website: [],
    businessHours: null,
    address: null,
    fbPage: {},
    igProfessional: {},
    isProfileLinked: false,
    isProfileLocked: true,
    coverPhoto: null,
    automatedType: 'unknown',
    prompts: null,
    commandsDescription: null,
    commands: null
  },
  to: {
    server: 'g.us',
    user: '120363195055397672',
    _serialized: '120363195055397672@g.us'
  },
  erro: true,
  text: 'Error to chat not find',
  status: 404
}

**Comment by allanalcantara** [comment]
tenta enviar assim:
const audioFilePatch = './musica.mp3';
await client.sendVoice([sender.id](http://sender.id/), audioFilePatch).then((result) => {
    console.log('Result: ', result); //return object success
})
    .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
    });

**Comment by llzmbbtz** [comment]
> tenta fazer da seguinte maneira:
> 
> if (message.body.toLowerCase() === '/audio') { const audioFilePatch = './music1a.mp3'; await client.sendVoice(message.from, audioFilePatch).then((result) => { console.log('Áudio enviado com sucesso:', result); //return object success }) .catch(async (erro) => { await client.reply(message.from, '🤖 Chat Bot: Desculpe, houve um problema ao enviar o áudio. Por favor, tente novamente mais tarde.', message.id); console.error('Error when sending: ', erro); //return object error }); }
> 
> Quando é algo que se espera por meio do await, usa-se async na função. segue exemplo, em caso de erro e envio ![unnamed (1)](https://user-images.githubusercontent.com/33518897/282786431-16514a76-a99d-4dfa-96d7-63cb78687fd3.jpg) ![unnamed](https://user-images.githubusercontent.com/33518897/282786444-ba7c5ae0-dd67-45a3-832a-6b1902dfeaa4.jpg)

Obrigado pela ajuda, eu tentei aqui mas continuo recebendo "erro: true,
  text: 'Error to chat not find',
  status: 404" Eu tentei de todas as maneiras usar o venom-bot, mas tudo que consigo enviar são textos. Quando se trata de mídia eu tenho esse problema. Tive que migrar pro whatsapp-web.js pra conseguir enviar as coisas. Eu sou novo nisso, tudo que faço é com ajuda do chat gpt, então não tenho muitas habilidades de resolver esses problemas.

**Comment by w7br** [comment]
Conseguiu resolver? Ontem tive um problema com meu sistema, precisei formatar, e para minha grato surpresa, meu bot que roda localmente havia parado de funcionar, também com o mesmo problema que vc aponta ... "Error to chat not find" ... imaginava que pudesse ser permissão dos arquivos e pastas, mas presumo que esteja enganado.

Agradeceria por qualquer ajuda

**Comment by allanalcantara** [comment]
Boa tarde, por gentileza envia a parte do código que referencia ao audio

**Comment by fellipgomes** [comment]
mesmo problema aqui, testei com aúdio

**Comment by allanalcantara** [comment]
Não sei como vocês estão fazendo, mas não é nenhum Bixo de 7 cabeças, Até por que esta funcionando normalmente. dentre as funções, defina:
`async function start(client) {
  try {
client.onMessage(async (message) => {
// Constante para mensagemRecebida do Usuario
      const mensagemRecebida = message.body.toLowerCase();
 // Variavel da função que envia o audio
if (mensagemRecebida === 'audio') {
            const audioFilePatch = 'local_do_audio.mp3';
            await client
              .sendVoice(message.from, audioFilePatch)
              .then((result) => {
                console.log('Áudio enviado com sucesso:', result); //return object success
              })
              .catch(async (erro) => {
                await client.reply(
                  message.from,
                  '🤖 Chat Bot: Desculpe, houve um problema ao enviar o áudio. Por favor, tente novamente mais tarde.',
                  message.id
                );
                console.error('Error when sending: ', erro); //return object error
              });
  } catch (error) {
    console.error('Erro ao iniciar o bot:', error);
  }`
  
  toda vez que o usuario digitar audio, ele recebera o audio que vc enviou

**Comment by netohd** [comment]
também estou tendo o mesmo problema, tentei várias coisas mas sem sucesso

**Comment by allanalcantara** [comment]
> também estou tendo o mesmo problema, tentei várias coisas mas sem sucesso
> 
> ```
> function start(client) {
>       client.onMessage(async (message) => {
>         if (message.mimetype?.includes('ogg') && message.isGroupMsg === false) {
>           const audioFilePatch = './audio.mp3';
>           await client.sendVoice(message.from, audioFilePatch)
>             .then((result) => {
>               console.log('Áudio enviado com sucesso:', result); //return object success
>             })
>             .catch(async (erro) => {
>               await client.reply(message.from, '🤖 Chat Bot: Desculpe, houve um problema ao enviar o áudio. Por favor, tente novamente mais tarde.', message.id);
>               console.error('Error when sending: ', erro); //return object error
>             });
>         }
>       });
>     }
> ```

Posta toda parte de conexão do teu arquivo pra gente saber qual é o formato de envio que esta sendo feito
