### ISSUE TITLE
info icon say it is an old version of whatsapp?

### ISSUE THREAD

**Issue by venturion** [orkestral/venom#2530]
## Description
when i send a message the whatsapp show a icon beside it, saying that  the emissor was using an old version of whatsapp

[Description of the bug, When Issue Happens]
it occurs when i send the message via venom bot api

## Environment

- **Venom version(s):** [5.0.21]
- **Browser:** [Chrome 119]
- **OS:** [Windows 10]
- **Node version:** [node 19]

## Steps to Reproduce

1.  send a message via venom bot api

## Additional context / Screenshot
![mensagem de teste 01](https://github.com/orkestral/venom/assets/3776794/ef3aa28e-74ae-4229-b048-f20ab5f1f2d8)
![mensagem de teste 02](https://github.com/orkestral/venom/assets/3776794/fb47d2e2-1916-4dc4-9f15-45544d36fa26)

**Comment by CleyssonDias** [comment]
resolveu?

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
