### ISSUE TITLE
getGroupMembers not working as expected

### ISSUE THREAD

**Issue by pedroota** [orkestral/venom#2536]
## Description

Hello everyone! I'm currently working on retrieving the members of a specific group, but I've encountered an issue in my code. The error message I'm receiving is "Evaluation failed: TypeError: window.Store.Cmd.openChatBottom is not a function."

Error:

![image](https://github.com/orkestral/venom/assets/48136045/2a4ae6df-bd83-4a55-be5a-23dc45c41814)

My code:

![image](https://github.com/orkestral/venom/assets/48136045/b05646bf-a0c5-43a0-b554-cdf9733d6ea8)

## Environment

- **Venom version(s):** 5.0.21
- **Browser:** Chrome
- **OS:** Windows 11
- **Node version:** 18 LTS

**Comment by ono77** [comment]
same problem, it seems that the module window.Store.Cmd and other properties of Window.Store are missing in src\lib\wapi\store\store-objects.js and get-store.js

**Comment by RAKESHSUVIDYA** [comment]
same problem. I am get **window.Store.Cmd.openChatBottom is not a function**

**Comment by jadsonlourenco** [comment]
Same issue, not working...

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
