### ISSUE TITLE
Is it possible to read the messages we write ourselves? That is, our own messages that we write from the Smartphone or whatappsweb?

### ISSUE THREAD

**Issue by inforaudio** [orkestral/venom#2537]
We are checking other bot, and this function is possible..

It may not make much sense if we want the bot to do all the work automatically.
But there are times when we want to monitor conversations and provide data.

Would be possible read this messages?

**Comment by inforaudio** [comment]
searching , we found it..  
client.onAnyMessage( async (message) => {}
With this , you can see all messages. in and out.

**Comment by Felic1ty** [comment]
Is there a way to directly obtain all chat records of contacts, including messages sent by oneself? Thank you

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
