### ISSUE TITLE
Message sending time for each number

### ISSUE THREAD

**Issue by fellipgomes** [orkestral/venom#2577]
I'm using venom-bot on Linux

It works so well that I'm frustrated, how can I reduce the speed at which messages are sent to each different number?

I've already put several "sleeps" on but none of them hold up to Venom's delivery speed.

If you deliver too many messages I will block my account

How can I set a waiting time for each message to the user?

`const venom = require('venom-bot');
const fs = require('fs');

const numbers_list = fs.readFileSync('./numbers.txt', 'utf-8');
const wordList = numbers_list.split('\n');

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function start(client, numero) {
    client
    .sendText(numero, '👋 Olá, já conhece a ACERTO TI?!\nConserto de computadores, Internet via satélite, câmeras de segurança e muito mais!\n\nPalmerópolis - TO')
    .then((result) => {
        console.log('Result: ', result); //return object success
    })
    .catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
    });
    
  }

venom
  .create(
    //session
    'sessionName', //Pass the name of the client you want to start the bot
    //catchQR
    (base64Qrimg, asciiQR, attempts, urlCode) => {
      console.log('Number of attempts to read the qrcode: ', attempts);
      console.log('Terminal qrcode: ', asciiQR);
      console.log('base64 image string qrcode: ', base64Qrimg);
      console.log('urlCode (data-ref): ', urlCode);
    },
    // statusFind
    (statusSession, session) => {
      console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken || chatsAvailable || deviceNotConnected || serverWssNotConnected || noOpenBrowser || initBrowser || openBrowser || connectBrowserWs || initWhatsapp || erroPageWhatsapp || successPageWhatsapp || waitForLogin || waitChat || successChat
      //Create session wss return "serverClose" case server for close
      console.log('Session name: ', session);
    },

    // BrowserInstance
    (browser, waPage) => {
      console.log('Browser PID:', browser.process().pid);
      waPage.screenshot({ path: 'screenshot.png' });
    }
  )
  .then((client) => {
    wordList.forEach(function (e){
        start(client, e)
        
      });
  })
  .catch((erro) => {
    console.log(erro);
  });`

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
