### ISSUE TITLE
Update Copyright at Footer

### ISSUE THREAD

**Issue by amanr-dev** [orkestral/venom#2582]
Update the copyright year at Footer.

**Comment by Tade77** [comment]
Hello @amanr-dev I'm a frontend developer, i will like to work on the copyright update. I need your authorisation

**Comment by amanr-dev** [comment]
Ok go for it, assigned it to @Tade77

**Comment by gyanavardhana** [comment]
Hello @amanr-dev I have tried to solve the issue and have submitted a pull request. I need the approval for your workflows to run.please assign me the authorisation. I will check and try to solve again if anything happens. 
and here is the my pullrequest link.
https://github.com/orkestral/venom/pull/2585

**Comment by amanr-dev** [comment]
> Hello @amanr-dev I have tried to solve the issue and have submitted a pull request. I need the approval for your workflows to run.please assign me the authorisation. I will check and try to solve again if anything happens. It would be a great help if you have specified more about issue ,like copyright year is only found in the license. and here is the my pull request link. #2585

Hi @gyanavardhana , i already assigned it to @Tade77

**Comment by orkestral** [comment]
Não entendi ?

**Comment by Tade77** [comment]
Hello @amanr-dev i have been trying so hard to find the file that i want work on in order to update the copyright year, can you please give access to the library or workflow so i can complete the task.

**Comment by amanr-dev** [comment]
> Hello @amanr-dev i have been trying so hard to find the file that i want work on in order to update the copyright year, can you please give access to the library or workflow so i can complete the task. @ ![Venom](https://private-user-images.githubusercontent.com/100138027/295972683-9ffe3296-12a6-4119-8199-49d5d40323d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAxNTcsIm5iZiI6MTcwNDk4OTg1NywicGF0aCI6Ii8xMDAxMzgwMjcvMjk1OTcyNjgzLTlmZmUzMjk2LTEyYTYtNDExOS04MTk5LTQ5ZDVkNDAzMjNkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mjg3MGQ5MTkxMTg5YTc0NzM0ODFlMjE2ODMwZGNkMWNjM2M3NzViYzRkMWNlZTg5ZTdkNDE2ZDA4MTdiZmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7MlIvA_dJF0rfqB1g6oFtlEUyid16OWsmHFY762tiZM)

Hi, @Tade77, The same issue is also with me.

**Comment by orkestral** [comment]
@Tade77 You have to ask me, only I can authorize anything in the repository

**Comment by Tade77** [comment]
Alright my apology, i kindly need your authorisation if the issue is still open

**Comment by orkestral** [comment]
@Tade77 You can contribute, your collaboration is very important only to do the pull that we approve

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
