### ISSUE TITLE
Error sendFileFromBase64

### ISSUE THREAD

**Issue by pipterbusiness** [orkestral/venom#259]
client.sendFileFromBase64(to, fileBase64, 'pdf', 'pdf')

Error
UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property '1' of null at r (D:\Projetos\tagchat\tagchat-whatsapp\node_modules\venom-bot\dist\lib\wapi\wapi.js:8:22947)

**Comment by bhavya32** [comment]
I have not tried but if the function is not correct, you can decode base64 to buffer and send using sendFile
