### ISSUE TITLE
run on a Server or Docker

### ISSUE THREAD

**Issue by nathanribeiroo** [orkestral/venom#26]
I'm trying to run on AWS or a docker and I can't. Can someone help me?

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!

**Comment by myfjdthink** [comment]
Here is a working demo, it may help.  @nathanribeiroo

```yaml
FROM buildkite/puppeteer as base

WORKDIR /app

# ------------ Dependencies for sharp ------------
RUN  apt-get update \
     && apt-get install -y build-essential python3

COPY package.json .
RUN npm install --production --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/mirrors/node --build-from-source && mv node_modules prod_node_modules
RUN npm install --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/mirrors/node --build-from-source

# ------------ build ------------
FROM buildkite/puppeteer as build
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY src ./src
COPY tsconfig.json tsconfig.build.json package.json ./
RUN npm run build

# ------------ main ------------
FROM buildkite/puppeteer as prod

WORKDIR /app
COPY --from=base /app/prod_node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json .

CMD ["npm","start"]
EXPOSE 3000
```

**Comment by chrisk8er** [comment]
hi @myfjdthink thanks for sharing, after i got an error after i run the dockerfile
```
whatsapp-api | info:     Checking for updates
whatsapp-api | info:     You're up to date
whatsapp-api | info:     [admin:browser] Initializing browser...
whatsapp-api | error:    [admin:browser] Error no open browser
whatsapp-api | error:    [admin:browser] Failed to launch the browser process!
whatsapp-api | [0204/112019.031191:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
whatsapp-api | 
whatsapp-api | 
whatsapp-api | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
whatsapp-api |
```
please help... thanks

**Comment by henriquechagasg** [comment]
For me worked building the container with armno/node-chromium image:
`FROM armno/node-chromium:11.6.0

WORKDIR /usr/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]`

And in venom.create I used the following arguments:

`const chromiumArgs = [
    '--disable-web-security', '--no-sandbox', '--disable-web-security',
    '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
    '--disable-offline-load-stale-cache', '--disk-cache-size=0',
    '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
    '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
    '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
    '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'
  ];

venom.create( 'session', (base64Qrimg, asciiQR, attempts) => {

}, (statusSession, session) => {

}, { useChrome: false,
     browserArgs: chromiumArgs,
     headless: true 
    })
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
      });`
