### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by netohd** [orkestral/venom#2611]
## Description

In the lib documentation, await in writeFile makes no sense, since this function does not return a promise.

![image](https://github.com/orkestral/venom/assets/23285614/b1d54923-4400-4788-bd29-c9eed3cecad2)

**Comment by blackinitial** [comment]
@netohd i try to accee the docs is not error 404 https://docs.orkestral.io/venom

**Comment by netohd** [comment]
I found this code in the npm page

**Comment by mr2samawi** [comment]
> I found this code in the npm page
how to get the doc in code?
