### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by guilhermewiest** [orkestral/venom#2619]
The venom-bot have an error when I try install Venom-bot in Visual Studio Code's console.

Error:

npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\guilherme.wiest\\Desktop\\AVABot\\node_modules\\venom-bot\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\guilherme.wiest\Desktop\AVABot\node_modules\venom-bot\node_modules\puppeteer\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\guilherme.wiest\\Desktop\\AVABot\\node_modules\\venom-bot\\node_modules\\puppeteer\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\guilherme.wiest\Desktop\AVABot\node_modules\venom-bot\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node install.mjs
npm ERR! Error: ERROR: Failed to set up Chrome v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR!     at file:///C:/Users/guilherme.wiest/Desktop/AVABot/node_modules/venom-bot/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:58:23
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)
npm ERR!     at async downloadBrowser (file:///C:/Users/guilherme.wiest/Desktop/AVABot/node_modules/venom-bot/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:87:9) {
npm ERR!   [cause]: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/win64/chrome-win64.zip
npm ERR!       at file:///C:/Users/guilherme.wiest/Desktop/AVABot/node_modules/venom-bot/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:64:31
npm ERR!       at ClientRequest.requestCallback (file:///C:/Users/guilherme.wiest/Desktop/AVABot/node_modules/venom-bot/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:42:13)
npm ERR!       at Object.onceWrapper (node:events:634:26)
npm ERR!       at ClientRequest.emit (node:events:519:28)
npm ERR!       at HTTPParser.parserOnIncomingClient (node:_http_client:690:27)
npm ERR!       at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR!       at TLSSocket.socketOnData (node:_http_client:532:22)
npm ERR!       at TLSSocket.emit (node:events:519:28)
npm ERR!       at addChunk (node:internal/streams/readable:559:12)
npm ERR!       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)

**Comment by albertojrigail** [comment]
+1

**Comment by 9cb14c1ec0** [comment]
When puppeteer was trying to download a version of chrome, the server hosting the chrome installer returned a Internal Server error.  This is not a venom bug, and when I click the download link that returned the Internal Server error, it now downloads just fine.  I think this bug should be closed.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
