### ISSUE TITLE
Error send Video 

### ISSUE THREAD

**Issue by diogo-palma** [orkestral/venom#264]
Hi, i want to send video from venom before update i send videos with sendImage but now i see this function can send only images, then i use sendFile and he works, but now i have this in the console

node:4650) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat] (https://web.whatsapp.com/app2.50a9c969b35b21702839.js:2:439527)
    at Object.f [as sendFile] (/root/whatsbot/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:24364)
    at ExecutionContext._evaluateInternal (/root/whatsbot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4650) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

can anyone help with this?

**Comment by bhavya32** [comment]
@diogo-palma My video files are going, please share the code.

**Comment by diogo-palma** [comment]
async function enviarImagem(chat_id,contato,image,mensagem) {

   var fileDir = path.resolve(__dirname, '..') + '/public/uploads/';
	await global.client[chat_id].sendFile(
      contato+"@c.us",
      fileDir + image,
      image,
      mensagem
   ).catch((erro) => {
      console.error('Error when sending: ', erro); //return object error
    });
   return true;
}

**Comment by diogo-palma** [comment]
> (node:27883) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat] (https://web.whatsapp.com/app2.50a9c969b35b21702839.js:2:439527)
    at Object.f [as sendFile] (/root/whatsbot/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:24364)
    at ExecutionContext._evaluateInternal (/root/whatsbot/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by caugustoschiller** [comment]
if (message.body === '/encontro' && message.isGroupMsg === true) {
            let user = message.from;
            await client
                .sendFile(
                    ${user}`,
                    'Encontro.mp4',
                    'Encontro',
                    'Encontro do Hospício dia 16/10! Não percam caralhoooo!!! 🔝🔝🔝🔝🔝'
                )
                .then((result) => {
                    console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });
        }

**Comment by diogo-palma** [comment]
> if (message.body === '/encontro' && message.isGroupMsg === true) {
> let user = message.from;
> await client
> .sendFile(
> ${user}`,
> 'Encontro.mp4',
> 'Encontro',
> 'Encontro do Hospício dia 16/10! Não percam caralhoooo!!! '
> )
> .then((result) => {
> console.log('Result: ', result); //return object success
> })
> .catch((erro) => {
> console.error('Error when sending: ', erro); //return object error
> });
> }

do u test in server online?

**Comment by caugustoschiller** [comment]
I ran an instance on google cloud, just left the files in the same folder

**Comment by diogo-palma** [comment]
i see the problem is when i update venon,  i think in the puppeters version problem
