### ISSUE TITLE
Creating project with typescript

### ISSUE THREAD

**Issue by lulukamagaiver** [orkestral/venom#265]
Hello guys, I'm creating a node api with typescript and when compiling the project it gives the following error:
`node_modules/venom-bot/dist/api/whatsapp.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get waPage(): Page;`

**Comment by bhavya32** [comment]
@lulukamagaiver Code?

**Comment by lulukamagaiver** [comment]
@bhavya32 this happens when you saw the project compiled using the following command: `"compile": "tsc -w"`

**Comment by edgardmessias** [comment]
@lulukamagaiver , what is your typescript version?
