### ISSUE TITLE
WhatsApp will soon disallow 'unsafe-inline' and 'unsafe-eval'

### ISSUE THREAD

**Issue by ghayman** [orkestral/venom#2657]
@9cb14c1ec0 @mdedirudianto 

#2654 is looking great! Thank you so much for you work on that! I am doing more testing today on your latest commit on your fork.

However, the test 'webVersion'  WhatsApp page 2.3000.1012170943-alpha does not seem to have the new WA Security Policy. I only see that if a set the "Join the Beta" flag  in web.whatsapp.com itself. 

That serves up Version 2.3000.1012248284

If you look in the Headers  received for url web.whatsapp.com you will see that Content-Security-Policy  'script-src' item no longer allows 'unsafe-inline' and 'unsafe-eval'

This will cause page.addScriptTag() to be rejected and wapi.js will not get injected.
It will also disallow any `eval('some javascript)` code and cause it to fail as well

Potential Solution
I did find that page.evaluate(<some javascript code>) still works.

So my solution was to replace page.addScriptTag() in whatsapp.js with page.evaluate() and literally copy and paste the compiled dist/lib/wapi.js code in to that as the code to be evaluated (yes, this was big. Yes this is a "build" nightmare).

This seems to work and does not trigger the unsafe script errors that will block wapi.js and other JS <script> code from being injected.

_Originally posted by @ghayman in https://github.com/orkestral/venom/issues/2622#issuecomment-2015824389_

**Comment by 9cb14c1ec0** [comment]
We could just drop the Content-Security-Policy header with puppeteer.  Did you try that?  My code already does this if a version is specified.

**Comment by ghayman** [comment]
Oh! Nice idea - I am somewhat new to Puppeteer - I did not think of that!

**Comment by 9cb14c1ec0** [comment]
https://github.com/orkestral/venom/blob/17aae02a7cecbd7f1cb02b86cbd5e8ca38b8acbf/src/controllers/browser.ts#L60-L70

**Comment by ghayman** [comment]
```typescript
    await waPage.setUserAgent(useragentOverride);

    // Seems like they already thought of this
    await waPage.setBypassCSP(true);

    waPage.setDefaultTimeout(60000);
```

**Comment by 9cb14c1ec0** [comment]
Are you going to open a pull request, or should I?

**Comment by 9cb14c1ec0** [comment]
Opened #2658 

I am running into this problem on pretty much all versions of whatsapp now.
