### ISSUE TITLE
sendChatstate instead setChatstate

### ISSUE THREAD

**Issue by yurik44** [orkestral/venom#266]
Is sendChatstate instead setChatstate:

https://github.com/orkestral/venom/blob/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/api/layers/sender.layer.ts#L675

https://github.com/orkestral/venom/blob/0d3763498543f876e7c42661933e31a822d1e048/src/lib/wapi/wapi.js#L246

**Comment by joaosouz4dev** [comment]
I think this has been fixed
