### ISSUE TITLE
Can't install last version (5.0.22)

### ISSUE THREAD

**Issue by brnyza** [orkestral/venom#2668]
with this cmd: 
npm i venom-bot@5.0.22

it's returning:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for venom-bot@5.0.22.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by danielvieira43** [comment]
Me neither. Here at github the latest version is 5.0.22 but at npmjs.com shows 5.0.21 • Public • Published 6 months ago

Using 5.0.21:
The event venomClient.onStateChange never been triggered again;
My venom instances are getting the error: ReferenceError: WAPI is not defined;

Someone else stuck with the same issues?

Thanks

**Comment by matheusbsant** [comment]
Same problem here, I started having this problem 2 days ago, since then my code doesn't work. And when trying to install the new version, it generated the same error as you

**Comment by ghayman** [comment]
There has been a flurry of work recently to ensure we have proper support for WhatsApp 2.3.xxxx.
Note: this is still WIP - there are a number of PR still pending

You might want to try installing directly from github for now until next full release is made to npmjs

npm install orkestral/venom

**Comment by TiBrWo** [comment]
@ghayman Thanks!!

**Comment by danielvieira43** [comment]
@ghayman Thank you! Installing directly from github made it work for now.

**Comment by orkestral** [comment]
New Release: `npm i venom-bot@5.1.0`
We have support for Venom for just $15 per month, if you are interested, call our support via the link: https://web.whatsapp.com/send?phone=5561985290357
