### ISSUE TITLE
Error [ReferenceError]: WAPI is not defined

### ISSUE THREAD

**Issue by matheusbsant** [orkestral/venom#2680]
Does anyone have an estimate of when this problem will be resolved? Several people have already opened a call here, I tested all the "supposed" solutions and it didn't help. Could it be an update error? A "bug" in the library? I know that I need this to be resolved as soon as possible, the company I work for depends a lot on this functionality.

**Comment by alxcancado** [comment]
> > Does anyone have an estimate of when this problem will be resolved? Several people have already opened a call here, I tested all the "supposed" solutions and it didn't help. Could it be an update error? A "bug" in the library? I know that I need this to be resolved as soon as possible, the company I work for depends a lot on this functionality.
> 
> Delete the folder "tokens" and try again.

I just did that and does not work

**Comment by farleyBatista** [comment]
Same error here, but it doesn't go beyond the Checking is logged... option.

**Comment by farleyBatista** [comment]
> > O mesmo erro aqui, mas não vai além da opção Verificando está registrado....
> 
> Isso está acontecendo porque a versão do npm Node não está atualizada. Para corrigir isso, use os seguintes comandos:
> 
> 1. npm remove veneno-bot
> 2. npm install --save orkestral/venom
> 
> Isso deve fazer funcionar novamente.

When running the command npm install --save orkestral/venom, it displays the error below:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\farle\AppData\Local\npm-cache\_logs\2024-04-02T22_32_19_228Z-debug-0.log

**Comment by gschneider17** [comment]
Hola, actualizando Node descargandolo desde la pagina oficial volvió a funcionar en mi caso. Espero sirva...

**Comment by dgabriel2334** [comment]
I have a solution for this, it's like a brazilian dialect "gambiarra" but this works

You need install venom via npm with this command "npm install github:orkestral/venom" for the latest (master branch)

Then you need in node_modules path and navigate to venom-bot/controllers/browser.js then comment the line 44.

`require("node-fetch");`

This fix for me!

**Comment by BhagavatiAntala** [comment]
TypeError: Cannot set properties of undefined (setting 'session')
Getting this error on latest script

**Comment by pedro0506** [comment]
> I have a solution for this, it's like a brazilian dialect "gambiarra" but this works
> 
> You need install venom via npm with this command "npm install github:orkestral/venom" for the latest (master branch)
> 
> Then you need in node_modules path and navigate to venom-bot/controllers/browser.js then comment the line 44.
> 
> `require("node-fetch");`
> 
> This fix for me!

Yeees, this work for me! =)

**Comment by dgabriel2334** [comment]
> TypeError: Cannot set properties of undefined (setting 'session') Getting this error on latest script

Try this!
https://github.com/orkestral/venom/issues/2680#issuecomment-2034141883

**Comment by thiagoalvesfoz** [comment]
I was having this same problem

A new release corrected all my problems like `WAPI is not defined` that I was facing in the last few days.

- remove venom-bot
- remove folder tokens/

```bash
npm install venom-bot@5.1.0
```

**Comment by matheusbsant** [comment]
Installing this new version the problem was resolved here too.

**Comment by farleyBatista** [comment]
> ```shell
> npm install venom-bot@5.1.0
> ```

This "gambiarra" worked for me.
