### ISSUE TITLE
ERROR - Full documentation link has 404 error.

### ISSUE THREAD

**Issue by dingkai031** [orkestral/venom#2687]
## Description

Hello I'm new here, and wanted to start development using this library. But it seems that we cannot access the documentation page. Is it just me or..

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. Open https://docs.orkestral.io/venom

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

![image](https://github.com/orkestral/venom/assets/37379472/d4660b69-0b88-4a18-ba37-696bb174910a)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Blira** [comment]
I might be wrong, but theres a chance it's this way for a really long time now...
Honestly, I get a "abandoned project" vibe from venom

**Comment by maico910** [comment]
This problem has been reported for a long time, but it's still unfixed.

Check the answer to my issue.
 https://github.com/orkestral/venom/issues/2406#issuecomment-2034947936

**Comment by tls-jil** [comment]
@maico910 @dingkai031 

Here you will be able to find the Documentation Link

https://htmlpreview.github.io/?https://github.com/orkestral/venom/blob/a3430326eca50122cc5ee5a59453a0c9e4259d49/index.html

**Comment by tls-jil** [comment]
https://github.com/orkestral/venom/issues/2544
