### ISSUE TITLE
ERROR - onAnyMessage don't work on last version 

### ISSUE THREAD

**Issue by PedroPC23** [orkestral/venom#2704]
Just uploaded to the last version and onMessage works but not onAnyMessage, neither sending or receiving.

**Comment by Debanjan-San** [comment]
> Just uploaded to the last version and onMessage works but not onAnyMessage, neither sending or receiving.

facing the same issue which version is working do u know

**Comment by kurybr** [comment]
I have same problem too

**Comment by 9cb14c1ec0** [comment]
I think #2712 might fix this.

**Comment by PedroPC23** [comment]
> I think #2712 might fix this.

Working again with this. Thank you so much 🤠
