### ISSUE TITLE
vcard name that the user received was "You"

### ISSUE THREAD

**Issue by frankeu** [orkestral/venom#273]
I'm trying to send my BOT number using below function to the user. But the vcard name that the user received was "You" not "TryBOT"
**.sendContactVcard('000000000000@c.us', '111111111111@c.us', 'TryBOT')**

**Comment by frankeu** [comment]
![Uploading IMG_20201030_024948.jpg…]()

**Comment by orkestral** [comment]
only send if you have the contact saved in the phonebook
