### ISSUE TITLE
How much long the session can be active once logged in? 

### ISSUE THREAD

**Issue by sahil-patel6** [orkestral/venom#2750]
Once logged in, how long the session will be active? from which method can we know if the session is active or not? I tried isLoggedIn() method but it is returning false even though its active then I tried getConntectionState() is returning "CONNECTED" but when session is not active (meaning forcefully logging out that session from WhatsApp App) it is throwing some error "Error [ReferenceError]: Store is not defined"

**Comment by ghayman** [comment]
Please try installing directly from Github - package is behind in releasing official fixes

npm install orkestral/venom

there was a fix made for isLoggedIn() a few weeks ago
you can expect sessions that are in constant use to stay connected
WhatsApp will automatically log out unused sessions after about 10-14 days (it seems - don't quote me on that)
