### ISSUE TITLE
sendImageAsStickerGif Issue

### ISSUE THREAD

**Issue by kaiserdj** [orkestral/venom#277]
So i try that function and the results are not as expected.
![opt0f410e5fe67a294ec30bbf347a48ad85](https://user-images.githubusercontent.com/5487950/97599159-f906d580-1a07-11eb-921d-0b396c7c3476.gif)
![optbd1bc5c9e40b99d8f9d4021987744c69](https://user-images.githubusercontent.com/5487950/97599162-f99f6c00-1a07-11eb-850a-315ba0ffba40.gif)
Thats the real GIF i want to send.
Android: https://srv-store2.gofile.io/download/VrvkEV/WhatsApp%20Video%202020-10-29%20at%2016.59.06.mp4
![image](https://user-images.githubusercontent.com/5487950/97600038-ed67de80-1a08-11eb-815c-9ec7b708daa9.png)
![image](https://user-images.githubusercontent.com/5487950/97600124-07092600-1a09-11eb-8219-918a9b0a1a65.png)
Pc: https://srv-store2.gofile.io/download/VrvkEV/vrMpBVZHF9.mp4
and that's what i got

**Comment by kaiserdj** [comment]
I think it may be a problem of color palette difference between the .gif and .webp formats, which is the format used by whatsapp

**Comment by kaiserdj** [comment]
Test Sticker from file Webp:
https://srv-store4.gofile.io/download/29MIBn/stickers.mp4
File Gif:
https://srv-store5.gofile.io/download/u33E8S/test.gif
File Webp:
https://srv-store4.gofile.io/download/zIh36x/test.webp

**Comment by fdciabdul** [comment]
you don't need to specify the webp file again , just update the dependency about webp converter , it'll fix your issue tbh

**Comment by kaiserdj** [comment]
You mean venom's webp dependency?

**Comment by Fredwuz** [comment]
I fixed this error I added a color shifted image as the first frame of the gif
InputGif
![InputGif](https://user-images.githubusercontent.com/36505101/97816305-b0178100-1c94-11eb-8bd9-c4146b530442.gif)
firstFrame
![FirstFrame](https://user-images.githubusercontent.com/36505101/97816310-be659d00-1c94-11eb-8777-080d4a2989ab.png)
FinalGif
![FinalGif](https://user-images.githubusercontent.com/36505101/97816318-c3c2e780-1c94-11eb-8825-10c23d509577.gif)
Inside Whatsapp Application
![InsideWhatsapp](https://user-images.githubusercontent.com/36505101/97816385-287e4200-1c95-11eb-8694-d0dbdd5c22cd.gif)
hopped this helped

**Comment by kaiserdj** [comment]
What is the exact change you have made?
I don't get the same result, modifying the first frame

**Comment by Fredwuz** [comment]
this is the first version it works but as it changes only the brightness it only works on darker images and sometimes on light images yeah... this version changes only the brightness 
```javascript
const Jimp = require('jimp')

  await Jimp.read('Sticker/firstframe' + message.from + '.png')
    .then((image) => {
      image.brightness(0.04)
      image.write('Sticker/firstframe' + message.from + '.png')
    })
    .catch((err) => {
      // Handle an exception.
    })
```

this is my second version to do it its a bit clumsy yeah but it works a lot better and almost no transparent squares 
in this version, I change on every pixel every value of Red, Green, and Blue either 5 up or down and this version works a lot better than the above one 
```javascript
const sizeOf = require('image-size')
const Jimp = require('jimp')

  var dimensions = await sizeOf('Sticker/' + message.from + '.gif')
  success = true
  while (success) {
    await Jimp.read('Sticker/firstframe' + message.from + '.png')
      .then((image) => {
        for (let i = 1; i < dimensions.width; i++) {
          for (let j = 1; j < dimensions.height; j++) {
            Sleep(1)
            colors = Jimp.intToRGBA(image.getPixelColor(i, j))
            if (colors.r > 155) {
              colors.r = colors.r - 5
            } else {
              colors.r = colors.r + 5
            }
            if (colors.g > 155) {
              colors.g = colors.g - 5
            } else {
              colors.g = colors.g + 5
            }
            if (colors.b > 155) {
              colors.b = colors.b - 5
            } else {
              colors.b = colors.b + 5
            }
            if (colors.a > 155) {
              colors.a = colors.a - 5
            } else {
              colors.a = colors.a + 5
            }

            hex = Jimp.rgbaToInt(colors.r, colors.g, colors.b, colors.a)

            //     console.log(hex)
            image.setPixelColor(hex, i, j) // sets the colour of that pixel
            success = false
          }
        }
        image.write('Sticker/firstframe' + message.from + '.png')
      })
      .catch((err) => {
        console.log('ERROR: ' + err)
      })
  }

function Sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds))
}

```
