### ISSUE TITLE
WhatsApp have changed their QR code landing page

### ISSUE THREAD

**Issue by ghayman** [orkestral/venom#2818]
The new landing page has different CSS class names and Venom is failing to find the QR code

A fix is in progress...

**Comment by rafaelgit** [comment]
Thank you. I look forward to it.

**Comment by albertpare** [comment]
Thank you

**Comment by 9cb14c1ec0** [comment]
Thanks, @ghayman .   If you need any help, I'm available.

**Comment by ghayman** [comment]
I have the fix done - we were testing this week.
I can post it here tomorrow

**Comment by ghayman** [comment]
Actually I was able to do it now

Please install from venom/master - we still do not have access to npmjs registory

**Comment by ghayman** [comment]
@9cb14c1ec0 did you say that you were still having issues after the fix I posted?
If so, we should take a look. As you can see from the patch, I picked a CSS class selector what seemed to wrap the QA code. But maybe you're seeing different CSS?

**Comment by 9cb14c1ec0** [comment]
The problem was with my deployment process not working.  After fixing that, this issue is resolved for me.
