### ISSUE TITLE
Donations to this recipient aren't supported in this country Trying to make a Donation from India

### ISSUE THREAD

**Issue by lightningfuzion2** [orkestral/venom#2819]
on making a Donation from India.
Donations to this recipient aren't supported in this country.
this is what Paypal says
![image](https://github.com/user-attachments/assets/51588611-e38e-47e1-978c-c17331b498ba)

**Comment by ghayman** [comment]
We appreciate the thought - @jonalan7 has not been active for a while.

There are a couple of us providing some support but no need to donate at this time.

**Comment by jonalan7** [comment]
@lightningfuzion2 
I'm preparing to resume a project I worked on, focused on refactoring Venom. Now, it is more stable and organized than before, and I am already implementing the new changes. If you'd like to take a look, you can visit: [Hydra-bot](https://github.com/jonalan7/Hydra-bot) I will be implementing all the Venom functions with fixes and improvements!
