### ISSUE TITLE
Existe alguma forma de integrar com o dialogflow? Ou alguem consegue me mostrar como faço a função para auto responder mensagens?

### ISSUE THREAD

**Issue by karlosgaldino** [orkestral/venom#286]
Meu projeto tem dois arquivos: sessions.js e index.js

Na sessions trato a utilização do VENON:

`// person.js
'use strict';

const os = require('os');
const fs = require('fs');
const path = require('path');
const venom = require('venom-bot');
const dialogflow = require('@google-cloud/dialogflow').v2beta1;
const uuid = require('uuid');
const { json } = require('express');
const { Session } = require('inspector');

module.exports = class Sessions {

    static async start(sessionName) {
        Sessions.sessions = Sessions.sessions || []; //start array

        var session = Sessions.getSession(sessionName);

        if (session == false) { //create new session
            console.log("session == false");
            session = await Sessions.addSesssion(sessionName);
        } else if (["CLOSED"].includes(session.state)) { //restart session
            console.log("session.state == CLOSED");
            session.state = "STARTING";
            session.status = 'notLogged';
            session.client = Sessions.initSession(sessionName);
            Sessions.setup(sessionName);
        } else if (["CONFLICT", "UNPAIRED", "UNLAUNCHED"].includes(session.state) || ["isLogged"].includes(session.status)) {
            console.log("client.useHere()");
            session.client.then(client => {
                client.useHere();
            });
        } else {
            console.log("session.state: " + session.state);
        }
        return session;
    }//start

    static async addSesssion(sessionName) {
        var newSession = {
            name: sessionName,
            qrcode: false,
            client: false,
            status: 'notLogged',
            state: 'STARTING'
        }
        Sessions.sessions.push(newSession);
        console.log("newSession.state: " + newSession.state);

        //setup session
        newSession.client = Sessions.initSession(sessionName);
        Sessions.setup(sessionName);

        return newSession;
    }//addSession

    static async initSession(sessionName) {
        var session = Sessions.getSession(sessionName);
        const client = await venom.create(
            sessionName,
            (base64Qr) => {
                session.state = "QRCODE";
                session.qrcode = base64Qr;
                console.log("new qrcode updated - session.state: " + session.state);
            },
            (statusFind) => {
                session.status = statusFind;
                console.log("session.status: " + session.status);
            },
            {
                headless: true,
                devtools: false,
                useChrome: false,
                debug: false,
                logQR: false,
                browserArgs: [
                    '--log-level=3',
                    '--no-default-browser-check',
                    '--disable-site-isolation-trials',
                    '--no-experiments',
                    '--ignore-gpu-blacklist',
                    '--ignore-certificate-errors',
                    '--ignore-certificate-errors-spki-list',
                    '--disable-gpu',
                    '--disable-extensions',
                    '--disable-default-apps',
                    '--enable-features=NetworkService',
                    '--disable-setuid-sandbox',
                    '--no-sandbox',
                    // Extras
                    '--disable-webgl',
                    '--disable-threaded-animation',
                    '--disable-threaded-scrolling',
                    '--disable-in-process-stack-traces',
                    '--disable-histogram-customizer',
                    '--disable-gl-extensions',
                    '--disable-composited-antialiasing',
                    '--disable-canvas-aa',
                    '--disable-3d-apis',
                    '--disable-accelerated-2d-canvas',
                    '--disable-accelerated-jpeg-decoding',
                    '--disable-accelerated-mjpeg-decode',
                    '--disable-app-list-dismiss-on-blur',
                    '--disable-accelerated-video-decode',
                ],
                refreshQR: 15000,
                autoClose: 60 * 60 * 24 * 365, //never
                disableSpins: true
            }
        );
        return client;
    }//initSession

    static async setup(sessionName) {
        var session = Sessions.getSession(sessionName);
        await session.client.then(client => {
            client.onStateChange(state => {
                session.state = state;
                console.log("session.state: " + state);
            });//.then((client) => Sessions.startProcess(client));
            client.onMessage((message) => {
                if (message.body === 'hi') {
                    client.sendText(message.from, 'Hello\nfriend!');
                }
            });
        });
    }//setup

    static async closeSession(sessionName) {
        var session = Sessions.getSession(sessionName);
        if (session) { //só adiciona se não existir
            if (session.state != "CLOSED") {
                if (session.client)
                    await session.client.then(async client => {
                        try {
                            await client.close();
                        } catch (error) {
                            console.log("client.close(): " + error.message);
                        }
                        session.state = "CLOSED";
                        session.client = false;
                        console.log("client.close - session.state: " + session.state);
                    });
                return { result: "success", message: "CLOSED" };
            } else {//close
                return { result: "success", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//close

    static getSession(sessionName) {
        var foundSession = false;
        if (Sessions.sessions)
            Sessions.sessions.forEach(session => {
                if (sessionName == session.name) {
                    foundSession = session;
                }
            });
        return foundSession;
    }//getSession

    static getSessions() {
        if (Sessions.sessions) {
            return Sessions.sessions;
        } else {
            return [];
        }
    }//getSessions

    static async getQrcode(sessionName) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            //if (["UNPAIRED", "UNPAIRED_IDLE"].includes(session.state)) {
            if (["UNPAIRED_IDLE"].includes(session.state)) {
                //restart session
                await Sessions.closeSession(sessionName);
                Sessions.start(sessionName);
                return { result: "error", message: session.state };
            } else if (["CLOSED"].includes(session.state)) {
                Sessions.start(sessionName);
                return { result: "error", message: session.state };
            } else { //CONNECTED
                if (session.status != 'isLogged') {
                    return { result: "success", message: session.state, qrcode: session.qrcode };
                } else {
                    return { result: "success", message: session.state };
                }
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    } //getQrcode

    static async sendText(sessionName, number, text) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendText = await session.client.then(async client => {
                    const user = await client.getNumberProfile(number + '@c.us');
                    console.log(user);

                    const messages = await client.getAllUnreadMessages();
                    console.log(messages);                    
                    return await client.sendText(number + '@c.us', 'Olá '+ user.id.user + ' '+ text);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//message

    static async sendLinkPreview(sessionName, number, link, title) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendLinkPreview = await session.client.then(async client => {
                    return await client.sendLinkPreview(number + '@c.us', link, title);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//link

    static async sendLocation(sessionName, number, long, lat, pais) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendLocation = await session.client.then(async client => {
                    return await client.sendLocation(number + '@c.us', long, lat, pais);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//Localização

    static async sendContactVcard(sessionName, number, contact, cname) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendContactVcard = await session.client.then(async client => {
                    return await client.sendContactVcard(number + '@c.us', contact + '@c.us', cname);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//Contato

    static async sendImage(sessionName, number, path, imgname, caption) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultImage = await session.client.then(async client => {
                    return await client.sendImage(number + '@c.us', path,  imgname, caption);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//Imagem

    static async sendFile(sessionName, number, path, filename, caption) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendFile = await session.client.then(async client => {
                    return await client.sendFile(number + '@c.us', path,  filename, caption);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//Documentos

    static async rumSample(projectId,texto){
        const sessionId = uuid.v4();
        const sessionClient = new dialogflow.SessionsClient();
        const sessionPath = sessionClient.projectAgentSessionPath(projectId, sessionId);
        const request = {
            session: sessionPath,
            queryInput: {
                text: {
                    text: texto,
                    languageCode: 'pt-BR',
                },
            },
        };

        const responses = await sessionClient.detectIntent(request);
        console.log('Detected intent');
        const result = responses[0].queryResult;
        console.log(`   Query: ${result.queryText}`);
        console.log(`   Response: ${result.fulfillmentText}`);
        if (result.intent) {
            console.log(`   Intent: ${result.intent.displayName}`);
        } else {
            console.log(`   No intent matched.`);
        }
    }

    /*static async sendFile(sessionName, number, base64Data, fileName, caption) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendFile = await session.client.then(async (client) => {
                    var folderName = fs.mkdtempSync(path.join(os.tmpdir(), session.name + '-'));
                    var filePath = path.join(folderName, fileName);
                    fs.writeFileSync(filePath, base64Data, 'base64');
                    console.log(filePath);
                    return await client.sendFile(number + '@c.us', filePath, fileName, caption);
                });//client.then(
                return { result: "success" };
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//message*/
}`

O index.js chama cada metodo:

`const fs = require('fs');
const https = require('https');
const express = require("express");
const cors = require('cors');
const Sessions = require("./sessions");
require('dotenv').config();
const venom = require('venom-bot');

var app = express();

app.use(cors());
app.use(express.json());

if (process.env.HTTPS == 1) { //with ssl
    https.createServer(
        {
            key: fs.readFileSync(process.env.SSL_KEY_PATH),
            cert: fs.readFileSync(process.env.SSL_CERT_PATH)
        },
        app).listen(process.env.HOST_PORT);
    console.log("Https server running on port " + process.env.HOST_PORT);
} else { //http
    app.listen(process.env.HOST_PORT, () => {
        console.log("Http server running on port " + process.env.HOST_PORT);
    });
}//http

app.get("/start", async (req, res, next) => {
    console.log("starting..." + req.query.sessionName);
    var session = await Sessions.start(req.query.sessionName);

    if (["CONNECTED", "QRCODE", "STARTING"].includes(session.state)) {
        res.status(200).json({ result: 'success', message: session.state });
    } else {
        res.status(200).json({ result: 'error', message: session.state });
    }
});//start

app.get("/qrcode", async (req, res, next) => {
    console.log("qrcode..." + req.query.sessionName);
    var session = Sessions.getSession(req.query.sessionName);

    if (session != false) {
        if (session.status != 'isLogged') {
            if (req.query.image) {
                session.qrcode = session.qrcode.replace('data:image/png;base64,', '');
                const imageBuffer = Buffer.from(session.qrcode, 'base64');
                res.writeHead(200, {
                    'Content-Type': 'image/png',
                    'Content-Length': imageBuffer.length
                });
                res.end(imageBuffer);
            } else {
                res.status(200).json({ result: "success", message: session.state, qrcode: session.qrcode });
            }
        } else {
            res.status(200).json({ result: "error", message: session.state });
        }
    } else {
        res.status(200).json({ result: "error", message: "NOTFOUND" });
    }
});//qrcode

app.post("/sendText", async function sendText(req, res, next) {
    var result = await Sessions.sendText(
        req.body.sessionName,
        req.body.number,
        req.body.text
    );
    //console.log(req.body);
    res.json(result);
});//sendText

app.get("/mensagem", async function(req, res, next) {
    var result = await Sessions.sendText(
        req.query.sessionName,
        req.query.number,
        req.query.text
    );
    res.json(result);
});//mensagem

app.get("/link", async function(req, res, next) {
    var result = await Sessions.sendLinkPreview(
        req.query.sessionName,
        req.query.number,
        req.query.link,
        req.query.title
    );
    res.json(result);
});//enviar link

app.get("/endereco", async function(req, res, next) {
    var result = await Sessions.sendLocation(
        req.query.sessionName,
        req.query.number,
        req.query.long,
        req.query.lat,
        req.query.pais
    );
    res.json(result);
});//enviar Localização

app.get("/contato", async function(req, res, next) {
    var result = await Sessions.sendContactVcard(
        req.query.sessionName,
        req.query.number,
        req.query.contact,
        req.query.cname
    );
    res.json(result);
});//enviar Contato

app.get("/imagem", async function(req, res, next) {
    var result = await Sessions.sendImage(
        req.query.sessionName,
        req.query.number,
        req.query.path,
        req.query.imgname,
        req.query.caption
    );
    res.json(result);
});//enviar Imagem

app.get("/doc", async function(req, res, next) {
    var result = await Sessions.sendFile(
        req.query.sessionName,
        req.query.number,
        req.query.path,
        req.query.filename,
        req.query.caption
    );
    res.json(result);
});//enviar Documento

app.get("/dialog", async function(req, res, next) {
    var project = 'chatbot-bjqupc';
    var result = await Sessions.rumSample(project, req.query.texto);
    res.json(result);
});//dialog

app.post("/sendFile", async (req, res, next) => {
    var result = await Sessions.sendFile(
        req.body.sessionName,
        req.body.number,
        req.body.base64Data,
        req.body.fileName,
        req.body.caption
    );
    res.json(result);
});//sendFile

app.get("/close", async (req, res, next) => {
    var result = await Sessions.closeSession(req.query.sessionName);
    res.json(result);
});//close

process.stdin.resume();//so the program will not close instantly

async function exitHandler(options, exitCode) {
    if (options.cleanup) {
        console.log('cleanup');
        await Sessions.getSessions().forEach(async session => {
            await Sessions.closeSession(session.sessionName);
        });
    }
    if (exitCode || exitCode === 0) {
        console.log(exitCode);
    }

    if (options.exit) {
        process.exit();
    }
} //exitHandler 
//do something when app is closing
process.on('exit', exitHandler.bind(null, { cleanup: true }));
//catches ctrl+c event
process.on('SIGINT', exitHandler.bind(null, { exit: true }));
// catches "kill pid" (for example: nodemon restart)
process.on('SIGUSR1', exitHandler.bind(null, { exit: true }));
process.on('SIGUSR2', exitHandler.bind(null, { exit: true }));
//catches uncaught exceptions
process.on('uncaughtException', exitHandler.bind(null, { exit: true }));`

Quero incluir uma função (ou método) que escute e responda.

**Comment by matheusm821** [comment]
Eu sei que tem aplicativos que mandam mensagens no whatzapp sem abrir o whatzapp tenho um codigo fonte que faz isso mais é em java

**Comment by karlosgaldino** [comment]
Valeu pela resposta @matheusm821. Não sei nada de Java. O Venon tá rodando na minha maquina. Consigo lidar com as funções de envio... falta agora conseguir implementar essa função de escuta para responder mensagens. Posso até conectar ao Client do Dialog flow para node.

**Comment by matheusm821** [comment]
Cara eu queria saber como o aplicativo CINNDI faz para enviar mensagem sem precisar de nenhuma api nem logar nenhum qrcode

**Comment by caugustoschiller** [comment]
Fiz integração com o Dialogflow

```
   await  runSample(geral);
            async function runSample(query) {
                // A unique identifier for the given session
                const sessionId = uuid.v4();

                // Create a new session

                const sessionPath = await sessionClient.projectAgentSessionPath(projectId, sessionId);

                // The text query request.
                const request = {
                    session: sessionPath,
                    queryInput: {
                        text: {
                            // The query to send to the dialogflow agent
                            text: query,
                            // The language used by the client (en-US)
                            languageCode: 'pt-BR',
                        },
                    },

                };


                // Send request and log result
                const responses = await sessionClient.detectIntent(request);
                console.log('Detected intent');


                const result = await responses[0].queryResult;
                console.log(`  Query: ${result.queryText}`);
                console.log(`  Response: ${result.fulfillmentText}`);
                if (result.fulfillmentText) {
                    console.log(`  Intent: ${result.intent.displayName}`);

                    client
                        .sendText(message.from, result.fulfillmentText)
                        .then((result) => {
                            console.log('Result: ', result); //return object success
                        })
                        .catch((erro) => {
                            console.error('Error when sending: ', erro); //return object error
                        });

                } else {
                    console.log(`  No intent matched.`);
                }
            };
```

**Comment by matheusm821** [comment]
No meu caso eu queria criar um apk cpm react native um bot

**Comment by karlosgaldino** [comment]
@caugustoschiller obrigado pela contribuição... meu código está quase igual ao seu... o dialogflow responde se eu eu enviar um texto. Agora precisa saber como integrar isso com a função do Venom que fica ouvindo as mensagens que chegam (tipo um auto responder). Na documentação deles tem um trecho de codigo que não consegui rodar:

`// Listen to messages
client.onMessage(message => {
  ...
})`

**Comment by caugustoschiller** [comment]
Para o caso do meu código ele pega a variável geral e roda a runSample recebendo geral da seguinte maneira:

```
client.onMessage(async (message) => {


        geral = message.body.toLowerCase();

coloca a runSample(geral) aqui dentro e vai funcionar
		}
```
mas vc pode usar ele não recebendo nada apenas runSample() e colocar no lugar da query a variável message

**Comment by karlosgaldino** [comment]
@caugustoschiller cara, estou pecando em algum canto:

sessions.js processa as funções (métodos):

`module.exports = class Sessions {

    static async readMessage(sessionName = 'session1') {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendFile = await session.client.then(async client => {
                    await client.onMessage(async (message) => {
                    	rumSample(message);
                    	console.log(message);
                    })
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }//Recebe msgs

    static async rumSample(){
    	const projectId = 'chatbot-bjqupc';
        const sessionId = uuid.v4(); // ok
        const sessionClient = new dialogflow.SessionsClient();
        const sessionPath = sessionClient.projectAgentSessionPath(projectId, sessionId);//ok
        const request = {
            session: sessionPath,
            queryInput: {
                text: {
                    text: message,
                    languageCode: 'pt-BR',
                },
            },
        };

        const responses = await sessionClient.detectIntent(request);//ok
        console.log('Detected intent');//ok

        const result = responses[0].queryResult;
        console.log(`   Query: ${result.queryText}`);
        console.log(`   Response: ${result.fulfillmentText}`);
        if (result.fulfillmentText) {
            console.log(`   Intent: ${result.intent.displayName}`);
            client
            	.sendText(message.from, result.fulfillmentText)
            	.then((result) => {
            		console.log('Result: ', result);
            	})
            	.catch((erro) => {
            		console.error('Error when sending: ', erro);
            	});
        } else {
            console.log(`   No intent matched.`);
        }
    }
`

no index.js eu tento fazer a chamada na rota /dialog:

`app.get("/dialog", async function(req, res, next) {
    var result = await Sessions.readMessage();
    console.log('chmada da função...');
    res.json(result);
});//dialog`

Não funciona.

**Comment by karlosgaldino** [comment]
@caugustoschiller muito obrigado, consegui resolver com as dicas que me passou. Obrigado mesmo.

**Comment by francisbreit** [comment]
>  await  runSample(geral);
>             async function runSample(query) {
>                 // A unique identifier for the given session
>                 const sessionId = uuid.v4();
> 
>                 // Create a new session
> 
>                 const sessionPath = await sessionClient.projectAgentSessionPath(projectId, sessionId);
> 
>                 // The text query request.
>                 const request = {
>                     session: sessionPath,
>                     queryInput: {
>                         text: {
>                             // The query to send to the dialogflow agent
>                             text: query,
>                             // The language used by the client (en-US)
>                             languageCode: 'pt-BR',
>                         },
>                     },
> 
>                 };
> 
> 
>                 // Send request and log result
>                 const responses = await sessionClient.detectIntent(request);
>                 console.log('Detected intent');
> 
> 
>                 const result = await responses[0].queryResult;
>                 console.log(`  Query: ${result.queryText}`);
>                 console.log(`  Response: ${result.fulfillmentText}`);
>                 if (result.fulfillmentText) {
>                     console.log(`  Intent: ${result.intent.displayName}`);
> 
>                     client
>                         .sendText(message.from, result.fulfillmentText)
>                         .then((result) => {
>                             console.log('Result: ', result); //return object success
>                         })
>                         .catch((erro) => {
>                             console.error('Error when sending: ', erro); //return object error
>                         });
> 
>                 } else {
>                     console.log(`  No intent matched.`);
>                 }
>             };

Muito boas as dicas e eu estou tentando fazer essa integração. Desculpe pela inexperiência com Venom. Esse else que vc disse inserir no Venom, fica em qual arquivo e pasta?
