### ISSUE TITLE
Issue with the QRCode image

### ISSUE THREAD

**Issue by Eider3a** [orkestral/venom#287]
Hi guys, I hope you are doing well.

I have an issue after I generate the QR code as an image. It is generated well in the path that I specified but when I attempt to log in using the QR Code image it doesn't, the WhatsApp account doesn't read the image but when I try to read the code that is generated in the terminal it works well. The generated image seems to have its borders missing. I don't know what's wrong. 

Thank you, let me know if you know how to work it out.

**Comment by tadeubarbosa** [comment]
I was with that same problem sometime ago. To solve that, I wrote a simple html page with a white background and putted the qrcode image with a padding and a single border.

**Comment by Eider3a** [comment]
Thanks buddy for the recommendation, it works like a charm. I just took the generated image and I put it into a website using a white background.

**Comment by Eider3a** [comment]
> I was with that same problem sometime ago. To solve that, I wrote a simple html page with a white background and putted the qrcode image with a padding and a single border.
