### ISSUE TITLE
How to track exceptions

### ISSUE THREAD

**Issue by CyberSinister** [orkestral/venom#29]
**Edit: I forgot to mention that I've never used Node or Express before this, in my life. So please go easy on me.**

Hey!

I am running this program through an API I made in Express. When I call the endpoint with my desired number and message, it should send the message to my desired number. This works fine on my local computer but when I upload this whole code to my server that I want to use it on, It stops working.

When I first upload it to the server, I was getting the messages but they stopped all of a sudden. I tried removing tokens and adding new Whatsapp accounts but that was to no avail. Also, before, my API was returning 200 when everything was working fine but now it returns a 404.

To be specific, here's my route so you have an idea of what I'm talking about:
```
app.get('/sendText/:number/:message', async function (req, res) {
	var number = req.params.number;
	var chatId = number + '@c.us';
	var message = req.params.message	
	
	await client.sendText(chatId, message);

	console.log(chatId)
	console.log(message)

	res.status(200).json({
		number: number,
		chatId: chatId,
	});
});
```
Also, I know there's nothing wrong with my server as it does print the chatId and message in the console when I call the API.

What's going on?

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!

**Comment by CyberSinister** [comment]
Thank you for you reply orkestral but the issue is not third party. The thing is that no messages are being sent from the app. I didn't know anything about NodeJS so I was wondering if it's giving some exception that I'm not seeing
