### ISSUE TITLE
Error no open browsers

### ISSUE THREAD

**Issue by cristianormoraes** [orkestral/venom#290]
root@myvps:~/wzp# node index.js

    ▐█  ██  █░▐█▀▀▀░▐█     ▄█▀▀█▄ ▄█▀▀█▄ ▐██   ██▌ ▓█▀▀▀░
     █▌▐██▄▓█ ▐█▄▄▄ ▐█    ▐█      █▒  ▐█▄▐█▀▌ ▐▌█▌ ▓█▄▄▄
     ▐██ ▐██░ ▐█    ▐█    ▐█▄  ▄▀ █▌  ▐█ ▐█ █▓█ █▌ ██
      ▀▀  ▀▀  ▀▀▀▀▀░▐▀▀▀▀▀  ▀▀▀▀   ▀▀▀▀  ▐▀  ▀  ▀▀ ▀▀▀▀▀
                                   ▄
      ▄▄░          ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄ ██         ▄▄       ▄▄▄▄      ░
      ░██▄        ██ ███▀▀▀▀▀▀▀▀█▌ ███▌       ██▄  ▄▄█▀▀▀▀▀▀█▄   ▓█▄           ▄█░
       ░██▄     ░██▀ ███           ██▀██▄     ██▄ ▄█░        ▀█▄ ▓███▄      ░████░
         ██▌   ▄██░ ▄███▄▄▄▄       ██  ▓██▄   ██▄▐█           ▐█ ▓█▌▀██▄  ▄███░██░
          ██▌ ▄██░  ▀███▀▀▀▀       ██   ▐██▌  ██▄▐█           ▐█░▓█▌  ▀█████░  ██░
           ▓████     ███           ██     ▀██▄██▄ █▌          ██ ▓█▌    ▀█░    ██░
            ▀██      ███        █▌ ██       ▀███▄  ▀█▄     ▄▄█▀  ▓█▌           ██░
             ▀       ▀███████████▌ ██        ░██▄    ▀▀███▀▀░    ▀█▌           ▓█░
                                              ▀░

Chrome not found, using chromium
Error no open browsers
✓ Checking for updates
✖ Error no open browser
root@myvps:~/wzp#

somebody could help me ?

**Comment by thecrux4020** [comment]
same error, using inside docker with chromium

**Comment by mateusbadalotti** [comment]
Same error running on Linux / CentOS 8, chrome is installed on the machine and running, also the same error with chromium option. Any workaround for this issue? Windows is working fine.

**Comment by Wualace** [comment]
Same error running in Heroku

**Comment by lucasscarduelli** [comment]
Same error, running on docker or VPS server!

**Comment by tadeubarbosa** [comment]
I was with that same problem, someone share that code on the group that solve the problem to me:

```javascript
const chromiumArgs = [
  '--disable-web-security', '--no-sandbox', '--disable-web-security',
  '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
  '--disable-offline-load-stale-cache', '--disk-cache-size=0',
  '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
  '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
  '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
  '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'
];

// then put it in your venom create options:
venom.create({
	...
	browserArgs: chromiumArgs,
})
```

**Comment by bergfenix** [comment]
Dont work for me :(

Error no open browser

**Comment by lucasscarduelli** [comment]
Great, it's work to me!!

**Comment by tadeubarbosa** [comment]
> Dont work for me :(
> 
> Error no open browser

Are your Venom in the last version?

**Comment by tadeubarbosa** [comment]
> Dont work for me :(
> 
> Error no open browser

Is your Venom in the last version?

**Comment by mateusbadalotti** [comment]
Creating the app using the following args solved the issue.

`venom.create(
	'session',
	(base64Qrimg, asciiQR, attempts) => {},
	(statusSession, session) => {}, { useChrome: false, browserArgs: ['--no-sandbox'] }
).then((client) => start(client));`

**Comment by antirek** [comment]
Maybe help someone this info 

I build docker image with venom and run it on Ubuntu 14.04 and Ubuntu 18.04
on Ubuntu 14.04 option --no-sandbox isn't required
on Ubuntu 18.04 option --no-sandbox is required
for correct start up

**Comment by cristianormoraes** [comment]
▐█  ██  █░▐█▀▀▀░▐█     ▄█▀▀█▄ ▄█▀▀█▄ ▐██   ██▌ ▓█▀▀▀░
     █▌▐██▄▓█ ▐█▄▄▄ ▐█    ▐█      █▒  ▐█▄▐█▀▌ ▐▌█▌ ▓█▄▄▄
     ▐██ ▐██░ ▐█    ▐█    ▐█▄  ▄▀ █▌  ▐█ ▐█ █▓█ █▌ ██
      ▀▀  ▀▀  ▀▀▀▀▀░▐▀▀▀▀▀  ▀▀▀▀   ▀▀▀▀  ▐▀  ▀  ▀▀ ▀▀▀▀▀
                                   ▄
      ▄▄░          ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄ ██         ▄▄       ▄▄▄▄      ░
      ░██▄        ██ ███▀▀▀▀▀▀▀▀█▌ ███▌       ██▄  ▄▄█▀▀▀▀▀▀█▄   ▓█▄           ▄█░
       ░██▄     ░██▀ ███           ██▀██▄     ██▄ ▄█░        ▀█▄ ▓███▄      ░████░
         ██▌   ▄██░ ▄███▄▄▄▄       ██  ▓██▄   ██▄▐█           ▐█ ▓█▌▀██▄  ▄███░██░
          ██▌ ▄██░  ▀███▀▀▀▀       ██   ▐██▌  ██▄▐█           ▐█░▓█▌  ▀█████░  ██░
           ▓████     ███           ██     ▀██▄██▄ █▌          ██ ▓█▌    ▀█░    ██░
            ▀██      ███        █▌ ██       ▀███▄  ▀█▄     ▄▄█▀  ▓█▌           ██░
             ▀       ▀███████████▌ ██        ░██▄    ▀▀███▀▀░    ▀█▌           ▓█░
                                              ▀░

✓ You're up to date
Chrome not found, using chromium
✖ Error no open browser
(node:107450) UnhandledPromiseRejectionWarning: Error no open browser
(node:107450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:107450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hodevcom** [comment]
I had try centOS 6, centOS 7, Ubuntu 14.04, Ubuntu 18.04 and node.js 12 and 14 in all servers, did not work. 

My server Ubuntu 18.04 with nodejs 12 did not work since 2.0.25 update.

Works on windows server 2012 only.

**Comment by Dhyeythumar** [comment]
Did anyone manage to run venom-bot on Heroku? I am also getting the same error and none of the above solution works.
