### ISSUE TITLE
problem sending an image

### ISSUE THREAD

**Issue by edalicioh** [orkestral/venom#291]
I have a problem, image messages and not returning any error or success

this is my code

 const pathImg = resolve(__dirname, 'upload', 'image.jpg');
    await client
  .sendFile(
    '554896728555@c.us',
   pathImg,
    'image',
    'See my file'
  )
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

**Comment by kaiserdj** [comment]
Surely it is the same problem as: https://github.com/orkestral/venom/issues/289#issue-737115721

**Comment by tadeubarbosa** [comment]
Did you try to put it on a try catch block? Can you do it, please?
