### ISSUE TITLE
Adicionar Bloquear Grupo apenas para admin falar

### ISSUE THREAD

**Issue by gustavoalistic** [orkestral/venom#294]
Por favor, adicionem essa função, seria de muita utilidade para mim e meus colegas.
a função seria de liberar o grupo pra todos falarem ou travar o grupo para apenas adm falar

**Comment by orkestral** [comment]
Amigo nos ajude contribua com 30 Reais que esse final de semana já colocaremos em nossa nova atualização:

https://mpago.la/1Z7uEsp

**Comment by orkestral** [comment]
aliás já colocamos, mais nos ajude
