### ISSUE TITLE
 [Bug] getGroupMembersIds and getGroupMembers throwing error

### ISSUE THREAD

**Issue by adarshmadrecha** [orkestral/venom#296]
As of `v2.0.18`, these functions are not working
* getGroupMembersIds 
* getGroupMembers

**Comment by caugustoschiller** [comment]
they were working
i think whatsapp atualization

**Comment by VincentWo** [comment]
Anyone working on Fixing this? I would love to help, but this codebase kind of overwhelms me :)

**Comment by caugustoschiller** [comment]
lol! kkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by edgardmessias** [comment]
I will working on this issue tomorrow

**Comment by VincentWo** [comment]
Muito obrigado (hope my portugues is correct), really appreciate it!

**Comment by edgardmessias** [comment]
Issued fixed in v2.0.19
