### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by contatodct** [orkestral/venom#3]
Good Morning
I'm not able to install on debian 8 with nodejs already installed ...
please if possible send me a detailed tutorial on how to install and make the basics sound better .. Thanks.

**Comment by contatodct** [comment]
DEBIAN 9.X 64Bits

▗▄ ▄ ▄  ▄▄▄ ▄   ▄▄▄  ▗▄▄▖▗▄▖ ▗▄▖▄▄▄▖
 █▟█▙█  █▄▄ █   █    █ ▐█ █ █ █ █▄▄
 ▐█ █▌  █▄▄ ███ ▜▄▛▘ ▜▙▟▀ █   █ █▄▄▖

▄▄▄▖       ▄▄▄▄▄▄▄▄▄▄▄▟▌▀▖     ▗▄▄▖
▝▄ ▐▖     ▟▘▐         ▐▌ ▝▙    ▐  ▌ ▄▞▀▀▀▀▀▄▖ ▛▀▄        ▄▘▌
 ▝▄ ▐▖   ▐▘ ▟▖ ▜▀▀▀▀▀▌▐▖  ▝▚▖  ▐  ▙▞▘▗▞▀▀▀▚▖▝▙▛ ▝▜▖    ▗▀  ▌
  ▀▖ ▜  ▗▘ ▟█  ▜     ▝▐▌ ▟▖ ▜▖ ▐  █ ▟▘     ▐▖▝█   ▝▙▖▗▞▘   ▌
   ▜▖ ▜▄▛ ▐▜▝  ▝ ▘▜   ▝▌ ▟▀▖ ▝▙▐  ▌▗▌       ▜ ▙ ▐▙▖ ▀▘ ▗▟▘ ▌
    ▚▖ ▀ ▗▌▝▜▖ ▜▀▀▀   ▐▌ ▟ ▝▙  ▜  ▙ ▙       ▛ ▙ ▐▌▝▄  ▟▀▐▘ ▌
     ▚▖ ▗▛  ▐▖ ▜    ▗▛▜▌ ▟   ▚▖   █▖▝▙▖   ▗▛ ▟▛ ▐▖  ▀▞  ▐▖ ▌
     ▝▚▗▛   ▐   ▘▘▘▘▘ ▐▌ ▟    ▀▄  ▌▝▙▖▝▀▀▀▘▗▞▘▛ ▐▌      ▐  ▌
      ▝▛    ▝▀▝▘▘▘▘▘▘▀▝▘▘▀     ▝▙ ▌  ▝▀▘▘▀▀▘  ▀▘▀       ▝▀▝▘
                                 ▚▌


(node:26951) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0610/192643.518545:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by orkestral** [comment]
> DEBIAN 9.X 64Bits
> 
> ▗▄ ▄ ▄ ▄▄▄ ▄ ▄▄▄ ▗▄▄▖▗▄▖ ▗▄▖▄▄▄▖
> █▟█▙█ █▄▄ █ █ █ ▐█ █ █ █ █▄▄
> ▐█ █▌ █▄▄ ███ ▜▄▛▘ ▜▙▟▀ █ █ █▄▄▖
> 
> ▄▄▄▖ ▄▄▄▄▄▄▄▄▄▄▄▟▌▀▖ ▗▄▄▖
> ▝▄ ▐▖ ▟▘▐ ▐▌ ▝▙ ▐ ▌ ▄▞▀▀▀▀▀▄▖ ▛▀▄ ▄▘▌
> ▝▄ ▐▖ ▐▘ ▟▖ ▜▀▀▀▀▀▌▐▖ ▝▚▖ ▐ ▙▞▘▗▞▀▀▀▚▖▝▙▛ ▝▜▖ ▗▀ ▌
> ▀▖ ▜ ▗▘ ▟█ ▜ ▝▐▌ ▟▖ ▜▖ ▐ █ ▟▘ ▐▖▝█ ▝▙▖▗▞▘ ▌
> ▜▖ ▜▄▛ ▐▜▝ ▝ ▘▜ ▝▌ ▟▀▖ ▝▙▐ ▌▗▌ ▜ ▙ ▐▙▖ ▀▘ ▗▟▘ ▌
> ▚▖ ▀ ▗▌▝▜▖ ▜▀▀▀ ▐▌ ▟ ▝▙ ▜ ▙ ▙ ▛ ▙ ▐▌▝▄ ▟▀▐▘ ▌
> ▚▖ ▗▛ ▐▖ ▜ ▗▛▜▌ ▟ ▚▖ █▖▝▙▖ ▗▛ ▟▛ ▐▖ ▀▞ ▐▖ ▌
> ▝▚▗▛ ▐ ▘▘▘▘▘ ▐▌ ▟ ▀▄ ▌▝▙▖▝▀▀▀▘▗▞▘▛ ▐▌ ▐ ▌
> ▝▛ ▝▀▝▘▘▘▘▘▘▀▝▘▘▀ ▝▙ ▌ ▝▀▘▘▀▀▘ ▀▘▀ ▝▀▝▘
> ▚▌
> 
> (node:26951) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
> [0610/192643.518545:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
> 
> ```
> at onClose (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
> at Interface.<anonymous> (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
> at Interface.emit (events.js:327:22)
> at Interface.close (readline.js:424:8)
> at Socket.onend (readline.js:202:10)
> at Socket.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1224:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> ```
> 
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:26951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:26951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Create user for used

**Comment by clebersonjf83** [comment]
cleberson@DESKTOP-5D2R8NV:~/venom$ sudo npm run start

> venom-bot@1.0.0 start /home/cleberson/venom
> npm run build:venom & tsc app.ts && node app.js


> venom-bot@1.0.0 build:venom /home/cleberson/venom
> tsc

error TS6053: File 'app.ts' not found.


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! venom-bot@1.0.0 start: `npm run build:venom & tsc app.ts && node app.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the venom-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cleberson/.npm/_logs/2020-06-11T00_21_24_510Z-debug.log
cleberson@DESKTOP-5D2R8NV:~/venom$

**Comment by orkestral** [comment]
> cleberson@DESKTOP-5D2R8NV:~/venom$ sudo npm run start
> 
> > venom-bot@1.0.0 start /home/cleberson/venom
> > npm run build:venom & tsc app.ts && node app.js
> 
> > venom-bot@1.0.0 build:venom /home/cleberson/venom
> > tsc
> 
> error TS6053: File 'app.ts' not found.
> 
> Found 1 error.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! venom-bot@1.0.0 start: `npm run build:venom & tsc app.ts && node app.js`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the venom-bot@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/cleberson/.npm/_logs/2020-06-11T00_21_24_510Z-debug.log
> cleberson@DESKTOP-5D2R8NV:~/venom$

not run compile, starting for npm install venom-bot

**Comment by clebersonjf83** [comment]
> > cleberson@DESKTOP-5D2R8NV:~/venom$ sudo npm run start
> > > venom-bot@1.0.0 start /home/cleberson/venom
> > > npm run build:venom & tsc app.ts && node app.js
> > 
> > 
> > > venom-bot@1.0.0 build:venom /home/cleberson/venom
> > > tsc
> > 
> > 
> > error TS6053: File 'app.ts' not found.
> > Found 1 error.
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 2
> > npm ERR! venom-bot@1.0.0 start: `npm run build:venom & tsc app.ts && node app.js`
> > npm ERR! Exit status 2
> > npm ERR!
> > npm ERR! Failed at the venom-bot@1.0.0 start script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! /home/cleberson/.npm/_logs/2020-06-11T00_21_24_510Z-debug.log
> > cleberson@DESKTOP-5D2R8NV:~/venom$
> 
> not run compile, starting for npm install venom-bot

cleberson@DESKTOP-5D2R8NV:~$ npm i --save venom-bot
npm WARN saveError ENOENT: no such file or directory, open '/home/cleberson/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/cleberson/package.json'
npm WARN cleberson No description
npm WARN cleberson No repository field.
npm WARN cleberson No README data
npm WARN cleberson No license field.

+ venom-bot@1.0.0
updated 1 package and audited 337 packages in 17.514s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

cleberson@DESKTOP-5D2R8NV:~$ cd venom
cleberson@DESKTOP-5D2R8NV:~/venom$ npm run start

> venom-bot@1.0.0 start /home/cleberson/venom
> npm run build:venom & tsc app.ts && node app.js


> venom-bot@1.0.0 build:venom /home/cleberson/venom
> tsc

error TS6053: File 'app.ts' not found.


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! venom-bot@1.0.0 start: `npm run build:venom & tsc app.ts && node app.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the venom-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cleberson/.npm/_logs/2020-06-11T16_41_23_717Z-debug.log

**Comment by orkestral** [comment]
You are using the venom compiler not to your distances, try taking a javascript or typescript course to learn how to deal with the library, thanks!

**Comment by curruwilla** [comment]
> > DEBIAN 9.X 64Bits
> > ▗▄ ▄ ▄ ▄▄▄ ▄ ▄▄▄ ▗▄▄▖▗▄▖ ▗▄▖▄▄▄▖
> > █▟█▙█ █▄▄ █ █ █ ▐█ █ █ █ █▄▄
> > ▐█ █▌ █▄▄ ███ ▜▄▛▘ ▜▙▟▀ █ █ █▄▄▖
> > ▄▄▄▖ ▄▄▄▄▄▄▄▄▄▄▄▟▌▀▖ ▗▄▄▖
> > ▝▄ ▐▖ ▟▘▐ ▐▌ ▝▙ ▐ ▌ ▄▞▀▀▀▀▀▄▖ ▛▀▄ ▄▘▌
> > ▝▄ ▐▖ ▐▘ ▟▖ ▜▀▀▀▀▀▌▐▖ ▝▚▖ ▐ ▙▞▘▗▞▀▀▀▚▖▝▙▛ ▝▜▖ ▗▀ ▌
> > ▀▖ ▜ ▗▘ ▟█ ▜ ▝▐▌ ▟▖ ▜▖ ▐ █ ▟▘ ▐▖▝█ ▝▙▖▗▞▘ ▌
> > ▜▖ ▜▄▛ ▐▜▝ ▝ ▘▜ ▝▌ ▟▀▖ ▝▙▐ ▌▗▌ ▜ ▙ ▐▙▖ ▀▘ ▗▟▘ ▌
> > ▚▖ ▀ ▗▌▝▜▖ ▜▀▀▀ ▐▌ ▟ ▝▙ ▜ ▙ ▙ ▛ ▙ ▐▌▝▄ ▟▀▐▘ ▌
> > ▚▖ ▗▛ ▐▖ ▜ ▗▛▜▌ ▟ ▚▖ █▖▝▙▖ ▗▛ ▟▛ ▐▖ ▀▞ ▐▖ ▌
> > ▝▚▗▛ ▐ ▘▘▘▘▘ ▐▌ ▟ ▀▄ ▌▝▙▖▝▀▀▀▘▗▞▘▛ ▐▌ ▐ ▌
> > ▝▛ ▝▀▝▘▘▘▘▘▘▀▝▘▘▀ ▝▙ ▌ ▝▀▘▘▀▀▘ ▀▘▀ ▝▀▝▘
> > ▚▌
> > (node:26951) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
> > [0610/192643.518545:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
> > ```
> > at onClose (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
> > at Interface.<anonymous> (/root/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
> > at Interface.emit (events.js:327:22)
> > at Interface.close (readline.js:424:8)
> > at Socket.onend (readline.js:202:10)
> > at Socket.emit (events.js:327:22)
> > at endReadableNT (_stream_readable.js:1224:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)
> > ```
> > 
> > 
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:26951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > (node:26951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Create user for use


I have the same problem, how do I solve it?

I did not understand
