### ISSUE TITLE
we can't get last seen of a contact now

### ISSUE THREAD

**Issue by tadeubarbosa** [orkestral/venom#303]
Theres is some items in the [message interface](https://github.com/orkestral/venom/blob/6ee310c8e46a2c6103f2c65d3a6acc028cc70732/src/api/model/message.ts#L116), that allow us to get the last seen of a contact.

https://github.com/orkestral/venom/blob/6ee310c8e46a2c6103f2c65d3a6acc028cc70732/src/api/model/message.ts#L115-L116

But every time that I try to access, they are `null`.

An example, download the most recent code, create the `onMessage` method. And then try to:

````js
import {Message} from "venom-bot";

client.onMessage((message: Message) => {
    console.log('new message received!');

	console.log('isOnline', message.isOnline); // null
	console.log('lastSeen', message.lastSeen); // null

	console.log('chat.isOnline', message.chat.isOnline); // null
	console.log('chat.lastSeen', message.chat.lastSeen); // null
});
````

**Comment by joaosouz4dev** [comment]
I think this return depends on whatsapp
maybe we can debug this more deeply to see if this is coming as a parameter for the message scope

**Comment by edgardmessias** [comment]
Look:
`isOnline` and `lastSeen` are deprecated.

Use `client.getChatIsOnline()` and `client.getLastSeen()` instead

https://orkestral.github.io/venom/classes/whatsapp.html#getchatisonline
https://orkestral.github.io/venom/classes/whatsapp.html#getlastseen
