### ISSUE TITLE
Gif Sticker working only on WhatsApp Web

### ISSUE THREAD

**Issue by leandrosabatini** [orkestral/venom#305]
I sent a .gif file as sticker and can view on whatsapp web like a normal gif, but on cellphone it seems like a static image.

code:

```
client
    .sendImageAsStickerGif(message.from, './file.gif')
    .catch((erro) => {
        console.error('Error when sending: ', erro);
    })
;
```

**Comment by joaosouz4dev** [comment]
it depends on whatsapp, i think you need to move your finger over the sticker to activate the gif.
