### ISSUE TITLE
BUG - SenderLayer.prototype.sendText --  IPHONE 7 e IPHONE 7 PLUS

### ISSUE THREAD

**Issue by igortrust** [orkestral/venom#306]
Dear,

We have a very particular case here. When using whtasapp businnes on Iphone 7 and Iphone 7 Plus (on android this error does not occur) we have a reject in "Case 1" (line 115 from sender.layer.JS) that generates the following error:

(node:14752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

The **result** variable has this: 
_{
  me: {
    id: "1",
    ref: "1@confidence",
    refTTL: 20000,
    wid: {
      server: "c.us",
      user: "55confidence",
      _serialized: "5579confidence@c.us",
    },
    connected: true,
    protoVersion: [
      0,
      17,
    ],
    clientToken: "confidence",
    serverToken: "confidence",
    isResponse: "true",
    battery: 47,
    plugged: false,
    lc: "BR",
    lg: "pt",
    locales: "pt-BR",
    is24h: true,
    platform: "smbi",
    phone: {
      wa_version: "2.20.120.21",
      mcc: "724",
      mnc: "002",
      os_version: "14.1",
      device_manufacturer: "Apple",
      device_model: "iPhone 7 Plus",
      os_build_number: "undefined",
    },
    tos: 0,
    smbTos: 0,
    pushname: "confidence",
    blockStoreAdds: false,
  },
  to: "status@broadcast",
  erro: true,
  text: "The number does not exist",
  status: 404,
}_

I was unable to identify what causes this error.
I know it's not the best way to solve it, but.... I took the reject (result) while I can't find a solution .
can you help me?

**Comment by joaosouz4dev** [comment]
try using the new versions if the error happens again create a new issue please
