### ISSUE TITLE
Not Login

### ISSUE THREAD

**Issue by Wualace** [orkestral/venom#308]
Hello!
Currently I am trying to deploy the bot on a VPS instance but i am getting the following log in console:

✓ Checking for updates
✖ Not Login
✓ headless option is active, browser hidden
✓ the autoClose function is on
✖ Session Autoclose Called
Error in login

My VPS:
- Ubuntu 18.04
- Node 14.15.0
- Npm 6.14.8
- Venom 2.0.18

Please help me how can I solve this??

**Comment by joaosouz4dev** [comment]
try to use new versions and check if your environment supports our dependencies
