### ISSUE TITLE
Error on sendText

### ISSUE THREAD

**Issue by brgomes** [orkestral/venom#309]
(node:18049) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Object.window.WAPI.getchatId (/home/bruno/www/estudos/whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:32278)
    at async Object.window.WAPI.sendMessage (/home/bruno/www/estudos/whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:39096)
    at ExecutionContext._evaluateInternal (/home/bruno/www/estudos/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/bruno/www/estudos/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joaosouz4dev** [comment]
whats version u are using?

**Comment by brgomes** [comment]
Versão 2.0.18

**Comment by igortrust** [comment]
The same is happening here #306 
I gave a bypass to avoid closing the venom.



> (node:18049) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
> at Function.assign ()
> at Object.window.WAPI.getchatId (/home/bruno/www/estudos/whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:32278)
> at async Object.window.WAPI.sendMessage (/home/bruno/www/estudos/whatsapp/node_modules/venom-bot/dist/lib/wapi/wapi.js:8:39096)
> at ExecutionContext._evaluateInternal (/home/bruno/www/estudos/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async ExecutionContext.evaluate (/home/bruno/www/estudos/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:18049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:18049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by joaosouz4dev** [comment]
try using the new versions if the error persists please create an issue again
