### ISSUE TITLE
Error emoji

### ISSUE THREAD

**Issue by mikelustosa** [orkestral/venom#311]
![image](https://user-images.githubusercontent.com/45069559/99076007-31c2b500-2599-11eb-8535-272cb9706a2e.png)

Someone with an emoji error?

**Comment by edgardmessias** [comment]
@mikelustosa , could you provide a source code for reproduce?

**Comment by mikelustosa** [comment]
> @mikelustosa , você poderia fornecer um código-fonte para reprodução?

https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js

**Comment by edgardmessias** [comment]
@mikelustosa , could you provide a short script to reproduce this issue? Like a string with message
Don't post source from another project.

**Comment by joaosouz4dev** [comment]
I believe that this error may be due to the way of sending the emoji, we cannot help improve your code, I can guarantee that venom sends emoji without problems, as I personally tested this function.
