### ISSUE TITLE
Specify timeout o send functions

### ISSUE THREAD

**Issue by LucasPonzo** [orkestral/venom#314]
When device is not connected, send functions doesn't returns until connected again. It's a good idea do pass an options object specifing a timeout (or at least a timeout parameter), If timeout threshold is reached the function throws the proper error to the caller. 

Another interesting option is to be possible to determine if the function will try to send the message once connected again.

**Comment by leobevi** [comment]
@LucasPonzo 
As an alternative you can use the 
status = await client.getConnectionState ();
console.log (status);

This will return the status of your connection

**Comment by joaosouz4dev** [comment]
this needs to be addressed in your application, there are many ways to do this and we will soon be posting a safe example of how to do this.

**Comment by Sp0derDev** [comment]
I'm having the same issue here. Trying to find an optimal solution to handle this.
