### ISSUE TITLE
Version 1.0.5 has no dist folder

### ISSUE THREAD

**Issue by acristoffers** [orkestral/venom#32]
After `npm i venom-bot`, there is no node_modules/venom-bot/dist. All the READMEs are there, only the dist folder is missing.

**Comment by israelfontes** [comment]
i'm experiencing the same problem...

**Comment by orkestral** [comment]
Sorry for what happened, we are upgrading to version 1.0.6 with the correction of the problem, in about 30 minutes, Thanks!

**Comment by kingaspx** [comment]
Just download the project and run npm build, here it is working 100%.

**thanks for the project.**
