### ISSUE TITLE
How get actual QR code?

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#327]
I start instance of venom. But authorize whatsapp later, some hours later, for example. QR code (which I saved on start) is expired already. 

Can I use retrieveQR in my instance for get actual QR code at this moment without restart instance of venom?

**Comment by tadeubarbosa** [comment]
Using that example: https://github.com/orkestral/venom/blob/master/docs/about.md#exporting-qr-code
After saving the qrcode to an file, it will be ready to be read.
If you are using some socket, you can refresh the page with the qrcode every time that the qrcode will be refreshed. Or if you have just a html file, you can use a meta in your html: https://www.w3schools.com/tags/att_meta_http_equiv.asp


```javascript
require('fs').writeFile('out.png', imageBuffer['data'], 'binary', function (err) {
  if (err != null) {
    console.log(err);
  }
});
```

**Comment by joaosouz4dev** [comment]
I believe that the answer of @tadeubarbosa  already helps in your doubt.

**Comment by antirek** [comment]
Ok, thanks. 
If use autoClose=0, qr code will be update forever. And using callback I can update out.png with actual qr code and pass it by request.
