### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by kingaspx** [orkestral/venom#34]
Há algum jeito de fazer um chatbot com essa API? Eu estou tentando algo bem básico, mas sem sucesso...

Exemplo:

```js
 await client.onMessage((message) => {
        io.emit('message-received', message)

        if (message.body.toLowerCase().includes('olá')) {
            var textArray = [ //random message
                `Olá, tudo bem? 
                Digite 1 para pegar a 2ª via do seu boleto ou
                Digite 2 para verificar suas pendências`,

                `Seja bem vindo!! 
                Digite 1 para pegar a 2ª via do seu boleto ou
                Digite 2 para verificar suas pendências`,
            ]

            var i = Math.floor(Math.random() * textArray.length)
            client.sendText(message.from, textArray[i]);

        } else if (message.body === '1' || message.body === 1) { //choice 1
            client.sendText(message.from, `Certo, você escolheu: *2ª via do boleto.*, você quer para este mês mesmo? Diga *sim* ou *não*`);
        } else if (message.body === '2') { //choice 2
            client.sendText(message.from, `Certo, aguarde um instante, estou verificando...`);
        }
```

Assim ele até funciona, mas quando chega na parte do "sim" ou "não" não tem o que ser feito, já que só da pra adicionar uma instancia de `onMessage`

Valeu!

**Comment by orkestral** [comment]
Precisa sacar de GPU accelerated Neural Networks with Brain.js, aqui só corrigimos bugs do repo, mais da para fazer muita coisa com Venom. Obrigado e sucesso!

**Comment by kingaspx** [comment]
Valeu!! Tem algum modo de eu entrar em contato com você no particular? Estou com um projeto bem legal usando sua API!

**Comment by karlosgaldino** [comment]
Olá @kingaspx poderia me dar uma dica de como fazer esta parte de ler mensagens de entrada e responder? Só o básico mesmo, sem if ou qualquer checagem. Tipo, qualquer mensagem que chegar responda com 'xpt.o'. Podes me dar uma direção?

**Comment by kingaspx** [comment]
Opa @karlosgaldino, blz?

```
 await client.onMessage((message) => { //aqui ele fica escutando as mensagens que vão chegar
     client.sendText(message.from, `xpt.o`); //aqui ele responde com: xpt.o
 }
```

**Comment by calebetadeu** [comment]
Da pra enviar pra mais de 1 contato?
