### ISSUE TITLE
Métodos e atributos sem tipagem

### ISSUE THREAD

**Issue by GuilhermeCunha** [orkestral/venom#340]
As funções ou atributos abaixo ou não tem tipagem, ou estão com tipagem insuficiente.

**_/api/layers/business.layer.d.ts_**

- [ ]  getBusinessProfilesProducts
- [ ]  sendImageWithProduct

**_/api/layers/controls.layer.d.ts_**

- [ ] pinChat
- [ ] clearChat
- [ ] deleteMessage

**_/api/layers/group.layer.d.ts_**

- [ ] leaveGroup

**_/api/layers/listener.layer.d.ts_**

- [ ] onAddedToGroup
- [ ] onIncomingCall

**_/api/layers/profile.layer.d.ts_**

- [ ] sendMute

**_/api/layers/retriever.layer.d.ts_**

- [ ] getListMutes
- [x] getSessionTokenBrowser
- [x] checkNumberStatus
- [ ] getUnreadMessages
- [ ] getAllNewMessages

**_/api/layers/sender.layer.d.ts_**

- [ ] sendLinkPreview
- [x] sendText
- [x] sendMessageOptions
- [ ] sendImage
- [ ] sendImageFromBase64
- [x] reply
- [ ] sendFileFromBase64
- [ ] sendFile
- [ ] sendContactVcard
- [ ] sendContactVcardList
- [ ] forwardMessages
- [ ] sendImageAsStickerGif
- [ ] sendImageAsSticker
- [ ] sendLocation

**_/controllers/initializer.d.ts_**

- [ ] create

**Comment by edgardmessias** [comment]
@GuilhermeCunha , poderia atualizar esse issue com o que falta?
