### ISSUE TITLE
Venom throws error on auth

### ISSUE THREAD

**Issue by effer89** [orkestral/venom#341]
On starting a new session, it can't log in on whats:
It throws:

![image](https://user-images.githubusercontent.com/13169985/99706070-50351e80-2a79-11eb-8e78-1e5d574476f8.png)

Any ideas?

Thanks!

venom-bot: 2.0.21

**Comment by danireginatto** [comment]
+1

**Comment by edgardmessias** [comment]
Try with venom-bot: 2.0.22
