### ISSUE TITLE
Problemas ao receber mensagens

### ISSUE THREAD

**Issue by tchelocabral** [orkestral/venom#347]
Temos um problema para receber as mensagens.
Elas não passam pelo venom. 

O envio de mensagem está ok, fizemos testes e as mensagens são enviadas perfeitamente.
Porém as respostas dos contatos não passam pelo venom nem aparece nada nos logs.
Um contato envia mensagem ao número, porém, nem aparece nos logs do venom.
Se eu envio uma msg usando o venom, passa lindamente pelo log e o contato recebe.

Ontem estava ok o processo, mas hoje parou de funcionar.
Atualizamos a versão do venom e conferimos as versões do node, tudo ok.

O código que estamos usando é:

```

client.onMessage((message) => {
      console.log("message", message);
      let msg = format(message);
      if (message.isGroupMsg === false) {
        axios
          .post("http://localhost/api/zap", msg)
          .then(function (response) {
            console.log("response", response);
          })
          .catch(function (error) {
            console.log(error);
          });
      }
    });

```
Estamos usando:
Node: 14.15.1
Venom: 2.0.22

**Comment by joaosouz4dev** [comment]
it's working perfectly, I believe that somehow you may be calling the customer the wrong way, maybe.
Try to replicate the basic code to test your application
