### ISSUE TITLE
How do I stop hearing the "onMessage" event? help me

### ISSUE THREAD

**Issue by GhostWolf95** [orkestral/venom#349]

**Comment by joaosouz4dev** [comment]
remove the function from your code, does that solve?

**Comment by edgardmessias** [comment]
I will work to rework the event manager

**Comment by edgardmessias** [comment]
now onMessage return a object with dispose method, example:
```javascript
var r = client.onMessage(...);

r.disponse(); // Stop listening
```

**Comment by SyedSaifAli** [comment]
after calling `dispose()`, still getting messages. How to stop listening to onMessage? @edgardmessias

**Comment by SyedSaifAli** [comment]
> now onMessage return a object with dispose method, example:
> 
> ```js
> var r = client.onMessage(...);
> 
> r.disponse(); // Stop listening
> ```
after calling dispose(), still getting messages. How to stop listening to onMessage? @edgardmessias

**Comment by edgardmessias** [comment]
Sorry @SyedSaifAli , I'm not working with venom anymore, I started a fork of that and is working: https://github.com/wppconnect-team/wppconnect

**Comment by SyedSaifAli** [comment]
> Sorry @SyedSaifAli , I'm not working with venom anymore, I started a fork of that and is working: https://github.com/wppconnect-team/wppconnect

Oh, okay. not a problem :)
Can you just tell us whether `dispose` is working in this fork which you shared?
Thank you.

**Comment by edgardmessias** [comment]
@SyedSaifAli , yes, is working like a charm

**Comment by SyedSaifAli** [comment]
> @SyedSaifAli , yes, is working like a charm

Hey @edgardmessias, I tried this library too https://github.com/wppconnect-team/wppconnect and it seems like its not working also there. :/

**Comment by edgardmessias** [comment]
@SyedSaifAli , first open a issue in the correct repository

**Comment by SyedSaifAli** [comment]
@edgardmessias Done.
