### ISSUE TITLE
How to capture media messages

### ISSUE THREAD

**Issue by VyTorBrB** [orkestral/venom#352]
The .onMessage() method works fine however when i receive media (docs, images) that property "body" is the base64 variant, the problem is that i cant download the file, it comes encrypted, im just finding trouble in dealing with this type of message.

**Comment by Fredwuz** [comment]
Just use 
```js
  if (message.isMedia === true || message.isMMS === true) {
    const buffer = await client.decryptFile(message);
    // At this point you can do whatever you want with the buffer
    // Most likely you want to write it into a file
    const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
    await fs.writeFile(fileName, buffer, (err) => {
      ...
    });
```
as it stands in the readme for downloading files
https://github.com/orkestral/venom#downloading-files
