### ISSUE TITLE
Retornar o código do qrcode além da imagem

### ISSUE THREAD

**Issue by tomsilva** [orkestral/venom#355]
Oi a todos, gostaria de saber se e possivel que em vez de trazer o base64 da imagem trazer direto o qrcode no metodo.

o qrcode esta na tag    " _1yHR2 UlvkP" do navegador, 

https://prnt.sc/vp9mxh

segue o link

**Comment by edgardmessias** [comment]
Em vez de substituir, vou adicionar esse valor no retorno como o quarto parâmetro da função.
