### ISSUE TITLE
Sticker not sending , please see the errors in the attached image

### ISSUE THREAD

**Issue by ramz30011** [orkestral/venom#356]
![Screen Shot 2020-11-25 at 6 11 00 PM](https://user-images.githubusercontent.com/62383141/100253436-c9d17e80-2f49-11eb-8ffb-444b31b6a8a5.png)

**Comment by joaosouz4dev** [comment]
what version of whatsapp and venom are you on?

**Comment by ramz30011** [comment]
i am not using venom directly, i am using your WAPI file in browser directly for testing before using venom. would this affect it ? if yes can you please guide me so that i can trace it please ?

**Comment by joaosouz4dev** [comment]
sticker here works, I don't know how you only use wapi, but I think you made a code with some error
