### ISSUE TITLE
Download ppt (push to talk)

### ISSUE THREAD

**Issue by antonio-couto** [orkestral/venom#36]
I already sent this issue, the download file function cannot download ppt audio if testing the flag "message.isMedia" I need always to comment. Below the code, I got the last version and still that way,
thanks in advance.

 /**
   * Decrypts message file
   * @param message Message object
   * @returns Decrypted file buffer (null otherwise)
   */
  public async downloadFile(message: Message) {
    //if (message.isMedia) {
      const url = message.clientUrl;
      const encBase64 = await this.page.evaluate((url: string) => {
        return fetch(url)
          .then((response) => response.arrayBuffer())
          .then((bytes) => WAPI.arrayBufferToBase64(bytes));
      }, url);

      return decrypt(encBase64, message);
    //} else {
    //  return null;
    //}
  }
}

**Comment by orkestral** [comment]
we are working to fix this problem

**Comment by antonio-couto** [comment]
I made a modification on my code and works, i am just set message.is Media = true, so the download function works,
I think is not the case to modify this function, just to put on documentation.

    if (message.type == 'ptt') {
      message.isMedia = true;
    }
    const buffer = await globalClient.downloadFile(message);

thanks.
