### ISSUE TITLE
pergunta: a função business sendButtons funciona ?

### ISSUE THREAD

**Issue by marcelocecin** [orkestral/venom#364]
bom dia prezados
a função business sendButtons está funcionando ?
poderiam dar um exemplo de como utilizar ?
muito obrigado !

**Comment by MarToxAk** [comment]
Boa Noite a onde esta localizado essa função... Eu dei uma olhada na documentação e não encontrei

**Comment by marcelocecin** [comment]
bom dia
está nesse código [aqui](https://github.com/orkestral/venom/blob/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/lib/wapi/business/send-message-with-buttons.js)
se puder testar, não tenho conta Business para fazer o teste
obrigado

**Comment by marcelocecin** [comment]
bom dia, acho que o método `Store.bp` parou de funcionar no `WA_VERSION 2.2049.8`
