### ISSUE TITLE
Venom is timing out after 24 hours

### ISSUE THREAD

**Issue by lordtottuu** [orkestral/venom#37]
I'm using Venom to run a chatbot. Everything works perfectly but after 24 hours, Venom shows a time out message and after restarting, it's stuck on "authenticating".

If I delete the 'tokens' directory and try again, I have to rescan the QR and it starts working again. 

Is there a way to watch the _'TIMEOUT'_ event and reconnect, without having to scan the QR each time? Or is it a limitation with Whatsapp web that we'll have to reauth with a QR every 24 hours?

**Comment by orkestral** [comment]
After several tests no problems found

**Comment by lordtottuu** [comment]
Sorry about talking about the same topic but is there a way to capture the timeout event and force a signin or at least raise an alert? It timed out two more times but then has been running rock solid for 3 days. 

I understand this is probably due to internet or connectivity issues with the host phone that Whatsapp is on but given this is an important part of our infrastructure, would like to know if there are options within Venom instead of manually sending a ping pong message every minute and checking for a response.

Thanks again for your patience!
