### ISSUE TITLE
Error sendFile

### ISSUE THREAD

**Issue by borellaster** [orkestral/venom#370]
I got this error and I couldn't resolve it

`erro: true,
  text: 'test',
  status: '',
  type: 'FileFromBase64',
  filename: 'a.pdf',
  mimeType: 'application/pdf'`

I am using this code

`await client.sendFile(number + '@c.us', filePath, fileName, caption);`

I try to sendBase64 too, but I got the same error.

Someone can help me?

**Comment by edgardmessias** [comment]
Could you provide a example file?

**Comment by borellaster** [comment]
> Could you provide a example file?

Agora que vi que é do brasil.

Me basiei nesse link. o sendText funciona perfeitamente

https://github.com/billbarsch/myzap/blob/master/sessions.js#L211


Felipe

**Comment by borellaster** [comment]
> Could you provide a example file?

A Api escreve o PDF temporario na pasta certo, porem na hora de enviar não tem jeito.

Retorna isso e eu não consigo passar adiante

  erro: true,
  text: 'oi',
  status: '',
  type: 'FileFromBase64',
  filename: 'a.pdf',
  mimeType: 'application/pdf'

**Comment by edgardmessias** [comment]
Certo, mas teria como você anexar o PDF aqui? Para tentar reproduzir o mesmo?

**Comment by borellaster** [comment]
> Certo, mas teria como você anexar o PDF aqui? Para tentar reproduzir o mesmo?

Segue o PDF. Trata-se de um PDF bem simples.



[a.pdf](https://github.com/orkestral/venom/files/5616222/a.pdf)

**Comment by borellaster** [comment]
Eu tentei tudo quanto foi codigo, e caio sempre no mesmo erro.

Você tem algum codigo funcional  que envie PDF?

Estou usando a v2.0.27

Felipe

**Comment by edgardmessias** [comment]
Poderia passar como você está fazendo a chamada, fiz vários testes aqui não consegui reproduzir o problema ainda.

**Comment by borellaster** [comment]
mando um post para http://localhost:4002/sendFile  (ele esta rodando na porta 4002)

`"sessionName": "nomeDaSessao",
 "number": "54xxxxx",
 "base64Data": "string de base 64",
 "fileName": "a.pdf",
 "caption": "oi"`

**Comment by edgardmessias** [comment]
Você está usando o "https://github.com/billbarsch/myzap"?  Certeza que está a versão correta do Venom?

**Comment by borellaster** [comment]
Eu atualizei para a ultima versao, como lhe falei, a mensagem de texto envia.

Mas se voce tiver um projeto (mesmo que bem basico) que envie o PDF, por favor compartilhe comigo. Ja tentei varios outros projetos do zero e caio sempre no mesmo erro, simplesmente nao envia, nem arquivo e nem imagem.

Felipe

**Comment by borellaster** [comment]
Eu olhei no exemplos do projeto, e não tem nenhum que auxilie enviar um arquivo, seja ele PDF ou outro tipo

Você tem algum projeto ai para que eu possa me guiar?
Estou esgotando alternativas

Felipe

**Comment by borellaster** [comment]
Bom dia,

não consegui, gostaria de usar essa biblioteca, mas não estou conseguindo, seguindo a documentação parece muito facil, porem não funciona. Volto a pedir, você tem algum projeto ou arquivo que funcione o envio de um PDF ou Imagem?

Felipe

**Comment by edgardmessias** [comment]
Estamos investigando o que pode estar ocorrendo, acredito que possa ser um problema com o número de contato que você está tentando enviar, certeza que está no formato `5500000000@c.us`?
Tente fazer teste com e sem o nono dígito por favor.

**Comment by borellaster** [comment]
Cara realmente é o nono digito, acredito que deveriam ajustar, pois muita gente vai passar por este problema.

Obrigado.

**Comment by edgardmessias** [comment]
Está na lista de ajustes, não somente para essa chamada.
