### ISSUE TITLE
About "client.onLiveLocation"

### ISSUE THREAD

**Issue by MarToxAk** [orkestral/venom#376]
I'm testing Venom-Bot, and I'm not very experienced in nodejs and javascript.
I haven't had many difficulties so far, except with the events of **"client.onLiveLocation"**, I'm testing it and it doesn't return any value nor does it go through it. could someone help me.

I used this code as a test.

```
client.onLiveLocation ('chatId', (liveLocation) => {
             console.log('test')
             console.log(liveLocation)
           });
```
in **chatId** put the number I'm trying to get the values.

**Comment by orkestral** [comment]
fixed in version 3.0.5

**Comment by Dlbraganca** [comment]
I'm using the current version 3.0.16 and i had this same issue that client.onLiveLocation doesn't return any value. I tried to downgrade to the version 3.0.5 and it did not work either.

**Comment by danfra** [comment]
Hi There! I'm using the verfsion 4.0.3 and also had the same issue. Someone have an idea about this?  In others WhatsApp APIs, I had received lat and long  data without any problem
