### ISSUE TITLE
Doesn't download image

### ISSUE THREAD

**Issue by DanielJ06** [orkestral/venom#378]
```
if (msg.isMedia == true || msg.isMMS == true) {
            try {
              const buffer = await client.decryptFile(msg); 
              let base64data = Buffer.from(buffer).toString('base64');
              let imagebase64 = 'data:'+msg.mimetype+';base64,'+base64data;
              ... send base 64 to react
          } catch (err) {
             console.log(err)
         }
}
```

return: `Error trying to download the file.`

**Comment by MarToxAk** [comment]
Are you trying to save the files? if so, the save function is missing. and also to save it has to be in binary and the variable Buffer.
If you want Base64, the message.body function is already formatted.
```
if (message.isMedia === true || message.isMMS === true) {
                const buffer = await client.decryptFile(message);
                //Media in Base64
                console.log(message.body)
                const fileName = `media_folder/file_name.${mime.extension(message.mimetype)}`;
                await fs.writeFile(fileName, buffer, (err) => {
                });
            }
```

**Comment by DanielJ06** [comment]
Hello, I just want to display it as an <img /> tag in React Js, but passing the Base64 of the message.body, the image is VERY small, and with a horrible quality, so I tried to do it that way, but doesn't works :/

**Comment by DanielJ06** [comment]
![Capturar](https://user-images.githubusercontent.com/56522385/100936614-8ee2c400-34d0-11eb-81d4-cab4130874d7.PNG)

Result with Base64 from message.body

**Comment by MarToxAk** [comment]
esqueceu de coloca 'hex'
new code >>
`let base64data = Buffer.from(buffer, 'hex').toString('base64');`

**Comment by DanielJ06** [comment]
Same low quality on React 😞 @MarToxAk

**Comment by MarToxAk** [comment]
@DanielJ06 Você é brasileiro né, então vamos conversa em portugues...
Você esta tentando implementa para ser renviado no sendFile por Base64? ou esta tentando carregar no corpo do HTML ?

**Comment by DanielJ06** [comment]
Opa, melhor. Então, no meu server side eu tenho uma estrutura com socket.io e venom. Nos eventos de onMessage eu emito o conteúdo da mensagem e recebo no meu frontend(React), com mensagens tipo chat o funcionamento está excelente, mas coloquei uma validação pra caso o type seja "image", renderizar uma imagem com o base64 vindo do message.body, e de fato dá pra ver que é a imagem recebida mesmo, porém, com uma qualidade horrível. Por enquanto só quero implementar a visualização de imagens recebidas,  e consequentemente implementar o envio de mídias também

**Comment by MarToxAk** [comment]
Então em todos os meu testes o download deram certo inclusive no site doc do React... Quando você salva na maquina fica com a resolução ruim ou ele fica boa ?
![Captura de tela 2020-12-03 101444](https://user-images.githubusercontent.com/8673366/101022630-64d0e680-3550-11eb-84eb-59520af94755.png)

**Comment by DanielJ06** [comment]
Na real ele nem baixando está: 
![Capturar](https://user-images.githubusercontent.com/56522385/101025341-3228ed00-3554-11eb-9067-fc606c66980e.PNG)

Na hora de renderizar no react eu estava passando o message.body, e estava bem embaçada igual ao preview que mandei ali em cima, por isso estou tentando essa alternativa

**Comment by MarToxAk** [comment]
Faz o seguinte, apaga a pasta node_modules e da npm -i e vê se soluciona.

**Comment by DanielJ06** [comment]
```
const buffer = await client.decryptFile(msg); 
let base64data = Buffer.from(buffer, 'hex').toString('base64');
```
Aparentemente o erro tá nesse trecho, pois mesmo sem colocar pra gerar ele cai no catch. E não, não resolveu apagar a node_modules e instalar dnv

**Comment by dmonteirosouza** [comment]
@DanielJ06 Também estou tendo o mesmo problema aqui #383 . No meu caso, no onMessage está funcionando perfeitamente, eu envio ele com o axios. No entanto, estou tentando fazer a mesma coisa com o loadAndGetAllMessagesInChat, e converter a imagem, mas nesse caso, não funciona.

**Comment by DanielJ06** [comment]
Consegui resolver. Eu rodava o venom em um módulo desktop com electron, resolvi testar ele só pela cli e por mais estranho que pareça, funcionou perfeitamente

**Comment by edgardmessias** [comment]
Install nightly release and try use `client.downloadMedia(messageId)`, it will return a base64 string
