### ISSUE TITLE
checking phone status

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#379]
How I can receive actual status of phone, offline/online?

If I understand right that mobile phone with whatsapp app must be online and whatsap web instance (venom) running. 

Mobile phone may be sometimes offline. If mobile phone offline I can catch changeState event via client.onStateChange? Ok.

But state don't change when mobile phone set offline. But if I send outgoing message via whatsapp web instance (venom) I receive state = TIMEOUT. And when mobile phone set online I receive state = CONNECTED. 

And when I send incoming message to whatsapp, whatsapp web instance (venom) also don't know that mobile phone is offline and don't fire any event about it.

**Comment by edgaru** [comment]
Same problem,  steps to reproduce:

1. Start session.
2. Turn off the internet on the phone.
3. Check device status (it return CONNECTED)
4. Send a message(State change to TIMEOUT on onStateChange)
4. Message marked as sent, but waiting for connection.

**Comment by edgardmessias** [comment]
It is a whatsapp web interface problem, there is a delay between check the current state.
