### ISSUE TITLE
Is there a way to check if I'm sending a message?

### ISSUE THREAD

**Issue by jonalan7** [orkestral/venom#38]
**I know there is a way to check if the customer has sent a message!**

client.onMessage((message) => { ... });

**Is there the reverse?** 

**Check for example if I send a message by cell phone!**
**With the same authenticated**

**Comment by pmlnunes** [comment]
Would also like to know if this is possible.

**Comment by pmlnunes** [comment]
I found it, you can use the `client.onAnyMessage(...`

**Comment by jonalan7** [comment]
> Eu achei, você pode usar o `client.onAnyMessage(...`

Very good! You are the man!!!
