### ISSUE TITLE
sendImageAsSticker() returns undefined

### ISSUE THREAD

**Issue by vigsoft410** [orkestral/venom#380]
`result` returns `undefined`, how can I fix it? It's something wrong?
```
await client
    .sendImageAsSticker('000000000000@c.us', './image.jpg').then((result) => {
        console.log('Result: ', result); //return object success
    }).catch((erro) => {
        console.error('Error when sending: ', erro); //return object error
    });
```
:brazil:

**Comment by vigsoft410** [comment]
This is the full function:
```
client.onMessage(async (message) => {
		if (message.type === 'image') {
			console.log(message)
			await client
				.sendImageAsSticker(message.from, message.directPath)
				.then((result) => {
					console.log('Result: ', result); 
				}).catch((erro) => {
					console.error('Error when sending: ', erro); 
				});
		}
	});
```

**Comment by MarToxAk** [comment]
sendImageAsSticker it has to be a .gif

**Comment by vigsoft410** [comment]
> sendImageAsSticker it has to be a .gif

it wouldn't be a `sendImageAsStickerGif()` that would have to be gif?

**Comment by edgardmessias** [comment]
@vigsoft410 , reinstall your node_modules, there is a problem with `sharp` library.

I will update the notification to show better the message

**Comment by vigsoft410** [comment]
> @vigsoft410 , reinstall your node_modules, there is a problem with `sharp` library.
> 
> I will update the notification to show better the message

Well I did it, but still not working. Are this parameters correct? -> `.sendImageAsSticker(message.from, message.directPath)` 

![Captura de tela de 2020-12-03 14-19-48](https://user-images.githubusercontent.com/60678520/101064338-a6728900-3572-11eb-9cc3-5da71f4d36a3.png)

**Comment by edgardmessias** [comment]
@vigsoft410 , it is wrong, you must check https://github.com/orkestral/venom#downloading-files
`message.directPath` is not the filePath

**Comment by vigsoft410** [comment]
> @vigsoft410 , it is wrong, you must check https://github.com/orkestral/venom#downloading-files
> `message.directPath` is not the filePath

There's a example of how to get this filePath?
