### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by leandrogmuller** [orkestral/venom#382]
Is there any log file to configure to output logs?

**Comment by ImFarel** [comment]
here try this [gist](https://gist.github.com/ImFarel/0bbbe0757c5dc9b99b68a8887094180b)

**Comment by ImFarel** [comment]
I instead create this [code ](https://gist.github.com/ImFarel/0bbbe0757c5dc9b99b68a8887094180b)to output message log to a file.
