### ISSUE TITLE
Error tryng to download the file.

### ISSUE THREAD

**Issue by dmonteirosouza** [orkestral/venom#383]
![image](https://user-images.githubusercontent.com/52721882/101016254-47e3e580-3547-11eb-9a19-53f08e6c6561.png)
I'm trying to add formatted media, but I get the error message: Error tryng to download the file.
All messages come normal, just do not decrypt the media
What is Wrong? Thank you

**Comment by edgardmessias** [comment]
Install nightly release and try use `client.downloadMedia(messageId)`, it will return a base64 string
