### ISSUE TITLE
How to read only a few messages?

### ISSUE THREAD

**Issue by jonalan7** [orkestral/venom#39]
Hi, I need to read the an amount of latest messages from a chat.
This amount can be 10 for sample.

I tried  some samples posted here as:
loadAndGetAllMessagesInChat();
It works, but calls all chat messages
Is it possible?
Does someone could post a sample?

**Comment by orkestral** [comment]
At the moment we only support here for problems on Venom, for these details we have a group on whatsapp, with more than 50 people to help you.

https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

Thank You!
