### ISSUE TITLE
client.getAllUnreadMessages(); Returns more than just unreaded messages

### ISSUE THREAD

**Issue by DanielJ06** [orkestral/venom#390]
Ao utilizar o método `getAllUnreadedMessages`, ele de fato retorna somente os chats com mensagens pendentes, porém ao invés de retornar somente as mensagens pendentes desses chats, retorna elas e mais algumas anteriores (Já lidas), o que dificulta um pouco na minha aplicação destacar as mensagens não lidas, tem algum outro método ou parâmetro que faça retornar SOMENTE as mensagens não lidas dos respectivos chats?

**Comment by jesusvalverde** [comment]
I do use client.getUnreadMessages(true,true,true);   but as long sendSeen do not work for I can not put those messages on the "seen" list and avoid reading all over again

**Comment by lucaspiressimao** [comment]
> I do use client.getUnreadMessages(true,true,true); but as long sendSeen do not work for I can not put those messages on the "seen" list and avoid reading all over again

this method getAllUnreadMessages always return an empty array for me. How can I get just the unread messages ?

**Comment by vqmacedo** [comment]
Same for me, always return empty array

**Comment by igiul667** [comment]
For me the issue is that 

> getAllUnreadedMessages
always returns more than just the unread messages... why is this closed, no solution has been posted
