### ISSUE TITLE
issue deleting messages.

### ISSUE THREAD

**Issue by fquero47** [orkestral/venom#395]
await client.sendText('0000000000@g.us', 'Message body').then(async(message)=>{
      setTimeout(async ()=>{
      let msjdel = await client.deleteMessage(message.to, message.id.toString(), false);
      console.log(msjdel); 
      }, 15000);
      });

this function sends a message and delete it 15 seconds after. But it's not working even tho it returns and logs "true"

**Comment by joaosouz4dev** [comment]
validate that message.id is really a string and retorn it.

**Comment by joaosouz4dev** [comment]
![image](https://user-images.githubusercontent.com/47183663/101638920-706b5400-3a0d-11eb-8bb3-8e5a38391bb3.png)
I tested it and here it works

**Comment by fquero47** [comment]
> ![image](https://user-images.githubusercontent.com/47183663/101638920-706b5400-3a0d-11eb-8bb3-8e5a38391bb3.png)
> I tested it and here it works

Thanks for your reply. I forgot to mention that I'm trying to delete is groupMessage and I see that you tested it on Non group messages. if you can test in group messages you will see that it works like a clearChat function.

**Comment by fquero47** [comment]
update: The only solution I found is to use a mock group and use its id as first argument. and it works.
