### ISSUE TITLE
receive or generate message id before sending

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#400]
venom instance (wapi) generate message id with very simple code
`````export function getNewId() {
  var text = '';
  var possible =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for (var i = 0; i < 20; i++)
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}
`````

my system which send messages via venom must write message in db with id which then can check by id
I write before sending, and I can generate id before sending

And I must pass my generated id to sendMessage function, like it
`````
sendMessage(to, content, {newMsgId: generatedId});
`````

or other side additional function like client.getNewMsgId() which return generated id

**Comment by Lucipher** [comment]
https://github.com/orkestral/venom/issues/210

**Comment by grupoinfoshop** [comment]
great idea.  I am also trying to implement this.  when sending the message if the cell phone is disconnected, the id is returned for later control.  I await a solution too
