### ISSUE TITLE
WAPI is not defined with pkg

### ISSUE THREAD

**Issue by brunocordeiro180** [orkestral/venom#402]
When using pkg to create executable, venom gives the following error message:

`(node:64956) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:1:16
    at ExecutionContext._evaluateInternal (/snapshot/teste/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/snapshot/teste/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async Socket.<anonymous> (/snapshot/teste/index.js:134:19)
(Use 'wpp-venom-socket-linux --trace-warnings ...' to show where the warning was created)
(node:64956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The venom-bot version used is 2.1.2. I also tried to pass local chrome path in puppeteerOptions, but the error persists.

**Comment by joaosouz4dev** [comment]
I couldn't reproduce this error, I haven't created any executables with venom yet, are you using electron?

**Comment by brunocordeiro180** [comment]
> I couldn't reproduce this error, I haven't created any executables with venom yet, are you using electron?

No, I just created a node js project and create a executable with command `pkg package.json --out-path ./build`. Running the project with `node index.js` works just fine. But when using executable generated by pkg i got the error "WAPI is not defined". The project that I'm using is the following: 

https://github.com/brunocordeiro180/wpp-web-socket.io

**Comment by DanielJ06** [comment]
@joaosouz4dev - Vi que é brasileiro, portanto acho que não se importa se conversamos em português. Você já executou o venom com o electron? Atualmente estou querendo fazer um projeto onde consumo a api do venom, e preciso, de alguma maneira, executar o venom na máquina do meu usuário de maneira intuitiva, tentei com o electron, e para envio e recebimento de mensagens funciona perfeitamente, por outro lado, mensagens do tipo "image", não funcionam. Já passou por algo parecido que possa me dar um insight sobre?

**Comment by joaosouz4dev** [comment]
@DanielJ06 Nunca usei electron, mas acredito que seja algum tipo de permissão, acho que você pode usar algum tipo de banco de dados e cdn para resolver seu problema. Se quiser compartilhar seu projeto ficarei feliz em colaborar.

**Comment by edgardmessias** [comment]
O problema ocorre por causa da maneira que o puppeteer trabalha ao executar essa linha: https://github.com/orkestral/venom/blob/0ee3f0c0d6f9a137a16e6bedf329cb9e80579f2f/src/controllers/browser.ts#L112

Basicamente ele tenta ler um arquivo físico no disco.
Essa linha é a linha que faz a leitura do arquivo no disco: https://github.com/puppeteer/puppeteer/blob/49f25e2412fbe3ac43ebc6913a582718066486cc/experimental/puppeteer-firefox/lib/DOMWorld.js#L157

Se puder fazer o teste de leitura desse arquivo utilizando o `readFileAsync`, isso resolverá o problema do empacotamento.

Dentro do electron, o módulo `fs` consegue ler conteúdo dentro do `.asar`

**Comment by vasani-arpit** [comment]
You can use pkg easily. I have been using it in [WBOT](https://github.com/vasani-arpit/WBOT)

add this in package.json 

```JavaScript
"pkg": {
    "scripts": "src/**/*.js", // took it from my repo. this path may be different in your case.
    "targets": [
      "node10-win",
      "node10-linux",
      "node10-macos"
    ]
  }
```
then you can do `pkg .` to generate the packages.

**Comment by williaanlopes** [comment]
try

```
npm uninstall venom-bot
npm install venon-bot
```

**Comment by brunocordeiro180** [comment]
> O problema ocorre por causa da maneira que o puppeteer trabalha ao executar essa linha:
> 
> https://github.com/orkestral/venom/blob/0ee3f0c0d6f9a137a16e6bedf329cb9e80579f2f/src/controllers/browser.ts#L112
> 
> Basicamente ele tenta ler um arquivo físico no disco.
> Essa linha é a linha que faz a leitura do arquivo no disco: https://github.com/puppeteer/puppeteer/blob/49f25e2412fbe3ac43ebc6913a582718066486cc/experimental/puppeteer-firefox/lib/DOMWorld.js#L157
> 
> Se puder fazer o teste de leitura desse arquivo utilizando o `readFileAsync`, isso resolverá o problema do empacotamento.
> 
> Dentro do electron, o módulo `fs` consegue ler conteúdo dentro do `.asar`

It worked, I had to change wapi path inside venom. To not directly change venom code I made a fork from venom, changed the wapi path and then installed the forked repo in my project

**Comment by luiscuriel** [comment]
> > O problema ocorre por causa da maneira que o puppeteer trabalha ao executar essa linha:
> > https://github.com/orkestral/venom/blob/0ee3f0c0d6f9a137a16e6bedf329cb9e80579f2f/src/controllers/browser.ts#L112
> > 
> > Basicamente ele tenta ler um arquivo físico no disco.
> > Essa linha é a linha que faz a leitura do arquivo no disco: https://github.com/puppeteer/puppeteer/blob/49f25e2412fbe3ac43ebc6913a582718066486cc/experimental/puppeteer-firefox/lib/DOMWorld.js#L157
> > Se puder fazer o teste de leitura desse arquivo utilizando o `readFileAsync`, isso resolverá o problema do empacotamento.
> > Dentro do electron, o módulo `fs` consegue ler conteúdo dentro do `.asar`
> 
> It worked, I had to change wapi path inside venom. To not directly change venom code I made a fork from venom, changed the wapi path and then installed the forked repo in my project

I have the same problem... can you please post the code you used? Thanks

**Comment by juniormelo26** [comment]
Olá, saudações senhores, poderiam compartilhar por favor a correção?  Obrigado!

**Comment by juniormelo26** [comment]
A solução para mim foi no package.json atualiza aversao para 5.1.0 e instalar o sharp, no meu caso pra linux resollveu.
`{
  "dependencies": {
    "cors": "^2.8.5",
    "ejs": "^3.1.9",
    "express": "^4.18.2",
    "puppeteer": "^21.5.2",
    "sharp": "^0.33.3",
    "socket.io": "^4.7.2",
    "venom-bot": "5.1.0"
  }
}`
