### ISSUE TITLE
How to send multiple line on sendtext message?

### ISSUE THREAD

**Issue by Ramhy** [orkestral/venom#403]
im trying to make multiple line message using sendText function and the message is messy, an help will be so meaningfull

```javascript
client
.sendText('000000000000@c.us', 'Hello there,
this is from venom bot
thanks'
.then((result) => {
console.log('success'); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});
```

**Comment by mikelustosa** [comment]
use \n to send multiple line

**Comment by mikelustosa** [comment]
Ex.: client
.sendText('000000000000@c.us', 'Hello there,\n
this is from venom bot\n
thanks'

**Comment by joaosouz4dev** [comment]
Ex.: 
`client.sendText('000000000000@c.us', 'Hello there,\nthis is from venom bot\nthanks')`
