### ISSUE TITLE
refused to set unsafe header

### ISSUE THREAD

**Issue by brunocordeiro180** [orkestral/venom#409]
When using electron with venom, the messages with images gives the following error:

![image](https://user-images.githubusercontent.com/19695449/101682434-61eb5f80-3a42-11eb-92d5-5f732a6fb340.png)

**Comment by antirek** [comment]
Show your code

**Comment by brunocordeiro180** [comment]
`const { ipcRenderer, remote } = require("electron");
const venom = require('venom-bot');
const rimraf = require('rimraf');
const io = require('socket.io-client');
const path = require('path');
var locateChrome = require('locate-chrome');

const chromiumArgs = [
  '--disable-web-security', '--no-sandbox', '--disable-web-security',
  '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
  '--disable-offline-load-stale-cache', '--disk-cache-size=0',
  '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
  '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
  '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
  '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'
];

var chromePath = path.join(process.cwd(), 'chromium/linux-818858/chrome-linux/chrome');


locateChrome(function(l) {
  chromePath = l;
});

let isVisible = false;
let venomInstance;

const show = () => {
	if (!isVisible) {
		ipcRenderer.send('show');
		isVisible = true;
	}
}

window.vm = new Vue({
  el: '#app',
  data: {
    base64Url: null,
    authenticated: false,
    loading: true,
    connClient: null,
    socket: io('http://localhost:3333')
  },

  mounted() {
		window.onkeydown = (e) => {
			if (e.key == 'F12') {
				remote.getCurrentWebContents().openDevTools({ mode: 'undocked' });
			}
		}
    show()
    // this.start()
	},

  methods: {
    start() {
      this.loading = true;
      try {
        venomInstance = venom.create('session', (base64Qr) => {
          this.base64Url = false;
          this.loading = false;
          this.base64Url = base64Qr;
        }, 
        (statusSession, session) => {
          if (statusSession === 'qrReadSuccess') {
            this.socket.emit('successOnConnect')
          }
        } , 
        {logQR: false, autoClose: 0, puppeteerOptions : { executablePath: chromePath }}).then(client => {
          this.socket.emit('join', {
            name: 'cliente',
            room: 'vendergas'
          })
          this.loading = false;
          this.authenticated = true;
          this.base64Url = false;
          this.connClient = client;
          this.startClient(client);
        })
      } catch(err) {
        console.log(err);
      }
    },

    async startClient(client) {
      client.onMessage(async msg => {
        if (msg.from !== 'status@broadcast') {
          if (msg.isMedia == true || msg.isMMS == true) {
            try {
              const buffer = await client.decryptFile(msg.body); 
              let base64data = Buffer.from(buffer, 'hex').toString('base64');
              this.socket.emit('moduleSend', {
                msgContent: base64data,
                type: msg.type,
                from: msg.from,
                to: msg.to,
                name: msg.sender.pushname ? msg.sender.pushname : msg.from,
                avatar: msg.sender.profilePicThumbObj.img ? msg.sender.profilePicThumbObj.img : 'none',
                timestamp: msg.timestamp 
              });
            } catch (err) {
              console.error(err);
              console.log('Ocorreu um erro ao realizar decode64 do arquivo');
            }    
          } else {
            this.socket.emit('moduleSend', {
              msgContent: msg.body,
              type: msg.type,
              from: msg.from,
              to: msg.to,
              name: msg.sender.pushname ? msg.sender.pushname : msg.from,
              avatar: msg.sender.profilePicThumbObj.img ? msg.sender.profilePicThumbObj.img : 'none',
              timestamp: msg.timestamp 
            });
          }
        } 
      })

      // Retrieve all unread message
      //const messages = await client.getAllUnreadMessages();

      client.onStateChange(state => {
        if ('CONFLICT'.includes(state)) {
          this.kill()
          this.socket.emit('errorOnConnect')
        }
        if ('UNPAIRED'.includes(state)) {
          this.kill()
          this.socket.emit('errorOnConnect')
        }
        if('CONNECTED'.includes(state)) {
          this.socket.emit('successOnConnect')
        }
      })

      this.socket.on('frontReceive', async data => {
        await client.sendSeen(data.to);
        client.sendText(data.to, String(data.msgContent));
      })

      this.socket.on('markAsRead', async data => {
        await client.sendSeen(data);
      })
      
      this.socket.on("oldMessages", async () => {
        const unread = await client.getUnreadMessages(true,true,true);
        const chats = await client.getAllChats();
        const device = await client.getHostDevice();
        this.socket.emit('listenOldMessages', {clients: chats, hostDevice: device, unreadMessages: unread});
      })
    },

    kill() {
      this.connClient.close();
      rimraf("tokens", () => console.log('done'))
      this.authenticated = false;
      this.socket.emit('errorOnConnect')
      this.start();
    }
  }
})`

**Comment by brunocordeiro180** [comment]
`const { ipcRenderer, remote } = require("electron");`
`const venom = require('venom-bot');`
`const rimraf = require('rimraf');`
`const io = require('socket.io-client');`
`const path = require('path');`
`var locateChrome = require('locate-chrome');`

`const chromiumArgs = [
  '--disable-web-security', '--no-sandbox', '--disable-web-security',
  '--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
  '--disable-offline-load-stale-cache', '--disk-cache-size=0',
  '--disable-background-networking', '--disable-default-apps', '--disable-extensions',
  '--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
  '--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
  '--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'
];`

`var chromePath = path.join(process.cwd(), 'chromium/linux-818858/chrome-linux/chrome');`

`locateChrome(function(l) {
  chromePath = l;
});`

`let isVisible = false;`
`let venomInstance;`

`const show = () => {
	if (!isVisible) {
		ipcRenderer.send('show');
		isVisible = true;
	}
}`

`window.vm = new Vue({`
  `el: '#app',`
  `data: {`
    `base64Url: null,`
    `authenticated: false,`
    `loading: true,`
    `connClient: null,`
    `socket: io('http://localhost:3333')`
  `},`

  `mounted() {`
		`window.onkeydown = (e) => {`
		`	if (e.key == 'F12') {`
		`		remote.getCurrentWebContents().openDevTools({ mode: 'undocked' });`
		`	}`
		`}`
    `show()`
    `this.start()`
	`},`

  `methods: {`
    `start() {`
      `this.loading = true;`
      `try {`
       ` venomInstance = venom.create('session', (base64Qr) => {`
        `  this.base64Url = false;`
         ` this.loading = false;`
          `this.base64Url = base64Qr;`
        `}, `
        `(statusSession, session) => {`
        `  if (statusSession === 'qrReadSuccess') {`
         `   this.socket.emit('successOnConnect')`
          `}`
        `} , `
        `{logQR: false, autoClose: 0, puppeteerOptions : { executablePath: chromePath }}).then(client => {`
         ` this.socket.emit('join', {`
          `  name: 'cliente',`
           ` room: 'vendergas'`
          `})`
          `this.loading = false;`
          `this.authenticated = true;`
          `this.base64Url = false;`
          `this.connClient = client;`
         ` this.startClient(client);`
        `})`
     ` } catch(err) {`
      `  console.log(err);`
      `}`
   ` },`

    async startClient(client) {
      client.onMessage(async msg => {
        if (msg.from !== 'status@broadcast') {
          if (msg.isMedia == true || msg.isMMS == true) {
            try {
              const buffer = await client.decryptFile(msg.body); 
              let base64data = Buffer.from(buffer, 'hex').toString('base64');
              this.socket.emit('moduleSend', {
                msgContent: base64data,
                type: msg.type,
                from: msg.from,
                to: msg.to,
                name: msg.sender.pushname ? msg.sender.pushname : msg.from,
                avatar: msg.sender.profilePicThumbObj.img ? msg.sender.profilePicThumbObj.img : 'none',
                timestamp: msg.timestamp 
              });
            } catch (err) {
              console.error(err);
              console.log('Ocorreu um erro ao realizar decode64 do arquivo');
            }    
          } else {
            this.socket.emit('moduleSend', {
              msgContent: msg.body,
              type: msg.type,
              from: msg.from,
              to: msg.to,
              name: msg.sender.pushname ? msg.sender.pushname : msg.from,
              avatar: msg.sender.profilePicThumbObj.img ? msg.sender.profilePicThumbObj.img : 'none',
              timestamp: msg.timestamp 
            });
          }
        } 
      })

      // Retrieve all unread message
      //const messages = await client.getAllUnreadMessages();

      client.onStateChange(state => {
        if ('CONFLICT'.includes(state)) {
          this.kill()
          this.socket.emit('errorOnConnect')
        }
        if ('UNPAIRED'.includes(state)) {
          this.kill()
          this.socket.emit('errorOnConnect')
        }
        if('CONNECTED'.includes(state)) {
          this.socket.emit('successOnConnect')
        }
      })

      this.socket.on('frontReceive', async data => {
        await client.sendSeen(data.to);
        client.sendText(data.to, String(data.msgContent));
      })

      this.socket.on('markAsRead', async data => {
        await client.sendSeen(data);
      })
      
      this.socket.on("oldMessages", async () => {
        const unread = await client.getUnreadMessages(true,true,true);
        const chats = await client.getAllChats();
        const device = await client.getHostDevice();
        this.socket.emit('listenOldMessages', {clients: chats, hostDevice: device, unreadMessages: unread});
      })
    },

    kill() {
      this.connClient.close();
      rimraf("tokens", () => console.log('done'))
      this.authenticated = false;
      this.socket.emit('errorOnConnect')
      this.start();
    }`
  `}`
`})`

**Comment by antirek** [comment]
Do you can use venom instance not in electron window (chrome) context?

**Comment by brunocordeiro180** [comment]
Yes, the problem is the combination venom + electron

**Comment by vasani-arpit** [comment]
You won't able to package the electron app if you use venom in it. Electron has the [webview](https://www.electronjs.org/docs/api/webview-tag) use that to open whatsapp and then inject the WAPI script into it using [preload](https://www.electronjs.org/docs/api/webview-tag#preload) attribute.
