### ISSUE TITLE
Erro ao enviar Localização

### ISSUE THREAD

**Issue by JandersonFB** [orkestral/venom#410]
Olá, 
Estou recebendo esse erro ao enviar a localização.

![image](https://user-images.githubusercontent.com/11274709/101684829-c1973a00-3a45-11eb-8bd3-de036c579d59.png)

**Comment by antirek** [comment]
Show your code

**Comment by JandersonFB** [comment]
`async function sendLocation() {
            try {

                await clientsArray[session].sendLocation(chatId, '-23.4226649','-51.9239818','ConveniBeer');

                res.status(200).json({
                    response: {
                        status: true,
                        chatId: chatId,
                        message: 'Location Sent.. ',
                        session: session,
                        secret: secret,
                    },
                })

            } catch (error) {
                res.status(400).json({
                    response: {
                        status: false,
                        chatId: chatId,
                        message: 'Location not Sent...',
                        session: session,
                        secret: secret,
                        log: error
                    },
                })
            }
        }`
