### ISSUE TITLE
how to capture that state before starting a session

### ISSUE THREAD

**Issue by JandersonFB** [orkestral/venom#413]
Hi,
how to capture this state before starting a session:

![image](https://user-images.githubusercontent.com/11274709/101713360-439f5700-3a76-11eb-96f1-77373f2449b8.png)

**Comment by antirek** [comment]
No way.

Session will be started only if your phone connected and paired with venom instance. And after this you can receive changes of state. It's "state in session" :)

**Comment by edgardmessias** [comment]
@antirek , @JandersonFB , it is possible.

You need pass `waitForLogin: false` ([doc here](https://orkestral.github.io/venom/interfaces/createconfig.html#waitforlogin)) in the option. With this, the `venom.create` will return a non logged instance. After that you can listen the events.

At end of your code, you can call `await client.waitForLogin()` ([doc here](https://orkestral.github.io/venom/classes/whatsapp.html#waitforlogin)) to start the QRCode reading.

**Comment by JandersonFB** [comment]
@edgardmessias vi que você é conterrâneo do PR rs, então vamos de pt_BR.

Estou com um delay para LER o QR e o onStateChange mandar essa informação para o FRONT-END, porém esses LOGS ai, assim que o "celular treme" mostrando que foi feito a leitura do QR, ele já começa a se movimentar, por isso surgiu a minha necessidade de capturar esse LOG e não no onStateChange, pois lá demora um pouco até aparecer o "qrReadSuccess"

Entendeu?

**Comment by edgardmessias** [comment]
Veja bem, existe um processo entre a leitura do QRCode até a interface estar disponível, basicamente a interface web do whatsapp web passa pelo processo de QR > PAIRING > SYNCING > CHAT.
O momento que você faz o scan, ele entra no modo PAIRING e depois SYNCING, então enquanto ele não entrar no CHAT, não funciona o envio das mensagens

**Comment by edgardmessias** [comment]
O PR #407 vai trazer novas opções relacionadas a interface, que difere do State. Basicamente existem 3 itens: State, Stream e Interface
* O State retorna a relação de conexão entre a interface e o celular
* O Stream retorna a relação do WEBSOCKET do whatsappweb com o servidor do whatsapp
* E a interface é a combinação de ambos, mostrando qual componente do react que está carregado no momento
