### ISSUE TITLE
Send text message to a list of contacts

### ISSUE THREAD

**Issue by LuizTokuhara** [orkestral/venom#414]
Is it possible to send text message to a list of contacts?
For example:

var contactArray = [{name: "john", phone: "000000@c.us"}, {name: "maria", phone: "00000@c.us"}, {name: "ted", phone: "0000@c.us"}];

await client
  .sendText(contactArray, '👋 Hello from venom!')
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
});

**Comment by joaosouz4dev** [comment]
use loop for this,
```
contactArray.forEach((el) => {
await client
.sendText(el.phone, '👋 Hello from venom!')
.then((result) => {
console.log('Result: ', result); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});
})
```
be careful with this type of function as it can ban your number if whatsapp detects something out of the ordinary, try to put a delay in your loop for sending these messages
