### ISSUE TITLE
Listing all groups after creating a new group doesn't return new group name

### ISSUE THREAD

**Issue by garciabruno** [orkestral/venom#415]
Steps to reproduce:

* 1- Create a group with a test name, eg: "NEW_GROUP" (`client.createGroup`)
* 2- List all groups (`client.getAllGroups`), all information about "NEW_GROUP" is there except key "name"

**Comment by jonalan7** [comment]
**The problem has been resolved with a new update!** 
Use: 
```
// Retrieves all grups
const groups = await client.getAllChatsGroups ();
```

**Comment by garciabruno** [comment]
Thanks a lot!!

**Comment by YuriFontella** [comment]
With the getAllChatsGroups() function is returning this error:

```bash
Error: Evaluation failed: ReferenceError: groupId is not defined
at __puppeteer_evaluation_script__:3:29
at ExecutionContext._evaluateInternal (.../node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ExecutionContext.evaluate (.../node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
```

**Comment by ArmandoTL** [comment]
> ```shell
> Error: Evaluation failed: ReferenceError: groupId is not defined
> ```

no have solution?

**Comment by ArmandoTL** [comment]
> **The problem has been resolved with a new update!** Use:
> 
> ```
> // Retrieves all grups
> const groups = await client.getAllChatsGroups ();
> ```

"node_modules/venom-bot": {
      "version": "4.2.0",
      "resolved": "git+ssh://git@github.com/orkestral/venom.git#87ca0525f4741e3801f0a86ca097823eb4c5132c",
      "license": "MIT",
      "dependencies": {
        "@typescript-eslint/eslint-plugin": "^5.29.0",
        "@typescript-eslint/parser": "^5.29.0",
        "atob": "^2.1.2",
        "axios": "^0.27.2",
        "boxen": "^5.1.1",
        "catch-exit": "^1.1.0",
        "chalk": "^4.0.0",
        "chrome-launcher": "^0.15.1",
        "commitizen": "^4.2.4",
        "cz-conventional-changelog": "^3.3.0",
        "dotenv": "^16.0.1",
        "futoin-hkdf": "^1.5.1",
        "latest-version": "^5.1.0",
        "mime-types": "^2.1.35",
        "ora": "^6.1.0",
        "puppeteer": "^14.4.1",
        "puppeteer-extra": "^3.2.3",
        "puppeteer-extra-plugin-stealth": "^2.10.1",
        "qrcode-terminal": "^0.12.0",
        "sanitize-filename": "^1.6.3",
        "sharp": "^0.30.7",
        "spinnies": "^0.5.1",
        "tree-kill": "^1.2.2",
        "typedoc": "^0.22.15",
        "typedoc-default-themes": "^0.12.10",
        "winston": "^3.7.2",
        "ws": "^8.8.0",
        "yoo-hoo": "^1.2.0"
      },
