### ISSUE TITLE
se cruzan las respuestas del bot cuando conversa con varios usuarios al tiempo

### ISSUE THREAD

**Issue by GhostWolf95** [orkestral/venom#420]
Buenas, estoy realizando un bot de atención al cliente, pero, cuando varios clientes conversan al tiempo, el bot cruza los mensajes entre lo usuarios. podrían ayudarme con esto. gracias

Hi, I'm making a customer service bot, but when several customers talk at the same time, the bot crosses the messages between the users. could you help me with this. thanks

**Comment by jesusvalverde** [comment]
puedes enviar un fragmento del codigo, porque yo no tengo problemas con los mios

"Could you please send some code, I do not have issues like those with mines"

**Comment by GhostWolf95** [comment]
Hola Jesus, Este es el fragmento de código.

instancia.onMessage((message) => {
      console.log("MENSAJE RECIBIDO");
      if(message.type == 'chat' && message.isMedia == false && message.isGroupMsg == false){
        // console.log(message);
        msg_usuario = message.body;
        telefono_usuario = message.from;
        nom_usuario = message.from.replace("@c.us", "");
        contacto_usuario = nom_usuario.substr(2);
        //Registrando contacto
        contactos.RegistrarContacto(contacto_usuario, id, telefono_usuario, nom_usuario).then((res) => {
        }).catch((error) => {
          logger.Error("ERROR REGISTRANDO NUMERO EN DIRECTORIO DE CONTACTOS. respuesta: "+JSON.stringify(error));
        })
        //Consulta la respuesta haciendo peticion a una API
        bot.Conversar(id, telefono_usuario, msg_usuario).then((res) => {
            if(res.code != 422){
                respuesta = res.res.enunciado.replace(/\\n/g, "\n");
                if(res.res.imagen != undefined && res.res.imagen != ""){
                  help.SubirBase64(res.res.imagen).then((resp) => {
                      ruta = resp.ruta;
                      name = resp.file_name;
                      EnviarArchivo(id, telefono_usuario, ruta, name, respuesta)
                      .catch((error) => {
                          logger.Error("Error Enviando archivo de respuesta de bot. IDCliente: "+id+" | ERROR: "+JSON.stringify(error));
                      });
                  }).catch((error) => {
                      logger.Error("Error Subiendo archivo de respuesta de bot. IDCliente: "+id+" | ERROR: "+JSON.stringify(error));
                  });                           
                }else{
                  EnviarMensajeTxtWp(id, telefono_usuario, respuesta) 
                  .catch((error) => {
                      logger.Error("Error Enviando respuesta de bot. IDCliente: "+id+" - telefono_usuario:"+telefono_usuario+" - enunciado:"+respuesta+" | ERROR: "+JSON.stringify(error));
                  });
                  
                  if(res.res.archivo != undefined && res.res.archivo != ""){
                    name_archivo = res.res.archivo;
                    EnviarArchivo(id, telefono_usuario, "storage/archivos/"+name_archivo, name_archivo, respuesta, 0)
                    .catch((error) => {
                        logger.Error("Error Enviando archivo de respuesta de bot. IDCliente: "+id+" | ERROR: "+JSON.stringify(error));
                    });
                  }
                }        
            }else{
                logger.Error("Error de validacion Consultando respuesta de bot. IDCliente: "+id+" | ERROR: "+JSON.stringify(erro));
            }
        }).catch((erro) => {
            logger.Error("Error Consultando respuesta de bot. IDCliente: "+id+"  | ERROR: "+JSON.stringify(erro));
        });
      }
    });

**Comment by jesusvalverde** [comment]
Bueno por lo que veo son consultas a un api externo o una db por lo que puede haber un poco de delay en función de la carga.
 
-Usar "await" para que los procedimientos terminen antes de saltar a la siguiente linea, sobre todo con los envios de archivos sin querer queriendo te puedes generar tiempos de espera mas alto que pueden hacerte 'saltar' a lineas sin tener resultados.
await bot.Conversar
await EnviarMensajeTxtWp(..)
.. vas a tener que hacer que tus funciones sean async pero te dará más confianza para hacer hilos paralelos (o al menos a mi me las da).

-Bonus ... Cuando hagas el boot.Conversa, dentro del Json/conjunto de variables que te retornas inclúyete el número [res.res.telefono_usuario] y usa ese numero , asi tendrás más certeza aun de que no has tenido una variable arrastra que por la ausencia de una await o un delay se te ha corrido.

Cualquier otra cosa me comentas...

**Comment by GhostWolf95** [comment]
Gracias @jesusvalverde. Excelente me ayudo mucho tu respuesta.
