### ISSUE TITLE
Error no open browser

### ISSUE THREAD

**Issue by hodevcom** [orkestral/venom#421]
Error on ubuntu server after update 2.0.16.

![image](https://user-images.githubusercontent.com/66075384/101853444-58dfb880-3b3e-11eb-9303-5c801b6c0b9c.png)

**Comment by antirek** [comment]
try use browserArgs: ['--no-sandbox'] in venom options

**Comment by hodevcom** [comment]
My args: ['--disable-web-security', '--no-sandbox', '--disable-web-security',
'--aggressive-cache-discard', '--disable-cache', '--disable-application-cache',
'--disable-offline-load-stale-cache', '--disk-cache-size=0',
'--disable-background-networking', '--disable-default-apps', '--disable-extensions',
'--disable-sync', '--disable-translate', '--hide-scrollbars', '--metrics-recording-only',
'--mute-audio', '--no-first-run', '--safebrowsing-disable-auto-update',
'--ignore-certificate-errors', '--ignore-ssl-errors', '--ignore-certificate-errors-spki-list'];

**Comment by cristianormoraes** [comment]
same problem here..

**Comment by migueljr** [comment]
Estou tambem com o mesmo problema...

**Comment by dilsoncosta** [comment]
aqui também está com o msm erro

**Comment by cristianormoraes** [comment]
> aqui também está com o msm erro
> [SOLUTION]
> [#290 (comment)](https://github.com/orkestral/venom/issues/290#issuecomment-728182088)

not worked for me, I was opened this issue...



aqui não funcionou... eu que abri esse tópico !

**Comment by cristianormoraes** [comment]
▐█  ██  █░▐█▀▀▀░▐█     ▄█▀▀█▄ ▄█▀▀█▄ ▐██   ██▌ ▓█▀▀▀░
     █▌▐██▄▓█ ▐█▄▄▄ ▐█    ▐█      █▒  ▐█▄▐█▀▌ ▐▌█▌ ▓█▄▄▄
     ▐██ ▐██░ ▐█    ▐█    ▐█▄  ▄▀ █▌  ▐█ ▐█ █▓█ █▌ ██
      ▀▀  ▀▀  ▀▀▀▀▀░▐▀▀▀▀▀  ▀▀▀▀   ▀▀▀▀  ▐▀  ▀  ▀▀ ▀▀▀▀▀
                                   ▄
      ▄▄░          ▄ ▄▄▄▄▄▄▄▄▄▄▄▄▄ ██         ▄▄       ▄▄▄▄      ░
      ░██▄        ██ ███▀▀▀▀▀▀▀▀█▌ ███▌       ██▄  ▄▄█▀▀▀▀▀▀█▄   ▓█▄           ▄█░
       ░██▄     ░██▀ ███           ██▀██▄     ██▄ ▄█░        ▀█▄ ▓███▄      ░████░
         ██▌   ▄██░ ▄███▄▄▄▄       ██  ▓██▄   ██▄▐█           ▐█ ▓█▌▀██▄  ▄███░██░
          ██▌ ▄██░  ▀███▀▀▀▀       ██   ▐██▌  ██▄▐█           ▐█░▓█▌  ▀█████░  ██░
           ▓████     ███           ██     ▀██▄██▄ █▌          ██ ▓█▌    ▀█░    ██░
            ▀██      ███        █▌ ██       ▀███▄  ▀█▄     ▄▄█▀  ▓█▌           ██░
             ▀       ▀███████████▌ ██        ░██▄    ▀▀███▀▀░    ▀█▌           ▓█░
                                              ▀░

✓ You're up to date
Chrome not found, using chromium
✖ Error no open browser
(node:107450) UnhandledPromiseRejectionWarning: Error no open browser
(node:107450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:107450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by antirek** [comment]
Why don't you describe version of venom-bot and your environment with problem?

For example, I use venom-bot 2.1.2 on ubuntu 20.04 with node.js 14.15.1 and all right! :) 

Do you try change some parameters or combine them?

**Comment by cristianormoraes** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Venom-bot:  venom-bot-2.1.2

**Comment by antirek** [comment]
ok, maybe try update node?

I also use venom-bot 2.1.2 on ubuntu 18.04.1 (in docker) and image with node 14.15.1 
my config {"autoClose":0,"browserArgs":["--no-sandbox"],"headless":true,"devtools":false,"useChrome":false,"debug":false,"logQR":false,"disableSpins":true,"disableWelcome":true}  and also all right ))

**Comment by cristianormoraes** [comment]
node updated to v14.15.1, but same error.

tried your config, but same error...

**Comment by dilsoncosta** [comment]
> > aqui também está com o msm erro
> > [SOLUTION]
> > [#290 (comment)](https://github.com/orkestral/venom/issues/290#issuecomment-728182088)
> 
> not worked for me, I was opened this issue...
> 
> aqui não funcionou... eu que abri esse tópico !

aqui funciono pra mim, que estranho

**Comment by MarceloTomaz** [comment]
Try this !
# apt-get install libglib2.0-dev libnss3 libatk1.0-0 libcups2 libgtk-3-dev libasound2

-- Venom Config

         ...
         puppeteerOptions: {
                    args: [
                        '--no-sandbox',
                        '--disable-setuid-sandbox'
                    ]
                }
       ...

**Comment by cristianormoraes** [comment]
tried too, but, unsuccessful

**Comment by MarceloTomaz** [comment]
> tried too, but, unsuccessful

https://medium.com/mockingbot/run-puppeteer-chrome-headless-on-ec2-amazon-linux-ami-6c9c6a17bee6

**Comment by cristianormoraes** [comment]
I'm using ubuntu 18

**Comment by edgardmessias** [comment]
@cristianormoraes @migueljr @dilsoncosta 

I improved the error output. Could you try this PR #443: `npm install github:edgardmessias/venom#fix_browser`

This not solve the problem, but improve the output

**Comment by cristianormoraes** [comment]
@edgardmessias after install your version, the error has change to:


internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/var/www/zap/node_modules/venom-bot/dist/index.js'. P                                                                                                                                                             lease verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/www/zap/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/var/www/zap/node_modules/venom-bot/package.json',
  requestPath: 'venom-bot'
}

**Comment by edgardmessias** [comment]
@cristianormoraes , yes, it is the intention, so, you problem is: "BROWSER NOT FOUND"

Look https://orkestral.github.io/venom/interfaces/createconfig.html#puppeteeroptions and https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions

Try pass the `executablePath` argument

**Comment by cristianormoraes** [comment]
you mean?



puppeteerOptions: {
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ],

		executablePath: '/usr/bin/chromium-browser'
            }

**Comment by cristianormoraes** [comment]
works fine! thank you @edgardmessias
