### ISSUE TITLE
Venom is not generating the QrCode when I am not logged in

### ISSUE THREAD

**Issue by Eider3a** [orkestral/venom#429]
I don't have the token folder because I'm not logged in, but when I  am trying to generate the QRCode, the process is not working out and the image is never shown. The library is up to date.

This Is what I get when I am trying to generate the QrCode.
✓ You're up to date
✓ headless option is active, browser hidden
⠇ {session: sessionName, apiInject: injecting, autoCloneRemain: 167}: Checking is logged...

This is the output I am getting in the console after autoCloneRemain is equals to 0.
✓ You're up to date
✓ headless option is active, browser hidden
✖ {session: sessionName, apiInject: failed}: Page Closed
✖ {session: sessionName, apiInject: failed}: Page Closed
✖ {session: sessionName, apiInject: failed}: Unknow error
Unknow error

I will appreciate any help.
Regards.

**Comment by UnknownMovements** [comment]
I'm getting the same issue in my project. Any thoughts?

**Comment by edgardmessias** [comment]
Could you make test with #427?

**Comment by carloslleitao** [comment]
Hey Guys, we made a test here with the recommended procedure but it still doesnt work for qrcode

**Comment by carloslleitao** [comment]
Hey guys just to mention, our problem was internal here, changes worked fine and qrcode is showing up normally!

**Comment by Eider3a** [comment]
Hi guys, now it is working without a problem, I just delete the node_modules folder and I reinstalled everything.
It did the trick for me.

Thanks for the recommendations.
