### ISSUE TITLE
Error sending csv file

### ISSUE THREAD

**Issue by joaosouz4** [orkestral/venom#43]
await client.sendFile(chatId, 'path/to/file.csv', 'cv.csv', '');
when trying to send a csv
![3992e4da-8db4-48a8-99be-632d73161c50](https://user-images.githubusercontent.com/47183663/85872907-ca04fc80-b7a6-11ea-8327-9bf7db08319b.jpg)

**Comment by CosmicSnow** [comment]
problem solved, and PR made.
You can download the branch https://github.com/orkestral/venom/tree/fix-mime-types-send-file and build it if you wish.
or wait for the merge, and update it via npm.

I'll leave it open while not merged into master.
