### ISSUE TITLE
Has anyone created a list of URL requests to be opened on a firewall?

### ISSUE THREAD

**Issue by carloslleitao** [orkestral/venom#433]
Hey guys, has anyone at any point in time created a list of URLs that MUST be opened for venom for the send message and send file features to be opened on a firewall? Imagining a scenario where a VM is inside a network and that I need to open just what is needed for the feature, would we have a list of URLs to be opened for this? Is it dynamic?

Thanks for anyone interacting in advance

**Comment by edgardmessias** [comment]
https://web.whatsapp.com/*
wss://web.whatsapp.com/*
https://chat.whatsapp.com/*
*.whatsapp.net
