### ISSUE TITLE
Rebuild Session

### ISSUE THREAD

**Issue by xxxLord99** [orkestral/venom#441]
hellow sir @orkestral ,

can you gave me an solutions about
how can save a session after server exit, and rebuild it again at the startup of my server without scanning a QR Code ?

thx sir.

**Comment by rafa-so** [comment]
Here I don't need rescanning qr code all times I restart session server.  Show all steps that you are doing, and all lib verions and SO used. :)

**Comment by edgardmessias** [comment]
Read the docs:
https://orkestral.github.io/venom/interfaces/createoptions.html#createpathfiletoken
https://orkestral.github.io/venom/classes/whatsapp.html#getsessiontokenbrowser
https://orkestral.github.io/venom/modules.html#create
