### ISSUE TITLE
¿cuales son las limitaciones en numero de mensajes recibidos y enviados por día o por hora?. What are the limitations on the number of messages received and sent per day or per hour?

### ISSUE THREAD

**Issue by GhostWolf95** [orkestral/venom#447]
Hola, me surgió una pregunta, ¿cual es el limite de mensajes por hora y/o días que se permite enviar y/o recibir, para que whatsapp no bloquee el numero?. gracias

Hello, I have a question, what is the limit of messages per hour and / or days that is allowed to send and / or receive, so that WhatsApp does not block the number? thanks

**Comment by edgardmessias** [comment]
It is impossible to determine because it is a unofficial way to send messages
