### ISSUE TITLE
Send image using base64 format

### ISSUE THREAD

**Issue by xxxLord99** [orkestral/venom#450]
hellow sir @orkestral,

i have a question, how can i send an image using base64 formatt ?

thx sir.

**Comment by antirek** [comment]
1. convert image to base64 like npm https://www.npmjs.com/package/image-to-base64 
2. append prefix like 'data:image/png;base64,' to converted string
3. send received base64 string via client.sendFileFromBase64

**Comment by xxxLord99** [comment]
>     1. convert image to base64 like npm https://www.npmjs.com/package/image-to-base64
> 
>     2. append prefix like 'data:image/png;base64,' to converted string
> 
>     3. send received base64 string via client.sendFileFromBase64

in case i'm using library pdf2pic, to convert my pdf to image and generate as base64 format, so when i send to WA
i got this error message. pict below :


![image](https://user-images.githubusercontent.com/56199096/102585553-2e43c000-413b-11eb-93df-77a64f8173c3.png)

@antirek

**Comment by xxxLord99** [comment]
`export function sendMessageFile (client, payload) {
  return new Promise((resolve, reject) => {
    const convertPDFtoImgAsB64 = fromBase64(payload.files, options).bulk(1, 'B64')
    convertPDFtoImgAsB64.then((result) => {
      let imgBase64 = `data:image/png;${result[0].base64}`
      console.log('>>>', imgBase64)
      client
        .sendFileFromBase64(
          `${payload.to}${_prefix}`, 
          imgBase64, 
          'SPK',
          'Data SPK'
        )
        .then((result) => {
          if(result === false) {
            throw new Error('Phone number doesn\'t exists ...')
          } else {
            resolve(result)
          }
        }).catch(er => {
          console.log('X1 :', er)
          reject(er)
        })
    }).catch(er => {
      console.log('X2 :', er)
      reject(er)
    })
  })
}`

that's my code sir @antirek

**Comment by xxxLord99** [comment]
@antirek , ummm oke sir th

>     1. convert image to base64 like npm https://www.npmjs.com/package/image-to-base64
> 
>     2. append prefix like 'data:image/png;base64,' to converted string
> 
>     3. send received base64 string via client.sendFileFromBase64

this is work for me, thx sir
