### ISSUE TITLE
Venom eating disk space

### ISSUE THREAD

**Issue by LucasPonzo** [orkestral/venom#454]
## Description

Venom eating huge space on disk.

## Environment

- **Venom version(s):** 2.0.27
- **Browser:** Chromium installed by venom dependencies
- **OS:** Windows Server 2019
- **Node version:** 10.16.3

## Steps to Reproduce

1. Install an run Venom based Bot
2. Disk space used increases hugely

`https://s3-sa-east-1.amazonaws.com/player.gestorhappy.com.br/350415d5-05ba-41d1-8750-0be2702d85d0.jpg`

**Comment by antirek** [comment]
don't use a windows, seriously ))

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
