### ISSUE TITLE
Reply with sticker

### ISSUE THREAD

**Issue by kaiserdj** [orkestral/venom#460]
I would like to be able to send a reply to a message with a sticker (using the sendImageAsStickerGif and sendImageAsSticker functions inside the sendMessageOptions function), but I think that right now there is no possible way to do it with Venom.

**Comment by edgardmessias** [comment]
@kaiserdj , please, update to use issue template or I will close it.
Template: https://github.com/orkestral/venom/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
