### ISSUE TITLE
How to send mp3 as audio

### ISSUE THREAD

**Issue by RubberArchind** [orkestral/venom#47]
Hi, I tried sending an mp3 file with sendFile () but the file was sent not as audio but as a normal file

![image](https://user-images.githubusercontent.com/35050952/85942937-f495b780-b956-11ea-9d54-8f93aa21c951.png)
*It was sent like that, instead of
![image](https://user-images.githubusercontent.com/35050952/85942960-155e0d00-b957-11ea-901e-c831d39298fc.png)

**Comment by joaosouz4** [comment]
you need to send it as ptt, but ptt still has some problems that will be fixed soon

**Comment by RubberArchind** [comment]
Alright, thank you for the response.
I will wait for the next update
