### ISSUE TITLE
Support for termux ( Open Source Android terminal and Linux environment) 

### ISSUE THREAD

**Issue by rishabhrpg** [orkestral/venom#470]
It would be a good option if venom could run inside termux app so that it can be deployed to the same phone where WhatsApp is running.

I tried running it directly currently it through an error in openurl.js where it tries to invoke a system call to open a URL and throws  "Unsupported Platform" exception.

**Comment by antirek** [comment]
"Unsupported Platform" it's your pain )) 

What is the benefit for community from this issue?

For example, you may write simple instruction or script how you start run venom in termux for minutes. And append some logs for understanding problems in your environment. And maybe somebody can repeat your way and help you overcome exceptions.

**Comment by edgardmessias** [comment]
This is an external dependency problem.

Closed in favor of https://github.com/puppeteer/puppeteer/issues/2957 and https://github.com/puppeteer/puppeteer/issues/4362

**Comment by rishabhrpg** [comment]
@edgardmessias Hello, I was able to run puppeteer inside termux, It just takes a fre more arguments to launch the browser. 
it would be great if venom can expose a method that can take the extra argument to be passed into puppeteer. 

[puppeteer-on-termux](https://github.com/rishabhrpg/puppeteer-on-termux)
