### ISSUE TITLE
Cannot build the project running "npm run build", any tips ?

### ISSUE THREAD

**Issue by antonio-couto** [orkestral/venom#48]
[08:58:50] Using gulpfile C:\Source\NodeJs\venom\src\lib\jsQR\gulpfile.js
[08:58:50] Starting 'default'...
[08:58:50] Finished 'default' after 47 ms
src/controllers/browser.ts:68:40 - error TS2345: Argument of type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Browser' is not assignable to parameter of type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Browser'.
  Types of property 'on' are incompatible.
    Type '<K extends "disconnected" | "targetchanged" | "targetcreated" | "targetdestroyed">(eventName: K, handler: (e: import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").BrowserEventObj[K], ...args: any[]) => void) => import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/n...' is not assignable to type '<K extends "disconnected" | "targetchanged" | "targetcreated" | "targetdestroyed">(eventName: K, handler: (e: import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").BrowserEventObj[K], ...args: any[]) => void) => import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Browser'.
      Types of parameters 'handler' and 'handler' are incompatible.
        Types of parameters 'e' and 'e' are incompatible.
          Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").BrowserEventObj[K]' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").BrowserEventObj[K]'.
            Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").BrowserEventObj' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").BrowserEventObj'.
              The types returned by 'targetchanged.browserContext().newPage()' are incompatible between these types.
                Type 'Promise<import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Page>' is not assignable to type 'Promise<import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Page>'.
                  Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Page' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Page'.
                    Types of property 'on' are incompatible.
                      Type '<K extends "error" | "dialog" | "close" | "load" | "response" | "request" | "domcontentloaded" | "console" | "frameattached" | "framedetached" | "framenavigated" | "metrics" | "pageerror" 
| ... 4 more ... | "workerdestroyed">(eventName: K, handler: (e: import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node...' is not assignable to type '<K extends "error" | "dialog" | "close" | "load" | "response" | "request" | "domcontentloaded" | "console" | "frameattached" | "framedetached" | "framenavigated" | "metrics" | "pageerror" | ... 4 more ... | "workerdestroyed">(eventName: K, handler: (e: import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/ind...'.
                        Types of parameters 'handler' and 'handler' are incompatible.
                          Types of parameters 'e' and 'e' are incompatible.
                            Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").PageEventObj[K]' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").PageEventObj[K]'.
                              Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").PageEventObj' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").PageEventObj'.
                                The types returned by 'console.args()' are incompatible between these types.
                                  Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").JSHandle<any>[]' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").JSHandle<any>[]'.
                                    Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").JSHandle<any>' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").JSHandle<any>'.
                                      The types returned by 'asElement().contentFrame()' are incompatible between these types.
                                        Type 'Promise<import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Frame>' is not assignable to type 'Promise<import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Frame>'.
                                          Type 'import("C:/Source/NodeJs/venom/node_modules/puppeteer-extra/node_modules/@types/puppeteer/index").Frame' is not assignable to type 'import("C:/Source/NodeJs/venom/node_modules/@types/puppeteer/index").Frame'.
                                            The types returned by 'executionContext()' are incompatible between these types.
                                              Type 'Promise<ExecutionContext>' is missing the following properties from type 'ExecutionContext': queryObjects, evaluate, evaluateHandle
                                                Type 'PageEventObj[K]' is not assignable to type 'never'.
                                                  Type 'Error | Dialog | ConsoleMessage | Worker | Frame | Request | Response | { title: string; metrics: Metrics; } | Page' is not assignable to type 'never'.
                                                    Type 'Error' is not assignable to type 'never'.
                                                      Type 'BrowserEventObj[K]' is not assignable to type 'undefined'.
                                                        Type 'Target' is not assignable to type 'undefined'.

68   const waPage = await getWhatsappPage(browser);
                                          ~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! venom-bot@1.0.7 build: `npm run build:wapi && npm run build:middleware && npm run build:jsQR && tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the venom-bot@1.0.7 build script.

**Comment by joaosouz4** [comment]
this was corrected in the last accepted PR involving the publication of AutoClose
