### ISSUE TITLE
Bug no sendText, promise nunca retorna.

### ISSUE THREAD

**Issue by joaovrgumiero** [orkestral/venom#483]
## Description

O problema é que quando desativa o Wi-FI do dispositivo, tem um delay até atualizar o state do client, possibilitando chamar o sendText nesse meio tempo.

Quando acontece isso, o sendText fica processando eternamente, não retorna nem sucesso nem erro na Promise.

Minha sugestão é colocar um timeout de processamento no sendText.

## Environment

- **Venom version(s):** 2.2.3
- **OS:** Ubuntu 20.04 LTS
- **Node version:** 12.20.0

## Steps to Reproduce

Basta desativar o Wi-FI do dispositivo conectado e chamar o método sendText em sequência.

**Comment by orkestral** [comment]
fixed in version 3.0.5
