### ISSUE TITLE
npm run start fails with "error TS6053: File 'app.ts' not found."

### ISSUE THREAD

**Issue by nisarhassan12** [orkestral/venom#487]
## Description

I tried running `npm start` after doing `npm install && npm run build` but it failed with the following error:

![image](https://user-images.githubusercontent.com/46004116/103440306-2c631c00-4c66-11eb-9370-e7587d544f89.png)

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. clone the repo.
2. run `npm install && npm run build`.
3. try `npm start` once the build finishes.

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by edgardmessias** [comment]
It is not a BUG, it is used only for development purpose.

If you want use venom-bot, please read the documentation: https://orkestral.github.io/venom/#installation
