### ISSUE TITLE
how to use onparticipantschanged function

### ISSUE THREAD

**Issue by xshion13** [orkestral/venom#5]
i never used this feature maybe someone can explain or provide an working example about this, just for send message if someone is added or kicked from one group

**Comment by orkestral** [comment]
yes it checks if there is any change in the group like when someone enters or leaves

**Comment by xshion13** [comment]
> yes it checks if there is any change in the group like when someone enters or leaves

i mean how to do it, i dont know how to leave message, if someone is kicked leave rules message. if someone is added a welcome message is sended
