### ISSUE TITLE
Mark as read on group chats

### ISSUE THREAD

**Issue by Cempakers87** [orkestral/venom#508]
Hello, if we execute getAllGroups function it will return list group array object data including unreadCount. Let say there is a group named "Testing" has unreadCount:7.

How can we mark that message as read (change unreadCount to 0) via venom without manually open apps on smartphone or WhatsApp web?

Please help. Thanks.

**Comment by diogo-palma** [comment]
Hi, Venom have a function:
await client.sendSeen('NUMBER_OF_GROUP@g.us');

**Comment by Cempakers87** [comment]
> Hi, Venom have a function:
> await client.sendSeen('[NUMBER_OF_GROUP@g.us](mailto:NUMBER_OF_GROUP@g.us)');

Hi @diogo-palma,
actually I have already try that function you mention but somehow doesn't work. That's why I open an issue.
Now it works after you answered me and I re-try.
Big thanks.
