### ISSUE TITLE
sendFile() is not sending a caption.

### ISSUE THREAD

**Issue by antonio-couto** [orkestral/venom#51]
sendFile() is not sending a caption ou perhaps i am doing something wrong.
Do i must do any change on the caption string ? I am just sending 'test', but is no working, below the screen on my wa, the name it working ok:

![image](https://user-images.githubusercontent.com/10817547/86032940-86143080-ba0e-11ea-9a35-0ca23c89a814.png)

**Comment by joaosouz4** [comment]
can you send us your used shipping function?

**Comment by antonio-couto** [comment]
This is the parameters on my call:

![image](https://user-images.githubusercontent.com/10817547/86034564-371bca80-ba11-11ea-936f-85d14ff36004.png)


I am using this function from the file:
C:\Source\NodeJs\venom\src\api\layers\sender.layer.ts

/**
   * Sends file from path
   * @param to Chat id
   * @param path File path
   * @param filename
   * @param caption
   */
  public async sendFile(
    to: string,
    path: string,
    filename: string,
    caption?: string
  ) {
    const base64 = await fileToBase64(path);
    return this.sendFileFromBase64(to, base64, filename, caption);
  }

**Comment by antonio-couto** [comment]
I making more tests and i found out that the problem with caption is on pdf files, image file its working.

![image](https://user-images.githubusercontent.com/10817547/86040074-c4631d00-ba19-11ea-9061-7f01ae908143.png)

**Comment by antonio-couto** [comment]
more test, for now the only file that works caption is on image:

![image](https://user-images.githubusercontent.com/10817547/86042954-553bf780-ba1e-11ea-9f29-db0b0b68043b.png)

**Comment by smashah** [comment]
@antonio-couto You can't add a caption (even on the app) when sending a document. Send the document then reply to the message if you want to caption it.

**Comment by joaosouz4** [comment]
@antonio-couto 

that's the answer,
> @antonio-couto You can't add a caption (even on the app) when sending a document. Send the document then reply to the message if you want to caption it.

 you can also enter the name of the file you want. i will close this topic
