### ISSUE TITLE
sendFile many requests

### ISSUE THREAD

**Issue by misterxis** [orkestral/venom#511]
What would be the easiest way to implement more than 800 requests for a sendFile in Venom-Bot?

I tried to use GuzzleHTTP in PHP, but it is overloading.

**Comment by antirek** [comment]
Do you need a ban from whatsapp? 800 reqs, oh-m...

for example, use cron for sending 5 request per minute

and what is mean GuzzleHTTP in PHP? Your system on php? And you try use venom-bot? May be #488 for you? http-api for venom-bot from @allburov

**Comment by misterxis** [comment]
I use a API based on #MyZAP and the GuzzleHTTP is a framework for PHP to post async requests. The requests are for numbers that have agreed to receive the file. Five reqs per minute are too slow.

**Comment by misterxis** [comment]
Solution in issue closed #414
