### ISSUE TITLE
can not find any function to handle story replies

### ISSUE THREAD

**Issue by MarziehMahdavi** [orkestral/venom#52]
does Venom bot have any function to handle story replies?
**_onMessage()_** function not working for story replies.

**Comment by kingaspx** [comment]
Have you tested the onAnyMessage() function?

**Comment by MarziehMahdavi** [comment]
> Have you tested the **_onAnyMessage()_** function?

It's also not working

**Comment by bhavya32** [comment]
@joaosouz4 I believe its a feature request.

**Comment by joaosouz4** [comment]
@jonalan7  Look this.

**Comment by jonalan7** [comment]
@MarziehMahdavi **Could you be clearer in your question?**

**Comment by bhavya32** [comment]
@MarziehMahdavi I believe he is asking that If someone replies to a particular message, i.e. by right swiping on the message, auto-reply does not work.

**Comment by joaosouz4** [comment]
@jonalan7 @bhavya32 @MarziehMahdavi  It took me a while to understand your question to the people above, but I believe that you are referring to responses sent by the images published in the storie "snap do whatsapp", I will look for a solution to this proposal
