### ISSUE TITLE
Identificar que o celular foi desconectado da internet.

### ISSUE THREAD

**Issue by JoaoGabrielDePaula** [orkestral/venom#522]
Boa tarde,

não estou conseguindo capturar o estado de celular desconectado da internet.

estou  monitorando o "statusSession"

```
venom
        .create(
            //session
            'sessionName', //Pass the name of the client you want to start the bot
            //catchQR
            (base64Qrimg, asciiQR, attempts, urlCode) => {
                console.log('Number of attempts to read the qrcode: ', attempts);
                console.log('Terminal qrcode: ', asciiQR);
                console.log('base64 image string qrcode: ', base64Qrimg);
                console.log('urlCode (data-ref): ', urlCode);
            },
            // statusFind
            (statusSession, session) => {
                console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
                //Create session wss return "serverClose" case server for close
                console.log('Session name: ', session);
            },
            // options
            {
                folderNameToken: 'tokens', //folder name when saving tokens
                mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
                headless: true, // Headless chrome
                devtools: false, // Open devtools by default
                useChrome: true, // If false will use Chromium instance
                debug: false, // Opens a debug session
                logQR: true, // Logs QR automatically in terminal
                browserWS: '', // If u want to use browserWSEndpoint
                browserArgs: [''], // Parameters to be added into the chrome browser instance
                puppeteerOptions: {}, // Will be passed to puppeteer.launch
                disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
                disableWelcome: true, // Will disable the welcoming message which appears in the beginning
                updatesLog: true, // Logs info updates automatically in terminal
                autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
                createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
            }
        ).then((client) => {
            start(client);
        }).catch((erro) => {
            console.log(erro);
        }
    );
```

e o "state" do evento "onStateChange"

```
function start(client) {

    client.onStateChange((state) => {
        console.log('State changed: ', state);
        // force whatsapp take over
        if ('CONFLICT'.includes(state)) client.useHere();
        // detect disconnect on whatsapp
        if ('UNPAIRED'.includes(state)) console.log('logout');
    });
      
      // function to detect incoming call
    client.onIncomingCall(async (call) => {
        console.log(call);
        client.sendText(call.peerJid, "Sorry, I still can't answer calls");
    });

    client.onMessage((message) => {
        if (message.body === 'Hi' && message.isGroupMsg === false) {
        client
            .sendText(message.from, 'Welcome Venom 🕷')
            .then((result) => {
            console.log('Result: ', result); //return object success
            })
            .catch((erro) => {
            console.error('Error when sending: ', erro); //return object error
            });
        }
    });
}

```

Alguém pode me orientar?

**Comment by diogo-palma** [comment]
não aparece nada no console?

**Comment by JoaoGabrielDePaula** [comment]
Não aparece nada... desconecto o celular e espero por tempo bastante tempo... mas nenhum retorno...

Já o CONFLIT é retornado quando entro no web.whatsApp.

Alguma sugestão?

**Comment by diogo-palma** [comment]
so aparece se vc enviar uma msg ou interagir com alguma função do client 
por exemplo, se vc desconectar o celular da internet o status nao vai te informar nada, mas se vc mandar uma msg pelo venom ele vai te retornar o STATUS TIMEOUT, porem quando voltar a internet do celular, essa mesma msg vai ser enviada, da uma lida nesse post abaixo..
#379

**Comment by JoaoGabrielDePaula** [comment]
Vou dar uma olhada @diogo-palma... muito obrigado até então!

**Comment by bbf6** [comment]
In my case, everything was working fine during the lasts months. Today I just stop my app to add a string to an array (anything weird about it); now, when I try to restart, The console throws back this log:

```
info:     Checking for updates
info:     You're up to date
info:     [session:browser] Initializing browser...
info:     [session:client] Initializing...
info:     [session:client] Auto close configured to 60s
info:     [session:client] Auto close configured to 60s
info:     [session:client] Closing the page
error:    [session:page] Page Closed
warn:     [session:client] Phone not connected
(node:1314368) UnhandledPromiseRejectionWarning: Phone not connected
```
When I notice this, I whent for the update with the "npm update" command but that does not solve the problem. I also have tried deleting the "session.data.json" file and capture a new QR code, but I get the same result. The phone has internet I tested.

**Comment by bbf6** [comment]
> 
> 
> In my case, everything was working fine during the lasts months. Today I just stop my app to add a string to an array (anything weird about it); now, when I try to restart, The console throws back this log:
> 
> ```
> info:     Checking for updates
> info:     You're up to date
> info:     [session:browser] Initializing browser...
> info:     [session:client] Initializing...
> info:     [session:client] Auto close configured to 60s
> info:     [session:client] Auto close configured to 60s
> info:     [session:client] Closing the page
> error:    [session:page] Page Closed
> warn:     [session:client] Phone not connected
> (node:1314368) UnhandledPromiseRejectionWarning: Phone not connected
> ```
> 
> When I notice this, I whent for the update with the "npm update" command but that does not solve the problem. I also have tried deleting the "session.data.json" file and capture a new QR code, but I get the same result. The phone has internet I tested.

Ok, I tried restarting the phone, reinstalling WhatsApp, deleting the node_modules, updating the server with apt upgrade and finally rebooting the system. I don't know which of this was the solution, but my app is working again.

**Comment by diogo-palma** [comment]
you can see  what is happening when you put in options headless: false, useChrome: true, when use this config you will see browse open...

**Comment by diogo-palma** [comment]
put autoClose: 0 too

**Comment by diogo-palma** [comment]
but remember when u put this your browser don't close auto when you start a create venom isntance...

**Comment by jonalan7** [comment]
**The problem was solved with a new update!** [https://github.com/orkestral/venom#getting-started](https://github.com/orkestral/venom#getting-started)
