### ISSUE TITLE
getAllChats  dont return profilePicThumbObj{} 

### ISSUE THREAD

**Issue by diogo-palma** [orkestral/venom#523]
## Description

Hello, before when returning the getAllCats () function
it had at least the first 20 urls of the photos of the contacts
now it's not bringing any, why will it be?
[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):*2.2.3*

**Comment by Cempakers87** [comment]
same with getAllGroups functions, now each group doesn't have profilePicThumbObj

**Comment by jonalan7** [comment]
**Whatsapp updated scripts, we will have to take a look at where they put the address.**
