### ISSUE TITLE
Arquivo Corel Draw (.CDR) não é reconhecido como arquivo válido base64, erro ao enviar arquivo.

### ISSUE THREAD

**Issue by zerobgk** [orkestral/venom#537]
## Description

Quando tento enviar um arquivo Corel .CDR para um chat qualquer me é retornado um erro "Invalid base64!' (Acredito que possa ser algo com o mimetype do Corel (application/x-vnd.corel.zcf.draw.document+zip)
Mas consigo receber o arquivo facilmente e salvá-lo em .cdr

## Environment

- **Venom version(s):** 2.2.3
- **Browser:** Chromium 88.0.4298.0
- **OS:** Windows 10
- **Node version:** v14.15.0

## Steps to Reproduce

1. Recebo um arquivo via API (Express), o arquivo é salvo em uma pasta local. (O arquivo é salvo normalmente, sem nenhum problema)
2. Tento enviar o mesmo arquivo pelo client com o método sendFile (Exemplo: client.sendFile('999999999@c.us', 'path/file.cdr')
3. Recebo o erro:  { erro: true, to: '(numero)@c.us', text: 'Invalid base64!' }

## Log Output

{ erro: true, to: '558781615939@c.us', text: 'Invalid base64!' }

O logger level no 'silly' não altera o output.

```
If relevant, paste all of your Log Output
```

## Your Code

O objeto do venom é encapsulado por outro objeto que criei, e seus métodos são repassados.

`
async sendFile(to, filePath, fileName) {
        return await this.client.sendFile(to, filePath, fileName)
}
`
## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/57375055/105227603-49da2600-5b40-11eb-9569-cb1825ac356b.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by antirek** [comment]
How many bytes (Kbytes or Mbytes) in your Corel Draw document?

**Comment by zerobgk** [comment]
Hello, sorry for the delay. The Corel Draw document i've tested have 865KB. I did test too with direct Whatsapp Web and it works but at venom no.

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
