### ISSUE TITLE
Não está permitindo debugar aplicação gerando um erro

### ISSUE THREAD

**Issue by mario-berardo** [orkestral/venom#538]
## Description
Causa um erro ao debugar no VSCODE

Could not read source map for file:///c:/testebot/node_modules/venom-bot/dist/index.js: ENOENT: no such file or directory, open 'c:\testebot\node_modules\venom-bot\dist\index.js.map'

[Description of the bug, When Issue Happens]

## Environment
Venom version : ùltima
VSCode : 1.50.1
Node : 12.16.1

## Steps to Reproduce

1. npm install
2. npm install venom-bot --save
3. Run -> Iniciar Depuração -> Selecionar NodeJS

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ferbsferbs** [comment]
how did you fix?
