### ISSUE TITLE
Venom just breaks if has no authentication

### ISSUE THREAD

**Issue by effer89** [orkestral/venom#54]
Hi,

If I leave a sessions waiting for auth It breaks when auto close run. Even if I try reopen the same same session it won't work.

![image](https://user-images.githubusercontent.com/13169985/86166865-e200b700-baeb-11ea-9c21-354c066a5026.png)

Won't work with catch block as well.

Btw, amazing work :D

**Comment by NabiilahDatabase** [comment]
try this code before creating venom session:
`
const fs = require('fs-extra');
. . .
const cacheExists = await fs.pathExists(`./${sessionName}`);
    if (cacheExists) {
        fs.remove(`./${sessionName}/Default/Service Worker/Database/MANIFEST-000001`);
    }
`

**Comment by joaosouz4** [comment]
this has been fixed in the new version
