### ISSUE TITLE
need a little info

### ISSUE THREAD

**Issue by kikiixyz** [orkestral/venom#540]
whether this will send interactive buttons?
`https://github.com/orkestral/venom/blob/72e24d35cd8d5ff6472095b44fce79c3af0e32c6/src/lib/wapi/business/send-message-with-buttons.js#L55`

**Comment by kikiixyz** [comment]
https://github.com/orkestral/venom/blob/72e24d35cd8d5ff6472095b44fce79c3af0e32c6/src/lib/wapi/business/send-message-with-buttons.js#L55

**Comment by antirek** [comment]
try use it  :)
