### ISSUE TITLE
Como usar o método sendMessageOptions

### ISSUE THREAD

**Issue by karlosgaldino** [orkestral/venom#549]
Não consigo e não encontrei comentários de quem conseguiu usar o método de respostas com opções.

Por padrão ele recebe um o terceiro parametro como vázio, exemplo: "quotedMessageId = {}".

Na prática, qual a maneira correta de usar este recurso?

await client.
        .sendMessageOptions(
          '000000000000@c.us',
          'This is a reply!',
           {
              quotedMessageId: reply,
            }
        )
        .then((retorno) => {
          resp = retorno;
        })
        .catch((e) => {
          console.log(e);
        });

**Comment by romulloleal** [comment]
quotedMessage é o id da mensagem mencionada. Sabe aquela opção de "responder" no whats? É exatamente isso.
