### ISSUE TITLE
Nova versão do venom-bot não está permitindo debug

### ISSUE THREAD

**Issue by mario-berardo** [orkestral/venom#551]
## Description
Nova versão não está baixando os arquivos com extensão .map para permitir debug da aplicação com VSCode. 

[Description of the bug, When Issue Happens]
Causa um erro no VSCode.

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
