### ISSUE TITLE
Phone disconnected after a while

### ISSUE THREAD

**Issue by jonit-dev** [orkestral/venom#553]
## Description

Hey guys!  Venombot is disconnecting after a while (recurrently). What may be the issue?
Nothing changed on my code. I'm just submitting requests to it like I always used to:

```
 
app-bots        | info:     Checking for updates
app-bots        | info:     You're up to date
app-bots        | info:     [A1:browser] Initializing browser...
app-bots        | info:     [A1:client] Initializing...
app-bots        | info:     [A1:client] Auto close configured to 60s
app-bots        | info:     [A1:client] Auto close configured to 60s
app-bots        | info:     [A1:client] Closing the page
app-bots        | error:    [A1:page] Page Closed
app-bots        | warn:     [A1:client] Phone not connected
app-bots        | (node:73) UnhandledPromiseRejectionWarning: Phone not connected
app-bots        | (node:73) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
app-bots        | (node:73) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

- **Venom version(s):** 2.2.3
- **Browser:** ?
- **OS:** Ubuntu 18
- **Node version:** 15

## Steps to Reproduce

1. Start your bot, make sure your QR code is connected
2. After submitting some requests, it simply disconnects (I'm running on docker)

**Comment by dmastag** [comment]
I got the same issue on a Fresh Ubuntu VPS

**Comment by jonit-dev** [comment]
@dmastag I've tried to review my code and everything, but I guess it's some problem with this module itself.
It just disconnects randomly, sometimes... I don't know what's triggering it

**Comment by jonit-dev** [comment]
Yeah, I still have this issue.
What I'm doing to remediate (at least for now) is triggering a docker-compose restart on the bots container, every few hours, to make sure it "refreshes" the connection.

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
