### ISSUE TITLE
Recieve document's isMedia and isMMS  value

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#554]
Recieve document (Excel, word, pdf ...)  message detail isMedia and isMMS  are both false
Image or GIF or Video isMedia  is  true

**Comment by claudioscarpafilho** [comment]
Além dessas duas condições (isMedia e isMMS), eu também verifico o valor da variável 'type'.

if (message.isMedia === true || message.isMMS === true || message.type === 'ptt' || message.type === 'sticker' || message.type === 'document') 

Dessa forma, resolve esse problema.

**Comment by Lucipher** [comment]
> Além dessas duas condições (isMedia e isMMS), eu também verifico o valor da variável 'type'.
> 
> if (message.isMedia === true || message.isMMS === true || message.type === 'ptt' || message.type === 'sticker' || message.type === 'document')
> 
> Dessa forma, resolve esse problema.

Well noted with thanks !
