### ISSUE TITLE
Métodos nao estão trazendo chats. 

### ISSUE THREAD

**Issue by tomsilva** [orkestral/venom#555]
## Description

Oi Pessoal Boa tarde a todos..

Estava revisando aqui os metodos , getChatById, getChat, traz todas as informacoes do chat porem nao vem as conversas.
Esta certo isso mesmo...

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jonalan7** [comment]
**To list all messages in a chat, simply use the client.getAllUnreadMessages(); function #390**

**Comment by lucaspiressimao** [comment]
> To list all messages in a chat, simply use the client.getAllUnreadMessages(); function #390

This method is not working for me, it returns an empty array.
No meu caso eu tentei usar o getAllUnreadMessages mas retornou um array vazio.

**Comment by jonalan7** [comment]
> > To list all messages in a chat, simply use the client.getAllUnreadMessages(); function #390
> 
> This method is not working for me, it returns an empty array.
> No meu caso eu tentei usar o getAllUnreadMessages mas retornou um array vazio.

**For me it works normally! Remember that this function returns all unread messages!**

**Comment by jonalan7** [comment]
**For loading every message use loadAndGetAllMessagesInChat(chatId, true, true)**

**Comment by aislanspeedio** [comment]
> **For loading every message use loadAndGetAllMessagesInChat(chatId, true, true)**

This method is returning an error `undefined` function in the latest version
