### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#569]
Até a pouco estava funcionando corretamente, porém vi que ocorreu esse erro `Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined`. Pesquisando em outras libs, vi que esse erro ocorre quando o source do web.whatsapp atualiza, alguém mais passando por isso?

**Comment by jonalan7** [comment]
**There is currently no way to do that! But it is a good idea!**

**Comment by jonalan7** [comment]
**Qual é a função que esta dando este error? Acredito que seja o seu projeto que esteja passando algum parâmetro errado. Aconselho a revisar o mesmo!**

**Comment by gustavobborges** [comment]
to passando pela mesma coisa.... ha 1 mes tava rodando.. agora ta dando "info:     [session:client] Auto close configured to 60s
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined" e não salva o Token.... 
alguém conseguiu uma solução?

**Comment by developerdevice** [comment]
> to passando pela mesma coisa.... ha 1 mes tava rodando.. agora ta dando "info: [session:client] Auto close configured to 60s
> Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined" e não salva o Token....
> alguém conseguiu uma solução?

Pelo menos no meu caso, o erro aconteceu porque eu estava rodando a função `start() `duas vezes.

**Comment by marciusbezerra** [comment]
Estou passando pelo mesmo problema: **Evaluation failed: TypeError: Cannot read properties of undefined (reading 'attributes')**

No meu caso, ocorre quando eu chamo o método reply (que antes funcionava normalmente):

`await venomClient.reply(message.from, cleanText, message.id.toString());`

Erro:
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'attributes')
at Object.window.WAPI.window.WAPI.scope (C:\...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:34545)
at Object.window.WAPI.window.WAPI.checkIdMessage (...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:31665)
at async Object.window.WAPI.window.WAPI.reply (...\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:55620)
at ExecutionContext._evaluateInternal (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async ExecutionContext.evaluate (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
```

**Comment by marciusbezerra** [comment]
> > to passando pela mesma coisa.... ha 1 mes tava rodando.. agora ta dando "info: [session:client] Auto close configured to 60s
> > Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined" e não salva o Token....
> > alguém conseguiu uma solução?
> 
> Pelo menos no meu caso, o erro aconteceu porque eu estava rodando a função `start() `duas vezes.

Como evitar de chamar a função start() 2 vezes? como eu sei se já chamei?

**Comment by riservato-thiagomelo** [comment]
O mesmo está acontecendo comigo.

- não estou invocando start() mais de 1x;
- fazer downgrade não adianta;
- o stack trace não mostra qual função causa o erro;
- as vezes o erro some, as vezes aparece.

**Comment by marciusbezerra** [comment]
works for me in 4.0.2 version!
