### ISSUE TITLE
Automatically mark messages as read on client.onMessage event. Marcar automaticamente as mensagens como lidas no onMessage

### ISSUE THREAD

**Issue by vqmacedo** [orkestral/venom#570]
When I get the messages on client.onMessage it remains in whatsapp as unread, is there any parameter to always set as readen?

Quando as mensagens são recebidas no onMessage, eles continuam com a sinalização de não lidas no whatsapp. Tem alguma forma de marcar automaticamente todas elas, quando passarem por esse metodo como lidas?

**Comment by romulloleal** [comment]
await client.sendSeen('000000000000@c.us');

**Comment by vqmacedo** [comment]
Imaginei que pudesse ter outra forma, fico com receio de chegarem diversas mensagens e na primeira já marco todas como lidas

**Comment by romulloleal** [comment]
> Imaginei que pudesse ter outra forma, fico com receio de chegarem diversas mensagens e na primeira já marco todas como lidas

Mas é exatamente isso que o whatsapp faz quando você abre um chat. Ele marca todas as demais como lidas do determinado chat.

**Comment by vqmacedo** [comment]
Blz, Obrigado. Você por acaso usa o client.getAllUnreadMessages() ?? Quando rodo ele volta sempre um array em branco, mas quando rodo o getAllChats(), vem com a propriedade unreadCount preenchida com os valores das mensagens não lidas.

**Comment by vqmacedo** [comment]
Blz, Obrigado. Você por acaso usa o client.getAllUnreadMessages() ?? Quando rodo ele volta sempre um array em branco, mas quando rodo o getAllChats(), vem com a propriedade unreadCount preenchida com os valores das mensagens não lidas.

> > Imaginei que pudesse ter outra forma, fico com receio de chegarem diversas mensagens e na primeira já marco todas como lidas
> 
> Mas é exatamente isso que o whatsapp faz quando você abre um chat. Ele marca todas as demais como lidas do determinado chat.

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
