### ISSUE TITLE
When I try download an audio from Whatsapp i receive this reponse

### ISSUE THREAD

**Issue by NiedsonEmanoel** [orkestral/venom#572]
(node:1288) UnhandledPromiseRejectionWarning: Error: message is missing critical data needed to download the file.
    at Whatsapp.<anonymous> (/home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:233:35)
    at step (/home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:46:23)
    at Object.next (/home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:27:53)
    at /home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:17:12)
    at Whatsapp.decryptFile (/home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/whatsapp.js:226:16)
    at EventEmitter.client.onMessage (/home/niedson/Myzap-Flow/index.js:279:39)
    at EventEmitter.emit (events.js:198:13)
    at /home/niedson/Myzap-Flow/node_modules/venom-bot/dist/api/layers/listener.layer.js:159:90
(node:1288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by clovisdanielss** [comment]
I'm getting the same error in some connections. After some restarts, it works again.
Do not know anything, just that clientUrl is coming empty.

**Comment by NiedsonEmanoel** [comment]
> Estou recebendo o mesmo erro em algumas conexões. Após algumas reinicializações, ele funciona novamente.
> Não sei de nada, só que clientUrl está vindo vazio.
> 
> Acho que talvez seja a web do WhatsApp. Porque eu também tenho alguns áudios vazios hoje usando. Quando reiniciei funcionou.

Você deve ser BR, vou falar em Português (case you don't understand, warn-me).

Eu tenho uma pergunta... Como você reiniciou?
Você reiniciou sua aplicação, o pupetter ou o venom?

**Comment by NiedsonEmanoel** [comment]
Resolvido.

Defeito intermitente @orkestral

**Comment by clovisdanielss** [comment]
> > Estou recebendo o mesmo erro em algumas conexões. Após algumas reinicializações, ele funciona novamente.
> > Não sei de nada, só que clientUrl está vindo vazio.
> > Acho que talvez seja a web do WhatsApp. Porque eu também tenho alguns áudios vazios hoje usando. Quando reiniciei funcionou.
> 
> Você deve ser BR, vou falar em Português (case you don't understand, warn-me).
> 
> Eu tenho uma pergunta... Como você reiniciou?
> Você reiniciou sua aplicação, o pupetter ou o venom?

Cara, reiniciando o Venom mesmo. 
Me diz uma coisa, porque a issue foi fechada ?

**Comment by NiedsonEmanoel** [comment]
Eu fechei pois é intermitente, mas já reabri.

Obrigado.

**Comment by clovisdanielss** [comment]
> Eu fechei pois é intermitente, mas já reabri.
> 
> Obrigado.

Beleza, mas me responde uma coisa, o problema persistiu pra você ? Aconteceu novamente ?

**Comment by edgardmessias** [comment]
Façam um teste com o [downloadMedia](https://orkestral.github.io/venom/classes/whatsapp.html#downloadmedia), ele retorna um base64

**Comment by NiedsonEmanoel** [comment]
> > Eu fechei pois é intermitente, mas já reabri.
> > Obrigado.
> 
> Beleza, mas me responde uma coisa, o problema persistiu pra você ? Aconteceu novamente ?
> 
> Hoje de manhã aconteceu novamente comigo, fiz o mesmo procedimento e parou. Mas queria saber o porque desse erro.
> Valeu.
> 
> (Okay, but answer me one thing, did the problem persist for you? Did it happen again?
> 
> This morning it happened to me again, I did the same procedure and it stopped. But I wanted to know why this error.
> Thanks.)

Aqui no meu projeto está tudo ok, por enquanto.
Vou tentar implementar a solução que o @edgardmessias sugeriu

**Comment by clovisdanielss** [comment]
Também não tive mais problemas.

Mesmo mantendo o decryptFile.

**Comment by NiedsonEmanoel** [comment]
Defeito intermitente.
Fechando o issue.

**Comment by rafaelsiq** [comment]
@clovisdanielss  vc aplicou alguma solução? No meu projeto o problema persiste, já reinstalei o venom mas não solucionou o problema.
