### ISSUE TITLE
How to get waPage object

### ISSUE THREAD

**Issue by adierebel** [orkestral/venom#573]
previously, I got the `waPage` through `client` object

```javascript
venom.create()
	.then((client) => { client.waPage })
	.catch((error) => { });
```

but it is obtained after a promise is given. I want to get `waPage` when the `create` function is called. How to do it?

**Comment by jonalan7** [comment]
**There is currently no way to do that! But it is a good idea!**

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
