### ISSUE TITLE
Funções de decriptFile e downloadMedia estão retornando arquivo corrompido

### ISSUE THREAD

**Issue by jaderesp** [orkestral/venom#580]
Ao realizar a tentativa de descriptografar os arquivos recebidos para converter para base64 o resultado da decodificação não gera um arquivo legível, ou seja gera um arquivo corrompido (provavelmente não descriptografado).
Exemplo:
```
                     const buffer = await client.decryptFile(message);
OU
                    const buffer = await client.downloadMedia(message.id);

**Comment by clovisdanielss** [comment]
Rapaz, aqui o decryptFile não gera problemas.
O downloadMedia, quando eu transformo a string em buffer, de fato eu tive problemas. 

Como tá o resto do código ?

**Comment by jaderesp** [comment]
`    const buffer = await client.downloadMedia(message.id);
                    let base64data = Buffer.from(buffer).toString('base64');
                    let imagebase64 = 'data:' + message.mimetype + ';base64,' + base64data;

                    console.log("Extenção do arquivo da mensagem: ",message)

                    console.log("Base64 do arquivo: ",imagebase64)

                    /* upload file */
                    ext = mime.extension(message.mimetype);
                    var now = new Date();   
                    var  fileName = "FILE_TESTE_" + now.getSeconds() + "." + ext;
                    await fs.writeFileSync("./public/uploads" + fileName, imagebase64);`

**Comment by clovisdanielss** [comment]
> `
> 
> ```
>                 const buffer = await client.downloadMedia(message.id);
>                 let base64data = Buffer.from(buffer).toString('base64');
>                 let imagebase64 = 'data:' + message.mimetype + ';base64,' + base64data;
> 
>                 console.log("Extenção do arquivo da mensagem: ",message)
> 
>                 console.log("Base64 do arquivo: ",imagebase64) 
> 
>                 /* upload file */
>                 ext = mime.extension(message.mimetype);
>                 var now = new Date();   
>                 var  fileName = "FILE_TESTE_" + now.getSeconds() + "." + ext;
>                 await fs.writeFileSync("./public/uploads" + fileName, imagebase64);`
> ```

Cara, na variável base64data tu quer é o dado em binário, não é ?
Nesse caso, tua constante que tu chamou de buffer, no caso seria um bufferString pq o valor resultante é uma string.

Então você deveria chamar 
`let base64data = Buffer.from(bufferString, 'base64');`

A referência pode ser vista aqui no [node](https://nodejs.org/api/buffer.html#buffer_static_method_buffer_from_string_encoding)

**Comment by jaderesp** [comment]
> 
> 
> Ao realizar a tentativa de descriptografar os arquivos recebidos para converter para base64 o resultado da decodificação não gera um arquivo legível, ou seja gera um arquivo corrompido (provavelmente não descriptografado).
> Exemplo:
> 
> ```
>                      const buffer = await client.decryptFile(message);
> OU
>                     const buffer = await client.downloadMedia(message.id);
> ```

Pessoal obrigado pela ajuda de todos, vc tambem @clovisdanielss, eu não sei por que motivo a função que eu utilizava a meses esse codigo e ele parou de funcionar,

porém graças a um dos amigos do grupo o Eduardo em enviou codigo funcional do projeto dele, e testei aqui voltou a funcionar, porém precisei fazer várias alterações no projeto do bot em php, mas agora voltou a funcionar.

segue o codigo de como ficou:


`  



                    const buffer = await client.decryptFile(message);
                    /* criar o base64 */
                    let base64data = Buffer.from(buffer).toString('base64');
                    let imagebase64 = 'data:' + message.mimetype + ';base64,' + base64data;
                    
                    var telefone = ((String(`${message.from}`).split('@')[0]).substr(2));
                    let date_ob = new Date();
                    let date = ("0" + date_ob.getDate()).slice(-2);
                    let month = ("0" + (date_ob.getMonth() + 1)).slice(-2);
                    let year = date_ob.getFullYear();
                    let miliseconds = date_ob.getMilliseconds();
                    const fileName = `${telefone}-${year}${month}${date}-${miliseconds}`;
                    const file = `${fileName}.${mime.extension(message.mimetype)}`;
                    try {
                        fs.writeFileSync(`./public/uploads/${file}`, buffer);

                    }catch(error){
                        console.log("Erro ao processar o arquivo: ",error)
                        return;
                    }`

**Comment by jaderesp** [comment]
> 
> 
> Ao realizar a tentativa de descriptografar os arquivos recebidos para converter para base64 o resultado da decodificação não gera um arquivo legível, ou seja gera um arquivo corrompido (provavelmente não descriptografado).
> Exemplo:
> 
> ```
>                      const buffer = await client.decryptFile(message);
> OU
>                     const buffer = await client.downloadMedia(message.id);
> ```

Pessoal obrigado pela ajuda de todos, vc tambem @clovisdanielss, eu não sei por que motivo a função que eu utilizava a meses esse codigo e ele parou de funcionar,

porém graças a um dos amigos do grupo o Eduardo em enviou codigo funcional do projeto dele, e testei aqui voltou a funcionar, porém precisei fazer várias alterações no projeto do bot em php, mas agora voltou a funcionar.

segue o codigo de como ficou:


`  



                    const buffer = await client.decryptFile(message);
                    /* criar o base64 */
                    let base64data = Buffer.from(buffer).toString('base64');
                    let imagebase64 = 'data:' + message.mimetype + ';base64,' + base64data;
                    
                    var telefone = ((String(`${message.from}`).split('@')[0]).substr(2));
                    let date_ob = new Date();
                    let date = ("0" + date_ob.getDate()).slice(-2);
                    let month = ("0" + (date_ob.getMonth() + 1)).slice(-2);
                    let year = date_ob.getFullYear();
                    let miliseconds = date_ob.getMilliseconds();
                    const fileName = `${telefone}-${year}${month}${date}-${miliseconds}`;
                    const file = `${fileName}.${mime.extension(message.mimetype)}`;
                    try {
                        fs.writeFileSync(`./public/uploads/${file}`, buffer);

                    }catch(error){
                        console.log("Erro ao processar o arquivo: ",error)
                        return;
                    }`

**Comment by diogo-palma** [comment]
o clientUrl ta vindo como deprecatedMms3Url

**Comment by jaderesp** [comment]
Pessal depois de testar por 3 dias a função esvaziamos os caches dos nossos projetos e realmente a o problema é atualização do venom, o decriptFile ta com problemas..emitindo seguinte erro:

**UnhandledPromiseRejectionWarning: Error:** message is missing critical data needed to download the file.

tradução: **mensagem está faltando dados críticos necessários para baixar o arquivo.**
😱😱😱

**Comment by jaderesp** [comment]
Pessal depois de testar por 3 dias a função esvaziamos os caches dos nossos projetos e realmente a o problema é atualização do venom, o decriptFile ta com problemas..emitindo seguinte erro:

**UnhandledPromiseRejectionWarning: Error:** message is missing critical data needed to download the file.

tradução: **mensagem está faltando dados críticos necessários para baixar o arquivo.**

**Comment by clovisdanielss** [comment]
Sim, olha aqui, esse PR resolveu. [PR](https://github.com/orkestral/venom/pull/584)

**Comment by jaderesp** [comment]
> 
> 
> Sim, olha aqui, esse PR resolveu. [PR](https://github.com/orkestral/venom/pull/584)
> 
> Relaciona essa ISSUE com ele.

valew @clovisdanielss  brigadão ai pela informação amigo. deu certo aqui.
