### ISSUE TITLE
Error trying to download the file. in decryptFile

### ISSUE THREAD

**Issue by matheust3** [orkestral/venom#585]
## Description

After the merge "fix: client url undefined # 584"

I've been getting the following error: "Error trying to download the file."

## Environment

- **Venom version(s):** [2.2.3]
- **Node version:** [v14.15.1]

## Steps to Reproduce

await client.decryptFile(message)

**Comment by adeja** [comment]
Same here

**Comment by jonalan7** [comment]
changes have been made to the repository! You must wait for a new update or build the current project.

**Comment by eltondcr** [comment]
this will solve your problem temporarily. Here we try to decrypt, if it fails, download it as base 64 and convert it to a file.

        `let buffer;
        try {
          buffer = await clients[clientId].decryptFile(message);
        } catch (error) {
          try {
            buffer = await clients[clientId].downloadMedia(message.id);
          } catch (error1) {
            console.log(error1);
          }
        }
 
        let base64Data = buffer.split(",")[1]; 
        await fs.promises.writeFile(pathFile, base64Data, "base64");

        console.log("ok");
`

**Comment by matheust3** [comment]
I fix this error in this [request](https://github.com/orkestral/venom/pull/586)

**Comment by matheust3** [comment]
waiting for Pull request
