### ISSUE TITLE
Error to send image as a sticker

### ISSUE THREAD

**Issue by matheust3** [orkestral/venom#587]
## Description

I'm getting a whatsapp error when I try to send an image as a sticker

## Environment

- **Venom version(s):** [2.2.3]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1-add a png file to a folder
2- call:
`client.sendImageAsSticker(msg.chatId, `${__dirname}/../fixtures/png.png`)`

Error received from whatsapp:
`{
  me: {
    id: '1',
    ref: '1@FfQ4CZiDfTb6aoKdMlMIjHmTpoKTHZfuufQCP0V3TmnqeorhrSIFLT5WAcsejG7G4Z+UutNDhZ4hHw==',
    refTTL: 20000,
    wid: {
      server: 'c.us',
      user: '5565xxxxxxx',
      _serialized: '5565xxxxxx@c.us'
    },
    connected: true,
    protoVersion: [ 0, 17 ],
    clientToken: 'T/TNQvXfBz1dGfGZbtr8oGbBMffIwXt6WwkywsC8QdCy8=',
    serverToken: '1@Hg4sVABjfIyEKHqX3EYoMgBZ6PKIVBwvbWYLfvTtZMWlb3+fv82Tdqr6Q4TAFqYt3r0zv1DL3EJXGrOA==',
    secret: 'XJwlmY/JanN/t7brhZtsxs/xG5gbIxxVrM5bBd2j/fTZAO0xfVXRagxh6fl1WHf/n7I+LEiAG+sfbHxzWofCEnRWk7eJgR11i/wL50XeGVd3QGx5jWUZdq01l2OXbAx3R/d6A30Qs9U6mibsx4fVr12tYx/O4tE49Ud02fH+/ckZRGQi7SNUxtw7LNOMr0OtvfOUtx2BWY',
    isResponse: 'false',
    battery: 71,
    plugged: false,
    lc: 'BR',
    lg: 'pt',
    locales: 'pt-BR',
    is24h: true,
    platform: 'android',
    phone: {
      wa_version: '2.21.2.18',
      mcc: '724',
      mnc: '005',
      os_version: '11',
      device_manufacturer: 'Xiaomi',
      device_model: 'laurel_sprout',
      os_build_number: 'qssi-user 11 RKQ1.200903.002 V12.0.4.0.RFQMIXM'
    },
    tos: 0,
    smbTos: 0,
    pushname: 'Matheus',
    blockStoreAdds: false,
    isVoipInitialized: false
  },
  to: {
    fromMe: true,
    remote: {
      server: 'g.us',
      user: '5565xxxxxx-1531776745',
      _serialized: '5565xxxxxxx-1531776745@g.us'
    },
    id: '18E67A91E2DD6A6F890B587FFE3A62C9DA',
    _serialized: 'true_5565xxxxxx-1531776745@g.us_18E67A91E2DD6A6F890B587F3A62C9DA',
    isOnline: null
  },
  erro: true,
  text: null,
  status: 'ERROR_EXPIRED',
  type: 'Sticker'
}`

**Comment by matheust3** [comment]
Same error to send sendImageAsStickerGif

**Comment by GladistonXD** [comment]
The same mistake happened to me today

**Comment by Finch47** [comment]
Same thing with sendImage

**Comment by matheust3** [comment]
I haven't found any documentation that explains how these methods work, and I can't understand using devTool.

We have to wait for the maintainer, maybe he can give a light.

**Comment by adeja** [comment]
Same here, with animated or regular sticker.

**Comment by clovisdanielss** [comment]
#602

**Comment by jonalan7** [comment]
**We are already solving! Soon a new update.**

**Comment by jonalan7** [comment]
**The problem was solved with a new update!**

**Comment by gifuzzz** [comment]
same problem with version 3.0.1
