### ISSUE TITLE
Stuck on initializing when bot restarts

### ISSUE THREAD

**Issue by clovisdanielss** [orkestral/venom#597]
## Description

When I create a client and run venom-bot, It works fine. After I connect, the token is generated. 
When I turn off the bot and try to re-create the client with the same token, I got stuck on initializing.

This bug was not happening on venom-bot 2.2.3.
## Steps to Reproduce

1. Start any application.
2. Connect the venom bot, reading the QR code.
3. Restart the application, with the same token.

## Log Output
Stuck here:
```
info:     [instance_1000050:browser] Initializing browser...
info:     [instance_1000050:client] Initializing...
```
## Expected

The bot should reconnect with the same token.

**Comment by tadeubarbosa** [comment]
If you are using a mobile phone try unblocking it. Sometimes when we try to connect to whatsapp web and the phone was blocked for a while, then we need to do it.

**Comment by clovisdanielss** [comment]
> If you are using a mobile phone try unblocking it. Sometimes when we try to connect to whatsapp web and the phone was blocked for a while, then we need to do it.

Thank you, but I already tried. It's not the blocked screen.

In my start method, which is called after create succeds, I call client.getHostDevice(), and now I'm seeing that it throws an error. 

`
Error: Evaluation failed: ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:1:16
    at ExecutionContext._evaluateInternal (C:\Users\clovi\source\repos\WhatsAppServer\node_modules\venom-bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any idea?
`

**Comment by clovisdanielss** [comment]
This issue is related to #595. 

But the issue was closed without answers.

**Comment by clovisdanielss** [comment]
With venom-bot 2.2.3, I got no problems. 

It's just on version 2.2.4

**Comment by clovisdanielss** [comment]
Solved with method onStreamChange, from version 2.2.4 changelog.
