### ISSUE TITLE
send file not work

### ISSUE THREAD

**Issue by thaziz** [orkestral/venom#598]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by annaselh** [comment]
You don't describe it more specific, but actually I got same topic error when sending image or file I got json with error message (not an exception). this is return I've got while sending a file or image.

` "Error when sending":{
   "me":{
      "id":"1",
      "ref":"1@dbLOMKoWyV4C08P3yapamYozJU57gMhgjlbwxIC7ix+HZXXC2Oj1ds0LUrk6I81HqW94ci62P5hp+A==",
      "refTTL":20000,
      "wid":{
         "server":"c.us",
         "user":"6281330144033",
         "_serialized":"6281330144033@c.us"
      },
      "connected":true,
      "protoVersion":[
         0,
         17
      ],
      "clientToken":"Re/kd3zewuSMN0pMEjOPR0KmNupJWJnRTHMo4mBD/JA=",
      "serverToken":"1@iQHcu6jw7gNMkhMFaBhhOcVQjr/vY+30b8MydjCvCRZO3pXU2pRbh8M6lF8iSXoLJEDot6q8wCGlQA==",
      "isResponse":"true",
      "battery":41,
      "plugged":false,
      "lc":"US",
      "lg":"en",
      "locales":"en-US",
      "platform":"smba",
      "phone":{
         "wa_version":"2.20.206.24",
         "mcc":"510",
         "mnc":"089",
         "os_version":"9",
         "device_manufacturer":"asus",
         "device_model":"ASUS_X00T_3",
         "os_build_number":"PKQ1.WW_Phone-16.2017.2009.087-20200826"
      },
      "tos":0,
      "smbTos":0,
      "pushname":"Sabit Studio",
      "blockStoreAdds":false,
      "isVoipInitialized":false
   },
   "to":{
      "fromMe":true,
      "remote":{
         "server":"c.us",
         "user":"6285791818225",
         "_serialized":"6285791818225@c.us"
      },
      "id":"N6EGSUC3ROYYHTJ2Z50T",
      "_serialized":"true_6285791818225@c.us_N6EGSUC3ROYYHTJ2Z50T",
      "isOnline":null
   },
   "erro":true,
   "text":"lagi dong",
   "status":false,
   "type":"sendImage",
   "filename":"6285791818225-from_me-wa-1613448934533.png",
   "mimeType":"image/png"
}`

**Comment by clovisdanielss** [comment]
Same thing here.

> You don't describe it more specific, but actually I got same topic error when sending image or file I got json with error message (not an exception). this is return I've got while sending a file or image.
> 
> ` "Error when sending":{ "me":{ "id":"1", "ref":"1@dbLOMKoWyV4C08P3yapamYozJU57gMhgjlbwxIC7ix+HZXXC2Oj1ds0LUrk6I81HqW94ci62P5hp+A==", "refTTL":20000, "wid":{ "server":"c.us", "user":"6281330144033", "_serialized":"6281330144033@c.us" }, "connected":true, "protoVersion":[ 0, 17 ], "clientToken":"Re/kd3zewuSMN0pMEjOPR0KmNupJWJnRTHMo4mBD/JA=", "serverToken":"1@iQHcu6jw7gNMkhMFaBhhOcVQjr/vY+30b8MydjCvCRZO3pXU2pRbh8M6lF8iSXoLJEDot6q8wCGlQA==", "isResponse":"true", "battery":41, "plugged":false, "lc":"US", "lg":"en", "locales":"en-US", "platform":"smba", "phone":{ "wa_version":"2.20.206.24", "mcc":"510", "mnc":"089", "os_version":"9", "device_manufacturer":"asus", "device_model":"ASUS_X00T_3", "os_build_number":"PKQ1.WW_Phone-16.2017.2009.087-20200826" }, "tos":0, "smbTos":0, "pushname":"Sabit Studio", "blockStoreAdds":false, "isVoipInitialized":false }, "to":{ "fromMe":true, "remote":{ "server":"c.us", "user":"6285791818225", "_serialized":"6285791818225@c.us" }, "id":"N6EGSUC3ROYYHTJ2Z50T", "_serialized":"true_6285791818225@c.us_N6EGSUC3ROYYHTJ2Z50T", "isOnline":null }, "erro":true, "text":"lagi dong", "status":false, "type":"sendImage", "filename":"6285791818225-from_me-wa-1613448934533.png", "mimeType":"image/png" }`

**Comment by clovisdanielss** [comment]
> ## Description
> When using sendFileFromBase64 or sendImageFromBase64 we are catching an error.
> 
> ## Steps to Reproduce
> 1. Try to send any file using any of those methods
> 
> ## Log Output
> ```
>"Error when sending":{ "me":{ "id":"1", "ref":"1@dbLOMKoWyV4C08P3yapamYozJU57gMhgjlbwxIC7ix+HZXXC2Oj1ds0LUrk6I81HqW94ci62P5hp+A==", "refTTL":20000, "wid":{ "server":"c.us", "user":"6281330144033", "_serialized":"6281330144033@c.us" }, "connected":true, "protoVersion":[ 0, 17 ], "clientToken":"Re/kd3zewuSMN0pMEjOPR0KmNupJWJnRTHMo4mBD/JA=", "serverToken":"1@iQHcu6jw7gNMkhMFaBhhOcVQjr/vY+30b8MydjCvCRZO3pXU2pRbh8M6lF8iSXoLJEDot6q8wCGlQA==", "isResponse":"true", "battery":41, "plugged":false, "lc":"US", "lg":"en", "locales":"en-US", "platform":"smba", "phone":{ "wa_version":"2.20.206.24", "mcc":"510", "mnc":"089", "os_version":"9", "device_manufacturer":"asus", "device_model":"ASUS_X00T_3", "os_build_number":"PKQ1.WW_Phone-16.2017.2009.087-20200826" }, "tos":0, "smbTos":0, "pushname":"Sabit Studio", "blockStoreAdds":false, "isVoipInitialized":false }, "to":{ "fromMe":true, "remote":{ "server":"c.us", "user":"6285791818225", "_serialized":"6285791818225@c.us" }, "id":"N6EGSUC3ROYYHTJ2Z50T", "_serialized":"true_6285791818225@c.us_N6EGSUC3ROYYHTJ2Z50T", "isOnline":null }, "erro":true, "text":"lagi dong", "status":false, "type":"sendImage", "filename":"6285791818225-from_me-wa-1613448934533.png", "mimeType":"image/png" }
> ```
> 
> 
> ## Additional context / Screenshot
> Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by clovisdanielss** [comment]
The error is generated in sendFileFromBase64 from sender.layer.ts

`      
        let result = await this.page.evaluate(
        ({ to, base64, filename, caption, type }) => {
          return WAPI.sendFile(base64, to, filename, caption, type);
        },
        { to, base64, filename, caption, type }
       )
`

In this line, the `page.evaluate` does not even call the callback. Still no idea why the error happens.

**Comment by tadeubarbosa** [comment]
Same error here. I'm using the latest version, using the example in docs.
That error is same with *sendFile* and *sendFileFromBase64*.

**Comment by tadeubarbosa** [comment]
> You don't describe it more specific, but actually I got same topic error when sending image or file I got json with error message (not an exception). this is return I've got while sending a file or image.
> 
> ` "Error when sending":{ "me":{ "id":"1", "ref"

@annaselh I think that this code that you had commented, contain personal information.

**Comment by jonalan7** [comment]
**The problem was solved! Wait for a new update!**

**Comment by clovisdanielss** [comment]
Where can I check if the update is **on** ?

**Comment by marciusbezerra** [comment]
> 2.2.5-alpha

how do i update to this version?

**Comment by IgorPC** [comment]
Same error here, how can i update for the version 2.2.5?

**Comment by marciusbezerra** [comment]
in version 2.2.3 everything was running smoothly

**Comment by IgorPC** [comment]
> in version 2.2.3 everything was running smoothly

True, i'll use this version until version 2.2.5 is officially launched

**Comment by marciusbezerra** [comment]
in my case not even 2.2.3 is working anymore, even to send simple messages, without images:

```
(node:16624) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (C:\Projetos\Node\venom-wp\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:37022)       
    at __puppeteer_evaluation_script__:3:53
```

**Comment by marciusbezerra** [comment]
I finally managed to make it work, you have to call venom.create at the beginning of everything, as it is asynchronous, and I still had problems with sending images, which was fixed with the nightly version!

`npm i --save https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz`

**Comment by tadeubarbosa** [comment]
You said to use `venom.create` before each function?
Can you explain, please?

**Comment by marciusbezerra** [comment]
> You said to use `venom.create` before each function?
> Can you explain, please?

when you start on the node, you already call venom.create, on npm start for example. only once. you cannot call create when you are going to send a message, as the connection is asynchronous.

**Comment by marciusbezerra** [comment]
the venom-bot-nightly.tgz version only sent an image once, on windows, when I published the application on linux it didn't send any more images! still have this error!

**Comment by tadeubarbosa** [comment]
yes, these functions still getting error

**Comment by marciusbezerra** [comment]
![image](https://user-images.githubusercontent.com/1328224/108264940-e6dfad00-7146-11eb-860d-b1be2d132e8d.png)

**Comment by jonalan7** [comment]
**The problem was solved with a new update!**
