### ISSUE TITLE
Retorno do método onMessage está diferente na versão 2.2.4

### ISSUE THREAD

**Issue by sircaio21** [orkestral/venom#602]
Olá, 
Preciso acessar os dados dos contatos que enviam mensagem para o bot, no entanto, após atualizar a versão do venom-bot para 2.2.4, o objeto de retorno das mensagens recebidas mudou e não consigo mais ter acesso ao .chat.contact, pois o mesmo existe, porém está vazio.

Retorno na versão 2.2.3:
![printVenom](https://user-images.githubusercontent.com/53582675/108096083-511d2280-705f-11eb-93fc-b6e04d2673f1.png)

Retorno na versão 2.2.4:
contact: {}

**Comment by clovisdanielss** [comment]
Usa o client.getContact

`const contact = await client.getContact(message.chat.id);`

**Comment by sircaio21** [comment]
> Usa o client.getContact
> 
> `const contact = await client.getContact(message.chat.id);`
> 
> E fecha a issue se isso resolver. Pra mim resolveu.
> Valeu.



> Usa o client.getContact
> 
> `const contact = await client.getContact(message.chat.id);`
> 
> E fecha a issue se isso resolver. Pra mim resolveu.
> Valeu.

Deu certo, mt obg
