### ISSUE TITLE
sendFileFromBase64 doesn't works on v2.2.4

### ISSUE THREAD

**Issue by sircaio21** [orkestral/venom#604]
## Environment
- **Venom version(s):** 2.2.4
- **Browser:** Chrome
- **OS:** Windows 10
- **Node version:** v14.15.4

I'm trying to send files using the "sendFileFromBase64" method, but it doesn't work. Error text on return is empty.
![image](https://user-images.githubusercontent.com/53582675/108202467-e7088a00-70ff-11eb-86d5-8635cfefdf34.png)

in version 2.2.3 it works

**Comment by jonalan7** [comment]
#598

**Comment by leandrosnx** [comment]
Same error here

**Comment by leandrosnx** [comment]
`[Nest] 19460   - 02/17/2021, 11:16:39 PM   [ExceptionsHandler] Object:
{
  "me": {
    "id": "1",
    "ref": "1@VaGieR+sNO1hXUBncPf+N5NpLutpNyzqs1oOeH7pafL9JtwwlwBlJVV2zdPh1MUu3kj/2eDP5wPQQ==",
    "refTTL": 20000,
    "wid": {
      "server": "c.us",
      "user": "55628",
      "_serialized": "55628@c.us" // hidden
    },
    "connected": true,
    "protoVersion": [
      0,
      17
    ],
    "clientToken": "M1hzt0Of4pqn2g+DiPRCj/pZ9wARqS9m3oPm8w=",
    "serverToken": "1@jTGnKtN2o+k7O2Ky/acbtf+QiGU3+0XA6KkB0X7niIXXlDdtrp/IJjBbPLUOd3npPiCBIanw==",
    "isResponse": "true",
    "battery": 59,
    "plugged": false,
    "lc": "BR",
    "lg": "pt",
    "locales": "pt-BR",
    "is24h": true,
    "platform": "smba",
    "phone": {
      "wa_version": "2.21.2.18",
      "mcc": "724",
      "mnc": "006",
      "os_version": "11",
      "device_manufacturer": "samsung",
      "device_model": "beyond2",
      "os_build_number": "RP1A.200720.012.G975FXXU9E4"
    },
    "tos": 0,
    "smbTos": 0,
    "pushname": "Leandro Sanches",
    "blockStoreAdds": false,
    "isVoipInitialized": false
  },
  "to": {
    "fromMe": true,
    "remote": {
      "server": "c.us",
      "user": "5562...",
      "_serialized": "5562...@c.us"
    },
    "id": "KPIVDI7FPRF74LSP5X",
    "_serialized": "true_5562...@c.us_KPIVDI7FPRF74LSP5",
    "isOnline": null
  },
  "erro": true,
  "text": "asdasdasd",
  "status": false,
  "type": "sendFile",
  "filename": "tree-alone-dark-evening-4k.jpeg",
  "mimeType": "image/jpeg"
}
`

**Comment by jonalan7** [comment]
**This problem has already been fixed, please wait for new updates!**
