### ISSUE TITLE
when I try to send a message, the following error is occurring: UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined

### ISSUE THREAD

**Issue by marciusbezerra** [orkestral/venom#605]
## UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined

when I try to send a message, the following error is occurring ...

`(node:30568) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:3:45
    at ExecutionContext._evaluateInternal (C:\Projetos\Node\venom-wp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Projetos\Node\venom-wp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)`

## Environment

- **Venom version(s):** [2.2.4]
- **Browser:** [Chrome 88]
- **OS:** [Windows 10]
- **Node version:** [12.18.3]

## Steps to Reproduce

`await venomClient.sendImage(sendTo, `./images/goodmorning/${image}`, image, goodMorningMsg);`

**Comment by clovisdanielss** [comment]
Well, #598 shows a problem to send media. 

But, it was a different error. 
In your case, I got a similar problem, but it was related to the client.onStreamChange that I was not using properly.
Look at [here](https://github.com/orkestral/venom#getting-started).

Hope to help, but I'm not sure.

**Comment by marciusbezerra** [comment]
> Bem, [# 598](https://github.com/orkestral/venom/issues/598) mostra um problema para enviar mídia.
> 
> Mas, foi um erro diferente.
> No seu caso, tive um problema parecido, mas estava relacionado ao client.onStreamChange que não estava usando corretamente.
> Olhe [aqui](https://github.com/orkestral/venom#getting-started) .
> 
> Espero ajudar, mas não tenho certeza.

if i downgrade to version 2.2.3 will i still need to use this asynchronous onStreamChange?

**Comment by marciusbezerra** [comment]
> Well, #598 shows a problem to send media.
> 
> But, it was a different error.
> In your case, I got a similar problem, but it was related to the client.onStreamChange that I was not using properly.
> Look at [here](https://github.com/orkestral/venom#getting-started).
> 
> Hope to help, but I'm not sure.

if i downgrade to version 2.2.3 will i still need to use this asynchronous onStreamChange?

**Comment by marciusbezerra** [comment]
in version 2.2.3 everything was running smoothly

**Comment by clovisdanielss** [comment]
> > Well, #598 shows a problem to send media.
> > But, it was a different error.
> > In your case, I got a similar problem, but it was related to the client.onStreamChange that I was not using properly.
> > Look at [here](https://github.com/orkestral/venom#getting-started).
> > Hope to help, but I'm not sure.
> 
> if i downgrade to version 2.2.3 will i still need to use this asynchronous onStreamChange?

No you dont, but you wont donwload any files

**Comment by marciusbezerra** [comment]
> > > Well, #598 shows a problem to send media.
> > > But, it was a different error.
> > > In your case, I got a similar problem, but it was related to the client.onStreamChange that I was not using properly.
> > > Look at [here](https://github.com/orkestral/venom#getting-started).
> > > Hope to help, but I'm not sure.
> > 
> > 
> > if i downgrade to version 2.2.3 will i still need to use this asynchronous onStreamChange?
> 
> No you dont, but you wont donwload any files
> 
> I think it's better to use the enchantment.

I've already managed to solve several problems, but he just isn't sending images yet. I'm using the venom-bot-nightly.tgz version. When trying to upload an image, it returns the following error:

`Page Closed`

**Comment by marciusbezerra** [comment]
it was related to the client.onStreamChange that I was not using properly
