### ISSUE TITLE
The message id returned when send an file and the id when receive ack is different

### ISSUE THREAD

**Issue by tadeubarbosa** [orkestral/venom#607]
## Description

When we send an message, the result of then, contains the message id:

```js
await venom.sendText(numero, base64, filename, texto)
  .then(async (response) => {
	console.log('message id', response.id)
  })
  .catch(error => {});

await venom.sendFileFromBase64(numero, base64, filename, texto)
  .then(async (response) => {
	console.log('message id', response.id)
  })
  .catch(error => {});

await whatsapp.onAck(async (message) => {
	console.log('message id', message.id.id) // mark this message has sent
});
```

But, right now, when I send an image, the message id is missing or it returns an different id.
So we can't check a file as sent.

## Environment

- **Venom version(s):** 2.2.4
- **Browser:** Chromium 85
- **OS:** Ubuntu 12
- **Node version:** Node 12

**Comment by tadeubarbosa** [comment]
it's working in the business version!

**Comment by robinhodemorais** [comment]
did you get a way to identify? because I have this same doubt, I realized that when sending a message it also happens to have a different id
