### ISSUE TITLE
What function i need to use for access all messages in chat

### ISSUE THREAD

**Issue by IgorPC** [orkestral/venom#608]
I'm using **getAllMessagesInChat** function to access all messages in chat. But i only received the other person messages.

What function i need to use for access my messages and other person messages?

**Comment by jonalan7** [comment]
These are the requested parameters:

**getAllMessagesInChat( chatId: string, includeMe: boolean, includeNotifications: boolean);**

If you want all the messages you should do it this way:

**getAllMessagesInChat( '000000000000@c.us', true, true);**

**Comment by IgorPC** [comment]
Thanks! It's working now
