### ISSUE TITLE
QRCode is not working

### ISSUE THREAD

**Issue by bigjoevtrj** [orkestral/venom#61]
My phone doesn't recognize the QR Code.

as a temporary solution I've used this options: 
{ headless: false, logQR: false, useChrome: true } and read QRCode at Chrome Window, but it doesn't work at my terminal

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
Can confirm, I see the QRCode i scan it using my phone, and then nothing happens. What can I do to make sure it works from terminal?

**Comment by orkestral** [comment]
Working normally.

**Comment by betonetotbo** [comment]
I think this is related to #67
