### ISSUE TITLE
When i try start the Venom, i receive this Error.

### ISSUE THREAD

**Issue by NiedsonEmanoel** [orkestral/venom#610]
Error: Error: Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at __puppeteer_evaluation_script__:2:58

**Comment by NiedsonEmanoel** [comment]
I deleted the folder 'tokens' and it looks like it is working.

**Comment by NiedsonEmanoel** [comment]
Issue resolved.

**Comment by creuza** [comment]
Este é um problema relacionado a um módulo que o venom usa chamado puppeteer. Este erro provavelmente está ocorrendo dentro do browser simulado pelo puppeteer, pois ele não está conseguindo acessar o localStorage.

**Comment by NiedsonEmanoel** [comment]
Me parece que por algum motivo o próprio WhatsWeb invalidou meu token, reloguei e deu certo.
