### ISSUE TITLE
How to disable venom to close Chrome ?

### ISSUE THREAD

**Issue by clovisdanielss** [orkestral/venom#614]
When 'notLogged' status is triggered, the venom-bot closes the browser instance that is running. 

But I instead want to control when the browser should be closed.
Also, It removes the token. I need to maintain it. 

I appreciate any help.

Thank you very much.

**Comment by jonalan7** [comment]
**When the client is not connected to whatzapp, a callback is called via the venom create function, returning the 'notLogged' parameter, by default, there is a time to close an instance, the autoClose parameter: 60000, if you don't want, just put autoClose: 0.**
