### ISSUE TITLE
DeprecationWarning 

### ISSUE THREAD

**Issue by textarea** [orkestral/venom#615]
## Description

Get DeprecationWarning in logout() call after browserClose event

## Environment

- **Venom version(s):** 2.2.3
- **Browser:** Chromium
- **OS:** Debian 10
- **Node version:** Node 15

## Log Output

(node:26360) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will throw if path does not exist or is a file. Use fs.rm(path, { recursive: true, force: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
process warning DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will throw if path does not exist or is a file. Use fs.rm(path, { recursive: true, force: true }) instead
at emitPermissiveRmdirWarning (node:internal/fs/utils:762:13)
at __node_internal_ (node:internal/fs/utils:741:7)
at Object.rmdirSync (node:fs:911:15)
at Plugin.deleteUserDataDir (/var/www/wa/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
at Plugin.onClose (/var/www/wa/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
at /var/www/wa/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
at Array.map (<anonymous>)
at Object.emit (/var/www/wa/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
at Browser.emit (/var/www/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
at /var/www/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:85:94

## Your Code

...
// statusFind
async (statusSession, session) => {
    if (session === 'browserClose') {
        await client.logout()
    }
},
.....

**Comment by jonalan7** [comment]
**Where did you find this logout() from? The correct one is client.close();**

**Comment by textarea** [comment]
https://orkestral.github.io/venom/classes/whatsapp.html#logout

**Comment by jonalan7** [comment]
another thing, if you are using the create callback, in this case the statusFind, in the session parameter, the name of the client will be returned, whereas the statusSession parameter, will be returning the status of the session. In other words, the session parameter will never return browserClose. See this example: [https://github.com/orkestral/venom#optional-create-parameters](https://github.com/orkestral/venom#optional-create-parameters)

**Comment by textarea** [comment]
Sure?
https://orkestral.github.io/venom/pages/Getting%20Started/creating-client.html

![Schermata 2021-02-20 alle 12 21 45](https://user-images.githubusercontent.com/1927403/108593812-42dc4880-7376-11eb-9736-39315d6ccbbe.jpg)

**Comment by textarea** [comment]
also in your link https://github.com/orkestral/venom#optional-create-parameters
![Schermata 2021-02-20 alle 12 24 11](https://user-images.githubusercontent.com/1927403/108593852-9a7ab400-7376-11eb-93bd-a16a3798e8ac.jpg)

**Comment by jonalan7** [comment]
**You cannot use the logout () command, because the browser is closed!**
**This is the correct way:**
```
// statusFind
(statusSession, session) => {
  if (statusSession === 'browserClose') {
       console.log("The browser is closed: ", statusSession);
       console.log("Session Name", session );
  }
}
```

**Comment by textarea** [comment]
Ok, thanks

**Comment by textarea** [comment]
This issue is back again in 3.0.4 release, I don't have logout() or any others code in statusFind callback
