### ISSUE TITLE
getAllContacts() function doesn't work in version 2.2.4

### ISSUE THREAD

**Issue by imtraineeudemy** [orkestral/venom#622]
## Description

client.getAllContacts() doesn't return contacts

## Environment

- **Venom version(s):** 2.2.4
- **Browser:** Chrome 88.0.4324.150
- **OS:** Windows 10, CentOS 7
- **Node version:** Node 14

## Log Output

```
Doesn't log anything.
```

**Comment by jonalan7** [comment]
**Use the newest version!**

**Comment by kakagome** [comment]
I have been tried too using version 2.2.6, but this function still not working. Thank you.

**Comment by kakagome** [comment]
> **Use the newest version!**

I have been tried too using version 2.2.6, but this function still not working. Thank you.

**Comment by imtraineeudemy** [comment]
> **Use the newest version!**

Yes same with me, it's still not working even though i am using the latest version (2.2.6). Thanks.

**Comment by m0w4hhed** [comment]
downgrade to 2.2.3 version (temporary)
