### ISSUE TITLE
(statusSession, session)

### ISSUE THREAD

**Issue by diegosystem32** [orkestral/venom#623]
## Description

get statusSession, session Don´t working....

async (statusSession, session) => {
      console.log(statusSession, session)
      var json;
      var obj = sessionStatus.find(x => x.name === session);
      console.log("aaaaaaaaaaaa" + JSON.stringify(obj))
      if (obj !== undefined) {
        obj.status = statusSession;
      }
      else {
        sessionStatus.push({ "name": session, "status": statusSession, "device": [] }); //Dont´t get session and statusSession
      }
      console.log('Status Session: ', statusSession);
      console.log('Session name: ', session);
      //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
      //Create session wss return "serverClose" case server for close
      try {
        if (statusSession === "inChat" || statusSession === "qrReadSuccess" || statusSession === "isLogged") {
          json = { res: ``, restatus: `${statusSession}` };
        }
        if (statusSession === "qrReadFail" || statusSession === "qrReadError") {
          json = { res: ``, restatus: `${statusSession}` };
        }
        if (statusSession === "notLogged") {
          json = { res: `../temp/QRCode-${newPhone}.png`, restatus: `<div style='color:green'>${statusSession}</div>` };
        }
        res.status(200).json(json);
      } catch (err) {
        console.log("Tempo de espera para leitura QRcode acabou");
        //return res.status(500).json(err + " = " + statusSession);
        //res.send({res:`Erro! ${statusSession}`});
      }
    },

## Environment

- **Venom version(s):** [2.2.6]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **Node version:** [e.g. Node 8, Node 14]

**Comment by jonalan7** [comment]
Is working normally! Review your codes! See an example: [https://github.com/orkestral/venom#callback-status-session](https://github.com/orkestral/venom#callback-status-session)

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
