### ISSUE TITLE
Message is missing critical data needed to download the file

### ISSUE THREAD

**Issue by carloslleitao** [orkestral/venom#624]
Hi everyone, we are using Venom here and today we got this issue, even checking that a solution was already made to this 10 days ago in another issue, we downloaded latest version from master branch and still got the same issue. Any ideas?

whatsapp-rpa_1  | (node:25) UnhandledPromiseRejectionWarning: Error: message is missing critical data needed to download the file.
whatsapp-rpa_1  |     at Whatsapp.<anonymous> (/app/venom/dist/api/whatsapp.js:233:35)
whatsapp-rpa_1  |     at step (/app/venom/dist/api/whatsapp.js:46:23)
whatsapp-rpa_1  |     at Object.next (/app/venom/dist/api/whatsapp.js:27:53)
whatsapp-rpa_1  |     at /app/venom/dist/api/whatsapp.js:21:71
whatsapp-rpa_1  |     at new Promise (<anonymous>)
whatsapp-rpa_1  |     at __awaiter (/app/venom/dist/api/whatsapp.js:17:12)
whatsapp-rpa_1  |     at Whatsapp.decryptFile (/app/venom/dist/api/whatsapp.js:226:16)
whatsapp-rpa_1  |     at WrapperService.messageListener (/app/api/dist/services/wrapper/wrapper.service.js:198:45)
whatsapp-rpa_1  |     at EventEmitter.<anonymous> (/app/api/dist/services/wrapper/wrapper.service.js:61:54)
whatsapp-rpa_1  |     at EventEmitter.emit (events.js:315:20)
whatsapp-rpa_1  |     at /app/venom/dist/api/layers/listener.layer.js:159:90
whatsapp-rpa_1  |     at Page._onBindingCalled (/app/venom/node_modules/puppeteer/lib/Page.js:408:62)
whatsapp-rpa_1  |     at CDPSession.<anonymous> (/app/venom/node_modules/puppeteer/lib/Page.js:126:60)
whatsapp-rpa_1  |     at CDPSession.emit (events.js:315:20)
whatsapp-rpa_1  |     at CDPSession._onMessage (/app/venom/node_modules/puppeteer/lib/Connection.js:166:18)
whatsapp-rpa_1  |     at Connection._onMessage (/app/venom/node_modules/puppeteer/lib/Connection.js:83:25)

**Comment by carloslleitao** [comment]
Anyone is experiencing this issue guys?

**Comment by antirek** [comment]
it's actua probleml for 3.0.1 too

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
