### ISSUE TITLE
Forward video message

### ISSUE THREAD

**Issue by misterxis** [orkestral/venom#625]
Please, I put the message.id and i received sucess message, but wont go. Where is my error?

`static async forwardMessages(sessionName){
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultForward = await session.client.then(async (client) => {
                    return await client.forwardMessages('550098765432@c.us',
                                                        ["false_550012345678-1613960890@g.us_406A5F37391F174D5E22538F98609089".toString()],
                                                        true);
                });
                return { result: "success", data: resultForward };
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND " + session.state};
        }
    }`

**Comment by misterxis** [comment]
![image](https://user-images.githubusercontent.com/35082933/108803792-50fab680-757a-11eb-8b13-fd438d7c76bc.png)

**Comment by misterxis** [comment]
The problem is with video forward... text is ok... anybody?

**Comment by orkestral** [comment]
fixed in version 3.0.5
