### ISSUE TITLE
Proper Error Handling On sendImageAsStickerGif

### ISSUE THREAD

**Issue by kaiserdj** [orkestral/venom#628]
## Description

Whenever you try to process a sticker that the file size exceeds 1MB, it'll just warn you in the console and then give you an Evaluation failed: n exception.

It'd be nice if you could throw an max sticker file size exceeded exception instead of console logging the sticker size message, or at least something like that. That way we can handle it better.

## Environment

- **Venom version(s):** 2.2.6
- **Browser:** 
- **OS:**  Windows 10
- **Node version:**  Node 14

## Steps to Reproduce

https://github.com/orkestral/venom/issues/482

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
