### ISSUE TITLE
How to force disconnect/logout

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#629]
I need to provide a option to logout from WhatsApp via Venom. I read a function called `logout()`, but it don't work as expected. Reading the doc wasn't useful for this purpose.

**Comment by orkestral** [comment]
fixed in version 3.0.5

**Comment by developerdevice** [comment]
Seems likes it's working now, but when you run logout() first time works as expected, if you read qrcode and try logout again, this message is triggered

> 
0|index  | TypeError: logout is not a function
