### ISSUE TITLE
How does the sendText works?

### ISSUE THREAD

**Issue by OthavioH** [orkestral/venom#63]
Can I get a number like +551982848587 and send a message even if I don't have the number added as a contact?

**Comment by neovoice** [comment]
I have tried this code, but does not work for me, can someone help to implement sendMessageToId method?
*****************************************************
const venom = require('venom-bot');

enviar()

async function enviar(){
const client= await venom.create()
respuesta = await client.sendMessageToId('<number>@c.us', 'Hello')
console.log(respuesta)
}
****************************************************

**Comment by joaosouz4** [comment]
> I have tried this code, but does not work for me, can someone help to implement sendMessageToId method?
> 
> const venom = require('venom-bot');
> 
> enviar()
> 
> async function enviar(){
> const client= await venom.create()
> respuesta = await client.sendMessageToId('551982848587@c.us', 'Hello')
> console.log(respuesta)
> }


u need to write like this
> respuesta = await client.sendMessageToId('codeCountryAndNumber@c.us', 'Hello')
> EX: respuesta = await client.sendMessageToId('codeCountryAndNumber@c.us', 'Hello')

without the plus sign or any character
this example is used for when we want to send a message to a contact that we don't already have on our list, be careful when using this function

**Comment by neovoice** [comment]
> > I have tried this code, but does not work for me, can someone help to implement sendMessageToId method?
> > const venom = require('venom-bot');
> > enviar()
> > async function enviar(){
> > const client= await venom.create()
> > respuesta = await client.sendMessageToId('[551982848587@c.us](mailto:551982848587@c.us)', 'Hello')
> > console.log(respuesta)
> > }
> 
> @neovoice u need to write like this
> 
> > respuesta = await client.sendMessageToId('[codeCountryAndNumber@c.us](mailto:codeCountryAndNumber@c.us)', 'Hello')
> > EX: respuesta = await client.sendMessageToId('[codeCountryAndNumber@c.us](mailto:codeCountryAndNumber@c.us)', 'Hello')
> 
> without the plus sign or any character
> this example is used for when we want to send a message to a contact that we don't already have on our list, be careful when using this function

Thanks a lot!

That works for me.
