### ISSUE TITLE
Error: Protocol error: Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by berrabe** [orkestral/venom#630]
## Description

Suddenly, the browser (puppeter w/ chromium) closes itself

## Environment

- **Venom version(s):** 2.2.6
- **Browser:** chromium-81.0.4044.113-r0 and chromium-chromedriver-81.0.4044.113-r0
- **OS:** docker alpine:edge
- **Node version:** nodejs-14.16.0-r0

## Steps to Reproduce

1. follow coding documentation

## Log Output

![a edited](https://user-images.githubusercontent.com/34432326/108964382-fc585800-76ad-11eb-9ad0-4e7c729f9f45.png)

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
