### ISSUE TITLE
venom doesn't send message

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#632]
## Description

cannot send message

Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined at Object.window.WAPI.window.WAPI.sendMessage (../node_modules/venom-bot/dist/lib/wapi/wapi.js:1:35930) at __puppeteer_evaluation_script__:3:53 at ExecutionContext._evaluateInternal (../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19) at processTicksAndRejections (internal/process/task_queues.js:97:5) at ExecutionContext.evaluate (../node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

## Environment

- **Venom version(s):** [ 2.2.6]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

**Comment by Lucipher** [comment]
the same issue

**Comment by thaziz** [comment]
the same issue

**Comment by lgcarvalho1** [comment]
same

**Comment by luidiva** [comment]
something has changed. I'm getting 'javascript error: webpackJsonp is not defined'

**Comment by ghifar1** [comment]
whatsapp update their application

**Comment by clovisdanielss** [comment]
#633

**Comment by nonna2010** [comment]
the same issue
Help ??

**Comment by antirek** [comment]
I think that need test nightly version. @orkestral patch https://github.com/orkestral/venom/blob/master/src/lib/wapi/store/get-store.js and some other changes

**Comment by samuelrbo** [comment]
If this project uses the same js lib as WebWhatsapp-Wrapper, this is the correction 

https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/1006

https://github.com/mukulhase/WebWhatsapp-Wrapper/blob/6eae48b8f6e69c6564ce2ab2eec0b12c5876dd94/webwhatsapi/js/wapi.js

**Comment by jonit-dev** [comment]
I was getting the same error while trying to use the .sendLinkPreview method.
Try to use .sendText meanwhile (that's what I'm doing until I get a fix)
It's working fine!

**Comment by antirek** [comment]
fixed in 3.0.1 thanks @jonalan7 @orkestral :+1:

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
