### ISSUE TITLE
Problema ao criar sessao

### ISSUE THREAD

**Issue by diogo-palma** [orkestral/venom#633]
## Description
após criar a sessão está ocorrendo este erro

There was an error in the bot Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at Object.window.WAPI.window.WAPI.restartService (G:\projetos\valdeci\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:57963)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (G:\projetos\valdeci\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (G:\projetos\valdeci\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** 2.2.6
- **Browser:** Chrome
- **OS:** Windows 10
- **Node version:** Node 14

## Steps to Reproduce

1. [First Step]
Criar sessao venom

```
If relevant, paste all of your Log Output
```

## Your Code

 ```
bot.create(
            //session
            'sessionName', //Pass the name of the client you want to start the bot
            //catchQR
            (base64Qrimg, asciiQR, attempts, urlCode) => {
              console.log('Number of attempts to read the qrcode: ', attempts);
              console.log('Terminal qrcode: ', asciiQR);
              console.log('base64 image string qrcode: ', base64Qrimg);
              console.log('urlCode (data-ref): ', urlCode);
            },
            // statusFind
            (statusSession, session) => {
              console.log('Status Session: ', statusSession); //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
              //Create session wss return "serverClose" case server for close
              console.log('Session name: ', session);
            },
            // options
            {
              folderNameToken: 'tokens', //folder name when saving tokens
              mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
              headless: true, // Headless chrome
              devtools: false, // Open devtools by default
              useChrome: true, // If false will use Chromium instance
              debug: false, // Opens a debug session
              logQR: true, // Logs QR automatically in terminal
              browserWS: '', // If u want to use browserWSEndpoint
              browserArgs: [''], // Parameters to be added into the chrome browser instance
              puppeteerOptions: {}, // Will be passed to puppeteer.launch
              disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
              disableWelcome: true, // Will disable the welcoming message which appears in the beginning
              updatesLog: true, // Logs info updates automatically in terminal
              autoClose: false, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
              createPathFileToken: false, //creates a folder when inserting an object in the client's browser, to work it is necessary to pass the parameters in the function create browserSessionToken
            },
            // BrowserSessionToken
            // To receive the client's token use the function await client.getSessionTokenBrowser()
          )
          .then((client) => {
            let time = 0,
              started = false;
            client.onStreamChange((state) => {
              console.log('Connection status: ', state);
              clearTimeout(time);
              if (state === 'CONNECTED' && !started) {
                start(client);
                started = true;
              }
              //DISCONNECTED when the mobile device is disconnected
              if (state === 'DISCONNECTED' || state === 'SYNCING') {
                time = setTimeout(() => {
                  client.close();
                  // process.exit(); //optional function if you work with only one session
                }, 80000);
              }
            });
          })
          .catch((erro) => {
            console.log('There was an error in the bot', erro);
          });
```

**Comment by effer89** [comment]
Bom dia, também com esse mesmo erro

**Comment by tadeubarbosa** [comment]
o wpp atualizou o webpack, o pessoal está na correria pra tentar corrigir... =/

**Comment by tauasilva** [comment]
Infelizmente estou com o mesmo problema!

**Comment by clovisdanielss** [comment]
> o wpp atualizou o webpack, o pessoal está na correria pra tentar corrigir... =/

Cara, como ficar por dentro dessas atualizações? Como você sabe que atualizaram lá? Tem link de repo ? é público ?

Obrigado por avisar.

**Comment by AllanBSantos** [comment]
também estou com o mesmo problema

**Comment by GladistonXD** [comment]
Acredito que seja algum problema no repositório, não uma alteração no sistema do whatsapp pois usando outro método como o @OPEN-WA que também usa puppeteer ainda esta funcional

**Comment by effer89** [comment]
> Acredito que seja algum problema no repositório, não uma alteração no sistema do whatsapp pois usando outro método como o OPEN-WA que também usa puppeteer ainda esta funcional

Pode me falar onde você substituiu com o open-wa por favor?

**Comment by guilhermehduarte** [comment]
> Acredito que seja algum problema no repositório, não uma alteração no sistema do whatsapp pois usando outro método como o OPEN-WA que também usa puppeteer ainda esta funcional

Também acho, o OPEN-WA está 100% funcional

**Comment by rafaelferres** [comment]
Subiram uma correção hoje no open-wa, por isso ele está funcional

**Comment by carloslleitao** [comment]
same thing here...hope they get a fix soon

**Comment by techwebsolucao** [comment]
mesma coisa aqui ...

**Comment by techwebsolucao** [comment]
parou ontem de noite perto das 21:20

**Comment by rafaelferres** [comment]
Foi uma atualização no Whatsapp sim, o OPEN-WA fez a correção hoje de manhã

**Comment by antoniovalenzuela** [comment]
same issue

**Comment by eltondcr** [comment]
same issue

**Comment by antoniovalenzuela** [comment]
> same issue

open-wa perfect!!

**Comment by neocomun** [comment]
Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

**Comment by danireginatto** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

testamos aqui não foi

**Comment by guilhermehduarte** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

Ainda não está funcional

```
node:18) UnhandledPromiseRejectionWarning: TypeError: client.onStreamChange is not a function
    at /usr/src/mywhats-api/sessions.js:234:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.setup (/usr/src/mywhats-api/sessions.js:231:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by antoniovalenzuela** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

works! but all auto-responses are duplicated (2 messages ¿?)

**Comment by edalicioh** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

(node:36498) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string

Mais esta envinado normal

**Comment by edalicioh** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

(node:36498) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string

Mais esta enviando normal

**Comment by effer89** [comment]
Testando atualizar com Yarno erro permanece, alguma sugestão?

**Comment by miguelarcjr** [comment]
Mesmo problema

**Comment by techwebsolucao** [comment]
> Forcem a atualização npm install venom-bot@3.0.0 já está funcionando

Aqui deu certo muito obrigado <3

**Comment by clovisdanielss** [comment]
Ninguém mais com a #639 ?

**Comment by igortrust** [comment]
> Testando atualizar com Yarn erro permanece, alguma sugestão?

Aqui estava com erro para atualizar, exclui a pasta do node_modules e dei um yarn… Funciou, mas está com o problema de duplicação no onMessage  #639

**Comment by techwebsolucao** [comment]
> Ninguém mais com a #639 ?😢

**Comment by effer89** [comment]
> > Testando atualizar com Yarn erro permanece, alguma sugestão?
> 
> Aqui estava com erro para atualizar, exclui a pasta do node_modules e dei um yarn… Funciou, mas está com o problema de duplicação no onMessage #639

Então, eu fiz isso também, mas parece que ele não baixa a ultima versão, tem alguma ideia? :P

**Comment by igortrust** [comment]
> > > Testando atualizar com Yarn erro permanece, alguma sugestão?
> > 
> > 
> > Aqui estava com erro para atualizar, exclui a pasta do node_modules e dei um yarn… Funciou, mas está com o problema de duplicação no onMessage #639
> 
> Então, eu fiz isso também, mas parece que ele não baixa a ultima versão, tem alguma ideia? :P

Da algum erro após o yarn? Alterou o package.json?

**Comment by effer89** [comment]
> > > > Testando atualizar com Yarn erro permanece, alguma sugestão?
> > > 
> > > 
> > > Aqui estava com erro para atualizar, exclui a pasta do node_modules e dei um yarn… Funciou, mas está com o problema de duplicação no onMessage #639
> > 
> > 
> > Então, eu fiz isso também, mas parece que ele não baixa a ultima versão, tem alguma ideia? :P
> 
> Da algum erro após o yarn? Alterou o package.json?

@igortrust obrigado pela ajuda, no fim das contas era porque eu estava usando o NVM, não sei porque mas o puppeteer não tava identificando o node atualizado que estava no NVM, parei de usar ele (e atualizei o da maquina e funcionou)

**Comment by NiedsonEmanoel** [comment]
Alguém mais com a #639?

**Comment by guilhermehduarte** [comment]
> > > > > Testando atualizar com Yarn erro permanece, alguma sugestão?
> > > > 
> > > > 
> > > > Aqui estava com erro para atualizar, exclui a pasta do node_modules e dei um yarn… Funciou, mas está com o problema de duplicação no onMessage #639
> > > 
> > > 
> > > Então, eu fiz isso também, mas parece que ele não baixa a ultima versão, tem alguma ideia? :P
> > 
> > 
> > Da algum erro após o yarn? Alterou o package.json?
> 
> @igortrust obrigado pela ajuda, no fim das contas era porque eu estava usando o NVM, não sei porque mas o puppeteer não tava identificando o node atualizado que estava no NVM, parei de usar ele (e atualizei o da maquina e funcionou)

Quais alterações de versões de bibliotecas devo fazer alem do vemom 3.0.0?

**Comment by tadeubarbosa** [comment]
> > o wpp atualizou o webpack, o pessoal está na correria pra tentar corrigir... =/
> 
> Cara, como ficar por dentro dessas atualizações? Como você sabe que atualizaram lá? Tem link de repo ? é público ?
> 
> Obrigado por avisar.

o pessoal avisa lá no grupo de suporte do Venom... eu não entendo muito dessa parte também, pelo que @GladistonXD disse, é atualização em alguma biblioteca

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
