### ISSUE TITLE
URGENT - checkNumberStatus return change

### ISSUE THREAD

**Issue by guilhermehduarte** [orkestral/venom#634]
The checkNumberStatus method has stopped validating.

The return is 200, however, only the searched number appears on the return:

//response to sistem/checkNumberStatus 
```
{
    "Number": 5512997709337
}
```

**Comment by effer89** [comment]
Só por curiosidade, qual a versão que você esta usando do venom?

**Comment by guilhermehduarte** [comment]
> Só por curiosidade, qual a versão que você esta usando do venom?

Estou usando a versão mais atual (2.2.6)
Ontem o método checkNumberStatus parou de funcionar. Antes, o retorno era a validação se o número era uma conta válida do WhatsApp. O atual retorno, é o exemplo que dei acima. Não sei se houve alguma alteração na chamada do Venom.

I'm using the latest version (2.2.6)
Yesterday the checkNumberStatus method stopped working. Previously, the return was validation if the number was a valid WhatsApp account. The current return is the example I gave above. I don't know if there's been a change in Venom's call.

**Comment by effer89** [comment]
Atualmente o venom não está funcionando, whats mudou algumas coisas e é preciso corrigir no bot também #633 #632 pode ser esse problema ai

**Comment by guilhermehduarte** [comment]
Obrigado! Acompanhando a resolução pela equipe!
