### ISSUE TITLE
onMessage doubling the arrival of messages

### ISSUE THREAD

**Issue by devpremium** [orkestral/venom#639]
onMessage doubling the arrival of messages

client.onMessage((message) => {
     console.log(message);
});

**Comment by igortrust** [comment]
same here!

**Comment by clovisdanielss** [comment]
same here.

**Comment by techwebsolucao** [comment]
same here.

**Comment by NiedsonEmanoel** [comment]
Same here!

**Comment by Pezhvak** [comment]
same here :|

**Comment by Pezhvak** [comment]
I confirm there is a bug which receives messages in duplicate in v3.00

**Comment by Pezhvak** [comment]
This is the most stupid workaround for now, this is far from perfect but gets the job done, you can create an array and push message ids to that array, make sure to contain indexes otherwise you get your memory full.

```
venom.create(undefined, undefined, undefined, {disableWelcome: true}).then((client) => start(client));
let last_msg = '';

function start(client) {
    client.onMessage((message) => {
        if (last_msg === message.id) {
            last_msg = '';
            return;
        }
        last_msg = message.id;
    });
```

**Comment by igortrust** [comment]
> Esta é a solução mais estúpida por enquanto, está longe de ser perfeita, mas dá conta do recado, você pode criar um array e enviar ids de mensagem para esse array, certifique-se de conter índices, caso contrário, sua memória ficará cheia.
> 
> ```
> venom.create(undefined, undefined, undefined, {disableWelcome: true}).then((client) => start(client));
> let last_msg = '';
> 
> function start(client) {
>     client.onMessage((message) => {
>         if (last_msg === message.id) {
>             last_msg = '';
>             return;
>         }
>         last_msg = message.id;
>     });
> ```

Why no?

**Comment by Pezhvak** [comment]
> > Esta é a solução mais estúpida por enquanto, está longe de ser perfeita, mas dá conta do recado, você pode criar um array e enviar ids de mensagem para esse array, certifique-se de conter índices, caso contrário, sua memória ficará cheia.
> > ```
> > venom.create(undefined, undefined, undefined, {disableWelcome: true}).then((client) => start(client));
> > let last_msg = '';
> > 
> > function start(client) {
> >     client.onMessage((message) => {
> >         if (last_msg === message.id) {
> >             last_msg = '';
> >             return;
> >         }
> >         last_msg = message.id;
> >     });
> > ```
> 
> Why no?

because it's bad practice to code like that, I shared it with you as a solution until it gets fixed.

**Comment by igortrust** [comment]
> > > Esta é a solução mais estúpida por enquanto, está longe de ser perfeita, mas dá conta do recado, você pode criar um array e enviar ids de mensagem para esse array, certifique-se de conter índices, caso contrário, sua memória ficará cheia.
> > > ```
> > > venom.create(undefined, undefined, undefined, {disableWelcome: true}).then((client) => start(client));
> > > let last_msg = '';
> > > 
> > > function start(client) {
> > >     client.onMessage((message) => {
> > >         if (last_msg === message.id) {
> > >             last_msg = '';
> > >             return;
> > >         }
> > >         last_msg = message.id;
> > >     });
> > > ```
> > 
> > 
> > Why no?
> 
> because it's bad practice to code like that, I shared it with you as a solution until it gets fixed.

I'm sorry, I was just a joke… 

But I did something "temporary" too, even though I know it's not the best solution!

```
// I am using a BD temp
//Check if there is message.id in the bd, if not, do it

let idmessage = [banco.db[message.from]].filter(function (element) {
            return element.id == message.id;
          });
          if (!idmessage[0]) {
            banco.db[message.from].id = message.id
                 ...
          }

```

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3
