### ISSUE TITLE
Can't Create Client

### ISSUE THREAD

**Issue by OrhanArslan** [orkestral/venom#646]
When try to create a new client, I get "[sulla.create.folderNameToken] browserClose" log and can't login.
I'm using 3.0.1.

**Comment by OrhanArslan** [comment]
Token is not generated.

**Comment by antirek** [comment]
show your code. sulla?

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3

**Comment by OrhanArslan** [comment]
I'm still facing same issue in 3.0.3 and 3.0.4. Could you check again please?
