### ISSUE TITLE
getAllChatsGroups function does not exist

### ISSUE THREAD

**Issue by garciabruno** [orkestral/venom#647]
## getAllChatsGroups function is undefined

The function getAllChatsGroups is undefined.
I also tried the function getAllGroups (as shown in the docs) and it doesn't exist either.

## Environment

- **Venom version(s):** 3.0.1
- **Browser:** [Version 87.0.4280.141 (Official Build) (64-bit)
- **OS:** Ubuntu Linux 20.10
- **Node version:** v15.10.0

## Steps to Reproduce

1. Try to use the function.
2. See how it fails

**Comment by romulloleal** [comment]
can you send your code to review?

**Comment by orkestral** [comment]
fixed in version 3.0.5
