### ISSUE TITLE
Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#648]
I'm sending a message from Venom with `sendText();`, the message is sent, but returns the follow error 

> 0|index  | Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
> 0|index  |     at t.default (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889667)
> 0|index  |     at Function.fromString (https://web.whatsapp.com/bootstrap_main.5c62c9ecb1108604f507.js:2:1889406)
> 0|index  |     at Object.e [as getMessageById] (/var/www/whapi/node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:22970)
> 0|index  |     at __puppeteer_evaluation_script__:1:37
> 0|index  |     at ExecutionContext._evaluateInternal (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
> 0|index  |     at runMicrotasks (<anonymous>)
> 0|index  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 0|index  |     at async ExecutionContext.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by KreisonReis** [comment]
same issue

**Comment by antirek** [comment]
duplicate #631 
use nightly build

**Comment by helloeyesimple** [comment]
@antirek issue still persist whether I'm using from nightly or master build

**Comment by developerdevice** [comment]
> duplicate #631
> use nightly build

Mesmo utilizando o nightly continua com o erro.

**Comment by antirek** [comment]
Oh, it's fromString error. Need new fix.

**Comment by antirek** [comment]
I check now, work fine. I use ubuntu 20.04, venom 3.0.1 and node.js 14. 
What is your configuration? And show your code.

**Comment by developerdevice** [comment]
> I check now, work fine. I use ubuntu 20.04, venom 3.0.1 and node.js 14.
> What is your configuration? And show your code.

venom-bot": ^3.0.1, node v14.15.4, NPM 6.14.10, debian 9

**Comment by orkestral** [comment]
more time sleep for await Store.Contacts

**Comment by helloeyesimple** [comment]
@antirek 
venom 3.0.1, node 12.18.3, windows 7 64bit

**Comment by techwebsolucao** [comment]
same issue

**Comment by helloeyesimple** [comment]
okay I think I've found the problem, sometimes sendText is fine after restarting client so many times, but I don't think this should be the solution :(

**Comment by miguelarcjr** [comment]
same issue

**Comment by orkestral** [comment]
corrention in npm i venom-bot version 3.0.3

**Comment by developerdevice** [comment]
> corrention in npm i venom-bot version 3.0.3

Hey, ADM. Thank you for reply. But I've tried 3.0.3, 3.0.4 and nightly version, the bug persists.

I'm running the block of code

`const response = await clientsArray[session].sendText(phone + "@c.us", msg);`

And the output to it

> Error: Evaluation failed: Error: MsgKey fromString error: str is null or not a string
