### ISSUE TITLE
Module parse failed: Unexpected character '' (1:0)

### ISSUE THREAD

**Issue by rafahlobo** [orkestral/venom#653]
I'm having the following problem below:

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/sharp/lib/output.js 4:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/venom-bot/dist/api/helpers/select-sticker.js
 @ ./node_modules/venom-bot/dist/api/helpers/index.js
 @ ./node_modules/venom-bot/dist/controllers/initializer.js
 @ ./node_modules/venom-bot/dist/index.js
 
 
 
# Environment
* Venom version(s): 3.0.2
* Browser: Version 88.0.4324.182 (Official Build) (64-bit)
* OS: Ubuntu Linux 20.10
* Node version: v14.15.3
* Framework: vue + electron

**Comment by orkestral** [comment]
fixed in version 3.0.5

**Comment by rafahlobo** [comment]
I keep getting the same error.

 error  in ./node_modules/sharp/build/Release/sharp.node

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/sharp/lib/utility.js 5:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/venom-bot/dist/api/helpers/select-sticker.js
 @ ./node_modules/venom-bot/dist/api/helpers/index.js
 @ ./node_modules/venom-bot/dist/controllers/initializer.js
 @ ./node_modules/venom-bot/dist/index.js
 @ ./src/background/service/whatsapp/whatsappManager.js
 @ ./src/background/eventHandler.js
 @ ./src/background/handlerViews.js
 @ ./src/background/app.js
 @ ./src/background.js
 @ multi ./src/background.js

 error  in ./node_modules/sleep/build/Release/node_sleep.node

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/sleep/index.js 1:12-54
 @ ./node_modules/lolcatjs/index.js
 @ ./node_modules/yoo-hoo/lib/index.js
 @ ./node_modules/venom-bot/dist/controllers/welcome.js
 @ ./node_modules/venom-bot/dist/controllers/initializer.js
 @ ./node_modules/venom-bot/dist/index.js
 @ ./src/background/service/whatsapp/whatsappManager.js
 @ ./src/background/eventHandler.js
 @ ./src/background/handlerViews.js
 @ ./src/background/app.js
 @ ./src/background.js
 @ multi ./src/background.js

 ERROR  Build failed with errors.
