### ISSUE TITLE
clearChat is not working and returning error

### ISSUE THREAD

**Issue by 239626** [orkestral/venom#657]
## Description

after upgrading venom to 3.0.5 an error returned whenever I use clearChat

## Environment

- **Venom version(s):** 3.0.5
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** CentOS
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by orkestral** [comment]
resolved in version 3.0.6
