### ISSUE TITLE
Logout function is not working as expected

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#667]
## Description

If you run the venom, reads QRcode and is connected to, so try use the `client.logout()` for the first time and it will work as expected, but when you read the QRcode again and try to use `client.logout()` the result is:

> 0|index  | TypeError: logout is not a function
> 0|index  |     at /var/www/whapi/node/index.js:214:3
> 0|index  |     at Layer.handle [as handle_request] (/var/www/whapi/node/node_modules/express/lib/router/layer.js:95:5)
> 0|index  |     at next (/var/www/whapi/node/node_modules/express/lib/router/route.js:137:13)
> 0|index  |     at Route.dispatch (/var/www/whapi/node/node_modules/express/lib/router/route.js:112:3)
> 0|index  |     at Layer.handle [as handle_request] (/var/www/whapi/node/node_modules/express/lib/router/layer.js:95:5)
> 0|index  |     at /var/www/whapi/node/node_modules/express/lib/router/index.js:281:22
> 0|index  |     at Function.process_params (/var/www/whapi/node/node_modules/express/lib/router/index.js:335:12)
> 0|index  |     at next (/var/www/whapi/node/node_modules/express/lib/router/index.js:275:10)
> 0|index  |     at jsonParser (/var/www/whapi/node/node_modules/body-parser/lib/types/json.js:101:7)
> 0|index  |     at Layer.handle [as handle_request] (/var/www/whapi/node/node_modules/express/lib/router/layer.js:95:5)

## Environment

- **Venom version(s):** 3.0.6
- **Browser:**  Chrome 88
- **OS:** Debian 9 Stretch
- **Node version:** v14.15.4

## Known-solution

The way I found to avoid it is restarting the project.

**Comment by developerdevice** [comment]
Wassup, Guys. Any news about this issue?

**Comment by jonalan7** [comment]
I tested and the function is working normally, review your source code!

**Comment by developerdevice** [comment]
> I tested and the function is working normally, review your source code!

Can you show me you tested code?
