### ISSUE TITLE
QRCode callback not invoked if autoClose is false

### ISSUE THREAD

**Issue by betonetotbo** [orkestral/venom#67]
In my case, I want to keep venom runinng and the QRCode refreshing.

For this I defined this config for venom session creation:

```node
const VENOM_CONFIG = { 
    logQR: false, 
    headless: true, 
    browserArgs: ['--no-sandbox'], 
    useChrome: false, 
    autoClose: false, 
    debug: false, 
    devtools: false, 
    disableSpins: true,
    refreshQR: 15000
};
```
When I run my application, it starts a venom session and the QRCode callback export it as a PNG to my frontend.

Inside the callback I also use a websocket message to notify the frontend that exists a new QRCode, and the frontend download the PNG again to display it to the enduser. 

And here is the BUG, the callback is never called again.

Try to open https://web.whatsapp.com/ without pairing it, and keep viewing the QR Code. It will change every minute, and the venom does not intercept the change.

Another bug is, after a while the https://web.whatsapp.com/ will require a user iteration, a click over the QRCode area to force the geration of a new QRCode.

**Comment by betonetotbo** [comment]
As a workaround I'm using this:

```javascript
var lastAsciiQR;
venom
	.create('session', 
		(base64Qr, asciiQR) => {
			// log QRCode only when it changes!
			if (asciiQR != lastAsciiQR) {
				lastAsciiQR = asciiQR;
				console.log(asciiQR);
			}
		} 
	, 
	null,
	{
		logQR: false, 
		headless: false,
		autoClose: Number.MAX_SAFE_INTEGER
	})
```

**Comment by lucascardev** [comment]
@betonetotbo Same here! when autoclose is false, QR code load once, even if Refesh is set.

**Comment by joaosouz4** [comment]
this has been fixed in the new version, if any other problems arise, create a new problem
