### ISSUE TITLE
Anyone else with a problem with sendContactVcard?

### ISSUE THREAD

**Issue by techwebsolucao** [orkestral/venom#677]
Anyone else with a problem with sendContactVcard

Problem is that it gives error when I try to send a card

erro: true,
  text: null,
  status: 'ERROR_UNKNOWN',

**Comment by leandrosnx** [comment]
+1 same error here

**Comment by jonalan7** [comment]
**This problem has already been solved!**

**Comment by techwebsolucao** [comment]
@jonalan7  here follows the error in version 3.0.7 already deleted the folder node and packejson block and did not solve

if (message.body === "3" && message.isGroupMsg === false) {
await client.sendContactVcard(message.from, '00000000000@c.us', 'Suporte')
.then((result) => {
console.log('Result: ', result); //return object success
})
.catch((erro) => {
console.error('Error when sending: ', erro); //return object error
});
