### ISSUE TITLE
how can i make a command like !join LinkOfTheGroup

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#686]
command to make bot join a group

**Comment by RubberArchind** [comment]
You can use this ```await client.joinGroup(url.split('/')[3]);```

**Comment by ArmyNicolasG** [comment]
> You can use this `await client.joinGroup(url.split('/')[3]);`

do i have to use await?

**Comment by ArmyNicolasG** [comment]
like this?
      vinculo = message.body.split(' ');
      vinculo = message.body[1];
      client.joinGroup(vinculo.split('/')[3])

**Comment by RubberArchind** [comment]
what is vinculo value?
url in my example is something like this https://chat.whatsapp.com/abcbakjsbdjka

**Comment by orkestral** [comment]
yes
