### ISSUE TITLE
profilePicThumbObj gets only eurl to array number 17

### ISSUE THREAD

**Issue by rafaelbellintani** [orkestral/venom#687]
First place,  sorry for my bad english.

I'm trying to put the profile pictures inside a img tag with the Contact profilePicThumbObj eurl, but i noticed that when the iteration reach array[17], profilePicThumbObj returns only {}, and eurl returns unknow. How can i get the rest of the profile pictures, there is another parameter that i can use?

**Comment by orkestral** [comment]
only and image returned when profile allows image to be displayed for profiles outside your contact
