### ISSUE TITLE
getAllUnreadMessages() Not Working

### ISSUE THREAD

**Issue by chrisk8er** [orkestral/venom#689]
## Description
I get an error message after using getAllUnreadMessages() function.

## Environment

- **Venom version(s):** 3.0.6
- **Browser:** Chrome 88
- **OS:** OSX 10.13.6
- **Node version:** Node 12.18.3

## Steps to Reproduce

1. Hit getAllUnreadMessage() function.

## Log Output

```
Not relevant output
```

## Your Code

```
async getAllNewMessages(): Promise<any> {
    if (this.clientIsReady()) {
      try {
        const messages = await this.client.getAllUnreadMessages()
        inDev && console.log(messages)
        return messages
      } catch (error) {
        inDev && console.log(error)
      }
    }
  }
```

**Comment by OrhanArslan** [comment]
getAllUnreadMessages was not working properly. For example when there are 3 unread messages, function returns much more messages than 3

**Comment by chrisk8er** [comment]
Hope someone could fix this problem.

**Comment by OrhanArslan** [comment]
@orkestral could you add @chrisk8er 's solution to the project?
