### ISSUE TITLE
When I send messages too fast, the message id doubles on return

### ISSUE THREAD

**Issue by devpremium** [orkestral/venom#693]
When I send messages very fast the message id doubles on return, in the print below I give a log console of the result of sending by the sendText function and the ids are returned with duplication, only when fired very fast it almost always doubles when I send two messages in the same second.

![Screenshot_1](https://user-images.githubusercontent.com/52453013/109831385-26fe5f80-7c1e-11eb-8850-97293b38020d.jpg)

With the duplicity of the ids I don't know what the real id of the message I sent making it impossible to use the id for other functions such as deleting the message or consulting.

I am using the latest version available

**Comment by devpremium** [comment]
Each message was called individually with an http request

**Comment by devpremium** [comment]
In the ack the return of these messages do not repeat the ids, apparently the problem is only in sendText
![image](https://user-images.githubusercontent.com/52453013/109832800-785b1e80-7c1f-11eb-94b6-fa747270342e.png)

**Comment by jonalan7** [comment]
**I will take a look!**

**Comment by jonalan7** [comment]
**Error fixed**
