### ISSUE TITLE
Error Phython

### ISSUE THREAD

**Issue by marciusbezerra** [orkestral/venom#694]
Error.

C:\Projetos\Node\venom-wp\node_modules\sleep>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used

**Comment by marciusbezerra** [comment]
am I going to have to install this fucking phython now?

**Comment by antirek** [comment]
curses are unnecessary

if script said "I need python", please, give it python ))))
