### ISSUE TITLE
Receive image

### ISSUE THREAD

**Issue by whande1992** [orkestral/venom#697]
## Description
BASE64 of the images received is of very low quality, what is the correct way to download the images?
[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** 12.18.0
- **Browser:** Versão 88.0.4324.182 (Versão oficial) 64 bits
- **OS:** Ubuntu 20.04
- **Node version:** 12

## Steps to Reproduce

1 - Receive an image
2 - Capture base64 in the message content
3 - Decode base64, the image will be in low quality.

```
{
  id: 'false_554299841696@c.us_3A5DFF4C29EC544EDB0D19E9A6E2B672',
  body: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABsbGxscGx4hIR4qLSgtKj04MzM4PV1CR0JHQl2NWGdYWGdYjX2Xe3N7l33gsJycsOD/2c7Z//////////////8BGxsbGxwbHiEhHiotKC0qPTgzMzg9XUJHQkdCXY1YZ1hYZ1iNfZd7c3uXfeCwnJyw4P/Zztn////////////////CABEIAEEAMQMBIgACEQEDEQH/xAAtAAADAQEBAAAAAAAAAAAAAAAAAQIDBAUBAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEAMQAAAA9pUlI0ZjuBwncZ1Ka1mLQU1QAETUCHROudjEEZ1nZd56y52IsQJBYUEIAAF//8QAIxAAAgICAgEEAwAAAAAAAAAAAREAAiExEBIDIjJBUQQTIP/aAAgBAQABPwAgioAEIssAOdXsQ0AKFIKoe1TYh/BoTuW7fEd/lTtjEdvqZ5JyBLnEGBDdbhuviAsPg+6EMQFOHtghQF8ncLAClcgyy6htSnUa5O5ZoKDULWBKNFjl+ozyhr1KBWrgxFAAz9ZZPYytTUbfFr1Bh8njtgyholWOGylbdhrggRD6/r//xAAYEQACAwAAAAAAAAAAAAAAAAACEBJAUf/aAAgBAgEBPwBxHKP/xAAYEQACAwAAAAAAAAAAAAAAAAACEBJAUf/aAAgBAwEBPwBzLaP/2Q==',
  type: 'image',
  t: 1614881569,
  notifyName: '',
 (...)
}
```

**Comment by antirek** [comment]
in message base64 - it's preview

use example https://github.com/orkestral/venom#downloading-files decryptFile 

and message must contain deprecatedMms3Url
