### ISSUE TITLE
Audio files need a modification to work

### ISSUE THREAD

**Issue by antonio-couto** [orkestral/venom#7]
The message with audio files (opus) has "type":"ptt" and "isMedia":false, so the function downloadFile
on whatsapp.ts modeule checks the flag isMedia = true in order to download the audio file, if i remove this check the audio file is downloaded properly.
Thanks in advance.
Antonio

**Comment by orkestral** [comment]
in version 1.0.1 that we are going to create for the weekend now, we will include a new specific function for this function, thanks!
