### ISSUE TITLE
sendLinkPreview not workin on 3.0.8

### ISSUE THREAD

**Issue by 239626** [orkestral/venom#701]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jonalan7** [comment]
**The problem has now been fixed! Just update to the latest version!**

**Comment by 239626** [comment]
@jonalan7 
thanks for the fix

I tested it and it works fine in 3.0.9, 
but the link is sent twice in the message twice, one on the head of the message and one where I put it.
