### ISSUE TITLE
Venom suddenly stops receiving new messages

### ISSUE THREAD

**Issue by nicolasdeory** [orkestral/venom#702]
## Description

Bot suddenly stops receiving new messages or sending new ones after a few hours. It seems like the connection with WA Web is lost, but no error is thrown so the only way to check bot health is by sending ping messages to itself.

## Environment

- **Venom version(s):** 3.0.8
- **Browser:** Chromium 88
- **OS:** Windows 10
- **Node version:** Node 14

## Steps to Reproduce

1. Launch the bot
2. After a few hours it'll stop responding to messages and lose connection to the Whatsapp Web instance

## Log Output

N/A

## Your Code

```javascript
create('test2',
    (base64Qrimg, asciiQR, attempts) => { },
    (statusSession, session) => { console.log(statusSession) },
    {
        useChrome: false,
        browserArgs: ['--no-sandbox']
    },
    JSON.parse(process.env.WHATSAPP_TOKEN ?? ''))
    .then((client) => 
    {
       // this is a class defined elsewhere
        bot(client);
    })
    .catch((error) => console.log(error));

// inside the bot class
client.onAnyMessage((message) =>
    {
        console.log(message.body);
        // after a while, it'll stop receiving messages
    })
```

**Comment by budimanlai** [comment]
in version 3.0.5, my bot suddenly can't receive messages. And after upgrade to 3.0.8, my bot Failed to authenticate. Please advices.

**Comment by jonalan7** [comment]
Try to upgrade to the most current version! If the problem still exists, create a more detailed issue!
