### ISSUE TITLE
Unable to load the sleep module (no animation available)

### ISSUE THREAD

**Issue by ryugif** [orkestral/venom#713]
Hi, im facing this error when i upgrade to newest version, even when i trying to make new app using venom-bot on my server. Im deploying my app on VPS in digitalocean. thanks before 

The log : 
`- Unable to load the sleep module (no animation available)`

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem

**Comment by downdawn** [comment]
Same question. venom-bot+socket.io

**Comment by adsau59** [comment]
yeah getting the same log but no issues other than that

**Comment by jjeanjacques10** [comment]
Same error here. I received this error when I tried move my code to another file. For example:

## It works
- src
  - index.js << My code is here

## It not works
- src
   - adapters
      - whatsapp.js << Now my code is here
    - index.js

Error:
```Unable to load the sleep module (no animations available)```
