### ISSUE TITLE
Function forwardMessages() return error 404 

### ISSUE THREAD

**Issue by campagnani** [orkestral/venom#717]
## Description

Function forwardMessages() doesn't works and return error 404 when is called.

## Environment

- **Venom version(s):** [3.0.6 to 3.0.9]
- **Browser:** [Chromium 88.0.4324.182]
- **OS:** [Debian 11 Arm64, but also in Debian 11 Amd64 and Ubuntu 20.04 Amd64]
- **Node version:** [Node 14]

## Steps to Reproduce

1. Compile the code
2. Run the code
3. When the function is called it will return an error

## Code

```
...
try{
    let chats = await this.client.getAllChatsGroups();
    for (const chat of chats) {
        const chatId = chat.id._serialized;
        await this.client.forwardMessages(chatId, [message.id], false);
    }
}
catch (error) {
    console.log(error);
}
...
```

## Log Output

```
{
    me: { //much information// },
    to: { //much information// },
    erro: true
    text: null
    status: 404
    type: 'forwardMessages'
}
```

## Additional information

The problem started with version 3.0.6
I believe that from this commit: 
Return object forwardMessages and sendText ([ee40497](https://github.com/orkestral/venom/commit/ee404970ecad12f704e1b21363c87f84292b69b8))

**Comment by jonalan7** [comment]
Two questions, is the message identification correct? Is message sent?

**Comment by campagnani** [comment]
"is the message identification correct?"

```
this.client?.onMessage(this.messageReceived.bind(this));
```

```
async messageReceived(message: Message){
```
```
await this.client.forwardMessages(chatId, [message.id], false);
```

"Is message sent?"
No.

**Comment by jonalan7** [comment]
Tested here is works normally! Upgrade to the latest version! Or review your script again!

```
client.onMessage(async (message) => {
   await client.forwardMessages(message.to, message.id, false)
     .then((result) => {
        console.log(result); //return object success
     })
     .catch((erro) => {
        console.log(erro); //return object error
     });
  });
```

**Comment by campagnani** [comment]
I tested the new versions and continue the same error. So I think have a error in my code, but I don't identified. Could you please point the error in the code to me?

The purpose of the code is to forward messages from the VENOM-BOT group to all other groups.

´´´
import { create, Message, Whatsapp } from "venom-bot";

class Bot
{
    client?: Whatsapp;

	async init() 
	{
		const client = await create("VENOM");
		if (client == null)
		{
			console.log("create() retornou false ao invés de um client");
			return;
		}
		this.client = client;
		this.client?.onMessage(this.messageReceived.bind(this));
	}

    async messageReceived(message: Message) 
    {
        if (this.client == null){return;}

        try
        {
            const groupName = "VENOM-BOT";
            if (message.chat.isGroup && message.chat.contact.name === groupName)
            {
                let chats = await this.client.getAllChatsGroups();

                for (const chat of chats)
                {
                    if (chat.contact.name === groupName) { continue; }

                    const chatId = chat.id._serialized;
                    await this.client.forwardMessages(chatId, [message.id], false)
                    .then((result) => {
                           console.log(result); //return object success
                    })
                   .catch((erro) => {
                           console.log(erro); //return object error
                    });
                }
            }
        }
        catch (error)
        {
            console.log(error);
        }
    }
}

async function main()
{
    const bot = new Bot();
    await bot.init();
}

main().then(() => {});
´´´

**Comment by m0w4hhed** [comment]
same with me, on v3.0.11, while receiving a message from group then forward to another group,

using:
`client.forwardMessages(TARGET_ID, MESSAGE_ID, false)`

return an error like this:
`
{"me":{"id":"1","ref":"1@ijx24Q2vi1VkhI1/WAchgCyFASRGKPg9RfmdfJEaxGMByxDIZAopi3lZdfxjHRtAS0jZ0EP457eZww==","refTTL":20000,"wid":{"server":"c.us","user":"6283127006124","_serialized":"6283127006124@c.us"},"connected":true,"protoVersion":[0,17],"clientToken":"DgfwC+l1zS0g0COmVV8JL+c2ylaEA7y7KP0V3K1J4c8=","serverToken":"1@/6ep9ogE19N7eJpdUeNLPrGsD3iI165wpPOkry+jnTyfKGRfa8URc2JhaRLVhOUkB+I2xJ4ET3cGJA==","isResponse":"true","battery":33,"plugged":false,"lc":"ID","lg":"in","locales":"id-ID","is24h":true,"platform":"smba","phone":{"wa_version":"2.21.4.22","mcc":"510","mnc":"011","os_version":"7.0","device_manufacturer":"Xiaomi","device_model":"mido","os_build_number":"AL1512-mido-build-20191107001817"},"tos":0,"smbTos":0,"pushname":"NH Update","stale":false,"blockStoreAdds":false,"isVoipInitialized":false},"to":{"fromMe":false,"remote":{"server":"g.us","user":"6281333908590-1587175217","_serialized":"6281333908590-1587175217@g.us"},"id":"4D4E209A2BE1C34DDF21A084B4391B33","_serialized":"false_6281333908590-1587175217@g.us_4D4E209A2BE1C34DDF21A084B4391B33","formattedName":"DRAFT NH","isBusiness":false,"isMyContact":false,"isOnline":null},"erro":true,"text":null,"status":404,"type":"forwardMessages"}
`
and works in version < 3.0.5

**Comment by m0w4hhed** [comment]
@jonalan7

**Comment by jonalan7** [comment]
I'll take a look!  @m0w4hhed

**Comment by m0w4hhed** [comment]
up up,.... still not working with newest version

**Comment by jonalan7** [comment]
I tested it in group chat and it works normally!

**Comment by campagnani** [comment]
I just tested it in version 3.0.14 and it still doesn't work. This is my code:

```
import { create, Message, Whatsapp } from "venom-bot";

class Bot
{
    client?: Whatsapp;

    async init() 
    {
        const client = await create("Coreia");
        if (client == null) {return;}
        this.client = client;
        this.client?.onMessage(this.messageReceived.bind(this));
        console.log("Inicializado!");
    }

    async messageReceived(message: Message) 
    {
        if (this.client == null){return;}

        try
        {
            const groupName = "CoreiaZap";
            if (message.chat.isGroup && message.chat.contact.name === groupName)
            {
                let chats = await this.client.getAllChatsGroups();
                for (const chat of chats)
                {
                    if (chat.contact.name === groupName) { continue; }
                    const chatId = chat.id._serialized;
                    await this.client.forwardMessages(chatId, [message.id], false);
                }
            }
        }
        catch (error)
        {
            console.log(error);
        }
    }
}
    
async function main()
{
    const bot = new Bot();
    await bot.init();
}

main().then(() => {});
```

**Comment by campagnani** [comment]
@jonalan7

**Comment by campagnani** [comment]
I tested in new version 3.0.15 and it still doesn't work. Same error 404 and don't forward mesages.

**Comment by campagnani** [comment]
@jonalan7 Still don't working in version 3.0.16. 

I am trying forward messages that I receive from other people in a specifc group, to other groups. Like a bridge.

But don't forward and give the error 404:

```
{
    me: { //much information// },
    to: { //much information// },
    erro: true
    text: null
    status: 404
    type: 'forwardMessages'
}
```

**Comment by jonalan7** [comment]
I haven't stopped to take a look at this feature yet! When it's time I'll take a look!

**Comment by campagnani** [comment]
I tested in new version 3.0.17 and it still doesn't work.

**Comment by mailonruan** [comment]
I'm also having problems forwardMessages, venom version 3.0.19
