### ISSUE TITLE
Can't send non-contact message

### ISSUE THREAD

**Issue by mrksvol** [orkestral/venom#718]
If i send to non-contact user message - "UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.match is not a function"

Before it works

**Comment by jonalan7** [comment]
What function are you using? What would that non-contact look like?

**Comment by mrksvol** [comment]
> What function are you using? What would that non-contact look like?

sendText()

The number that is not in your contacts

**Comment by antirek** [comment]
what version of venom? @mrksvol 
I use venom 3.0.9 and it's ok.

**Comment by jonalan7** [comment]
bro I believe it is a problem with your project! Put your code so I can evaluate!

**Comment by mrksvol** [comment]
This is just a test bench that I was testing
`const message = 'Привет, как дела?';

const venom = require('venom-bot');
let fs = require('fs'),
    readline = require('readline');
let rd = readline.createInterface({
    input: fs.createReadStream('numbers.txt'),
});
let array = []; 
rd.on('line', (line) => {
    console.log(line)
    array.push(line)
})
rd.on('close', () => {
    console.log(array)
})


venom
  .create(
    'sessionName',
    undefined,
    (statusSession, session) => {
      console.log('Status Session: ', statusSession);
      //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || dele>
      //Create session wss return "serverClose" case server for close
      console.log('Session name: ', session);
    },
    undefined
  )
  .then((client) => {
      console.log(client)
      for(let i=0; i<array.length; i++){
        client
            .sendText(array[i] + '@c.us','test')
            .then((result) => {
                console.log(`Sended ${array[i]}`); //return object success
            })
            .catch((erro) => {
                console.error(`Error`); //return object error
            });
      }

  })`

**Comment by mrksvol** [comment]
This is just a test bench that I was testing

```js
const message = 'Привет, как дела?';

const venom = require('venom-bot');
let fs = require('fs'),
    readline = require('readline');
let rd = readline.createInterface({
    input: fs.createReadStream('numbers.txt'),
});
let array = []; 
rd.on('line', (line) => {
    console.log(line)
    array.push(line)
})
rd.on('close', () => {
    console.log(array)
})


venom
  .create(
    'sessionName',
    undefined,
    (statusSession, session) => {
      console.log('Status Session: ', statusSession);
      //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || dele>
      //Create session wss return "serverClose" case server for close
      console.log('Session name: ', session);
    },
    undefined
  )
  .then((client) => {
      console.log(client)
      for(let i=0; i<array.length; i++){
        client
            .sendText(array[i] + '@c.us','test')
            .then((result) => {
                console.log('sended'); //return object success
            })
            .catch((erro) => {
                console.error('error'); //return object error
            });
      }

  })


```

**Comment by jonalan7** [comment]
I found the problem! You are sending a message to a number that does not exist!

**Comment by mrksvol** [comment]
> I found the problem! You are sending a message to a number that does not exist!


No, I rechecked
If there is an active dialog - it sends, I deleted the dialog - such an error

>(node:9301) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: e.match is not a function
    at new l (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1052938)
    at new s (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1057160)
    at Object.window.WAPI.window.WAPI.getNewMessageId (<anonymous>:1:57115)
    at async Object.window.WAPI.window.WAPI.sendMessage (<anonymous>:1:37297)
    at ExecutionContext._evaluateInternal (/home/mrks/Рабочий стол/WORK/scripts/StressTestWA/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/mrks/Рабочий стол/WORK/scripts/StressTestWA/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:9301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9301) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jonalan7** [comment]
Has the issue been fixed! #720

**Comment by mrksvol** [comment]
> Has the issue been fixed! #720

Thank!
But I don't understand how to get the fix xD
I am using npm

**Comment by mrksvol** [comment]
Thanks!

**Comment by jonalan7** [comment]
I will not do an update yet at npm, if you want you can do the following!
Download the project or make a fork, then download all the dependencies, using the command: 
`npm i`
After downloading, build the project using the command: 
`npm run build`
You will get a folder like the name dist, replace that dist in your current project!

**Comment by AkashWeybee** [comment]
> @mrksvol
> I will not do an update yet at npm, if you want you can do the following!
> Download the project or make a fork, then download all the dependencies, using the command:
> `npm i`
> After downloading, build the project using the command:
> `npm run build`
> You will get a folder like the name dist, replace that dist in your current project!

It's working now 🎉💛

Sir, please update npm with this important update.

Literally, I can't thank enough, This is the best repo.

**Comment by xzvcit** [comment]
Bro, please update npm  :(
Anyone who works with docker will find it inconvenient to replace a node_modules

**Comment by dmastag** [comment]
I am not able to rebuild npm run build and keep getting 


```
ERROR in ./middleware.ts 55:0
Module parse failed: The keyword 'enum' is reserved (55:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
| */
> enum ExposedFn {
|   OnMessage = 'onMessage',
|   OnAck = 'onAck',
```

I guess i'll just have to wait until an update has been pushed to npm

**Comment by jonalan7** [comment]
**Download the latest version!**

**Comment by cassioseffrin** [comment]
@jonalan7 it's working on version 3.0.9, however in latest version 3.0.17 still the same ! Do you have any estimative when your commit will be released to npmjs.com ?

**Comment by mrksvol** [comment]
Alo beat Che za huita
