### ISSUE TITLE
sendSeen() is not working

### ISSUE THREAD

**Issue by brendomaciel** [orkestral/venom#719]
## Description

The method getAllUnreadMessages() is returning the entire message history of a chat with unread messages, event if it was mark as seen previously.

## Environment

- **Venom version(s):** 3.0.9
- **Browser:** Chrome 89.0.4389.82 64 bits
- **OS:** Windows 10
- **Node version:** Node 14.15.0

## Steps to Reproduce

1. Start a new conversation sending a message from another device (not the device where WhatsApp is logged in) to the WhatsApp account logged in Venom
2. Execute a sendSeen() for that chat
3. Send another message from the other device
4. Execute getAllUnreadMessages() and log the result
5. Now you should be able to see two messages logged

I supose that sendSeen() should update "ack" message property with other value rather than "-1", since [getAllUnreadMessages()](https://github.com/orkestral/venom/blob/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/lib/wapi/functions/get-all-unread-messages.js) uses this exact same criterion. But when I use getAllMessagesInChat(), it all comes with "ack" equals to "-1".

**Comment by jonalan7** [comment]
Two questions, is the message identification correct? Is message sent?

**Comment by jonalan7** [comment]
Two questions, is the message identification correct? Is message sent?

**Comment by igiul667** [comment]
Same problem
