### ISSUE TITLE
function SendFile transforms image and does not send as file

### ISSUE THREAD

**Issue by joaosouz4** [orkestral/venom#72]
I need to send an image as a file through venom without going through any transformation process

**Comment by Gabriel-Almeida-Ajax** [comment]
any example of using this function, need to do any specific imports?

**Comment by joaosouz4** [comment]
@Gabriel-Almeida-Ajax have in the official documentation

**Comment by bhavya32** [comment]
@joaosouz4 I would really love this function to not change. It is so easy to use. I do not want to check my buffer if it is image or video or file. I simply forward it to sendFile.

**Comment by joaosouz4** [comment]
Your argument is completely valid, but this problem has been created for a long time and we have not yet found a solution for it, but once it is found, we will probably create a new function, thank you.
