### ISSUE TITLE
Erro Evaluation 

### ISSUE THREAD

**Issue by KreisonReis** [orkestral/venom#720]
Error: Evaluation failed: TypeError: e.match is not a function
0|api_zap  |     at new l (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1052938)
0|api_zap  |     at new s (https://web.whatsapp.com/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js:1:1057160)
0|api_zap  |     at Object.window.WAPI.window.WAPI.getNewMessageId (C:\Users\Administrator\Desktop\api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:57115)
0|api_zap  |     at async Object.window.WAPI.window.WAPI.sendMessage (C:\Users\Administrator\Desktop\api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:37297)
0|api_zap  |     at ExecutionContext._evaluateInternal (C:\Users\Administrator\Desktop\api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
0|api_zap  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|api_zap  |     at async ExecutionContext.evaluate (C:\Users\Administrator\Desktop\api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

on sendText, my version "venom-bot": "^3.0.9"

**Comment by KreisonReis** [comment]
my code:
async api(request, response){
		let numero = request.query.number,
			texto =  request.query.text;

		await global.cli
			.sendText(numero+'@c.us', texto)
			.then((result) => {
				return response.json('OK');
			})
			.catch((erro) => {
				return response.status(400).send({'message': erro});
			});
	}
	
	reinstalled node_modules but the error persists

**Comment by jonalan7** [comment]
**I made a correction to the problem!**
