### ISSUE TITLE
Close browser after some time of inactivity

### ISSUE THREAD

**Issue by rrispoli** [orkestral/venom#723]
**Is your feature request related to a problem? Please describe.**

The big problem for me to have multiple venom instances running at same time is the large memory usage of Chrome, even if it headless and with some time of inactivity.

I run some memory tests and each venom instance (with Chrome running locally per instance) average memory usage is about 220~250mb.

After some search, I found this platform https://browserless.io that allow Puppeteer connect throught remote WSS endpoint. With this, each venom instance (with remote wss Chrome connection) average memory usage is about just 10~20mb!

But in venom the browser remains opened all the time and browseless.io charge for browser running seconds.

So, running Chrome browser remotely or even locally it would be great if there was a way to keep the venom instance running, but close the browser after some time of inactivity and only open browser when some method is called.

This feature already exist or can be implemented?

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem
