### ISSUE TITLE
'The number does not exist' on a perfectly valid number.

### ISSUE THREAD

**Issue by ghuwe** [orkestral/venom#731]
## Description

In 3.0.9, I use sendText to send a message, and it works perfectly.
In 3.0.10, the same code, with the same number returns a 404 'The number does not exist' error message.

## Environment

- **Venom version(s):** 3.0.10
- **Browser:** Any
- **OS:** Arch Linux
- **Node version:** Node 15

## Steps to Reproduce

1. Update to 3.0.10
2. Use the sendText function.

**Comment by reynaldomota** [comment]
I have the same problem to use .sendText ().

It returns error
  Object.window.WAPI.window.WAPI.getNewMessageId
at async Object.window.WAPI.window.WAPI.sendMessage

I've already upgraded to the pressure cooker and nothing! = /

I'm going to go crazy !!
