### ISSUE TITLE
Browser não abre

### ISSUE THREAD

**Issue by mvac1991** [orkestral/venom#736]
A aplicação rodava normalmente mas percebo que as vezes aparece esse erro:

✓ You're up to date
✓ headless option is active, browser hidden
✓ headless option is active, browser hidden
✖ Error no open browser....

O que pode ser?

**Comment by antirek** [comment]
what options for start venom you are using?

for example
`````
{
   "autoClose":0,
   "browserArgs":[
      "--no-sandbox"
   ],
   "headless":true,
   "devtools":false,
   "useChrome":false,
   "debug":false,
   "logQR":false,
   "disableSpins":true,
   "disableWelcome":true
}
`````

**Comment by jonalan7** [comment]
**Venom did not find the browser on your operating system! Install the browser!
Try:** `npm install --save chromium`

**Comment by jonalan7** [comment]
Or see: #290

**Comment by mvac1991** [comment]
.create(
        user_whatsapp,
        (base64Qr, asciiQR)  => {
        exportQR(base64Qr, '../qrCodes/' + user_whatsapp + '.png');
        function exportQR(qrCode, path) {
            qrCode = qrCode.replace('data:image/png;base64,', '');
            const imageBuffer = Buffer.from(qrCode, 'base64');
            fs.writeFileSync(path, imageBuffer);
        }},  
        // statusFind
        (statusSession, session) => {
            console.log("Status da sessão -> ", statusSession) //return isLogged || notLogged || browserClose || qrReadSuccess || qrReadFail || autocloseCalled || desconnectedMobile || deleteToken
            if ( statusSession==="browserClose" || statusSession==="qrReadError" || statusSession==="notLoggedhecking" || statusSession==="deleteToken" ) {
                console.log("Encerrando conexão com client.")
                encerrarClient(user_id, user_whatsapp) //encerrar client
            }
            if ( statusSession==="inChat" ) {
                console.log("Ativando conexão com client.")
                ativarClient(user_id) //encerrar client
            }
            console.log("Sessão -> ", session)
        },
        {
            useChrome: false,
            browserArgs: ['--no-sandbox'],
            headless: true, // ocultar / visualizar chrome
            autoClose: 60000
        })

    .then((client) => {
        usuarioAtual.client = client;
        return client
    })

    .catch(err=> console.log(err));

**Comment by mvac1991** [comment]
Este código funcionava perfeitamente

está em um servidor linux centos

tem umas 4 pessoas que utilizam

de repente ele cai e fica retornando esses error abaixo:

![Screenshot_7](https://user-images.githubusercontent.com/35501007/111481490-c6891b00-8711-11eb-8e5a-7b8c77b1f33d.jpg)

**Comment by mvac1991** [comment]
Eu coloquei uma regra para que o sistema funcione adequadamente

quando o usuário clica em CONECTAR é iniciado uma instância do client no servidor

se ele não se conectar em 60 segundos a instancia fecha por causa do autoClosed.

**Comment by AndersonVale** [comment]
> what options for start venom you are using?
> 
> for example
> 
> ```
> {
>    "autoClose":0,
>    "browserArgs":[
>       "--no-sandbox"
>    ],
>    "headless":true,
>    "devtools":false,
>    "useChrome":false,
>    "debug":false,
>    "logQR":false,
>    "disableSpins":true,
>    "disableWelcome":true
> }
> ```

worked for me...
tks

**Comment by alexprazeres** [comment]
aqui no CentOS 7 só funcionou após essas configurações:
```
{
      headless: true,
      browserArgs: ['--no-sandbox', '--disable-setuid-sandbox']
  }
```
