### ISSUE TITLE
Não consigo enviar VÍDEOS

### ISSUE THREAD

**Issue by mvac1991** [orkestral/venom#747]
Eu consigo enviar ÁUDIOS, PDF, IMAGENS utilizando a função **sendVideoAsGif** perfeitamente.

Porém, não consigo, de forma alguma, enviar VÍDEOS. Já tentei as 2 alternativas:

**await client.sendFile( to_whatsapp, url_arquivo );**
**await client.sendVideoAsGif( to_whatsapp, url_arquivo );**

Nenhuma delas funcionou. Já procurei aqui nas issues e até agora não encontrei nenhuma solução.

**Comment by NiedsonEmanoel** [comment]
tenta o sendFileFromBase64

**Comment by mvac1991** [comment]
> tenta o sendFileFromBase64

Retorna este erro:

(Use `node --trace-deprecation ...` to show where the warning was created)
(node:13668) UnhandledPromiseRejectionWarning: #<Object>
(node:13668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:13668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jonalan7** [comment]
Você não tratou uma função assíncrona, você tem que colocar o comando .catch()

**Comment by mvac1991** [comment]
> Você não tratou uma função assíncrona, você tem que colocar o comando .catch()

Coloquei o tratamento, retorna o erro abaixo:
![erro sendfilefrombase64](https://user-images.githubusercontent.com/35501007/112085453-4e838080-8b69-11eb-92c7-9a8abb7d1743.jpg)

**Comment by mvac1991** [comment]
Tentei utilizar somente o SENDFILE e ele retornou INVALIDMEDIAFILE:
![Screenshot_9](https://user-images.githubusercontent.com/35501007/112090601-9bb82000-8b72-11eb-8ac5-ceab308d38f7.jpg)

**Comment by mvac1991** [comment]
Sinceramente, já não sei mais o que fazer.

A função de enviar VÍDEOS está bugada.

**Comment by paulocorcino** [comment]
Veja se você não está usando com o puppeteer o chromium, ele não suporta envio de arquivos MP4. Para isto deve apontar a um Chrome.

**Comment by mvac1991** [comment]
> Veja se você não está usando com o puppeteer o chromium, ele não suporta envio de arquivos MP4. Para isto deve apontar a um Chrome.

Eu segui a documentação oficial do Venom e não funcionou, lá não diz que o chromium não suporta

Como eu faria para apontar pro Chrome?

**Comment by paulocorcino** [comment]
> > Veja se você não está usando com o puppeteer o chromium, ele não suporta envio de arquivos MP4. Para isto deve apontar a um Chrome.
> 
> Eu segui a documentação oficial do Venom e não funcionou, lá não diz que o chromium não suporta
> 
> Como eu faria para apontar pro Chrome?

https://orkestral.github.io/venom/interfaces/createconfig.html#usechrome
https://orkestral.github.io/venom/interfaces/createconfig.html#browser

Não se este parâmetro browser referencia o path do navegador, infelizmente não usei o Venom mas já passei por este erro quando o chromium.

**Comment by mvac1991** [comment]
> > > Veja se você não está usando com o puppeteer o chromium, ele não suporta envio de arquivos MP4. Para isto deve apontar a um Chrome.
> > 
> > 
> > Eu segui a documentação oficial do Venom e não funcionou, lá não diz que o chromium não suporta
> > Como eu faria para apontar pro Chrome?
> 
> https://orkestral.github.io/venom/interfaces/createconfig.html#usechrome
> https://orkestral.github.io/venom/interfaces/createconfig.html#browser
> 
> Não sei se este parâmetro browser referencia o path do navegador, infelizmente não usei o Venom, mas já passei por este erro quando é usado o chromium para tratar aequivos mp4, por ele não conter o codec.

[PROBLEMA RESOLVIDO]
Inclusive vejo muitas pessoas pesquisando por isso, e deu certo.

Adicionei o parâmetro **useChrome:true** e pronto!
![Screenshot_11](https://user-images.githubusercontent.com/35501007/112248848-6de7df80-8c35-11eb-875a-60171d030d01.jpg)

Obrigado 🤝

**Comment by tinazhe** [comment]
> How can I do this when my project is hosted on heroku?

i have the same problem
