### ISSUE TITLE
Suggestions of groups methods improvements

### ISSUE THREAD

**Issue by rrispoli** [orkestral/venom#749]
Hi, I'm working with groups and I have some suggestions:

Methods that can be included:
- **setGroupName:** (groupId: string, name: string)
- **setGroupDescription:** (groupId: string, description: string)
- **setGroupPhoto:** (groupId: string, filePath: string)
- **setGroupEditPermission:** (groupId: string, onlyAdmin: bool)
- **setGroupTypingPermission:** (groupId: string, onlyAdmin: bool)

Method that can be improved:
- **createGroup:** include (description: string) and (photoFilePath: string) parameters

**Comment by mohinderq** [comment]
Maybe a method like:

- **getGroupInfo(groupId: string) **
returns the group name, and description

**Comment by tisquip** [comment]
Hie/ Also maybe a setGroupMessagingParticipants(groupParticipants: enum). So you can set who is allowed to message in the group (i.e groupParticipants.allParticipants or groupParticipants.onlyAdmins). The option can be found on whatsapp web when in a group > group info > group settings > send messages.

Thanks

**Comment by jonalan7** [comment]
**we will be putting these functions in the future!**
