### ISSUE TITLE
Imagens agrupadas são duplicadas quando baixadas.

### ISSUE THREAD

**Issue by RaffDevs** [orkestral/venom#759]
Ao receber uma mensagem que são varias imagens agrupadas, todas são baixadas, porém repetidas. Ex:

1 - Alguém envia duas imagens agrupadas (imagem1.jpeg & imagem2.jpeg);
2 - As duas são baixadas. Vejo os  logs dos arquivos sendo escritos pelo fs.writeFile.
3 - Quando vou olhar na pasta, tem somente um arquivo.

A impressão que tenho é que  apesar de eu ver chegando uma mensagem para cada imagem, somente uma mensagem está sendo usada para baixar a imagem. Logo o writeFile escreve duas vezes o mesmo arquivo.

Segue o código:

`
const mime = require('mime-types');
const path = require('path');
const fs = require('fs');

module.exports = async (session) => {

        session.onMessage(async(message) => {

            let filename = `${message.from}_${message.timestamp}.${mime.extension(message.mimetype)}`;
  
            let filepath = path.join(__dirname, '../', 'public', 'downloads') + `/${filename}`;
                   
            const buffer = await session.decryptFile(message);
  
            await fs.writeFile(filepath, buffer, err => {
                if (err) {
                        console.log('Erro ao escrever o arquivo', err);
                         throw err;
               }
               console.log('Arquivo escrito com sucesso!');

}`

**Comment by esteban-url** [comment]
I fixed this by changing the file name to a more detailed name using date-fns
https://date-fns.org/v2.19.0/docs/lightFormat

```js
const lightFormat = require('date-fns/lightFormat')
// ...
const path = `${folderName}/${lightFormat(
                  new Date(),
                  'yyyy-MM-dd--HH-mm-ss-SSS'
                )}.${mime.extension(message.mimetype)}`
```

**Comment by RaffDevs** [comment]
Bro, you saved my life. Thanks a lot!!!!

**Comment by esteban-url** [comment]
no problem! I'm glad it worked for you!

--
Esteban Rojas
