### ISSUE TITLE
Mandar mensagens sempre que der 14h/ Send message when it's 2 P.M.

### ISSUE THREAD

**Issue by lfilipe09** [orkestral/venom#760]
Eu posso mandar mensagem em horários programados para uma lista de usuário todos os dias? Isso é possível? Vi que na documentação os eventos só são acionados se ocorre uma interação com o bot de alguma forma como mensagens novas, ligações e etc... Mas teria como eu rodar um programa secundário que avisa o bot sempre que der uma determinada hora para ele disparar para essa lista de pessoas a mensagem?

**Comment by devjva** [comment]
send a message to a specific contact without interaction


```
client
					  .sendText('5547988041608@c.us', '👋 Hello from venom!')
					  .then((result) => {
						console.log('Result: ', result); //return object success
					  })
					  .catch((erro) => {
						console.error('Error when sending: ', erro); //return object error
					  });
```

**Comment by lfilipe09** [comment]
Thank youuuuuuuu!

**Comment by ArmyNicolasG** [comment]
to send programmed messages...
setInterval(() => {
     client.sendText(to, "message");
}, 6000*1) //every 1 hour
