### ISSUE TITLE
Is this against Whatsapp's Terms of Service?

### ISSUE THREAD

**Issue by lfilipe09** [orkestral/venom#764]
I am thinking using this library to develop an academic research in my university, I see on internet nowadays a lot of companies that develop whatsapp chatbots using theis own API, but they don't have access to Whatsapp API according to the official [list](https://www.facebook.com/business/partner-directory/search?solution_type=messaging&platforms=whatsapp) . I've made some interviews with that companies that develop chatbot for whatsapp without license and they have told me that Whatsapp only blocks bulk messaging and abusive behavior.

And in my case this chatbot would bring such good things for the community i am working for, I will not send any bulk messaging and I'll only talk to people that is in my contact list or sent me a text before and they can leave chatbot anytime and the chatbot asks for permission to talking to people in first interaction.

Is this against Whatsapp's Terms of Service? I read this [article](https://faq.whatsapp.com/general/security-and-privacy/unauthorized-use-of-automated-or-bulk-messaging-on-whatsapp/?lang=en) and this [white paper](https://scontent.whatsapp.net/v/t61.22868-34/69510151_652112781951150_6923638360331596993_n.pdf/Stopping-Abuse-white-paper.pdf?ccb=1-3&_nc_sid=2fbf2a&_nc_ohc=L-Xdw3LDI68AX_G5bOt&_nc_ht=scontent.whatsapp.net&oh=971abb195a2cd607f463dfbcadfe65f8&oe=605B6E4F) and I'm very afraid

**Comment by antirek** [comment]
"Волков бояться - в лес не ходить" (russian proverb)

I think that venom is just an experiment for enthusiasts only. If you afraid - don't use & "don't worry, be happy" ;))

**Comment by edudesouza** [comment]
Please read its terms:

https://www.whatsapp.com/legal/
