### ISSUE TITLE
Message templates with interactive buttons 

### ISSUE THREAD

**Issue by 2482103133** [orkestral/venom#767]
Can I send a message template with interactive buttons like the examples in the link?
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/examples

![image](https://user-images.githubusercontent.com/37145130/112284511-4a1faa80-8cc4-11eb-955b-27ac5ddd6735.png)

**Comment by antirek** [comment]
I think that no. Or maybe any hack?

**Comment by jonalan7** [comment]
At the moment it is not possible to do this! This function has not yet been found! 😟

**Comment by famarojr** [comment]
Not yet in venom? I saw some no official accounts sending these buttons, but I don´t know if they use venom.

Any news?
