### ISSUE TITLE
Como entendo como funciona esse bot, e coisas do tipo... se posso ser bloqueado e tals...

### ISSUE THREAD

**Issue by sostenesapollo** [orkestral/venom#769]

**Comment by campagnani** [comment]
Você entende lendo a documentação:
[orkestral.github.io/venom](https://orkestral.github.io/venom)

[Começando a usar](https://orkestral.github.io/venom/pages/Getting%20Started/creating-client.html)

[Funções Basicas](https://orkestral.github.io/venom/pages/Getting%20Started/basic-functions.html)
