### ISSUE TITLE
send mp4 file error

### ISSUE THREAD

**Issue by Lucipher** [orkestral/venom#770]
await client
  .sendFile(
    '000000000000@c.us',
    'path/to/abc.mp4',
    'file_name',
    'send my mp4'
  )
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

return error

**Error: Evaluation failed: Error: InvalidMediaFileType**

**Comment by antirek** [comment]
I have same error sometimes on running instance, but can't reproduce on test instance

do you have detailed error description from output?

**Comment by Lucipher** [comment]
use chrome instead of chromium and then works!
