### ISSUE TITLE
Cannot read property 'wid' of undefined when reply or forward messages

### ISSUE THREAD

**Issue by vendergas** [orkestral/venom#773]
## Description

I get this error when I try to reply or forward any message using WAPI

## Environment

- **Venom version(s):** 3.0.11
- **Browser:** Chrome 89
- **OS:** Linux Mint 20.1
- **Node version:** Node 14

## Steps to Reproduce

I'm not using Venom, I'm just using the wapi.js lib of Venom.
Just try to reply or forward any message using WAPI.
It worked in previous version.

```javascript
window.WAPI.reply(chatId, content, quotedMessageId);
```

## Log Output

```
wapi.js:1 Uncaught (in promise) TypeError: Cannot read property 'wid' of undefined
    at Object.window.WAPI.window.WAPI.reply (wapi.js:1)
window.WAPI.window.WAPI.reply @ wapi.js:1
async function (async)
window.WAPI.window.WAPI.reply @ wapi.js:1
(anonymous) @ VM913:1
```

## Your Code

```javascript
window.WAPI.reply(chatId, content, quotedMessageId);
```

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem
