### ISSUE TITLE
getMessageById and loadAndGetAllMessagesInChat Returns document in messages that arrive as video

### ISSUE THREAD

**Issue by devpremium** [orkestral/venom#775]
The image arrived as "type": "video" on onMenssage but when I search with one of these two functions it returns as a document.

See in the example below how it arrives in onMessage, and how it looks when consulted in getMessageById:

![onM](https://user-images.githubusercontent.com/52453013/112650028-c1bb1a00-8e29-11eb-9ba2-a4531c0f7fc9.png)
![getM](https://user-images.githubusercontent.com/52453013/112650033-c2ec4700-8e29-11eb-9a60-46fb573ff16e.png)

**Comment by devpremium** [comment]
Another detail sometimes returns video sometimes document

**Comment by jonalan7** [comment]
For lack of more information this issue will be closed!
