### ISSUE TITLE
Erro em download de áudio

### ISSUE THREAD

**Issue by X-C0DE** [orkestral/venom#777]
Estou tendo alguns erros para baixar um áudio recebido. Inicialmente eu tentei da forma como o [exemplo](https://github.com/orkestral/venom#downloading-files) mostra.

Em um teste feito com áudio, imagem e video, eu recebi apenas imagem e video. Depois notei que o `message.isMedia` da minha mensagem estava vindo como falso, e foi daí então que mudei a condição para `message.type === "ptt"`, mas dessa forma ao tentar o download me foi retornado uma mensagem de erro:
```
(node:14015) UnhandledPromiseRejectionWarning: Error trying to download the file.
(node:14015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:14015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
Alguém sabe como eu posso estar resolvendo isso?

**Comment by X-C0DE** [comment]
Estranho que eu tentei de novo agora com um áudio e deu certo

**Comment by firat125** [comment]
Hi, I am trying to download media as well, how did you try to download the media? I don't see any built-in functions for it.
