### ISSUE TITLE
WhatsApp works with Google Chrome 60+ |  stopping at 'Checking is logged...' in console

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#780]
## Description

Sometimes instance disconnect from whatsapp server and show that "WhatsApp works with Google Chrome 60+" )))

I test it on Chromium 88 and Google Chrome 89 both.

## Environment

- **Venom version(s):** [e.g. 3.0.11]
- **Browser:** [e.g. Chrome 89, Chromium 88]
- **OS:** [ubuntu 20.04]
- **Node version:** [Node 14]

## Steps to Reproduce

1. create and run venom instance
2. wait day or week
3. get this screen 

![Screenshot (10)](https://user-images.githubusercontent.com/324436/112799207-3eebc680-9098-11eb-8b00-46a042e20793.png)

**Comment by chrisk8er** [comment]
i got this problem too...

**Comment by jonalan7** [comment]
**It must be an argent problem in the puppeteer, I verified, apparently argent is only recognizing windows, since you are using linux. This may be what is making the error happen! I will have to stop for a while to be able to analyze this problem!**

**Comment by antirek** [comment]
@jonalan7 move two my instances with this problem to venom 3.0.14  -> last three days - all right! 
may be changes in user-agent https://github.com/orkestral/venom/commit/60458e559d999eebe4ab4794d91fbaf9e3f01c06 help? 

do you have plan to upgrade puppeteer?

**Comment by antirek** [comment]
but this issue repeated again, also on venom-bot@3.0.14 :((

**Comment by jonalan7** [comment]
The problem still persists? @antirek

**Comment by antirek** [comment]
Yes

**Comment by jonalan7** [comment]
I found a solution! add to args :  

` --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36`

Or remove all parameters from the args in option 'browser Args' and leave the originals of the venom

[Parameters](https://github.com/orkestral/venom#optional-create-parameters)

**Comment by antirek** [comment]
yes, I use browserArgs (browserArgs: [ '--no-sandbox' ])
without --no-sandbox receive error: 'error on create Error no open browser....' it's maybe depend from root privileges?
ok, thanks, I updated my browserArgs

**Comment by antirek** [comment]
Maybe conflict? 
Whatsapp app show that paired with whatsapp-web from Chrome on Windows. And puppeteer-extra-plugin-stealth make that it's Chrome on Windows. But in some requests we set user-agent from Chrome on Linux?
@jonalan7

**Comment by AlanMartines** [comment]
after updating even with automatic closing disabled after generating 6x the qrcode it stops.

![image](https://user-images.githubusercontent.com/10979090/117181662-7b9b9380-ada3-11eb-96ae-c7c80b96bf8a.png)

**Comment by AlanMartines** [comment]
After I updated to version 3.0.16, it returned to normal operation, but it presented this situation that qrcode is loaded only 6x and stops, I have to start the process again ...
