### ISSUE TITLE
Is there a way i can make unlimited sessions?

### ISSUE THREAD

**Issue by itsOwen** [orkestral/venom#785]
is there a  way i can make unlimited sessions with venom for eg: my app is hosted on heroku and if anytime a new user arrives he/she will be able to login with his own whatsapp account

**Comment by jonalan7** [comment]
you can create multiple sessions this way : [Multiple Sessions]( https://github.com/orkestral/venom#venom-will-remember-the-session-so-there-is-no-need-to-authenticate-everytime)
