### ISSUE TITLE
Versão 3.0.12, não identificando desconexão via celular

### ISSUE THREAD

**Issue by leobevi** [orkestral/venom#794]
Olá,
Quando feita uma desconexão da sessão pelo celular o venom não está identificando esta desconexão.
Estava na versão 3.0.8 funcionava normalmente, atualizei para a versão 3.0.12 e quando o usuário desconecta a sessão do celular a mesma não é identificada.
Tentei capturar ela pelo client.onStateChange e quando descontato ele me mostra como OPENING, não consigo trabalhar com este status pois ele aparece em outras situações não somente na desconexão.

Existe uma outra forma de capturar o status de desconexão?

Obrigado!

**Comment by jonalan7** [comment]
The new update fixes this problem! You will receive in the option StatusFind, the return will be desconnectedMobile [Callback Status Session](https://github.com/orkestral/venom#callback-status-session)
