### ISSUE TITLE
 ERROR : onStateChange does not catch logout event - not solved in V3.0.12 

### ISSUE THREAD

**Issue by grupobyb** [orkestral/venom#795]
When disconnecting the session from the phone Venom-bot does not send the change of state

this happened to someone else ?

**Comment by didintri196** [comment]
me too..

**Comment by grupobyb** [comment]
any solution ?

**Comment by jonalan7** [comment]
The new update fixes this problem! You will receive in the option StatusFind, the return will be desconnectedMobile [Callback Status Session](https://github.com/orkestral/venom#callback-status-session)

**Comment by Pezhvak** [comment]
it doesn't work with `waitForLogin: false`. is there any other way? @jonalan7
