### ISSUE TITLE
No browser open

### ISSUE THREAD

**Issue by kingrootid** [orkestral/venom#796]
✓ You're up to date
Chrome not found, using chromium
✖ Error no open browser....
Error no open browser....
any solution ?

**Comment by kingrootid** [comment]
{
            folderNameToken: 'tokens', //folder name when saving tokens
            mkdirFolderToken: '', //folder directory tokens, just inside the venom folder, example:  { mkdirFolderToken: '/node_modules', } //will save the tokens folder in the node_modules directory
            headless: true, // Headless chrome
            devtools: false, // Open devtools by default
            useChrome: false, // If false will use Chromium instance
            debug: false, // Opens a debug session
            logQR: true, // Logs QR automatically in terminal
            browserArgs: ['--no-sandbox'], // Parameters to be added into the chrome browser instance
            disableSpins: true, // Will disable Spinnies animation, useful for containers (docker) for a better log
            disableWelcome: true, // Will disable the welcoming message which appears in the beginning
            updatesLog: true, // Logs info updates automatically in terminal
            autoClose: 60000, // Automatically closes the venom-bot only when scanning the QR code (default 60 seconds, if you want to turn it off, assign 0 or false)
        }

**Comment by antirek** [comment]
Do you see #736 ?
