### ISSUE TITLE
client.sendText not working after update

### ISSUE THREAD

**Issue by xshion13** [orkestral/venom#80]
please check it

**Comment by RubberArchind** [comment]
I also experienced it, it works in private chat but it doesn't work in group chat

**Comment by jvdutra** [comment]
It's not working to new contacts.

**Comment by jvdutra** [comment]
It's not working for new chats.

**Comment by jvdutra** [comment]
Private chat works sometimes.

**Comment by jonalan7** [comment]
> Eu também experimentei, funciona em bate-papo privado, mas não em bate-papo em grupo

**Comment by jonalan7** [comment]
the error has already been fixed! Please test

**Comment by smashah** [comment]
This is what happens when you don't know what you're doing when you're copy-pasting code.

**Comment by jonalan7** [comment]
> This is what happens when you don't know what you're doing when you're copy-pasting code.

you are absolutely correct! If you want to help, instead of criticizing, I am at your disposal!

**Comment by jonalan7** [comment]
> This is what happens when you don't know what you're doing when you're copy-pasting code.

Enjoy and copy and paste some functions that I will be doing here!

**Comment by xshion13** [comment]
> This is what happens when you don't know what you're doing when you're copy-pasting code.

i used your project even donated for it but idk where are you now since your project is closed and new bot with paid features got added maybe should i migrate again

**Comment by smashah** [comment]
@xshion13 [always welcome. I'm still actively working on it. There are only a few things that are paid, 99% of the work I do on it is still open source. Message me on the discord if you have any questions/want access to anything + there are some cool new features which I'm just writing documentation for now.](https://github.com/open-wa/wa-automate-nodejs)

**Comment by andazlan** [comment]
have the same problem...

**Comment by jonalan7** [comment]
**Fixed in the last update!**
