### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Session closed.

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#806]
## Description

When the qrcode is read everything works as expected, but if you logout directly from Whatsapp app ou using `logout() ` function is triggered an error.

## Environment

- **Venom version(s):** 3.0.12-alpha.0
- **Browser:** Chrome 88
- **OS:** Debian Stretch
- **Node version:** Node 14

## Steps to Reproduce

1. Read QrCode
2. Logout from Whatsapp

## Log Output

> 0|index  | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
> 0|index  |     at CDPSession.send (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
> 0|index  |     at ExecutionContext._evaluateInternal (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
> 0|index  |     at ExecutionContext.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:27)
> 0|index  |     at DOMWorld.evaluate (/var/www/whapi/node/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:90:24)
> 0|index  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by TanderBolt** [comment]
#807
