### ISSUE TITLE
onMessage event not working after update

### ISSUE THREAD

**Issue by jvdutra** [orkestral/venom#81]
It seems like onMessage event is not detecting new messages from new contacts after today's update.

**Comment by jonalan7** [comment]
is working normally!

**Comment by jvdutra** [comment]
Here messages from new contacts, that I didn't interact, aren't falling on "on message" event

**Comment by jonalan7** [comment]
I will give an observation

**Comment by elchory96** [comment]
The same thing happens to me, the moment I write you a new contact that you have never written, the venom does not take it, only when I turn off the server and upload it again.

**Comment by jeffersonveloso** [comment]
The same thing is happening to me, for new messages it is not detecting. If I stop the application and the person submits it again it detects it.

**Comment by jonalan7** [comment]
**Fixed in the last update!**
