### ISSUE TITLE
Problem sendContactVcard

### ISSUE THREAD

**Issue by luizclaudioleme** [orkestral/venom#816]
Name of contact - Appear as "You" and not with the name of the contact to be sent.

await client
  .sendContactVcard('000000000000@c.us', '111111111111@c.us', 'Name of contact')
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

**Comment by antirek** [comment]
Error log?

**Comment by luizclaudioleme** [comment]
Sorry, but how do I log?
