### ISSUE TITLE
Double Session

### ISSUE THREAD

**Issue by kingrootid** [orkestral/venom#817]
Hello,

i want to ask if i have a 2 session . 
session 1 called A
session 2 called B

how can i send a message to other phone number with A

here my code
`venom
    .create()
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });
venom.create('blabla')
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });
async function start(client) {
    client.onMessage((message) => {
        if (message.body === 'Hi' && message.isGroupMsg === false) {
            client
                .sendText(message.from, 'Welcome Venom 🕷')
                .then((result) => {
                    console.log('Ada pesan baru');
                    //   console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.log('Ada pesan baru Tapi Error');
                    // console.error('Error when sending: ', erro); //return object error
                });
        }
    });
    let battery = await client.getBatteryLevel();
    // console.log(battery);
    app.get('/', function (req, res) {
        res.status(200).json({ error: 'message' })
    })
    // console.log(client.getBatteryLevel());
}`

**Comment by antirek** [comment]
1. please format your code
2. do you read [multiple sessions](https://github.com/orkestral/venom#multiples-sessions-can-be-created-at-the-same-time-by-pasing-a-session-name-to-create-function)?
3. your can write like:
`````javascript 
const numberA = '000000000000@c.us'
await clientB.sendText(numberA, '👋 Hello from venom!')
`````

**Comment by kingrootid** [comment]
venom 
.create() 
.then((client) => start(client))
.catch((erro) => { console.log(erro); 
}); 
venom.create('blabla') .then((client) => start(client)) .catch((erro) => { console.log(erro); }); async function start(client) { client.onMessage((message) => { if (message.body === 'Hi' && message.isGroupMsg === false) { client .sendText(message.from, 'Welcome Venom 🕷') .then((result) => { console.log('Ada pesan baru'); // console.log('Result: ', result); //return object success }) .catch((erro) => { console.log('Ada pesan baru Tapi Error'); // console.error('Error when sending: ', erro); //return object error }); } }); let battery = await client.getBatteryLevel(); // console.log(battery); app.get('/', function (req, res) { res.status(200).json({ error: 'message' }) }) // console.log(client.getBatteryLevel()); }

> 1. please format your code
> 2. do you read [multiple sessions](https://github.com/orkestral/venom#multiples-sessions-can-be-created-at-the-same-time-by-pasing-a-session-name-to-create-function)?
> 3. your can write like:
> 
> ```js
> const numberA = '000000000000@c.us'
> await clientB.sendText(numberA, '👋 Hello from venom!')
> ```

how to define clientB to session b ?


here my code 
```js
const venom = require('venom-bot');

venom
  .create()
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });
venom
  .create('blabla')
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });
function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```

**Comment by antirek** [comment]
Srsly? 
Some variants:
1. do startA() and startB() and inside do anymore
2. or you can return client from start() and returned client do clientA = client on first create and same for clientB in 'blabla' session
3. or (my lovely) create instanceA.js and instanceB.js and write code for sessions independent ;))

**Comment by kingrootid** [comment]
> Srsly?
> Some variants:
> 
>     1. do startA() and startB() and inside do anymore
> 
>     2. or you can return client from start() and returned client do clientA = client on first create and same for clientB in 'blabla' session
> 
>     3. or (my lovely) create instanceA.js and instanceB.js and write code for sessions independent ;))

```js
const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
await fs.writeFile(fileName, buffer, (err) => {
if (err) {
console.log('Error downloading media');
  } else {
 let sql = `insert into media set media='${image}''`;
let query = con.query(sql, (err) => {
 if (err) throw err;
console.log(`{susccess: true,message : "pesan masuk from ${message.from} : '${message.body}'"}`);
 })
```

how about store image to mysql ?
column "media" type is blob

**Comment by antirek** [comment]
`````
await fs.writeFile(fileName, buffer, (err) => { 
`````
promise and callback in one line? it's not work so
try use writeFileSync instead, for example

and store media in db - so-so ((  media files save on fs, filepath - into db

Your last comment haven't relation to topic 'Double session' If you receive decision for 'double session' request, please, close this issue.
