### ISSUE TITLE
cannot start venom bot, getaddrInfo EAI_AGAIN

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#819]
cannot start my bot, it was working normally this week until today
![FOTO1VENOMBOT](https://user-images.githubusercontent.com/71280145/114177472-0e125980-9902-11eb-9f71-d588177f848f.png)
![FOTO2VENOMBOT](https://user-images.githubusercontent.com/71280145/114177638-41ed7f00-9902-11eb-8e01-063a7cb6e03d.png)

**Comment by antirek** [comment]
check your network connection and dns settings
venom try check new version in npm registry and can't do it

**Comment by antirek** [comment]
also you can try disable check updates venom-bot 
set updatesLog = false in config on start 

https://github.com/orkestral/venom/blob/29aa07959ad32402366f97e4867532d057304f3c/src/controllers/initializer.ts#L150

**Comment by jonalan7** [comment]
Apparently you don't have internet! Therefore, it is not possible to verify that you have a new update!
