### ISSUE TITLE
how the typing works

### ISSUE THREAD

**Issue by EduardoTayupanta** [orkestral/venom#833]
I have a problem typing before I send a message and stop typing.

**Comment by antirek** [comment]
Show your code

**Comment by EduardoTayupanta** [comment]
The scheme used is the following

// Start typing...
await client.startTyping('000000000000@c.us');

// Send basic text
await client.sendText('000000000000@c.us', '👋 Hello from venom!')

// Stop typing
await client.stopTyping('000000000000@c.us');
