### ISSUE TITLE
Conversations with threads

### ISSUE THREAD

**Issue by ArmyNicolasG** [orkestral/venom#834]
hi, how can i make a threading conversation? which means the bot answers taking into account the last messages, taking args with different messages

I WANT SOMETHING LIKE THIS:
![image](https://user-images.githubusercontent.com/71280145/114775402-df97e280-9d36-11eb-83af-438b8fae5196.png)

NOT THIS:
![image](https://user-images.githubusercontent.com/71280145/114775583-140b9e80-9d37-11eb-8973-1691ccbdcfdb.png)

**Comment by antirek** [comment]
I think that it's not venom-bot task.

You can store session with contact via 'flow steps' and write your logic how it works. Via command like '/command' from contact you start session flow for this contact. If your contact in flow - write question from step. And also add timeout exit from session with bye message if contact don't answer.

**Comment by ArmyNicolasG** [comment]
> I think that it's not venom-bot task.
> 
> You can store session with contact via 'flow steps' and write your logic how it works. Via command like '/command' from contact you start session flow for this contact. If your contact in flow - write question from step. And also add timeout exit from session with bye message if contact don't answer.

Something like using variables for storing data for each question sessions?

**Comment by antirek** [comment]
maybe, 
variables means 'in-memory'? - it's not 'restartable' )))

you can write scenario for sessions in code, but current 'step' of scenario for each contact store in db
after receiving message from contact you check current step and save for this data from message and move pointer of session to next step, may be so?

**Comment by antirek** [comment]
@ArmyNicolasG see bot example with sessions and steps (stages) https://github.com/juniorwmr/botwhatsapp-venom/
