### ISSUE TITLE
ciphertext no body

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#844]
## Description
Sometimes I receive message with type=ciphertext
message doesn't contain any text or body
I can't reproduce this message.

## Environment

- **Venom version(s):** [3.0.14]
- **Browser:** [Chrome 89]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

## Log Output

`````
id: 'false_7XXXXX@c.us_E50FF41DE3D73B37C12F6DD6E15CD601',
type: 'ciphertext',
t: 1618301286,
notifyName: '',
from: '7XXXXX@c.us',
to: '7XXXXX@c.us',
self: 'in',
ack: 0,
invis: false,
isNewMsg: true,
star: false,
recvFresh: true,
isFromTemplate: false,
broadcast: false,
mentionedJidList: [],
isVcardOverMmsDocument: false,
isForwarded: false,
labels: [],
isDynamicReplyButtonsMsg: false,
chatId: '7XXXXX@c.us',
fromMe: false,
sender: {
  id: '7XXXXX@c.us',
  type: 'in',
  formattedName: '+7 XXXXX',
  isMe: false,
  isMyContact: false,
  isPSA: false,
  isUser: true,
  isWAContact: true,
  profilePicThumbObj: {},
  msgs: null
},
`````

**Comment by Lucipher** [comment]
@antirek  did you fixed the problem ?

**Comment by antirek** [comment]
No. It's usually on first message from non contact list dialog or from status@broadcast.

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem

**Comment by ferbsferbs** [comment]
i have the same problem. ANy updates?

**Comment by felipewget** [comment]
I have the same problem @TanderBolt , closed because are no other occurrences? use bots with wpp multidevices and this problem show everytime

**Comment by filipemontt** [comment]
same problem

**Comment by drmss** [comment]
same problem.
first message of newly created chat has this problem.
please fix this

**Comment by valentinolopezbruno** [comment]
async function processCipherText(client, msgId, from){ setTimeout( async () => { const Messages = await client.getAllMessagesInChat(from); Messages.forEach(message => { if(message.id == msgId) { if(message.type == 'ciphertext'){ console.log('process again'); processCipherText(number, msgId, from); }else{ console.log('message processed'); console.log(message.body); } } }) }, 500); }
