### ISSUE TITLE
When I send a message, the "client" is getting undefined

### ISSUE THREAD

**Issue by lfilipe09** [orkestral/venom#845]
I start my chatbot with venom.create() and the program checks the hour in a .csv file to send messages to someone.

Ok, in te first value of the .csv file it does it very well and send a message in the hour that is written in file, all normal.  Let's supposed it's 8:00

But from the second value (8:01) onwards the 'client' gets undefined and comes the error: 'Cannot read property 'sendText' of undefined'

I tried venom.create() inside another venom.create() to check if works, I'm thinking that I have to reset the 'client' every time.
but this does not works.

Someone can help me?
Thank you!

**Comment by antirek** [comment]
show your code

**Comment by lfilipe09** [comment]
Ok, I think i will show in parts because all the program is over 2000 lines

I start the venom like this:

```
venom
    .create()
    .then((client) => {
        logEveryMinute(0, client);
        start(client);
        moment.locale('pt-br');
    })
    .catch((erro) => {
        console.log(erro);
    });
```

I pass the client in two functions. The start(client) is a function that is triggered when someone sends a message. The logEveryMinute function is a recursive function (calls itself forever) checking if it's the correct time in a .csv file to send a message. But, I don't know if it's like this, after someone talking to the chatbot and kind 'using' the 'client' it gets undefined for the other function 'logeveryminute'. But, the opposite it's not true. When 'logeveryminute' is triggered, the start(client) is not affected, and the client doesn't gets undefined.

I'll show you a piece of both functions because they are gigant

**This is a piece of the start(client) function**

```
function start(client) {
    //Ao receber mensagem
    client.onMessage((message) => {
        //verifica se faz muito tempo que não conversa
        var existe_tel = existData(message.from, 'telefone');
        //se o número já existe nabase
        if (existe_tel == true) {
            console.log('entrou no contexto hora');
            var hora = findDataUser(message.from, 'tempo');
            if (hora != 'hora') {
                if ((moment().valueOf() - hora > 2400000)) {
                    console.log('faz mais de 40min');
                    //AddData(message.from, 'tempo', 'contexto', '*');
                    //replaceData(message.from, '1', 'prospec');
                }
            }
            console.log('trocou');
            replaceData(message.from, moment().valueOf(), 'tempo')
        }    .
      (and other things.....)

}
```

**This is a piece of the logEveryMinute function**

async function logEveryMinute(i, client) {
        setTimeout(() => {
            console.log(moment().hour());
            console.log(moment().minute());
            logEveryMinute(++i);
       }, 60000)
}

If you want to see more I can send more slics of code! I'm afraid sending a gigantic message and people don't read it because of the size

**Comment by lfilipe09** [comment]
There's a way or command to 'refresh' the program?
I think the problem is about both functions share the same `client` feedback and, somehow, he gets undefined if used by `start(client)` or if passes a lot of time with program running without any command and I try to use sendText, the client become undefined too

**Comment by lfilipe09** [comment]
OMG I solved haha
Sorry guys! It was a silly mistake, in my recursive function, when I call it again I forgot pass the 'client' as a parameter haha
It was only this

**Comment by antirek** [comment]
It's "[Rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging)" 😀
