### ISSUE TITLE
Multiples sessions

### ISSUE THREAD

**Issue by merciomedina** [orkestral/venom#86]
Hi.
I have some questions:

1 - I need to create some sessions for differents phone numbers and after created using by example code below, not working... There is some way to do this?
async () => {
  const marketingClient = await venom.create('marketing');
  const salesClient = await venom.create('sales');
  const supportClient = await venom.create('support');
};

2 - How can i get status after read the QRCODE? I tried by onStateChange event and also not working.

Tks.

**Comment by joaosouz4** [comment]
you need to use the callback method
like this :
const supportClient = await venom.create('sessionName', qrCallback, (statusFind) => {
  console.log(statusFind);
})
  .then((client) => {
    start(client);
  })
  .catch((erro) => console.log(erro));

**Comment by bhavya32** [comment]
@joaosouz4 I believe he has left this issue. I vote to close it.
