### ISSUE TITLE
stuck on "Checking is logged..."

### ISSUE THREAD

**Issue by igiul667** [orkestral/venom#869]
## Description

Issue happens when starting venom library. After deleting tokens folder, and removing access from phone, it works, and asks for the QR code. If i stop it and try to start it again, it gets stuck on that. However, if i set the headless option to false, then it works every time

## Environment

- **Venom version(s):** 3.0.15
- **Browser:** Google Chrome 90.0.4430.93
- **OS:** Ubuntu server 20.4
- **Node version:**  Node 10

## Steps to Reproduce

1. Start the .js file that uses venom bot, it will ask for the qr code, scan it and everything works
2. Stop the execution (usnig ctrl+C), and start it again
3. now it stops on checking is logged
4. in the venom.create(...) method, set headless option to false
5. re start the node program
6. everything works

## Additional context / Screenshot
I need to run it in headless mode, as using graphics is very demanding on resources.

I don't think code is needed, as this issue has already been encountered other times. However if I have to send it, I will.

**Comment by robinhodemorais** [comment]
I have the same problem, I already elected and the problem persists

**Comment by thyagojcosta** [comment]
Também estou com esse problema. Começou hoje no final da tarde...

**Comment by haseebpvt** [comment]
I'm also facing this issue

**Comment by xbrunosousa** [comment]
Same here. Since 2h ago

**Comment by xbrunosousa** [comment]
Im removed files of `tokens` folder, and works now;

**Comment by xbrunosousa** [comment]
> Também estou com esse problema. Começou hoje no final da tarde...

Aqui, resolvi removendo o json da pasta tokens e reiniciando, @thyagojcosta. (Necessita re-emparelhar o WhatsApp Web)

**Comment by AkashWeybee** [comment]
Same Problem, 

We are in production mode.

So please resolve this issue as soon as possible

**Comment by thyagojcosta** [comment]
> > Também estou com esse problema. Começou hoje no final da tarde...
> 
> Aqui, resolvi removendo o json da pasta tokens e reiniciando, @thyagojcosta. (Necessita re-emparelhar o WhatsApp Web)

Mas tu consegue reconectar sem precisar excluir de novo o json? Pq eu só consigo conectar fazendo esse procedimento de exluir a sessão salva e fazer nova leitura do qrcode

**Comment by xbrunosousa** [comment]
> > > Também estou com esse problema. Começou hoje no final da tarde...
> > 
> > 
> > Aqui, resolvi removendo o json da pasta tokens e reiniciando, @thyagojcosta. (Necessita re-emparelhar o WhatsApp Web)
> 
> Mas tu consegue reconectar sem precisar excluir de novo o json? Pq eu só consigo conectar fazendo esse procedimento de exluir a sessão salva e fazer nova leitura do qrcode

O bug aqui só aconteceu na manhã de hoje. Não validava a sessão, ficava só checando. Excluí o json e li o qr novamente, daí conectou.

**Comment by thyagojcosta** [comment]
> > > > Também estou com esse problema. Começou hoje no final da tarde...
> > > 
> > > 
> > > Aqui, resolvi removendo o json da pasta tokens e reiniciando, @thyagojcosta. (Necessita re-emparelhar o WhatsApp Web)
> > 
> > Mas tu consegue reconectar sem precisar excluir de novo o json? Pq eu só consigo conectar fazendo esse procedimento de exluir a sessão salva e fazer nova leitura do qrcode
> 
> O bug aqui só aconteceu na manhã de hoje. Não validava a sessão, ficava só checando. Excluí o json e li o qr novamente, daí conectou.

O problema é justamente esse, ele n consegue se conectar usando o token salvo, sóquando faz nova leitura do qrcode. Provavelmente na próxima inicialização também vai dar problema de novo aí

**Comment by rafaelbellintani** [comment]
> > > > > Também estou com esse problema. Começou hoje no final da tarde...
> > > > 
> > > > 
> > > > Aqui, resolvi removendo o json da pasta tokens e reiniciando, @thyagojcosta. (Necessita re-emparelhar o WhatsApp Web)
> > > 
> > > 
> > > Mas tu consegue reconectar sem precisar excluir de novo o json? Pq eu só consigo conectar fazendo esse procedimento de exluir a sessão salva e fazer nova leitura do qrcode
> > 
> > 
> > O bug aqui só aconteceu na manhã de hoje. Não validava a sessão, ficava só checando. Excluí o json e li o qr novamente, daí conectou.
> 
> O problema é justamente esse, ele n consegue se conectar usando o token salvo, sóquando faz nova leitura do qrcode. Provavelmente na próxima inicialização também vai dar problema de novo aí

Realmente, após deletar o token e depois de muitas tentativas ele gera o QR CODE, ai você cadastra, mas após sair e tentar de novo não entra mais, só fazendo o mesmo processo.

**Comment by igiul667** [comment]
> Im removed files of `tokens` folder, and works now;

As others have already said, if you remove the token data, and scan the QR code it works, but if you try to restart the application that uses venom, it gets stuck again.

**Comment by rafaelbellintani** [comment]
> > Im removed files of `tokens` folder, and works now;
> 
> As others have already said, if you remove the token data, and scan the QR code it works, but if you try to restart the application that uses venom, it gets stuck again. Another way to "solve" the issue is to set the "headless" option to false, as it seems to solve all issues.

I tried this, but in my case doesn't work, the browser keep trying to reach the phone, i believe is something with the browser, direct in google chrome browser it worked, but in the browser when venom-bot takes control, connection keep reconnecting without success.

**Comment by igiul667** [comment]
I finally got it working, but I reverted back to version 3.0.13, so the issue seems to be related to some new update. It isn't the best solution, but it works.

**Comment by rafaelbellintani** [comment]
> I finally got it working, but I reverted back to version 3.0.13, so the issue seems to be related to some new update. It isn't the best solution, but it works.

This worked, thanks!

**Comment by robinhodemorais** [comment]
I returned the version to 3.0.13, but I'm having this error

[image: image.png]


Em ter., 4 de mai. de 2021 às 12:04, Rafael Bellintani <
***@***.***> escreveu:

**Comment by robinhodemorais** [comment]
node index.js
Unable to load the sleep module (no animations available)
http-Web rodando na porta:9000
- Criando sessão 21990516576_11111111111111
- Adicionando sessão
- Nova sessão: STARTING
- Iniciando sistema
- Checking for updates
- Checking for updates...
- Sistema iniciado!
- There is a new version available
┌──────────────────────────────────────────────────────┐
│                                                      │
│   There is a new version of Venom 3.0.13 ➜  3.0.15   │
│   Update your package by running:                    │
│                                                      │
│   > npm update venom-bot                             │
│                                                      │
└──────────────────────────────────────────────────────┘
For more info visit: https://github.com/orkestral/venom/blob/master/Update.md

- There is a new version available
- Waiting... checking the browser...
- There is a new version available
- Browser successfully opened
- There is a new version available
- checking headless...
- There is a new version available
- headless option is active, browser hidden
(node:7664) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:261:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext._evaluateInternal (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:215:61)
    at async ExecutionContext.evaluate (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rafaelbellintani** [comment]
> node index.js
> Unable to load the sleep module (no animations available)
> http-Web rodando na porta:9000
> 
> * Criando sessão 21990516576_11111111111111
> * Adicionando sessão
> * Nova sessão: STARTING
> * Iniciando sistema
> * Checking for updates
> * Checking for updates...
> * Sistema iniciado!
> * There is a new version available
>   ┌──────────────────────────────────────────────────────┐
>   │                                                      │
>   │   There is a new version of Venom 3.0.13 ➜  3.0.15   │
>   │   Update your package by running:                    │
>   │                                                      │
>   │   > npm update venom-bot                             │
>   │                                                      │
>   └──────────────────────────────────────────────────────┘
>   For more info visit: https://github.com/orkestral/venom/blob/master/Update.md
> * There is a new version available
> * Waiting... checking the browser...
> * There is a new version available
> * Browser successfully opened
> * There is a new version available
> * checking headless...
> * There is a new version available
> * headless option is active, browser hidden
>   (node:7664) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
>   at rewriteError (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:261:23)
>   at processTicksAndRejections (internal/process/task_queues.js:93:5)
>   at async ExecutionContext._evaluateInternal (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:215:61)
>   at async ExecutionContext.evaluate (D:\mywhats-api-node\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
>   (Use `node --trace-warnings ...` to show where the warning was created)
>   (node:7664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>   (node:7664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Make a new folder, and install venom-bot 3.0.13, and try again.

**Comment by igiul667** [comment]
also i think you should maybe open a new issue, as the problem seems different from the main one

**Comment by robinhodemorais** [comment]
oops sorry for the delay, but I had some difficulties, but I did what they
told me and it worked, I just saw that version 3.0.16 came out, I updated
it separately here and it seems to work correctly.




Em ter., 4 de mai. de 2021 às 18:33, igiul667 ***@***.***>
escreveu:

**Comment by haseebpvt** [comment]
Seems like the issue is fixed in the latest version _3.0.16_. I'm no longer having this issue now after updating the package.
