### ISSUE TITLE
autoClose must be undefined in order to work ?

### ISSUE THREAD

**Issue by antonio-couto** [orkestral/venom#87]
I must doing something wrong, its not a issue, its more a asking, i can only disable autoClose setting it to undefined, setting to false or 'false' is not working.

its my code, thanks for great job on this project!!!

  const options = {
    headless: true,
    devtools: false,
    useChrome: true,
    debug: false,
    logQR: true,
    browserArgs: [''],
    refreshQR: 1000,
    autoClose: undefined,
    disableSpins: true
  };

   venom.create('session', qrCallback, (statusFind) => {
    console.log(statusFind);
  }, options)
  .then((client) => {
    console.log('START START START START START ')
    start(client);
  })
  .catch((erro) => {
    console.log('ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ')
    console.log(erro)
  });

**Comment by RubberArchind** [comment]
it worked fine for me setting autoClose to false

**Comment by antonio-couto** [comment]
I will try again, but to be honest, now i am using autoclose = true.
Thanks a lot for your help!
