### ISSUE TITLE
ERROR : STATE not change 

### ISSUE THREAD

**Issue by grupobyb** [orkestral/venom#871]
Hello, good morning everyone, again we find the same STATUS error that VENOM does not recognize, could someone give us more information about how the states are crawling ??? so we collaborate with these things. doing reverse engineering on development having so many collaborators does not make sense.

TKS

**Comment by jonalan7** [comment]
If there is an error happening, be more specific!

**Comment by raulluque** [comment]
The same thing happens to me, it does not detect the logout from the cell phone.

statusFind where we close session from the cell phone does not delete the token.json.

It does not issue any state

**Comment by grupobyb** [comment]
Hello @jonalan7, thanks for your help, when we close the session from the cell phone, it does not send the closed state.
and we can't delete the token.

this had already happened in issue #522  #781 ,  Could you give us some help on how the crawler does to read these states.

so we can help every time Whastapp is updated.


En español 
Vimos que sos de lima, nosotros de argentina te dejo nuestro contacto jmframil o Raulluque_1989@hotmail.com -> Skype 
nos estamos volviendo con el tema de no saber como funciona el CRAWLER y vemos que cada vez que Whatsapp cambia tenemos que esperar que que se actualice Venom nos podrás dar una mano para entenderlo.

**Comment by jonalan7** [comment]
The token is always deleted automatically, there is no need to delete it manually! If he is not deleting, you must give permissions! @grupobyb

**Comment by jonalan7** [comment]
Google it! : Setting file and directory permissions linux

**Comment by grupobyb** [comment]
@jonalan7 gracias por seguir ayudándonos, la carpeta tokens y todas las demás carpetas tienen +777 no creo que sea un problema de permisos, ya que la función StatusFind no devuelve valor alguno cuando desconectas el celular.

![image_2021_05_04T15_08_06_871Z](https://user-images.githubusercontent.com/41598928/117026105-dbc20500-acd1-11eb-9e24-7fe6f1cff5f4.png)

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem
