### ISSUE TITLE
Failed to connect when there is a saved token in versions 3.0.14 and 3.0.15

### ISSUE THREAD

**Issue by casantos10** [orkestral/venom#872]
In versions 3.0.14 and 3.0.15, when a saved token already exists, it does not reconnect, it only displays the message "[instance: instanceName]: Checking is logged ...". I reinstalled version 3.0.13 and the problem did not occur.

**Comment by RafaelBini** [comment]
Same issue here!! It began to happen yesterday night

**Comment by AlanMartines** [comment]
also...

**Comment by thyagojcosta** [comment]
> In versions 3.0.14 and 3.0.15, when a saved token already exists, it does not reconnect, it only displays the message "[instance: instanceName]: Checking is logged ...". I reinstalled version 3.0.13 and the problem did not occur.

Volta pra versão 3.0.13 que vai funcionar. Teve uma issue igual a essa que foi fechada hoje e por enquanto essa é a solução

**Comment by AlanMartines** [comment]
Voltei para a 3.0.13 e não foi não... tive que configurar **headless: false** e usar o **xvfb** (emulador de tela/vídeo), solução paliativa mas foi assim...

**Comment by thyagojcosta** [comment]
> Voltei para a 3.0.13 e não foi não... tive que configurar **headless: false** e usar o **xvfb** (emulador de tela/vídeo), solução paliativa mas foi assim...

Aqui tá funcionando normal, inclusive em produção. Também testei em desenvolvimento com outros números e com outras sessões e funcionou tranquilo.

Se tu n fez ainda, apaga os módulos e reinstala tudo com a versão 3.0.13, eu não precisei fazer aqui, mas deve funcionar também

**Comment by casantos10** [comment]
> > In versions 3.0.14 and 3.0.15, when a saved token already exists, it does not reconnect, it only displays the message "[instance: instanceName]: Checking is logged ...". I reinstalled version 3.0.13 and the problem did not occur.
> 
> Volta pra versão 3.0.13 que vai funcionar. Teve uma issue igual a essa que foi fechada hoje e por enquanto essa é a solução

Eu fiz isso pra resolver, tanto é que foi assim que descobri qual versão estava funcionando. Coloquei a mensagem para relatar mesmo o problema. Valeu pelo retorno

**Comment by jonalan7** [comment]
This bug has been fixed! #780
