### ISSUE TITLE
Error conflict

### ISSUE THREAD

**Issue by lepokoloko** [orkestral/venom#878]
Error: Evaluation failed: Takeover called without conflict!
0|index  |     at ExecutionContext._evaluateInternal (/root/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|index  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|index  | Error: Evaluation failed: Takeover called without conflict!
0|index  |     at ExecutionContext._evaluateInternal (/root/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|index  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|index  | Error: Evaluation failed: Takeover called without conflict!
0|index  |     at ExecutionContext._evaluateInternal (/root/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|index  |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by antirek** [comment]
What do you do before this error? How repeat this problem?
