### ISSUE TITLE
How to add package and title on sticker

### ISSUE THREAD

**Issue by adonaidiofanes** [orkestral/venom#88]
How to i can add name of package and title for one sticker?

![image](https://user-images.githubusercontent.com/1199971/88712513-3baad000-d0f0-11ea-9120-37b97a1ac7f8.png)

**Comment by kaiserdj** [comment]
nothing new?

**Comment by Fredwuz** [comment]
It is possible to add a package and title when you edit the EXIF data of the webp file and for example, copy the data of an exiting sticker to the one you want the Titel and Sticker
