### ISSUE TITLE
Disconnected after 2 minutes of inactivity

### ISSUE THREAD

**Issue by LuizTokuhara** [orkestral/venom#891]
## Description

I am using the same code, just updated venom to the latest version.

## Environment

- **Venom version(s):** 3.0.16
- **Browser:** Chrome 90.0.4430.212
- **OS:** OSX 10.15.7
- **Node version:** Node v10.16.0

## Steps to Reproduce

Connect to bot (using json token) and do not interact.
After 2 minutes the bot is disconnected with status deviceNotConnected.

**Comment by TanderBolt** [comment]
closed because there are no other occurrences of this problem
