### ISSUE TITLE
Sending messages while the phone is disconnected

### ISSUE THREAD

**Issue by francisbreit** [orkestral/venom#895]
I am trying to create a way to send messages when the cell phone has been paired but has been temporarily disconnected. I tried it with guzzlehttp, but was unsuccessful. It would be a kind of queue to send messages when the cell phone reconnects again.

**Comment by rafaelbellintani** [comment]
try this code:

var connectionState = await client.getConnectionState(); 
                                if(connectionState == 'CONFLICT' || connectionState == 'DISCONNECTED'){
                                    await client.restartService();
                                    connectionState;
                                }  

If the status service has a problem, than connect again.

**Comment by AlexsandroZanella2** [comment]
O ideal é fazer isso no seu projeto. Você pode verificar se o status é CONECTADO, e se for, realiza o envio da fila e a limpa.
Mas a forma do @rafaelbellintani é perfeitamente válida
