### ISSUE TITLE
Deploy venom-bot umbler

### ISSUE THREAD

**Issue by robinhodemorais** [orkestral/venom#896]
Boa noite, gostaria de saber se alguém já tentou hospedar o venom-bot na umbler, pois quando vou iniciar a sessão ele dá erro

Aproveitando, vocês já conseguiram em qual hospedagem ?

> May 13 21:25:27   (node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> May 13 21:25:27   (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> May 13 21:25:27   (node:27) UnhandledPromiseRejectionWarning: Error no open browser....
> May 13 21:25:27   - Session name: undefined
> May 13 21:25:27   - Status da sessão: noOpenBrowser
> May 13 21:25:27   - Error no open browser....
> May 13 21:25:27   - You're up to date
> May 13 21:25:27   - Waiting... checking the browser...
> May 13 21:25:27   - You're up to date
> May 13 21:25:27   - You're up to date
> May 13 21:25:27   - Sistema iniciado!
> May 13 21:25:27   - Checking for updates...
> May 13 21:25:27   - Checking for updates
> May 13 21:25:27   - Iniciando sistema
> May 13 21:25:27   - Nova sessão: STARTING
> May 13 21:25:27   - Adicionando sessão
> May 13 21:25:27   - Criando sessão 21990516576_11111111111111
> May 13 21:25:15   - isConnected
> May 13 21:25:15   socketid AxCdn78G9o53GGqAAAAB
> May 13 21:23:49   - isConnected
> May 13 21:20:18   http-Web rodando na porta:3000
> May 13 21:20:17  
> May 13 21:20:17   > node index.js

**Comment by erickfrancis** [comment]
Boa noite amigo, você configurou o seu ambiente como? Utilizou docker?

**Comment by robinhodemorais** [comment]
Boa noite, não fiz padrão, criei o site com o nodejs e fiz o deploy conforme o passo a passo da umbler.
