### ISSUE TITLE
 Exported QR code is not recognized by the reader

### ISSUE THREAD

**Issue by izidorio** [orkestral/venom#9]
Following the example "Exporting QR", it is possible to successfully generate the QR code .png file.

However, when trying to scan the QR code of the generated image, it is not recognized.

It is only possible to scan the QR code through the terminal.

**Comment by orkestral** [comment]
You have to create a function to keep updating, because the image updates

**Comment by izidorio** [comment]
It worked. in fact the error was trying to read the image with the mac image viewer, as i'm using the night theme, so the image was without contrast. Anyone with this problem, try with a Qr reader first to read the generated qr.png image. If you are unable to read the likely error, there is a lack of contrast.

**Comment by edmagnini** [comment]
@izidorio, how you solve this contrast issue?
