### ISSUE TITLE
check status conection device/phone

### ISSUE THREAD

**Issue by gamadoleo** [orkestral/venom#90]
Good morning, I'm trying to send messages sent via server request, so far so good, but I'm having an impact on confirming that a poison bot from the api, as it keeps sending, shooting to sendText from venom and not used no alert if there is a moment of connection between the poison bot and the broken device, would you like some method to check how the connection / synchronization with the physical device is? Has as?

**Comment by jonalan7** [comment]
you already tried to use

```
// In case of being logged out of whatsapp web
// Force it to keep the current session
// State change
client.onStateChange((state) => {
  console.log(state);
  const conflits = [
    venom.SocketState.CONFLICT,
    venom.SocketState.UNPAIRED,
    venom.SocketState.UNLAUNCHED,
  ];
  if (conflits.includes(state)) {
    client.useHere();
  }
});
```

**Comment by gamadoleo** [comment]
ok
