### ISSUE TITLE
Doesn't reconnect automatically after restarting script

### ISSUE THREAD

**Issue by CyberSinister** [orkestral/venom#902]
Hi, I'm running venom in a simple script with forever to keep the service running. The problem started happing like 15 minutes before posting this issue. 

I removed the token from the tokens folder and logged out of venom from my phone. I logged back in just fine but when I stopped the script I had ran using the command ```node server.js``` and restarted it using ```forever start server.js```, I didn't get a response from my API. I stopped the forever service and ran the script again using node to see the console output and saw that it was stuck on "Checking is logged in". I tried everything but it just doesn't work after I restart the script. Only works when I freshly login

Can anyone help? I am really lost and really need to get out up and running. I would really appreciate any help.

**Comment by robinhodemorais** [comment]
I realized that yesterday too, I went back to version 3.0.13 and it is
working right now.





Em qua., 19 de mai. de 2021 às 11:33, CyberSinister <
***@***.***> escreveu:

**Comment by jonalan7** [comment]
**For lack of more information this issue will be closed!**
