### ISSUE TITLE
Is possible to send message in any group?

### ISSUE THREAD

**Issue by FelipeDeveloperFullStack** [orkestral/venom#910]
Is possible to send message in any group using 0000000000-0000000000@g.us?

EX Bellow:

`await client
  .sendText('0000000000-0000000000@g.us', '👋 Hello from venom!')
  .then((result) => {
    console.log('Result: ', result); 
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });`

The exemple above is working?

**Comment by TanderBolt** [comment]
yes is working
