### ISSUE TITLE
Possibility to send message without creating the chat

### ISSUE THREAD

**Issue by CAIOHOBORGHI** [orkestral/venom#92]
I've noticed that the methods sendMessageToId and sendText only works if there's an existent chat with the destination number. 

Is there any way to send it without creating the conversation? 

Thank you in advance,
Caio Borghi

**Comment by RubberArchind** [comment]
I think You can still use sendText () for that.

In case you want to broadcast to all users without conversation, you can use getAllChats () to get all chatIDs and store them in an array, then make iterations to it to send messages to each clientId.

clientId is basically (phone code + number + @ c.us / @ g.us)
