### ISSUE TITLE
Error deleteMessage

### ISSUE THREAD

**Issue by subzerowis** [orkestral/venom#921]
Trying to delete a message generates the following error!

![image](https://user-images.githubusercontent.com/84788964/119515812-8fa43680-bd4c-11eb-82ff-3e263d07edc9.png)

I noticed that the new codes are very similar to this project  [wapi.js](https://github.com/open-wa/wa-automate-nodejs/blob/master/src/lib/wapi.js#L1022)

**Comment by subzerowis** [comment]
![image](https://user-images.githubusercontent.com/84788964/119518081-9469ea00-bd4e-11eb-84f8-a6bb68427430.png)

**Comment by TanderBolt** [comment]
This problem is already solved in version 3.0.17 use an npm update venom-bot

**Comment by subzerowis** [comment]
I have the newest version! This is script error! You are copying other people's projects and not knowing how to put them in your project!

**Comment by arturromaorocha** [comment]
Estou com mesmo problema aqui.
