### ISSUE TITLE
Can we replace sharp? It has some compatibility issues in Windows 7

### ISSUE THREAD

**Issue by bhavya32** [orkestral/venom#922]
I know that sharp is just used for stickers which are not that important. I don't know why but I have some serious compatibility issues with sharp.  I tried uninstall reinstall, rebuild. It installs successfully but I get the following error when I fire up venom.
![Screenshot 2021-05-25 200816](https://user-images.githubusercontent.com/55047586/119547371-aaa99180-bdb2-11eb-8fd5-cdeae41dd228.jpg)

This is exclusive to 20% of windows 7 system I saw. I can't find a considerate solution. If you can,  please use some alternate package.

**Comment by jonalan7** [comment]
For lack of more information this issue will be closed!
