### ISSUE TITLE
Chrome CPU 2.7% to 8% each

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#928]
Hey guys, I'm running Venom with five Instances and I can see that each one consumes from 2.7 to 8% CPU, how can I improve it? I know the question is not issued to Venom, but I believe this question can help everyone on here.

**Comment by bhavya32** [comment]
+1

Sometimes my CPU usage reaches 20%.

**Comment by developerdevice** [comment]
> +1
> 
> Sometimes my CPU usage reaches 20%.

The best way to avoid CPU spending is:

1. Limit numbers of concurrents QRcode generating
2. Define autoclose (not zero)
3. Limit messages sent (like queue system)

For some reason when I changed from Chromium to Chrome, the CPU decreased by 2%. Remember keeping open only active user's browser (check doc).

This practices helped me a lot.
