### ISSUE TITLE
sendImageAsStickerGif Issue

### ISSUE THREAD

**Issue by RubberArchind** [orkestral/venom#93]
So i try that function and the results are not as expected.
![sample](https://user-images.githubusercontent.com/35050952/89025248-b4a86280-d350-11ea-851b-a126aca45886.gif)
Thats the real GIF i want to send.

![out](https://user-images.githubusercontent.com/35050952/89025398-fa652b00-d350-11ea-9578-c287af77e556.gif)
and that's what i got

**Comment by jonalan7** [comment]
Do all GIFs have the same problem?

**Comment by RubberArchind** [comment]
Yes

**Comment by Fredwuz** [comment]
a little late but this problem can be fixed if the gif is edited before so it has the 1:1 ratio else it will get glitchy like shown above its possible to add a transparent border to achieve the 1:1 ratio as shown in the gif below
![StickerVideo](https://user-images.githubusercontent.com/36505101/96054902-ff7f4400-0e82-11eb-860e-1014f11b4649.gif)
and here is the edited video
![Sticker](https://user-images.githubusercontent.com/36505101/96054913-09a14280-0e83-11eb-8f8c-ccb065ab7a9f.gif)

**Comment by RubberArchind** [comment]
@Fredwuz Wow thanks for your answer, I understand now where the problem is.
will close this issue.
