### ISSUE TITLE
An error accurred while using the function client.getGroupInfoFromInviteLink(InviteCode)

### ISSUE THREAD

**Issue by FelipeDeveloperFullStack** [orkestral/venom#931]
Hello!

When using the function client.getGroupInfoFromInviteLink(InviteCode), an error accurred after to connecting my smartphone.

How to solve it?

Image bellow.

![image](https://user-images.githubusercontent.com/9463295/119869444-9e2e5180-bef6-11eb-863e-597b9285e1ea.png)
![image](https://user-images.githubusercontent.com/9463295/119869864-1bf25d00-bef7-11eb-8859-f546d0d20c8b.png)

**Comment by jonalan7** [comment]
this problem has already been fixed
