### ISSUE TITLE
[Feat] Support browserless

### ISSUE THREAD

**Issue by jvkassi** [orkestral/venom#94]
Hello,

Thanks for all of your work.
Is it possible to support to remote connect to a browserless server.
I've done something like this in controllers/browser.ts.

```
  const browser = await puppeteer.connect({
    browserWSEndpoint:
      "wss://BROWSERLESS_BROWSER" + "?--user-data-dir=/tmp/jekas",
  });

  return browser;
```

Is there something else to take into contributions ?

**Comment by smashah** [comment]
@jvkassi you can use this out of the box in [@open-wa](https://github.com/open-wa/wa-automate-nodejs)  for now while you're waiting for these guys to copy paste the functionality to venom:

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#browserwsendpoint

**Comment by orkestral** [comment]
Vagabundo desses, postando merda aqui!
