### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by developerdevice** [orkestral/venom#946]
When a message is sent occurs the error below. Seems like Venom can't check number.

> 0|index  | Error: Evaluation failed: TypeError: Cannot read property 'match' of undefined
> 0|index  |     at new l (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:24974)
> 0|index  |     at new o (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:29593)
> 0|index  |     at Object.window.WAPI.window.WAPI.checkNumberStatus (/root/app/node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:64857)
> 0|index  |     at Object.window.WAPI.window.WAPI.sendExist (/root/app/node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:29722)
> 0|index  |     at Object.window.WAPI.window.WAPI.getNewMessageId (/root/app/node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:59967)
> 0|index  |     at Object.window.WAPI.window.WAPI.sendMessage (/root/app/node/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38163)
> 0|index  |     at ExecutionContext._evaluateInternal (/root/app/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
> 0|index  |     at process._tickCallback (internal/process/next_tick.js:68:7)

## Environment

- **Venom version(s):** [e.g. 3.0.17, 3.0.16...]
- **Browser:** [Chrome 88]
- **OS:** [Debian 10]
- **Node version:** [Node 14]

**Comment by tadeubarbosa** [comment]
Também estou com esse erro...

**Comment by Fibonacci-Solucoes-Ageis** [comment]
+1

**Comment by morebros2** [comment]
This problems seems to be happening with whatsapp web version 2.2121.5

**Comment by JuanCasian** [comment]
+1

**Comment by morebros2** [comment]
also, queryLinkPreview is broken

**Comment by xbrunosousa** [comment]
Same here

**Comment by jonalan7** [comment]
**This issue has been resolved**

**Comment by developerdevice** [comment]
> **This issue has been resolved**

Congrats! Working as expected, thank you.
