### ISSUE TITLE
How to close connection before the client read QR code

### ISSUE THREAD

**Issue by VictorCampelo** [orkestral/venom#95]
I would like to close a session before the client can read the QR code.

When i start the VenomBot calling `bot.create`, i would like to be able to finish this call on any time without call `client.close()` only when the client proprelly read the code.

**Comment by joaosouz4** [comment]
You can use the autoClose function, insert after the create function use the client function.

**Comment by VictorCampelo** [comment]
> You can use the autoClose function, insert after the create function use the client function.

Thanks a lot @ joao souz4. I solved my trouble using your tip and adding process.exit () at strategic points to my code.
