### ISSUE TITLE
deleteMessage delete only local message

### ISSUE THREAD

**Issue by antirek** [orkestral/venom#974]
## Description

deleteMessage delete only local message

also in docs 
`````
// Delete message (last parameter: delete only locally)
await client.deleteMessage('000000000000@c.us', ['false_000000000000@c.us_B70847EE89E22D20FB86ECA0C1B11609','false_000000000000@c.us_B70847EE89E22D20FB86ECA0C1B11777'],)
`````
what is last param only local? here https://github.com/orkestral/venom/blob/master/src/api/layers/controls.layer.ts#L169 I see only two params

## Environment

- **Venom version(s):** [3.0.18]
- **Browser:** [Chrome 90]
- **OS:** [Ubuntu 20.04]
- **Node version:** [Node 14]

**Comment by jonalan7** [comment]
**When you are using this function, are you clearing for both chats?**

**Comment by antirek** [comment]
@jonalan7 No. Only for local.

Local - it mean whatsapp account with venom. I send from venom to remote phone (on my another whatsapp account). I receive messageId. Then  client.deleteMessage('remotenumber@c.us', [messageId]) and local mesage was deleted (I see it on my phone which is paired with venom) but message on remote phone exist beyond. 

I try use wppconnect deleteMessage and it's work for local and remote message, clear both. Oh-m...

**Comment by antirek** [comment]
@jonalan7 do you know how fix it?

**Comment by bhavya32** [comment]
@antirek It was present in that file till June 3 when @jonalan7 removed it(don't know why).

https://github.com/orkestral/venom/commit/cc8ece0d004c3107e5c3c47f6b47ad97aa3899d4#diff-527a7f6e973e13c4fccf308c12a6f51d97e75277c9103b0c3333c07739e8f8f0L130

You can add that feature yourself.

**Comment by jonalan7** [comment]
I had some family issues! But I'll check it out!
