### ISSUE TITLE
Using this with Clusters?

### ISSUE THREAD

**Issue by HuskyCodez** [orkestral/venom#975]
Hi is it possible to use venom with node clusters if so, how?

**Comment by jonalan7** [comment]
**For clusters you can use a pm2 lib in ubuntu**

**Comment by HuskyCodez** [comment]
> **For clusters you can use a pm2 lib in ubuntu**

i figured out pm2 but with 2 instances if i stop one the other node doesn't let the bot to continue running seamlessly?

**Comment by antirek** [comment]
Your bot run on one whatsapp account, yes? You can't use clusters but you can use two instance with one auth token with realized failover. One of instance must be a master and other - slave. If slave check that master is down slave can run venom and reconnect. @HuskyCodez
