### ISSUE TITLE
Uncaught TypeError: Store.WapQuery.groupInviteInfo is not a function

### ISSUE THREAD

**Issue by vphelipe** [orkestral/venom#976]
Group invite info problem

**Comment by jonalan7** [comment]
what is the problem?

**Comment by vphelipe** [comment]
The function that returns data from a group link no longer works.

https://github.com/orkestral/venom/blob/master/src/lib/wapi/functions/get-group-info-from-invite-link.js

Line: var groupInfo = await Store.WapQuery.groupInviteInfo(inviteCode);

Erro:

Uncaught TypeError: Store.WapQuery.groupInviteInfo is not a function

**Comment by jonalan7** [comment]
This issue has been solved!

if you have any questions, pass the code after chat.whatsapp.com **"https://chat.whatsapp.com/H8gTeMgNVto5PiphIzriNs"**

in this case it would be this code: **"H8gTeMgNVto5PiphIzriNs"**
