### ISSUE TITLE
Error when I try to delete message: "Cannot read property 'erro' of undefined"

### ISSUE THREAD

**Issue by samuelnovaes** [orkestral/venom#977]
## Description

When I try to delete a message in version 3.0.18, I get the following error: `Cannot read property 'erro' of undefined`.

## Environment

- **Venom version(s):** 3.0.18
- **OS:** Linux Mint 20.1
- **Node version:** Node 14

## Steps to Reproduce

```javascript
client.deleteMessage(chatId, messageId);
```

## Log Output

```
(node:10231) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:218:47)
    at step (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:48:23)
    at Object.next (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:29:53)
    at fulfilled (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Your Code

```javascript
//DELETA UMA MENSAGEM
socket.on('deleteMessage', async (chatId, messageId) => {
	try {
		await client.deleteMessage(chatId, messageId);
	}
	catch (error) {
		console.error(error.stack);
	}
});
```

**Comment by antirek** [comment]
@samuelnovaes I don't understand: you try do forwardMessage or deleteMessage?

**Comment by samuelnovaes** [comment]
@antirek I'm trying to delete the message. I copied the wrong code, but I've corrected the description.

**Comment by jonalan7** [comment]
I'll take a look!

**Comment by eduardomazolini** [comment]
Same error.
messagesDelete
chatId 55119XXXXXXXX@c.us
messageId true_55119XXXXXXXX@c.us_CAB0F0387695282466659B059CADDF88


(node:88486) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (/XXX/node_modules/venom-bot/dist/api/layers/controls.layer.js:218:47)
    at step (/XXX/node_modules/venom-bot/dist/api/layers/controls.layer.js:48:23)
    at Object.next (/XXX/node_modules/venom-bot/dist/api/layers/controls.layer.js:29:53)
    at fulfilled (/XXXnode_modules/venom-bot/dist/api/layers/controls.layer.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:88486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by ViniciusSossela** [comment]
Same error with `sendText` function

```
(node:3065) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
    at Whatsapp.<anonymous> (/Users/viniciussossella/node_modules/venom-bot/dist/api/layers/sender.layer.js:164:47)
    at step (/Users/viniciussossella/node_modules/venom-bot/dist/api/layers/sender.layer.js:48:23)
    at Object.next (/Users/viniciussossella/node_modules/venom-bot/dist/api/layers/sender.layer.js:29:53)
    at fulfilled (/Users/viniciussossella/node_modules/venom-bot/dist/api/layers/sender.layer.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:3065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by alex3o0** [comment]
> 
> ## Description
> 
> When I try to delete a message in version 3.0.18, I get the following error: `Cannot read property 'erro' of undefined`.
> ## Environment
> 
>     * **Venom version(s):** 3.0.18
> 
>     * **OS:** Linux Mint 20.1
> 
>     * **Node version:** Node 14
> 
> 
> ## Steps to Reproduce
> 
> ```js
> client.deleteMessage(chatId, messageId);
> ```
> 
> ## Log Output
> 
> ```
> (node:10231) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
>     at Whatsapp.<anonymous> (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:218:47)
>     at step (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:48:23)
>     at Object.next (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:29:53)
>     at fulfilled (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:20:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> ```
> 
> ## Your Code
> 
> ```js
> //DELETA UMA MENSAGEM
> socket.on('deleteMessage', async (chatId, messageId) => {
> 	try {
> 		await client.deleteMessage(chatId, messageId);
> 	}
> 	catch (error) {
> 		console.error(error.stack);
> 	}
> });
> ```

Dosen't `deleteMessage` returns a Promise object which needs a `then` and `catch` calls?

**Comment by rogereur** [comment]
Same error here. Any solution?

`(node:16792) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read pr
 of undefined                                                                                     
    at Object.window.WAPI.window.WAPI.sendMessage (C:\Users\rogel\Downloads\whatsBot-Wati\node_mod
ot\dist\lib\wapi\wapi.js:1:36106)                                                                 
    at __puppeteer_evaluation_script__:3:53                                                       
    at ExecutionContext._evaluateInternal (C:\Users\rogel\Downloads\whatsBot-Wati\node_modules\pup
js\puppeteer\common\ExecutionContext.js:217:19)                                                   
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                           
    at async ExecutionContext.evaluate (C:\Users\rogel\Downloads\whatsBot-Wati\node_modules\puppet
puppeteer\common\ExecutionContext.js:106:16)                                                      
(Use `node --trace-warnings ...` to show where the warning was created)                           
(node:16792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated 
rowing inside of an async function without a catch block, or by rejecting a promise which was not 
 .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhan
ons=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:16792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the fut
 rejections that are not handled will terminate the Node.js process with a non-zero exit code.    
                                                                                                  `

**Comment by samuelnovaes** [comment]
> > ## Description
> > When I try to delete a message in version 3.0.18, I get the following error: `Cannot read property 'erro' of undefined`.
> > ## Environment
> > ```
> > * **Venom version(s):** 3.0.18
> > 
> > * **OS:** Linux Mint 20.1
> > 
> > * **Node version:** Node 14
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Steps to Reproduce
> > ```js
> > client.deleteMessage(chatId, messageId);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Log Output
> > ```
> > (node:10231) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'erro' of undefined
> >     at Whatsapp.<anonymous> (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:218:47)
> >     at step (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:48:23)
> >     at Object.next (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:29:53)
> >     at fulfilled (/home/samuel/Documentos/talkone-ws/node_modules/venom-bot/dist/api/layers/controls.layer.js:20:58)
> >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Your Code
> > ```js
> > //DELETA UMA MENSAGEM
> > socket.on('deleteMessage', async (chatId, messageId) => {
> > 	try {
> > 		await client.deleteMessage(chatId, messageId);
> > 	}
> > 	catch (error) {
> > 		console.error(error.stack);
> > 	}
> > });
> > ```
> 
> Dosen't `deleteMessage` returns a Promise object which needs a `then` and `catch` calls?

Yes. But it can be used with try and catch with async functions
