### ISSUE TITLE
client.getGroupInviteLink doesn't work

### ISSUE THREAD

**Issue by ClaraProgramadora** [orkestral/venom#978]
## Description

Function getGroupInviteLink returns an invalid link: 
`https://chat.whatsapp.com/new Promise((t,r)=>{var a=new V.default(e);a.onSend=t,a.onDrop=r,this.sendQueue.push(a),this.flushQueue()})
.then(e=>200===e.status?e.code:Promise.reject(new r.ServerStatusCodeError(e.status)))`

The code doesn't execute.

## Environment

- **Venom version(s):** 3.0.18
- **Browser:** chrome 91
- **OS:** OSX 10.15.6
- **Node version:** Node 12.16.3

## Steps to Reproduce

1. client.getGroupInviteLink(idGroup);

**Comment by jonalan7** [comment]
This issue has been solved!
