### ISSUE TITLE
Envio do Qrcode

### ISSUE THREAD

**Issue by leobevi** [orkestral/venom#98]
Olá, tenho a seguinte situação,
estou tentando fazer a autenticação pela minha aplicação,

o QRcode chega para mim, eu faço a leitura mas continua pedindo o qr-code quando inicio o projeto.
o que posso estar fazendo de errado?

  venom.create((base64Qr, asciiQR) => {
      startExpress('',base64Qr);
  });  
  
function startExpress(whats,qrc){
  app.get('/', function(req, res){
    if(whats===''){
      res.send(qrc);
    }else{
      whats.sendMessageToId('55xxxxxxx@c.us', 'Acesso via web');  
    }
  });  
}

**Comment by joaosouz4** [comment]
In the documentation that we describe how to export or qr code
like this:
```
const fs = require('fs');

// Second create() parameter is the QR callback
venom.create('sessionMarketing', (base64Qr, asciiQR) => {
  // To log the QR in the terminal
  console.log(asciiQR);

  // To write it somewhere else in a file
  exportQR(base64Qr, 'marketing-qr.png');
});

// Writes QR in specified path
function exportQR(qrCode, path) {
  qrCode = qrCode.replace('data:image/png;base64,', '');
  const imageBuffer = Buffer.from(qrCode, 'base64');

  // Creates 'marketing-qr.png' file
  fs.writeFileSync(path, imageBuffer);
}
```

**Comment by leobevi** [comment]
OK Joao thanks for your attention!

**Comment by curruwilla** [comment]
@leobevi você ta usando em algum host já? porque comigo em localhost funciona, mas nos host da erro..
