### ISSUE TITLE
Using Venom in production

### ISSUE THREAD

**Issue by LeandroParisi** [orkestral/venom#982]
Has anyone ever used Venom bot in a production app? Do you know if it's too heavy for say, a basic AWS with for example 1GB ram?

---

- Documentation: https://orkestral.github.io/venom/
- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
- Also have a look at the readme for more information on how to get support:
  https://github.com/babel/babel/blob/master/README.md

**Comment by jonalan7** [comment]
For lack of more information this issue will be closed!

**Comment by HuskyCodez** [comment]
> Has anyone ever used Venom bot in a production app? Do you know if it's too heavy for say, a basic AWS with for example 1GB ram?
> 
> * Documentation: https://orkestral.github.io/venom/
> * Discord: https://discord.gg/qCJ95FVbzR
> * WhatsApp Group (Paid): (Request Access)[https://web.whatsapp.com/send?phone=556181590153&text=I%20want%20access%20to%20the%20WhatsApp%20Venom%20support%20group]
> * Also have a look at the readme for more information on how to get support:
>   https://github.com/babel/babel/blob/master/README.md

im not exactly running it in mass production but for my class group chat im using digital oceans 4gb 20$ plan and it works pretty fine
