### ISSUE TITLE
client.livelocation does not return any value

### ISSUE THREAD

**Issue by Dlbraganca** [orkestral/venom#989]
I'm using the current version 3.0.18 and i had this issue that client.onLiveLocation doesn't return any value. I tried to downgrade to the version 3.0.5 and it did not work either.

**Comment by alex3o0** [comment]
Is your testing phone client allowing to its whatsapp app to share its location to your bot?

**Comment by Interspock** [comment]
Same problem, the event onLiveLocation never gets fired.
The live location I send to the bot is trapped by the "onMessage" event. Not by the onLiveLocation

Any idea?

The snippet:

	client.onLiveLocation(here-my-testing-phone-number@c.us, (liveLocation) => {
	   console.log(liveLocation);
	});
