### ISSUE TITLE
if onStateChange not connected, reconnect?

### ISSUE THREAD

**Issue by HuskyCodez** [orkestral/venom#990]
is there any function to reconnect the client if the state is not "connected"

**Comment by sebaev** [comment]
Check if this is what you need!

```
client.onStateChange((state) => {
    console.log('New state: ', state);
    // Force whatsapp take over
    if ('CONFLICT'.includes(state)) client.useHere();
    // Detect disconnect on whatsapp
    if ('UNPAIRED'.includes(state)) console.log('logout');
  });

client.onStreamChange((state) => {
    let time = 0;
    console.log('State Connection Stream: ' + state);
    clearTimeout(time);
    if (state === 'DISCONNECTED' || state === 'SYNCING') {
      time = setTimeout(() => {
        client.close();
      }, 80000);
    }
  });
```

**Comment by HuskyCodez** [comment]
> Check if this is what you need!
> 
> ```
> client.onStateChange((state) => {
>     console.log('New state: ', state);
>     // Force whatsapp take over
>     if ('CONFLICT'.includes(state)) client.useHere();
>     // Detect disconnect on whatsapp
>     if ('UNPAIRED'.includes(state)) console.log('logout');
>   });
> 
> client.onStreamChange((state) => {
>     let time = 0;
>     console.log('State Connection Stream: ' + state);
>     clearTimeout(time);
>     if (state === 'DISCONNECTED' || state === 'SYNCING') {
>       time = setTimeout(() => {
>         client.close();
>       }, 80000);
>     }
>   });
> ```

yes it is, thanks!
