### ISSUE TITLE
Change the name of groups

### ISSUE THREAD

**Issue by matheushss1** [orkestral/venom#992]
I'm tryin' to set the name of the groups and I can't find out which call to Store or WAPI I need to do.
I've verified that a simple `window.WAPI.setGroupIcon()` changes the picture of the group and a call to `window.Store.WapQuery.setGroupDescription()` changes the description of the group but I can't find out how to change the name of the groups.

**Comment by jonalan7** [comment]
I will be putting new group functions in the future! Just wait!
