### ISSUE TITLE
BUG When I send a contact with method sendContactVCard

### ISSUE THREAD

**Issue by AdllerSimas** [orkestral/venom#996]
## Description

When i try to send a contact, i get an error:

Error: Evaluation failed: TypeError: c.waitForPrep is not a function
0|chat     |     at https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:424136
0|chat     |     at q (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333948)
0|chat     |     at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333529)
0|chat     |     at ExecutionContext._evaluateInternal (/myFile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|chat     |     at runMicrotasks (<anonymous>)
0|chat     |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
0|chat     |     at async ExecutionContext.evaluate (myFile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:1

## Environment

- **Venom version(s):** [3.0.16]

## Steps to Reproduce

When I use the method client.sendContactVcard()

## Log Output

Error: Evaluation failed: TypeError: c.waitForPrep is not a function
0|chat     |     at https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:424136
0|chat     |     at q (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333948)
0|chat     |     at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333529)
0|chat     |     at ExecutionContext._evaluateInternal (/myFile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
0|chat     |     at runMicrotasks (<anonymous>)
0|chat     |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
0|chat     |     at async ExecutionContext.evaluate (myFile/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:1.

**Comment by felipelyp** [comment]
**I'm having problems too**

Já testou em versão anterior do Venom Bot?

**Comment by AdllerSimas** [comment]
I used version 3.0.16 for over 1 month and it was working correctly. I sent contacts normally, no problems. But from one day to another it stopped working, generating the problem I mentioned

**Comment by jonalan7** [comment]
**This problem has been fixed! Wait for new updates!**
